within BIOMD633;
model BIOMD0000000633 "Bulik2016 - Regulation of hepatic glucose metabolism" annotation(Documentation(info="<annotation>
      <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	
	
	
	
	
	
      </rdf:RDF>
    </annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_cyto elmt_cyto;
    Class_elmt_ext elmt_ext;
    Class_elmt_er elmt_er;
    Class_elmt_mito elmt_mito;

    equation
        Params.elmt_p = elmt_cyto.elmt_p;
        Params.elmt_oa_mito = elmt_mito.elmt_oa_mito;
        Params.elmt_glyglc = elmt_cyto.elmt_glyglc;
        Params.elmt_gdp = elmt_cyto.elmt_gdp;
        Params.elmt_pp = elmt_cyto.elmt_pp;
        Params.elmt_adp_mito = elmt_mito.elmt_adp_mito;
        Params.elmt_utp = elmt_cyto.elmt_utp;
        Params.elmt_fru6p = elmt_cyto.elmt_fru6p;
        Params.elmt_p_mito = elmt_mito.elmt_p_mito;
        Params.elmt_h = elmt_cyto.elmt_h;
        Params.elmt_glc1p = elmt_cyto.elmt_glc1p;
        Params.elmt_glc_er = elmt_er.elmt_glc_er;
        Params.elmt_bpg13 = elmt_cyto.elmt_bpg13;
        Params.elmt_lac_ext = elmt_ext.elmt_lac_ext;
        Params.elmt_co2 = elmt_cyto.elmt_co2;
        Params.elmt_amp = elmt_cyto.elmt_amp;
        Params.elmt_udp = elmt_cyto.elmt_udp;
        Params.elmt_cit = elmt_cyto.elmt_cit;
        Params.elmt_fru16bp = elmt_cyto.elmt_fru16bp;
        Params.elmt_udpglc = elmt_cyto.elmt_udpglc;
        Params.elmt_mal = elmt_cyto.elmt_mal;
        Params.elmt_gap = elmt_cyto.elmt_gap;
        Params.elmt_glc6p = elmt_cyto.elmt_glc6p;
        Params.elmt_dhap = elmt_cyto.elmt_dhap;
        Params.elmt_mal_mito = elmt_mito.elmt_mal_mito;
        Params.elmt_nadh_mito = elmt_mito.elmt_nadh_mito;
        Params.elmt_glc_ext = elmt_ext.elmt_glc_ext;
        Params.elmt_fru26bp = elmt_cyto.elmt_fru26bp;
        Params.elmt_glc6p_er = elmt_er.elmt_glc6p_er;
        Params.elmt_nad_mito = elmt_mito.elmt_nad_mito;
        Params.elmt_co2_mito = elmt_mito.elmt_co2_mito;
        Params.elmt_pep_mito = elmt_mito.elmt_pep_mito;
        Params.elmt_lac = elmt_cyto.elmt_lac;
        Params.elmt_pyr = elmt_cyto.elmt_pyr;
        Params.elmt_pyr_mito = elmt_mito.elmt_pyr_mito;
        Params.elmt_nad = elmt_cyto.elmt_nad;
        Params.elmt_h_mito = elmt_mito.elmt_h_mito;
        Params.elmt_glc = elmt_cyto.elmt_glc;
        Params.elmt_atp = elmt_cyto.elmt_atp;
        Params.elmt_atp_mito = elmt_mito.elmt_atp_mito;
        Params.elmt_gtp_mito = elmt_mito.elmt_gtp_mito;
        Params.elmt_pg3 = elmt_cyto.elmt_pg3;
        Params.elmt_pep = elmt_cyto.elmt_pep;
        Params.elmt_pg2 = elmt_cyto.elmt_pg2;
        Params.elmt_nadh = elmt_cyto.elmt_nadh;
        Params.elmt_gdp_mito = elmt_mito.elmt_gdp_mito;
        Params.elmt_gtp = elmt_cyto.elmt_gtp;
        Params.elmt_oa = elmt_cyto.elmt_oa;
        Params.elmt_adp = elmt_cyto.elmt_adp;
        Reacs.elmt_v_TPI = Params.elmt_v_TPI;
        Reacs.elmt_v_GLUT2 = Params.elmt_v_GLUT2;
        Reacs.elmt_v_PC = Params.elmt_v_PC;
        Reacs.elmt_v_LDH = Params.elmt_v_LDH;
        Reacs.elmt_v_PEPCK = Params.elmt_v_PEPCK;
        Reacs.elmt_v_MDH = Params.elmt_v_MDH;
        Reacs.elmt_v_NDK_GTP_mito = Params.elmt_v_NDK_GTP_mito;
        Reacs.elmt_v_NDK_UTP = Params.elmt_v_NDK_UTP;
        Reacs.elmt_v_MDH_mito = Params.elmt_v_MDH_mito;
        Reacs.elmt_v_EN = Params.elmt_v_EN;
        Reacs.elmt_v_GP = Params.elmt_v_GP;
        Reacs.elmt_v_PyrT = Params.elmt_v_PyrT;
        Reacs.elmt_v_GS = Params.elmt_v_GS;
        Reacs.elmt_v_FBP2 = Params.elmt_v_FBP2;
        Reacs.elmt_v_GPI = Params.elmt_v_GPI;
        Reacs.elmt_v_MALT = Params.elmt_v_MALT;
        Reacs.elmt_v_UGT = Params.elmt_v_UGT;
        Reacs.elmt_v_PK = Params.elmt_v_PK;
        Reacs.elmt_v_FBP1 = Params.elmt_v_FBP1;
        Reacs.elmt_v_PGK = Params.elmt_v_PGK;
        Reacs.elmt_v_G6PT_ER = Params.elmt_v_G6PT_ER;
        Reacs.elmt_v_PEPCK_mito = Params.elmt_v_PEPCK_mito;
        Reacs.elmt_v_LACT = Params.elmt_v_LACT;
        Reacs.elmt_v_GAPDH = Params.elmt_v_GAPDH;
        Reacs.elmt_v_ALD = Params.elmt_v_ALD;
        Reacs.elmt_v_PGM = Params.elmt_v_PGM;
        Reacs.elmt_v_G6P_ER = Params.elmt_v_G6P_ER;
        Reacs.elmt_v_G1PI = Params.elmt_v_G1PI;
        Reacs.elmt_v_PyrMalT = Params.elmt_v_PyrMalT;
        Reacs.elmt_v_GLCT_ER = Params.elmt_v_GLCT_ER;
        Reacs.elmt_v_GK = Params.elmt_v_GK;
        Reacs.elmt_v_PFK2 = Params.elmt_v_PFK2;
        Reacs.elmt_v_NDK_GTP = Params.elmt_v_NDK_GTP;
        Reacs.elmt_v_PFK1 = Params.elmt_v_PFK1;
        Reacs.elmt_v_PEPT = Params.elmt_v_PEPT;
        elmt_mito.elmt_product41 = Reacs.elmt_product41;
        elmt_mito.elmt_reactant40 = Reacs.elmt_reactant40;
        elmt_mito.elmt_product51 = Reacs.elmt_product51;
        elmt_mito.elmt_reactant30 = Reacs.elmt_reactant30;
        elmt_mito.elmt_reactant52 = Reacs.elmt_reactant52;
        elmt_mito.elmt_product50 = Reacs.elmt_product50;
        elmt_mito.elmt_product71 = Reacs.elmt_product71;
        elmt_mito.elmt_reactant42 = Reacs.elmt_reactant42;
        elmt_mito.elmt_PyrT = Reacs.elmt_PyrT;
        elmt_mito.elmt_product43 = Reacs.elmt_product43;
        elmt_mito.elmt_reactant48 = Reacs.elmt_reactant48;
        elmt_mito.elmt_MDH_mito = Reacs.elmt_MDH_mito;
        elmt_mito.elmt_reactant49 = Reacs.elmt_reactant49;
        elmt_mito.elmt_reactant66 = Reacs.elmt_reactant66;
        elmt_mito.elmt_reactant34 = Reacs.elmt_reactant34;
        elmt_mito.elmt_PC = Reacs.elmt_PC;
        elmt_mito.elmt_PEPT = Reacs.elmt_PEPT;
        elmt_mito.elmt_PEPCK_mito = Reacs.elmt_PEPCK_mito;
        elmt_mito.elmt_PyrMalT = Reacs.elmt_PyrMalT;
        elmt_mito.elmt_product35 = Reacs.elmt_product35;
        elmt_mito.elmt_product68 = Reacs.elmt_product68;
        elmt_mito.elmt_MALT = Reacs.elmt_MALT;
        elmt_mito.elmt_NDK_GTP_mito = Reacs.elmt_NDK_GTP_mito;
        elmt_er.elmt_G6P_ER = Reacs.elmt_G6P_ER;
        elmt_er.elmt_product23 = Reacs.elmt_product23;
        elmt_er.elmt_product12 = Reacs.elmt_product12;
        elmt_er.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_er.elmt_GLCT_ER = Reacs.elmt_GLCT_ER;
        elmt_er.elmt_G6PT_ER = Reacs.elmt_G6PT_ER;
        elmt_er.elmt_product17 = Reacs.elmt_product17;
        elmt_cyto.elmt_product73 = Reacs.elmt_product73;
        elmt_cyto.elmt_PGM = Reacs.elmt_PGM;
        elmt_cyto.elmt_PGK = Reacs.elmt_PGK;
        elmt_cyto.elmt_product33 = Reacs.elmt_product33;
        elmt_cyto.elmt_product76 = Reacs.elmt_product76;
        elmt_cyto.elmt_G1PI = Reacs.elmt_G1PI;
        elmt_cyto.elmt_product31 = Reacs.elmt_product31;
        elmt_cyto.elmt_NDK_GTP = Reacs.elmt_NDK_GTP;
        elmt_cyto.elmt_reactant44 = Reacs.elmt_reactant44;
        elmt_cyto.elmt_GLCT_ER = Reacs.elmt_GLCT_ER;
        elmt_cyto.elmt_reactant45 = Reacs.elmt_reactant45;
        elmt_cyto.elmt_PEPT = Reacs.elmt_PEPT;
        elmt_cyto.elmt_NDK_UTP = Reacs.elmt_NDK_UTP;
        elmt_cyto.elmt_PyrMalT = Reacs.elmt_PyrMalT;
        elmt_cyto.elmt_PFK1 = Reacs.elmt_PFK1;
        elmt_cyto.elmt_PFK2 = Reacs.elmt_PFK2;
        elmt_cyto.elmt_product27 = Reacs.elmt_product27;
        elmt_cyto.elmt_product26 = Reacs.elmt_product26;
        elmt_cyto.elmt_LDH = Reacs.elmt_LDH;
        elmt_cyto.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_cyto.elmt_product25 = Reacs.elmt_product25;
        elmt_cyto.elmt_PK = Reacs.elmt_PK;
        elmt_cyto.elmt_product69 = Reacs.elmt_product69;
        elmt_cyto.elmt_TPI = Reacs.elmt_TPI;
        elmt_cyto.elmt_PEPCK = Reacs.elmt_PEPCK;
        elmt_cyto.elmt_product29 = Reacs.elmt_product29;
        elmt_cyto.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_cyto.elmt_reactant58 = Reacs.elmt_reactant58;
        elmt_cyto.elmt_reactant54 = Reacs.elmt_reactant54;
        elmt_cyto.elmt_EN = Reacs.elmt_EN;
        elmt_cyto.elmt_reactant11 = Reacs.elmt_reactant11;
        elmt_cyto.elmt_reactant56 = Reacs.elmt_reactant56;
        elmt_cyto.elmt_product37 = Reacs.elmt_product37;
        elmt_cyto.elmt_product39 = Reacs.elmt_product39;
        elmt_cyto.elmt_reactant62 = Reacs.elmt_reactant62;
        elmt_cyto.elmt_reactant20 = Reacs.elmt_reactant20;
        elmt_cyto.elmt_reactant64 = Reacs.elmt_reactant64;
        elmt_cyto.elmt_product55 = Reacs.elmt_product55;
        elmt_cyto.elmt_PyrT = Reacs.elmt_PyrT;
        elmt_cyto.elmt_product10 = Reacs.elmt_product10;
        elmt_cyto.elmt_reactant60 = Reacs.elmt_reactant60;
        elmt_cyto.elmt_product53 = Reacs.elmt_product53;
        elmt_cyto.elmt_GPI = Reacs.elmt_GPI;
        elmt_cyto.elmt_GLUT2 = Reacs.elmt_GLUT2;
        elmt_cyto.elmt_reactant28 = Reacs.elmt_reactant28;
        elmt_cyto.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_cyto.elmt_ALD = Reacs.elmt_ALD;
        elmt_cyto.elmt_reactant67 = Reacs.elmt_reactant67;
        elmt_cyto.elmt_reactant24 = Reacs.elmt_reactant24;
        elmt_cyto.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_cyto.elmt_UGT = Reacs.elmt_UGT;
        elmt_cyto.elmt_product47 = Reacs.elmt_product47;
        elmt_cyto.elmt_product46 = Reacs.elmt_product46;
        elmt_cyto.elmt_G6PT_ER = Reacs.elmt_G6PT_ER;
        elmt_cyto.elmt_reactant72 = Reacs.elmt_reactant72;
        elmt_cyto.elmt_product63 = Reacs.elmt_product63;
        elmt_cyto.elmt_product8 = Reacs.elmt_product8;
        elmt_cyto.elmt_LACT = Reacs.elmt_LACT;
        elmt_cyto.elmt_reactant74 = Reacs.elmt_reactant74;
        elmt_cyto.elmt_product61 = Reacs.elmt_product61;
        elmt_cyto.elmt_product6 = Reacs.elmt_product6;
        elmt_cyto.elmt_reactant75 = Reacs.elmt_reactant75;
        elmt_cyto.elmt_GK = Reacs.elmt_GK;
        elmt_cyto.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_cyto.elmt_reactant5 = Reacs.elmt_reactant5;
        elmt_cyto.elmt_GAPDH = Reacs.elmt_GAPDH;
        elmt_cyto.elmt_reactant70 = Reacs.elmt_reactant70;
        elmt_cyto.elmt_product65 = Reacs.elmt_product65;
        elmt_cyto.elmt_MDH = Reacs.elmt_MDH;
        elmt_cyto.elmt_product21 = Reacs.elmt_product21;
        elmt_cyto.elmt_reactant7 = Reacs.elmt_reactant7;
        elmt_cyto.elmt_reactant36 = Reacs.elmt_reactant36;
        elmt_cyto.elmt_product1 = Reacs.elmt_product1;
        elmt_cyto.elmt_reactant38 = Reacs.elmt_reactant38;
        elmt_cyto.elmt_GS = Reacs.elmt_GS;
        elmt_cyto.elmt_GP = Reacs.elmt_GP;
        elmt_cyto.elmt_reactant32 = Reacs.elmt_reactant32;
        elmt_cyto.elmt_product4 = Reacs.elmt_product4;
        elmt_cyto.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_cyto.elmt_product2 = Reacs.elmt_product2;
        elmt_cyto.elmt_product59 = Reacs.elmt_product59;
        elmt_cyto.elmt_product15 = Reacs.elmt_product15;
        elmt_cyto.elmt_MALT = Reacs.elmt_MALT;
        elmt_cyto.elmt_product13 = Reacs.elmt_product13;
        elmt_cyto.elmt_product57 = Reacs.elmt_product57;
        elmt_cyto.elmt_FBP2 = Reacs.elmt_FBP2;
        elmt_cyto.elmt_product19 = Reacs.elmt_product19;
        elmt_cyto.elmt_FBP1 = Reacs.elmt_FBP1;

end BIOMD0000000633;
