within BIOMD526;
class Reactions

    input Real elmt_p18;
    input Real elmt_kD216trans_p55;
    input Real elmt_kDISC;
    input Real elmt_kD216trans_p43;
    input Real elmt_p55free;
    input Real elmt_kD216;
    input Real elmt_kBid;
    input Real elmt_PrNES_mCherry;
    input Real elmt_Bid;
    input Real elmt_koff_FADD;
    input Real elmt_kD374;
    input Real elmt_kon_FADD;
    input Real elmt_cell;
    input Real elmt_DISC;
    input Real elmt_CD95act;
    input Real elmt_kD374trans_p43;
    input Real elmt_p43;
    input Real elmt_kD374trans_p55;
    input Real elmt_p30;
    input Real elmt_kD374probe;
    input Real elmt_PrER_mGFP;
    input Real elmt_DISCp55;
    input Real elmt_kdiss_p18;
    input Real elmt_FADD;

    Real elmt_reaction_3(unit = "") "";
    Real elmt_reactant4 "";
    Real elmt_product6 "";
    Real elmt_reactant5 "";
    Real elmt_reaction_4(unit = "") "";
    Real elmt_product8 "";
    Real elmt_reactant7 "";
    Real elmt_reaction_1(unit = "") "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_reaction_2(unit = "") "";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_reaction_16(unit = "") "";
    Real elmt_product38 "";
    Real elmt_reactant37 "";
    Real elmt_reaction_17(unit = "") "";
    Real elmt_product40 "";
    Real elmt_reactant39 "";
    Real elmt_reaction_9(unit = "") "";
    Real elmt_reactant19 "";
    Real elmt_product21 "";
    Real elmt_product20 "";
    Real elmt_reaction_14(unit = "") "";
    Real elmt_reactant31 "";
    Real elmt_product33 "";
    Real elmt_product32 "";
    Real elmt_reaction_15(unit = "") "";
    Real elmt_product36 "";
    Real elmt_product35 "";
    Real elmt_reactant34 "";
    Real elmt_reaction_7(unit = "") "";
    Real elmt_product15 "";
    Real elmt_product14 "";
    Real elmt_reactant13 "";
    Real elmt_reaction_8(unit = "") "";
    Real elmt_reactant16 "";
    Real elmt_product18 "";
    Real elmt_product17 "";
    Real elmt_reaction_5(unit = "") "";
    Real elmt_product10 "";
    Real elmt_reactant9 "";
    Real elmt_reaction_18(unit = "") "";
    Real elmt_reactant41 "";
    Real elmt_product43 "";
    Real elmt_product42 "";
    Real elmt_reaction_6(unit = "") "";
    Real elmt_product12 "";
    Real elmt_reactant11 "";
    Real elmt_reaction_19(unit = "") "";
    Real elmt_product45 "";
    Real elmt_product46 "";
    Real elmt_reactant44 "";
    Real elmt_reaction_12(unit = "") "";
    Real elmt_product27 "";
    Real elmt_reactant26 "";
    Real elmt_reaction_13(unit = "") "";
    Real elmt_product30 "";
    Real elmt_reactant28 "";
    Real elmt_product29 "";
    Real elmt_reaction_10(unit = "") "";
    Real elmt_product23 "";
    Real elmt_reactant22 "";
    Real elmt_reaction_11(unit = "") "";
    Real elmt_product25 "";
    Real elmt_reactant24 "";


    initial equation
        elmt_product30 = 1.0;
        elmt_reactant41 = 1.0;
        elmt_product12 = 1.0;
        elmt_product33 = 1.0;
        elmt_product32 = 1.0;
        elmt_product10 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_reactant44 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product27 = 1.0;
        elmt_reactant9 = 1.0;
        elmt_product25 = 1.0;
        elmt_product46 = 1.0;
        elmt_product29 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product8 = 1.0;
        elmt_product40 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product6 = 1.0;
        elmt_reactant31 = 1.0;
        elmt_product45 = 1.0;
        elmt_product23 = 1.0;
        elmt_reactant5 = 1.0;
        elmt_product21 = 1.0;
        elmt_product43 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_product20 = 1.0;
        elmt_product42 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant37 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant39 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant34 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_product38 = 1.0;
        elmt_product15 = 1.0;
        elmt_product36 = 1.0;
        elmt_product14 = 1.0;
        elmt_product35 = 1.0;
        elmt_product18 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_reaction_3 = (elmt_kDISC * elmt_p55free * elmt_DISC * elmt_cell);
        elmt_reaction_4 = (elmt_kD216 * elmt_DISCp55 * elmt_cell);
        elmt_reaction_1 = (elmt_kon_FADD * elmt_CD95act * elmt_FADD * elmt_cell);
        elmt_reaction_2 = (elmt_koff_FADD * elmt_DISC * elmt_cell);
        elmt_reaction_16 = (elmt_kdiss_p18 * elmt_p18 * elmt_cell);
        elmt_reaction_17 = (elmt_kBid * elmt_Bid * (elmt_p43 + elmt_p18) * elmt_cell);
        elmt_reaction_9 = (elmt_kD216trans_p43 * elmt_p43 * elmt_p43 * elmt_cell);
        elmt_reaction_14 = (elmt_kD374trans_p55 * elmt_p30 * (elmt_DISCp55 + elmt_p30) * elmt_cell);
        elmt_reaction_15 = (elmt_kD374trans_p43 * elmt_p30 * elmt_p43 * elmt_cell);
        elmt_reaction_7 = (elmt_kD216 * elmt_p43 * elmt_cell);
        elmt_reaction_8 = (elmt_kD216trans_p55 * elmt_p43 * (elmt_DISCp55 + elmt_p30) * elmt_cell);
        elmt_reaction_5 = (elmt_kD216trans_p55 * elmt_DISCp55 * (elmt_DISCp55 + elmt_p30) * elmt_cell);
        elmt_reaction_18 = (elmt_kD374probe * elmt_PrNES_mCherry * (elmt_p43 + elmt_p18) * elmt_cell);
        elmt_reaction_6 = (elmt_kD216trans_p43 * elmt_DISCp55 * elmt_p43 * elmt_cell);
        elmt_reaction_19 = (elmt_kD374probe * elmt_PrER_mGFP * elmt_p18 * elmt_cell);
        elmt_reaction_12 = (elmt_kD374trans_p43 * elmt_DISCp55 * elmt_p43 * elmt_cell);
        elmt_reaction_13 = (elmt_kD374 * elmt_p30 * elmt_cell);
        elmt_reaction_10 = (elmt_kD374 * elmt_DISCp55 * elmt_cell);
        elmt_reaction_11 = (elmt_kD374trans_p55 * elmt_DISCp55 * (elmt_DISCp55 + elmt_p30) * elmt_cell);
        der(elmt_product30) = 0;
        der(elmt_reactant41) = 0;
        der(elmt_product12) = 0;
        der(elmt_product33) = 0;
        der(elmt_product32) = 0;
        der(elmt_product10) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_reactant44) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product27) = 0;
        der(elmt_reactant9) = 0;
        der(elmt_product25) = 0;
        der(elmt_product46) = 0;
        der(elmt_product29) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product8) = 0;
        der(elmt_product40) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product6) = 0;
        der(elmt_reactant31) = 0;
        der(elmt_product45) = 0;
        der(elmt_product23) = 0;
        der(elmt_reactant5) = 0;
        der(elmt_product21) = 0;
        der(elmt_product43) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_product20) = 0;
        der(elmt_product42) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant37) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant39) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant34) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_product38) = 0;
        der(elmt_product15) = 0;
        der(elmt_product36) = 0;
        der(elmt_product14) = 0;
        der(elmt_product35) = 0;
        der(elmt_product18) = 0;
        der(elmt_product17) = 0;

end Reactions;
