within BIOMD228;
model S2MModel "Swat2004_Mammalian_G1_S_Transition" annotation(Documentation(info="<annotation>
      <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
      </rdf:RDF>
    </annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_cell elmt_cell;

    equation
        Reacs.elmt_phi_CycDa = Params.elmt_phi_CycDa;
        Reacs.elmt_pRBp = elmt_cell.elmt_pRBp;
        Reacs.elmt_CycEa = elmt_cell.elmt_CycEa;
        Reacs.elmt_a = Params.elmt_a;
        Reacs.elmt_CycDi = elmt_cell.elmt_CycDi;
        Reacs.elmt_cell = elmt_cell.elmt_cell;
        Reacs.elmt_k16 = Params.elmt_k16;
        Reacs.elmt_phi_CycDi = Params.elmt_phi_CycDi;
        Reacs.elmt_k98 = Params.elmt_k98;
        Reacs.elmt_k1 = Params.elmt_k1;
        Reacs.elmt_phi_pRB = Params.elmt_phi_pRB;
        Reacs.elmt_k2 = Params.elmt_k2;
        Reacs.elmt_k3 = Params.elmt_k3;
        Reacs.elmt_CycEi = elmt_cell.elmt_CycEi;
        Reacs.elmt_k61 = Params.elmt_k61;
        Reacs.elmt_AP1 = elmt_cell.elmt_AP1;
        Reacs.elmt_phi_pRBp = Params.elmt_phi_pRBp;
        Reacs.elmt_Km1 = Params.elmt_Km1;
        Reacs.elmt_Km2 = Params.elmt_Km2;
        Reacs.elmt_k25 = Params.elmt_k25;
        Reacs.elmt_J15 = Params.elmt_J15;
        Reacs.elmt_k23 = Params.elmt_k23;
        Reacs.elmt_J12 = Params.elmt_J12;
        Reacs.elmt_k67 = Params.elmt_k67;
        Reacs.elmt_J13 = Params.elmt_J13;
        Reacs.elmt_J11 = Params.elmt_J11;
        Reacs.elmt_Km9 = Params.elmt_Km9;
        Reacs.elmt_J18 = Params.elmt_J18;
        Reacs.elmt_Km4 = Params.elmt_Km4;
        Reacs.elmt_k28 = Params.elmt_k28;
        Reacs.elmt_J63 = Params.elmt_J63;
        Reacs.elmt_J61 = Params.elmt_J61;
        Reacs.elmt_J62 = Params.elmt_J62;
        Reacs.elmt_phi_E2F1 = Params.elmt_phi_E2F1;
        Reacs.elmt_pRBpp = elmt_cell.elmt_pRBpp;
        Reacs.elmt_E2F1 = elmt_cell.elmt_E2F1;
        Reacs.elmt_k34 = Params.elmt_k34;
        Reacs.elmt_J68 = Params.elmt_J68;
        Reacs.elmt_k76 = Params.elmt_k76;
        Reacs.elmt_J65 = Params.elmt_J65;
        Reacs.elmt_phi_CycEa = Params.elmt_phi_CycEa;
        Reacs.elmt_kp = Params.elmt_kp;
        Reacs.elmt_pRB = elmt_cell.elmt_pRB;
        Reacs.elmt_CycDa = elmt_cell.elmt_CycDa;
        Reacs.elmt_phi_AP1 = Params.elmt_phi_AP1;
        Reacs.elmt_Fm = Params.elmt_Fm;
        Reacs.elmt_phi_pRBpp = Params.elmt_phi_pRBpp;
        Reacs.elmt_phi_CycEi = Params.elmt_phi_CycEi;
        Reacs.elmt_k89 = Params.elmt_k89;
        Reacs.elmt_k43 = Params.elmt_k43;
        elmt_cell.elmt_pRB_degradation = Reacs.elmt_pRB_degradation;
        elmt_cell.elmt_CycE_degradation = Reacs.elmt_CycE_degradation;
        elmt_cell.elmt_pRBpp_degradation = Reacs.elmt_pRBpp_degradation;
        elmt_cell.elmt_CycD_degradation = Reacs.elmt_CycD_degradation;
        elmt_cell.elmt_product27 = Reacs.elmt_product27;
        elmt_cell.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_cell.elmt_product25 = Reacs.elmt_product25;
        elmt_cell.elmt_pRB_phosphorylation = Reacs.elmt_pRB_phosphorylation;
        elmt_cell.elmt_pRBp_phosphorylation = Reacs.elmt_pRBp_phosphorylation;
        elmt_cell.elmt_CycE_synthesis = Reacs.elmt_CycE_synthesis;
        elmt_cell.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_cell.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_cell.elmt_reactant17 = Reacs.elmt_reactant17;
        elmt_cell.elmt_reactant11 = Reacs.elmt_reactant11;
        elmt_cell.elmt_reactant13 = Reacs.elmt_reactant13;
        elmt_cell.elmt_CycE_degradation2 = Reacs.elmt_CycE_degradation2;
        elmt_cell.elmt_pRB_synthesis = Reacs.elmt_pRB_synthesis;
        elmt_cell.elmt_CycD_degradation2 = Reacs.elmt_CycD_degradation2;
        elmt_cell.elmt_CycE_inibition = Reacs.elmt_CycE_inibition;
        elmt_cell.elmt_pRBpp_dephosphorylation = Reacs.elmt_pRBpp_dephosphorylation;
        elmt_cell.elmt_CycD_synthesis = Reacs.elmt_CycD_synthesis;
        elmt_cell.elmt_product12 = Reacs.elmt_product12;
        elmt_cell.elmt_product10 = Reacs.elmt_product10;
        elmt_cell.elmt_pRBp_degradation = Reacs.elmt_pRBp_degradation;
        elmt_cell.elmt_reactant26 = Reacs.elmt_reactant26;
        elmt_cell.elmt_reactant28 = Reacs.elmt_reactant28;
        elmt_cell.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_cell.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_cell.elmt_reactant24 = Reacs.elmt_reactant24;
        elmt_cell.elmt_E2F1_synthesis = Reacs.elmt_E2F1_synthesis;
        elmt_cell.elmt_reactant19 = Reacs.elmt_reactant19;
        elmt_cell.elmt_AP1_synthesis = Reacs.elmt_AP1_synthesis;
        elmt_cell.elmt_CycD_activation = Reacs.elmt_CycD_activation;
        elmt_cell.elmt_product8 = Reacs.elmt_product8;
        elmt_cell.elmt_reactant1 = Reacs.elmt_reactant1;
        elmt_cell.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_cell.elmt_product6 = Reacs.elmt_product6;
        elmt_cell.elmt_product23 = Reacs.elmt_product23;
        elmt_cell.elmt_CycE_activation = Reacs.elmt_CycE_activation;
        elmt_cell.elmt_Ap1_degradation = Reacs.elmt_Ap1_degradation;
        elmt_cell.elmt_reactant5 = Reacs.elmt_reactant5;
        elmt_cell.elmt_product20 = Reacs.elmt_product20;
        elmt_cell.elmt_reactant7 = Reacs.elmt_reactant7;
        elmt_cell.elmt_product0 = Reacs.elmt_product0;
        elmt_cell.elmt_CycD_inibition = Reacs.elmt_CycD_inibition;
        elmt_cell.elmt_product4 = Reacs.elmt_product4;
        elmt_cell.elmt_product2 = Reacs.elmt_product2;
        elmt_cell.elmt_pRBp_dephosphorylation = Reacs.elmt_pRBp_dephosphorylation;
        elmt_cell.elmt_reactant29 = Reacs.elmt_reactant29;
        elmt_cell.elmt_product15 = Reacs.elmt_product15;
        elmt_cell.elmt_E2F1_degradation = Reacs.elmt_E2F1_degradation;
        elmt_cell.elmt_product18 = Reacs.elmt_product18;

end S2MModel;
