

#include <iostream>
#include <vector>
#include <iomanip>
#include <string>
#include <fstream>

#include "OneDHeatTransferTI_Modelica_N_40_SystemDefinition.cuh"
#include "SingleSystem_PerThread_Interface.cuh"

using namespace std;

#define SOLVER RKCK45 // Runge-Kutta Order 4th
#define PRECISION double
const int NT   = 1;
const int SD   = 39;
const int NCP  = 1;
const int NSP  = 88;
const int NISP = 1;
const int NE   = 0;
const int NA   = 353;
const int NIA  = 0;
const int NDO  = 15000;


void FillSolverObject(
    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION>& Solver, 
    int FirstProblemNumber, int NumberOfThreads
) {
    int k_begin = FirstProblemNumber;
    int k_end   = FirstProblemNumber + NumberOfThreads;
	
    int ProblemNumber = 0;
    while (k_begin < k_end) {
        Solver.SetHost(ProblemNumber, TimeDomain, 0, 0.0);
        Solver.SetHost(ProblemNumber, TimeDomain, 1, 1500.0);  

        // Settaggio dei valori iniziali degli ActualState
 

        Solver.SetHost(ProblemNumber, ActualTime, 0.0);
        Solver.SetHost(ProblemNumber, ControlParameters, 0, 0.0);
        Solver.SetHost(ProblemNumber, DenseIndex, 0 );

        // Settaggio dei valori iniziali per ACC (se presenti)


        // Settaggio dei valori iniziali per ACCi (se presenti)

		
        ProblemNumber++;
        k_begin++;
    }

    // Settaggio dei valori iniziali per sPAR (se presenti)


    // Settaggio dei valori iniziali per sPARi (se presenti)

}


void SaveData(
    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION>& Solver, 
    ofstream& DataFile, int NumberOfThreads
) {
    int Width = 18;
    DataFile.precision(10);
    DataFile.flags(ios::scientific);
	
    for (int tid=0; tid<NumberOfThreads; tid++)
    {
        DataFile.width(Width); DataFile << "X_heatcapacitor[1].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[2].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[3].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[4].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[5].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[6].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[7].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[8].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[9].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[10].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[11].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[12].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[13].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[14].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[15].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[16].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[17].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[18].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[19].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[20].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[21].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[22].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[23].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[24].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[25].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[26].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[27].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[28].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[29].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[30].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[31].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[32].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[33].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[34].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[35].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[36].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[37].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[38].T" << ',';
        DataFile.width(Width); DataFile << "X_heatcapacitor[39].T" << ',';
        DataFile.width(Width); DataFile << "sPAR_A" << ',';
        DataFile.width(Width); DataFile << "sPAR_L" << ',';
        DataFile.width(Width); DataFile << "sPAR_T0" << ',';
        DataFile.width(Width); DataFile << "sPAR_TN" << ',';
        DataFile.width(Width); DataFile << "sPAR_cp" << ',';
        DataFile.width(Width); DataFile << "sPAR_fixedtemperature.T" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[1].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[2].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[3].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[4].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[5].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[6].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[7].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[8].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[9].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[10].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[11].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[12].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[13].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[14].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[15].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[16].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[17].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[18].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[19].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[20].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[21].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[22].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[23].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[24].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[25].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[26].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[27].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[28].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[29].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[30].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[31].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[32].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[33].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[34].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[35].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[36].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[37].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[38].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_heatcapacitor[39].C" << ',';
        DataFile.width(Width); DataFile << "sPAR_lambda" << ',';
        DataFile.width(Width); DataFile << "sPAR_m" << ',';
        DataFile.width(Width); DataFile << "sPAR_rho" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[1].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[2].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[3].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[4].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[5].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[6].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[7].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[8].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[9].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[10].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[11].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[12].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[13].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[14].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[15].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[16].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[17].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[18].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[19].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[20].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[21].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[22].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[23].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[24].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[25].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[26].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[27].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[28].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[29].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[30].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[31].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[32].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[33].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[34].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[35].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[36].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[37].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[38].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_thermalconductor[39].G" << ',';
        DataFile.width(Width); DataFile << "sPAR_v" << ',';
        DataFile.width(Width); DataFile << "sPARi_N" << ',';
        DataFile.width(Width); DataFile << "ACC_fixedtemperature.port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_fixedtemperature.port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[1].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[2].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[3].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[4].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[5].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[6].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[7].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[8].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[9].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[10].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[11].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[12].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[13].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[14].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[15].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[16].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[17].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[18].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[19].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[20].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[21].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[22].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[23].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[24].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[25].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[26].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[27].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[28].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[29].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[30].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[31].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[32].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[33].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[34].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[35].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[36].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[37].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[38].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[39].der_T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[1].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[2].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[3].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[4].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[5].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[6].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[7].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[8].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[9].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[10].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[11].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[12].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[13].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[14].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[15].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[16].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[17].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[18].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[19].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[20].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[21].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[22].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[23].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[24].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[25].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[26].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[27].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[28].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[29].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[30].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[31].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[32].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[33].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[34].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[35].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[36].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[37].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[38].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[39].port.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[1].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[2].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[3].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[4].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[5].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[6].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[7].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[8].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[9].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[10].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[11].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[12].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[13].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[14].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[15].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[16].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[17].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[18].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[19].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[20].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[21].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[22].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[23].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[24].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[25].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[26].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[27].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[28].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[29].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[30].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[31].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[32].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[33].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[34].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[35].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[36].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[37].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[38].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_heatcapacitor[39].port.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[1].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[2].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[3].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[4].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[5].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[6].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[7].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[8].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[9].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[10].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[11].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[12].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[13].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[14].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[15].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[16].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[17].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[18].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[19].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[20].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[21].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[22].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[23].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[24].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[25].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[26].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[27].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[28].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[29].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[30].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[31].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[32].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[33].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[34].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[35].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[36].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[37].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[38].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[39].Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[1].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[2].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[3].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[4].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[5].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[6].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[7].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[8].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[9].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[10].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[11].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[12].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[13].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[14].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[15].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[16].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[17].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[18].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[19].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[20].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[21].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[22].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[23].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[24].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[25].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[26].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[27].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[28].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[29].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[30].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[31].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[32].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[33].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[34].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[35].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[36].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[37].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[38].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[39].dT" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[1].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[2].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[3].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[4].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[5].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[6].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[7].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[8].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[9].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[10].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[11].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[12].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[13].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[14].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[15].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[16].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[17].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[18].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[19].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[20].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[21].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[22].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[23].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[24].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[25].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[26].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[27].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[28].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[29].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[30].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[31].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[32].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[33].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[34].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[35].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[36].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[37].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[38].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[39].port_a.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[1].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[2].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[3].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[4].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[5].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[6].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[7].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[8].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[9].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[10].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[11].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[12].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[13].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[14].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[15].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[16].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[17].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[18].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[19].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[20].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[21].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[22].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[23].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[24].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[25].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[26].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[27].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[28].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[29].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[30].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[31].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[32].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[33].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[34].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[35].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[36].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[37].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[38].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[39].port_a.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[1].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[2].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[3].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[4].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[5].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[6].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[7].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[8].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[9].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[10].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[11].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[12].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[13].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[14].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[15].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[16].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[17].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[18].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[19].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[20].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[21].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[22].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[23].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[24].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[25].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[26].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[27].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[28].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[29].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[30].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[31].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[32].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[33].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[34].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[35].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[36].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[37].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[38].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[39].port_b.Q_flow" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[1].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[2].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[3].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[4].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[5].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[6].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[7].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[8].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[9].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[10].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[11].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[12].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[13].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[14].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[15].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[16].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[17].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[18].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[19].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[20].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[21].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[22].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[23].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[24].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[25].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[26].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[27].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[28].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[29].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[30].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[31].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[32].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[33].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[34].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[35].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[36].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[37].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[38].port_b.T" << ',';
        DataFile.width(Width); DataFile << "ACC_thermalconductor[39].port_b.T" << ',';
        DataFile.width(Width); DataFile << endl;
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 1) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 2) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 3) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 4) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 5) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 6) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 7) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 8) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 9) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 10) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 11) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 12) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 13) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 14) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 15) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 16) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 17) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 18) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 19) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 20) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 21) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 22) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 23) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 24) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 25) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 26) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 27) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 28) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 29) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 30) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 31) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 32) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 33) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 34) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 35) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 36) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 37) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 38) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 1) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 2) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 3) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 4) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 5) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 6) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 7) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 8) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 9) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 10) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 11) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 12) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 13) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 14) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 15) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 16) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 17) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 18) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 19) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 20) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 21) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 22) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 23) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 24) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 25) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 26) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 27) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 28) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 29) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 30) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 31) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 32) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 33) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 34) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 35) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 36) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 37) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 38) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 39) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 40) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 41) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 42) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 43) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 44) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 45) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 46) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 47) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 48) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 49) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 50) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 51) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 52) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 53) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 54) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 55) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 56) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 57) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 58) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 59) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 60) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 61) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 62) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 63) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 64) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 65) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 66) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 67) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 68) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 69) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 70) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 71) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 72) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 73) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 74) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 75) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 76) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 77) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 78) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 79) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 80) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 81) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 82) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 83) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 84) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 85) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 86) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 87) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(IntegerSharedParameters, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 1) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 2) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 3) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 4) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 5) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 6) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 7) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 8) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 9) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 10) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 11) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 12) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 13) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 14) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 15) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 16) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 17) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 18) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 19) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 20) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 21) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 22) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 23) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 24) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 25) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 26) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 27) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 28) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 29) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 30) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 31) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 32) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 33) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 34) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 35) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 36) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 37) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 38) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 39) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 40) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 41) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 42) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 43) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 44) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 45) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 46) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 47) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 48) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 49) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 50) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 51) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 52) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 53) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 54) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 55) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 56) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 57) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 58) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 59) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 60) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 61) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 62) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 63) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 64) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 65) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 66) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 67) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 68) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 69) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 70) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 71) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 72) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 73) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 74) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 75) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 76) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 77) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 78) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 79) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 80) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 81) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 82) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 83) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 84) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 85) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 86) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 87) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 88) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 89) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 90) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 91) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 92) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 93) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 94) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 95) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 96) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 97) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 98) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 99) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 100) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 101) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 102) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 103) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 104) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 105) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 106) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 107) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 108) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 109) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 110) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 111) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 112) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 113) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 114) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 115) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 116) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 117) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 118) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 119) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 120) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 121) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 122) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 123) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 124) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 125) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 126) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 127) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 128) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 129) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 130) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 131) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 132) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 133) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 134) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 135) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 136) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 137) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 138) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 139) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 140) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 141) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 142) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 143) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 144) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 145) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 146) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 147) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 148) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 149) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 150) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 151) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 152) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 153) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 154) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 155) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 156) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 157) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 158) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 159) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 160) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 161) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 162) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 163) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 164) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 165) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 166) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 167) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 168) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 169) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 170) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 171) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 172) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 173) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 174) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 175) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 176) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 177) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 178) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 179) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 180) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 181) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 182) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 183) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 184) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 185) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 186) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 187) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 188) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 189) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 190) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 191) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 192) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 193) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 194) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 195) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 196) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 197) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 198) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 199) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 200) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 201) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 202) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 203) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 204) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 205) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 206) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 207) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 208) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 209) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 210) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 211) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 212) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 213) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 214) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 215) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 216) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 217) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 218) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 219) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 220) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 221) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 222) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 223) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 224) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 225) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 226) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 227) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 228) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 229) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 230) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 231) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 232) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 233) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 234) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 235) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 236) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 237) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 238) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 239) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 240) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 241) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 242) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 243) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 244) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 245) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 246) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 247) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 248) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 249) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 250) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 251) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 252) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 253) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 254) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 255) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 256) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 257) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 258) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 259) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 260) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 261) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 262) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 263) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 264) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 265) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 266) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 267) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 268) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 269) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 270) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 271) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 272) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 273) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 274) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 275) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 276) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 277) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 278) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 279) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 280) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 281) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 282) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 283) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 284) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 285) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 286) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 287) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 288) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 289) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 290) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 291) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 292) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 293) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 294) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 295) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 296) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 297) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 298) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 299) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 300) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 301) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 302) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 303) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 304) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 305) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 306) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 307) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 308) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 309) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 310) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 311) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 312) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 313) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 314) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 315) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 316) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 317) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 318) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 319) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 320) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 321) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 322) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 323) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 324) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 325) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 326) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 327) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 328) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 329) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 330) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 331) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 332) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 333) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 334) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 335) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 336) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 337) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 338) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 339) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 340) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 341) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 342) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 343) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 344) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 345) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 346) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 347) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 348) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 349) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 350) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 351) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 352) << ',';

        DataFile << '\n';
    }
}


int main() {
    int NumberOfProblems = NT; // Numero di problemi da risolvere, uno per thread
    int blockSize        = 512; // Numero di Thread per blocchi
    
    // Listing dei Device CUDA
    ListCUDADevices();

    int MajorVersion = 7; // Major version della CUDA compute capability
    int MinorVersion = 5; // Minor version della CUDA compute capability

    // Seleziona il Device da utilizzare dando in input la CUDA compute capability e ne stampa le caratteristiche
    int SelectedDevice = SelectDeviceByClosestRevision(MajorVersion, MinorVersion);
    PrintPropertiesOfSpecificDevice(SelectedDevice);

    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION> Solver(SelectedDevice);
    Solver.SolverOption(ThreadsPerBlock, blockSize);
    Solver.SolverOption(PreferSharedMemory, 1);
    Solver.SolverOption(InitialTimeStep, 0.01);
    Solver.SolverOption(ActiveNumberOfThreads, NT);
    Solver.SolverOption(MaximumTimeStep, 1000000.0);
    Solver.SolverOption(MinimumTimeStep, 1e-14);
    Solver.SolverOption(TimeStepGrowLimit, 5.0);

    Solver.SolverOption(TimeStepShrinkLimit, 0.2);



    Solver.SolverOption(DenseOutputMinimumTimeStep, 0.0);
    Solver.SolverOption(DenseOutputSaveFrequency, 1);
    Solver.SolverOption(AbsoluteTolerance, 0, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 1, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 2, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 3, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 4, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 5, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 6, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 7, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 8, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 9, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 10, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 11, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 12, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 13, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 14, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 15, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 16, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 17, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 18, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 19, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 20, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 21, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 22, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 23, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 24, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 25, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 26, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 27, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 28, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 29, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 30, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 31, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 32, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 33, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 34, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 35, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 36, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 37, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 38, 1e-06);

    Solver.SolverOption(RelativeTolerance, 0, 1e-06);
    Solver.SolverOption(RelativeTolerance, 1, 1e-06);
    Solver.SolverOption(RelativeTolerance, 2, 1e-06);
    Solver.SolverOption(RelativeTolerance, 3, 1e-06);
    Solver.SolverOption(RelativeTolerance, 4, 1e-06);
    Solver.SolverOption(RelativeTolerance, 5, 1e-06);
    Solver.SolverOption(RelativeTolerance, 6, 1e-06);
    Solver.SolverOption(RelativeTolerance, 7, 1e-06);
    Solver.SolverOption(RelativeTolerance, 8, 1e-06);
    Solver.SolverOption(RelativeTolerance, 9, 1e-06);
    Solver.SolverOption(RelativeTolerance, 10, 1e-06);
    Solver.SolverOption(RelativeTolerance, 11, 1e-06);
    Solver.SolverOption(RelativeTolerance, 12, 1e-06);
    Solver.SolverOption(RelativeTolerance, 13, 1e-06);
    Solver.SolverOption(RelativeTolerance, 14, 1e-06);
    Solver.SolverOption(RelativeTolerance, 15, 1e-06);
    Solver.SolverOption(RelativeTolerance, 16, 1e-06);
    Solver.SolverOption(RelativeTolerance, 17, 1e-06);
    Solver.SolverOption(RelativeTolerance, 18, 1e-06);
    Solver.SolverOption(RelativeTolerance, 19, 1e-06);
    Solver.SolverOption(RelativeTolerance, 20, 1e-06);
    Solver.SolverOption(RelativeTolerance, 21, 1e-06);
    Solver.SolverOption(RelativeTolerance, 22, 1e-06);
    Solver.SolverOption(RelativeTolerance, 23, 1e-06);
    Solver.SolverOption(RelativeTolerance, 24, 1e-06);
    Solver.SolverOption(RelativeTolerance, 25, 1e-06);
    Solver.SolverOption(RelativeTolerance, 26, 1e-06);
    Solver.SolverOption(RelativeTolerance, 27, 1e-06);
    Solver.SolverOption(RelativeTolerance, 28, 1e-06);
    Solver.SolverOption(RelativeTolerance, 29, 1e-06);
    Solver.SolverOption(RelativeTolerance, 30, 1e-06);
    Solver.SolverOption(RelativeTolerance, 31, 1e-06);
    Solver.SolverOption(RelativeTolerance, 32, 1e-06);
    Solver.SolverOption(RelativeTolerance, 33, 1e-06);
    Solver.SolverOption(RelativeTolerance, 34, 1e-06);
    Solver.SolverOption(RelativeTolerance, 35, 1e-06);
    Solver.SolverOption(RelativeTolerance, 36, 1e-06);
    Solver.SolverOption(RelativeTolerance, 37, 1e-06);
    Solver.SolverOption(RelativeTolerance, 38, 1e-06);
   
    
    int NumberOfSimulationLaunches = NumberOfProblems / NT + (NumberOfProblems % NT == 0 ? 0:1);
    ofstream DataFile;
    DataFile.open ( "OneDHeatTransferTI_Modelica_N_40.csv" );
    clock_t SimulationStart = clock();
    clock_t TransientStart;
    clock_t TransientEnd;    
    for (int i=0; i < NumberOfSimulationLaunches; i++) {
        FillSolverObject(Solver, i*NT, NT);
        Solver.SynchroniseFromHostToDevice(All);
        Solver.InsertSynchronisationPoint();
        Solver.SynchroniseSolver();

        TransientStart = clock();
        for (int j=0; j < 1; j++) {
            Solver.Solve();
            Solver.InsertSynchronisationPoint();
            Solver.SynchroniseSolver();
        }
        TransientEnd = clock();
        cout << "Launches: " << i << "  Simulation time: ";
        cout << 1000.0*(TransientEnd-TransientStart) / CLOCKS_PER_SEC << "ms" << endl << endl;
        for (int j=0; j<1; j++)
        {
            Solver.Solve();
            Solver.SynchroniseFromDeviceToHost(All);
            Solver.InsertSynchronisationPoint();
            Solver.SynchroniseSolver();
            SaveData(Solver, DataFile, NT);
        }
    }

    clock_t SimulationEnd = clock();
    cout << "Total simulation time: " << 1000.0*(SimulationEnd-SimulationStart) / CLOCKS_PER_SEC << "ms";
    cout << endl;
	
    DataFile.close();
    
    Solver.Print(DenseOutput, 0);
    Solver.Print(ActualState);
    Solver.Print(ActualTime);
	
    cout << "Test finished!" << endl;

    return 0;
}

