/* Simulation code for System generated by the OpenModelica Compiler 1.9.2 (r25115). */
#define time data->localData[0]->timeValue

/* States */
/* x */
#define _$Px(i) data->localData[i]->realVars[0]
#define $Px _$Px(0)
#define $P$PRE$Px data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$Px data->modelData.realVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Px $P$ATTRIBUTE$Px
#define $Px__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$Px__varInfo data->modelData.realVarsData[0].info
#define _$P$PRE$Px(i) $P$PRE$Px


/* StatesDerivatives */
/* der(x) */
#define _$P$DER$Px(i) data->localData[i]->realVars[1]
#define $P$DER$Px _$P$DER$Px(0)
#define $P$PRE$P$DER$Px data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$P$DER$Px data->modelData.realVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Px $P$ATTRIBUTE$P$DER$Px
#define $P$DER$Px__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$P$DER$Px__varInfo data->modelData.realVarsData[1].info
#define _$P$PRE$P$DER$Px(i) $P$PRE$P$DER$Px


/* Non Discrete Real Algebraic Vars */

/* Discrete Real Algebraic Vars */

/* Nonlinear Constraints For Dyn. Optimization */

/* Nonlinear Final Constraints For Dyn. Optimization */

/* Algebraic Parameter */

/* External Objects */

/* Algebraic Integer Vars */

/* Algebraic Integer Parameter */

/* Algebraic Boolean Vars */

/* Algebraic Boolean Parameters */

/* Algebraic String Variables */

/* Algebraic String Parameter */

/* sample */


