within BIOMD162;
model Hernjak2005_Calcium_Signaling "Hernjak2005_Calcium_Signaling" annotation(Documentation(info="<annotation>
      <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
      </rdf:RDF>
    </annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_Cytosol elmt_Cytosol;
    Class_elmt_ER elmt_ER;
    Class_elmt_PM elmt_PM;
    Class_elmt_ERM elmt_ERM;
    Class_elmt_Extracellular elmt_Extracellular;

    equation
        Params.elmt_Ca_D_Cytosol = elmt_Cytosol.elmt_Ca_D_Cytosol;
        Params.elmt_Ca_D_Extracellular = elmt_Extracellular.elmt_Ca_D_Extracellular;
        Params.elmt_Ca_Cytosol = elmt_Cytosol.elmt_Ca_Cytosol;
        Params.elmt_Ca_Extracellular = elmt_Extracellular.elmt_Ca_Extracellular;
        Reacs.elmt_PABMg_D_Cytosol = elmt_Cytosol.elmt_PABMg_D_Cytosol;
        Reacs.elmt_D28k_high_Cytosol = elmt_Cytosol.elmt_D28k_high_Cytosol;
        Reacs.elmt_PABCa_Cytosol = elmt_Cytosol.elmt_PABCa_Cytosol;
        Reacs.elmt_PABMg_Cytosol = elmt_Cytosol.elmt_PABMg_Cytosol;
        Reacs.elmt_ERDensity_ERM = elmt_ERM.elmt_ERDensity_ERM;
        Reacs.elmt_ERM = elmt_ERM.elmt_ERM;
        Reacs.elmt_D28kB_D_Cytosol = elmt_Cytosol.elmt_D28kB_D_Cytosol;
        Reacs.elmt_h_D_ERM = elmt_ERM.elmt_h_D_ERM;
        Reacs.elmt_CG_Cytosol = elmt_Cytosol.elmt_CG_Cytosol;
        Reacs.elmt_CG_D_Cytosol = elmt_Cytosol.elmt_CG_D_Cytosol;
        Reacs.elmt_D28k_Cytosol = elmt_Cytosol.elmt_D28k_Cytosol;
        Reacs.elmt_Cytosol = elmt_Cytosol.elmt_Cytosol;
        Reacs.elmt_PM = elmt_PM.elmt_PM;
        Reacs.elmt_Ca_ER = elmt_ER.elmt_Ca_ER;
        Reacs.elmt_PA_D_Cytosol = elmt_Cytosol.elmt_PA_D_Cytosol;
        Reacs.elmt_KMOLE = Params.elmt_KMOLE;
        Reacs.elmt_CGB_Cytosol = elmt_Cytosol.elmt_CGB_Cytosol;
        Reacs.elmt_flux1_ar = Params.elmt_flux1_ar;
        Reacs.elmt_D28k_high_D_Cytosol = elmt_Cytosol.elmt_D28k_high_D_Cytosol;
        Reacs.elmt_PA_Cytosol = elmt_Cytosol.elmt_PA_Cytosol;
        Reacs.elmt_IP3_Cytosol = elmt_Cytosol.elmt_IP3_Cytosol;
        Reacs.elmt_Mg_Cytosol = elmt_Cytosol.elmt_Mg_Cytosol;
        Reacs.elmt_Ca_D_Cytosol = elmt_Cytosol.elmt_Ca_D_Cytosol;
        Reacs.elmt_D28kB_high_D_Cytosol = elmt_Cytosol.elmt_D28kB_high_D_Cytosol;
        Reacs.elmt_D28kB_high_Cytosol = elmt_Cytosol.elmt_D28kB_high_Cytosol;
        Reacs.elmt_ERDensity_D_ERM = elmt_ERM.elmt_ERDensity_D_ERM;
        Reacs.elmt_Mg_D_Cytosol = elmt_Cytosol.elmt_Mg_D_Cytosol;
        Reacs.elmt_IP3_D_Cytosol = elmt_Cytosol.elmt_IP3_D_Cytosol;
        Reacs.elmt_pulses_ar = Params.elmt_pulses_ar;
        Reacs.elmt_CGB_D_Cytosol = elmt_Cytosol.elmt_CGB_D_Cytosol;
        Reacs.elmt_PABCa_D_Cytosol = elmt_Cytosol.elmt_PABCa_D_Cytosol;
        Reacs.elmt_Ca_D_ER = elmt_ER.elmt_Ca_D_ER;
        Reacs.elmt_h_ERM = elmt_ERM.elmt_h_ERM;
        Reacs.elmt_D28k_D_Cytosol = elmt_Cytosol.elmt_D28k_D_Cytosol;
        Reacs.elmt_flux0_ar = Params.elmt_flux0_ar;
        Reacs.elmt_Ca_Cytosol = elmt_Cytosol.elmt_Ca_Cytosol;
        Reacs.elmt_D28kB_Cytosol = elmt_Cytosol.elmt_D28kB_Cytosol;
        elmt_Cytosol.elmt_reactant40 = Reacs.elmt_reactant40;
        elmt_Cytosol.elmt_reactant41 = Reacs.elmt_reactant41;
        elmt_Cytosol.elmt_reactant42 = Reacs.elmt_reactant42;
        elmt_Cytosol.elmt_CGbinding = Reacs.elmt_CGbinding;
        elmt_Cytosol.elmt_CG_d = Reacs.elmt_CG_d;
        elmt_Cytosol.elmt_reactant47 = Reacs.elmt_reactant47;
        elmt_Cytosol.elmt_reactant48 = Reacs.elmt_reactant48;
        elmt_Cytosol.elmt_PABCa_deg = Reacs.elmt_PABCa_deg;
        elmt_Cytosol.elmt_reactant49 = Reacs.elmt_reactant49;
        elmt_Cytosol.elmt_product70 = Reacs.elmt_product70;
        elmt_Cytosol.elmt_reactant43 = Reacs.elmt_reactant43;
        elmt_Cytosol.elmt_reactant46 = Reacs.elmt_reactant46;
        elmt_Cytosol.elmt_IP3R_fluxD = Reacs.elmt_IP3R_fluxD;
        elmt_Cytosol.elmt_ER_leak_fluxD = Reacs.elmt_ER_leak_fluxD;
        elmt_Cytosol.elmt_D28kB_d = Reacs.elmt_D28kB_d;
        elmt_Cytosol.elmt_D28k_d = Reacs.elmt_D28k_d;
        elmt_Cytosol.elmt_reactant50 = Reacs.elmt_reactant50;
        elmt_Cytosol.elmt_reactant51 = Reacs.elmt_reactant51;
        elmt_Cytosol.elmt_reactant52 = Reacs.elmt_reactant52;
        elmt_Cytosol.elmt_reactant59 = Reacs.elmt_reactant59;
        elmt_Cytosol.elmt_PABCa_d = Reacs.elmt_PABCa_d;
        elmt_Cytosol.elmt_CGB_d = Reacs.elmt_CGB_d;
        elmt_Cytosol.elmt_reactant54 = Reacs.elmt_reactant54;
        elmt_Cytosol.elmt_reactant55 = Reacs.elmt_reactant55;
        elmt_Cytosol.elmt_reactant57 = Reacs.elmt_reactant57;
        elmt_Cytosol.elmt_ER_leak_flux = Reacs.elmt_ER_leak_flux;
        elmt_Cytosol.elmt_PABMg_deg = Reacs.elmt_PABMg_deg;
        elmt_Cytosol.elmt_PA_Ca = Reacs.elmt_PA_Ca;
        elmt_Cytosol.elmt_Ca_deg = Reacs.elmt_Ca_deg;
        elmt_Cytosol.elmt_reactant20 = Reacs.elmt_reactant20;
        elmt_Cytosol.elmt_product12 = Reacs.elmt_product12;
        elmt_Cytosol.elmt_CG_deg = Reacs.elmt_CG_deg;
        elmt_Cytosol.elmt_reactant26 = Reacs.elmt_reactant26;
        elmt_Cytosol.elmt_reactant27 = Reacs.elmt_reactant27;
        elmt_Cytosol.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_Cytosol.elmt_reactant23 = Reacs.elmt_reactant23;
        elmt_Cytosol.elmt_reactant24 = Reacs.elmt_reactant24;
        elmt_Cytosol.elmt_D28k_high_d = Reacs.elmt_D28k_high_d;
        elmt_Cytosol.elmt_PABMg_d = Reacs.elmt_PABMg_d;
        elmt_Cytosol.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_Cytosol.elmt_reactant19 = Reacs.elmt_reactant19;
        elmt_Cytosol.elmt_CGB_deg = Reacs.elmt_CGB_deg;
        elmt_Cytosol.elmt_IP3R_flux = Reacs.elmt_IP3R_flux;
        elmt_Cytosol.elmt_D28kBDbinding = Reacs.elmt_D28kBDbinding;
        elmt_Cytosol.elmt_PA_MgD = Reacs.elmt_PA_MgD;
        elmt_Cytosol.elmt_CD28k_highDbinding = Reacs.elmt_CD28k_highDbinding;
        elmt_Cytosol.elmt_D28kB_high_d = Reacs.elmt_D28kB_high_d;
        elmt_Cytosol.elmt_pulses = Reacs.elmt_pulses;
        elmt_Cytosol.elmt_reactant30 = Reacs.elmt_reactant30;
        elmt_Cytosol.elmt_reactant31 = Reacs.elmt_reactant31;
        elmt_Cytosol.elmt_CD28k_high = Reacs.elmt_CD28k_high;
        elmt_Cytosol.elmt_reactant37 = Reacs.elmt_reactant37;
        elmt_Cytosol.elmt_reactant38 = Reacs.elmt_reactant38;
        elmt_Cytosol.elmt_D28k_high_deg = Reacs.elmt_D28k_high_deg;
        elmt_Cytosol.elmt_product5 = Reacs.elmt_product5;
        elmt_Cytosol.elmt_SERCA_fluxD = Reacs.elmt_SERCA_fluxD;
        elmt_Cytosol.elmt_reactant33 = Reacs.elmt_reactant33;
        elmt_Cytosol.elmt_D28k_deg = Reacs.elmt_D28k_deg;
        elmt_Cytosol.elmt_reactant34 = Reacs.elmt_reactant34;
        elmt_Cytosol.elmt_reactant35 = Reacs.elmt_reactant35;
        elmt_Cytosol.elmt_product2 = Reacs.elmt_product2;
        elmt_Cytosol.elmt_reactant29 = Reacs.elmt_reactant29;
        elmt_Cytosol.elmt_product15 = Reacs.elmt_product15;
        elmt_Cytosol.elmt_PA_Mg = Reacs.elmt_PA_Mg;
        elmt_Cytosol.elmt_IP3_degr = Reacs.elmt_IP3_degr;
        elmt_Cytosol.elmt_SERCA_flux = Reacs.elmt_SERCA_flux;
        elmt_Cytosol.elmt_IP3deg = Reacs.elmt_IP3deg;
        elmt_Cytosol.elmt_D28kB_high_deg = Reacs.elmt_D28kB_high_deg;
        elmt_Cytosol.elmt_flux0 = Reacs.elmt_flux0;
        elmt_Cytosol.elmt_flux1 = Reacs.elmt_flux1;
        elmt_Cytosol.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_Cytosol.elmt_product25 = Reacs.elmt_product25;
        elmt_Cytosol.elmt_PA_deg = Reacs.elmt_PA_deg;
        elmt_Cytosol.elmt_product28 = Reacs.elmt_product28;
        elmt_Cytosol.elmt_D28kB_deg = Reacs.elmt_D28kB_deg;
        elmt_Cytosol.elmt_product45 = Reacs.elmt_product45;
        elmt_Cytosol.elmt_Ca_d = Reacs.elmt_Ca_d;
        elmt_Cytosol.elmt_PA_Dbinding = Reacs.elmt_PA_Dbinding;
        elmt_Cytosol.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_Cytosol.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_Cytosol.elmt_CaD28k_med = Reacs.elmt_CaD28k_med;
        elmt_Cytosol.elmt_reactant17 = Reacs.elmt_reactant17;
        elmt_Cytosol.elmt_reactant11 = Reacs.elmt_reactant11;
        elmt_Cytosol.elmt_reactant13 = Reacs.elmt_reactant13;
        elmt_Cytosol.elmt_IP3_d = Reacs.elmt_IP3_d;
        elmt_Cytosol.elmt_product36 = Reacs.elmt_product36;
        elmt_Cytosol.elmt_product39 = Reacs.elmt_product39;
        elmt_Cytosol.elmt_reactant61 = Reacs.elmt_reactant61;
        elmt_Cytosol.elmt_reactant63 = Reacs.elmt_reactant63;
        elmt_Cytosol.elmt_product56 = Reacs.elmt_product56;
        elmt_Cytosol.elmt_product53 = Reacs.elmt_product53;
        elmt_Cytosol.elmt_reactant67 = Reacs.elmt_reactant67;
        elmt_Cytosol.elmt_IP3_degr1 = Reacs.elmt_IP3_degr1;
        elmt_Cytosol.elmt_CG_Dbinding = Reacs.elmt_CG_Dbinding;
        elmt_Cytosol.elmt_reactant1 = Reacs.elmt_reactant1;
        elmt_Cytosol.elmt_reactant4 = Reacs.elmt_reactant4;
        elmt_Cytosol.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_Cytosol.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_Cytosol.elmt_product66 = Reacs.elmt_product66;
        elmt_Cytosol.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_Cytosol.elmt_reactant71 = Reacs.elmt_reactant71;
        elmt_Cytosol.elmt_reactant7 = Reacs.elmt_reactant7;
        elmt_Cytosol.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_Cytosol.elmt_PA_d = Reacs.elmt_PA_d;
        elmt_ERM.elmt_reaction1 = Reacs.elmt_reaction1;
        elmt_ERM.elmt_reaction0 = Reacs.elmt_reaction0;
        elmt_ERM.elmt_reactant32 = Reacs.elmt_reactant32;
        elmt_ERM.elmt_reactant22 = Reacs.elmt_reactant22;

end Hernjak2005_Calcium_Signaling;
