within BIOMD202;
model ChenXF2008_CICR "ChenXF2008_CICR" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_Cytoplasm elmt_Cytoplasm;
    Class_elmt_ER elmt_ER;
    Class_elmt_PM elmt_PM;

    equation
        Params.elmt_Ca_Cyt = elmt_Cytoplasm.elmt_Ca_Cyt;
        Reacs.elmt_p = Params.elmt_p;
        Reacs.elmt_Vs4 = Params.elmt_Vs4;
        Reacs.elmt_kdo = Params.elmt_kdo;
        Reacs.elmt_V_PMleak = Params.elmt_V_PMleak;
        Reacs.elmt_Ko = Params.elmt_Ko;
        Reacs.elmt_Orai1 = elmt_PM.elmt_Orai1;
        Reacs.elmt_S4 = elmt_ER.elmt_S4;
        Reacs.elmt_S2 = elmt_ER.elmt_S2;
        Reacs.elmt_Ca_Cyt = elmt_Cytoplasm.elmt_Ca_Cyt;
        Reacs.elmt_V_PMCA = Params.elmt_V_PMCA;
        Reacs.elmt_O_o = elmt_PM.elmt_O_o;
        Reacs.elmt_kod = Params.elmt_kod;
        Reacs.elmt_h = Params.elmt_h;
        Reacs.elmt_V_SERCA = Params.elmt_V_SERCA;
        Reacs.elmt_Ca_ec = Params.elmt_Ca_ec;
        Reacs.elmt_K_PMCA = Params.elmt_K_PMCA;
        Reacs.elmt_l_hill = Params.elmt_l_hill;
        Reacs.elmt_K2 = Params.elmt_K2;
        Reacs.elmt_Ka = Params.elmt_Ka;
        Reacs.elmt_Oc = elmt_PM.elmt_Oc;
        Reacs.elmt_K_SERCA = Params.elmt_K_SERCA;
        Reacs.elmt_IP3_Cyt = elmt_Cytoplasm.elmt_IP3_Cyt;
        Reacs.elmt_K_deg = Params.elmt_K_deg;
        Reacs.elmt_Vcp = Params.elmt_Vcp;
        Reacs.elmt_S2a = elmt_ER.elmt_S2a;
        Reacs.elmt_K_PLC = Params.elmt_K_PLC;
        Reacs.elmt_kd_oligo = Params.elmt_kd_oligo;
        Reacs.elmt_PM = elmt_PM.elmt_PM;
        Reacs.elmt_Ca_ER = elmt_ER.elmt_Ca_ER;
        Reacs.elmt_Ki = Params.elmt_Ki;
        Reacs.elmt_k_a = Params.elmt_k_a;
        Reacs.elmt_kop = Params.elmt_kop;
        Reacs.elmt_Kc = Params.elmt_Kc;
        Reacs.elmt_Cytoplasm = elmt_Cytoplasm.elmt_Cytoplasm;
        Reacs.elmt_k_i = Params.elmt_k_i;
        Reacs.elmt_L = Params.elmt_L;
        Reacs.elmt_ER = elmt_ER.elmt_ER;
        Reacs.elmt_kdeg = Params.elmt_kdeg;
        Reacs.elmt_n_hill = Params.elmt_n_hill;
        Reacs.elmt_P_IP3R = Params.elmt_P_IP3R;
        Reacs.elmt_k_soc = Params.elmt_k_soc;
        Reacs.elmt_V_PLC = Params.elmt_V_PLC;
        Reacs.elmt_kdc = Params.elmt_kdc;
        Reacs.elmt_q = Params.elmt_q;
        elmt_PM.elmt_closed_CRAC_channel_deg = Reacs.elmt_closed_CRAC_channel_deg;
        elmt_PM.elmt_product12 = Reacs.elmt_product12;
        elmt_PM.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_PM.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_PM.elmt_open_CRAC_channel_deg = Reacs.elmt_open_CRAC_channel_deg;
        elmt_PM.elmt_open_to_closed = Reacs.elmt_open_to_closed;
        elmt_PM.elmt_Orai1_t = Params.elmt_Orai1_t;
        elmt_PM.elmt_reactant13 = Reacs.elmt_reactant13;
        elmt_PM.elmt_open_CRAC_channel_prod = Reacs.elmt_open_CRAC_channel_prod;
        elmt_PM.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_PM.elmt_close_CRAC_prod = Reacs.elmt_close_CRAC_prod;
        elmt_PM.elmt_product15 = Reacs.elmt_product15;
        elmt_PM.elmt_r_hill = Params.elmt_r_hill;
        elmt_PM.elmt_product17 = Reacs.elmt_product17;
        elmt_Cytoplasm.elmt_PLC = Reacs.elmt_PLC;
        elmt_Cytoplasm.elmt_reactant2 = Reacs.elmt_reactant2;
        elmt_Cytoplasm.elmt_ER_Channel = Reacs.elmt_ER_Channel;
        elmt_Cytoplasm.elmt_deg = Reacs.elmt_deg;
        elmt_Cytoplasm.elmt_product6 = Reacs.elmt_product6;
        elmt_Cytoplasm.elmt_PMCA = Reacs.elmt_PMCA;
        elmt_Cytoplasm.elmt_reactant5 = Reacs.elmt_reactant5;
        elmt_Cytoplasm.elmt_reactant7 = Reacs.elmt_reactant7;
        elmt_Cytoplasm.elmt_SERCA = Reacs.elmt_SERCA;
        elmt_Cytoplasm.elmt_PM_Channel = Reacs.elmt_PM_Channel;
        elmt_Cytoplasm.elmt_product1 = Reacs.elmt_product1;
        elmt_Cytoplasm.elmt_product4 = Reacs.elmt_product4;
        elmt_ER.elmt_K1 = Params.elmt_K1;
        elmt_ER.elmt_product8 = Reacs.elmt_product8;
        elmt_ER.elmt_St = Params.elmt_St;
        elmt_ER.elmt_product10 = Reacs.elmt_product10;
        elmt_ER.elmt_reactant11 = Reacs.elmt_reactant11;
        elmt_ER.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_ER.elmt_product3 = Reacs.elmt_product3;
        elmt_ER.elmt_act_apoSTIM1_deg = Reacs.elmt_act_apoSTIM1_deg;
        elmt_ER.elmt_ER_Channel = Reacs.elmt_ER_Channel;
        elmt_ER.elmt_act_apoSTIM1_syn = Reacs.elmt_act_apoSTIM1_syn;
        elmt_ER.elmt_SERCA = Reacs.elmt_SERCA;
        elmt_ER.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_ER.elmt_apoSTIM1_oligo_deg = Reacs.elmt_apoSTIM1_oligo_deg;
        elmt_ER.elmt_apoSTIM1_oligo_syn = Reacs.elmt_apoSTIM1_oligo_syn;

end ChenXF2008_CICR;
