# Makefile generated by OpenModelica
# Platform: linux64

# Simulations use -O3 by default
CC=clang
CXX=clang++
LINK=clang -shared
EXEEXT=
DLLEXT=.so
CFLAGS_BASED_ON_INIT_FILE=
DEBUG_FLAGS=-Os
CFLAGS=$(CFLAGS_BASED_ON_INIT_FILE) $(DEBUG_FLAGS) -fPIC -falign-functions -mfpmath=sse -fno-dollars-in-identifiers ${MODELICAUSERCFLAGS}   
CPPFLAGS= -I"/usr/bin/../include/omc/c" -I. -DOPENMODELICA_XML_FROM_FILE_AT_RUNTIME -DOMC_MODEL_PREFIX=BIOMD033_Brown2004_NGF_EGF_signaling -DOMC_NUM_MIXED_SYSTEMS=0 -DOMC_NUM_LINEAR_SYSTEMS=0 -DOMC_NUM_NONLINEAR_SYSTEMS=1 -DOMC_NDELAY_EXPRESSIONS=0 -DOMC_NVAR_STRING=0
LDFLAGS=-L"/usr/bin/../lib/x86_64-linux-gnu/omc" -L"/usr/bin/../lib" -Wl,-rpath,"/usr/bin/../lib/x86_64-linux-gnu/omc" -Wl,-rpath,"/usr/bin/../lib"     -Wl,--no-as-needed -Wl,--disable-new-dtags -lSimulationRuntimeC -llapack -lblas -lm -lm -lomcgc -lpthread -rdynamic -Wl,--no-undefined 
DIREXTRA=-L"/home/yorunoomo/Scrivania/Tirocinio/util/Software/sbml2Modelica/test/biomodels/modelica/BIOMD033"
MAINFILE=BIOMD033.Brown2004_NGF_EGF_signaling.c
MAINOBJ=BIOMD033.Brown2004_NGF_EGF_signaling.o
CFILES=BIOMD033.Brown2004_NGF_EGF_signaling_functions.c BIOMD033.Brown2004_NGF_EGF_signaling_records.c \
BIOMD033.Brown2004_NGF_EGF_signaling_01exo.c BIOMD033.Brown2004_NGF_EGF_signaling_02nls.c BIOMD033.Brown2004_NGF_EGF_signaling_03lsy.c BIOMD033.Brown2004_NGF_EGF_signaling_04set.c BIOMD033.Brown2004_NGF_EGF_signaling_05evt.c BIOMD033.Brown2004_NGF_EGF_signaling_06inz.c BIOMD033.Brown2004_NGF_EGF_signaling_07dly.c \
BIOMD033.Brown2004_NGF_EGF_signaling_08bnd.c BIOMD033.Brown2004_NGF_EGF_signaling_09alg.c BIOMD033.Brown2004_NGF_EGF_signaling_10asr.c BIOMD033.Brown2004_NGF_EGF_signaling_11mix.c BIOMD033.Brown2004_NGF_EGF_signaling_12jac.c BIOMD033.Brown2004_NGF_EGF_signaling_13opt.c BIOMD033.Brown2004_NGF_EGF_signaling_14lnz.c \
BIOMD033.Brown2004_NGF_EGF_signaling_15syn.c BIOMD033.Brown2004_NGF_EGF_signaling_16dae.c BIOMD033.Brown2004_NGF_EGF_signaling_17inl.c 

OFILES=$(CFILES:.c=.o)
GENERATEDFILES=$(MAINFILE) BIOMD033.Brown2004_NGF_EGF_signaling.makefile BIOMD033.Brown2004_NGF_EGF_signaling_literals.h BIOMD033.Brown2004_NGF_EGF_signaling_functions.h $(CFILES)

.PHONY: omc_main_target clean bundle

# This is to make sure that BIOMD033.Brown2004_NGF_EGF_signaling_*.c are always compiled.
.PHONY: $(CFILES)

omc_main_target: $(MAINOBJ) BIOMD033.Brown2004_NGF_EGF_signaling_functions.h BIOMD033.Brown2004_NGF_EGF_signaling_literals.h $(OFILES)
	$(CC) -I. -o BIOMD033.Brown2004_NGF_EGF_signaling$(EXEEXT) $(MAINOBJ) $(OFILES) $(CPPFLAGS) $(DIREXTRA)   $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
clean:
	@rm -f BIOMD033.Brown2004_NGF_EGF_signaling_records.o $(MAINOBJ)

bundle:
	@tar -cvf BIOMD033.Brown2004_NGF_EGF_signaling_Files.tar $(GENERATEDFILES)