/* Simulation code for BIOMD033.Brown2004_NGF_EGF_signaling generated by the OpenModelica Compiler OpenModelica 1.16.1. */
#if !defined(BIOMD033_Brown2004_NGF_EGF_signaling__MODEL_H)
#define BIOMD033_Brown2004_NGF_EGF_signaling__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "BIOMD033.Brown2004_NGF_EGF_signaling_functions.h"


extern void BIOMD033_Brown2004_NGF_EGF_signaling_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void BIOMD033_Brown2004_NGF_EGF_signaling_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void BIOMD033_Brown2004_NGF_EGF_signaling_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_checkForAsserts(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* BIOMD033_Brown2004_NGF_EGF_signaling_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* BIOMD033_Brown2004_NGF_EGF_signaling_relationDescription(int i);
extern void BIOMD033_Brown2004_NGF_EGF_signaling_function_initSample(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_initialAnalyticJacobianF(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionJacF_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* BIOMD033_Brown2004_NGF_EGF_signaling_linear_model_frame(void);
extern const char* BIOMD033_Brown2004_NGF_EGF_signaling_linear_model_datarecovery_frame(void);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_mayer(DATA* data, modelica_real** res, short *);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_setInputData(DATA *data, const modelica_boolean file);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void BIOMD033_Brown2004_NGF_EGF_signaling_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void BIOMD033_Brown2004_NGF_EGF_signaling_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void BIOMD033_Brown2004_NGF_EGF_signaling_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void BIOMD033_Brown2004_NGF_EGF_signaling_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_inputNames(DATA* data, char ** names);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_functionLocalKnownVars(DATA*, threadData_t*);
extern int BIOMD033_Brown2004_NGF_EGF_signaling_symbolicInlineSystem(DATA*, threadData_t*);

#include "BIOMD033.Brown2004_NGF_EGF_signaling_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(BIOMD033_Brown2004_NGF_EGF_signaling__MODEL_H) */


