/* Additional record code for BIOMD033.Brown2004_NGF_EGF_signaling generated by the OpenModelica Compiler OpenModelica 1.16.1. */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "BIOMD033.Brown2004_NGF_EGF_signaling_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

