/* Simulation code for DTS generated by the OpenModelica Compiler OpenModelica 1.13.0~dev-803-gd154693. */
#if !defined(DTS__MODEL_H)
#define DTS__MODEL_H
#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "DTS_functions.h"


extern void DTS_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void DTS_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int DTS_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int DTS_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int DTS_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int DTS_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int DTS_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int DTS_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int DTS_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int DTS_checkForAsserts(DATA *data, threadData_t *threadData);
extern int DTS_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int DTS_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int DTS_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* DTS_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* DTS_relationDescription(int i);
extern void DTS_function_initSample(DATA *data, threadData_t *threadData);
extern int DTS_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int DTS_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int DTS_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int DTS_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int DTS_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int DTS_functionJacG_column(void* data, threadData_t *threadData);
extern int DTS_functionJacA_column(void* data, threadData_t *threadData);
extern int DTS_functionJacB_column(void* data, threadData_t *threadData);
extern int DTS_functionJacC_column(void* data, threadData_t *threadData);
extern int DTS_functionJacD_column(void* data, threadData_t *threadData);
extern const char* DTS_linear_model_frame(void);
extern const char* DTS_linear_model_datarecovery_frame(void);
extern int DTS_mayer(DATA* data, modelica_real** res, short *);
extern int DTS_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int DTS_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int DTS_setInputData(DATA *data, const modelica_boolean file);
extern int DTS_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void DTS_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void DTS_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int DTS_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void DTS_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void DTS_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int DTS_inputNames(DATA* data, char ** names);
extern int DTS_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int DTS_functionLocalKnownVars(DATA*, threadData_t*);
extern int DTS_symbolicInlineSystem(DATA*, threadData_t*);

#include "DTS_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#endif

