/* Additional record code for DTS generated by the OpenModelica Compiler OpenModelica 1.13.0~dev-803-gd154693. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

