

#include <iostream>
#include <vector>
#include <iomanip>
#include <string>
#include <fstream>

#include "CocurrentHeatExchangerEquations_N_80_SystemDefinition.cuh"
#include "SingleSystem_PerThread_Interface.cuh"

using namespace std;

#define SOLVER RKCK45 // Runge-Kutta Order 4th
#define PRECISION double
const int NT   = 1;
const int SD   = 237;
const int NCP  = 1;
const int NSP  = 13;
const int NISP = 1;
const int NE   = 0;
const int NA   = 163;
const int NIA  = 0;
const int NDO  = 100000;


void FillSolverObject(
    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION>& Solver, 
    int FirstProblemNumber, int NumberOfThreads
) {
    int k_begin = FirstProblemNumber;
    int k_end   = FirstProblemNumber + NumberOfThreads;
	
    int ProblemNumber = 0;
    while (k_begin < k_end) {
        Solver.SetHost(ProblemNumber, TimeDomain, 0, 0.0);
        Solver.SetHost(ProblemNumber, TimeDomain, 1, 20.0);  

        // Settaggio dei valori iniziali degli ActualState
 

        Solver.SetHost(ProblemNumber, ActualTime, 0.0);
        Solver.SetHost(ProblemNumber, ControlParameters, 0, 0.0);
        Solver.SetHost(ProblemNumber, DenseIndex, 0 );

        // Settaggio dei valori iniziali per ACC (se presenti)


        // Settaggio dei valori iniziali per ACCi (se presenti)

		
        ProblemNumber++;
        k_begin++;
    }

    // Settaggio dei valori iniziali per sPAR (se presenti)


    // Settaggio dei valori iniziali per sPARi (se presenti)

}


void SaveData(
    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION>& Solver, 
    ofstream& DataFile, int NumberOfThreads
) {
    int Width = 18;
    DataFile.precision(10);
    DataFile.flags(ios::scientific);
	
    for (int tid=0; tid<NumberOfThreads; tid++)
    {
        DataFile.width(Width); DataFile << "X_TA[2]" << ',';
        DataFile.width(Width); DataFile << "X_TA[3]" << ',';
        DataFile.width(Width); DataFile << "X_TA[4]" << ',';
        DataFile.width(Width); DataFile << "X_TA[5]" << ',';
        DataFile.width(Width); DataFile << "X_TA[6]" << ',';
        DataFile.width(Width); DataFile << "X_TA[7]" << ',';
        DataFile.width(Width); DataFile << "X_TA[8]" << ',';
        DataFile.width(Width); DataFile << "X_TA[9]" << ',';
        DataFile.width(Width); DataFile << "X_TA[10]" << ',';
        DataFile.width(Width); DataFile << "X_TA[11]" << ',';
        DataFile.width(Width); DataFile << "X_TA[12]" << ',';
        DataFile.width(Width); DataFile << "X_TA[13]" << ',';
        DataFile.width(Width); DataFile << "X_TA[14]" << ',';
        DataFile.width(Width); DataFile << "X_TA[15]" << ',';
        DataFile.width(Width); DataFile << "X_TA[16]" << ',';
        DataFile.width(Width); DataFile << "X_TA[17]" << ',';
        DataFile.width(Width); DataFile << "X_TA[18]" << ',';
        DataFile.width(Width); DataFile << "X_TA[19]" << ',';
        DataFile.width(Width); DataFile << "X_TA[20]" << ',';
        DataFile.width(Width); DataFile << "X_TA[21]" << ',';
        DataFile.width(Width); DataFile << "X_TA[22]" << ',';
        DataFile.width(Width); DataFile << "X_TA[23]" << ',';
        DataFile.width(Width); DataFile << "X_TA[24]" << ',';
        DataFile.width(Width); DataFile << "X_TA[25]" << ',';
        DataFile.width(Width); DataFile << "X_TA[26]" << ',';
        DataFile.width(Width); DataFile << "X_TA[27]" << ',';
        DataFile.width(Width); DataFile << "X_TA[28]" << ',';
        DataFile.width(Width); DataFile << "X_TA[29]" << ',';
        DataFile.width(Width); DataFile << "X_TA[30]" << ',';
        DataFile.width(Width); DataFile << "X_TA[31]" << ',';
        DataFile.width(Width); DataFile << "X_TA[32]" << ',';
        DataFile.width(Width); DataFile << "X_TA[33]" << ',';
        DataFile.width(Width); DataFile << "X_TA[34]" << ',';
        DataFile.width(Width); DataFile << "X_TA[35]" << ',';
        DataFile.width(Width); DataFile << "X_TA[36]" << ',';
        DataFile.width(Width); DataFile << "X_TA[37]" << ',';
        DataFile.width(Width); DataFile << "X_TA[38]" << ',';
        DataFile.width(Width); DataFile << "X_TA[39]" << ',';
        DataFile.width(Width); DataFile << "X_TA[40]" << ',';
        DataFile.width(Width); DataFile << "X_TA[41]" << ',';
        DataFile.width(Width); DataFile << "X_TA[42]" << ',';
        DataFile.width(Width); DataFile << "X_TA[43]" << ',';
        DataFile.width(Width); DataFile << "X_TA[44]" << ',';
        DataFile.width(Width); DataFile << "X_TA[45]" << ',';
        DataFile.width(Width); DataFile << "X_TA[46]" << ',';
        DataFile.width(Width); DataFile << "X_TA[47]" << ',';
        DataFile.width(Width); DataFile << "X_TA[48]" << ',';
        DataFile.width(Width); DataFile << "X_TA[49]" << ',';
        DataFile.width(Width); DataFile << "X_TA[50]" << ',';
        DataFile.width(Width); DataFile << "X_TA[51]" << ',';
        DataFile.width(Width); DataFile << "X_TA[52]" << ',';
        DataFile.width(Width); DataFile << "X_TA[53]" << ',';
        DataFile.width(Width); DataFile << "X_TA[54]" << ',';
        DataFile.width(Width); DataFile << "X_TA[55]" << ',';
        DataFile.width(Width); DataFile << "X_TA[56]" << ',';
        DataFile.width(Width); DataFile << "X_TA[57]" << ',';
        DataFile.width(Width); DataFile << "X_TA[58]" << ',';
        DataFile.width(Width); DataFile << "X_TA[59]" << ',';
        DataFile.width(Width); DataFile << "X_TA[60]" << ',';
        DataFile.width(Width); DataFile << "X_TA[61]" << ',';
        DataFile.width(Width); DataFile << "X_TA[62]" << ',';
        DataFile.width(Width); DataFile << "X_TA[63]" << ',';
        DataFile.width(Width); DataFile << "X_TA[64]" << ',';
        DataFile.width(Width); DataFile << "X_TA[65]" << ',';
        DataFile.width(Width); DataFile << "X_TA[66]" << ',';
        DataFile.width(Width); DataFile << "X_TA[67]" << ',';
        DataFile.width(Width); DataFile << "X_TA[68]" << ',';
        DataFile.width(Width); DataFile << "X_TA[69]" << ',';
        DataFile.width(Width); DataFile << "X_TA[70]" << ',';
        DataFile.width(Width); DataFile << "X_TA[71]" << ',';
        DataFile.width(Width); DataFile << "X_TA[72]" << ',';
        DataFile.width(Width); DataFile << "X_TA[73]" << ',';
        DataFile.width(Width); DataFile << "X_TA[74]" << ',';
        DataFile.width(Width); DataFile << "X_TA[75]" << ',';
        DataFile.width(Width); DataFile << "X_TA[76]" << ',';
        DataFile.width(Width); DataFile << "X_TA[77]" << ',';
        DataFile.width(Width); DataFile << "X_TA[78]" << ',';
        DataFile.width(Width); DataFile << "X_TA[79]" << ',';
        DataFile.width(Width); DataFile << "X_TA[80]" << ',';
        DataFile.width(Width); DataFile << "X_TB[2]" << ',';
        DataFile.width(Width); DataFile << "X_TB[3]" << ',';
        DataFile.width(Width); DataFile << "X_TB[4]" << ',';
        DataFile.width(Width); DataFile << "X_TB[5]" << ',';
        DataFile.width(Width); DataFile << "X_TB[6]" << ',';
        DataFile.width(Width); DataFile << "X_TB[7]" << ',';
        DataFile.width(Width); DataFile << "X_TB[8]" << ',';
        DataFile.width(Width); DataFile << "X_TB[9]" << ',';
        DataFile.width(Width); DataFile << "X_TB[10]" << ',';
        DataFile.width(Width); DataFile << "X_TB[11]" << ',';
        DataFile.width(Width); DataFile << "X_TB[12]" << ',';
        DataFile.width(Width); DataFile << "X_TB[13]" << ',';
        DataFile.width(Width); DataFile << "X_TB[14]" << ',';
        DataFile.width(Width); DataFile << "X_TB[15]" << ',';
        DataFile.width(Width); DataFile << "X_TB[16]" << ',';
        DataFile.width(Width); DataFile << "X_TB[17]" << ',';
        DataFile.width(Width); DataFile << "X_TB[18]" << ',';
        DataFile.width(Width); DataFile << "X_TB[19]" << ',';
        DataFile.width(Width); DataFile << "X_TB[20]" << ',';
        DataFile.width(Width); DataFile << "X_TB[21]" << ',';
        DataFile.width(Width); DataFile << "X_TB[22]" << ',';
        DataFile.width(Width); DataFile << "X_TB[23]" << ',';
        DataFile.width(Width); DataFile << "X_TB[24]" << ',';
        DataFile.width(Width); DataFile << "X_TB[25]" << ',';
        DataFile.width(Width); DataFile << "X_TB[26]" << ',';
        DataFile.width(Width); DataFile << "X_TB[27]" << ',';
        DataFile.width(Width); DataFile << "X_TB[28]" << ',';
        DataFile.width(Width); DataFile << "X_TB[29]" << ',';
        DataFile.width(Width); DataFile << "X_TB[30]" << ',';
        DataFile.width(Width); DataFile << "X_TB[31]" << ',';
        DataFile.width(Width); DataFile << "X_TB[32]" << ',';
        DataFile.width(Width); DataFile << "X_TB[33]" << ',';
        DataFile.width(Width); DataFile << "X_TB[34]" << ',';
        DataFile.width(Width); DataFile << "X_TB[35]" << ',';
        DataFile.width(Width); DataFile << "X_TB[36]" << ',';
        DataFile.width(Width); DataFile << "X_TB[37]" << ',';
        DataFile.width(Width); DataFile << "X_TB[38]" << ',';
        DataFile.width(Width); DataFile << "X_TB[39]" << ',';
        DataFile.width(Width); DataFile << "X_TB[40]" << ',';
        DataFile.width(Width); DataFile << "X_TB[41]" << ',';
        DataFile.width(Width); DataFile << "X_TB[42]" << ',';
        DataFile.width(Width); DataFile << "X_TB[43]" << ',';
        DataFile.width(Width); DataFile << "X_TB[44]" << ',';
        DataFile.width(Width); DataFile << "X_TB[45]" << ',';
        DataFile.width(Width); DataFile << "X_TB[46]" << ',';
        DataFile.width(Width); DataFile << "X_TB[47]" << ',';
        DataFile.width(Width); DataFile << "X_TB[48]" << ',';
        DataFile.width(Width); DataFile << "X_TB[49]" << ',';
        DataFile.width(Width); DataFile << "X_TB[50]" << ',';
        DataFile.width(Width); DataFile << "X_TB[51]" << ',';
        DataFile.width(Width); DataFile << "X_TB[52]" << ',';
        DataFile.width(Width); DataFile << "X_TB[53]" << ',';
        DataFile.width(Width); DataFile << "X_TB[54]" << ',';
        DataFile.width(Width); DataFile << "X_TB[55]" << ',';
        DataFile.width(Width); DataFile << "X_TB[56]" << ',';
        DataFile.width(Width); DataFile << "X_TB[57]" << ',';
        DataFile.width(Width); DataFile << "X_TB[58]" << ',';
        DataFile.width(Width); DataFile << "X_TB[59]" << ',';
        DataFile.width(Width); DataFile << "X_TB[60]" << ',';
        DataFile.width(Width); DataFile << "X_TB[61]" << ',';
        DataFile.width(Width); DataFile << "X_TB[62]" << ',';
        DataFile.width(Width); DataFile << "X_TB[63]" << ',';
        DataFile.width(Width); DataFile << "X_TB[64]" << ',';
        DataFile.width(Width); DataFile << "X_TB[65]" << ',';
        DataFile.width(Width); DataFile << "X_TB[66]" << ',';
        DataFile.width(Width); DataFile << "X_TB[67]" << ',';
        DataFile.width(Width); DataFile << "X_TB[68]" << ',';
        DataFile.width(Width); DataFile << "X_TB[69]" << ',';
        DataFile.width(Width); DataFile << "X_TB[70]" << ',';
        DataFile.width(Width); DataFile << "X_TB[71]" << ',';
        DataFile.width(Width); DataFile << "X_TB[72]" << ',';
        DataFile.width(Width); DataFile << "X_TB[73]" << ',';
        DataFile.width(Width); DataFile << "X_TB[74]" << ',';
        DataFile.width(Width); DataFile << "X_TB[75]" << ',';
        DataFile.width(Width); DataFile << "X_TB[76]" << ',';
        DataFile.width(Width); DataFile << "X_TB[77]" << ',';
        DataFile.width(Width); DataFile << "X_TB[78]" << ',';
        DataFile.width(Width); DataFile << "X_TB[79]" << ',';
        DataFile.width(Width); DataFile << "X_TB[80]" << ',';
        DataFile.width(Width); DataFile << "X_TW[1]" << ',';
        DataFile.width(Width); DataFile << "X_TW[2]" << ',';
        DataFile.width(Width); DataFile << "X_TW[3]" << ',';
        DataFile.width(Width); DataFile << "X_TW[4]" << ',';
        DataFile.width(Width); DataFile << "X_TW[5]" << ',';
        DataFile.width(Width); DataFile << "X_TW[6]" << ',';
        DataFile.width(Width); DataFile << "X_TW[7]" << ',';
        DataFile.width(Width); DataFile << "X_TW[8]" << ',';
        DataFile.width(Width); DataFile << "X_TW[9]" << ',';
        DataFile.width(Width); DataFile << "X_TW[10]" << ',';
        DataFile.width(Width); DataFile << "X_TW[11]" << ',';
        DataFile.width(Width); DataFile << "X_TW[12]" << ',';
        DataFile.width(Width); DataFile << "X_TW[13]" << ',';
        DataFile.width(Width); DataFile << "X_TW[14]" << ',';
        DataFile.width(Width); DataFile << "X_TW[15]" << ',';
        DataFile.width(Width); DataFile << "X_TW[16]" << ',';
        DataFile.width(Width); DataFile << "X_TW[17]" << ',';
        DataFile.width(Width); DataFile << "X_TW[18]" << ',';
        DataFile.width(Width); DataFile << "X_TW[19]" << ',';
        DataFile.width(Width); DataFile << "X_TW[20]" << ',';
        DataFile.width(Width); DataFile << "X_TW[21]" << ',';
        DataFile.width(Width); DataFile << "X_TW[22]" << ',';
        DataFile.width(Width); DataFile << "X_TW[23]" << ',';
        DataFile.width(Width); DataFile << "X_TW[24]" << ',';
        DataFile.width(Width); DataFile << "X_TW[25]" << ',';
        DataFile.width(Width); DataFile << "X_TW[26]" << ',';
        DataFile.width(Width); DataFile << "X_TW[27]" << ',';
        DataFile.width(Width); DataFile << "X_TW[28]" << ',';
        DataFile.width(Width); DataFile << "X_TW[29]" << ',';
        DataFile.width(Width); DataFile << "X_TW[30]" << ',';
        DataFile.width(Width); DataFile << "X_TW[31]" << ',';
        DataFile.width(Width); DataFile << "X_TW[32]" << ',';
        DataFile.width(Width); DataFile << "X_TW[33]" << ',';
        DataFile.width(Width); DataFile << "X_TW[34]" << ',';
        DataFile.width(Width); DataFile << "X_TW[35]" << ',';
        DataFile.width(Width); DataFile << "X_TW[36]" << ',';
        DataFile.width(Width); DataFile << "X_TW[37]" << ',';
        DataFile.width(Width); DataFile << "X_TW[38]" << ',';
        DataFile.width(Width); DataFile << "X_TW[39]" << ',';
        DataFile.width(Width); DataFile << "X_TW[40]" << ',';
        DataFile.width(Width); DataFile << "X_TW[41]" << ',';
        DataFile.width(Width); DataFile << "X_TW[42]" << ',';
        DataFile.width(Width); DataFile << "X_TW[43]" << ',';
        DataFile.width(Width); DataFile << "X_TW[44]" << ',';
        DataFile.width(Width); DataFile << "X_TW[45]" << ',';
        DataFile.width(Width); DataFile << "X_TW[46]" << ',';
        DataFile.width(Width); DataFile << "X_TW[47]" << ',';
        DataFile.width(Width); DataFile << "X_TW[48]" << ',';
        DataFile.width(Width); DataFile << "X_TW[49]" << ',';
        DataFile.width(Width); DataFile << "X_TW[50]" << ',';
        DataFile.width(Width); DataFile << "X_TW[51]" << ',';
        DataFile.width(Width); DataFile << "X_TW[52]" << ',';
        DataFile.width(Width); DataFile << "X_TW[53]" << ',';
        DataFile.width(Width); DataFile << "X_TW[54]" << ',';
        DataFile.width(Width); DataFile << "X_TW[55]" << ',';
        DataFile.width(Width); DataFile << "X_TW[56]" << ',';
        DataFile.width(Width); DataFile << "X_TW[57]" << ',';
        DataFile.width(Width); DataFile << "X_TW[58]" << ',';
        DataFile.width(Width); DataFile << "X_TW[59]" << ',';
        DataFile.width(Width); DataFile << "X_TW[60]" << ',';
        DataFile.width(Width); DataFile << "X_TW[61]" << ',';
        DataFile.width(Width); DataFile << "X_TW[62]" << ',';
        DataFile.width(Width); DataFile << "X_TW[63]" << ',';
        DataFile.width(Width); DataFile << "X_TW[64]" << ',';
        DataFile.width(Width); DataFile << "X_TW[65]" << ',';
        DataFile.width(Width); DataFile << "X_TW[66]" << ',';
        DataFile.width(Width); DataFile << "X_TW[67]" << ',';
        DataFile.width(Width); DataFile << "X_TW[68]" << ',';
        DataFile.width(Width); DataFile << "X_TW[69]" << ',';
        DataFile.width(Width); DataFile << "X_TW[70]" << ',';
        DataFile.width(Width); DataFile << "X_TW[71]" << ',';
        DataFile.width(Width); DataFile << "X_TW[72]" << ',';
        DataFile.width(Width); DataFile << "X_TW[73]" << ',';
        DataFile.width(Width); DataFile << "X_TW[74]" << ',';
        DataFile.width(Width); DataFile << "X_TW[75]" << ',';
        DataFile.width(Width); DataFile << "X_TW[76]" << ',';
        DataFile.width(Width); DataFile << "X_TW[77]" << ',';
        DataFile.width(Width); DataFile << "X_TW[78]" << ',';
        DataFile.width(Width); DataFile << "X_TW[79]" << ',';
        DataFile.width(Width); DataFile << "sPAR_L" << ',';
        DataFile.width(Width); DataFile << "sPAR_areaA" << ',';
        DataFile.width(Width); DataFile << "sPAR_areaB" << ',';
        DataFile.width(Width); DataFile << "sPAR_cpA" << ',';
        DataFile.width(Width); DataFile << "sPAR_cpB" << ',';
        DataFile.width(Width); DataFile << "sPAR_cpW" << ',';
        DataFile.width(Width); DataFile << "sPAR_gammaA" << ',';
        DataFile.width(Width); DataFile << "sPAR_gammaB" << ',';
        DataFile.width(Width); DataFile << "sPAR_l" << ',';
        DataFile.width(Width); DataFile << "sPAR_omega" << ',';
        DataFile.width(Width); DataFile << "sPAR_rhoA" << ',';
        DataFile.width(Width); DataFile << "sPAR_rhoB" << ',';
        DataFile.width(Width); DataFile << "sPAR_wB" << ',';
        DataFile.width(Width); DataFile << "sPARi_N" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[1]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[2]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[3]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[4]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[5]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[6]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[7]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[8]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[9]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[10]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[11]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[12]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[13]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[14]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[15]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[16]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[17]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[18]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[19]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[20]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[21]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[22]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[23]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[24]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[25]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[26]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[27]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[28]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[29]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[30]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[31]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[32]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[33]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[34]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[35]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[36]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[37]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[38]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[39]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[40]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[41]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[42]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[43]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[44]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[45]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[46]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[47]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[48]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[49]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[50]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[51]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[52]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[53]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[54]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[55]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[56]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[57]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[58]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[59]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[60]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[61]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[62]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[63]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[64]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[65]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[66]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[67]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[68]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[69]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[70]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[71]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[72]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[73]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[74]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[75]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[76]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[77]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[78]" << ',';
        DataFile.width(Width); DataFile << "ACC_QA[79]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[1]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[2]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[3]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[4]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[5]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[6]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[7]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[8]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[9]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[10]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[11]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[12]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[13]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[14]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[15]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[16]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[17]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[18]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[19]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[20]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[21]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[22]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[23]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[24]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[25]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[26]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[27]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[28]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[29]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[30]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[31]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[32]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[33]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[34]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[35]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[36]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[37]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[38]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[39]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[40]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[41]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[42]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[43]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[44]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[45]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[46]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[47]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[48]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[49]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[50]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[51]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[52]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[53]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[54]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[55]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[56]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[57]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[58]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[59]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[60]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[61]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[62]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[63]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[64]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[65]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[66]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[67]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[68]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[69]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[70]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[71]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[72]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[73]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[74]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[75]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[76]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[77]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[78]" << ',';
        DataFile.width(Width); DataFile << "ACC_QB[79]" << ',';
        DataFile.width(Width); DataFile << "ACC_QtotA" << ',';
        DataFile.width(Width); DataFile << "ACC_QtotB" << ',';
        DataFile.width(Width); DataFile << "ACC_TA[1]" << ',';
        DataFile.width(Width); DataFile << "ACC_TB[1]" << ',';
        DataFile.width(Width); DataFile << "ACC_wA" << ',';
        DataFile.width(Width); DataFile << endl;
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 1) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 2) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 3) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 4) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 5) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 6) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 7) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 8) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 9) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 10) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 11) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 12) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 13) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 14) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 15) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 16) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 17) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 18) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 19) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 20) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 21) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 22) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 23) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 24) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 25) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 26) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 27) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 28) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 29) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 30) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 31) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 32) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 33) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 34) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 35) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 36) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 37) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 38) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 39) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 40) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 41) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 42) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 43) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 44) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 45) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 46) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 47) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 48) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 49) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 50) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 51) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 52) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 53) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 54) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 55) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 56) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 57) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 58) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 59) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 60) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 61) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 62) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 63) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 64) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 65) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 66) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 67) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 68) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 69) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 70) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 71) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 72) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 73) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 74) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 75) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 76) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 77) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 78) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 79) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 80) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 81) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 82) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 83) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 84) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 85) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 86) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 87) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 88) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 89) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 90) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 91) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 92) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 93) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 94) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 95) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 96) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 97) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 98) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 99) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 100) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 101) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 102) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 103) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 104) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 105) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 106) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 107) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 108) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 109) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 110) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 111) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 112) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 113) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 114) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 115) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 116) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 117) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 118) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 119) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 120) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 121) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 122) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 123) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 124) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 125) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 126) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 127) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 128) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 129) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 130) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 131) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 132) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 133) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 134) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 135) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 136) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 137) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 138) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 139) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 140) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 141) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 142) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 143) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 144) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 145) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 146) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 147) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 148) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 149) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 150) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 151) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 152) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 153) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 154) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 155) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 156) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 157) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 158) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 159) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 160) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 161) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 162) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 163) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 164) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 165) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 166) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 167) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 168) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 169) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 170) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 171) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 172) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 173) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 174) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 175) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 176) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 177) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 178) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 179) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 180) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 181) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 182) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 183) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 184) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 185) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 186) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 187) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 188) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 189) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 190) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 191) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 192) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 193) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 194) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 195) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 196) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 197) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 198) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 199) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 200) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 201) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 202) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 203) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 204) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 205) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 206) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 207) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 208) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 209) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 210) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 211) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 212) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 213) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 214) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 215) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 216) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 217) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 218) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 219) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 220) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 221) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 222) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 223) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 224) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 225) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 226) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 227) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 228) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 229) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 230) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 231) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 232) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 233) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 234) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 235) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 236) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 1) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 2) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 3) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 4) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 5) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 6) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 7) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 8) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 9) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 10) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 11) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(SharedParameters, 12) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(IntegerSharedParameters, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 1) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 2) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 3) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 4) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 5) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 6) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 7) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 8) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 9) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 10) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 11) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 12) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 13) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 14) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 15) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 16) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 17) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 18) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 19) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 20) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 21) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 22) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 23) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 24) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 25) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 26) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 27) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 28) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 29) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 30) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 31) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 32) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 33) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 34) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 35) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 36) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 37) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 38) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 39) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 40) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 41) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 42) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 43) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 44) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 45) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 46) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 47) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 48) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 49) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 50) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 51) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 52) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 53) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 54) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 55) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 56) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 57) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 58) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 59) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 60) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 61) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 62) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 63) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 64) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 65) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 66) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 67) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 68) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 69) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 70) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 71) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 72) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 73) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 74) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 75) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 76) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 77) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 78) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 79) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 80) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 81) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 82) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 83) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 84) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 85) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 86) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 87) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 88) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 89) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 90) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 91) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 92) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 93) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 94) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 95) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 96) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 97) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 98) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 99) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 100) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 101) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 102) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 103) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 104) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 105) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 106) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 107) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 108) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 109) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 110) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 111) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 112) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 113) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 114) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 115) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 116) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 117) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 118) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 119) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 120) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 121) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 122) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 123) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 124) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 125) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 126) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 127) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 128) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 129) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 130) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 131) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 132) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 133) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 134) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 135) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 136) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 137) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 138) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 139) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 140) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 141) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 142) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 143) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 144) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 145) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 146) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 147) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 148) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 149) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 150) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 151) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 152) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 153) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 154) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 155) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 156) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 157) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 158) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 159) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 160) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 161) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 162) << ',';

        DataFile << '\n';
    }
}


int main() {
    int NumberOfProblems = NT; // Numero di problemi da risolvere, uno per thread
    int blockSize        = 512; // Numero di Thread per blocchi
    
    // Listing dei Device CUDA
    ListCUDADevices();

    int MajorVersion = 7; // Major version della CUDA compute capability
    int MinorVersion = 5; // Minor version della CUDA compute capability

    // Seleziona il Device da utilizzare dando in input la CUDA compute capability e ne stampa le caratteristiche
    int SelectedDevice = SelectDeviceByClosestRevision(MajorVersion, MinorVersion);
    PrintPropertiesOfSpecificDevice(SelectedDevice);

    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION> Solver(SelectedDevice);
    Solver.SolverOption(ThreadsPerBlock, blockSize);
    Solver.SolverOption(PreferSharedMemory, 1);
    Solver.SolverOption(InitialTimeStep, 0.01);
    Solver.SolverOption(ActiveNumberOfThreads, NT);
    Solver.SolverOption(MaximumTimeStep, 1000000.0);
    Solver.SolverOption(MinimumTimeStep, 1e-14);
    Solver.SolverOption(TimeStepGrowLimit, 5.0);

    Solver.SolverOption(TimeStepShrinkLimit, 0.2);



    Solver.SolverOption(DenseOutputMinimumTimeStep, 0.0);
    Solver.SolverOption(DenseOutputSaveFrequency, 1);
    Solver.SolverOption(AbsoluteTolerance, 0, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 1, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 2, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 3, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 4, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 5, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 6, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 7, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 8, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 9, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 10, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 11, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 12, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 13, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 14, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 15, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 16, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 17, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 18, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 19, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 20, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 21, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 22, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 23, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 24, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 25, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 26, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 27, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 28, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 29, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 30, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 31, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 32, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 33, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 34, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 35, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 36, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 37, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 38, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 39, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 40, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 41, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 42, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 43, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 44, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 45, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 46, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 47, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 48, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 49, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 50, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 51, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 52, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 53, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 54, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 55, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 56, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 57, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 58, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 59, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 60, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 61, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 62, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 63, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 64, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 65, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 66, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 67, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 68, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 69, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 70, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 71, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 72, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 73, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 74, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 75, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 76, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 77, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 78, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 79, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 80, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 81, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 82, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 83, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 84, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 85, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 86, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 87, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 88, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 89, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 90, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 91, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 92, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 93, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 94, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 95, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 96, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 97, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 98, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 99, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 100, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 101, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 102, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 103, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 104, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 105, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 106, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 107, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 108, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 109, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 110, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 111, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 112, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 113, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 114, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 115, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 116, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 117, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 118, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 119, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 120, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 121, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 122, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 123, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 124, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 125, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 126, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 127, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 128, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 129, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 130, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 131, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 132, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 133, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 134, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 135, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 136, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 137, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 138, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 139, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 140, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 141, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 142, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 143, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 144, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 145, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 146, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 147, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 148, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 149, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 150, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 151, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 152, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 153, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 154, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 155, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 156, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 157, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 158, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 159, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 160, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 161, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 162, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 163, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 164, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 165, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 166, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 167, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 168, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 169, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 170, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 171, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 172, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 173, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 174, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 175, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 176, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 177, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 178, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 179, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 180, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 181, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 182, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 183, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 184, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 185, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 186, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 187, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 188, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 189, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 190, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 191, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 192, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 193, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 194, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 195, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 196, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 197, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 198, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 199, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 200, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 201, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 202, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 203, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 204, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 205, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 206, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 207, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 208, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 209, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 210, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 211, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 212, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 213, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 214, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 215, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 216, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 217, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 218, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 219, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 220, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 221, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 222, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 223, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 224, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 225, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 226, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 227, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 228, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 229, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 230, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 231, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 232, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 233, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 234, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 235, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 236, 1e-06);

    Solver.SolverOption(RelativeTolerance, 0, 1e-06);
    Solver.SolverOption(RelativeTolerance, 1, 1e-06);
    Solver.SolverOption(RelativeTolerance, 2, 1e-06);
    Solver.SolverOption(RelativeTolerance, 3, 1e-06);
    Solver.SolverOption(RelativeTolerance, 4, 1e-06);
    Solver.SolverOption(RelativeTolerance, 5, 1e-06);
    Solver.SolverOption(RelativeTolerance, 6, 1e-06);
    Solver.SolverOption(RelativeTolerance, 7, 1e-06);
    Solver.SolverOption(RelativeTolerance, 8, 1e-06);
    Solver.SolverOption(RelativeTolerance, 9, 1e-06);
    Solver.SolverOption(RelativeTolerance, 10, 1e-06);
    Solver.SolverOption(RelativeTolerance, 11, 1e-06);
    Solver.SolverOption(RelativeTolerance, 12, 1e-06);
    Solver.SolverOption(RelativeTolerance, 13, 1e-06);
    Solver.SolverOption(RelativeTolerance, 14, 1e-06);
    Solver.SolverOption(RelativeTolerance, 15, 1e-06);
    Solver.SolverOption(RelativeTolerance, 16, 1e-06);
    Solver.SolverOption(RelativeTolerance, 17, 1e-06);
    Solver.SolverOption(RelativeTolerance, 18, 1e-06);
    Solver.SolverOption(RelativeTolerance, 19, 1e-06);
    Solver.SolverOption(RelativeTolerance, 20, 1e-06);
    Solver.SolverOption(RelativeTolerance, 21, 1e-06);
    Solver.SolverOption(RelativeTolerance, 22, 1e-06);
    Solver.SolverOption(RelativeTolerance, 23, 1e-06);
    Solver.SolverOption(RelativeTolerance, 24, 1e-06);
    Solver.SolverOption(RelativeTolerance, 25, 1e-06);
    Solver.SolverOption(RelativeTolerance, 26, 1e-06);
    Solver.SolverOption(RelativeTolerance, 27, 1e-06);
    Solver.SolverOption(RelativeTolerance, 28, 1e-06);
    Solver.SolverOption(RelativeTolerance, 29, 1e-06);
    Solver.SolverOption(RelativeTolerance, 30, 1e-06);
    Solver.SolverOption(RelativeTolerance, 31, 1e-06);
    Solver.SolverOption(RelativeTolerance, 32, 1e-06);
    Solver.SolverOption(RelativeTolerance, 33, 1e-06);
    Solver.SolverOption(RelativeTolerance, 34, 1e-06);
    Solver.SolverOption(RelativeTolerance, 35, 1e-06);
    Solver.SolverOption(RelativeTolerance, 36, 1e-06);
    Solver.SolverOption(RelativeTolerance, 37, 1e-06);
    Solver.SolverOption(RelativeTolerance, 38, 1e-06);
    Solver.SolverOption(RelativeTolerance, 39, 1e-06);
    Solver.SolverOption(RelativeTolerance, 40, 1e-06);
    Solver.SolverOption(RelativeTolerance, 41, 1e-06);
    Solver.SolverOption(RelativeTolerance, 42, 1e-06);
    Solver.SolverOption(RelativeTolerance, 43, 1e-06);
    Solver.SolverOption(RelativeTolerance, 44, 1e-06);
    Solver.SolverOption(RelativeTolerance, 45, 1e-06);
    Solver.SolverOption(RelativeTolerance, 46, 1e-06);
    Solver.SolverOption(RelativeTolerance, 47, 1e-06);
    Solver.SolverOption(RelativeTolerance, 48, 1e-06);
    Solver.SolverOption(RelativeTolerance, 49, 1e-06);
    Solver.SolverOption(RelativeTolerance, 50, 1e-06);
    Solver.SolverOption(RelativeTolerance, 51, 1e-06);
    Solver.SolverOption(RelativeTolerance, 52, 1e-06);
    Solver.SolverOption(RelativeTolerance, 53, 1e-06);
    Solver.SolverOption(RelativeTolerance, 54, 1e-06);
    Solver.SolverOption(RelativeTolerance, 55, 1e-06);
    Solver.SolverOption(RelativeTolerance, 56, 1e-06);
    Solver.SolverOption(RelativeTolerance, 57, 1e-06);
    Solver.SolverOption(RelativeTolerance, 58, 1e-06);
    Solver.SolverOption(RelativeTolerance, 59, 1e-06);
    Solver.SolverOption(RelativeTolerance, 60, 1e-06);
    Solver.SolverOption(RelativeTolerance, 61, 1e-06);
    Solver.SolverOption(RelativeTolerance, 62, 1e-06);
    Solver.SolverOption(RelativeTolerance, 63, 1e-06);
    Solver.SolverOption(RelativeTolerance, 64, 1e-06);
    Solver.SolverOption(RelativeTolerance, 65, 1e-06);
    Solver.SolverOption(RelativeTolerance, 66, 1e-06);
    Solver.SolverOption(RelativeTolerance, 67, 1e-06);
    Solver.SolverOption(RelativeTolerance, 68, 1e-06);
    Solver.SolverOption(RelativeTolerance, 69, 1e-06);
    Solver.SolverOption(RelativeTolerance, 70, 1e-06);
    Solver.SolverOption(RelativeTolerance, 71, 1e-06);
    Solver.SolverOption(RelativeTolerance, 72, 1e-06);
    Solver.SolverOption(RelativeTolerance, 73, 1e-06);
    Solver.SolverOption(RelativeTolerance, 74, 1e-06);
    Solver.SolverOption(RelativeTolerance, 75, 1e-06);
    Solver.SolverOption(RelativeTolerance, 76, 1e-06);
    Solver.SolverOption(RelativeTolerance, 77, 1e-06);
    Solver.SolverOption(RelativeTolerance, 78, 1e-06);
    Solver.SolverOption(RelativeTolerance, 79, 1e-06);
    Solver.SolverOption(RelativeTolerance, 80, 1e-06);
    Solver.SolverOption(RelativeTolerance, 81, 1e-06);
    Solver.SolverOption(RelativeTolerance, 82, 1e-06);
    Solver.SolverOption(RelativeTolerance, 83, 1e-06);
    Solver.SolverOption(RelativeTolerance, 84, 1e-06);
    Solver.SolverOption(RelativeTolerance, 85, 1e-06);
    Solver.SolverOption(RelativeTolerance, 86, 1e-06);
    Solver.SolverOption(RelativeTolerance, 87, 1e-06);
    Solver.SolverOption(RelativeTolerance, 88, 1e-06);
    Solver.SolverOption(RelativeTolerance, 89, 1e-06);
    Solver.SolverOption(RelativeTolerance, 90, 1e-06);
    Solver.SolverOption(RelativeTolerance, 91, 1e-06);
    Solver.SolverOption(RelativeTolerance, 92, 1e-06);
    Solver.SolverOption(RelativeTolerance, 93, 1e-06);
    Solver.SolverOption(RelativeTolerance, 94, 1e-06);
    Solver.SolverOption(RelativeTolerance, 95, 1e-06);
    Solver.SolverOption(RelativeTolerance, 96, 1e-06);
    Solver.SolverOption(RelativeTolerance, 97, 1e-06);
    Solver.SolverOption(RelativeTolerance, 98, 1e-06);
    Solver.SolverOption(RelativeTolerance, 99, 1e-06);
    Solver.SolverOption(RelativeTolerance, 100, 1e-06);
    Solver.SolverOption(RelativeTolerance, 101, 1e-06);
    Solver.SolverOption(RelativeTolerance, 102, 1e-06);
    Solver.SolverOption(RelativeTolerance, 103, 1e-06);
    Solver.SolverOption(RelativeTolerance, 104, 1e-06);
    Solver.SolverOption(RelativeTolerance, 105, 1e-06);
    Solver.SolverOption(RelativeTolerance, 106, 1e-06);
    Solver.SolverOption(RelativeTolerance, 107, 1e-06);
    Solver.SolverOption(RelativeTolerance, 108, 1e-06);
    Solver.SolverOption(RelativeTolerance, 109, 1e-06);
    Solver.SolverOption(RelativeTolerance, 110, 1e-06);
    Solver.SolverOption(RelativeTolerance, 111, 1e-06);
    Solver.SolverOption(RelativeTolerance, 112, 1e-06);
    Solver.SolverOption(RelativeTolerance, 113, 1e-06);
    Solver.SolverOption(RelativeTolerance, 114, 1e-06);
    Solver.SolverOption(RelativeTolerance, 115, 1e-06);
    Solver.SolverOption(RelativeTolerance, 116, 1e-06);
    Solver.SolverOption(RelativeTolerance, 117, 1e-06);
    Solver.SolverOption(RelativeTolerance, 118, 1e-06);
    Solver.SolverOption(RelativeTolerance, 119, 1e-06);
    Solver.SolverOption(RelativeTolerance, 120, 1e-06);
    Solver.SolverOption(RelativeTolerance, 121, 1e-06);
    Solver.SolverOption(RelativeTolerance, 122, 1e-06);
    Solver.SolverOption(RelativeTolerance, 123, 1e-06);
    Solver.SolverOption(RelativeTolerance, 124, 1e-06);
    Solver.SolverOption(RelativeTolerance, 125, 1e-06);
    Solver.SolverOption(RelativeTolerance, 126, 1e-06);
    Solver.SolverOption(RelativeTolerance, 127, 1e-06);
    Solver.SolverOption(RelativeTolerance, 128, 1e-06);
    Solver.SolverOption(RelativeTolerance, 129, 1e-06);
    Solver.SolverOption(RelativeTolerance, 130, 1e-06);
    Solver.SolverOption(RelativeTolerance, 131, 1e-06);
    Solver.SolverOption(RelativeTolerance, 132, 1e-06);
    Solver.SolverOption(RelativeTolerance, 133, 1e-06);
    Solver.SolverOption(RelativeTolerance, 134, 1e-06);
    Solver.SolverOption(RelativeTolerance, 135, 1e-06);
    Solver.SolverOption(RelativeTolerance, 136, 1e-06);
    Solver.SolverOption(RelativeTolerance, 137, 1e-06);
    Solver.SolverOption(RelativeTolerance, 138, 1e-06);
    Solver.SolverOption(RelativeTolerance, 139, 1e-06);
    Solver.SolverOption(RelativeTolerance, 140, 1e-06);
    Solver.SolverOption(RelativeTolerance, 141, 1e-06);
    Solver.SolverOption(RelativeTolerance, 142, 1e-06);
    Solver.SolverOption(RelativeTolerance, 143, 1e-06);
    Solver.SolverOption(RelativeTolerance, 144, 1e-06);
    Solver.SolverOption(RelativeTolerance, 145, 1e-06);
    Solver.SolverOption(RelativeTolerance, 146, 1e-06);
    Solver.SolverOption(RelativeTolerance, 147, 1e-06);
    Solver.SolverOption(RelativeTolerance, 148, 1e-06);
    Solver.SolverOption(RelativeTolerance, 149, 1e-06);
    Solver.SolverOption(RelativeTolerance, 150, 1e-06);
    Solver.SolverOption(RelativeTolerance, 151, 1e-06);
    Solver.SolverOption(RelativeTolerance, 152, 1e-06);
    Solver.SolverOption(RelativeTolerance, 153, 1e-06);
    Solver.SolverOption(RelativeTolerance, 154, 1e-06);
    Solver.SolverOption(RelativeTolerance, 155, 1e-06);
    Solver.SolverOption(RelativeTolerance, 156, 1e-06);
    Solver.SolverOption(RelativeTolerance, 157, 1e-06);
    Solver.SolverOption(RelativeTolerance, 158, 1e-06);
    Solver.SolverOption(RelativeTolerance, 159, 1e-06);
    Solver.SolverOption(RelativeTolerance, 160, 1e-06);
    Solver.SolverOption(RelativeTolerance, 161, 1e-06);
    Solver.SolverOption(RelativeTolerance, 162, 1e-06);
    Solver.SolverOption(RelativeTolerance, 163, 1e-06);
    Solver.SolverOption(RelativeTolerance, 164, 1e-06);
    Solver.SolverOption(RelativeTolerance, 165, 1e-06);
    Solver.SolverOption(RelativeTolerance, 166, 1e-06);
    Solver.SolverOption(RelativeTolerance, 167, 1e-06);
    Solver.SolverOption(RelativeTolerance, 168, 1e-06);
    Solver.SolverOption(RelativeTolerance, 169, 1e-06);
    Solver.SolverOption(RelativeTolerance, 170, 1e-06);
    Solver.SolverOption(RelativeTolerance, 171, 1e-06);
    Solver.SolverOption(RelativeTolerance, 172, 1e-06);
    Solver.SolverOption(RelativeTolerance, 173, 1e-06);
    Solver.SolverOption(RelativeTolerance, 174, 1e-06);
    Solver.SolverOption(RelativeTolerance, 175, 1e-06);
    Solver.SolverOption(RelativeTolerance, 176, 1e-06);
    Solver.SolverOption(RelativeTolerance, 177, 1e-06);
    Solver.SolverOption(RelativeTolerance, 178, 1e-06);
    Solver.SolverOption(RelativeTolerance, 179, 1e-06);
    Solver.SolverOption(RelativeTolerance, 180, 1e-06);
    Solver.SolverOption(RelativeTolerance, 181, 1e-06);
    Solver.SolverOption(RelativeTolerance, 182, 1e-06);
    Solver.SolverOption(RelativeTolerance, 183, 1e-06);
    Solver.SolverOption(RelativeTolerance, 184, 1e-06);
    Solver.SolverOption(RelativeTolerance, 185, 1e-06);
    Solver.SolverOption(RelativeTolerance, 186, 1e-06);
    Solver.SolverOption(RelativeTolerance, 187, 1e-06);
    Solver.SolverOption(RelativeTolerance, 188, 1e-06);
    Solver.SolverOption(RelativeTolerance, 189, 1e-06);
    Solver.SolverOption(RelativeTolerance, 190, 1e-06);
    Solver.SolverOption(RelativeTolerance, 191, 1e-06);
    Solver.SolverOption(RelativeTolerance, 192, 1e-06);
    Solver.SolverOption(RelativeTolerance, 193, 1e-06);
    Solver.SolverOption(RelativeTolerance, 194, 1e-06);
    Solver.SolverOption(RelativeTolerance, 195, 1e-06);
    Solver.SolverOption(RelativeTolerance, 196, 1e-06);
    Solver.SolverOption(RelativeTolerance, 197, 1e-06);
    Solver.SolverOption(RelativeTolerance, 198, 1e-06);
    Solver.SolverOption(RelativeTolerance, 199, 1e-06);
    Solver.SolverOption(RelativeTolerance, 200, 1e-06);
    Solver.SolverOption(RelativeTolerance, 201, 1e-06);
    Solver.SolverOption(RelativeTolerance, 202, 1e-06);
    Solver.SolverOption(RelativeTolerance, 203, 1e-06);
    Solver.SolverOption(RelativeTolerance, 204, 1e-06);
    Solver.SolverOption(RelativeTolerance, 205, 1e-06);
    Solver.SolverOption(RelativeTolerance, 206, 1e-06);
    Solver.SolverOption(RelativeTolerance, 207, 1e-06);
    Solver.SolverOption(RelativeTolerance, 208, 1e-06);
    Solver.SolverOption(RelativeTolerance, 209, 1e-06);
    Solver.SolverOption(RelativeTolerance, 210, 1e-06);
    Solver.SolverOption(RelativeTolerance, 211, 1e-06);
    Solver.SolverOption(RelativeTolerance, 212, 1e-06);
    Solver.SolverOption(RelativeTolerance, 213, 1e-06);
    Solver.SolverOption(RelativeTolerance, 214, 1e-06);
    Solver.SolverOption(RelativeTolerance, 215, 1e-06);
    Solver.SolverOption(RelativeTolerance, 216, 1e-06);
    Solver.SolverOption(RelativeTolerance, 217, 1e-06);
    Solver.SolverOption(RelativeTolerance, 218, 1e-06);
    Solver.SolverOption(RelativeTolerance, 219, 1e-06);
    Solver.SolverOption(RelativeTolerance, 220, 1e-06);
    Solver.SolverOption(RelativeTolerance, 221, 1e-06);
    Solver.SolverOption(RelativeTolerance, 222, 1e-06);
    Solver.SolverOption(RelativeTolerance, 223, 1e-06);
    Solver.SolverOption(RelativeTolerance, 224, 1e-06);
    Solver.SolverOption(RelativeTolerance, 225, 1e-06);
    Solver.SolverOption(RelativeTolerance, 226, 1e-06);
    Solver.SolverOption(RelativeTolerance, 227, 1e-06);
    Solver.SolverOption(RelativeTolerance, 228, 1e-06);
    Solver.SolverOption(RelativeTolerance, 229, 1e-06);
    Solver.SolverOption(RelativeTolerance, 230, 1e-06);
    Solver.SolverOption(RelativeTolerance, 231, 1e-06);
    Solver.SolverOption(RelativeTolerance, 232, 1e-06);
    Solver.SolverOption(RelativeTolerance, 233, 1e-06);
    Solver.SolverOption(RelativeTolerance, 234, 1e-06);
    Solver.SolverOption(RelativeTolerance, 235, 1e-06);
    Solver.SolverOption(RelativeTolerance, 236, 1e-06);
   
    
    int NumberOfSimulationLaunches = NumberOfProblems / NT + (NumberOfProblems % NT == 0 ? 0:1);
    ofstream DataFile;
    DataFile.open ( "CocurrentHeatExchangerEquations_N_80.csv" );
    clock_t SimulationStart = clock();
    clock_t TransientStart;
    clock_t TransientEnd;    
    for (int i=0; i < NumberOfSimulationLaunches; i++) {
        FillSolverObject(Solver, i*NT, NT);
        Solver.SynchroniseFromHostToDevice(All);
        Solver.InsertSynchronisationPoint();
        Solver.SynchroniseSolver();

        TransientStart = clock();
        for (int j=0; j < 1; j++) {
            Solver.Solve();
            Solver.InsertSynchronisationPoint();
            Solver.SynchroniseSolver();
        }
        TransientEnd = clock();
        cout << "Launches: " << i << "  Simulation time: ";
        cout << 1000.0*(TransientEnd-TransientStart) / CLOCKS_PER_SEC << "ms" << endl << endl;
        for (int j=0; j<1; j++)
        {
            Solver.Solve();
            Solver.SynchroniseFromDeviceToHost(All);
            Solver.InsertSynchronisationPoint();
            Solver.SynchroniseSolver();
            SaveData(Solver, DataFile, NT);
        }
    }

    clock_t SimulationEnd = clock();
    cout << "Total simulation time: " << 1000.0*(SimulationEnd-SimulationStart) / CLOCKS_PER_SEC << "ms";
    cout << endl;
	
    DataFile.close();
    
    Solver.Print(DenseOutput, 0);
    Solver.Print(ActualState);
    Solver.Print(ActualTime);
	
    cout << "Test finished!" << endl;

    return 0;
}

