within BIOMD285;
class Parameters

    input Real elmt_AggPolyQ3;
    input Real elmt_AggPolyQ4;
    input Real elmt_AggPolyQ1;
    input Real elmt_AggPolyQ2;
    input Real elmt_AggPolyQ5;

    input Boolean elmt_PIcellDeath;    input Boolean elmt_p38cellDeath;
    input Real assign_elmt_kalive;


    Real elmt_oligomers(unit = "") "oligomers";
    Real elmt_kproteff(unit = "") "";
    Real elmt_kdegPolyQ(unit = "") "";
    Real elmt_krelPolyQ(unit = "") "";
    Real elmt_kseqMisPProt(unit = "") "";
    Real elmt_kgenROSAggP(unit = "") "";
    Real elmt_kseqPolyQProt(unit = "") "";
    Real elmt_kmisfold(unit = "") "";
    Real elmt_ksynNatP(unit = "") "";
    Real elmt_kseqmRFPu(unit = "") "";
    Real elmt_kdisaggPolyQ4(unit = "") "";
    Real elmt_kdisaggPolyQ5(unit = "") "";
    Real elmt_krelMisPProt(unit = "") "";
    Real elmt_kdegMisP(unit = "") "";
    Real elmt_kdisaggPolyQ1(unit = "") "";
    Real elmt_kdisaggPolyQ2(unit = "") "";
    Real elmt_kdisaggPolyQ3(unit = "") "";
    Real elmt_ksynPolyQ(unit = "") "";
    Real elmt_kbinMisPProt(unit = "") "";
    Real elmt_kactp38(unit = "") "";
    Real elmt_kgenROSSeqAggP(unit = "") "";
    Real elmt_kp38death(unit = "") "";
    Real elmt_kseqPolyQ(unit = "") "";
    Real elmt_krelmRFPu(unit = "") "";
    Real elmt_kremROS(unit = "") "";
    Real elmt_kp38act(unit = "") "";
    Real elmt_kinactp38(unit = "") "";
    Real elmt_ksynmRFPu(unit = "") "";
    Real elmt_kgenROSp38(unit = "") "";
    Real elmt_krefold(unit = "") "";
    Real elmt_kaggPolyQ(unit = "") "";
    Real elmt_kagg2MisP(unit = "") "";
    Real elmt_kgenROS(unit = "") "";
    Real elmt_kinhprot(unit = "") "";
    Real elmt_kseqAggPProt(unit = "") "";
    Real elmt_kaggMisP(unit = "") "";
    Real elmt_kseqmRFPuProt(unit = "") "";
    Real elmt_kdegmRFPu(unit = "") "";
    Real elmt_kbinPolyQ(unit = "") "";
    Real elmt_kalive(unit = "") "";
    Real elmt_kPIdeath(unit = "") "";
    Real elmt_kseqMisP(unit = "") "";
    Real elmt_kdisaggMisP1(unit = "") "";
    Real elmt_kbinmRFPu(unit = "") "";
    Real elmt_kdisaggMisP3(unit = "") "";
    Real elmt_kdisaggMisP2(unit = "") "";
    Real elmt_kdisaggMisP5(unit = "") "";
    Real elmt_kdisaggMisP4(unit = "") "";


    initial equation
        elmt_kproteff = 1.0;
        elmt_kdegPolyQ = 0.0025;
        elmt_krelPolyQ = 1.0E-9;
        elmt_kseqMisPProt = 5.0E-7;
        elmt_kgenROSAggP = 5.0E-6;
        elmt_kseqPolyQProt = 5.0E-7;
        elmt_kmisfold = 2.0E-6;
        elmt_ksynNatP = 2.4;
        elmt_kseqmRFPu = 1.0E-10;
        elmt_kdisaggPolyQ4 = 2.0E-7;
        elmt_kdisaggPolyQ5 = 1.0E-7;
        elmt_krelMisPProt = 1.0E-8;
        elmt_kdegMisP = 0.01;
        elmt_kdisaggPolyQ1 = 5.0E-7;
        elmt_kdisaggPolyQ2 = 4.0E-7;
        elmt_kdisaggPolyQ3 = 3.0E-7;
        elmt_ksynPolyQ = 0.007;
        elmt_kbinMisPProt = 5.0E-8;
        elmt_kactp38 = 5.0E-6;
        elmt_kgenROSSeqAggP = 1.0E-7;
        elmt_kp38death = 9.0E-8;
        elmt_kseqPolyQ = 8.0E-7;
        elmt_krelmRFPu = 1.0E-8;
        elmt_kremROS = 2.0E-4;
        elmt_kp38act = 1.0;
        elmt_kinactp38 = 0.002;
        elmt_ksynmRFPu = 0.138;
        elmt_kgenROSp38 = 7.0E-4;
        elmt_krefold = 8.0E-5;
        elmt_kaggPolyQ = 5.0E-8;
        elmt_kagg2MisP = 1.0E-10;
        elmt_kgenROS = 0.0017;
        elmt_kinhprot = 5.0E-9;
        elmt_kseqAggPProt = 5.0E-7;
        elmt_kaggMisP = 1.0E-11;
        elmt_kseqmRFPuProt = 5.0E-7;
        elmt_kdegmRFPu = 0.005;
        elmt_kbinPolyQ = 5.0E-8;
        elmt_kalive = 1.0;
        elmt_kPIdeath = 2.5E-8;
        elmt_kseqMisP = 1.0E-9;
        elmt_kdisaggMisP1 = 5.0E-7;
        elmt_kbinmRFPu = 5.0E-7;
        elmt_kdisaggMisP3 = 3.0E-7;
        elmt_kdisaggMisP2 = 4.0E-7;
        elmt_kdisaggMisP5 = 1.0E-7;
        elmt_kdisaggMisP4 = 2.0E-7;


    equation
        elmt_oligomers = (elmt_AggPolyQ1 + elmt_AggPolyQ2 + elmt_AggPolyQ3 + elmt_AggPolyQ4 + elmt_AggPolyQ5);
        der(elmt_kproteff) = 0;
        der(elmt_kdegPolyQ) = 0;
        der(elmt_krelPolyQ) = 0;
        der(elmt_kseqMisPProt) = 0;
        der(elmt_kgenROSAggP) = 0;
        der(elmt_kseqPolyQProt) = 0;
        der(elmt_kmisfold) = 0;
        der(elmt_ksynNatP) = 0;
        der(elmt_kseqmRFPu) = 0;
        der(elmt_kdisaggPolyQ4) = 0;
        der(elmt_kdisaggPolyQ5) = 0;
        der(elmt_krelMisPProt) = 0;
        der(elmt_kdegMisP) = 0;
        der(elmt_kdisaggPolyQ1) = 0;
        der(elmt_kdisaggPolyQ2) = 0;
        der(elmt_kdisaggPolyQ3) = 0;
        der(elmt_ksynPolyQ) = 0;
        der(elmt_kbinMisPProt) = 0;
        der(elmt_kactp38) = 0;
        der(elmt_kgenROSSeqAggP) = 0;
        der(elmt_kp38death) = 0;
        der(elmt_kseqPolyQ) = 0;
        der(elmt_krelmRFPu) = 0;
        der(elmt_kremROS) = 0;
        der(elmt_kp38act) = 0;
        der(elmt_kinactp38) = 0;
        der(elmt_ksynmRFPu) = 0;
        der(elmt_kgenROSp38) = 0;
        der(elmt_krefold) = 0;
        der(elmt_kaggPolyQ) = 0;
        der(elmt_kagg2MisP) = 0;
        der(elmt_kgenROS) = 0;
        der(elmt_kinhprot) = 0;
        der(elmt_kseqAggPProt) = 0;
        der(elmt_kaggMisP) = 0;
        der(elmt_kseqmRFPuProt) = 0;
        der(elmt_kdegmRFPu) = 0;
        der(elmt_kbinPolyQ) = 0;
        der(elmt_kalive) = 0.0;
        der(elmt_kPIdeath) = 0;
        der(elmt_kseqMisP) = 0;
        der(elmt_kdisaggMisP1) = 0;
        der(elmt_kbinmRFPu) = 0;
        der(elmt_kdisaggMisP3) = 0;
        der(elmt_kdisaggMisP2) = 0;
        der(elmt_kdisaggMisP5) = 0;
        der(elmt_kdisaggMisP4) = 0;

        when elmt_PIcellDeath then
            reinit(elmt_kalive, assign_elmt_kalive);
        end when;
        when elmt_p38cellDeath then
            reinit(elmt_kalive, assign_elmt_kalive);
        end when;
end Parameters;
