within BIOMD265;
class Parameters

    input Real elmt_P27;
    input Real elmt_CD;
    input Real elmt_CYCB;
    input Real elmt_CE;
    input Real elmt_CDc20;
    input Real elmt_CYCA;
    input Real elmt_CDh1;
    input Real elmt_CA;
    input Real elmt_CYCD;
    input Real elmt_CYCE;

    input Boolean elmt_r31Ifpart1;    input Boolean elmt_divisionEvent;    input Boolean elmt_r31Ifpart2;    input Boolean elmt_checkEvent;
    input Real assign_elmt_r31switch;
    input Real assign_elmt_Flag;


    Real elmt_K25R(unit = "s-1.0") "";
    Real elmt_K8a(unit = "s-1.0") "";
    Real elmt_CYCET(unit = "") "";
    Real elmt_YE(unit = "") "";
    Real elmt_YB(unit = "") "";
    Real elmt_PP1T(unit = "") "";
    Real elmt_CYCAT(unit = "") "";
    Real elmt_LA(unit = "") "";
    Real elmt_LB(unit = "") "";
    Real elmt_HE(unit = "") "";
    Real elmt_K26(unit = "s-1.0") "";
    Real elmt_PP1A(unit = "") "";
    Real elmt_K25(unit = "s-1.0") "";
    Real elmt_HA(unit = "") "";
    Real elmt_LE(unit = "") "";
    Real elmt_K22(unit = "s-1.0") "";
    Real elmt_HB(unit = "") "";
    Real elmt_K23(unit = "s-1.0") "";
    Real elmt_K20(unit = "s-1.0") "";
    Real elmt_LD(unit = "") "";
    Real elmt_K21(unit = "") "";
    Real elmt_K26R(unit = "s-1.0") "";
    Real elmt_V8(unit = "") "";
    Real elmt_V6(unit = "") "";
    Real elmt_P27T(unit = "") "";
    Real elmt_J8(unit = "") "";
    Real elmt_K30(unit = "s-1.0") "";
    Real elmt_V4(unit = "") "";
    Real elmt_V2(unit = "") "";
    Real elmt_r31switch(unit = "") "";
    Real elmt_K6a(unit = "s-1.0") "";
    Real elmt_FE(unit = "") "";
    Real elmt_K8(unit = "s-1.0") "";
    Real elmt_Flag(unit = "") "";
    Real elmt_K6(unit = "s-1.0") "";
    Real elmt_K4(unit = "s-1.0") "";
    Real elmt_K2(unit = "s-1.0") "";
    Real elmt_K2a(unit = "s-1.0") "";
    Real elmt_FB(unit = "") "";
    Real elmt_CYCDT(unit = "") "";
    Real elmt_K2aa(unit = "s-1.0") "";
    Real elmt_eps(unit = "") "";
    Real elmt_K23a(unit = "s-1.0") "";
    Real elmt_RBT(unit = "") "";
    Real elmt_GE(unit = "") "";
    Real elmt_GB(unit = "") "";
    Real elmt_GA(unit = "") "";
    Real elmt_K12(unit = "s-1.0") "";
    Real elmt_E2FT(unit = "") "";
    Real elmt_K10(unit = "s-1.0") "";


    initial equation
        elmt_K25R = 10.0;
        elmt_K8a = 0.1;
        elmt_YE = 1.0;
        elmt_YB = 0.05;
        elmt_PP1T = 1.0;
        elmt_LA = 3.0;
        elmt_LB = 5.0;
        elmt_HE = 0.5;
        elmt_K26 = 10000.0;
        elmt_K25 = 1000.0;
        elmt_HA = 0.5;
        elmt_LE = 5.0;
        elmt_K22 = 1.0;
        elmt_HB = 1.0;
        elmt_K23 = 1.0;
        elmt_K20 = 10.0;
        elmt_LD = 3.3;
        elmt_K21 = 1.0;
        elmt_K26R = 200.0;
        elmt_J8 = 0.1;
        elmt_K30 = 20.0;
        elmt_r31switch = 1.0;
        elmt_K6a = 10.0;
        elmt_FE = 25.0;
        elmt_K8 = 2.0;
        elmt_Flag = 1.0;
        elmt_K6 = 100.0;
        elmt_K4 = 40.0;
        elmt_K2 = 20.0;
        elmt_K2a = 0.05;
        elmt_FB = 2.0;
        elmt_K2aa = 1.0;
        elmt_eps = 1.0;
        elmt_K23a = 0.005;
        elmt_RBT = 10.0;
        elmt_GE = 0.0;
        elmt_GB = 1.0;
        elmt_GA = 0.3;
        elmt_K12 = 1.5;
        elmt_E2FT = 5.0;
        elmt_K10 = 5.0;


    equation
        der(elmt_K25R) = 0;
        der(elmt_K8a) = 0;
        elmt_CYCET = (elmt_CE + elmt_CYCE);
        der(elmt_YE) = 0;
        der(elmt_YB) = 0;
        der(elmt_PP1T) = 0;
        elmt_CYCAT = (elmt_CA + elmt_CYCA);
        der(elmt_LA) = 0;
        der(elmt_LB) = 0;
        der(elmt_HE) = 0;
        der(elmt_K26) = 0;
        elmt_PP1A = (elmt_PP1T / (1.0 + (elmt_K21 * ((elmt_FB * elmt_CYCB) + (elmt_FE * (elmt_CYCA + elmt_CYCE))))));
        der(elmt_K25) = 0;
        der(elmt_HA) = 0;
        der(elmt_LE) = 0;
        der(elmt_K22) = 0;
        der(elmt_HB) = 0;
        der(elmt_K23) = 0;
        der(elmt_K20) = 0;
        der(elmt_LD) = 0;
        der(elmt_K21) = 0;
        der(elmt_K26R) = 0;
        elmt_V8 = (elmt_K8a + ((elmt_K8 * ((elmt_YB * elmt_CYCB) + (elmt_YE * (elmt_CYCA + elmt_CYCE)))) / (elmt_CYCET + elmt_J8)));
        elmt_V6 = (elmt_K6a + (elmt_K6 * ((elmt_HA * elmt_CYCA) + (elmt_HB * elmt_CYCB) + (elmt_HE * elmt_CYCE))));
        elmt_P27T = (elmt_CA + elmt_CD + elmt_CE + elmt_P27);
        der(elmt_J8) = 0;
        der(elmt_K30) = 0;
        elmt_V4 = (elmt_K4 * ((elmt_GA * elmt_CYCA) + (elmt_GB * elmt_CYCB) + (elmt_GE * elmt_CYCE)));
        elmt_V2 = ((elmt_K2aa * elmt_CDc20) + (elmt_K2a * (1.0 - elmt_CDh1)) + (elmt_K2 * elmt_CDh1));
        der(elmt_r31switch) = 0.0;
        der(elmt_K6a) = 0;
        der(elmt_FE) = 0;
        der(elmt_K8) = 0;
        der(elmt_Flag) = 0.0;
        der(elmt_K6) = 0;
        der(elmt_K4) = 0;
        der(elmt_K2) = 0;
        der(elmt_K2a) = 0;
        der(elmt_FB) = 0;
        elmt_CYCDT = (elmt_CD + elmt_CYCD);
        der(elmt_K2aa) = 0;
        der(elmt_eps) = 0;
        der(elmt_K23a) = 0;
        der(elmt_RBT) = 0;
        der(elmt_GE) = 0;
        der(elmt_GB) = 0;
        der(elmt_GA) = 0;
        der(elmt_K12) = 0;
        der(elmt_E2FT) = 0;
        der(elmt_K10) = 0;

        when elmt_r31Ifpart1 then
            reinit(elmt_r31switch, assign_elmt_r31switch);
        end when;
        when elmt_divisionEvent then
            reinit(elmt_Flag, assign_elmt_Flag);
        end when;
        when elmt_r31Ifpart2 then
            reinit(elmt_r31switch, assign_elmt_r31switch);
        end when;
        when elmt_checkEvent then
            reinit(elmt_Flag, assign_elmt_Flag);
        end when;
end Parameters;
