within BIOMD620;
model MODEL1604270002 "Palmer2014 - Effect of IL-1β-Blocking therapies in T2DM - Disease Condition" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_default_compartment elmt_default_compartment;
    Class_elmt_Anakinra_Administration_event elmt_Anakinra_Administration_event;

    equation
        Params.elmt_IL1b = elmt_default_compartment.elmt_IL1b;
        Params.elmt_IL1Ra = elmt_default_compartment.elmt_IL1Ra;
        Params.elmt_Proinsulin = elmt_default_compartment.elmt_Proinsulin;
        Params.elmt_Insulin = elmt_default_compartment.elmt_Insulin;
        Params.elmt_Anakinra = elmt_default_compartment.elmt_Anakinra;
        Params.elmt_Anakinra_Administration_event = elmt_Anakinra_Administration_event.execution;
        Reacs.elmt_vfg = Params.elmt_vfg;
        Reacs.elmt_il1bH = Params.elmt_il1bH;
        Reacs.elmt_kplacebo = Params.elmt_kplacebo;
        Reacs.elmt_Gh = Params.elmt_Gh;
        Reacs.elmt_apoptosis = Params.elmt_apoptosis;
        Reacs.elmt_Proinsulin = elmt_default_compartment.elmt_Proinsulin;
        Reacs.elmt_Insulin = elmt_default_compartment.elmt_Insulin;
        Reacs.elmt_f = elmt_default_compartment.elmt_f;
        Reacs.elmt_Kxi = Params.elmt_Kxi;
        Reacs.elmt_xfg = Params.elmt_xfg;
        Reacs.elmt_Kxg = Params.elmt_Kxg;
        Reacs.elmt_Tgl = Params.elmt_Tgl;
        Reacs.elmt_IL1b = elmt_default_compartment.elmt_IL1b;
        Reacs.elmt_kmfg = Params.elmt_kmfg;
        Reacs.elmt_kmf = Params.elmt_kmf;
        Reacs.elmt_vh = Params.elmt_vh;
        Reacs.elmt_Kxgi = Params.elmt_Kxgi;
        Reacs.elmt_vf = Params.elmt_vf;
        Reacs.elmt_vs = Params.elmt_vs;
        Reacs.elmt_replication = Params.elmt_replication;
        Reacs.elmt_kab = Params.elmt_kab;
        Reacs.elmt_IL1R = Params.elmt_IL1R;
        Reacs.elmt_k1 = Params.elmt_k1;
        Reacs.elmt_tauf = Params.elmt_tauf;
        Reacs.elmt_kms = Params.elmt_kms;
        Reacs.elmt_il1b0 = Params.elmt_il1b0;
        Reacs.elmt_CL = Params.elmt_CL;
        Reacs.elmt_placebo_on = Params.elmt_placebo_on;
        Reacs.elmt_k2 = Params.elmt_k2;
        Reacs.elmt_B = elmt_default_compartment.elmt_B;
        Reacs.elmt_ks = Params.elmt_ks;
        Reacs.elmt_Glucose = elmt_default_compartment.elmt_Glucose;
        Reacs.elmt_taus = Params.elmt_taus;
        Reacs.elmt_Anakinra = elmt_default_compartment.elmt_Anakinra;
        Reacs.elmt_kf = Params.elmt_kf;
        Reacs.elmt_TigB = elmt_default_compartment.elmt_TigB;
        Reacs.elmt_Vp = Params.elmt_Vp;
        Reacs.elmt_Anakinrasc = elmt_default_compartment.elmt_Anakinrasc;
        elmt_default_compartment.elmt_AnakinraSC_elimination = Reacs.elmt_AnakinraSC_elimination;
        elmt_default_compartment.elmt_Proinsulin_elimination = Reacs.elmt_Proinsulin_elimination;
        elmt_default_compartment.elmt_product12 = Reacs.elmt_product12;
        elmt_default_compartment.elmt_Bcell_apoptosis = Reacs.elmt_Bcell_apoptosis;
        elmt_default_compartment.elmt_product10 = Reacs.elmt_product10;
        elmt_default_compartment.elmt_TigB_down = Reacs.elmt_TigB_down;
        elmt_default_compartment.elmt_Proinsulin_dependent_glucose_uptake = Reacs.elmt_Proinsulin_dependent_glucose_uptake;
        elmt_default_compartment.elmt_Anakinra_absorption = Reacs.elmt_Anakinra_absorption;
        elmt_default_compartment.elmt_Insulin_dependent_glucose_uptake = Reacs.elmt_Insulin_dependent_glucose_uptake;
        elmt_default_compartment.elmt_TigB_up = Reacs.elmt_TigB_up;
        elmt_default_compartment.elmt_IL1b_degradation = Reacs.elmt_IL1b_degradation;
        elmt_default_compartment.elmt_reactant19 = Reacs.elmt_reactant19;
        elmt_default_compartment.elmt_Basal_glucose_uptake = Reacs.elmt_Basal_glucose_uptake;
        elmt_default_compartment.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_default_compartment.elmt_IL1b_placebo = Reacs.elmt_IL1b_placebo;
        elmt_default_compartment.elmt_Glucose_production = Reacs.elmt_Glucose_production;
        elmt_default_compartment.elmt_Ktr = Params.elmt_Ktr;
        elmt_default_compartment.elmt_Kglucose = Params.elmt_Kglucose;
        elmt_default_compartment.elmt_product8 = Reacs.elmt_product8;
        elmt_default_compartment.elmt_reactant1 = Reacs.elmt_reactant1;
        elmt_default_compartment.elmt_product6 = Reacs.elmt_product6;
        elmt_default_compartment.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_default_compartment.elmt_reactant5 = Reacs.elmt_reactant5;
        elmt_default_compartment.elmt_reactant7 = Reacs.elmt_reactant7;
        elmt_default_compartment.elmt_proinsulin_sec_down = Reacs.elmt_proinsulin_sec_down;
        elmt_default_compartment.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_default_compartment.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_default_compartment.elmt_product0 = Reacs.elmt_product0;
        elmt_default_compartment.elmt_reactant17 = Reacs.elmt_reactant17;
        elmt_default_compartment.elmt_Anakinra_elimination = Reacs.elmt_Anakinra_elimination;
        elmt_default_compartment.elmt_Glucose_dependent_insulin_secretion = Reacs.elmt_Glucose_dependent_insulin_secretion;
        elmt_default_compartment.elmt_reactant11 = Reacs.elmt_reactant11;
        elmt_default_compartment.elmt_product4 = Reacs.elmt_product4;
        elmt_default_compartment.elmt_reactant13 = Reacs.elmt_reactant13;
        elmt_default_compartment.elmt_Insulin_elimination = Reacs.elmt_Insulin_elimination;
        elmt_default_compartment.elmt_product2 = Reacs.elmt_product2;
        elmt_default_compartment.elmt_IL1b_treatment = Reacs.elmt_IL1b_treatment;
        elmt_default_compartment.elmt_product16 = Reacs.elmt_product16;
        elmt_default_compartment.elmt_Kin = Params.elmt_Kin;
        elmt_default_compartment.elmt_proinsulin_sec_up = Reacs.elmt_proinsulin_sec_up;
        elmt_default_compartment.elmt_Glucose_dependent_proinsulin_secretion = Reacs.elmt_Glucose_dependent_proinsulin_secretion;
        elmt_default_compartment.elmt_product18 = Reacs.elmt_product18;
        elmt_default_compartment.elmt_Bcell_replication = Reacs.elmt_Bcell_replication;
        elmt_default_compartment.elmt_lambda = Params.elmt_lambda;
        elmt_default_compartment.elmt_Anakinra_Administration_event = elmt_Anakinra_Administration_event.execution;
        elmt_Anakinra_Administration_event.elmt_Ana_on = Params.elmt_Ana_on;
        elmt_Anakinra_Administration_event.elmt_Anakinra_dose_counter = Params.elmt_Anakinra_dose_counter;
        elmt_Anakinra_Administration_event.elmt_Anakinrasc = elmt_default_compartment.elmt_Anakinrasc;

        Params.assign_elmt_Anakinra_dose_counter = elmt_Anakinra_Administration_event.value_elmt_Anakinra_dose_counter;
        elmt_default_compartment.assign_elmt_Anakinrasc = elmt_Anakinra_Administration_event.value_elmt_Anakinrasc;
end MODEL1604270002;
