within BIOMD140;
class Parameters

    input Real elmt_IKK_IkBalpha;
    input Real elmt_IkBbeta_nuc_NFkB_nuc;
    input Real elmt_IkBalpha;
    input Real elmt_IkBbeta_NFkB;
    input Real elmt_IkBeps_NFkB;
    input Real elmt_IkBbeta;
    input Real elmt_IKK_IkBeps;
    input Real elmt_IKK_IkBalpha_NFkB;
    input Real elmt_IKK_IkBbeta;
    input Real elmt_NFkB_nuc;
    input Real elmt_IKK_IkBeps_NFkB;
    input Real elmt_IkBalpha_NFkB;
    input Real elmt_IKK_IkBbeta_NFkB;
    input Real elmt_IkBeps;

    input Boolean elmt_event_0000001;
    input Real assign_elmt_flag_for_after_trigger;
    input Real assign_elmt_trigger_value;


    Real elmt_r5(unit = "") "";
    Real elmt_tp2(unit = "") "";
    Real elmt_r6(unit = "") "";
    Real elmt_tr3(unit = "") "";
    Real elmt_tp1(unit = "") "";
    Real elmt_tr2(unit = "") "";
    Real elmt_r3(unit = "") "";
    Real elmt_r4(unit = "") "";
    Real elmt_tr1(unit = "") "";
    Real elmt_r1(unit = "") "";
    Real elmt_r2(unit = "") "";
    Real elmt_d1(unit = "") "";
    Real elmt_d2(unit = "") "";
    Real elmt_k2_beta(unit = "") "";
    Real elmt_fr(unit = "") "";
    Real elmt_a6(unit = "") "";
    Real elmt_a7(unit = "") "";
    Real elmt_a4(unit = "") "";
    Real elmt_a5(unit = "") "";
    Real elmt_a2(unit = "") "";
    Real elmt_a3(unit = "") "";
    Real elmt_tr2b(unit = "") "";
    Real elmt_tr2a(unit = "") "";
    Real elmt_a1(unit = "") "";
    Real elmt_deg1(unit = "") "";
    Real elmt_deg4(unit = "") "";
    Real elmt_a8(unit = "") "";
    Real elmt_a9(unit = "") "";
    Real elmt_k1(unit = "") "";
    Real elmt_flag_for_after_trigger(unit = "") "";
    Real elmt_fr_after_trigger(unit = "") "";
    Real elmt_Total_IkBbeta(unit = "") "";
    Real elmt_trigger_value(unit = "") "";
    Real elmt_tr2e(unit = "") "";
    Real elmt_Total_NFkBn(unit = "") "";
    Real elmt_k2(unit = "") "";
    Real elmt_Total_IkBeps(unit = "") "";
    Real elmt_d5(unit = "") "";
    Real elmt_k2_eps(unit = "") "";
    Real elmt_d6(unit = "") "";
    Real elmt_d3(unit = "") "";
    Real elmt_d4(unit = "") "";
    Real elmt_k02(unit = "") "";
    Real elmt_k01(unit = "") "";
    Real elmt_Total_IkBalpha(unit = "") "";


    initial equation
        elmt_r5 = 0.45;
        elmt_tp2 = 0.012;
        elmt_r6 = 0.66;
        elmt_tr3 = 0.0168;
        elmt_tp1 = 0.018;
        elmt_tr2 = 0.99;
        elmt_r3 = 0.132;
        elmt_r4 = 1.224;
        elmt_tr1 = 0.2448;
        elmt_r1 = 0.2442;
        elmt_r2 = 0.09;
        elmt_d1 = 0.075;
        elmt_d2 = 0.105;
        elmt_k2_beta = 0.624;
        elmt_fr = 1.0;
        elmt_a6 = 30.0;
        elmt_a7 = 11.1;
        elmt_a4 = 30.0;
        elmt_a5 = 30.0;
        elmt_a2 = 0.36;
        elmt_a3 = 0.54;
        elmt_tr2b = 1.068E-5;
        elmt_tr2a = 9.25E-5;
        elmt_a1 = 1.35;
        elmt_deg1 = 0.00678;
        elmt_deg4 = 0.00135;
        elmt_a8 = 2.88;
        elmt_a9 = 4.2;
        elmt_k1 = 5.4;
        elmt_flag_for_after_trigger = 0.5;
        elmt_fr_after_trigger = 0.5;
        elmt_trigger_value = 0.0;
        elmt_tr2e = 7.62E-6;
        elmt_k2 = 0.828;
        elmt_d5 = 0.03;
        elmt_k2_eps = 0.624;
        elmt_d6 = 0.03;
        elmt_d3 = 0.105;
        elmt_d4 = 0.03;
        elmt_k02 = 0.0072;
        elmt_k01 = 0.0048;


    equation
        der(elmt_r5) = 0;
        der(elmt_tp2) = 0;
        der(elmt_r6) = 0;
        der(elmt_tr3) = 0;
        der(elmt_tp1) = 0;
        der(elmt_tr2) = 0;
        der(elmt_r3) = 0;
        der(elmt_r4) = 0;
        der(elmt_tr1) = 0;
        der(elmt_r1) = 0;
        der(elmt_r2) = 0;
        der(elmt_d1) = 0;
        der(elmt_d2) = 0;
        der(elmt_k2_beta) = 0;
        der(elmt_fr) = 0;
        der(elmt_a6) = 0;
        der(elmt_a7) = 0;
        der(elmt_a4) = 0;
        der(elmt_a5) = 0;
        der(elmt_a2) = 0;
        der(elmt_a3) = 0;
        der(elmt_tr2b) = 0;
        der(elmt_tr2a) = 0;
        der(elmt_a1) = 0;
        der(elmt_deg1) = 0;
        der(elmt_deg4) = 0;
        der(elmt_a8) = 0;
        der(elmt_a9) = 0;
        der(elmt_k1) = 0;
        der(elmt_flag_for_after_trigger) = 0.0;
        der(elmt_fr_after_trigger) = (elmt_trigger_value * ((-0.5) / Functions.pow((1.0 + (time - 2000.0)), 2.0)));
        elmt_Total_IkBbeta = (elmt_IkBbeta + elmt_IkBbeta_NFkB + elmt_IKK_IkBbeta + elmt_IKK_IkBbeta_NFkB);
        der(elmt_trigger_value) = 0.0;
        der(elmt_tr2e) = 0;
        elmt_Total_NFkBn = (elmt_IkBbeta_nuc_NFkB_nuc + elmt_NFkB_nuc);
        der(elmt_k2) = 0;
        elmt_Total_IkBeps = (elmt_IkBeps + elmt_IkBeps_NFkB + elmt_IKK_IkBeps + elmt_IKK_IkBeps_NFkB);
        der(elmt_d5) = 0;
        der(elmt_k2_eps) = 0;
        der(elmt_d6) = 0;
        der(elmt_d3) = 0;
        der(elmt_d4) = 0;
        der(elmt_k02) = 0;
        der(elmt_k01) = 0;
        elmt_Total_IkBalpha = (elmt_IkBalpha + elmt_IkBalpha_NFkB + elmt_IKK_IkBalpha + elmt_IKK_IkBalpha_NFkB);

        when elmt_event_0000001 then
            reinit(elmt_flag_for_after_trigger, assign_elmt_flag_for_after_trigger);
            reinit(elmt_trigger_value, assign_elmt_trigger_value);
        end when;
end Parameters;
