within BIOMD578;
class Class_elmt_cytosol

    input Real elmt_reactant40;
    input Real elmt_v_r_tetraarr;
    input Real elmt_v_r10;
    input Real elmt_reactant190;
    input Real elmt_v_r13_0;
    input Real elmt_reactant49;
    input Real elmt_v_r12;
    input Real elmt_v_r11;
    input Real elmt_reactant43;
    input Real elmt_v_r13_3;
    input Real elmt_v_r18;
    input Real elmt_v_r13_4;
    input Real elmt_v_r17;
    input Real elmt_v_r13_1;
    input Real elmt_v_r13_2;
    input Real elmt_reactant46;
    input Real elmt_v_r1;
    input Real elmt_product212;
    input Real elmt_reactant198;
    input Real elmt_v_r13_5;
    input Real elmt_reactant196;
    input Real elmt_product214;
    input Real elmt_v_r13_6;
    input Real elmt_reactant194;
    input Real elmt_reactant193;
    input Real elmt_product219;
    input Real elmt_product216;
    input Real elmt_product215;
    input Real elmt_product218;
    input Real elmt_reactant199;
    input Real elmt_reactant52;
    input Real elmt_v_r21;
    input Real elmt_v_r20;
    input Real elmt_v_r25;
    input Real elmt_reactant58;
    input Real elmt_v_r24;
    input Real elmt_reactant59;
    input Real elmt_v_r23;
    input Real elmt_v_r22;
    input Real elmt_v_r29;
    input Real elmt_v_r2_6;
    input Real elmt_v_r2_5;
    input Real elmt_reactant55;
    input Real elmt_v_r28;
    input Real elmt_reactant56;
    input Real elmt_v_r27;
    input Real elmt_v_r26;
    input Real elmt_v_r2_2;
    input Real elmt_product102;
    input Real elmt_v_r2_1;
    input Real elmt_product222;
    input Real elmt_v_r2_4;
    input Real elmt_product104;
    input Real elmt_v_r19;
    input Real elmt_v_r2_3;
    input Real elmt_product224;
    input Real elmt_v_r2_0;
    input Real elmt_product221;
    input Real elmt_product100;
    input Real elmt_product109;
    input Real elmt_product227;
    input Real elmt_product107;
    input Real elmt_reactant20;
    input Real elmt_product12;
    input Real elmt_reactant25;
    input Real elmt_reactant27;
    input Real elmt_reactant22;
    input Real elmt_reactant23;
    input Real elmt_reactant175;
    input Real elmt_reactant172;
    input Real elmt_reactant19;
    input Real elmt_reactant178;
    input Real elmt_reactant31;
    input Real elmt_product21;
    input Real elmt_reactant37;
    input Real elmt_reactant33;
    input Real elmt_reactant35;
    input Real elmt_reactant187;
    input Real elmt_product200;
    input Real elmt_reactant184;
    input Real elmt_product202;
    input Real elmt_reactant29;
    input Real elmt_reactant181;
    input Real elmt_product209;
    input Real elmt_product15;
    input Real elmt_product208;
    input Real elmt_product205;
    input Real elmt_product18;
    input Real elmt_product207;
    input Real elmt_reactant153;
    input Real elmt_reactant151;
    input Real elmt_numConcFactor;
    input Real elmt_reactant159;
    input Real elmt_reactant157;
    input Real elmt_reactant155;
    input Real elmt_reactant14;
    input Real elmt_reactant16;
    input Real elmt_reactant17;
    input Real elmt_v_r4_4;
    input Real elmt_reactant10;
    input Real elmt_v_r4_3;
    input Real elmt_reactant11;
    input Real elmt_v_r4_6;
    input Real elmt_v_r4_5;
    input Real elmt_reactant13;
    input Real elmt_reactant165;
    input Real elmt_v_r4_2;
    input Real elmt_reactant163;
    input Real elmt_v_r4_1;
    input Real elmt_reactant161;
    input Real elmt_reactant169;
    input Real elmt_reactant167;
    input Real elmt_product192;
    input Real elmt_product195;
    input Real elmt_product191;
    input Real elmt_reactant132;
    input Real elmt_reactant130;
    input Real elmt_product197;
    input Real elmt_reactant139;
    input Real elmt_reactant138;
    input Real elmt_reactant136;
    input Real elmt_reactant135;
    input Real elmt_reactant133;
    input Real elmt_reactant2;
    input Real elmt_reactant4;
    input Real elmt_reactant5;
    input Real elmt_reactant8;
    input Real elmt_reactant7;
    input Real elmt_v_r9;
    input Real elmt_v_r8;
    input Real elmt_v_r3_5;
    input Real elmt_v_r3_4;
    input Real elmt_reactant0;
    input Real elmt_v_r3_1;
    input Real elmt_reactant143;
    input Real elmt_v_r3_0;
    input Real elmt_v_r3_3;
    input Real elmt_reactant141;
    input Real elmt_v_r3_2;
    input Real elmt_reactant149;
    input Real elmt_reactant147;
    input Real elmt_reactant145;
    input Real elmt_product74;
    input Real elmt_product72;
    input Real elmt_product78;
    input Real elmt_product77;
    input Real elmt_reactant108;
    input Real elmt_product75;
    input Real elmt_product171;
    input Real elmt_product170;
    input Real elmt_product173;
    input Real elmt_product179;
    input Real elmt_reactant110;
    input Real elmt_reactant231;
    input Real elmt_product174;
    input Real elmt_product177;
    input Real elmt_product176;
    input Real elmt_reactant118;
    input Real elmt_reactant117;
    input Real elmt_product69;
    input Real elmt_reactant236;
    input Real elmt_reactant115;
    input Real elmt_reactant234;
    input Real elmt_reactant112;
    input Real elmt_reactant232;
    input Real elmt_product84;
    input Real elmt_product83;
    input Real elmt_product89;
    input Real elmt_product87;
    input Real elmt_product86;
    input Real elmt_v_r6_6;
    input Real elmt_product182;
    input Real elmt_v_r6_5;
    input Real elmt_product183;
    input Real elmt_v_r6_2;
    input Real elmt_product81;
    input Real elmt_v_r6_1;
    input Real elmt_product80;
    input Real elmt_v_r6_4;
    input Real elmt_product180;
    input Real elmt_v_r6_3;
    input Real elmt_reactant121;
    input Real elmt_reactant120;
    input Real elmt_product189;
    input Real elmt_product186;
    input Real elmt_product185;
    input Real elmt_product188;
    input Real elmt_reactant129;
    input Real elmt_reactant127;
    input Real elmt_reactant126;
    input Real elmt_reactant124;
    input Real elmt_reactant123;
    input Real elmt_reactant243;
    input Real elmt_product96;
    input Real elmt_product94;
    input Real elmt_product98;
    input Real elmt_product150;
    input Real elmt_v_r16_0;
    input Real elmt_product92;
    input Real elmt_v_r16_1;
    input Real elmt_product90;
    input Real elmt_v_r16_4;
    input Real elmt_product156;
    input Real elmt_v_r16_5;
    input Real elmt_v_r16_2;
    input Real elmt_v_r16_3;
    input Real elmt_product158;
    input Real elmt_product152;
    input Real elmt_v_r16_6;
    input Real elmt_product154;
    input Real elmt_reactant217;
    input Real elmt_reactant213;
    input Real elmt_reactant211;
    input Real elmt_reactant210;
    input Real elmt_product9;
    input Real elmt_product6;
    input Real elmt_product1;
    input Real elmt_product160;
    input Real elmt_v_r5_6;
    input Real elmt_product162;
    input Real elmt_v_r5_3;
    input Real elmt_v_r5_2;
    input Real elmt_v_r5_5;
    input Real elmt_product3;
    input Real elmt_v_r5_4;
    input Real elmt_reactant220;
    input Real elmt_product168;
    input Real elmt_v_r5_1;
    input Real elmt_product164;
    input Real elmt_product166;
    input Real elmt_reactant228;
    input Real elmt_reactant106;
    input Real elmt_reactant105;
    input Real elmt_reactant226;
    input Real elmt_v_rstprec;
    input Real elmt_reactant225;
    input Real elmt_reactant103;
    input Real elmt_reactant223;
    input Real elmt_reactant101;
    input Real elmt_product30;
    input Real elmt_reactant85;
    input Real elmt_v_GtRpre;
    input Real elmt_product34;
    input Real elmt_product32;
    input Real elmt_reactant82;
    input Real elmt_v_r15_1;
    input Real elmt_reactant88;
    input Real elmt_v_r15_2;
    input Real elmt_v_r15_0;
    input Real elmt_v_r15_5;
    input Real elmt_product134;
    input Real elmt_v_r15_6;
    input Real elmt_v_r15_3;
    input Real elmt_product137;
    input Real elmt_v_r15_4;
    input Real elmt_product131;
    input Real elmt_product26;
    input Real elmt_product24;
    input Real elmt_product28;
    input Real elmt_product41;
    input Real elmt_reactant95;
    input Real elmt_reactant97;
    input Real elmt_product45;
    input Real elmt_product44;
    input Real elmt_reactant91;
    input Real elmt_reactant93;
    input Real elmt_product42;
    input Real elmt_product140;
    input Real elmt_reactant99;
    input Real elmt_product146;
    input Real elmt_product148;
    input Real elmt_product142;
    input Real elmt_product144;
    input Real elmt_reactant206;
    input Real elmt_product38;
    input Real elmt_product36;
    input Real elmt_reactant204;
    input Real elmt_reactant203;
    input Real elmt_reactant201;
    input Real elmt_product39;
    input Real elmt_reactant61;
    input Real elmt_reactant62;
    input Real elmt_product51;
    input Real elmt_product50;
    input Real elmt_reactant64;
    input Real elmt_v_r31;
    input Real elmt_v_r30;
    input Real elmt_product54;
    input Real elmt_product53;
    input Real elmt_v_r36;
    input Real elmt_v_r_diarr;
    input Real elmt_v_r35;
    input Real elmt_v_r34;
    input Real elmt_v_r33;
    input Real elmt_v_r14_2;
    input Real elmt_reactant65;
    input Real elmt_v_r14_3;
    input Real elmt_reactant67;
    input Real elmt_v_r14_0;
    input Real elmt_v_r37;
    input Real elmt_reactant68;
    input Real elmt_v_r14_1;
    input Real elmt_v_r14_6;
    input Real elmt_product113;
    input Real elmt_product233;
    input Real elmt_v_r14_4;
    input Real elmt_product235;
    input Real elmt_v_r14_5;
    input Real elmt_product114;
    input Real elmt_product230;
    input Real elmt_product111;
    input Real elmt_product48;
    input Real elmt_product47;
    input Real elmt_product237;
    input Real elmt_product116;
    input Real elmt_product119;
    input Real elmt_product239;
    input Real elmt_product63;
    input Real elmt_reactant73;
    input Real elmt_product60;
    input Real elmt_product66;
    input Real elmt_reactant70;
    input Real elmt_reactant71;
    input Real elmt_v_r7_5;
    input Real elmt_v_r7_4;
    input Real elmt_v_r7_6;
    input Real elmt_v_r7_1;
    input Real elmt_reactant76;
    input Real elmt_v_r7_0;
    input Real elmt_v_r7_3;
    input Real elmt_v_r7_2;
    input Real elmt_reactant79;
    input Real elmt_product125;
    input Real elmt_product122;
    input Real elmt_product242;
    input Real elmt_product57;
    input Real elmt_product128;

    Real elmt_cytosol(unit = "m3.0") "cytosol";
    Real elmt_R3_RKpost_amount(unit = "m-6.0.");
    Real elmt_R3_RKpost_conc(unit = "m-9.0.");
    Real elmt_R3_RKpost(unit = "m-6.0.") "R3_RKpost";
    Real elmt_R5_RKpre_amount(unit = "m-6.0.");
    Real elmt_R5_RKpre_conc(unit = "m-9.0.");
    Real elmt_R5_RKpre(unit = "m-6.0.") "R5_RKpre";
    Real elmt_R2_RKpost_amount(unit = "m-6.0.");
    Real elmt_R2_RKpost_conc(unit = "m-9.0.");
    Real elmt_R2_RKpost(unit = "m-6.0.") "R2_RKpost";
    Real elmt_Arr_tetra_amount(unit = "");
    Real elmt_Arr_tetra_conc(unit = "m-3.0.");
    Real elmt_Arr_tetra(unit = "") "Arr_tetra";
    Real elmt_Gt_amount(unit = "m-6.0.");
    Real elmt_Gt_conc(unit = "m-9.0.");
    Real elmt_Gt(unit = "m-6.0.") "Gt";
    Real elmt_R6_RKpost_amount(unit = "m-6.0.");
    Real elmt_R6_RKpost_conc(unit = "m-9.0.");
    Real elmt_R6_RKpost(unit = "m-6.0.") "R6_RKpost";
    Real elmt_RGS_amount(unit = "m-6.0.");
    Real elmt_RGS_conc(unit = "m-9.0.");
    Real elmt_RGS(unit = "m-6.0.") "RGS";
    Real elmt_PDE_Ga_GTP_amount(unit = "m-6.0.");
    Real elmt_PDE_Ga_GTP_conc(unit = "m-9.0.");
    Real elmt_PDE_Ga_GTP(unit = "m-6.0.") "PDE_Ga_GTP";
    Real elmt_R1_RKpost_amount(unit = "m-6.0.");
    Real elmt_R1_RKpost_conc(unit = "m-9.0.");
    Real elmt_R1_RKpost(unit = "m-6.0.") "R1_RKpost";
    Real elmt_R4_RKpost_amount(unit = "m-6.0.");
    Real elmt_R4_RKpost_conc(unit = "m-9.0.");
    Real elmt_R4_RKpost(unit = "m-6.0.") "R4_RKpost";
    Real elmt_R5_RKpost_amount(unit = "m-6.0.");
    Real elmt_R5_RKpost_conc(unit = "m-9.0.");
    Real elmt_R5_RKpost(unit = "m-6.0.") "R5_RKpost";
    Real elmt_R6_Arr_amount(unit = "m-6.0.");
    Real elmt_R6_Arr_conc(unit = "m-9.0.");
    Real elmt_R6_Arr(unit = "m-6.0.") "R6_Arr";
    Real elmt_Arr_amount(unit = "");
    Real elmt_Arr_conc(unit = "m-3.0.");
    Real elmt_Arr(unit = "") "Arr";
    Real elmt_Ga_GTP_PDE_a_Ga_GTP_amount(unit = "m-6.0.");
    Real elmt_Ga_GTP_PDE_a_Ga_GTP_conc(unit = "m-9.0.");
    Real elmt_Ga_GTP_PDE_a_Ga_GTP(unit = "m-6.0.") "Ga_GTP_PDE_a_Ga_GTP";
    Real elmt_R0_G_GTP_amount(unit = "m-6.0.");
    Real elmt_R0_G_GTP_conc(unit = "m-9.0.");
    Real elmt_R0_G_GTP(unit = "m-6.0.") "R0_G_GTP";
    Real elmt_cGMP_conc(unit = "m-9.0.");
    Real elmt_cGMP_amount(unit = "m-6.0.");
    Real elmt_cGMP(unit = "m-9.0.") "cGMP";
    Real elmt_Gbg_amount(unit = "m-6.0.");
    Real elmt_Gbg_conc(unit = "m-9.0.");
    Real elmt_Gbg(unit = "m-6.0.") "Gbg";
    Real elmt_R4_Gt_amount(unit = "m-6.0.");
    Real elmt_R4_Gt_conc(unit = "m-9.0.");
    Real elmt_R4_Gt(unit = "m-6.0.") "R4_Gt";
    Real elmt_R1_RKpre_amount(unit = "m-6.0.");
    Real elmt_R1_RKpre_conc(unit = "m-9.0.");
    Real elmt_R1_RKpre(unit = "m-6.0.") "R1_RKpre";
    Real elmt_R_amount(unit = "m-6.0.");
    Real elmt_R_conc(unit = "m-9.0.");
    Real elmt_R(unit = "m-6.0.") "R";
    Real elmt_R0_Gt_amount(unit = "m-6.0.");
    Real elmt_R0_Gt_conc(unit = "m-9.0.");
    Real elmt_R0_Gt(unit = "m-6.0.") "R0_Gt";
    Real elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP_amount(unit = "m-6.0.");
    Real elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP_conc(unit = "m-9.0.");
    Real elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP(unit = "m-6.0.") "RGS_Ga_GTP_a_PDE_a_Ga_GTP";
    Real elmt_R5_Arr_amount(unit = "m-6.0.");
    Real elmt_R5_Arr_conc(unit = "m-9.0.");
    Real elmt_R5_Arr(unit = "m-6.0.") "R5_Arr";
    Real elmt_Ops_G_GTP_amount(unit = "m-6.0.");
    Real elmt_Ops_G_GTP_conc(unit = "m-9.0.");
    Real elmt_Ops_G_GTP(unit = "m-6.0.") "Ops_G_GTP";
    Real elmt_R2_G_amount(unit = "m-6.0.");
    Real elmt_R2_G_conc(unit = "m-9.0.");
    Real elmt_R2_G(unit = "m-6.0.") "R2_G";
    Real elmt_R3_G_GTP_amount(unit = "m-6.0.");
    Real elmt_R3_G_GTP_conc(unit = "m-9.0.");
    Real elmt_R3_G_GTP(unit = "m-6.0.") "R3_G_GTP";
    Real elmt_R5_amount(unit = "m-6.0.");
    Real elmt_R5_conc(unit = "m-9.0.");
    Real elmt_R5(unit = "m-6.0.") "R5";
    Real elmt_R4_G_amount(unit = "m-6.0.");
    Real elmt_R4_G_conc(unit = "m-9.0.");
    Real elmt_R4_G(unit = "m-6.0.") "R4_G";
    Real elmt_R6_amount(unit = "m-6.0.");
    Real elmt_R6_conc(unit = "m-9.0.");
    Real elmt_R6(unit = "m-6.0.") "R6";
    Real elmt_R3_amount(unit = "m-6.0.");
    Real elmt_R3_conc(unit = "m-9.0.");
    Real elmt_R3(unit = "m-6.0.") "R3";
    Real elmt_R6_RKpre_amount(unit = "m-6.0.");
    Real elmt_R6_RKpre_conc(unit = "m-9.0.");
    Real elmt_R6_RKpre(unit = "m-6.0.") "R6_RKpre";
    Real elmt_R4_amount(unit = "m-6.0.");
    Real elmt_R4_conc(unit = "m-9.0.");
    Real elmt_R4(unit = "m-6.0.") "R4";
    Real elmt_R6_G_amount(unit = "m-6.0.");
    Real elmt_R6_G_conc(unit = "m-9.0.");
    Real elmt_R6_G(unit = "m-6.0.") "R6_G";
    Real elmt_G_GTP_amount(unit = "m-6.0.");
    Real elmt_G_GTP_conc(unit = "m-9.0.");
    Real elmt_G_GTP(unit = "m-6.0.") "G_GTP";
    Real elmt_PDE_amount(unit = "m-6.0.");
    Real elmt_PDE_conc(unit = "m-9.0.");
    Real elmt_PDE(unit = "m-6.0.") "PDE";
    Real elmt_R1_amount(unit = "m-6.0.");
    Real elmt_R1_conc(unit = "m-9.0.");
    Real elmt_R1(unit = "m-6.0.") "R1";
    Real elmt_R4_RKpre_amount(unit = "m-6.0.");
    Real elmt_R4_RKpre_conc(unit = "m-9.0.");
    Real elmt_R4_RKpre(unit = "m-6.0.") "R4_RKpre";
    Real elmt_R2_amount(unit = "m-6.0.");
    Real elmt_R2_conc(unit = "m-9.0.");
    Real elmt_R2(unit = "m-6.0.") "R2";
    Real elmt_Ops_Gt_amount(unit = "m-6.0.");
    Real elmt_Ops_Gt_conc(unit = "m-9.0.");
    Real elmt_Ops_Gt(unit = "m-6.0.") "Ops_Gt";
    Real elmt_R5_G_GTP_amount(unit = "m-6.0.");
    Real elmt_R5_G_GTP_conc(unit = "m-9.0.");
    Real elmt_R5_G_GTP(unit = "m-6.0.") "R5_G_GTP";
    Real elmt_Arr_di_amount(unit = "");
    Real elmt_Arr_di_conc(unit = "m-3.0.");
    Real elmt_Arr_di(unit = "") "Arr_di";
    Real elmt_RecT_amount(unit = "m-6.0.");
    Real elmt_RecT_conc(unit = "m-9.0.");
    Real elmt_RecT(unit = "m-6.0.") "RecT";
    Real elmt_R0_G_amount(unit = "m-6.0.");
    Real elmt_R0_G_conc(unit = "m-9.0.");
    Real elmt_R0_G(unit = "m-6.0.") "R0_G";
    Real elmt_RGS_PDE_a_Ga_GTP_amount(unit = "m-6.0.");
    Real elmt_RGS_PDE_a_Ga_GTP_conc(unit = "m-9.0.");
    Real elmt_RGS_PDE_a_Ga_GTP(unit = "m-6.0.") "RGS_PDE_a_Ga_GTP";
    Real elmt_R0_amount(unit = "m-6.0.");
    Real elmt_R0_conc(unit = "m-9.0.");
    Real elmt_R0(unit = "m-6.0.") "R0";
    Real elmt_R3_Gt_amount(unit = "m-6.0.");
    Real elmt_R3_Gt_conc(unit = "m-9.0.");
    Real elmt_R3_Gt(unit = "m-6.0.") "R3_Gt";
    Real elmt_R4_Arr_amount(unit = "m-6.0.");
    Real elmt_R4_Arr_conc(unit = "m-9.0.");
    Real elmt_R4_Arr(unit = "m-6.0.") "R4_Arr";
    Real elmt_Ga_GTP_a_PDE_a_Ga_GTP_amount(unit = "m-6.0.");
    Real elmt_Ga_GTP_a_PDE_a_Ga_GTP_conc(unit = "m-9.0.");
    Real elmt_Ga_GTP_a_PDE_a_Ga_GTP(unit = "m-6.0.") "Ga_GTP_a_PDE_a_Ga_GTP";
    Real elmt_R2_G_GTP_amount(unit = "m-6.0.");
    Real elmt_R2_G_GTP_conc(unit = "m-9.0.");
    Real elmt_R2_G_GTP(unit = "m-6.0.") "R2_G_GTP";
    Real elmt_R0_RKpre_amount(unit = "m-6.0.");
    Real elmt_R0_RKpre_conc(unit = "m-9.0.");
    Real elmt_R0_RKpre(unit = "m-6.0.") "R0_RKpre";
    Real elmt_R3_RKpre_amount(unit = "m-6.0.");
    Real elmt_R3_RKpre_conc(unit = "m-9.0.");
    Real elmt_R3_RKpre(unit = "m-6.0.") "R3_RKpre";
    Real elmt_R3_Arr_amount(unit = "m-6.0.");
    Real elmt_R3_Arr_conc(unit = "m-9.0.");
    Real elmt_R3_Arr(unit = "m-6.0.") "R3_Arr";
    Real elmt_R6_G_GTP_amount(unit = "m-6.0.");
    Real elmt_R6_G_GTP_conc(unit = "m-9.0.");
    Real elmt_R6_G_GTP(unit = "m-6.0.") "R6_G_GTP";
    Real elmt_RecR_Ca_amount(unit = "m-6.0.");
    Real elmt_RecR_Ca_conc(unit = "m-9.0.");
    Real elmt_RecR_Ca(unit = "m-6.0.") "RecR_Ca";
    Real elmt_R6_Gt_amount(unit = "m-6.0.");
    Real elmt_R6_Gt_conc(unit = "m-9.0.");
    Real elmt_R6_Gt(unit = "m-6.0.") "R6_Gt";
    Real elmt_RecR_Ca_RK_amount(unit = "m-6.0.");
    Real elmt_RecR_Ca_RK_conc(unit = "m-9.0.");
    Real elmt_RecR_Ca_RK(unit = "m-6.0.") "RecR_Ca_RK";
    Real elmt_R2_Gt_amount(unit = "m-6.0.");
    Real elmt_R2_Gt_conc(unit = "m-9.0.");
    Real elmt_R2_Gt(unit = "m-6.0.") "R2_Gt";
    Real elmt_Ca2_buff_conc(unit = "m-3.0.");
    Real elmt_Ca2_buff_amount(unit = "");
    Real elmt_Ca2_buff(unit = "m-3.0.") "Ca2_buff";
    Real elmt_Ops_G_amount(unit = "m-6.0.");
    Real elmt_Ops_G_conc(unit = "m-9.0.");
    Real elmt_Ops_G(unit = "m-6.0.") "Ops_G";
    Real elmt_RK_amount(unit = "m-6.0.");
    Real elmt_RK_conc(unit = "m-9.0.");
    Real elmt_RK(unit = "m-6.0.") "RK";
    Real elmt_R2_Arr_amount(unit = "m-6.0.");
    Real elmt_R2_Arr_conc(unit = "m-9.0.");
    Real elmt_R2_Arr(unit = "m-6.0.") "R2_Arr";
    Real elmt_R1_G_amount(unit = "m-6.0.");
    Real elmt_R1_G_conc(unit = "m-9.0.");
    Real elmt_R1_G(unit = "m-6.0.") "R1_G";
    Real elmt_PDE_a_Ga_GTP_amount(unit = "m-6.0.");
    Real elmt_PDE_a_Ga_GTP_conc(unit = "m-9.0.");
    Real elmt_PDE_a_Ga_GTP(unit = "m-6.0.") "PDE_a_Ga_GTP";
    Real elmt_Ga_GDP_amount(unit = "m-6.0.");
    Real elmt_Ga_GDP_conc(unit = "m-9.0.");
    Real elmt_Ga_GDP(unit = "m-6.0.") "Ga_GDP";
    Real elmt_R3_G_amount(unit = "m-6.0.");
    Real elmt_R3_G_conc(unit = "m-9.0.");
    Real elmt_R3_G(unit = "m-6.0.") "R3_G";
    Real elmt_R5_G_amount(unit = "m-6.0.");
    Real elmt_R5_G_conc(unit = "m-9.0.");
    Real elmt_R5_G(unit = "m-6.0.") "R5_G";
    Real elmt_Ops_amount(unit = "m-6.0.");
    Real elmt_Ops_conc(unit = "m-9.0.");
    Real elmt_Ops(unit = "m-6.0.") "Ops";
    Real elmt_R1_G_GTP_amount(unit = "m-6.0.");
    Real elmt_R1_G_GTP_conc(unit = "m-9.0.");
    Real elmt_R1_G_GTP(unit = "m-6.0.") "R1_G_GTP";
    Real elmt_R1_Arr_amount(unit = "m-6.0.");
    Real elmt_R1_Arr_conc(unit = "m-9.0.");
    Real elmt_R1_Arr(unit = "m-6.0.") "R1_Arr";
    Real elmt_Ca2_free_conc(unit = "m-6.0.");
    Real elmt_Ca2_free_amount(unit = "m-3.0.");
    Real elmt_Ca2_free(unit = "m-6.0.") "Ca2_free";
    Real elmt_Ga_GTP_amount(unit = "m-6.0.");
    Real elmt_Ga_GTP_conc(unit = "m-9.0.");
    Real elmt_Ga_GTP(unit = "m-6.0.") "Ga_GTP";
    Real elmt_R_Gt_amount(unit = "m-6.0.");
    Real elmt_R_Gt_conc(unit = "m-9.0.");
    Real elmt_R_Gt(unit = "m-6.0.") "R_Gt";
    Real elmt_R2_RKpre_amount(unit = "m-6.0.");
    Real elmt_R2_RKpre_conc(unit = "m-9.0.");
    Real elmt_R2_RKpre(unit = "m-6.0.") "R2_RKpre";
    Real elmt_R4_G_GTP_amount(unit = "m-6.0.");
    Real elmt_R4_G_GTP_conc(unit = "m-9.0.");
    Real elmt_R4_G_GTP(unit = "m-6.0.") "R4_G_GTP";
    Real elmt_R5_Gt_amount(unit = "m-6.0.");
    Real elmt_R5_Gt_conc(unit = "m-9.0.");
    Real elmt_R5_Gt(unit = "m-6.0.") "R5_Gt";
    Real elmt_R1_Gt_amount(unit = "m-6.0.");
    Real elmt_R1_Gt_conc(unit = "m-9.0.");
    Real elmt_R1_Gt(unit = "m-6.0.") "R1_Gt";

    initial equation
        elmt_cytosol = 0.03916;
        elmt_R3_RKpost_amount = 0.0;
        elmt_R5_RKpre_amount = 0.0;
        elmt_R2_RKpost_amount = 0.0;
        elmt_Arr_tetra_amount = 891810.0;
        elmt_Gt_amount = 8152500.0;
        elmt_R6_RKpost_amount = 0.0;
        elmt_RGS_amount = 100000.0;
        elmt_PDE_Ga_GTP_amount = 0.0;
        elmt_R1_RKpost_amount = 0.0;
        elmt_R4_RKpost_amount = 0.0;
        elmt_R5_RKpost_amount = 0.0;
        elmt_R6_Arr_amount = 0.0;
        elmt_Arr_amount = 1260760.0;
        elmt_Ga_GTP_PDE_a_Ga_GTP_amount = 0.0;
        elmt_R0_G_GTP_amount = 0.0;
        elmt_cGMP_conc = 6.4944;
        elmt_Gbg_amount = 0.0;
        elmt_R4_Gt_amount = 0.0;
        elmt_R1_RKpre_amount = 0.0;
        elmt_R_amount = 9.81525E7;
        elmt_R0_Gt_amount = 0.0;
        elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP_amount = 0.0;
        elmt_R5_Arr_amount = 0.0;
        elmt_Ops_G_GTP_amount = 0.0;
        elmt_R2_G_amount = 0.0;
        elmt_R3_G_GTP_amount = 0.0;
        elmt_R5_amount = 0.0;
        elmt_R4_G_amount = 0.0;
        elmt_R6_amount = 0.0;
        elmt_R3_amount = 0.0;
        elmt_R6_RKpre_amount = 0.0;
        elmt_R4_amount = 0.0;
        elmt_R6_G_amount = 0.0;
        elmt_G_GTP_amount = 0.0;
        elmt_PDE_amount = 2000000.0;
        elmt_R1_amount = 0.0;
        elmt_R4_RKpre_amount = 0.0;
        elmt_R2_amount = 0.0;
        elmt_Ops_Gt_amount = 0.0;
        elmt_R5_G_GTP_amount = 0.0;
        elmt_Arr_di_amount = 1123300.0;
        elmt_RecT_amount = 9289650.0;
        elmt_R0_G_amount = 0.0;
        elmt_RGS_PDE_a_Ga_GTP_amount = 0.0;
        elmt_R0_amount = 0.0;
        elmt_R3_Gt_amount = 0.0;
        elmt_R4_Arr_amount = 0.0;
        elmt_Ga_GTP_a_PDE_a_Ga_GTP_amount = 0.0;
        elmt_R2_G_GTP_amount = 0.0;
        elmt_R0_RKpre_amount = 0.0;
        elmt_R3_RKpre_amount = 0.0;
        elmt_R3_Arr_amount = 0.0;
        elmt_R6_G_GTP_amount = 0.0;
        elmt_RecR_Ca_amount = 510930.0;
        elmt_R6_Gt_amount = 0.0;
        elmt_RecR_Ca_RK_amount = 199420.0;
        elmt_R2_Gt_amount = 0.0;
        elmt_Ca2_buff_conc = 19.2199;
        elmt_Ops_G_amount = 0.0;
        elmt_RK_amount = 580.0;
        elmt_R2_Arr_amount = 0.0;
        elmt_R1_G_amount = 0.0;
        elmt_PDE_a_Ga_GTP_amount = 0.0;
        elmt_Ga_GDP_amount = 0.0;
        elmt_R3_G_amount = 0.0;
        elmt_R5_G_amount = 0.0;
        elmt_Ops_amount = 0.0;
        elmt_R1_G_GTP_amount = 0.0;
        elmt_R1_Arr_amount = 0.0;
        elmt_Ca2_free_conc = 0.25;
        elmt_Ga_GTP_amount = 0.0;
        elmt_R_Gt_amount = 1847500.0;
        elmt_R2_RKpre_amount = 0.0;
        elmt_R4_G_GTP_amount = 0.0;
        elmt_R5_Gt_amount = 0.0;
        elmt_R1_Gt_amount = 0.0;


    equation
        assert(elmt_cytosol >= 0, "Compartment size became negative. Make sure this is a valid bahaviour.");
        der(elmt_cytosol) = 0;
        elmt_R3_RKpost = elmt_R3_RKpost_amount;
        elmt_R5_RKpre = elmt_R5_RKpre_amount;
        elmt_R2_RKpost = elmt_R2_RKpost_amount;
        elmt_Arr_tetra = elmt_Arr_tetra_amount;
        elmt_Gt = elmt_Gt_amount;
        elmt_R6_RKpost = elmt_R6_RKpost_amount;
        elmt_RGS = elmt_RGS_amount;
        elmt_PDE_Ga_GTP = elmt_PDE_Ga_GTP_amount;
        elmt_R1_RKpost = elmt_R1_RKpost_amount;
        elmt_R4_RKpost = elmt_R4_RKpost_amount;
        elmt_R5_RKpost = elmt_R5_RKpost_amount;
        elmt_R6_Arr = elmt_R6_Arr_amount;
        elmt_Arr = elmt_Arr_amount;
        elmt_Ga_GTP_PDE_a_Ga_GTP = elmt_Ga_GTP_PDE_a_Ga_GTP_amount;
        elmt_R0_G_GTP = elmt_R0_G_GTP_amount;
        elmt_cGMP = elmt_cGMP_conc;
        elmt_Gbg = elmt_Gbg_amount;
        elmt_R4_Gt = elmt_R4_Gt_amount;
        elmt_R1_RKpre = elmt_R1_RKpre_amount;
        elmt_R = elmt_R_amount;
        elmt_R0_Gt = elmt_R0_Gt_amount;
        elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP = elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP_amount;
        elmt_R5_Arr = elmt_R5_Arr_amount;
        elmt_Ops_G_GTP = elmt_Ops_G_GTP_amount;
        elmt_R2_G = elmt_R2_G_amount;
        elmt_R3_G_GTP = elmt_R3_G_GTP_amount;
        elmt_R5 = elmt_R5_amount;
        elmt_R4_G = elmt_R4_G_amount;
        elmt_R6 = elmt_R6_amount;
        elmt_R3 = elmt_R3_amount;
        elmt_R6_RKpre = elmt_R6_RKpre_amount;
        elmt_R4 = elmt_R4_amount;
        elmt_R6_G = elmt_R6_G_amount;
        elmt_G_GTP = elmt_G_GTP_amount;
        elmt_PDE = elmt_PDE_amount;
        elmt_R1 = elmt_R1_amount;
        elmt_R4_RKpre = elmt_R4_RKpre_amount;
        elmt_R2 = elmt_R2_amount;
        elmt_Ops_Gt = elmt_Ops_Gt_amount;
        elmt_R5_G_GTP = elmt_R5_G_GTP_amount;
        elmt_Arr_di = elmt_Arr_di_amount;
        elmt_RecT = elmt_RecT_amount;
        elmt_R0_G = elmt_R0_G_amount;
        elmt_RGS_PDE_a_Ga_GTP = elmt_RGS_PDE_a_Ga_GTP_amount;
        elmt_R0 = elmt_R0_amount;
        elmt_R3_Gt = elmt_R3_Gt_amount;
        elmt_R4_Arr = elmt_R4_Arr_amount;
        elmt_Ga_GTP_a_PDE_a_Ga_GTP = elmt_Ga_GTP_a_PDE_a_Ga_GTP_amount;
        elmt_R2_G_GTP = elmt_R2_G_GTP_amount;
        elmt_R0_RKpre = elmt_R0_RKpre_amount;
        elmt_R3_RKpre = elmt_R3_RKpre_amount;
        elmt_R3_Arr = elmt_R3_Arr_amount;
        elmt_R6_G_GTP = elmt_R6_G_GTP_amount;
        elmt_RecR_Ca = elmt_RecR_Ca_amount;
        elmt_R6_Gt = elmt_R6_Gt_amount;
        elmt_RecR_Ca_RK = elmt_RecR_Ca_RK_amount;
        elmt_R2_Gt = elmt_R2_Gt_amount;
        elmt_Ca2_buff = elmt_Ca2_buff_conc;
        elmt_Ops_G = elmt_Ops_G_amount;
        elmt_RK = elmt_RK_amount;
        elmt_R2_Arr = elmt_R2_Arr_amount;
        elmt_R1_G = elmt_R1_G_amount;
        elmt_PDE_a_Ga_GTP = elmt_PDE_a_Ga_GTP_amount;
        elmt_Ga_GDP = elmt_Ga_GDP_amount;
        elmt_R3_G = elmt_R3_G_amount;
        elmt_R5_G = elmt_R5_G_amount;
        elmt_Ops = elmt_Ops_amount;
        elmt_R1_G_GTP = elmt_R1_G_GTP_amount;
        elmt_R1_Arr = elmt_R1_Arr_amount;
        elmt_Ca2_free = elmt_Ca2_free_conc;
        elmt_Ga_GTP = elmt_Ga_GTP_amount;
        elmt_R_Gt = elmt_R_Gt_amount;
        elmt_R2_RKpre = elmt_R2_RKpre_amount;
        elmt_R4_G_GTP = elmt_R4_G_GTP_amount;
        elmt_R5_Gt = elmt_R5_Gt_amount;
        elmt_R1_Gt = elmt_R1_Gt_amount;
        der(elmt_Ca2_free_amount / elmt_cytosol) = ((((- elmt_v_r33) - elmt_v_r34) + elmt_v_r35) - (2.0 * elmt_v_r30 * elmt_numConcFactor));
        der(elmt_R3_RKpost_amount) = ((- (elmt_v_r4_3 * elmt_reactant43)) + (elmt_v_r3_2 * elmt_product30));
        der(elmt_R5_RKpre_amount) = ((elmt_v_r2_5 * elmt_product21) + (- (elmt_v_r3_5 * elmt_reactant35)));
        der(elmt_R2_RKpost_amount) = ((- (elmt_v_r4_2 * elmt_reactant40)) + (elmt_v_r3_1 * elmt_product28));
        der(elmt_Arr_tetra_amount) = (elmt_v_r_tetraarr * elmt_product237);
        der(elmt_Gt_amount) = ((- (elmt_v_r13_0 * elmt_reactant120)) + (- (elmt_v_r13_3 * elmt_reactant129)) + (- (elmt_v_r13_4 * elmt_reactant132)) + (- (elmt_v_r13_1 * elmt_reactant123)) + (- (elmt_v_r13_2 * elmt_reactant126)) + (- (elmt_v_r13_5 * elmt_reactant135)) + (- (elmt_v_r13_6 * elmt_reactant138)) + (elmt_v_r29 * elmt_product227) + (- (elmt_v_GtRpre * elmt_reactant117)) + (- (elmt_v_r8 * elmt_reactant105)));
        der(elmt_R6_RKpost_amount) = ((- (elmt_v_r4_6 * elmt_reactant52)) + (elmt_v_r3_5 * elmt_product36));
        der(elmt_RGS_amount) = ((elmt_v_r25 * elmt_product216) + (- (elmt_v_r24 * elmt_reactant211)) + (elmt_v_r23 * elmt_product209) + (- (elmt_v_r22 * elmt_reactant204)));
        der(elmt_PDE_Ga_GTP_amount) = ((elmt_v_r18 * elmt_product195) + (- (elmt_v_r19 * elmt_reactant196)));
        der(elmt_R1_RKpost_amount) = ((- (elmt_v_r4_1 * elmt_reactant37)) + (elmt_v_r3_0 * elmt_product26));
        der(elmt_R4_RKpost_amount) = ((- (elmt_v_r4_4 * elmt_reactant46)) + (elmt_v_r3_3 * elmt_product32));
        der(elmt_R5_RKpost_amount) = ((- (elmt_v_r4_5 * elmt_reactant49)) + (elmt_v_r3_4 * elmt_product34));
        der(elmt_R6_Arr_amount) = ((- (elmt_v_r6_6 * elmt_reactant88)) + (elmt_v_r5_6 * elmt_product72));
        der(elmt_Arr_amount) = ((elmt_v_r6_6 * elmt_product89) + (elmt_v_r6_5 * elmt_product86) + (elmt_v_r6_2 * elmt_product77) + (elmt_v_r6_1 * elmt_product74) + (elmt_v_r6_4 * elmt_product83) + (elmt_v_r6_3 * elmt_product80) + (- (elmt_v_r5_6 * elmt_reactant70)) + (- (elmt_v_r5_3 * elmt_reactant61)) + (- (elmt_v_r5_2 * elmt_reactant58)) + (- (elmt_v_r5_5 * elmt_reactant67)) + (- (elmt_v_r5_4 * elmt_reactant64)) + (- (elmt_v_r5_1 * elmt_reactant55)) + (- (elmt_v_r_diarr * elmt_reactant234)));
        der(elmt_Ga_GTP_PDE_a_Ga_GTP_amount) = ((- (elmt_v_r21 * elmt_reactant201)) + (elmt_v_r20 * elmt_product200));
        der(elmt_R0_G_GTP_amount) = ((- (elmt_v_r16_0 * elmt_reactant169)) + (elmt_v_r15_0 * elmt_product156));
        der(elmt_cGMP_amount) = ((elmt_v_r36 * elmt_product242) + (- (elmt_v_r37 * elmt_reactant243)));
        der(elmt_Gbg_amount) = ((elmt_v_r17 * elmt_product192) + (- (elmt_v_r29 * elmt_reactant226)));
        der(elmt_R4_Gt_amount) = ((elmt_v_r13_4 * elmt_product134) + (- (elmt_v_r14_4 * elmt_reactant149)));
        der(elmt_R1_RKpre_amount) = ((elmt_v_r2_1 * elmt_product9) + (- (elmt_v_r3_1 * elmt_reactant27)));
        der(elmt_R_amount) = ((elmt_v_r12 * elmt_product116) + (- (elmt_v_r1 * elmt_reactant0)) + (- (elmt_v_GtRpre * elmt_reactant118)));
        der(elmt_R0_Gt_amount) = ((elmt_v_r13_0 * elmt_product122) + (elmt_v_rstprec * elmt_product3) + (- (elmt_v_r14_0 * elmt_reactant141)));
        der(elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP_amount) = ((- (elmt_v_r23 * elmt_reactant206)) + (elmt_v_r22 * elmt_product205));
        der(elmt_R5_Arr_amount) = ((- (elmt_v_r6_5 * elmt_reactant85)) + (elmt_v_r5_5 * elmt_product69));
        der(elmt_Ops_G_GTP_amount) = ((elmt_v_r10 * elmt_product111) + (- (elmt_v_r11 * elmt_reactant112)));
        der(elmt_R2_G_amount) = ((- (elmt_v_r15_2 * elmt_reactant159)) + (elmt_v_r14_2 * elmt_product146));
        der(elmt_R3_G_GTP_amount) = ((- (elmt_v_r16_3 * elmt_reactant178)) + (elmt_v_r15_3 * elmt_product162));
        der(elmt_R5_amount) = ((- (elmt_v_r13_5 * elmt_reactant136)) + (- (elmt_v_r2_5 * elmt_reactant19)) + (elmt_v_r16_5 * elmt_product186) + (- (elmt_v_r5_5 * elmt_reactant68)) + (elmt_v_r4_5 * elmt_product50) + (- (elmt_v_r7_5 * elmt_reactant101)));
        der(elmt_R4_G_amount) = ((- (elmt_v_r15_4 * elmt_reactant163)) + (elmt_v_r14_4 * elmt_product150));
        der(elmt_R6_amount) = ((- (elmt_v_r13_6 * elmt_reactant139)) + (- (elmt_v_r2_6 * elmt_reactant22)) + (elmt_v_r16_6 * elmt_product189) + (- (elmt_v_r5_6 * elmt_reactant71)) + (elmt_v_r4_6 * elmt_product53) + (- (elmt_v_r7_6 * elmt_reactant103)));
        der(elmt_R3_amount) = ((- (elmt_v_r13_3 * elmt_reactant130)) + (- (elmt_v_r2_3 * elmt_reactant13)) + (elmt_v_r16_3 * elmt_product180) + (- (elmt_v_r5_3 * elmt_reactant62)) + (elmt_v_r4_3 * elmt_product44) + (- (elmt_v_r7_3 * elmt_reactant97)));
        der(elmt_R6_RKpre_amount) = (elmt_v_r2_6 * elmt_product24);
        der(elmt_R4_amount) = ((- (elmt_v_r13_4 * elmt_reactant133)) + (- (elmt_v_r2_4 * elmt_reactant16)) + (elmt_v_r16_4 * elmt_product183) + (- (elmt_v_r5_4 * elmt_reactant65)) + (elmt_v_r4_4 * elmt_product47) + (- (elmt_v_r7_4 * elmt_reactant99)));
        der(elmt_R6_G_amount) = ((- (elmt_v_r15_6 * elmt_reactant167)) + (elmt_v_r14_6 * elmt_product154));
        der(elmt_G_GTP_amount) = ((elmt_v_r11 * elmt_product113) + (- (elmt_v_r17 * elmt_reactant190)) + (elmt_v_r16_0 * elmt_product170) + (elmt_v_r16_1 * elmt_product173) + (elmt_v_r16_4 * elmt_product182) + (elmt_v_r16_5 * elmt_product185) + (elmt_v_r16_2 * elmt_product176) + (elmt_v_r16_3 * elmt_product179) + (elmt_v_r16_6 * elmt_product188));
        der(elmt_PDE_amount) = ((- (elmt_v_r18 * elmt_reactant194)) + (elmt_v_r25 * elmt_product215) + (elmt_v_r26 * elmt_product219));
        der(elmt_R1_amount) = ((- (elmt_v_r13_1 * elmt_reactant124)) + (- (elmt_v_r2_1 * elmt_reactant7)) + (elmt_v_r16_1 * elmt_product174) + (- (elmt_v_r5_1 * elmt_reactant56)) + (elmt_v_r4_1 * elmt_product38) + (- (elmt_v_r7_1 * elmt_reactant93)));
        der(elmt_R4_RKpre_amount) = ((elmt_v_r2_4 * elmt_product18) + (- (elmt_v_r3_4 * elmt_reactant33)));
        der(elmt_R2_amount) = ((- (elmt_v_r13_2 * elmt_reactant127)) + (- (elmt_v_r2_2 * elmt_reactant10)) + (elmt_v_r16_2 * elmt_product177) + (- (elmt_v_r5_2 * elmt_reactant59)) + (elmt_v_r4_2 * elmt_product41) + (- (elmt_v_r7_2 * elmt_reactant95)));
        der(elmt_Ops_Gt_amount) = ((- (elmt_v_r9 * elmt_reactant108)) + (elmt_v_r8 * elmt_product107));
        der(elmt_R5_G_GTP_amount) = ((- (elmt_v_r16_5 * elmt_reactant184)) + (elmt_v_r15_5 * elmt_product166));
        der(elmt_Arr_di_amount) = ((- (elmt_v_r_tetraarr * elmt_reactant236)) + (elmt_v_r_diarr * elmt_product235));
        der(elmt_RecT_amount) = (- (elmt_v_r30 * elmt_reactant228));
        der(elmt_R0_G_amount) = ((- (elmt_v_r15_0 * elmt_reactant155)) + (elmt_v_r14_0 * elmt_product142));
        der(elmt_RGS_PDE_a_Ga_GTP_amount) = ((- (elmt_v_r25 * elmt_reactant213)) + (elmt_v_r24 * elmt_product212));
        der(elmt_R0_amount) = ((- (elmt_v_r13_0 * elmt_reactant121)) + (elmt_v_r1 * elmt_product1) + (- (elmt_v_r2_0 * elmt_reactant4)) + (elmt_v_r16_0 * elmt_product171) + (- (elmt_v_r7_0 * elmt_reactant91)));
        der(elmt_R3_Gt_amount) = ((elmt_v_r13_3 * elmt_product131) + (- (elmt_v_r14_3 * elmt_reactant147)));
        der(elmt_R4_Arr_amount) = ((- (elmt_v_r6_4 * elmt_reactant82)) + (elmt_v_r5_4 * elmt_product66));
        der(elmt_Ga_GTP_a_PDE_a_Ga_GTP_amount) = ((elmt_v_r21 * elmt_product202) + (- (elmt_v_r22 * elmt_reactant203)) + (- (elmt_v_r27 * elmt_reactant220)));
        der(elmt_R2_G_GTP_amount) = ((- (elmt_v_r16_2 * elmt_reactant175)) + (elmt_v_r15_2 * elmt_product160));
        der(elmt_R0_RKpre_amount) = ((elmt_v_r2_0 * elmt_product6) + (- (elmt_v_r3_0 * elmt_reactant25)));
        der(elmt_R3_RKpre_amount) = ((elmt_v_r2_3 * elmt_product15) + (- (elmt_v_r3_3 * elmt_reactant31)));
        der(elmt_R3_Arr_amount) = ((- (elmt_v_r6_3 * elmt_reactant79)) + (elmt_v_r5_3 * elmt_product63));
        der(elmt_R6_G_GTP_amount) = ((- (elmt_v_r16_6 * elmt_reactant187)) + (elmt_v_r15_6 * elmt_product168));
        der(elmt_RecR_Ca_amount) = ((- (elmt_v_r31 * elmt_reactant232)) + (elmt_v_r30 * elmt_product230));
        der(elmt_R6_Gt_amount) = ((elmt_v_r13_6 * elmt_product140) + (- (elmt_v_r14_6 * elmt_reactant153)));
        der(elmt_RecR_Ca_RK_amount) = (elmt_v_r31 * elmt_product233);
        der(elmt_R2_Gt_amount) = ((elmt_v_r13_2 * elmt_product128) + (- (elmt_v_r14_2 * elmt_reactant145)));
        der(elmt_Ca2_buff_amount) = (elmt_v_r33 * elmt_product239);
        der(elmt_Ops_G_amount) = ((- (elmt_v_r10 * elmt_reactant110)) + (elmt_v_r9 * elmt_product109));
        der(elmt_RK_amount) = ((- (elmt_v_r2_6 * elmt_reactant23)) + (- (elmt_v_r2_5 * elmt_reactant20)) + (- (elmt_v_r2_2 * elmt_reactant11)) + (- (elmt_v_r2_1 * elmt_reactant8)) + (- (elmt_v_r2_4 * elmt_reactant17)) + (- (elmt_v_r2_3 * elmt_reactant14)) + (- (elmt_v_r2_0 * elmt_reactant5)) + (elmt_v_r4_4 * elmt_product48) + (elmt_v_r4_3 * elmt_product45) + (elmt_v_r4_6 * elmt_product54) + (elmt_v_r4_5 * elmt_product51) + (elmt_v_r4_2 * elmt_product42) + (elmt_v_r4_1 * elmt_product39) + (- (elmt_v_r31 * elmt_reactant231)));
        der(elmt_R2_Arr_amount) = ((- (elmt_v_r6_2 * elmt_reactant76)) + (elmt_v_r5_2 * elmt_product60));
        der(elmt_R1_G_amount) = ((- (elmt_v_r15_1 * elmt_reactant157)) + (elmt_v_r14_1 * elmt_product144));
        der(elmt_PDE_a_Ga_GTP_amount) = ((- (elmt_v_r20 * elmt_reactant199)) + (- (elmt_v_r24 * elmt_reactant210)) + (elmt_v_r23 * elmt_product208) + (elmt_v_r27 * elmt_product222) + (- (elmt_v_r26 * elmt_reactant217)) + (elmt_v_r19 * elmt_product197));
        der(elmt_Ga_GDP_amount) = ((elmt_v_r25 * elmt_product214) + (elmt_v_r23 * elmt_product207) + (- (elmt_v_r29 * elmt_reactant225)) + (elmt_v_r28 * elmt_product224) + (elmt_v_r27 * elmt_product221) + (elmt_v_r26 * elmt_product218));
        der(elmt_R3_G_amount) = ((- (elmt_v_r15_3 * elmt_reactant161)) + (elmt_v_r14_3 * elmt_product148));
        der(elmt_R5_G_amount) = ((- (elmt_v_r15_5 * elmt_reactant165)) + (elmt_v_r14_5 * elmt_product152));
        der(elmt_Ops_amount) = ((- (elmt_v_r12 * elmt_reactant115)) + (elmt_v_r11 * elmt_product114) + (elmt_v_r6_6 * elmt_product90) + (elmt_v_r6_5 * elmt_product87) + (elmt_v_r6_2 * elmt_product78) + (elmt_v_r6_1 * elmt_product75) + (elmt_v_r6_4 * elmt_product84) + (elmt_v_r6_3 * elmt_product81) + (elmt_v_r7_5 * elmt_product102) + (elmt_v_r7_4 * elmt_product100) + (- (elmt_v_r8 * elmt_reactant106)) + (elmt_v_r7_6 * elmt_product104) + (elmt_v_r7_1 * elmt_product94) + (elmt_v_r7_0 * elmt_product92) + (elmt_v_r7_3 * elmt_product98) + (elmt_v_r7_2 * elmt_product96));
        der(elmt_R1_G_GTP_amount) = ((- (elmt_v_r16_1 * elmt_reactant172)) + (elmt_v_r15_1 * elmt_product158));
        der(elmt_R1_Arr_amount) = ((- (elmt_v_r6_1 * elmt_reactant73)) + (elmt_v_r5_1 * elmt_product57));
        der(elmt_Ga_GTP_amount) = ((- (elmt_v_r18 * elmt_reactant193)) + (elmt_v_r17 * elmt_product191) + (- (elmt_v_r20 * elmt_reactant198)) + (- (elmt_v_r28 * elmt_reactant223)));
        der(elmt_R_Gt_amount) = ((- (elmt_v_rstprec * elmt_reactant2)) + (elmt_v_GtRpre * elmt_product119));
        der(elmt_R2_RKpre_amount) = ((elmt_v_r2_2 * elmt_product12) + (- (elmt_v_r3_2 * elmt_reactant29)));
        der(elmt_R4_G_GTP_amount) = ((- (elmt_v_r16_4 * elmt_reactant181)) + (elmt_v_r15_4 * elmt_product164));
        der(elmt_R5_Gt_amount) = ((elmt_v_r13_5 * elmt_product137) + (- (elmt_v_r14_5 * elmt_reactant151)));
        der(elmt_R1_Gt_amount) = ((elmt_v_r13_1 * elmt_product125) + (- (elmt_v_r14_1 * elmt_reactant143)));

    algorithm
        elmt_R3_RKpost_conc := elmt_R3_RKpost_amount / elmt_cytosol;
        elmt_R5_RKpre_conc := elmt_R5_RKpre_amount / elmt_cytosol;
        elmt_R2_RKpost_conc := elmt_R2_RKpost_amount / elmt_cytosol;
        elmt_Arr_tetra_conc := elmt_Arr_tetra_amount / elmt_cytosol;
        elmt_Gt_conc := elmt_Gt_amount / elmt_cytosol;
        elmt_R6_RKpost_conc := elmt_R6_RKpost_amount / elmt_cytosol;
        elmt_RGS_conc := elmt_RGS_amount / elmt_cytosol;
        elmt_PDE_Ga_GTP_conc := elmt_PDE_Ga_GTP_amount / elmt_cytosol;
        elmt_R1_RKpost_conc := elmt_R1_RKpost_amount / elmt_cytosol;
        elmt_R4_RKpost_conc := elmt_R4_RKpost_amount / elmt_cytosol;
        elmt_R5_RKpost_conc := elmt_R5_RKpost_amount / elmt_cytosol;
        elmt_R6_Arr_conc := elmt_R6_Arr_amount / elmt_cytosol;
        elmt_Arr_conc := elmt_Arr_amount / elmt_cytosol;
        elmt_Ga_GTP_PDE_a_Ga_GTP_conc := elmt_Ga_GTP_PDE_a_Ga_GTP_amount / elmt_cytosol;
        elmt_R0_G_GTP_conc := elmt_R0_G_GTP_amount / elmt_cytosol;
        elmt_cGMP_conc := elmt_cGMP_amount / elmt_cytosol;
        elmt_Gbg_conc := elmt_Gbg_amount / elmt_cytosol;
        elmt_R4_Gt_conc := elmt_R4_Gt_amount / elmt_cytosol;
        elmt_R1_RKpre_conc := elmt_R1_RKpre_amount / elmt_cytosol;
        elmt_R_conc := elmt_R_amount / elmt_cytosol;
        elmt_R0_Gt_conc := elmt_R0_Gt_amount / elmt_cytosol;
        elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP_conc := elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP_amount / elmt_cytosol;
        elmt_R5_Arr_conc := elmt_R5_Arr_amount / elmt_cytosol;
        elmt_Ops_G_GTP_conc := elmt_Ops_G_GTP_amount / elmt_cytosol;
        elmt_R2_G_conc := elmt_R2_G_amount / elmt_cytosol;
        elmt_R3_G_GTP_conc := elmt_R3_G_GTP_amount / elmt_cytosol;
        elmt_R5_conc := elmt_R5_amount / elmt_cytosol;
        elmt_R4_G_conc := elmt_R4_G_amount / elmt_cytosol;
        elmt_R6_conc := elmt_R6_amount / elmt_cytosol;
        elmt_R3_conc := elmt_R3_amount / elmt_cytosol;
        elmt_R6_RKpre_conc := elmt_R6_RKpre_amount / elmt_cytosol;
        elmt_R4_conc := elmt_R4_amount / elmt_cytosol;
        elmt_R6_G_conc := elmt_R6_G_amount / elmt_cytosol;
        elmt_G_GTP_conc := elmt_G_GTP_amount / elmt_cytosol;
        elmt_PDE_conc := elmt_PDE_amount / elmt_cytosol;
        elmt_R1_conc := elmt_R1_amount / elmt_cytosol;
        elmt_R4_RKpre_conc := elmt_R4_RKpre_amount / elmt_cytosol;
        elmt_R2_conc := elmt_R2_amount / elmt_cytosol;
        elmt_Ops_Gt_conc := elmt_Ops_Gt_amount / elmt_cytosol;
        elmt_R5_G_GTP_conc := elmt_R5_G_GTP_amount / elmt_cytosol;
        elmt_Arr_di_conc := elmt_Arr_di_amount / elmt_cytosol;
        elmt_RecT_conc := elmt_RecT_amount / elmt_cytosol;
        elmt_R0_G_conc := elmt_R0_G_amount / elmt_cytosol;
        elmt_RGS_PDE_a_Ga_GTP_conc := elmt_RGS_PDE_a_Ga_GTP_amount / elmt_cytosol;
        elmt_R0_conc := elmt_R0_amount / elmt_cytosol;
        elmt_R3_Gt_conc := elmt_R3_Gt_amount / elmt_cytosol;
        elmt_R4_Arr_conc := elmt_R4_Arr_amount / elmt_cytosol;
        elmt_Ga_GTP_a_PDE_a_Ga_GTP_conc := elmt_Ga_GTP_a_PDE_a_Ga_GTP_amount / elmt_cytosol;
        elmt_R2_G_GTP_conc := elmt_R2_G_GTP_amount / elmt_cytosol;
        elmt_R0_RKpre_conc := elmt_R0_RKpre_amount / elmt_cytosol;
        elmt_R3_RKpre_conc := elmt_R3_RKpre_amount / elmt_cytosol;
        elmt_R3_Arr_conc := elmt_R3_Arr_amount / elmt_cytosol;
        elmt_R6_G_GTP_conc := elmt_R6_G_GTP_amount / elmt_cytosol;
        elmt_RecR_Ca_conc := elmt_RecR_Ca_amount / elmt_cytosol;
        elmt_R6_Gt_conc := elmt_R6_Gt_amount / elmt_cytosol;
        elmt_RecR_Ca_RK_conc := elmt_RecR_Ca_RK_amount / elmt_cytosol;
        elmt_R2_Gt_conc := elmt_R2_Gt_amount / elmt_cytosol;
        elmt_Ca2_buff_conc := elmt_Ca2_buff_amount / elmt_cytosol;
        elmt_Ops_G_conc := elmt_Ops_G_amount / elmt_cytosol;
        elmt_RK_conc := elmt_RK_amount / elmt_cytosol;
        elmt_R2_Arr_conc := elmt_R2_Arr_amount / elmt_cytosol;
        elmt_R1_G_conc := elmt_R1_G_amount / elmt_cytosol;
        elmt_PDE_a_Ga_GTP_conc := elmt_PDE_a_Ga_GTP_amount / elmt_cytosol;
        elmt_Ga_GDP_conc := elmt_Ga_GDP_amount / elmt_cytosol;
        elmt_R3_G_conc := elmt_R3_G_amount / elmt_cytosol;
        elmt_R5_G_conc := elmt_R5_G_amount / elmt_cytosol;
        elmt_Ops_conc := elmt_Ops_amount / elmt_cytosol;
        elmt_R1_G_GTP_conc := elmt_R1_G_GTP_amount / elmt_cytosol;
        elmt_R1_Arr_conc := elmt_R1_Arr_amount / elmt_cytosol;
        elmt_Ca2_free_conc := elmt_Ca2_free_amount / elmt_cytosol;
        elmt_Ga_GTP_conc := elmt_Ga_GTP_amount / elmt_cytosol;
        elmt_R_Gt_conc := elmt_R_Gt_amount / elmt_cytosol;
        elmt_R2_RKpre_conc := elmt_R2_RKpre_amount / elmt_cytosol;
        elmt_R4_G_GTP_conc := elmt_R4_G_GTP_amount / elmt_cytosol;
        elmt_R5_Gt_conc := elmt_R5_Gt_amount / elmt_cytosol;
        elmt_R1_Gt_conc := elmt_R1_Gt_amount / elmt_cytosol;
end Class_elmt_cytosol;
