within BIOMD149;
class Parameters

    input Real elmt_X14;
    input Real elmt_X13;

    input Boolean elmt_event_0000001;    input Boolean elmt_event_0000002;
    input Real assign_elmt_W;


    Real elmt_n1(unit = "") "";
    Real elmt_k_minus6(unit = "") "";
    Real elmt_k_minus8(unit = "") "";
    Real elmt_k_minus7(unit = "") "";
    Real elmt_W(unit = "") "";
    Real elmt_k15(unit = "") "";
    Real elmt_Ki(unit = "") "";
    Real elmt_k14(unit = "") "";
    Real elmt_k13(unit = "") "";
    Real elmt_k11(unit = "") "";
    Real elmt_k10(unit = "") "";
    Real elmt_k_plus17(unit = "") "";
    Real elmt_Vmax5(unit = "") "";
    Real elmt_kcat6(unit = "") "";
    Real elmt_k1(unit = "") "";
    Real elmt_k_plus16(unit = "") "";
    Real elmt_Vmax6(unit = "") "";
    Real elmt_kcat7(unit = "") "";
    Real elmt_Vmax3(unit = "") "";
    Real elmt_kcat4(unit = "") "";
    Real elmt_Vmax4(unit = "") "";
    Real elmt_kcat5(unit = "") "";
    Real elmt_Vmax1(unit = "") "";
    Real elmt_Vmax2(unit = "") "";
    Real elmt_k19(unit = "") "";
    Real elmt_k18(unit = "") "";
    Real elmt_k9(unit = "") "";
    Real elmt_k4(unit = "") "";
    Real elmt_kcat2(unit = "") "";
    Real elmt_k5(unit = "") "";
    Real elmt_kcat3(unit = "") "";
    Real elmt_k2(unit = "") "";
    Real elmt_Vmax7(unit = "") "";
    Real elmt_k3(unit = "") "";
    Real elmt_kcat1(unit = "") "";
    Real elmt_Km1(unit = "") "";
    Real elmt_Km2(unit = "") "";
    Real elmt_k21(unit = "") "";
    Real elmt_k_minus17(unit = "") "";
    Real elmt_k_minus16(unit = "") "";
    Real elmt_k20(unit = "") "";
    Real elmt_Km9(unit = "") "";
    Real elmt_V12(unit = "") "";
    Real elmt_Km7(unit = "") "";
    Real elmt_Km8(unit = "") "";
    Real elmt_flag_for_wnt_signal(unit = "") "";
    Real elmt_k_plus8(unit = "") "";
    Real elmt_Km5(unit = "") "";
    Real elmt_k_plus7(unit = "") "";
    Real elmt_Km6(unit = "") "";
    Real elmt_Km3(unit = "") "";
    Real elmt_Km4(unit = "") "";
    Real elmt_k_plus6(unit = "") "";
    Real elmt_X13X14(unit = "") "";
    Real elmt_Km14(unit = "") "";
    Real elmt_Km12(unit = "") "";
    Real elmt_Km13(unit = "") "";
    Real elmt_Km10(unit = "") "";
    Real elmt_Km11(unit = "") "";


    initial equation
        elmt_n1 = 2.0;
        elmt_k_minus6 = 0.909;
        elmt_k_minus8 = 120.0;
        elmt_k_minus7 = 50.0;
        elmt_W = 0.0;
        elmt_k15 = 0.167;
        elmt_Ki = 9.0;
        elmt_k14 = 8.22E-5;
        elmt_k13 = 2.57E-4;
        elmt_k11 = 0.417;
        elmt_k10 = 206.0;
        elmt_k_plus17 = 1.0;
        elmt_Vmax5 = 45.0;
        elmt_kcat6 = 1.5;
        elmt_k1 = 0.182;
        elmt_k_plus16 = 1.0;
        elmt_Vmax6 = 45.0;
        elmt_kcat7 = 1.5;
        elmt_Vmax3 = 45.0;
        elmt_kcat4 = 1.5;
        elmt_Vmax4 = 45.0;
        elmt_kcat5 = 0.6;
        elmt_Vmax1 = 150.0;
        elmt_Vmax2 = 15.0;
        elmt_k19 = 39.0;
        elmt_k18 = 0.15;
        elmt_k9 = 206.0;
        elmt_k4 = 0.267;
        elmt_kcat2 = 1.5;
        elmt_k5 = 0.133;
        elmt_kcat3 = 1.5;
        elmt_k2 = 0.0182;
        elmt_Vmax7 = 45.0;
        elmt_k3 = 0.05;
        elmt_kcat1 = 1.5;
        elmt_Km1 = 10.0;
        elmt_Km2 = 8.0;
        elmt_k21 = 1.0E-6;
        elmt_k_minus17 = 1200.0;
        elmt_k_minus16 = 30.0;
        elmt_k20 = 0.015;
        elmt_Km9 = 9.0;
        elmt_V12 = 0.423;
        elmt_Km7 = 15.0;
        elmt_Km8 = 15.0;
        elmt_flag_for_wnt_signal = 0.0;
        elmt_k_plus8 = 1.0;
        elmt_Km5 = 15.0;
        elmt_k_plus7 = 1.0;
        elmt_Km6 = 15.0;
        elmt_Km3 = 15.0;
        elmt_Km4 = 15.0;
        elmt_k_plus6 = 0.0909;
        elmt_Km14 = 15.0;
        elmt_Km12 = 15.0;
        elmt_Km13 = 15.0;
        elmt_Km10 = 12.0;
        elmt_Km11 = 15.0;


    equation
        der(elmt_n1) = 0;
        der(elmt_k_minus6) = 0;
        der(elmt_k_minus8) = 0;
        der(elmt_k_minus7) = 0;
        der(elmt_W) = 0.0;
        der(elmt_k15) = 0;
        der(elmt_Ki) = 0;
        der(elmt_k14) = 0;
        der(elmt_k13) = 0;
        der(elmt_k11) = 0;
        der(elmt_k10) = 0;
        der(elmt_k_plus17) = 0;
        der(elmt_Vmax5) = 0;
        der(elmt_kcat6) = 0;
        der(elmt_k1) = 0;
        der(elmt_k_plus16) = 0;
        der(elmt_Vmax6) = 0;
        der(elmt_kcat7) = 0;
        der(elmt_Vmax3) = 0;
        der(elmt_kcat4) = 0;
        der(elmt_Vmax4) = 0;
        der(elmt_kcat5) = 0;
        der(elmt_Vmax1) = 0;
        der(elmt_Vmax2) = 0;
        der(elmt_k19) = 0;
        der(elmt_k18) = 0;
        der(elmt_k9) = 0;
        der(elmt_k4) = 0;
        der(elmt_kcat2) = 0;
        der(elmt_k5) = 0;
        der(elmt_kcat3) = 0;
        der(elmt_k2) = 0;
        der(elmt_Vmax7) = 0;
        der(elmt_k3) = 0;
        der(elmt_kcat1) = 0;
        der(elmt_Km1) = 0;
        der(elmt_Km2) = 0;
        der(elmt_k21) = 0;
        der(elmt_k_minus17) = 0;
        der(elmt_k_minus16) = 0;
        der(elmt_k20) = 0;
        der(elmt_Km9) = 0;
        der(elmt_V12) = 0;
        der(elmt_Km7) = 0;
        der(elmt_Km8) = 0;
        der(elmt_flag_for_wnt_signal) = 0;
        der(elmt_k_plus8) = 0;
        der(elmt_Km5) = 0;
        der(elmt_k_plus7) = 0;
        der(elmt_Km6) = 0;
        der(elmt_Km3) = 0;
        der(elmt_Km4) = 0;
        der(elmt_k_plus6) = 0;
        elmt_X13X14 = (elmt_X13 + elmt_X14);
        der(elmt_Km14) = 0;
        der(elmt_Km12) = 0;
        der(elmt_Km13) = 0;
        der(elmt_Km10) = 0;
        der(elmt_Km11) = 0;

        when elmt_event_0000001 then
            reinit(elmt_W, assign_elmt_W);
        end when;
        when elmt_event_0000002 then
            reinit(elmt_W, assign_elmt_W);
        end when;
end Parameters;
