within BIOMD007;
class Parameters

    input Real elmt_UbE;
    input Real elmt_Wee1;
    input Real elmt_UbE2;
    input Real elmt_Cdc25;

    input Boolean elmt_Division;    input Boolean elmt_Start;
    input Real assign_elmt_kp;
    input Real assign_elmt_Mass;


    Real elmt_Kmw(unit = "") "Kmw";
    Real elmt_Kmu(unit = "") "Kmu";
    Real elmt_V25prime(unit = "") "V25'";
    Real elmt_kur(unit = "") "kur";
    Real elmt_k7r(unit = "") "k7r";
    Real elmt_Cig1(unit = "") "Cig1";
    Real elmt_kur2(unit = "") "kur2";
    Real elmt_k1(unit = "") "k1";
    Real elmt_kir(unit = "") "kir";
    Real elmt_Kmu2(unit = "") "Kmu2";
    Real elmt_V6(unit = "") "V6";
    Real elmt_k8(unit = "") "k8";
    Real elmt_k6(unit = "") "k6";
    Real elmt_k6prime(unit = "") "k6'";
    Real elmt_k7(unit = "") "k7";
    Real elmt_k4(unit = "") "k4";
    Real elmt_k5(unit = "") "k5";
    Real elmt_k2(unit = "") "k2";
    Real elmt_mu(unit = "") "mu";
    Real elmt_k3(unit = "") "k3";
    Real elmt_k8r(unit = "") "k8r";
    Real elmt_Kmwr(unit = "") "Kmwr";
    Real elmt_k25(unit = "") "k25";
    Real elmt_V2(unit = "") "V2";
    Real elmt_Vwprime(unit = "") "Vw'";
    Real elmt_V2prime(unit = "") "V2'";
    Real elmt_ku2(unit = "") "ku2";
    Real elmt_k2prime(unit = "") "k2'";
    Real elmt_kwr(unit = "") "kwr";
    Real elmt_Kmcr(unit = "") "Kmcr";
    Real elmt_alpha(unit = "") "alpha";
    Real elmt_kp(unit = "") "kp";
    Real elmt_beta(unit = "") "beta";
    Real elmt_Vw(unit = "") "Vw";
    Real elmt_Kmur(unit = "") "Kmur";
    Real elmt_V6prime(unit = "") "V6'";
    Real elmt_Kmir(unit = "") "Kmir";
    Real elmt_kw(unit = "") "kw";
    Real elmt_ku(unit = "") "ku";
    Real elmt_kcr(unit = "") "kcr";
    Real elmt_V25(unit = "") "V25";
    Real elmt_Kmi(unit = "") "Kmi";
    Real elmt_Mass(unit = "") "Mass";
    Real elmt_Kmc(unit = "") "Kmc";
    Real elmt_kwee(unit = "") "kwee";
    Real elmt_ki(unit = "") "ki";
    Real elmt_Kmp(unit = "") "Kmp";
    Real elmt_Kmur2(unit = "") "Kmur2";
    Real elmt_kc(unit = "") "kc";


    initial equation
        elmt_Kmw = 0.1;
        elmt_Kmu = 0.01;
        elmt_V25prime = 0.025;
        elmt_kur = 0.1;
        elmt_k7r = 0.1;
        elmt_Cig1 = 0.0;
        elmt_kur2 = 0.3;
        elmt_k1 = 0.015;
        elmt_kir = 0.1;
        elmt_Kmu2 = 0.05;
        elmt_V6 = 7.5;
        elmt_k8 = 10.0;
        elmt_k6prime = 0.0;
        elmt_k7 = 100.0;
        elmt_k4 = 0.1875;
        elmt_k5 = 0.00175;
        elmt_mu = 0.00495;
        elmt_k3 = 0.09375;
        elmt_k8r = 0.1;
        elmt_Kmwr = 0.1;
        elmt_V2 = 0.25;
        elmt_Vwprime = 0.035;
        elmt_V2prime = 0.0075;
        elmt_ku2 = 1.0;
        elmt_k2prime = 0.05;
        elmt_kwr = 0.25;
        elmt_Kmcr = 0.1;
        elmt_alpha = 0.25;
        elmt_kp = 3.25;
        elmt_beta = 0.05;
        elmt_Vw = 0.35;
        elmt_Kmur = 0.01;
        elmt_V6prime = 0.0375;
        elmt_Kmir = 0.01;
        elmt_kw = 1.0;
        elmt_ku = 0.2;
        elmt_kcr = 0.25;
        elmt_V25 = 0.5;
        elmt_Kmi = 0.01;
        elmt_Mass = 0.49;
        elmt_Kmc = 0.1;
        elmt_ki = 0.4;
        elmt_Kmp = 0.001;
        elmt_Kmur2 = 0.05;
        elmt_kc = 1.0;


    equation
        der(elmt_Kmw) = 0;
        der(elmt_Kmu) = 0;
        der(elmt_V25prime) = 0;
        der(elmt_kur) = 0;
        der(elmt_k7r) = 0;
        der(elmt_Cig1) = 0;
        der(elmt_kur2) = 0;
        der(elmt_k1) = 0;
        der(elmt_kir) = 0;
        der(elmt_Kmu2) = 0;
        der(elmt_V6) = 0;
        der(elmt_k8) = 0;
        elmt_k6 = ((elmt_UbE2 * elmt_V6) + ((1.0 - elmt_UbE2) * elmt_V6prime));
        der(elmt_k6prime) = 0;
        der(elmt_k7) = 0;
        der(elmt_k4) = 0;
        der(elmt_k5) = 0;
        elmt_k2 = ((elmt_UbE * elmt_V2) + ((1.0 - elmt_UbE) * elmt_V2prime));
        der(elmt_mu) = 0;
        der(elmt_k3) = 0;
        der(elmt_k8r) = 0;
        der(elmt_Kmwr) = 0;
        elmt_k25 = ((elmt_Cdc25 * elmt_V25) + ((1.0 - elmt_Cdc25) * elmt_V25prime));
        der(elmt_V2) = 0;
        der(elmt_Vwprime) = 0;
        der(elmt_V2prime) = 0;
        der(elmt_ku2) = 0;
        der(elmt_k2prime) = 0;
        der(elmt_kwr) = 0;
        der(elmt_Kmcr) = 0;
        der(elmt_alpha) = 0;
        der(elmt_kp) = 0.0;
        der(elmt_beta) = 0;
        der(elmt_Vw) = 0;
        der(elmt_Kmur) = 0;
        der(elmt_V6prime) = 0;
        der(elmt_Kmir) = 0;
        der(elmt_kw) = 0;
        der(elmt_ku) = 0;
        der(elmt_kcr) = 0;
        der(elmt_V25) = 0;
        der(elmt_Kmi) = 0;
        der(elmt_Mass) = (elmt_Mass * elmt_mu);
        der(elmt_Kmc) = 0;
        elmt_kwee = ((elmt_Vwprime * (1.0 - elmt_Wee1)) + (elmt_Vw * elmt_Wee1));
        der(elmt_ki) = 0;
        der(elmt_Kmp) = 0;
        der(elmt_Kmur2) = 0;
        der(elmt_kc) = 0;

        when elmt_Division then
            reinit(elmt_kp, assign_elmt_kp);
            reinit(elmt_Mass, assign_elmt_Mass);
        end when;
        when elmt_Start then
            reinit(elmt_kp, assign_elmt_kp);
        end when;
end Parameters;
