/* Main Simulation File */
/* Simulation code for MoonLanding generated by the OpenModelica Compiler 1.9.2 (r25115). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "MoonLanding_functions.h"
#include "MoonLanding_model.h"
#include "MoonLanding_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


#define prefixedName_performSimulation MoonLanding_performSimulation
#include <simulation/solver/perform_simulation.c>

#define prefixedName_performQSSSimulation MoonLanding_performQSSSimulation
#include <simulation/solver/perform_qss_simulation.c>

/* dummy VARINFO and FILEINFO */
const FILE_INFO dummyFILE_INFO = omc_dummyFileInfo;
const VAR_INFO dummyVAR_INFO = omc_dummyVarInfo;
#if defined(__cplusplus)
extern "C" {
#endif
int measure_time_flag = 0;

int MoonLanding_input_function(DATA *data)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}

int MoonLanding_input_function_init(DATA *data)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}


int MoonLanding_output_function(DATA *data)
{
  TRACE_PUSH

  
  TRACE_POP
  return 0;
}


/*
 equation index: 20
 type: SIMPLE_ASSIGN
 $whenCondition1 = sample(1, 0.0, ctr.T)
 */
void MoonLanding_eqFunction_20(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,20};
  $P$whenCondition1 = $P$sample1;
  TRACE_POP
}
/*
 equation index: 21
 type: SIMPLE_ASSIGN
 der(apollo._altitude) = apollo.velocity
 */
void MoonLanding_eqFunction_21(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,21};
  $P$DER$Papollo$Paltitude = $Papollo$Pvelocity;
  TRACE_POP
}
/*
 equation index: 22
 type: SIMPLE_ASSIGN
 der(ctr._altitude) = ctr.velocity
 */
void MoonLanding_eqFunction_22(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,22};
  $P$DER$Pctr$Paltitude = $Pctr$Pvelocity;
  TRACE_POP
}
/*
 equation index: 23
 type: WHEN
 
 when {$whenCondition1} then
   ctr._history = pre(ctr.thrust);
 end when;
 */
void MoonLanding_eqFunction_23(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,23};
  if(initial())
  {
    $Pctr$Phistory = $P$PRE$Pctr$Phistory;
  }
  else if(0 || ($P$whenCondition1 && !$P$PRE$P$whenCondition1 /* edge */))
  {
    $Pctr$Phistory = $P$PRE$Pctr$Pthrust;
  }
  else
  {
    $Pctr$Phistory = $P$PRE$Pctr$Phistory;
  }
  TRACE_POP
}
/*
 equation index: 24
 type: WHEN
 
 when {$whenCondition1} then
   ctr._thrust = ECU.autopilot7(ctr.altitude, ctr.velocity, force1, force2, ctr.history);
 end when;
 */
void MoonLanding_eqFunction_24(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,24};
  if(initial())
  {
    $Pctr$Pthrust = $P$PRE$Pctr$Pthrust;
  }
  else if(0 || ($P$whenCondition1 && !$P$PRE$P$whenCondition1 /* edge */))
  {
    $Pctr$Pthrust = omc_ECU_autopilot7(threadData, $Pctr$Paltitude, $Pctr$Pvelocity, $Pforce1, $Pforce2, $Pctr$Phistory);
  }
  else
  {
    $Pctr$Pthrust = $P$PRE$Pctr$Pthrust;
  }
  TRACE_POP
}
/*
 equation index: 25
 type: SIMPLE_ASSIGN
 der(apollo._mass) = (-apollo.massLossRate) * abs(ctr.thrust)
 */
void MoonLanding_eqFunction_25(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,25};
  $P$DER$Papollo$Pmass = ((-$Papollo$PmassLossRate) * fabs($Pctr$Pthrust));
  TRACE_POP
}
/*
 equation index: 26
 type: SIMPLE_ASSIGN
 apollo._gravity = 6.672e-11 * DIVISION(moon.mass, (apollo.altitude + moon.radius) ^ 2.0)
 */
void MoonLanding_eqFunction_26(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,26};
  modelica_real tmp5;
  tmp5 = ($Papollo$Paltitude + $Pmoon$Pradius);
  $Papollo$Pgravity = (6.672e-11 * DIVISION_SIM($Pmoon$Pmass,(tmp5 * tmp5),"(apollo.altitude + moon.radius) ^ 2.0",equationIndexes));
  TRACE_POP
}
/*
 equation index: 27
 type: SIMPLE_ASSIGN
 ctr._acceleration = DIVISION(ctr.thrust - apollo.mass * apollo.gravity, apollo.mass)
 */
void MoonLanding_eqFunction_27(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,27};
  $Pctr$Pacceleration = DIVISION_SIM(($Pctr$Pthrust - ($Papollo$Pmass * $Papollo$Pgravity)),$Papollo$Pmass,"apollo.mass",equationIndexes);
  TRACE_POP
}
/*
 equation index: 28
 type: SIMPLE_ASSIGN
 der(ctr._velocity) = ctr.acceleration
 */
void MoonLanding_eqFunction_28(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,28};
  $P$DER$Pctr$Pvelocity = $Pctr$Pacceleration;
  TRACE_POP
}
/*
 equation index: 29
 type: SIMPLE_ASSIGN
 der(apollo._velocity) = ctr.acceleration
 */
void MoonLanding_eqFunction_29(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,29};
  $P$DER$Papollo$Pvelocity = $Pctr$Pacceleration;
  TRACE_POP
}
/*
 equation index: 30
 type: SIMPLE_ASSIGN
 ctr._initial_velocity = apollo.initial_velocity
 */
void MoonLanding_eqFunction_30(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,30};
  $Pctr$Pinitial_velocity = $Papollo$Pinitial_velocity;
  TRACE_POP
}
/*
 equation index: 31
 type: SIMPLE_ASSIGN
 ctr._initial_altitude = apollo.initial_altitude
 */
void MoonLanding_eqFunction_31(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,31};
  $Pctr$Pinitial_altitude = $Papollo$Pinitial_altitude;
  TRACE_POP
}


int MoonLanding_functionDAE(DATA *data)
{
  TRACE_PUSH
  int equationIndexes[1] = {0};
  
  data->simulationInfo.needToIterate = 0;
  data->simulationInfo.discreteCall = 1;
  MoonLanding_eqFunction_20(data);

  MoonLanding_eqFunction_21(data);

  MoonLanding_eqFunction_22(data);

  MoonLanding_eqFunction_23(data);

  MoonLanding_eqFunction_24(data);

  MoonLanding_eqFunction_25(data);

  MoonLanding_eqFunction_26(data);

  MoonLanding_eqFunction_27(data);

  MoonLanding_eqFunction_28(data);

  MoonLanding_eqFunction_29(data);

  MoonLanding_eqFunction_30(data);

  MoonLanding_eqFunction_31(data);
  
  
  
  TRACE_POP
  return 0;
}


/* forwarded equations */
extern void MoonLanding_eqFunction_20(DATA* data);
extern void MoonLanding_eqFunction_21(DATA* data);
extern void MoonLanding_eqFunction_22(DATA* data);
extern void MoonLanding_eqFunction_25(DATA* data);
extern void MoonLanding_eqFunction_26(DATA* data);
extern void MoonLanding_eqFunction_27(DATA* data);
extern void MoonLanding_eqFunction_28(DATA* data);
extern void MoonLanding_eqFunction_29(DATA* data);

static void functionODE_system0(DATA *data)
{
  MoonLanding_eqFunction_20(data);

  MoonLanding_eqFunction_21(data);

  MoonLanding_eqFunction_22(data);

  MoonLanding_eqFunction_25(data);

  MoonLanding_eqFunction_26(data);

  MoonLanding_eqFunction_27(data);

  MoonLanding_eqFunction_28(data);

  MoonLanding_eqFunction_29(data);
}

int MoonLanding_functionODE(DATA *data)
{
  TRACE_PUSH

  
  data->simulationInfo.callStatistics.functionODE++;
  
  data->simulationInfo.discreteCall = 0;
  functionODE_system0(data);

  
  TRACE_POP
  return 0;
}

/* forward the main in the simulation runtime */
extern int _main_SimulationRuntime(int argc, char**argv, DATA *data);

#include "MoonLanding_12jac.h"
#include "MoonLanding_13opt.h"
extern void MoonLanding_callExternalObjectConstructors(DATA *data);
extern void MoonLanding_callExternalObjectDestructors(DATA *_data);
extern void MoonLanding_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
extern void MoonLanding_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
extern void MoonLanding_initialMixedSystem(int nMixedSystems, MIXED_SYSTEM_DATA *data);
extern void MoonLanding_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
extern int MoonLanding_functionAlgebraics(DATA *data);
extern int MoonLanding_function_storeDelayed(DATA *data);
extern int MoonLanding_updateBoundVariableAttributes(DATA *data);
extern int MoonLanding_functionInitialEquations(DATA *data);
extern int MoonLanding_functionRemovedInitialEquations(DATA *data);
extern int MoonLanding_updateBoundParameters(DATA *data);
extern int MoonLanding_checkForAsserts(DATA *data);
extern int MoonLanding_function_ZeroCrossingsEquations(DATA *data);
extern int MoonLanding_function_ZeroCrossings(DATA *data, double* gout);
extern int MoonLanding_function_updateRelations(DATA *data, int evalZeroCross);
extern int MoonLanding_checkForDiscreteChanges(DATA *data);
extern const char* MoonLanding_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* MoonLanding_relationDescription(int i);
extern void MoonLanding_function_initSample(DATA *data);
extern int MoonLanding_initialAnalyticJacobianG(void* data);
extern int MoonLanding_initialAnalyticJacobianA(void* data);
extern int MoonLanding_initialAnalyticJacobianB(void* data);
extern int MoonLanding_initialAnalyticJacobianC(void* data);
extern int MoonLanding_initialAnalyticJacobianD(void* data);
extern int MoonLanding_functionJacG_column(void* data);
extern int MoonLanding_functionJacA_column(void* data);
extern int MoonLanding_functionJacB_column(void* data);
extern int MoonLanding_functionJacC_column(void* data);
extern int MoonLanding_functionJacD_column(void* data);
extern const char* MoonLanding_linear_model_frame(void);
extern int MoonLanding_mayer(DATA* data, modelica_real** res, short *);
extern int MoonLanding_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int MoonLanding_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int MoonLanding_setInputData(DATA *data);
extern int MoonLanding_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);

struct OpenModelicaGeneratedFunctionCallbacks MoonLanding_callback = {
   (int (*)(DATA *, void *)) MoonLanding_performSimulation,
   (int (*)(DATA *, void *)) MoonLanding_performQSSSimulation,
   MoonLanding_callExternalObjectConstructors,
   MoonLanding_callExternalObjectDestructors,
   MoonLanding_initialNonLinearSystem,
   MoonLanding_initialLinearSystem,
   MoonLanding_initialMixedSystem,
   MoonLanding_initializeStateSets,
   MoonLanding_functionODE,
   MoonLanding_functionAlgebraics,
   MoonLanding_functionDAE,
   MoonLanding_input_function,
   MoonLanding_input_function_init,
   MoonLanding_output_function,
   MoonLanding_function_storeDelayed,
   MoonLanding_updateBoundVariableAttributes,
   1 /* useSymbolicInitialization */,
   0 /* useHomotopy */,
   MoonLanding_functionInitialEquations,
   MoonLanding_functionRemovedInitialEquations,
   MoonLanding_updateBoundParameters,
   MoonLanding_checkForAsserts,
   MoonLanding_function_ZeroCrossingsEquations,
   MoonLanding_function_ZeroCrossings,
   MoonLanding_function_updateRelations,
   MoonLanding_checkForDiscreteChanges,
   MoonLanding_zeroCrossingDescription,
   MoonLanding_relationDescription,
   MoonLanding_function_initSample,
   MoonLanding_INDEX_JAC_A,
   MoonLanding_INDEX_JAC_B,
   MoonLanding_INDEX_JAC_C,
   MoonLanding_INDEX_JAC_D,
   MoonLanding_initialAnalyticJacobianA,
   MoonLanding_initialAnalyticJacobianB,
   MoonLanding_initialAnalyticJacobianC,
   MoonLanding_initialAnalyticJacobianD,
   MoonLanding_functionJacA_column,
   MoonLanding_functionJacB_column,
   MoonLanding_functionJacC_column,
   MoonLanding_functionJacD_column,
   MoonLanding_linear_model_frame,
   MoonLanding_mayer,
   MoonLanding_lagrange,
   MoonLanding_pickUpBoundsForInputsInOptimization,
   MoonLanding_setInputData,
   MoonLanding_getTimeGrid

};

void MoonLanding_setupDataStruc(DATA *data)
{
  assertStreamPrint(threadData,0!=data, "Error while initialize Data");
  data->callback = &MoonLanding_callback;
  data->modelData.modelName = "MoonLanding";
  data->modelData.modelFilePrefix = "MoonLanding";
  data->modelData.resultFileName = NULL;
  data->modelData.modelDir = "/home/enrico/Dropbox/teaching/2017/verifica-validazione-sistemi/modelica/examples/rocket/v4-feedback-ctr-only-accelerometer";
  data->modelData.modelGUID = "{8c4e810f-3df3-4a00-8276-176fa3c9f9e0}";
  #ifdef OPENMODELICA_XML_FROM_FILE_AT_RUNTIME
  data->modelData.initXMLData = NULL;
  data->modelData.modelDataXml.infoXMLData = NULL;
  #else
  data->modelData.initXMLData =
  #include "MoonLanding_init.c"
  ;
  data->modelData.modelDataXml.infoXMLData =
  #include "MoonLanding_info.c"
  ;
  #endif
  
  data->modelData.nStates = 5;
  data->modelData.nVariablesReal = 2*5+4+2+0 + 0;
  data->modelData.nDiscreteReal = 2;
  data->modelData.nVariablesInteger = 0;
  data->modelData.nVariablesBoolean = 1;
  data->modelData.nVariablesString = 0;
  data->modelData.nParametersReal = 11;
  data->modelData.nParametersInteger = 0;
  data->modelData.nParametersBoolean = 0;
  data->modelData.nParametersString = 2;
  data->modelData.nInputVars = 0;
  data->modelData.nOutputVars = 0;
  
  data->modelData.nAliasReal = 4;
  data->modelData.nAliasInteger = 0;
  data->modelData.nAliasBoolean = 0;
  data->modelData.nAliasString = 0;
  
  data->modelData.nZeroCrossings = 0;
  data->modelData.nSamples = 1;
  data->modelData.nRelations = 0;
  data->modelData.nMathEvents = 0;
  data->modelData.nExtObjs = 0;
  setupModelInfoFunctions(1);
  data->modelData.modelDataXml.fileName = "MoonLanding_info.json";
  data->modelData.modelDataXml.modelInfoXmlLength = 0;
  data->modelData.modelDataXml.nFunctions = 1;
  data->modelData.modelDataXml.nProfileBlocks = 0;
  data->modelData.modelDataXml.nEquations = 32;
  data->modelData.nMixedSystems = 0;
  data->modelData.nLinearSystems = 0;
  data->modelData.nNonLinearSystems = 0;
  data->modelData.nStateSets = 0;
  data->modelData.nJacobians = 4;
  data->modelData.nOptimizeConstraints = 0;
  data->modelData.nOptimizeFinalConstraints = 0;
  
  data->modelData.nDelayExpressions = 0;
  
}

#ifdef __cplusplus
}
#endif

static int rml_execution_failed()
{
  fflush(NULL);
  fprintf(stderr, "Execution failed!\n");
  fflush(NULL);
  return 1;
}

#if defined(threadData)
#undef threadData
#endif
/* call the simulation runtime main from our main! */
int main(int argc, char**argv)
{
  int res;
  DATA simulation_data;
  MMC_INIT();omc_alloc_interface.init();
  {
    MMC_TRY_TOP()
  
    MMC_TRY_STACK()
  
    MoonLanding_setupDataStruc(&simulation_data);
    simulation_data.threadData = threadData;
    res = _main_SimulationRuntime(argc, argv, &simulation_data);
    
    MMC_ELSE()
    rml_execution_failed();
    fprintf(stderr, "Stack overflow detected and was not caught.\nSend us a bug report at https://trac.openmodelica.org/OpenModelica/newticket\n    Include the following trace:\n");
    printStacktraceMessages();
    fflush(NULL);
    return 1;
    MMC_CATCH_STACK()
    
    MMC_CATCH_TOP(return rml_execution_failed());
  }

  fflush(NULL);
  EXIT(res);
  return res;
}

