within HeatExchanger.CounterCurrentHeatExchangerEquations;
model CounterCurrentHeatExchangerEquations_N_320
	extends CounterCurrentHeatExchangerEquations_N_10(N=320);
end CounterCurrentHeatExchangerEquations_N_320;