within HeatExchanger.CounterCurrentHeatExchangerEquations;
model CounterCurrentHeatExchangerEquations_N_20
	extends CounterCurrentHeatExchangerEquations_N_10(N=20);
end CounterCurrentHeatExchangerEquations_N_20;