within BIOMD143;
class Reactions

    input Real elmt_MLT_c;
    input Real elmt_NADPH_c;
    input Real elmt_Ko;
    input Real elmt_MLTH_c;
    input Real elmt_per3_p;
    input Real elmt_coII_p;
    input Real elmt_O2_p;
    input Real elmt_O2minus_p;
    input Real elmt_coI_p;
    input Real elmt_k16;
    input Real elmt_MLTH_p;
    input Real elmt_k15;
    input Real elmt_k14;
    input Real elmt_k13;
    input Real elmt_V;
    input Real elmt_k12;
    input Real elmt_phagosome;
    input Real elmt_MLT_p;
    input Real elmt_k11;
    input Real elmt_k10;
    input Real elmt_kminus13;
    input Real elmt_O2minus_c;
    input Real elmt_k1;
    input Real elmt_kminus1;
    input Real elmt_L;
    input Real elmt_k18;
    input Real elmt_Knadph;
    input Real elmt_k17;
    input Real elmt_k8;
    input Real elmt_k9;
    input Real elmt_k6;
    input Real elmt_k7;
    input Real elmt_NADP_c;
    input Real elmt_k4;
    input Real elmt_k5;
    input Real elmt_k2;
    input Real elmt_O2_c;
    input Real elmt_k3;
    input Real elmt_cytoplasm;
    input Real elmt_H2O2_c;
    input Real elmt_H2O2_p;
    input Real elmt_coIII_p;

    Real elmt_R7(unit = "") "NADPH autooxidation";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_product25 "";
    Real elmt_product24 "";
    Real elmt_reactant22 "";
    Real elmt_reactant23 "";
    Real elmt_R16(unit = "") "Melatonin  diffusion phagosome/cytoplasm";
    Real elmt_reactant47 "";
    Real elmt_product48 "";
    Real elmt_R8(unit = "") "NADP radical-Oxygen reaction";
    Real elmt_reactant26 "";
    Real elmt_reactant27 "";
    Real elmt_product29 "";
    Real elmt_product28 "";
    Real elmt_R17(unit = "") "Melatonin free radical  diffusion phagosome/cytoplasm";
    Real elmt_product50 "";
    Real elmt_reactant49 "";
    Real elmt_R5(unit = "") "H2O2 formation";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_reactant14 "";
    Real elmt_product16 "";
    Real elmt_reactant15 "";
    Real elmt_product17 "";
    Real elmt_R14(unit = "") "Oxygen diffusion- phagosome/cytoplasm";
    Real elmt_product44 "";
    Real elmt_reactant43 "";
    Real elmt_R6(unit = "") "compound III-superoxide reaction";
    Real elmt_reactant18 "";
    Real elmt_reactant19 "";
    Real elmt_product21 "";
    Real elmt_product20 "";
    Real elmt_R15(unit = "") "H2O2 diffusion phagosome/cytoplasm";
    Real elmt_product46 "";
    Real elmt_reactant45 "";
    Real elmt_R3(unit = "") "Melatonin-compound II reaction";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_product10 "";
    Real elmt_reactant7 "";
    Real elmt_R12(unit = "") "NADPH synthesis";
    Real elmt_product40 "";
    Real elmt_R4(unit = "") "compound III formation";
    Real elmt_product13 "";
    Real elmt_reactant11 "";
    Real elmt_reactant12 "";
    Real elmt_R1(unit = "") "Myeloperoxidase reaction";
    Real elmt_reactant1 "";
    Real elmt_reactant0 "";
    Real elmt_product2 "";
    Real elmt_R10(unit = "") "NADP free radical formation";
    Real elmt_product37 "";
    Real elmt_product36 "";
    Real elmt_reactant34 "";
    Real elmt_reactant35 "";
    Real elmt_R13a(unit = "") "Oxygen diffusion";
    Real elmt_product41 "";
    Real elmt_R2(unit = "") "Melatonin-compound I reaction";
    Real elmt_reactant4 "";
    Real elmt_reactant3 "";
    Real elmt_product6 "";
    Real elmt_product5 "";
    Real elmt_R11(unit = "") "NADP dimer formation";
    Real elmt_reactant38 "";
    Real elmt_product39 "";
    Real elmt_R13b(unit = "") "Oxygen diffusion";
    Real elmt_reactant42 "";
    Real elmt_R9(unit = "") "H2O2 formation";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_reactant30 "";
    Real elmt_reactant31 "";
    Real elmt_product33 "";
    Real elmt_product32 "";
    Real elmt_R18(unit = "") "Superoxide  diffusion phagosome/cytoplasm";
    Real elmt_product52 "";
    Real elmt_reactant51 "";
    Real elmt_R19(unit = "") "NADPH oxidase activity";
    Real elmt_reactant53 "";
    Real elmt_product56 "";
    Real elmt_product55 "";
    Real elmt_reactant54 "";


    initial equation
        elmt_reactant42 = 1.0;
        elmt_product33 = 1.0;
        elmt_product32 = 1.0;
        elmt_reactant47 = 1.0;
        elmt_reactant49 = 1.0;
        elmt_reactant43 = 1.0;
        elmt_reactant45 = 1.0;
        elmt_product25 = 1.0;
        elmt_product24 = 1.0;
        elmt_product29 = 1.0;
        elmt_product28 = 1.0;
        elmt_product41 = 1.0;
        elmt_product40 = 1.0;
        elmt_reactant51 = 1.0;
        elmt_reactant53 = 2.0;
        elmt_product44 = 1.0;
        elmt_reactant14 = 2.0;
        elmt_reactant15 = 2.0;
        elmt_reactant54 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_product37 = 1.0;
        elmt_product36 = 1.0;
        elmt_product39 = 1.0;
        elmt_product52 = 1.0;
        elmt_product50 = 1.0;
        elmt_product56 = 1.0;
        elmt_product55 = 2.0;
        elmt_product10 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product48 = 1.0;
        elmt_product46 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant1 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_reactant30 = 2.0;
        elmt_reactant3 = 1.0;
        elmt_product6 = 1.0;
        elmt_reactant31 = 2.0;
        elmt_product21 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product20 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_reactant38 = 2.0;
        elmt_product5 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant34 = 1.0;
        elmt_product2 = 1.0;
        elmt_reactant35 = 1.0;
        elmt_product16 = 1.0;
        elmt_product13 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_R7 = (elmt_cytoplasm * elmt_k7 * elmt_NADPH_c * elmt_O2_c);
        elmt_R16 = (elmt_phagosome * ((elmt_k16 * elmt_MLTH_p) - (elmt_k16 * elmt_MLTH_c)));
        elmt_R8 = (elmt_cytoplasm * elmt_k8 * elmt_NADP_c * elmt_O2_c);
        elmt_R17 = (elmt_phagosome * ((elmt_k17 * elmt_MLT_p) - (elmt_k17 * elmt_MLT_c)));
        elmt_R5 = (elmt_phagosome * elmt_k5 * Functions.pow(elmt_O2minus_p, 2.0));
        elmt_R14 = (elmt_phagosome * ((elmt_k14 * elmt_O2_p) - (elmt_k14 * elmt_O2_c)));
        elmt_R6 = (elmt_phagosome * elmt_k6 * elmt_coIII_p * elmt_O2minus_p);
        elmt_R15 = (elmt_phagosome * ((elmt_k15 * elmt_H2O2_p) - (elmt_k15 * elmt_H2O2_c)));
        elmt_R3 = (elmt_phagosome * elmt_k3 * elmt_coII_p * elmt_MLTH_p);
        elmt_R12 = (elmt_cytoplasm * elmt_k12);
        elmt_R4 = (elmt_phagosome * elmt_k4 * elmt_per3_p * elmt_O2minus_p);
        elmt_R1 = (elmt_phagosome * ((elmt_k1 * elmt_H2O2_p * elmt_per3_p) - (elmt_kminus1 * elmt_coI_p)));
        elmt_R10 = (elmt_cytoplasm * elmt_k10 * elmt_MLT_c * elmt_NADPH_c);
        elmt_R13a = (elmt_cytoplasm * elmt_k13);
        elmt_R2 = (elmt_phagosome * elmt_k2 * elmt_coI_p * elmt_MLTH_p);
        elmt_R11 = (elmt_cytoplasm * elmt_k11 * Functions.pow(elmt_NADP_c, 2.0));
        elmt_R13b = (elmt_cytoplasm * elmt_kminus13 * elmt_O2_c);
        elmt_R9 = (elmt_cytoplasm * elmt_k9 * Functions.pow(elmt_O2minus_c, 2.0));
        elmt_R18 = (elmt_phagosome * ((elmt_k18 * elmt_O2minus_p) - (elmt_k18 * elmt_O2minus_c)));
        elmt_R19 = (elmt_phagosome * ((((elmt_V * elmt_NADPH_c) / elmt_Knadph) * (1.0 + (elmt_NADPH_c / elmt_Knadph)) * elmt_O2_p) / ((elmt_L + Functions.pow((1.0 + (elmt_NADPH_c / elmt_Knadph)), 2.0)) * (elmt_Ko + elmt_O2_p))));
        der(elmt_reactant42) = 0;
        der(elmt_product33) = 0;
        der(elmt_product32) = 0;
        der(elmt_reactant47) = 0;
        der(elmt_reactant49) = 0;
        der(elmt_reactant43) = 0;
        der(elmt_reactant45) = 0;
        der(elmt_product25) = 0;
        der(elmt_product24) = 0;
        der(elmt_product29) = 0;
        der(elmt_product28) = 0;
        der(elmt_product41) = 0;
        der(elmt_product40) = 0;
        der(elmt_reactant51) = 0;
        der(elmt_reactant53) = 0;
        der(elmt_product44) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant54) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_product37) = 0;
        der(elmt_product36) = 0;
        der(elmt_product39) = 0;
        der(elmt_product52) = 0;
        der(elmt_product50) = 0;
        der(elmt_product56) = 0;
        der(elmt_product55) = 0;
        der(elmt_product10) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product48) = 0;
        der(elmt_product46) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant1) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_reactant30) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_product6) = 0;
        der(elmt_reactant31) = 0;
        der(elmt_product21) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product20) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_reactant38) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant34) = 0;
        der(elmt_product2) = 0;
        der(elmt_reactant35) = 0;
        der(elmt_product16) = 0;
        der(elmt_product13) = 0;
        der(elmt_product17) = 0;

end Reactions;
