within BIOMD423;
class Reactions

    input Real elmt_k1f;
    input Real elmt_k1e;
    input Real elmt_k1d;
    input Real elmt_k1c;
    input Real elmt_k1b;
    input Real elmt_k1a;
    input Real elmt_km23;
    input Real elmt_IRiP;
    input Real elmt_k1g;
    input Real elmt_km2;
    input Real elmt_X;
    input Real elmt_k1r;
    input Real elmt_IRS;
    input Real elmt_IRins;
    input Real elmt_km3;
    input Real elmt_IRi;
    input Real elmt_IR;
    input Real elmt_k3;
    input Real elmt_k1aBasic;
    input Real elmt_IRp;
    input Real elmt_IRSiP;
    input Real elmt_ins;
    input Real elmt_k22;
    input Real elmt_k21;
    input Real elmt_Xp;

    Real elmt_v1c(unit = "") "v1c";
    Real elmt_reactant4 "";
    Real elmt_product5 "";
    Real elmt_v1b(unit = "") "v1b";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_v1r(unit = "") "v1r";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_v1a(unit = "") "v1a";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_v3(unit = "") "v3";
    Real elmt_reactant18 "";
    Real elmt_product19 "";
    Real elmt_v2(unit = "") "v2";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_v1g(unit = "") "v1g";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_vm3(unit = "") "vm3";
    Real elmt_reactant20 "";
    Real elmt_product21 "";
    Real elmt_vm2(unit = "") "vm2";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_v1e(unit = "") "v1e";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_v1d(unit = "") "v1d";
    Real elmt_product7 "";
    Real elmt_reactant6 "";


    initial equation
        elmt_reactant2 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant20 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product11 = 1.0;
        elmt_product21 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_product15 = 1.0;
        elmt_product13 = 1.0;
        elmt_product19 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_v1c = (elmt_k1c * elmt_IRins);
        elmt_v1b = (elmt_k1b * elmt_IRins);
        elmt_v1r = (elmt_k1r * elmt_IRi);
        elmt_v1a = ((elmt_k1a * elmt_ins * elmt_IR) + (elmt_k1aBasic * elmt_IR));
        elmt_v3 = (elmt_k3 * elmt_X * elmt_IRSiP);
        elmt_v2 = ((elmt_k21 * elmt_IRS * (elmt_IRp + (elmt_k22 * elmt_IRiP))) / (1.0 + (elmt_km23 * elmt_Xp)));
        elmt_v1g = (elmt_k1g * elmt_IRp);
        elmt_vm3 = (elmt_km3 * elmt_Xp);
        elmt_vm2 = (elmt_km2 * elmt_IRSiP);
        elmt_v1e = (elmt_IRiP * (elmt_k1e + ((elmt_k1f * elmt_Xp) / (1.0 + elmt_Xp))));
        elmt_v1d = (elmt_k1d * elmt_IRp);
        der(elmt_reactant2) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant20) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product11) = 0;
        der(elmt_product21) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_product15) = 0;
        der(elmt_product13) = 0;
        der(elmt_product19) = 0;
        der(elmt_product17) = 0;

end Reactions;
