within BIOMD379;
class Parameters

    input Real elmt_G_p;
    input Real elmt_I_po;
    input Real elmt_Y;
    input Real elmt_Q_sto2;
    input Real elmt_X;
    input Real elmt_Q_sto1;
    input Real elmt_I_d;
    input Real elmt_G_t;
    input Real elmt_Q_gut;
    input Real elmt_I_p;

    Real elmt_U_ii(unit = "") "U_ii";
    Real elmt_k_empt(unit = "") "k_empt";
    Real elmt_Q_sto(unit = "") "Q_sto";
    Real elmt_S_b_minus(unit = "") "S_b_minus";
    Real elmt_f(unit = "") "f";
    Real elmt_U_id(unit = "") "U_id";
    Real elmt_d(unit = "") "d";
    Real elmt_b(unit = "") "b";
    Real elmt_k_abs(unit = "") "k_abs";
    Real elmt_HE(unit = "") "HE";
    Real elmt_U(unit = "") "U";
    Real elmt_S(unit = "") "S";
    Real elmt_k_gri(unit = "") "k_gri";
    Real elmt_K(unit = "") "K";
    Real elmt_V_m0(unit = "") "V_m0";
    Real elmt_I(unit = "") "I";
    Real elmt_S_po(unit = "") "S_po";
    Real elmt_k_max(unit = "") "k_max";
    Real elmt_aa(unit = "") "aa";
    Real elmt_m_2(unit = "") "m_2";
    Real elmt_G(unit = "") "G";
    Real elmt_m_1(unit = "") "m_1";
    Real elmt_k_2(unit = "") "k_2";
    Real elmt_E(unit = "") "E";
    Real elmt_k_1(unit = "") "k_1";
    Real elmt_D(unit = "") "D";
    Real elmt_m_6(unit = "") "m_6";
    Real elmt_m_5(unit = "") "m_5";
    Real elmt_k_min(unit = "") "k_min";
    Real elmt_k_e1(unit = "") "k_e1";
    Real elmt_m_4(unit = "") "m_4";
    Real elmt_k_e2(unit = "") "k_e2";
    Real elmt_gamma(unit = "") "gamma";
    Real elmt_m_3(unit = "") "m_3";
    Real elmt_EGP(unit = "") "EGP";
    Real elmt_I_b(unit = "") "I_b";
    Real elmt_K_m0(unit = "") "K_m0";
    Real elmt_G_b(unit = "") "G_b";
    Real elmt_S_b(unit = "") "S_b";
    Real elmt_k_p1(unit = "") "k_p1";
    Real elmt_k_p2(unit = "") "k_p2";
    Real elmt_p_2U(unit = "") "p_2U";
    Real elmt_k_p3(unit = "") "k_p3";
    Real elmt_k_p4(unit = "") "k_p4";
    Real elmt_U_idm(unit = "") "U_idm";
    Real elmt_alpha(unit = "") "alpha";
    Real elmt_beta(unit = "") "beta";
    Real elmt_k_i(unit = "") "k_i";
    Real elmt_part(unit = "") "part";
    Real elmt_HE_b(unit = "") "HE_b";
    Real elmt_cc(unit = "") "cc";
    Real elmt_V_I(unit = "") "V_I";
    Real elmt_V_G(unit = "") "V_G";
    Real elmt_BW(unit = "") "BW";
    Real elmt_V_mmax(unit = "") "V_mmax";
    Real elmt_Ra(unit = "") "Ra";
    Real elmt_V_mX(unit = "") "V_mX";


    initial equation
        elmt_U_ii = 1.0;
        elmt_S_b_minus = (-1.8);
        elmt_f = 0.9;
        elmt_d = 0.01;
        elmt_b = 0.82;
        elmt_k_abs = 0.057;
        elmt_k_gri = 0.0558;
        elmt_K = 2.3;
        elmt_V_m0 = 2.5;
        elmt_k_max = 0.0558;
        elmt_m_2 = 0.484;
        elmt_m_1 = 0.19;
        elmt_k_2 = 0.079;
        elmt_k_1 = 0.065;
        elmt_D = 78000.0;
        elmt_m_6 = 0.6471;
        elmt_m_5 = 0.0304;
        elmt_k_min = 0.008;
        elmt_k_e1 = 5.0E-4;
        elmt_m_4 = 0.194;
        elmt_k_e2 = 339.0;
        elmt_gamma = 0.5;
        elmt_I_b = 25.0;
        elmt_K_m0 = 225.59;
        elmt_G_b = 95.0;
        elmt_S_b = 1.8;
        elmt_k_p1 = 2.7;
        elmt_k_p2 = 0.0021;
        elmt_p_2U = 0.0331;
        elmt_k_p3 = 0.009;
        elmt_k_p4 = 0.0618;
        elmt_alpha = 0.05;
        elmt_beta = 0.11;
        elmt_k_i = 0.0079;
        elmt_part = 0.2;
        elmt_HE_b = 0.6;
        elmt_V_I = 0.05;
        elmt_V_G = 1.88;
        elmt_BW = 78.0;
        elmt_V_mX = 0.047;


    equation
        der(elmt_U_ii) = 0;
        elmt_k_empt = (elmt_k_min + (((elmt_k_max - elmt_k_min) / 2.0) * ((tanh((elmt_aa * (elmt_Q_sto - (elmt_b * elmt_D)))) - tanh((elmt_cc * (elmt_Q_sto - (elmt_d * elmt_D))))) + 2.0)));
        elmt_Q_sto = (elmt_Q_sto1 + elmt_Q_sto2);
        der(elmt_S_b_minus) = 0;
        der(elmt_f) = 0;
        elmt_U_id = elmt_U_idm;
        der(elmt_d) = 0;
        der(elmt_b) = 0;
        der(elmt_k_abs) = 0;
        elmt_HE = (((- elmt_m_5) * elmt_S) + elmt_m_6);
        elmt_U = (elmt_U_ii + elmt_U_id);
        elmt_S = (elmt_gamma * elmt_I_po);
        der(elmt_k_gri) = 0;
        der(elmt_K) = 0;
        der(elmt_V_m0) = 0;
        elmt_I = (elmt_I_p / elmt_V_I);
        elmt_S_po = (elmt_Y + ((elmt_K * (((((elmt_EGP + elmt_Ra) - elmt_E) - elmt_U_ii) - (elmt_k_1 * elmt_G_p)) + (elmt_k_2 * elmt_G_t))) / elmt_V_G) + elmt_S_b);
        der(elmt_k_max) = 0;
        elmt_aa = (((5.0 / 2.0) / (1.0 - elmt_b)) / elmt_D);
        der(elmt_m_2) = 0;
        elmt_G = (elmt_G_p / elmt_V_G);
        der(elmt_m_1) = 0;
        der(elmt_k_2) = 0;
        elmt_E = 0.0;
        der(elmt_k_1) = 0;
        der(elmt_D) = 0;
        der(elmt_m_6) = 0;
        der(elmt_m_5) = 0;
        der(elmt_k_min) = 0;
        der(elmt_k_e1) = 0;
        der(elmt_m_4) = 0;
        der(elmt_k_e2) = 0;
        der(elmt_gamma) = 0;
        elmt_m_3 = ((elmt_HE * elmt_m_1) / (1.0 - elmt_HE));
        elmt_EGP = (((elmt_k_p1 - (elmt_k_p2 * elmt_G_p)) - (elmt_k_p3 * elmt_I_d)) - (elmt_k_p4 * elmt_I_po));
        der(elmt_I_b) = 0;
        der(elmt_K_m0) = 0;
        der(elmt_G_b) = 0;
        der(elmt_S_b) = 0;
        der(elmt_k_p1) = 0;
        der(elmt_k_p2) = 0;
        der(elmt_p_2U) = 0;
        der(elmt_k_p3) = 0;
        der(elmt_k_p4) = 0;
        elmt_U_idm = ((elmt_V_mmax * elmt_G_t) / (elmt_K_m0 + elmt_G_t));
        der(elmt_alpha) = 0;
        der(elmt_beta) = 0;
        der(elmt_k_i) = 0;
        der(elmt_part) = 0;
        der(elmt_HE_b) = 0;
        elmt_cc = (((5.0 / 2.0) / elmt_d) / elmt_D);
        der(elmt_V_I) = 0;
        der(elmt_V_G) = 0;
        der(elmt_BW) = 0;
        elmt_V_mmax = ((1.0 - elmt_part) * (elmt_V_m0 + (elmt_V_mX * elmt_X)));
        elmt_Ra = ((elmt_f * elmt_k_abs * elmt_Q_gut) / elmt_BW);
        der(elmt_V_mX) = 0;

end Parameters;
