/* Simulation code for MoonLanding generated by the OpenModelica Compiler 1.9.2 (r25115). */
#define time data->localData[0]->timeValue

/* States */
/* apollo.altitude */
#define _$Papollo$Paltitude(i) data->localData[i]->realVars[0]
#define $Papollo$Paltitude _$Papollo$Paltitude(0)
#define $P$PRE$Papollo$Paltitude data->simulationInfo.realVarsPre[0]
#define $P$ATTRIBUTE$Papollo$Paltitude data->modelData.realVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$Paltitude $P$ATTRIBUTE$Papollo$Paltitude
#define $Papollo$Paltitude__varInfo data->modelData.realVarsData[0].info
#define $P$PRE$Papollo$Paltitude__varInfo data->modelData.realVarsData[0].info
#define _$P$PRE$Papollo$Paltitude(i) $P$PRE$Papollo$Paltitude


/* apollo.mass */
#define _$Papollo$Pmass(i) data->localData[i]->realVars[1]
#define $Papollo$Pmass _$Papollo$Pmass(0)
#define $P$PRE$Papollo$Pmass data->simulationInfo.realVarsPre[1]
#define $P$ATTRIBUTE$Papollo$Pmass data->modelData.realVarsData[1].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$Pmass $P$ATTRIBUTE$Papollo$Pmass
#define $Papollo$Pmass__varInfo data->modelData.realVarsData[1].info
#define $P$PRE$Papollo$Pmass__varInfo data->modelData.realVarsData[1].info
#define _$P$PRE$Papollo$Pmass(i) $P$PRE$Papollo$Pmass


/* apollo.velocity */
#define _$Papollo$Pvelocity(i) data->localData[i]->realVars[2]
#define $Papollo$Pvelocity _$Papollo$Pvelocity(0)
#define $P$PRE$Papollo$Pvelocity data->simulationInfo.realVarsPre[2]
#define $P$ATTRIBUTE$Papollo$Pvelocity data->modelData.realVarsData[2].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$Pvelocity $P$ATTRIBUTE$Papollo$Pvelocity
#define $Papollo$Pvelocity__varInfo data->modelData.realVarsData[2].info
#define $P$PRE$Papollo$Pvelocity__varInfo data->modelData.realVarsData[2].info
#define _$P$PRE$Papollo$Pvelocity(i) $P$PRE$Papollo$Pvelocity


/* StatesDerivatives */
/* der(apollo.altitude) */
#define _$P$DER$Papollo$Paltitude(i) data->localData[i]->realVars[3]
#define $P$DER$Papollo$Paltitude _$P$DER$Papollo$Paltitude(0)
#define $P$PRE$P$DER$Papollo$Paltitude data->simulationInfo.realVarsPre[3]
#define $P$ATTRIBUTE$P$DER$Papollo$Paltitude data->modelData.realVarsData[3].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Papollo$Paltitude $P$ATTRIBUTE$P$DER$Papollo$Paltitude
#define $P$DER$Papollo$Paltitude__varInfo data->modelData.realVarsData[3].info
#define $P$PRE$P$DER$Papollo$Paltitude__varInfo data->modelData.realVarsData[3].info
#define _$P$PRE$P$DER$Papollo$Paltitude(i) $P$PRE$P$DER$Papollo$Paltitude


/* der(apollo.mass) */
#define _$P$DER$Papollo$Pmass(i) data->localData[i]->realVars[4]
#define $P$DER$Papollo$Pmass _$P$DER$Papollo$Pmass(0)
#define $P$PRE$P$DER$Papollo$Pmass data->simulationInfo.realVarsPre[4]
#define $P$ATTRIBUTE$P$DER$Papollo$Pmass data->modelData.realVarsData[4].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Papollo$Pmass $P$ATTRIBUTE$P$DER$Papollo$Pmass
#define $P$DER$Papollo$Pmass__varInfo data->modelData.realVarsData[4].info
#define $P$PRE$P$DER$Papollo$Pmass__varInfo data->modelData.realVarsData[4].info
#define _$P$PRE$P$DER$Papollo$Pmass(i) $P$PRE$P$DER$Papollo$Pmass


/* der(apollo.velocity) */
#define _$P$DER$Papollo$Pvelocity(i) data->localData[i]->realVars[5]
#define $P$DER$Papollo$Pvelocity _$P$DER$Papollo$Pvelocity(0)
#define $P$PRE$P$DER$Papollo$Pvelocity data->simulationInfo.realVarsPre[5]
#define $P$ATTRIBUTE$P$DER$Papollo$Pvelocity data->modelData.realVarsData[5].attribute
#define $P$ATTRIBUTE$P$PRE$P$DER$Papollo$Pvelocity $P$ATTRIBUTE$P$DER$Papollo$Pvelocity
#define $P$DER$Papollo$Pvelocity__varInfo data->modelData.realVarsData[5].info
#define $P$PRE$P$DER$Papollo$Pvelocity__varInfo data->modelData.realVarsData[5].info
#define _$P$PRE$P$DER$Papollo$Pvelocity(i) $P$PRE$P$DER$Papollo$Pvelocity


/* Non Discrete Real Algebraic Vars */
/* apollo.gravity */
#define _$Papollo$Pgravity(i) data->localData[i]->realVars[6]
#define $Papollo$Pgravity _$Papollo$Pgravity(0)
#define $P$PRE$Papollo$Pgravity data->simulationInfo.realVarsPre[6]
#define $P$ATTRIBUTE$Papollo$Pgravity data->modelData.realVarsData[6].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$Pgravity $P$ATTRIBUTE$Papollo$Pgravity
#define $Papollo$Pgravity__varInfo data->modelData.realVarsData[6].info
#define $P$PRE$Papollo$Pgravity__varInfo data->modelData.realVarsData[6].info
#define _$P$PRE$Papollo$Pgravity(i) $P$PRE$Papollo$Pgravity


/* ctr.acceleration */
#define _$Pctr$Pacceleration(i) data->localData[i]->realVars[7]
#define $Pctr$Pacceleration _$Pctr$Pacceleration(0)
#define $P$PRE$Pctr$Pacceleration data->simulationInfo.realVarsPre[7]
#define $P$ATTRIBUTE$Pctr$Pacceleration data->modelData.realVarsData[7].attribute
#define $P$ATTRIBUTE$P$PRE$Pctr$Pacceleration $P$ATTRIBUTE$Pctr$Pacceleration
#define $Pctr$Pacceleration__varInfo data->modelData.realVarsData[7].info
#define $P$PRE$Pctr$Pacceleration__varInfo data->modelData.realVarsData[7].info
#define _$P$PRE$Pctr$Pacceleration(i) $P$PRE$Pctr$Pacceleration


/* Discrete Real Algebraic Vars */
/* ctr.history */
#define _$Pctr$Phistory(i) data->localData[i]->realVars[8]
#define $Pctr$Phistory _$Pctr$Phistory(0)
#define $P$PRE$Pctr$Phistory data->simulationInfo.realVarsPre[8]
#define $P$ATTRIBUTE$Pctr$Phistory data->modelData.realVarsData[8].attribute
#define $P$ATTRIBUTE$P$PRE$Pctr$Phistory $P$ATTRIBUTE$Pctr$Phistory
#define $Pctr$Phistory__varInfo data->modelData.realVarsData[8].info
#define $P$PRE$Pctr$Phistory__varInfo data->modelData.realVarsData[8].info
#define _$P$PRE$Pctr$Phistory(i) $P$PRE$Pctr$Phistory


/* ctr.thrust */
#define _$Pctr$Pthrust(i) data->localData[i]->realVars[9]
#define $Pctr$Pthrust _$Pctr$Pthrust(0)
#define $P$PRE$Pctr$Pthrust data->simulationInfo.realVarsPre[9]
#define $P$ATTRIBUTE$Pctr$Pthrust data->modelData.realVarsData[9].attribute
#define $P$ATTRIBUTE$P$PRE$Pctr$Pthrust $P$ATTRIBUTE$Pctr$Pthrust
#define $Pctr$Pthrust__varInfo data->modelData.realVarsData[9].info
#define $P$PRE$Pctr$Pthrust__varInfo data->modelData.realVarsData[9].info
#define _$P$PRE$Pctr$Pthrust(i) $P$PRE$Pctr$Pthrust


/* Nonlinear Constraints For Dyn. Optimization */

/* Nonlinear Final Constraints For Dyn. Optimization */

/* Algebraic Parameter */
/* apollo.initial_altitude */
#define $Papollo$Pinitial_altitude data->simulationInfo.realParameter[0]
#define _$Papollo$Pinitial_altitude(i) $Papollo$Pinitial_altitude
#define $P$ATTRIBUTE$Papollo$Pinitial_altitude data->modelData.realParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$Pinitial_altitude $P$ATTRIBUTE$Papollo$Pinitial_altitude
#define $Papollo$Pinitial_altitude__varInfo data->modelData.realParameterData[0].info


/* apollo.initial_velocity */
#define $Papollo$Pinitial_velocity data->simulationInfo.realParameter[1]
#define _$Papollo$Pinitial_velocity(i) $Papollo$Pinitial_velocity
#define $P$ATTRIBUTE$Papollo$Pinitial_velocity data->modelData.realParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$Pinitial_velocity $P$ATTRIBUTE$Papollo$Pinitial_velocity
#define $Papollo$Pinitial_velocity__varInfo data->modelData.realParameterData[1].info


/* apollo.initialmass */
#define $Papollo$Pinitialmass data->simulationInfo.realParameter[2]
#define _$Papollo$Pinitialmass(i) $Papollo$Pinitialmass
#define $P$ATTRIBUTE$Papollo$Pinitialmass data->modelData.realParameterData[2].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$Pinitialmass $P$ATTRIBUTE$Papollo$Pinitialmass
#define $Papollo$Pinitialmass__varInfo data->modelData.realParameterData[2].info


/* apollo.massLossRate */
#define $Papollo$PmassLossRate data->simulationInfo.realParameter[3]
#define _$Papollo$PmassLossRate(i) $Papollo$PmassLossRate
#define $P$ATTRIBUTE$Papollo$PmassLossRate data->modelData.realParameterData[3].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$PmassLossRate $P$ATTRIBUTE$Papollo$PmassLossRate
#define $Papollo$PmassLossRate__varInfo data->modelData.realParameterData[3].info


/* ctr.T */
#define $Pctr$PT data->simulationInfo.realParameter[4]
#define _$Pctr$PT(i) $Pctr$PT
#define $P$ATTRIBUTE$Pctr$PT data->modelData.realParameterData[4].attribute
#define $P$ATTRIBUTE$P$PRE$Pctr$PT $P$ATTRIBUTE$Pctr$PT
#define $Pctr$PT__varInfo data->modelData.realParameterData[4].info


/* force1 */
#define $Pforce1 data->simulationInfo.realParameter[5]
#define _$Pforce1(i) $Pforce1
#define $P$ATTRIBUTE$Pforce1 data->modelData.realParameterData[5].attribute
#define $P$ATTRIBUTE$P$PRE$Pforce1 $P$ATTRIBUTE$Pforce1
#define $Pforce1__varInfo data->modelData.realParameterData[5].info


/* force2 */
#define $Pforce2 data->simulationInfo.realParameter[6]
#define _$Pforce2(i) $Pforce2
#define $P$ATTRIBUTE$Pforce2 data->modelData.realParameterData[6].attribute
#define $P$ATTRIBUTE$P$PRE$Pforce2 $P$ATTRIBUTE$Pforce2
#define $Pforce2__varInfo data->modelData.realParameterData[6].info


/* moon.mass */
#define $Pmoon$Pmass data->simulationInfo.realParameter[7]
#define _$Pmoon$Pmass(i) $Pmoon$Pmass
#define $P$ATTRIBUTE$Pmoon$Pmass data->modelData.realParameterData[7].attribute
#define $P$ATTRIBUTE$P$PRE$Pmoon$Pmass $P$ATTRIBUTE$Pmoon$Pmass
#define $Pmoon$Pmass__varInfo data->modelData.realParameterData[7].info


/* moon.radius */
#define $Pmoon$Pradius data->simulationInfo.realParameter[8]
#define _$Pmoon$Pradius(i) $Pmoon$Pradius
#define $P$ATTRIBUTE$Pmoon$Pradius data->modelData.realParameterData[8].attribute
#define $P$ATTRIBUTE$P$PRE$Pmoon$Pradius $P$ATTRIBUTE$Pmoon$Pradius
#define $Pmoon$Pradius__varInfo data->modelData.realParameterData[8].info


/* thrustDecreaseTime */
#define $PthrustDecreaseTime data->simulationInfo.realParameter[9]
#define _$PthrustDecreaseTime(i) $PthrustDecreaseTime
#define $P$ATTRIBUTE$PthrustDecreaseTime data->modelData.realParameterData[9].attribute
#define $P$ATTRIBUTE$P$PRE$PthrustDecreaseTime $P$ATTRIBUTE$PthrustDecreaseTime
#define $PthrustDecreaseTime__varInfo data->modelData.realParameterData[9].info


/* thrustEndTime */
#define $PthrustEndTime data->simulationInfo.realParameter[10]
#define _$PthrustEndTime(i) $PthrustEndTime
#define $P$ATTRIBUTE$PthrustEndTime data->modelData.realParameterData[10].attribute
#define $P$ATTRIBUTE$P$PRE$PthrustEndTime $P$ATTRIBUTE$PthrustEndTime
#define $PthrustEndTime__varInfo data->modelData.realParameterData[10].info


/* External Objects */

/* Algebraic Integer Vars */

/* Algebraic Integer Parameter */

/* Algebraic Boolean Vars */
/* $whenCondition1 */
#define _$P$whenCondition1(i) data->localData[i]->booleanVars[0]
#define $P$whenCondition1 _$P$whenCondition1(0)
#define $P$PRE$P$whenCondition1 data->simulationInfo.booleanVarsPre[0]
#define $P$ATTRIBUTE$P$whenCondition1 data->modelData.booleanVarsData[0].attribute
#define $P$ATTRIBUTE$P$PRE$P$whenCondition1 $P$ATTRIBUTE$P$whenCondition1
#define $P$whenCondition1__varInfo data->modelData.booleanVarsData[0].info
#define $P$PRE$P$whenCondition1__varInfo data->modelData.booleanVarsData[0].info
#define _$P$PRE$P$whenCondition1(i) $P$PRE$P$whenCondition1


/* Algebraic Boolean Parameters */

/* Algebraic String Variables */

/* Algebraic String Parameter */
/* apollo.name */
#define $Papollo$Pname data->simulationInfo.stringParameter[0]
#define _$Papollo$Pname(i) $Papollo$Pname
#define $P$ATTRIBUTE$Papollo$Pname data->modelData.stringParameterData[0].attribute
#define $P$ATTRIBUTE$P$PRE$Papollo$Pname $P$ATTRIBUTE$Papollo$Pname
#define $Papollo$Pname__varInfo data->modelData.stringParameterData[0].info


/* moon.name */
#define $Pmoon$Pname data->simulationInfo.stringParameter[1]
#define _$Pmoon$Pname(i) $Pmoon$Pname
#define $P$ATTRIBUTE$Pmoon$Pname data->modelData.stringParameterData[1].attribute
#define $P$ATTRIBUTE$P$PRE$Pmoon$Pname $P$ATTRIBUTE$Pmoon$Pname
#define $Pmoon$Pname__varInfo data->modelData.stringParameterData[1].info


/* sample */
#define $P$sample1 data->simulationInfo.samples[0]

#define ECU_autopilot7_index 0

