within BIOMD640;
class Reactions

    input Real elmt_Akt_pS473_dephos_second;
    input Real elmt_IRS_p_phos_by_p70_S6K_pT229_pT389;
    input Real elmt_Akt_pT308_dephos_first;
    input Real elmt_PI3K_variant_phos_by_IR_beta_pY1146;
    input Real elmt_IRS_phos_by_IR_beta_pY1146;
    input Real elmt_TSC1_TSC2_pT1462_dephos;
    input Real elmt_mTORC2_S2481_phos_by_Amino_Acids;
    input Real elmt_PI3K_PDK1;
    input Real elmt_Akt_S473_phos_by_mTORC2_pS2481_second;
    input Real elmt_TSC1_TSC2;
    input Real elmt_TSC1_TSC2_S1387_phos_by_AMPK_pT172;
    input Real elmt_Akt_pS473_dephos_first;
    input Real elmt_TSC1_TSC2_T1462_phos_by_Akt_pT308;
    input Real elmt_PI3K_p_PDK1;
    input Real elmt_p70_S6K;
    input Real elmt_IRS_phos_by_p70_S6K_pT229_pT389;
    input Real elmt_Amino_Acids;
    input Real elmt_PRAS40_T246_phos_by_Akt_pT308_second;
    input Real elmt_mTORC1_S2448_activation_by_Amino_Acids;
    input Real elmt_IRS_p;
    input Real elmt_Akt_pT308;
    input Real elmt_p70_S6K_pT389_dephos_second;
    input Real elmt_TSC1_TSC2_pS1387_dephos;
    input Real elmt_PRAS40_pT246;
    input Real elmt_AMPK_T172_phos;
    input Real elmt_PRAS40_pT246_pS183;
    input Real elmt_IRS;
    input Real elmt_PRAS40_S183_phos_by_mTORC1_pS2448_second;
    input Real elmt_p70_S6K_T389_phos_by_mTORC1_pS2448_first;
    input Real elmt_PI3K_variant;
    input Real elmt_PRAS40_pT246_dephos_first;
    input Real elmt_mTORC1_pS2448;
    input Real elmt_p70_S6K_pT229;
    input Real elmt_p70_S6K_pT229_dephos_first;
    input Real elmt_PRAS40_pS183_dephos_first;
    input Real elmt_p70_S6K_pT389;
    input Real elmt_IRS_pS636;
    input Real elmt_PRAS40_pS183_dephos_second;
    input Real elmt_AMPK_pT172_dephos;
    input Real elmt_p70_S6K_T229_phos_by_PI3K_p_PDK1_first;
    input Real elmt_Akt_S473_phos_by_mTORC2_pS2481_first;
    input Real elmt_Akt_pT308_dephos_second;
    input Real elmt_Akt;
    input Real elmt_Cell;
    input Real elmt_mTORC1_pS2448_dephos_by_TSC1_TSC2;
    input Real elmt_PRAS40_S183_phos_by_mTORC1_pS2448_first;
    input Real elmt_p70_S6K_T389_phos_by_mTORC1_pS2448_second;
    input Real elmt_IR_beta_pY1146_dephos;
    input Real elmt_Insulin;
    input Real elmt_p70_S6K_pT229_pT389;
    input Real elmt_p70_S6K_pT389_dephos_first;
    input Real elmt_PRAS40_T246_phos_by_Akt_pT308_first;
    input Real elmt_Akt_pS473;
    input Real elmt_IR_beta_pY1146;
    input Real elmt_PI3K_PDK1_phos_by_IRS_p;
    input Real elmt_PRAS40_pT246_dephos_second;
    input Real elmt_IR_beta_phos_by_Insulin;
    input Real elmt_mTORC2_S2481_phos_by_PI3K_variant_p;
    input Real elmt_mTORC2_pS2481_dephos;
    input Real elmt_IR_beta_ready;
    input Real elmt_IRS_phos_by_Amino_Acids;
    input Real elmt_mTORC2;
    input Real elmt_mTORC1;
    input Real elmt_IRS_pS636_turnover;
    input Real elmt_AMPK_pT172;
    input Real elmt_PRAS40_pS183;
    input Real elmt_TSC1_TSC2_pS1387;
    input Real elmt_mTORC2_pS2481;
    input Real elmt_Akt_T308_phos_by_PI3K_p_PDK1_second;
    input Real elmt_AMPK;
    input Real elmt_PI3K_variant_p_dephos;
    input Real elmt_TSC1_TSC2_pT1462;
    input Real elmt_Akt_pT308_pS473;
    input Real elmt_p70_S6K_T229_phos_by_PI3K_p_PDK1_second;
    input Real elmt_IR_beta;
    input Real elmt_p70_S6K_pT229_dephos_second;
    input Real elmt_PI3K_variant_p;
    input Real elmt_IR_beta_refractory;
    input Real elmt_PRAS40;
    input Real elmt_PI3K_p_PDK1_dephos;
    input Real elmt_Akt_T308_phos_by_PI3K_p_PDK1_first;
    input Real elmt_AMPK_T172_phos_by_Amino_Acids;

    Real elmt_reaction_27(unit = "") "reaction_27";
    Real elmt_reactant52 "";
    Real elmt_product53 "";
    Real elmt_reaction_28(unit = "") "reaction_28";
    Real elmt_product55 "";
    Real elmt_reactant54 "";
    Real elmt_reaction_25(unit = "") "reaction_25";
    Real elmt_product49 "";
    Real elmt_reactant48 "";
    Real elmt_reaction_26(unit = "") "reaction_26";
    Real elmt_reactant50 "";
    Real elmt_product51 "";
    Real elmt_reaction_29(unit = "") "reaction_29";
    Real elmt_product57 "";
    Real elmt_reactant56 "";
    Real elmt_reaction_20(unit = "") "reaction_20";
    Real elmt_reactant38 "";
    Real elmt_product39 "";
    Real elmt_reaction_23(unit = "") "reaction_23";
    Real elmt_product45 "";
    Real elmt_reactant44 "";
    Real elmt_reaction_24(unit = "") "reaction_24";
    Real elmt_product47 "";
    Real elmt_reactant46 "";
    Real elmt_reaction_21(unit = "") "reaction_21";
    Real elmt_product41 "";
    Real elmt_reactant40 "";
    Real elmt_reaction_22(unit = "") "reaction_22";
    Real elmt_reactant42 "";
    Real elmt_product43 "";
    Real elmt_reaction_3(unit = "") "reaction_3";
    Real elmt_reactant4 "";
    Real elmt_product5 "";
    Real elmt_reaction_4(unit = "") "reaction_4";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_reaction_1(unit = "") "reaction_1";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_reaction_2(unit = "") "reaction_2";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_reaction_16(unit = "") "reaction_16";
    Real elmt_reactant30 "";
    Real elmt_product31 "";
    Real elmt_reaction_17(unit = "") "reaction_17";
    Real elmt_product33 "";
    Real elmt_reactant32 "";
    Real elmt_reaction_9(unit = "") "reaction_9";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_reaction_14(unit = "") "reaction_14";
    Real elmt_product27 "";
    Real elmt_reactant26 "";
    Real elmt_reaction_15(unit = "") "reaction_15";
    Real elmt_reactant28 "";
    Real elmt_product29 "";
    Real elmt_reaction_7(unit = "") "reaction_7";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_reaction_8(unit = "") "reaction_8";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_reaction_5(unit = "") "reaction_5";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_reaction_18(unit = "") "reaction_18";
    Real elmt_product35 "";
    Real elmt_reactant34 "";
    Real elmt_reaction_6(unit = "") "reaction_6";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_reaction_19(unit = "") "reaction_19";
    Real elmt_reactant36 "";
    Real elmt_product37 "";
    Real elmt_reaction_12(unit = "") "reaction_12";
    Real elmt_product23 "";
    Real elmt_reactant22 "";
    Real elmt_reaction_13(unit = "") "reaction_13";
    Real elmt_product25 "";
    Real elmt_reactant24 "";
    Real elmt_reaction_10(unit = "") "reaction_10";
    Real elmt_reactant18 "";
    Real elmt_product19 "";
    Real elmt_reaction_11(unit = "") "reaction_11";
    Real elmt_reactant20 "";
    Real elmt_product21 "";
    Real elmt_reaction_47(unit = "") "reaction_47";
    Real elmt_product93 "";
    Real elmt_reactant92 "";
    Real elmt_reaction_48(unit = "") "reaction_48";
    Real elmt_reactant94 "";
    Real elmt_product95 "";
    Real elmt_reaction_41(unit = "") "reaction_41";
    Real elmt_reactant80 "";
    Real elmt_product81 "";
    Real elmt_reaction_42(unit = "") "reaction_42";
    Real elmt_product83 "";
    Real elmt_reactant82 "";
    Real elmt_reaction_40(unit = "") "reaction_40";
    Real elmt_product79 "";
    Real elmt_reactant78 "";
    Real elmt_reaction_45(unit = "") "reaction_45";
    Real elmt_product89 "";
    Real elmt_reactant88 "";
    Real elmt_reaction_46(unit = "") "reaction_46";
    Real elmt_reactant90 "";
    Real elmt_product91 "";
    Real elmt_reaction_43(unit = "") "reaction_43";
    Real elmt_product85 "";
    Real elmt_reactant84 "";
    Real elmt_reaction_44(unit = "") "reaction_44";
    Real elmt_reactant86 "";
    Real elmt_product87 "";
    Real elmt_reaction_38(unit = "") "reaction_38";
    Real elmt_reactant74 "";
    Real elmt_product75 "";
    Real elmt_reaction_39(unit = "") "reaction_39";
    Real elmt_product77 "";
    Real elmt_reactant76 "";
    Real elmt_reaction_36(unit = "") "reaction_36";
    Real elmt_product71 "";
    Real elmt_reactant70 "";
    Real elmt_reaction_37(unit = "") "reaction_37";
    Real elmt_reactant72 "";
    Real elmt_product73 "";
    Real elmt_reaction_30(unit = "") "reaction_30";
    Real elmt_reactant58 "";
    Real elmt_product59 "";
    Real elmt_reaction_31(unit = "") "reaction_31";
    Real elmt_product61 "";
    Real elmt_reactant60 "";
    Real elmt_reaction_34(unit = "") "reaction_34";
    Real elmt_product67 "";
    Real elmt_reactant66 "";
    Real elmt_reaction_35(unit = "") "reaction_35";
    Real elmt_product69 "";
    Real elmt_reactant68 "";
    Real elmt_reaction_32(unit = "") "reaction_32";
    Real elmt_product63 "";
    Real elmt_reactant62 "";
    Real elmt_reaction_33(unit = "") "reaction_33";
    Real elmt_reactant64 "";
    Real elmt_product65 "";


    initial equation
        elmt_reactant40 = 1.0;
        elmt_reactant84 = 1.0;
        elmt_product73 = 1.0;
        elmt_reactant42 = 1.0;
        elmt_reactant86 = 1.0;
        elmt_product71 = 1.0;
        elmt_product33 = 1.0;
        elmt_reactant80 = 1.0;
        elmt_product77 = 1.0;
        elmt_product31 = 1.0;
        elmt_reactant82 = 1.0;
        elmt_product75 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_reactant44 = 1.0;
        elmt_reactant88 = 1.0;
        elmt_reactant46 = 1.0;
        elmt_product27 = 1.0;
        elmt_product25 = 1.0;
        elmt_product69 = 1.0;
        elmt_product29 = 1.0;
        elmt_reactant50 = 1.0;
        elmt_product41 = 1.0;
        elmt_reactant94 = 1.0;
        elmt_product85 = 1.0;
        elmt_reactant52 = 1.0;
        elmt_product83 = 1.0;
        elmt_product45 = 1.0;
        elmt_product89 = 1.0;
        elmt_reactant90 = 1.0;
        elmt_product43 = 1.0;
        elmt_reactant92 = 1.0;
        elmt_product87 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant58 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant54 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_product81 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_product37 = 1.0;
        elmt_product35 = 1.0;
        elmt_product79 = 1.0;
        elmt_product39 = 1.0;
        elmt_product51 = 1.0;
        elmt_product95 = 1.0;
        elmt_reactant62 = 1.0;
        elmt_reactant20 = 1.0;
        elmt_product93 = 1.0;
        elmt_reactant64 = 1.0;
        elmt_product55 = 1.0;
        elmt_product11 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant60 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_product91 = 1.0;
        elmt_reactant66 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant68 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_product49 = 1.0;
        elmt_product47 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant72 = 1.0;
        elmt_product63 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant30 = 1.0;
        elmt_reactant74 = 1.0;
        elmt_product61 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product23 = 1.0;
        elmt_product67 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product21 = 1.0;
        elmt_reactant70 = 1.0;
        elmt_product65 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant36 = 1.0;
        elmt_reactant38 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant32 = 1.0;
        elmt_reactant76 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant34 = 1.0;
        elmt_reactant78 = 1.0;
        elmt_product15 = 1.0;
        elmt_product59 = 1.0;
        elmt_product57 = 1.0;
        elmt_product13 = 1.0;
        elmt_product19 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_reaction_27 = (elmt_Cell * elmt_TSC1_TSC2_pS1387_dephos * elmt_TSC1_TSC2_pS1387);
        elmt_reaction_28 = (elmt_Cell * elmt_TSC1_TSC2_pT1462_dephos * elmt_TSC1_TSC2_pT1462);
        elmt_reaction_25 = (elmt_Cell * ((elmt_TSC1_TSC2_S1387_phos_by_AMPK_pT172 * elmt_TSC1_TSC2 * elmt_AMPK_pT172)));
        elmt_reaction_26 = (elmt_Cell * ((elmt_TSC1_TSC2_T1462_phos_by_Akt_pT308 * elmt_TSC1_TSC2 * (elmt_Akt_pT308 + elmt_Akt_pT308_pS473))));
        elmt_reaction_29 = (elmt_Cell * ((elmt_mTORC1_pS2448_dephos_by_TSC1_TSC2 * elmt_mTORC1_pS2448 * (elmt_TSC1_TSC2 + elmt_TSC1_TSC2_pS1387))));
        elmt_reaction_20 = (elmt_Cell * ((elmt_Akt_S473_phos_by_mTORC2_pS2481_second * elmt_Akt_pT308 * elmt_mTORC2_pS2481)));
        elmt_reaction_23 = (elmt_Cell * elmt_Akt_pT308_dephos_second * elmt_Akt_pT308_pS473);
        elmt_reaction_24 = (elmt_Cell * elmt_Akt_pS473_dephos_second * elmt_Akt_pT308_pS473);
        elmt_reaction_21 = (elmt_Cell * elmt_Akt_pT308_dephos_first * elmt_Akt_pT308);
        elmt_reaction_22 = (elmt_Cell * elmt_Akt_pS473_dephos_first * elmt_Akt_pS473);
        elmt_reaction_3 = (elmt_Cell * ((elmt_mTORC2_S2481_phos_by_Amino_Acids * elmt_mTORC2 * elmt_Amino_Acids)));
        elmt_reaction_4 = (elmt_Cell * ((elmt_IR_beta_phos_by_Insulin * elmt_IR_beta * elmt_Insulin)));
        elmt_reaction_1 = (elmt_Cell * ((elmt_IRS_phos_by_Amino_Acids * elmt_IRS * elmt_Amino_Acids)));
        elmt_reaction_2 = (elmt_Cell * ((elmt_AMPK_T172_phos_by_Amino_Acids * elmt_AMPK * elmt_Amino_Acids)));
        elmt_reaction_16 = (elmt_Cell * elmt_AMPK_pT172_dephos * elmt_AMPK_pT172);
        elmt_reaction_17 = (elmt_Cell * ((elmt_Akt_T308_phos_by_PI3K_p_PDK1_first * elmt_Akt * elmt_PI3K_p_PDK1)));
        elmt_reaction_9 = (elmt_Cell * ((elmt_IRS_phos_by_p70_S6K_pT229_pT389 * elmt_IRS * elmt_p70_S6K_pT229_pT389)));
        elmt_reaction_14 = (elmt_Cell * ((elmt_PI3K_variant_phos_by_IR_beta_pY1146 * elmt_PI3K_variant * elmt_IR_beta_pY1146)));
        elmt_reaction_15 = (elmt_Cell * ((elmt_AMPK_T172_phos * elmt_AMPK * elmt_IRS_p)));
        elmt_reaction_7 = (elmt_Cell * ((elmt_IRS_phos_by_IR_beta_pY1146 * elmt_IRS * elmt_IR_beta_pY1146)));
        elmt_reaction_8 = (elmt_Cell * ((elmt_IRS_p_phos_by_p70_S6K_pT229_pT389 * elmt_IRS_p * elmt_p70_S6K_pT229_pT389)));
        elmt_reaction_5 = (elmt_Cell * elmt_IR_beta_pY1146_dephos * elmt_IR_beta_pY1146);
        elmt_reaction_18 = (elmt_Cell * ((elmt_Akt_S473_phos_by_mTORC2_pS2481_first * elmt_Akt * elmt_mTORC2_pS2481)));
        elmt_reaction_6 = (elmt_Cell * elmt_IR_beta_ready * elmt_IR_beta_refractory);
        elmt_reaction_19 = (elmt_Cell * ((elmt_Akt_T308_phos_by_PI3K_p_PDK1_second * elmt_Akt_pS473 * elmt_PI3K_p_PDK1)));
        elmt_reaction_12 = (elmt_Cell * ((elmt_PI3K_PDK1_phos_by_IRS_p * elmt_PI3K_PDK1 * elmt_IRS_p)));
        elmt_reaction_13 = (elmt_Cell * elmt_PI3K_variant_p_dephos * elmt_PI3K_variant_p);
        elmt_reaction_10 = (elmt_Cell * elmt_IRS_pS636_turnover * elmt_IRS_pS636);
        elmt_reaction_11 = (elmt_Cell * elmt_PI3K_p_PDK1_dephos * elmt_PI3K_p_PDK1);
        elmt_reaction_47 = (elmt_Cell * elmt_PRAS40_pS183_dephos_second * elmt_PRAS40_pT246_pS183);
        elmt_reaction_48 = (elmt_Cell * elmt_PRAS40_pT246_dephos_second * elmt_PRAS40_pT246_pS183);
        elmt_reaction_41 = (elmt_Cell * ((elmt_PRAS40_S183_phos_by_mTORC1_pS2448_first * elmt_PRAS40 * elmt_mTORC1_pS2448)));
        elmt_reaction_42 = (elmt_Cell * ((elmt_PRAS40_T246_phos_by_Akt_pT308_first * elmt_PRAS40 * (elmt_Akt_pT308 + elmt_Akt_pT308_pS473))));
        elmt_reaction_40 = (elmt_Cell * elmt_p70_S6K_pT389_dephos_second * elmt_p70_S6K_pT229_pT389);
        elmt_reaction_45 = (elmt_Cell * elmt_PRAS40_pS183_dephos_first * elmt_PRAS40_pS183);
        elmt_reaction_46 = (elmt_Cell * elmt_PRAS40_pT246_dephos_first * elmt_PRAS40_pT246);
        elmt_reaction_43 = (elmt_Cell * ((elmt_PRAS40_T246_phos_by_Akt_pT308_second * elmt_PRAS40_pS183 * (elmt_Akt_pT308 + elmt_Akt_pT308_pS473))));
        elmt_reaction_44 = (elmt_Cell * ((elmt_PRAS40_S183_phos_by_mTORC1_pS2448_second * elmt_PRAS40_pT246 * elmt_mTORC1_pS2448)));
        elmt_reaction_38 = (elmt_Cell * elmt_p70_S6K_pT389_dephos_first * elmt_p70_S6K_pT389);
        elmt_reaction_39 = (elmt_Cell * elmt_p70_S6K_pT229_dephos_second * elmt_p70_S6K_pT229_pT389);
        elmt_reaction_36 = (elmt_Cell * ((elmt_p70_S6K_T389_phos_by_mTORC1_pS2448_second * elmt_p70_S6K_pT229 * elmt_mTORC1_pS2448)));
        elmt_reaction_37 = (elmt_Cell * elmt_p70_S6K_pT229_dephos_first * elmt_p70_S6K_pT229);
        elmt_reaction_30 = (elmt_Cell * ((elmt_mTORC1_S2448_activation_by_Amino_Acids * elmt_mTORC1 * elmt_Amino_Acids)));
        elmt_reaction_31 = (elmt_Cell * ((elmt_mTORC2_S2481_phos_by_PI3K_variant_p * elmt_mTORC2 * elmt_PI3K_variant_p)));
        elmt_reaction_34 = (elmt_Cell * ((elmt_p70_S6K_T389_phos_by_mTORC1_pS2448_first * elmt_p70_S6K * elmt_mTORC1_pS2448)));
        elmt_reaction_35 = (elmt_Cell * ((elmt_p70_S6K_T229_phos_by_PI3K_p_PDK1_second * elmt_p70_S6K_pT389 * elmt_PI3K_p_PDK1)));
        elmt_reaction_32 = (elmt_Cell * elmt_mTORC2_pS2481_dephos * elmt_mTORC2_pS2481);
        elmt_reaction_33 = (elmt_Cell * ((elmt_p70_S6K_T229_phos_by_PI3K_p_PDK1_first * elmt_p70_S6K * elmt_PI3K_p_PDK1)));
        der(elmt_reactant40) = 0;
        der(elmt_reactant84) = 0;
        der(elmt_product73) = 0;
        der(elmt_reactant42) = 0;
        der(elmt_reactant86) = 0;
        der(elmt_product71) = 0;
        der(elmt_product33) = 0;
        der(elmt_reactant80) = 0;
        der(elmt_product77) = 0;
        der(elmt_product31) = 0;
        der(elmt_reactant82) = 0;
        der(elmt_product75) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_reactant44) = 0;
        der(elmt_reactant88) = 0;
        der(elmt_reactant46) = 0;
        der(elmt_product27) = 0;
        der(elmt_product25) = 0;
        der(elmt_product69) = 0;
        der(elmt_product29) = 0;
        der(elmt_reactant50) = 0;
        der(elmt_product41) = 0;
        der(elmt_reactant94) = 0;
        der(elmt_product85) = 0;
        der(elmt_reactant52) = 0;
        der(elmt_product83) = 0;
        der(elmt_product45) = 0;
        der(elmt_product89) = 0;
        der(elmt_reactant90) = 0;
        der(elmt_product43) = 0;
        der(elmt_reactant92) = 0;
        der(elmt_product87) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant58) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant54) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_product81) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_product37) = 0;
        der(elmt_product35) = 0;
        der(elmt_product79) = 0;
        der(elmt_product39) = 0;
        der(elmt_product51) = 0;
        der(elmt_product95) = 0;
        der(elmt_reactant62) = 0;
        der(elmt_reactant20) = 0;
        der(elmt_product93) = 0;
        der(elmt_reactant64) = 0;
        der(elmt_product55) = 0;
        der(elmt_product11) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant60) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_product91) = 0;
        der(elmt_reactant66) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant68) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_product49) = 0;
        der(elmt_product47) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant72) = 0;
        der(elmt_product63) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant30) = 0;
        der(elmt_reactant74) = 0;
        der(elmt_product61) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product23) = 0;
        der(elmt_product67) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product21) = 0;
        der(elmt_reactant70) = 0;
        der(elmt_product65) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant36) = 0;
        der(elmt_reactant38) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_reactant76) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant34) = 0;
        der(elmt_reactant78) = 0;
        der(elmt_product15) = 0;
        der(elmt_product59) = 0;
        der(elmt_product57) = 0;
        der(elmt_product13) = 0;
        der(elmt_product19) = 0;
        der(elmt_product17) = 0;

end Reactions;
