
model BIOMD560 "Hui2014 - Age-related changes in articular cartilage"

    function pow
        input  Real x;
        input  Real power;
        output Real y;
        algorithm
            y := x^power;
    end pow;
    
    function piecewise
        input Real x;
        input Boolean condition;
        input Real y;
        output Real z;
        algorithm
            z := if condition then x else y;
    end piecewise;



    parameter Real kactCasp = 1e-07;
    parameter Real kactCaspBecI = 8.3e-07;
    parameter Real kactCaspp38 = 8e-07;
    parameter Real kactIntegrin = 4e-07;
    parameter Real kactLys = 1e-08;
    parameter Real kactMMP13 = 0.0001;
    parameter Real kactMMP2 = 1e-07;
    parameter Real kactNFkB = 0.0001;
    parameter Real kactRAGE = 0.001;
    parameter Real kactRunx2 = 0.001;
    parameter Real kactSox9 = 5e-06;
    parameter Real kactTgfbIntegrin = 0.001;
    parameter Real kactTgfbMMP2 = 1e-07;
    parameter Real kbinAggrecanCollagen2 = 0.0001;
    parameter Real kbinAlk1Alk5 = 5e-05;
    parameter Real kbinBaxBcl2 = 1.67;
    parameter Real kbinBaxToBcl2Bec = 0.000167;
    parameter Real kbinBcl2Beclin = 7.5e-05;
    parameter Real kbinBecToBaxBcl2 = 1.67e-05;
    parameter Real kbinSmad1Smad4 = 5e-05;
    parameter Real kbinSmad2Smad4 = 0.0001;
    parameter Real kbinSmad7Alk1 = 0.5;
    parameter Real kbinSmad7Alk5 = 2e-05;
    parameter Real kbinTgfbAlk1 = 2e-05;
    parameter Real kbinTgfbAlk5 = 3e-05;
    parameter Real kdamLys = 5e-06;
    parameter Real kdamNatP = 8e-06;
    parameter Real kdedimerAlk5 = 0.001;
    parameter Real kdegAcanmRNA = 9e-06;
    parameter Real kdegADAMTS5 = 5e-05;
    parameter Real kdegAggrecan = 1e-09;
    parameter Real kdegAlk1 = 1.2e-08;
    parameter Real kdegAlk5 = 4e-07;
    parameter Real kdegBcl2 = 0.000167;
    parameter Real kdegBcl2Casp = 0.00167;
    parameter Real kdegBcl2ROS = 0.00167;
    parameter Real kdegCol2mRNA = 1.07e-05;
    parameter Real kdegCollagen = 1e-08;
    parameter Real kdegDamP = 4e-05;
    parameter Real kdegIkB = 1e-06;
    parameter Real kdegIL1 = 0.005;
    parameter Real kdegMMP13 = 6.4e-06;
    parameter Real kdegMMP2 = 6.4e-06;
    parameter Real kdegSmad7 = 0.005;
    parameter Real kdegSmad7Alk1 = 5e-06;
    parameter Real kdegSmad7Alk5 = 1e-05;
    parameter Real kdegSOD = 0.001;
    parameter Real kdegSox9 = 4.8e-05;
    parameter Real kdegSox9mRNA = 0.0001;
    parameter Real kdegTgfb = 0.00578;
    parameter Real kdephosNFkB = 0.01;
    parameter Real kdephosp38 = 0.01;
    parameter Real kdephosSmad1 = 0.0005;
    parameter Real kdephosSmad1Smad7 = 0.0006;
    parameter Real kdephosSmad2 = 0.006;
    parameter Real kdimerAlk5 = 0.0002;
    parameter Real kgenROS = 0.0005;
    parameter Real kgenROSbyDamP = 0.0001;
    parameter Real kgenROSbyp38 = 0.0001;
    parameter Real kgenROSbyRAGE = 0.0004;
    parameter Real kinactBec = 5e-10;
    parameter Real kinactBecCasp = 1e-08;
    parameter Real kinactCasp = 0.0003;
    parameter Real kinactCaspBcl2 = 0.0003;
    parameter Real kinactIntegrin = 0.0005;
    parameter Real kinactNFkB = 0.1;
    parameter Real kinactRAGE = 0.001;
    parameter Real kinactRunx2 = 0.0005;
    parameter Real kinactSox9 = 0.0015;
    parameter Real kinactTgfb = 0.05;
    parameter Real kinhibLys = 7e-06;
    parameter Real kphosNFkB = 0.001;
    parameter Real kphosp38 = 1e-07;
    parameter Real kphosp38ROS = 0.0001;
    parameter Real kphosSmad1 = 2e-05;
    parameter Real kphosSmad2 = 4e-05;
    parameter Real kprodAGE = 1e-06;
    parameter Real krelAlk1Alk5 = 0.01;
    parameter Real krelBaxBcl2 = 0.00167;
    parameter Real krelBaxBcl2Bec = 0.00167;
    parameter Real krelBcl2Beclin = 0.0005;
    parameter Real krelBecBaxBcl2 = 0.0167;
    parameter Real krelSmad1Smad4 = 0.0167;
    parameter Real krelSmad2Smad4 = 0.0167;
    parameter Real krelSmad7Alk1 = 0.001;
    parameter Real krelSmad7Alk5 = 1e-06;
    parameter Real krelTgfbAlk1 = 1e-06;
    parameter Real krelTgfbAlk5 = 1e-06;
    parameter Real kremROS = 0.000383;
    parameter Real kremROSbySOD = 0.0001;
    parameter Real ksynAcanmRNA = 0.0;
    parameter Real ksynAcanmRNASox9A = 4.6e-06;
    parameter Real ksynADAMTS5 = 0.0005;
    parameter Real ksynAggrecan = 1e-06;
    parameter Real ksynAlk1 = 5e-06;
    parameter Real ksynAlk5 = 5e-06;
    parameter Real ksynBcl2 = 0.002;
    parameter Real ksynCol2 = 1e-07;
    parameter Real ksynCol2mRNA = 0.0;
    parameter Real ksynCol2mRNASmad = 1e-06;
    parameter Real ksynCol2mRNASox9A = 1e-06;
    parameter Real ksynIkB = 0.001;
    parameter Real ksynIL1 = 0.005;
    parameter Real ksynMMP13 = 3.2e-05;
    parameter Real ksynMMP13Runx2 = 1.5e-06;
    parameter Real ksynMMP2 = 5e-06;
    parameter Real ksynNatP = 0.0;
    parameter Real ksynRAGE = 0.0001;
    parameter Real ksynSmad7 = 1e-05;
    parameter Real ksynSOD = 0.002;
    parameter Real ksynSox9 = 0.00048;
    parameter Real ksynSox9mRNA = 1e-05;
    parameter Real ksynSox9mRNASox9A = 5e-06;
    parameter Real cell = 1.0;
    parameter Real nucleus = 1.0;
    parameter Real membrane = 1.0;
    parameter Real ecm = 1.0;



    Real AcanmRNA;
    Real ADAMTS5;
    Real AGEprod;
    Real Alk1;
    Real Alk1_Alk5;
    Real Alk5;
    Real Alk5_dimer;
    Real Bax;
    Real Bax_Bcl2;
    Real Bax_Bcl2_Beclin;
    Real Bax_Bcl2_Beclin_I;
    Real Bcl2;
    Real Bcl2_Beclin;
    Real Bcl2_Beclin_I;
    Real Beclin;
    Real Beclin_I;
    Real Caspase_A;
    Real Caspase_I;
    Real Col2mRNA;
    Real DamP;
    Real IkB;
    Real IkB_NFkB;
    Real IL1;
    Real Lys_A;
    Real Lys_I;
    Real MMP13;
    Real MMP2;
    Real NatP;
    Real NFkB;
    Real NFkB_P;
    Real p38;
    Real p38_P;
    Real proMMP13;
    Real proMMP2;
    Real RAGE;
    Real ROS;
    Real Runx2_A;
    Real Runx2_I;
    Real Smad1;
    Real Smad1_P;
    Real Smad1_P_Smad4;
    Real Smad2;
    Real Smad2_P;
    Real Smad2_P_Smad4;
    Real Smad4;
    Real Smad7;
    Real SOD;
    Real Sox9;
    Real Sox9_A;
    Real Sox9mRNA;
    Real Tgfb_A;
    Real Tgfb_Alk1_Alk5;
    Real Tgfb_Alk1_Alk5_Smad7;
    Real Tgfb_Alk5_dimer;
    Real Tgfb_Alk5_dimer_Smad7;
    Real AggFrag;
    Real Aggrecan;
    Real Aggrecan_Collagen2;
    Real ColFrag;
    Real Collagen2;
    Real Integrin;
    Real Tgfb_I;
    Real Sink;
    Real Source;
    Real IntegrinCount;

initial equation
    AcanmRNA = 0.0;
    ADAMTS5 = 0.0;
    AGEprod = 0.0;
    Alk1 = 500.0;
    Alk1_Alk5 = 0.0;
    Alk5 = 500.0;
    Alk5_dimer = 0.0;
    Bax = 0.0;
    Bax_Bcl2 = 90.0;
    Bax_Bcl2_Beclin = 10.0;
    Bax_Bcl2_Beclin_I = 0.0;
    Bcl2 = 30.0;
    Bcl2_Beclin = 25.0;
    Bcl2_Beclin_I = 0.0;
    Beclin = 75.0;
    Beclin_I = 0.0;
    Caspase_A = 0.0;
    Caspase_I = 100.0;
    Col2mRNA = 0.0;
    DamP = 0.0;
    IkB = 0.0;
    IkB_NFkB = 100.0;
    IL1 = 0.0;
    Lys_A = 40.0;
    Lys_I = 360.0;
    MMP13 = 0.0;
    MMP2 = 0.0;
    NatP = 1500.0;
    NFkB = 0.0;
    NFkB_P = 0.0;
    p38 = 100.0;
    p38_P = 0.0;
    proMMP13 = 0.0;
    proMMP2 = 0.0;
    RAGE = 0.0;
    ROS = 2.0;
    Runx2_A = 0.0;
    Runx2_I = 100.0;
    Smad1 = 600.0;
    Smad1_P = 0.0;
    Smad1_P_Smad4 = 0.0;
    Smad2 = 600.0;
    Smad2_P = 0.0;
    Smad2_P_Smad4 = 0.0;
    Smad4 = 600.0;
    Smad7 = 0.0;
    SOD = 2.0;
    Sox9 = 100.0;
    Sox9_A = 0.0;
    Sox9mRNA = 10.0;
    Tgfb_A = 0.0;
    Tgfb_Alk1_Alk5 = 0.0;
    Tgfb_Alk1_Alk5_Smad7 = 0.0;
    Tgfb_Alk5_dimer = 0.0;
    Tgfb_Alk5_dimer_Smad7 = 0.0;
    AggFrag = 0.0;
    Aggrecan = 0.0;
    Aggrecan_Collagen2 = 1000.0;
    ColFrag = 0.0;
    Collagen2 = 0.0;
    Integrin = 0.0;
    Tgfb_I = 200.0;
    Sink = 0.0;
    Source = 1.0;
    IntegrinCount = 0.0;

equation

    der(AcanmRNA) = (ksynAcanmRNASox9A * Sox9_A) + (ksynAggrecan * AcanmRNA) - (kdegAcanmRNA * AcanmRNA) - (ksynAggrecan * AcanmRNA);
    der(ADAMTS5) = (ksynADAMTS5 * IL1) + (kdegAggrecan * Aggrecan_Collagen2 * ADAMTS5) - (kdegADAMTS5 * ADAMTS5) - (kdegAggrecan * Aggrecan_Collagen2 * ADAMTS5);
    der(AGEprod) = (kprodAGE * Source) + (kactRAGE * AGEprod) - (kactRAGE * AGEprod);
    der(Alk1) = (krelAlk1Alk5 * Alk1_Alk5) + (ksynAlk1 * Source) - (kbinAlk1Alk5 * Alk1 * Alk5) - (kdegAlk1 * Alk1);
    der(Alk1_Alk5) = (kbinAlk1Alk5 * Alk1 * Alk5) + (krelTgfbAlk1 * Tgfb_Alk1_Alk5) - (krelAlk1Alk5 * Alk1_Alk5) - (kbinTgfbAlk1 * Tgfb_A * Alk1_Alk5);
    der(Alk5) = (ksynAlk5 * Source) + (2.0 * kdedimerAlk5 * Alk5_dimer) + (krelAlk1Alk5 * Alk1_Alk5) - (2.0 * kdimerAlk5 * Alk5 * (Alk5 - 1) * 0.5) - (kbinAlk1Alk5 * Alk1 * Alk5) - (kdegAlk5 * Alk5);
    der(Alk5_dimer) = (kdimerAlk5 * Alk5 * (Alk5 - 1) * 0.5) + (krelTgfbAlk5 * Tgfb_Alk5_dimer) - (kdedimerAlk5 * Alk5_dimer) - (kbinTgfbAlk5 * Tgfb_A * Alk5_dimer);
    der(Bax) = (kactCasp * Caspase_I * Bax) + (krelBaxBcl2 * Bax_Bcl2) + (krelBaxBcl2Bec * Bax_Bcl2_Beclin) + (krelBaxBcl2Bec * Bax_Bcl2_Beclin_I) - (kactCasp * Caspase_I * Bax) - (kbinBaxBcl2 * Bax * Bcl2) - (kbinBaxToBcl2Bec * Bax * Bcl2_Beclin) - (kbinBaxToBcl2Bec * Bax * Bcl2_Beclin_I);
    der(Bax_Bcl2) = (kbinBaxBcl2 * Bax * Bcl2) + (krelBecBaxBcl2 * Bax_Bcl2_Beclin) + (krelBecBaxBcl2 * Bax_Bcl2_Beclin_I) - (krelBaxBcl2 * Bax_Bcl2) - (kbinBecToBaxBcl2 * Beclin * Bax_Bcl2) - (kbinBecToBaxBcl2 * Beclin_I * Bax_Bcl2);
    der(Bax_Bcl2_Beclin) = (kbinBecToBaxBcl2 * Beclin * Bax_Bcl2) + (kbinBaxToBcl2Bec * Bax * Bcl2_Beclin) - (krelBaxBcl2Bec * Bax_Bcl2_Beclin) - (krelBecBaxBcl2 * Bax_Bcl2_Beclin);
    der(Bax_Bcl2_Beclin_I) = (kbinBecToBaxBcl2 * Beclin_I * Bax_Bcl2) + (kbinBaxToBcl2Bec * Bax * Bcl2_Beclin_I) - (krelBaxBcl2Bec * Bax_Bcl2_Beclin_I) - (krelBecBaxBcl2 * Bax_Bcl2_Beclin_I);
    der(Bcl2) = (kinactCaspBcl2 * Caspase_A * Bcl2) + (ksynBcl2 * Source) + (krelBaxBcl2 * Bax_Bcl2) + (krelBcl2Beclin * Bcl2_Beclin) + (krelBcl2Beclin * Bcl2_Beclin_I) - (kinactCaspBcl2 * Caspase_A * Bcl2) - (kdegBcl2 * Bcl2) - (kdegBcl2ROS * Bcl2 * ROS) - (kdegBcl2Casp * Bcl2 * Caspase_A) - (kbinBaxBcl2 * Bax * Bcl2) - (kbinBcl2Beclin * Bcl2 * Beclin) - (kbinBcl2Beclin * Bcl2 * Beclin_I);
    der(Bcl2_Beclin) = (kinactCaspBcl2 * Caspase_A * Bcl2_Beclin) + (kbinBcl2Beclin * Bcl2 * Beclin) + (krelBaxBcl2Bec * Bax_Bcl2_Beclin) - (kinactCaspBcl2 * Caspase_A * Bcl2_Beclin) - (krelBcl2Beclin * Bcl2_Beclin) - (kbinBaxToBcl2Bec * Bax * Bcl2_Beclin);
    der(Bcl2_Beclin_I) = (kbinBcl2Beclin * Bcl2 * Beclin_I) + (krelBaxBcl2Bec * Bax_Bcl2_Beclin_I) - (krelBcl2Beclin * Bcl2_Beclin_I) - (kbinBaxToBcl2Bec * Bax * Bcl2_Beclin_I);
    der(Beclin) = (kactLys * Lys_I * Beclin) + (krelBcl2Beclin * Bcl2_Beclin) + (krelBecBaxBcl2 * Bax_Bcl2_Beclin) - (kactLys * Lys_I * Beclin) - (kbinBcl2Beclin * Bcl2 * Beclin) - (kinactBec * Beclin) - (kinactBecCasp * Beclin * Caspase_A) - (kbinBecToBaxBcl2 * Beclin * Bax_Bcl2);
    der(Beclin_I) = (kactCaspBecI * Caspase_I * Beclin_I) + (krelBcl2Beclin * Bcl2_Beclin_I) + (kinactBec * Beclin) + (kinactBecCasp * Beclin * Caspase_A) + (krelBecBaxBcl2 * Bax_Bcl2_Beclin_I) - (kactCaspBecI * Caspase_I * Beclin_I) - (kbinBcl2Beclin * Bcl2 * Beclin_I) - (kbinBecToBaxBcl2 * Beclin_I * Bax_Bcl2);
    der(Caspase_A) = (kactCasp * Caspase_I * Bax) + (kactCaspBecI * Caspase_I * Beclin_I) + (kactCaspp38 * Caspase_I * p38_P) + (kdegBcl2Casp * Bcl2 * Caspase_A) + (kinactBecCasp * Beclin * Caspase_A) - (kinactCasp * Caspase_A) - (kinactCaspBcl2 * Caspase_A * Bcl2_Beclin) - (kinactCaspBcl2 * Caspase_A * Bcl2) - (kdegBcl2Casp * Bcl2 * Caspase_A) - (kinactBecCasp * Beclin * Caspase_A);
    der(Caspase_I) = (kinactCasp * Caspase_A) + (kinactCaspBcl2 * Caspase_A * Bcl2_Beclin) + (kinactCaspBcl2 * Caspase_A * Bcl2) - (kactCasp * Caspase_I * Bax) - (kactCaspBecI * Caspase_I * Beclin_I) - (kactCaspp38 * Caspase_I * p38_P);
    der(Col2mRNA) = (ksynCol2mRNASox9A * Sox9_A) + (ksynCol2mRNASmad * Smad2_P_Smad4) + (ksynCol2 * Col2mRNA) - (kdegCol2mRNA * Col2mRNA) - (ksynCol2 * Col2mRNA);
    der(DamP) = (kdamNatP * NatP * ROS / (10 + ROS)) + (kgenROSbyDamP * DamP) - (kdegDamP * DamP * Lys_A) - (kgenROSbyDamP * DamP);
    der(IkB) = (ksynIkB * NFkB_P) - (kinactNFkB * NFkB * IkB);
    der(IkB_NFkB) = (kinactNFkB * NFkB * IkB) - (kdegIkB * ROS * IkB_NFkB) - (kdegIkB * IL1 * IkB_NFkB);
    der(IL1) = (kdegIkB * IL1 * IkB_NFkB) + (ksynIL1 * NFkB_P) + (ksynMMP13 * IL1) + (ksynMMP2 * IL1) + (ksynADAMTS5 * IL1) + (kphosp38 * p38 * IL1) - (kdegIkB * IL1 * IkB_NFkB) - (kdegIL1 * IL1) - (ksynMMP13 * IL1) - (ksynMMP2 * IL1) - (ksynADAMTS5 * IL1) - (kphosp38 * p38 * IL1);
    der(Lys_A) = (kactLys * Lys_I * Beclin) + (kdegDamP * DamP * Lys_A) - (kinhibLys * Lys_A) - (kdegDamP * DamP * Lys_A) - (kdamLys * Lys_A * ROS / (10 + ROS));
    der(Lys_I) = (kinhibLys * Lys_A) + (kdamLys * Lys_A * ROS / (10 + ROS)) - (kactLys * Lys_I * Beclin);
    der(MMP13) = (kdegCollagen * Collagen2 * MMP13) + (kactMMP13 * proMMP13) - (kdegMMP13 * MMP13) - (kdegCollagen * Collagen2 * MMP13);
    der(MMP2) = (kactMMP2 * proMMP2) + (kactTgfbMMP2 * Tgfb_I * MMP2) - (kdegMMP2 * MMP2) - (kactTgfbMMP2 * Tgfb_I * MMP2);
    der(NatP) = 0.0;
    der(NFkB) = (kdegIkB * ROS * IkB_NFkB) + (kdegIkB * IL1 * IkB_NFkB) + (kdephosNFkB * NFkB_P) - (kinactNFkB * NFkB * IkB) - (kphosNFkB * NFkB * p38_P);
    der(NFkB_P) = (ksynRAGE * NFkB_P) + (ksynIL1 * NFkB_P) + (ksynIkB * NFkB_P) + (ksynSOD * NFkB_P) + (kphosNFkB * NFkB * p38_P) - (ksynRAGE * NFkB_P) - (ksynIL1 * NFkB_P) - (ksynIkB * NFkB_P) - (ksynSOD * NFkB_P) - (kdephosNFkB * NFkB_P);
    der(p38) = (kdephosp38 * p38_P) - (kphosp38 * p38 * IL1) - (kphosp38ROS * p38 * ROS);
    der(p38_P) = (kactCaspp38 * Caspase_I * p38_P) + (kphosp38 * p38 * IL1) + (kphosp38ROS * p38 * ROS) + (kphosNFkB * NFkB * p38_P) + (kgenROSbyp38 * p38_P) - (kactCaspp38 * Caspase_I * p38_P) - (kdephosp38 * p38_P) - (kphosNFkB * NFkB * p38_P) - (kgenROSbyp38 * p38_P);
    der(proMMP13) = (ksynMMP13 * IL1) + (ksynMMP13Runx2 * Runx2_A) - (kactMMP13 * proMMP13);
    der(proMMP2) = (ksynMMP2 * IL1) - (kactMMP2 * proMMP2);
    der(RAGE) = (kactRAGE * AGEprod) + (kgenROSbyRAGE * RAGE) + (ksynRAGE * NFkB_P) - (kgenROSbyRAGE * RAGE) - (kinactRAGE * RAGE);
    der(ROS) = (kdegBcl2ROS * Bcl2 * ROS) + (kgenROS * Source) + (kdamNatP * NatP * ROS / (10 + ROS)) + (kgenROSbyRAGE * RAGE) + (kdegIkB * ROS * IkB_NFkB) + (kgenROSbyDamP * DamP) + (kphosp38ROS * p38 * ROS) + (kgenROSbyp38 * p38_P) + (kdamLys * Lys_A * ROS / (10 + ROS)) - (kdegBcl2ROS * Bcl2 * ROS) - (kremROS * ROS) - (kdamNatP * NatP * ROS / (10 + ROS)) - (kdegIkB * ROS * IkB_NFkB) - (kremROSbySOD * SOD * ROS) - (kphosp38ROS * p38 * ROS) - (kdamLys * Lys_A * ROS / (10 + ROS));
    der(Runx2_A) = (kactRunx2 * Runx2_I * Smad1_P_Smad4) + (ksynMMP13Runx2 * Runx2_A) - (kinactRunx2 * Runx2_A * Smad2_P_Smad4) - (ksynMMP13Runx2 * Runx2_A);
    der(Runx2_I) = (kinactRunx2 * Runx2_A * Smad2_P_Smad4) - (kactRunx2 * Runx2_I * Smad1_P_Smad4);
    der(Smad1) = (kdephosSmad1 * Smad1_P) + (kdephosSmad1Smad7 * Smad1_P * Smad7) - (kphosSmad1 * Tgfb_Alk1_Alk5 * Smad1);
    der(Smad1_P) = (kphosSmad1 * Tgfb_Alk1_Alk5 * Smad1) + (krelSmad1Smad4 * Smad1_P_Smad4) - (kdephosSmad1 * Smad1_P) - (kdephosSmad1Smad7 * Smad1_P * Smad7) - (kbinSmad1Smad4 * Smad1_P * Smad4);
    der(Smad1_P_Smad4) = (kbinSmad1Smad4 * Smad1_P * Smad4) + (kactRunx2 * Runx2_I * Smad1_P_Smad4) - (krelSmad1Smad4 * Smad1_P_Smad4) - (kactRunx2 * Runx2_I * Smad1_P_Smad4);
    der(Smad2) = (kdephosSmad2 * Smad2_P) - (kphosSmad2 * Tgfb_Alk5_dimer * Smad2);
    der(Smad2_P) = (kphosSmad2 * Tgfb_Alk5_dimer * Smad2) + (krelSmad2Smad4 * Smad2_P_Smad4) - (kbinSmad2Smad4 * Smad2_P * Smad4) - (kdephosSmad2 * Smad2_P);
    der(Smad2_P_Smad4) = (kbinSmad2Smad4 * Smad2_P * Smad4) + (ksynSmad7 * Smad2_P_Smad4) + (kactSox9 * Smad2_P_Smad4 * Sox9) + (ksynCol2mRNASmad * Smad2_P_Smad4) + (kinactRunx2 * Runx2_A * Smad2_P_Smad4) - (krelSmad2Smad4 * Smad2_P_Smad4) - (ksynSmad7 * Smad2_P_Smad4) - (kactSox9 * Smad2_P_Smad4 * Sox9) - (ksynCol2mRNASmad * Smad2_P_Smad4) - (kinactRunx2 * Runx2_A * Smad2_P_Smad4);
    der(Smad4) = (krelSmad2Smad4 * Smad2_P_Smad4) + (krelSmad1Smad4 * Smad1_P_Smad4) - (kbinSmad2Smad4 * Smad2_P * Smad4) - (kbinSmad1Smad4 * Smad1_P * Smad4);
    der(Smad7) = (krelSmad7Alk5 * Tgfb_Alk5_dimer_Smad7) + (ksynSmad7 * Smad2_P_Smad4) + (kdephosSmad1Smad7 * Smad1_P * Smad7) + (krelSmad7Alk1 * Tgfb_Alk1_Alk5_Smad7) - (kbinSmad7Alk5 * Tgfb_Alk5_dimer * Smad7) - (kdephosSmad1Smad7 * Smad1_P * Smad7) - (kbinSmad7Alk1 * Tgfb_Alk1_Alk5 * Smad7) - (kdegSmad7 * Smad7);
    der(SOD) = (ksynSOD * NFkB_P) + (kremROSbySOD * SOD * ROS) - (kdegSOD * SOD) - (kremROSbySOD * SOD * ROS);
    der(Sox9) = (kinactSox9 * Sox9_A) + (ksynSox9 * Sox9mRNA) - (kactSox9 * Smad2_P_Smad4 * Sox9) - (kdegSox9 * Sox9);
    der(Sox9_A) = (kactSox9 * Smad2_P_Smad4 * Sox9) + (ksynSox9mRNASox9A * Sox9_A) + (ksynCol2mRNASox9A * Sox9_A) + (ksynAcanmRNASox9A * Sox9_A) - (kinactSox9 * Sox9_A) - (ksynSox9mRNASox9A * Sox9_A) - (ksynCol2mRNASox9A * Sox9_A) - (ksynAcanmRNASox9A * Sox9_A);
    der(Sox9mRNA) = (ksynSox9mRNA * Source) + (ksynSox9mRNASox9A * Sox9_A) + (ksynSox9 * Sox9mRNA) - (kdegSox9mRNA * Sox9mRNA) - (ksynSox9 * Sox9mRNA);
    der(Tgfb_A) = (kactTgfbIntegrin * Tgfb_I * Integrin) + (kactTgfbMMP2 * Tgfb_I * MMP2) + (krelTgfbAlk5 * Tgfb_Alk5_dimer) + (krelTgfbAlk1 * Tgfb_Alk1_Alk5) - (kinactTgfb * Tgfb_A) - (kbinTgfbAlk5 * Tgfb_A * Alk5_dimer) - (kbinTgfbAlk1 * Tgfb_A * Alk1_Alk5);
    der(Tgfb_Alk1_Alk5) = (kbinTgfbAlk1 * Tgfb_A * Alk1_Alk5) + (kphosSmad1 * Tgfb_Alk1_Alk5 * Smad1) + (krelSmad7Alk1 * Tgfb_Alk1_Alk5_Smad7) - (krelTgfbAlk1 * Tgfb_Alk1_Alk5) - (kphosSmad1 * Tgfb_Alk1_Alk5 * Smad1) - (kbinSmad7Alk1 * Tgfb_Alk1_Alk5 * Smad7);
    der(Tgfb_Alk1_Alk5_Smad7) = (kbinSmad7Alk1 * Tgfb_Alk1_Alk5 * Smad7) - (krelSmad7Alk1 * Tgfb_Alk1_Alk5_Smad7) - (kdegSmad7Alk1 * Tgfb_Alk1_Alk5_Smad7);
    der(Tgfb_Alk5_dimer) = (kbinTgfbAlk5 * Tgfb_A * Alk5_dimer) + (krelSmad7Alk5 * Tgfb_Alk5_dimer_Smad7) + (kphosSmad2 * Tgfb_Alk5_dimer * Smad2) - (krelTgfbAlk5 * Tgfb_Alk5_dimer) - (kbinSmad7Alk5 * Tgfb_Alk5_dimer * Smad7) - (kphosSmad2 * Tgfb_Alk5_dimer * Smad2);
    der(Tgfb_Alk5_dimer_Smad7) = (kbinSmad7Alk5 * Tgfb_Alk5_dimer * Smad7) - (krelSmad7Alk5 * Tgfb_Alk5_dimer_Smad7) - (kdegSmad7Alk5 * Tgfb_Alk5_dimer_Smad7);
    der(AggFrag) = (kdegAggrecan * Aggrecan_Collagen2 * ADAMTS5) ;
    der(Aggrecan) = (ksynAggrecan * AcanmRNA) - (kbinAggrecanCollagen2 * Aggrecan * Collagen2);
    der(Aggrecan_Collagen2) = (kbinAggrecanCollagen2 * Aggrecan * Collagen2) - (kdegAggrecan * Aggrecan_Collagen2 * ADAMTS5);
    der(ColFrag) = (kdegCollagen * Collagen2 * MMP13) ;
    der(Collagen2) = (kdegAggrecan * Aggrecan_Collagen2 * ADAMTS5) + (ksynCol2 * Col2mRNA) - (kdegCollagen * Collagen2 * MMP13) - (kbinAggrecanCollagen2 * Aggrecan * Collagen2);
    der(Integrin) = (kactIntegrin * Source) + (kactTgfbIntegrin * Tgfb_I * Integrin) - (kinactIntegrin * Integrin) - (kactTgfbIntegrin * Tgfb_I * Integrin);
    der(Tgfb_I) = (kinactTgfb * Tgfb_A) + (kdegSmad7Alk5 * Tgfb_Alk5_dimer_Smad7) + (kdegSmad7Alk1 * Tgfb_Alk1_Alk5_Smad7) - (kactTgfbIntegrin * Tgfb_I * Integrin) - (kactTgfbMMP2 * Tgfb_I * MMP2);
    der(Sink) = 0.0;
    der(Source) = 0.0;
    der(IntegrinCount) = (kactIntegrin * Source) ;




end BIOMD560;
