within BIOMD110;
model Qu2003_CellCycle "Qu2003_CellCycle" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_cell elmt_cell;

    equation
        Reacs.elmt_i = elmt_cell.elmt_i;
        Reacs.elmt_c = elmt_cell.elmt_c;
        Reacs.elmt_a = Params.elmt_a;
        Reacs.elmt_bi = Params.elmt_bi;
        Reacs.elmt_Tau = Params.elmt_Tau;
        Reacs.elmt_z0 = elmt_cell.elmt_z0;
        Reacs.elmt_aw = Params.elmt_aw;
        Reacs.elmt_cell = elmt_cell.elmt_cell;
        Reacs.elmt_k16u = Params.elmt_k16u;
        Reacs.elmt_cw = Params.elmt_cw;
        Reacs.elmt_ix = elmt_cell.elmt_ix;
        Reacs.elmt_k16 = Params.elmt_k16;
        Reacs.elmt_k15 = Params.elmt_k15;
        Reacs.elmt_k14 = Params.elmt_k14;
        Reacs.elmt_k13 = Params.elmt_k13;
        Reacs.elmt_az = Params.elmt_az;
        Reacs.elmt_x1 = elmt_cell.elmt_x1;
        Reacs.elmt_k12 = Params.elmt_k12;
        Reacs.elmt_k11 = Params.elmt_k11;
        Reacs.elmt_k10 = Params.elmt_k10;
        Reacs.elmt_cz = Params.elmt_cz;
        Reacs.elmt_z1 = elmt_cell.elmt_z1;
        Reacs.elmt_z2 = elmt_cell.elmt_z2;
        Reacs.elmt_k7u = Params.elmt_k7u;
        Reacs.elmt_ci = Params.elmt_ci;
        Reacs.elmt_k1 = Params.elmt_k1;
        Reacs.elmt_k8 = Params.elmt_k8;
        Reacs.elmt_k9 = Params.elmt_k9;
        Reacs.elmt_k6 = Params.elmt_k6;
        Reacs.elmt_k7 = Params.elmt_k7;
        Reacs.elmt_k4 = Params.elmt_k4;
        Reacs.elmt_k5 = Params.elmt_k5;
        Reacs.elmt_k2 = Params.elmt_k2;
        Reacs.elmt_ai = Params.elmt_ai;
        Reacs.elmt_k3 = Params.elmt_k3;
        Reacs.elmt_bw = Params.elmt_bw;
        Reacs.elmt_y = elmt_cell.elmt_y;
        Reacs.elmt_ixp = elmt_cell.elmt_ixp;
        Reacs.elmt_x = elmt_cell.elmt_x;
        Reacs.elmt_k2u = Params.elmt_k2u;
        Reacs.elmt_u = elmt_cell.elmt_u;
        Reacs.elmt_w0 = elmt_cell.elmt_w0;
        Reacs.elmt_w1 = elmt_cell.elmt_w1;
        Reacs.elmt_bz = Params.elmt_bz;
        elmt_cell.elmt_reaction_0000022 = Reacs.elmt_reaction_0000022;
        elmt_cell.elmt_reaction_0000021 = Reacs.elmt_reaction_0000021;
        elmt_cell.elmt_reaction_0000020 = Reacs.elmt_reaction_0000020;
        elmt_cell.elmt_product29 = Reacs.elmt_product29;
        elmt_cell.elmt_reaction_0000023 = Reacs.elmt_reaction_0000023;
        elmt_cell.elmt_reaction_0000019 = Reacs.elmt_reaction_0000019;
        elmt_cell.elmt_reaction_0000018 = Reacs.elmt_reaction_0000018;
        elmt_cell.elmt_reaction_0000017 = Reacs.elmt_reaction_0000017;
        elmt_cell.elmt_reaction_0000016 = Reacs.elmt_reaction_0000016;
        elmt_cell.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_cell.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_cell.elmt_reactant11 = Reacs.elmt_reactant11;
        elmt_cell.elmt_reaction_0000011 = Reacs.elmt_reaction_0000011;
        elmt_cell.elmt_reaction_0000010 = Reacs.elmt_reaction_0000010;
        elmt_cell.elmt_reaction_0000015 = Reacs.elmt_reaction_0000015;
        elmt_cell.elmt_reaction_0000014 = Reacs.elmt_reaction_0000014;
        elmt_cell.elmt_reaction_0000013 = Reacs.elmt_reaction_0000013;
        elmt_cell.elmt_reaction_0000007 = Reacs.elmt_reaction_0000007;
        elmt_cell.elmt_reaction_0000006 = Reacs.elmt_reaction_0000006;
        elmt_cell.elmt_reaction_0000005 = Reacs.elmt_reaction_0000005;
        elmt_cell.elmt_reactant20 = Reacs.elmt_reactant20;
        elmt_cell.elmt_product12 = Reacs.elmt_product12;
        elmt_cell.elmt_product10 = Reacs.elmt_product10;
        elmt_cell.elmt_reactant25 = Reacs.elmt_reactant25;
        elmt_cell.elmt_reactant26 = Reacs.elmt_reactant26;
        elmt_cell.elmt_reactant27 = Reacs.elmt_reactant27;
        elmt_cell.elmt_reactant28 = Reacs.elmt_reactant28;
        elmt_cell.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_cell.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_cell.elmt_reactant24 = Reacs.elmt_reactant24;
        elmt_cell.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_cell.elmt_reaction_0000004 = Reacs.elmt_reaction_0000004;
        elmt_cell.elmt_reaction_0000003 = Reacs.elmt_reaction_0000003;
        elmt_cell.elmt_reaction_0000002 = Reacs.elmt_reaction_0000002;
        elmt_cell.elmt_reaction_0000001 = Reacs.elmt_reaction_0000001;
        elmt_cell.elmt_product9 = Reacs.elmt_product9;
        elmt_cell.elmt_reactant1 = Reacs.elmt_reactant1;
        elmt_cell.elmt_reactant4 = Reacs.elmt_reactant4;
        elmt_cell.elmt_reactant30 = Reacs.elmt_reactant30;
        elmt_cell.elmt_product7 = Reacs.elmt_product7;
        elmt_cell.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_cell.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_cell.elmt_product23 = Reacs.elmt_product23;
        elmt_cell.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_cell.elmt_product0 = Reacs.elmt_product0;
        elmt_cell.elmt_reaction_000008 = Reacs.elmt_reaction_000008;
        elmt_cell.elmt_product5 = Reacs.elmt_product5;
        elmt_cell.elmt_reaction_000009 = Reacs.elmt_reaction_000009;
        elmt_cell.elmt_product2 = Reacs.elmt_product2;
        elmt_cell.elmt_product14 = Reacs.elmt_product14;
        elmt_cell.elmt_product13 = Reacs.elmt_product13;
        elmt_cell.elmt_product19 = Reacs.elmt_product19;
        elmt_cell.elmt_product17 = Reacs.elmt_product17;

end Qu2003_CellCycle;
