within BIOMD500;
model MODEL1311130001 "Begitt2014 - STAT1 cooperative DNA binding - single GAS polymer model" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_nucleus elmt_nucleus;
    Class_elmt_default elmt_default;

    equation
        Params.elmt_DNA_111 = elmt_nucleus.elmt_DNA_111;
        Params.elmt_DNA_1B11 = elmt_nucleus.elmt_DNA_1B11;
        Params.elmt_DNA_11B1 = elmt_nucleus.elmt_DNA_11B1;
        Params.elmt_DNA_01B1 = elmt_nucleus.elmt_DNA_01B1;
        Params.elmt_DNA_1B10 = elmt_nucleus.elmt_DNA_1B10;
        Params.elmt_DNA_010 = elmt_nucleus.elmt_DNA_010;
        Params.elmt_DNA_011 = elmt_nucleus.elmt_DNA_011;
        Params.elmt_DNA_110 = elmt_nucleus.elmt_DNA_110;
        Params.elmt_DNA_1B1B1 = elmt_nucleus.elmt_DNA_1B1B1;
        Reacs.elmt_nucleus = elmt_nucleus.elmt_nucleus;
        Reacs.elmt_Koff_G1 = Params.elmt_Koff_G1;
        Reacs.elmt_DNA_1B11 = elmt_nucleus.elmt_DNA_1B11;
        Reacs.elmt_DNA_11B1 = elmt_nucleus.elmt_DNA_11B1;
        Reacs.elmt_DNA_1B10 = elmt_nucleus.elmt_DNA_1B10;
        Reacs.elmt_DNA_01B1 = elmt_nucleus.elmt_DNA_01B1;
        Reacs.elmt_Kon_G1 = Params.elmt_Kon_G1;
        Reacs.elmt_DNA_1B1B1 = elmt_nucleus.elmt_DNA_1B1B1;
        Reacs.elmt_DNA_001 = elmt_nucleus.elmt_DNA_001;
        Reacs.elmt_Kon_NG1 = Params.elmt_Kon_NG1;
        Reacs.elmt_DNA_111 = elmt_nucleus.elmt_DNA_111;
        Reacs.elmt_DNA_100 = elmt_nucleus.elmt_DNA_100;
        Reacs.elmt_DNA_101 = elmt_nucleus.elmt_DNA_101;
        Reacs.elmt_Koff_P1 = Params.elmt_Koff_P1;
        Reacs.elmt_S1 = elmt_nucleus.elmt_S1;
        Reacs.elmt_Kon_P1 = Params.elmt_Kon_P1;
        Reacs.elmt_DNA_010 = elmt_nucleus.elmt_DNA_010;
        Reacs.elmt_Koff_NG1 = Params.elmt_Koff_NG1;
        Reacs.elmt_DNA_011 = elmt_nucleus.elmt_DNA_011;
        Reacs.elmt_DNA_110 = elmt_nucleus.elmt_DNA_110;
        Reacs.elmt_DNA_000 = elmt_nucleus.elmt_DNA_000;
        elmt_nucleus.elmt_reactant40 = Reacs.elmt_reactant40;
        elmt_nucleus.elmt_reactant42 = Reacs.elmt_reactant42;
        elmt_nucleus.elmt_product32 = Reacs.elmt_product32;
        elmt_nucleus.elmt_reactant44 = Reacs.elmt_reactant44;
        elmt_nucleus.elmt_reactant46 = Reacs.elmt_reactant46;
        elmt_nucleus.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_nucleus.elmt_product26 = Reacs.elmt_product26;
        elmt_nucleus.elmt_product29 = Reacs.elmt_product29;
        elmt_nucleus.elmt_product41 = Reacs.elmt_product41;
        elmt_nucleus.elmt_product45 = Reacs.elmt_product45;
        elmt_nucleus.elmt_product43 = Reacs.elmt_product43;
        elmt_nucleus.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_nucleus.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_nucleus.elmt_reactant10 = Reacs.elmt_reactant10;
        elmt_nucleus.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_nucleus.elmt_reactant13 = Reacs.elmt_reactant13;
        elmt_nucleus.elmt_product37 = Reacs.elmt_product37;
        elmt_nucleus.elmt_product35 = Reacs.elmt_product35;
        elmt_nucleus.elmt_product39 = Reacs.elmt_product39;
        elmt_nucleus.elmt_DNA49 = Reacs.elmt_DNA49;
        elmt_nucleus.elmt_product11 = Reacs.elmt_product11;
        elmt_nucleus.elmt_reactant25 = Reacs.elmt_reactant25;
        elmt_nucleus.elmt_reactant27 = Reacs.elmt_reactant27;
        elmt_nucleus.elmt_reactant28 = Reacs.elmt_reactant28;
        elmt_nucleus.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_nucleus.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_nucleus.elmt_reactant24 = Reacs.elmt_reactant24;
        elmt_nucleus.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_nucleus.elmt_reactant19 = Reacs.elmt_reactant19;
        elmt_nucleus.elmt_product47 = Reacs.elmt_product47;
        elmt_nucleus.elmt_DNA8 = Reacs.elmt_DNA8;
        elmt_nucleus.elmt_DNA9 = Reacs.elmt_DNA9;
        elmt_nucleus.elmt_product8 = Reacs.elmt_product8;
        elmt_nucleus.elmt_reactant1 = Reacs.elmt_reactant1;
        elmt_nucleus.elmt_reactant30 = Reacs.elmt_reactant30;
        elmt_nucleus.elmt_DNA6 = Reacs.elmt_DNA6;
        elmt_nucleus.elmt_reactant4 = Reacs.elmt_reactant4;
        elmt_nucleus.elmt_DNA7 = Reacs.elmt_DNA7;
        elmt_nucleus.elmt_reactant31 = Reacs.elmt_reactant31;
        elmt_nucleus.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_nucleus.elmt_product23 = Reacs.elmt_product23;
        elmt_nucleus.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_nucleus.elmt_reactant7 = Reacs.elmt_reactant7;
        elmt_nucleus.elmt_product20 = Reacs.elmt_product20;
        elmt_nucleus.elmt_DNA51 = Reacs.elmt_DNA51;
        elmt_nucleus.elmt_reactant36 = Reacs.elmt_reactant36;
        elmt_nucleus.elmt_DNA52 = Reacs.elmt_DNA52;
        elmt_nucleus.elmt_reactant38 = Reacs.elmt_reactant38;
        elmt_nucleus.elmt_DNA50 = Reacs.elmt_DNA50;
        elmt_nucleus.elmt_DNA11 = Reacs.elmt_DNA11;
        elmt_nucleus.elmt_product5 = Reacs.elmt_product5;
        elmt_nucleus.elmt_DNA12 = Reacs.elmt_DNA12;
        elmt_nucleus.elmt_reactant33 = Reacs.elmt_reactant33;
        elmt_nucleus.elmt_DNA53 = Reacs.elmt_DNA53;
        elmt_nucleus.elmt_reactant34 = Reacs.elmt_reactant34;
        elmt_nucleus.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_nucleus.elmt_DNA54 = Reacs.elmt_DNA54;
        elmt_nucleus.elmt_product2 = Reacs.elmt_product2;
        elmt_nucleus.elmt_DNA10 = Reacs.elmt_DNA10;
        elmt_nucleus.elmt_DNA1 = Reacs.elmt_DNA1;
        elmt_nucleus.elmt_product14 = Reacs.elmt_product14;
        elmt_nucleus.elmt_DNA4 = Reacs.elmt_DNA4;
        elmt_nucleus.elmt_DNA5 = Reacs.elmt_DNA5;
        elmt_nucleus.elmt_DNA2 = Reacs.elmt_DNA2;
        elmt_nucleus.elmt_DNA3 = Reacs.elmt_DNA3;
        elmt_nucleus.elmt_product17 = Reacs.elmt_product17;

end MODEL1311130001;
