within BIOMD347;
class Parameters

    Real elmt_SOCS3Turn(unit = "") "";
    Real elmt_JAK2ActEpo(unit = "") "";
    Real elmt_CISRNADelay(unit = "") "";
    Real elmt_CISEqc(unit = "") "";
    Real elmt_CISRNAEqc(unit = "") "";
    Real elmt_JAK2EpoRDeaSHP1(unit = "") "";
    Real elmt_STAT5ActEpoR(unit = "") "";
    Real elmt_SHP1Dea(unit = "") "";
    Real elmt_init_STAT5(unit = "") "";
    Real elmt_SHP1ActEpoR(unit = "") "";
    Real elmt_CISInh(unit = "") "";
    Real elmt_CISEqcOE(unit = "") "";
    Real elmt_epo_level(unit = "") "";
    Real elmt_STAT5Imp(unit = "") "";
    Real elmt_SOCS3Eqc(unit = "") "";
    Real elmt_STAT5ActJAK2(unit = "") "";
    Real elmt_EpoRActJAK2(unit = "") "";
    Real elmt_SOCS3EqcOE(unit = "") "";
    Real elmt_CISoe(unit = "") "";
    Real elmt_EpoRCISRemove(unit = "") "";
    Real elmt_CISTurn(unit = "") "";
    Real elmt_STAT5Exp(unit = "") "";
    Real elmt_SOCS3RNAEqc(unit = "") "";
    Real elmt_SOCS3Inh(unit = "") "";
    Real elmt_ActD(unit = "") "";
    Real elmt_SOCS3RNADelay(unit = "") "";
    Real elmt_SOCS3RNATurn(unit = "") "";
    Real elmt_EpoRCISInh(unit = "") "";
    Real elmt_init_SHP1(unit = "") "";
    Real elmt_CISRNATurn(unit = "") "";
    Real elmt_init_EpoRJAK2(unit = "") "";
    Real elmt_SOCS3oe(unit = "") "";


    initial equation
        elmt_SOCS3Turn = 10000.0;
        elmt_JAK2ActEpo = 633253.0;
        elmt_CISRNADelay = 0.144775;
        elmt_CISEqc = 432.871;
        elmt_CISRNAEqc = 1.0;
        elmt_JAK2EpoRDeaSHP1 = 142.722;
        elmt_STAT5ActEpoR = 38.9757;
        elmt_SHP1Dea = 0.00816391;
        elmt_init_STAT5 = 79.7535;
        elmt_SHP1ActEpoR = 0.001;
        elmt_CISInh = 7.84653E8;
        elmt_CISEqcOE = 0.530261;
        elmt_epo_level = 1.24997E-7;
        elmt_STAT5Imp = 0.0268889;
        elmt_SOCS3Eqc = 173.653;
        elmt_STAT5ActJAK2 = 0.0780965;
        elmt_EpoRActJAK2 = 0.267308;
        elmt_SOCS3EqcOE = 0.679157;
        elmt_CISoe = 0.0;
        elmt_EpoRCISRemove = 5.42932;
        elmt_CISTurn = 0.00839842;
        elmt_STAT5Exp = 0.0745155;
        elmt_SOCS3RNAEqc = 1.0;
        elmt_SOCS3Inh = 10.408;
        elmt_ActD = 0.0;
        elmt_SOCS3RNADelay = 1.06465;
        elmt_SOCS3RNATurn = 0.00830844;
        elmt_EpoRCISInh = 1000000.0;
        elmt_init_SHP1 = 26.7251;
        elmt_CISRNATurn = 1000.0;
        elmt_init_EpoRJAK2 = 3.97622;
        elmt_SOCS3oe = 0.0;


    equation
        der(elmt_SOCS3Turn) = 0;
        der(elmt_JAK2ActEpo) = 0;
        der(elmt_CISRNADelay) = 0;
        der(elmt_CISEqc) = 0;
        der(elmt_CISRNAEqc) = 0;
        der(elmt_JAK2EpoRDeaSHP1) = 0;
        der(elmt_STAT5ActEpoR) = 0;
        der(elmt_SHP1Dea) = 0;
        der(elmt_init_STAT5) = 0;
        der(elmt_SHP1ActEpoR) = 0;
        der(elmt_CISInh) = 0;
        der(elmt_CISEqcOE) = 0;
        der(elmt_epo_level) = 0;
        der(elmt_STAT5Imp) = 0;
        der(elmt_SOCS3Eqc) = 0;
        der(elmt_STAT5ActJAK2) = 0;
        der(elmt_EpoRActJAK2) = 0;
        der(elmt_SOCS3EqcOE) = 0;
        der(elmt_CISoe) = 0;
        der(elmt_EpoRCISRemove) = 0;
        der(elmt_CISTurn) = 0;
        der(elmt_STAT5Exp) = 0;
        der(elmt_SOCS3RNAEqc) = 0;
        der(elmt_SOCS3Inh) = 0;
        der(elmt_ActD) = 0;
        der(elmt_SOCS3RNADelay) = 0;
        der(elmt_SOCS3RNATurn) = 0;
        der(elmt_EpoRCISInh) = 0;
        der(elmt_init_SHP1) = 0;
        der(elmt_CISRNATurn) = 0;
        der(elmt_init_EpoRJAK2) = 0;
        der(elmt_SOCS3oe) = 0;

end Parameters;
