within BIOMD511;
class Reactions

    input Real elmt__3PGA_c;
    input Real elmt_PEP_c;
    input Real elmt_NADPH_c;
    input Real elmt_TSH2_c;
    input Real elmt_Rul5P_g;
    input Real elmt_Fru16BP_g;
    input Real elmt_AMP_g;
    input Real elmt__3PGA_g;
    input Real elmt_AMP_c;
    input Real elmt_Gly_e;
    input Real elmt_Rib5P_c;
    input Real elmt_glycosome;
    input Real elmt_cytosol;
    input Real elmt_Rul5P_c;
    input Real elmt_Rib5P_g;
    input Real elmt_Glc6P_c;
    input Real elmt__6PGL_g;
    input Real elmt_ATP_c;
    input Real elmt_Gly3P_c;
    input Real elmt_Glc6P_g;
    input Real elmt__6PGL_c;
    input Real elmt_ATP_g;
    input Real elmt_Gly3P_g;
    input Real elmt_DHAP_c;
    input Real elmt_ADP_c;
    input Real elmt_Pyr_c;
    input Real elmt_DHAP_g;
    input Real elmt_ADP_g;
    input Real elmt_NADP_g;
    input Real elmt_TS2_c;
    input Real elmt__6PG_g;
    input Real elmt_NADP_c;
    input Real elmt_NADH_g;
    input Real elmt__6PG_c;
    input Real elmt__13BPGA_g;
    input Real elmt_Glc_e;
    input Real elmt_Glc_c;
    input Real elmt_Fru6P_g;
    input Real elmt_GA3P_g;
    input Real elmt_Glc_g;
    input Real elmt__2PGA_c;
    input Real elmt_NAD_g;
    input Real elmt_NADPH_g;

    Real elmt_PGAM_c(unit = "") "PGAM_c";
    parameter Real elmt_PGAM_c_elmt_PGAM_c_Km2PGA(unit "") = 0.16 "";
    parameter Real elmt_PGAM_c_elmt_PGAM_c_Km3PGA(unit "") = 0.15 "";
    parameter Real elmt_PGAM_c_elmt_PGAM_c_Vmax(unit "") = 225.0 "";
    parameter Real elmt_PGAM_c_elmt_PGAM_c_Keq(unit "") = 0.17 "";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_GAPDH_g(unit = "") "GAPDH_g";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_Vmax(unit "") = 720.9 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_KmNAD(unit "") = 0.45 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_KmNADH(unit "") = 0.02 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_Keq(unit "") = 0.066 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_Km13BPGA(unit "") = 0.1 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_KmGA3P(unit "") = 0.15 "";
    Real elmt_product104 "";
    Real elmt_reactant103 "";
    Real elmt_reactant102 "";
    Real elmt_product105 "";
    Real elmt_reactant101 "";
    Real elmt_PPI_c(unit = "") "PPI_c";
    parameter Real elmt_PPI_c_elmt_PPI_c_KmRul5P(unit "") = 1.4 "";
    parameter Real elmt_PPI_c_elmt_PPI_c_Keq(unit "") = 5.6 "";
    parameter Real elmt_PPI_c_elmt_PPI_c_KmRib5P(unit "") = 4.0 "";
    parameter Real elmt_PPI_c_elmt_PPI_c_Vmax(unit "") = 72.0 "";
    Real elmt_product71 "";
    Real elmt_reactant70 "";
    Real elmt_GK_g(unit = "") "GK_g";
    parameter Real elmt_GK_g_elmt_GK_g_KmGly(unit "") = 0.44 "";
    parameter Real elmt_GK_g_elmt_GK_g_Vmax(unit "") = 200.0 "";
    parameter Real elmt_GK_g_elmt_GK_g_KmGly3P(unit "") = 3.83 "";
    parameter Real elmt_GK_g_elmt_GK_g_KmADP(unit "") = 0.56 "";
    parameter Real elmt_GK_g_elmt_GK_g_KmATP(unit "") = 0.24 "";
    parameter Real elmt_GK_g_elmt_GK_g_Keq(unit "") = 8.37E-4 "";
    Real elmt_reactant94 "";
    Real elmt_product96 "";
    Real elmt_reactant95 "";
    Real elmt_product97 "";
    Real elmt_GDA_g(unit = "") "GDA_g";
    parameter Real elmt_GDA_g_elmt_GDA_g_k(unit "") = 600.0 "";
    Real elmt_product58 "";
    Real elmt_product57 "";
    Real elmt_reactant55 "";
    Real elmt_reactant56 "";
    Real elmt_GPO_c(unit = "") "GPO_c";
    parameter Real elmt_GPO_c_elmt_GPO_c_KmGly3P(unit "") = 1.7 "";
    parameter Real elmt_GPO_c_elmt_GPO_c_Vmax(unit "") = 368.0 "";
    Real elmt_reactant106 "";
    Real elmt_product107 "";
    Real elmt_AK_c(unit = "") "AK_c";
    parameter Real elmt_AK_c_elmt_AK_c_k1(unit "") = 480.0 "";
    parameter Real elmt_AK_c_elmt_AK_c_k2(unit "") = 1000.0 "";
    Real elmt_product40 "";
    Real elmt_reactant38 "";
    Real elmt_product39 "";
    Real elmt_ATPu_c(unit = "") "ATPu_c";
    parameter Real elmt_ATPu_c_elmt_ATPu_c_k(unit "") = 50.0 "";
    Real elmt_product93 "";
    Real elmt_reactant92 "";
    Real elmt_GlcT_c(unit = "") "GlcT_c";
    parameter Real elmt_GlcT_c_elmt_GlcT_c_KmGlc(unit "") = 1.0 "";
    parameter Real elmt_GlcT_c_elmt_GlcT_c_alpha(unit "") = 0.75 "";
    parameter Real elmt_GlcT_c_elmt_GlcT_c_Vmax(unit "") = 111.7 "";
    Real elmt_product77 "";
    Real elmt_reactant76 "";
    Real elmt_GlcT_g(unit = "") "GlcT_g";
    parameter Real elmt_GlcT_g_elmt_GlcT_g_k2(unit "") = 250000.0 "";
    parameter Real elmt_GlcT_g_elmt_GlcT_g_k1(unit "") = 250000.0 "";
    Real elmt_reactant74 "";
    Real elmt_product75 "";
    Real elmt_PGL_c(unit = "") "PGL_c";
    parameter Real elmt_PGL_c_elmt_PGL_c_Km6PG(unit "") = 0.05 "";
    parameter Real elmt_PGL_c_elmt_PGL_c_Vmax(unit "") = 28.0 "";
    parameter Real elmt_PGL_c_elmt_PGL_c_Keq(unit "") = 20000.0 "";
    parameter Real elmt_PGL_c_elmt_PGL_c_k(unit "") = 0.055 "";
    parameter Real elmt_PGL_c_elmt_PGL_c_Km6PGL(unit "") = 0.05 "";
    Real elmt_reactant63 "";
    Real elmt_product64 "";
    Real elmt_PGI_g(unit = "") "PGI_g";
    parameter Real elmt_PGI_g_elmt_PGI_g_KmGlc6P(unit "") = 0.4 "";
    parameter Real elmt_PGI_g_elmt_PGI_g_KmFru6P(unit "") = 0.12 "";
    parameter Real elmt_PGI_g_elmt_PGI_g_Vmax(unit "") = 1305.0 "";
    parameter Real elmt_PGI_g_elmt_PGI_g_Ki6PG(unit "") = 0.14 "";
    parameter Real elmt_PGI_g_elmt_PGI_g_Keq(unit "") = 0.457 "";
    Real elmt_product49 "";
    Real elmt_reactant48 "";
    Real elmt_PGK_g(unit = "") "PGK_g";
    parameter Real elmt_PGK_g_elmt_PGK_g_Vmax(unit "") = 2862.0 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_Km13BPGA(unit "") = 0.003 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_Keq(unit "") = 3377.0 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_KmADP(unit "") = 0.1 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_KmATP(unit "") = 0.29 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_Km3PGA(unit "") = 1.62 "";
    Real elmt_reactant84 "";
    Real elmt_reactant85 "";
    Real elmt_product87 "";
    Real elmt_product86 "";
    Real elmt_G6PP_c(unit = "") "G6PP_c";
    parameter Real elmt_G6PP_c_elmt_G6PP_c_KmGlc(unit "") = 5.6 "";
    parameter Real elmt_G6PP_c_elmt_G6PP_c_Vmax(unit "") = 28.0 "";
    parameter Real elmt_G6PP_c_elmt_G6PP_c_Keq(unit "") = 263.0 "";
    parameter Real elmt_G6PP_c_elmt_G6PP_c_KmGlc6P(unit "") = 5.6 "";
    Real elmt_reactant41 "";
    Real elmt_product42 "";
    Real elmt_TOX_c(unit = "") "TOX_c";
    parameter Real elmt_TOX_c_elmt_TOX_c_k(unit "") = 2.0 "";
    Real elmt_reactant53 "";
    Real elmt_product54 "";
    Real elmt_PGL_g(unit = "") "PGL_g";
    parameter Real elmt_PGL_g_elmt_PGL_g_Keq(unit "") = 20000.0 "";
    parameter Real elmt_PGL_g_elmt_PGL_g_Vmax(unit "") = 5.0 "";
    parameter Real elmt_PGL_g_elmt_PGL_g_Km6PG(unit "") = 0.05 "";
    parameter Real elmt_PGL_g_elmt_PGL_g_k(unit "") = 0.055 "";
    parameter Real elmt_PGL_g_elmt_PGL_g_Km6PGL(unit "") = 0.05 "";
    Real elmt_product79 "";
    Real elmt_reactant78 "";
    Real elmt_ENO_c(unit = "") "ENO_c";
    parameter Real elmt_ENO_c_elmt_ENO_c_Km2PGA(unit "") = 0.054 "";
    parameter Real elmt_ENO_c_elmt_ENO_c_KmPEP(unit "") = 0.24 "";
    parameter Real elmt_ENO_c_elmt_ENO_c_Keq(unit "") = 4.17 "";
    parameter Real elmt_ENO_c_elmt_ENO_c_Vmax(unit "") = 598.0 "";
    Real elmt_product23 "";
    Real elmt_reactant22 "";
    Real elmt_TPI_g(unit = "") "TPI_g";
    parameter Real elmt_TPI_g_elmt_TPI_g_KmGA3P(unit "") = 0.25 "";
    parameter Real elmt_TPI_g_elmt_TPI_g_Keq(unit "") = 0.046 "";
    parameter Real elmt_TPI_g_elmt_TPI_g_KmDHAP(unit "") = 1.2 "";
    parameter Real elmt_TPI_g_elmt_TPI_g_Vmax(unit "") = 999.3 "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_G6PDH_c(unit = "") "G6PDH_c";
    parameter Real elmt_G6PDH_c_elmt_G6PDH_c_KmGlc6P(unit "") = 0.058 "";
    parameter Real elmt_G6PDH_c_elmt_G6PDH_c_Vmax(unit "") = 8.4 "";
    parameter Real elmt_G6PDH_c_elmt_G6PDH_c_Keq(unit "") = 5.02 "";
    parameter Real elmt_G6PDH_c_elmt_G6PDH_c_Km6PGL(unit "") = 0.04 "";
    parameter Real elmt_G6PDH_c_elmt_G6PDH_c_KmNADPH(unit "") = 1.0E-4 "";
    parameter Real elmt_G6PDH_c_elmt_G6PDH_c_KmNADP(unit "") = 0.0094 "";
    Real elmt_reactant18 "";
    Real elmt_reactant19 "";
    Real elmt_product21 "";
    Real elmt_product20 "";
    Real elmt_HXK_c(unit = "") "HXK_c";
    parameter Real elmt_HXK_c_elmt_HXK_c_Keq(unit "") = 759.0 "";
    parameter Real elmt_HXK_c_elmt_HXK_c_KmGlc(unit "") = 0.1 "";
    parameter Real elmt_HXK_c_elmt_HXK_c_KmATP(unit "") = 0.116 "";
    parameter Real elmt_HXK_c_elmt_HXK_c_KmADP(unit "") = 0.126 "";
    parameter Real elmt_HXK_c_elmt_HXK_c_KmGlc6P(unit "") = 2.7 "";
    parameter Real elmt_HXK_c_elmt_HXK_c_Vmax(unit "") = 154.32 "";
    Real elmt_product34 "";
    Real elmt_product35 "";
    Real elmt_reactant32 "";
    Real elmt_reactant33 "";
    Real elmt_TR_c(unit = "") "TR_c";
    parameter Real elmt_TR_c_elmt_TR_c_KmNADPH(unit "") = 7.7E-4 "";
    parameter Real elmt_TR_c_elmt_TR_c_KmTS2(unit "") = 0.0069 "";
    parameter Real elmt_TR_c_elmt_TR_c_KmTSH2(unit "") = 0.0018 "";
    parameter Real elmt_TR_c_elmt_TR_c_Keq(unit "") = 434.0 "";
    parameter Real elmt_TR_c_elmt_TR_c_KmNADP(unit "") = 0.081 "";
    parameter Real elmt_TR_c_elmt_TR_c_Vmax(unit "") = 252.0 "";
    Real elmt_product83 "";
    Real elmt_product82 "";
    Real elmt_reactant80 "";
    Real elmt_reactant81 "";
    Real elmt_G6PDH_g(unit = "") "G6PDH_g";
    parameter Real elmt_G6PDH_g_elmt_G6PDH_g_KmGlc6P(unit "") = 0.058 "";
    parameter Real elmt_G6PDH_g_elmt_G6PDH_g_Km6PGL(unit "") = 0.04 "";
    parameter Real elmt_G6PDH_g_elmt_G6PDH_g_Vmax(unit "") = 8.4 "";
    parameter Real elmt_G6PDH_g_elmt_G6PDH_g_KmNADPH(unit "") = 1.0E-4 "";
    parameter Real elmt_G6PDH_g_elmt_G6PDH_g_Keq(unit "") = 5.02 "";
    parameter Real elmt_G6PDH_g_elmt_G6PDH_g_KmNADP(unit "") = 0.0094 "";
    Real elmt_product12 "";
    Real elmt_product13 "";
    Real elmt_reactant10 "";
    Real elmt_reactant11 "";
    Real elmt_PYK_c(unit = "") "PYK_c";
    parameter Real elmt_PYK_c_elmt_PYK_c_KmPyr(unit "") = 50.0 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KmPEP(unit "") = 0.34 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_Vmax(unit "") = 1020.0 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_Keq(unit "") = 10800.0 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_n(unit "") = 2.5 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KmADP(unit "") = 0.114 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KmATP(unit "") = 15.0 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KiATP(unit "") = 0.57 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KiADP(unit "") = 0.64 "";
    Real elmt_reactant2 "";
    Real elmt_reactant3 "";
    Real elmt_product5 "";
    Real elmt_product4 "";
    Real elmt_G3PDH_g(unit = "") "G3PDH_g";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_Vmax(unit "") = 465.0 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_KmGly3P(unit "") = 2.0 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_Keq(unit "") = 17085.0 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_KmDHAP(unit "") = 0.1 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_KmNADH(unit "") = 0.01 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_KmNAD(unit "") = 0.4 "";
    Real elmt_reactant88 "";
    Real elmt_product91 "";
    Real elmt_reactant89 "";
    Real elmt_product90 "";
    Real elmt_ALD_g(unit = "") "ALD_g";
    parameter Real elmt_ALD_g_elmt_ALD_g_KmDHAP(unit "") = 0.015 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KiATP(unit "") = 0.68 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KiADP(unit "") = 1.51 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KmFru16BP(unit "") = 0.009 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KiAMP(unit "") = 3.65 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KiGA3P(unit "") = 0.098 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_Keq(unit "") = 0.084 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_Vmax(unit "") = 560.0 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KmGA3P(unit "") = 0.067 "";
    Real elmt_product99 "";
    Real elmt_product100 "";
    Real elmt_reactant98 "";
    Real elmt_NADPHu_c(unit = "") "NADPHu_c";
    parameter Real elmt_NADPHu_c_elmt_NADPHu_c_k(unit "") = 2.0 "";
    Real elmt_reactant30 "";
    Real elmt_product31 "";
    Real elmt_AK_g(unit = "") "AK_g";
    parameter Real elmt_AK_g_elmt_AK_g_k1(unit "") = 480.0 "";
    parameter Real elmt_AK_g_elmt_AK_g_k2(unit "") = 1000.0 "";
    Real elmt_reactant50 "";
    Real elmt_product52 "";
    Real elmt_product51 "";
    Real elmt_ATPT_g(unit = "") "ATPT_g";
    parameter Real elmt_ATPT_g_elmt_ATPT_g_Vmax(unit "") = 1.5 "";
    parameter Real elmt_ATPT_g_elmt_ATPT_g_Keq(unit "") = 1.0 "";
    parameter Real elmt_ATPT_g_elmt_ATPT_g_KmADP(unit "") = 0.02 "";
    parameter Real elmt_ATPT_g_elmt_ATPT_g_KmATP(unit "") = 0.02 "";
    Real elmt_product62 "";
    Real elmt_product61 "";
    Real elmt_reactant60 "";
    Real elmt_reactant59 "";
    Real elmt_PyrT_c(unit = "") "PyrT_c";
    parameter Real elmt_PyrT_c_elmt_PyrT_c_Vmax(unit "") = 230.0 "";
    parameter Real elmt_PyrT_c_elmt_PyrT_c_KmPyr(unit "") = 1.96 "";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_PPI_g(unit = "") "PPI_g";
    parameter Real elmt_PPI_g_elmt_PPI_g_Keq(unit "") = 5.6 "";
    parameter Real elmt_PPI_g_elmt_PPI_g_KmRul5P(unit "") = 1.4 "";
    parameter Real elmt_PPI_g_elmt_PPI_g_Vmax(unit "") = 72.0 "";
    parameter Real elmt_PPI_g_elmt_PPI_g_KmRib5P(unit "") = 4.0 "";
    Real elmt_reactant72 "";
    Real elmt_product73 "";
    Real elmt_HXK_g(unit = "") "HXK_g";
    parameter Real elmt_HXK_g_elmt_HXK_g_Keq(unit "") = 759.0 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_KmATP(unit "") = 0.116 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_KmADP(unit "") = 0.126 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_KmGlc(unit "") = 0.1 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_KmGlc6P(unit "") = 2.7 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_Vmax(unit "") = 1774.68 "";
    Real elmt_reactant25 "";
    Real elmt_product27 "";
    Real elmt_product26 "";
    Real elmt_reactant24 "";
    Real elmt_NADPHu_g(unit = "") "NADPHu_g";
    parameter Real elmt_NADPHu_g_elmt_NADPHu_g_k(unit "") = 2.0 "";
    Real elmt_reactant36 "";
    Real elmt_product37 "";
    Real elmt__6PGDH_g(unit = "") "_6PGDH_g";
    parameter Real elmt__6PGDH_g_elmt__6PGDH_g_KmNADPH(unit "") = 6.0E-4 "";
    parameter Real elmt__6PGDH_g_elmt__6PGDH_g_Keq(unit "") = 47.0 "";
    parameter Real elmt__6PGDH_g_elmt__6PGDH_g_Vmax(unit "") = 10.6 "";
    parameter Real elmt__6PGDH_g_elmt__6PGDH_g_Km6PG(unit "") = 0.0035 "";
    parameter Real elmt__6PGDH_g_elmt__6PGDH_g_KmNADP(unit "") = 0.001 "";
    parameter Real elmt__6PGDH_g_elmt__6PGDH_g_KmRul5P(unit "") = 0.03 "";
    Real elmt_product45 "";
    Real elmt_product47 "";
    Real elmt_product46 "";
    Real elmt_reactant43 "";
    Real elmt_reactant44 "";
    Real elmt__6PGDH_c(unit = "") "_6PGDH_c";
    parameter Real elmt__6PGDH_c_elmt__6PGDH_c_Keq(unit "") = 47.0 "";
    parameter Real elmt__6PGDH_c_elmt__6PGDH_c_Vmax(unit "") = 10.6 "";
    parameter Real elmt__6PGDH_c_elmt__6PGDH_c_KmNADP(unit "") = 0.001 "";
    parameter Real elmt__6PGDH_c_elmt__6PGDH_c_KmNADPH(unit "") = 6.0E-4 "";
    parameter Real elmt__6PGDH_c_elmt__6PGDH_c_Km6PG(unit "") = 0.0035 "";
    parameter Real elmt__6PGDH_c_elmt__6PGDH_c_KmRul5P(unit "") = 0.03 "";
    Real elmt_product67 "";
    Real elmt_product69 "";
    Real elmt_product68 "";
    Real elmt_reactant65 "";
    Real elmt_reactant66 "";
    Real elmt_PFK_g(unit = "") "PFK_g";
    parameter Real elmt_PFK_g_elmt_PFK_g_Vmax(unit "") = 1708.0 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_KmFru6P(unit "") = 0.999 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_KsATP(unit "") = 0.0393 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_Ki2(unit "") = 10.7 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_Ki1(unit "") = 15.8 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_KmATP(unit "") = 0.0648 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_KmADP(unit "") = 1.0 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_Keq(unit "") = 1035.0 "";
    Real elmt_product9 "";
    Real elmt_product8 "";
    Real elmt_reactant6 "";
    Real elmt_reactant7 "";
    Real elmt__3PGAT_g(unit = "") "_3PGAT_g";
    parameter Real elmt__3PGAT_g_elmt__3PGAT_g_k(unit "") = 250.0 "";
    Real elmt_reactant28 "";
    Real elmt_product29 "";


    initial equation
        elmt_product73 = 1.0;
        elmt_reactant41 = 1.0;
        elmt_product71 = 1.0;
        elmt_product77 = 1.0;
        elmt_product75 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_reactant43 = 1.0;
        elmt_reactant44 = 1.0;
        elmt_product69 = 1.0;
        elmt_product68 = 1.0;
        elmt_reactant50 = 2.0;
        elmt_product83 = 1.0;
        elmt_reactant53 = 1.0;
        elmt_product82 = 1.0;
        elmt_product87 = 1.0;
        elmt_product86 = 1.0;
        elmt_reactant59 = 1.0;
        elmt_reactant55 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_product104 = 1.0;
        elmt_product100 = 1.0;
        elmt_product79 = 1.0;
        elmt_product105 = 1.0;
        elmt_product107 = 1.0;
        elmt_product96 = 1.0;
        elmt_product93 = 1.0;
        elmt_product12 = 1.0;
        elmt_product99 = 1.0;
        elmt_product97 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_product91 = 1.0;
        elmt_product90 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product9 = 1.0;
        elmt_product8 = 1.0;
        elmt_reactant30 = 1.0;
        elmt_product23 = 1.0;
        elmt_product21 = 1.0;
        elmt_product20 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant36 = 1.0;
        elmt_reactant38 = 2.0;
        elmt_reactant32 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant33 = 1.0;
        elmt_product4 = 1.0;
        elmt_product15 = 1.0;
        elmt_reactant106 = 1.0;
        elmt_product13 = 1.0;
        elmt_reactant103 = 1.0;
        elmt_reactant102 = 1.0;
        elmt_reactant101 = 1.0;
        elmt_product17 = 1.0;
        elmt_reactant84 = 1.0;
        elmt_reactant85 = 1.0;
        elmt_product34 = 1.0;
        elmt_reactant80 = 1.0;
        elmt_reactant81 = 1.0;
        elmt_product31 = 1.0;
        elmt_reactant88 = 1.0;
        elmt_reactant89 = 1.0;
        elmt_product27 = 1.0;
        elmt_product26 = 1.0;
        elmt_product29 = 1.0;
        elmt_reactant94 = 1.0;
        elmt_reactant95 = 1.0;
        elmt_product40 = 1.0;
        elmt_product45 = 1.0;
        elmt_reactant92 = 1.0;
        elmt_product42 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant98 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_product37 = 1.0;
        elmt_product35 = 1.0;
        elmt_product39 = 1.0;
        elmt_product52 = 1.0;
        elmt_product51 = 1.0;
        elmt_reactant63 = 1.0;
        elmt_product54 = 1.0;
        elmt_reactant60 = 1.0;
        elmt_reactant65 = 1.0;
        elmt_reactant66 = 1.0;
        elmt_product49 = 1.0;
        elmt_product47 = 1.0;
        elmt_product46 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_reactant72 = 1.0;
        elmt_product62 = 1.0;
        elmt_reactant74 = 1.0;
        elmt_product61 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_product67 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_reactant70 = 1.0;
        elmt_product64 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_reactant76 = 1.0;
        elmt_reactant78 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product58 = 1.0;
        elmt_product57 = 1.0;


    equation
        elmt_PGAM_c = (((elmt_PGAM_c_elmt_PGAM_c_Vmax * elmt__3PGA_c * (1.0 - (elmt__2PGA_c / (elmt_PGAM_c_elmt_PGAM_c_Keq * elmt__3PGA_c)))) / (elmt_PGAM_c_elmt_PGAM_c_Km3PGA * (1.0 + (elmt__3PGA_c / elmt_PGAM_c_elmt_PGAM_c_Km3PGA) + (elmt__2PGA_c / elmt_PGAM_c_elmt_PGAM_c_Km2PGA)))));
        elmt_GAPDH_g = (((elmt_GAPDH_g_elmt_GAPDH_g_Vmax * elmt_GA3P_g * elmt_NAD_g * (1.0 - ((elmt__13BPGA_g * elmt_NADH_g) / (elmt_GAPDH_g_elmt_GAPDH_g_Keq * elmt_GA3P_g * elmt_NAD_g)))) / (elmt_GAPDH_g_elmt_GAPDH_g_KmGA3P * elmt_GAPDH_g_elmt_GAPDH_g_KmNAD * (1.0 + (elmt_GA3P_g / elmt_GAPDH_g_elmt_GAPDH_g_KmGA3P) + (elmt__13BPGA_g / elmt_GAPDH_g_elmt_GAPDH_g_Km13BPGA)) * (1.0 + (elmt_NAD_g / elmt_GAPDH_g_elmt_GAPDH_g_KmNAD) + (elmt_NADH_g / elmt_GAPDH_g_elmt_GAPDH_g_KmNADH)))));
        elmt_PPI_c = (((elmt_PPI_c_elmt_PPI_c_Vmax * elmt_Rul5P_c * (1.0 - (elmt_Rib5P_c / (elmt_PPI_c_elmt_PPI_c_Keq * elmt_Rul5P_c)))) / (elmt_PPI_c_elmt_PPI_c_KmRul5P * (1.0 + (elmt_Rul5P_c / elmt_PPI_c_elmt_PPI_c_KmRul5P) + (elmt_Rib5P_c / elmt_PPI_c_elmt_PPI_c_KmRib5P)))));
        elmt_GK_g = (((elmt_GK_g_elmt_GK_g_Vmax * elmt_Gly3P_g * elmt_ADP_g * (1.0 - ((elmt_Gly_e * elmt_ATP_g) / (elmt_GK_g_elmt_GK_g_Keq * elmt_Gly3P_g * elmt_ADP_g)))) / (elmt_GK_g_elmt_GK_g_KmGly3P * elmt_GK_g_elmt_GK_g_KmADP * (1.0 + (elmt_Gly3P_g / elmt_GK_g_elmt_GK_g_KmGly3P) + (elmt_Gly_e / elmt_GK_g_elmt_GK_g_KmGly)) * (1.0 + (elmt_ADP_g / elmt_GK_g_elmt_GK_g_KmADP) + (elmt_ATP_g / elmt_GK_g_elmt_GK_g_KmATP)))));
        elmt_GDA_g = ((elmt_Gly3P_g * elmt_GDA_g_elmt_GDA_g_k * elmt_DHAP_c) - (elmt_Gly3P_c * elmt_GDA_g_elmt_GDA_g_k * elmt_DHAP_g));
        elmt_GPO_c = (((elmt_GPO_c_elmt_GPO_c_Vmax * elmt_Gly3P_c) / (elmt_GPO_c_elmt_GPO_c_KmGly3P * (1.0 + (elmt_Gly3P_c / elmt_GPO_c_elmt_GPO_c_KmGly3P)))));
        elmt_AK_c = (((elmt_AK_c_elmt_AK_c_k1 * Functions.pow(elmt_ADP_c, 2.0)) - (elmt_AMP_c * elmt_ATP_c * elmt_AK_c_elmt_AK_c_k2)));
        elmt_ATPu_c = ((elmt_ATPu_c_elmt_ATPu_c_k * elmt_ATP_c) / elmt_ADP_c);
        elmt_GlcT_c = ((elmt_GlcT_c_elmt_GlcT_c_Vmax * (elmt_Glc_e - elmt_Glc_c)) / (elmt_GlcT_c_elmt_GlcT_c_KmGlc + elmt_Glc_e + elmt_Glc_c + ((elmt_GlcT_c_elmt_GlcT_c_alpha * elmt_Glc_e * elmt_Glc_c) / elmt_GlcT_c_elmt_GlcT_c_KmGlc)));
        elmt_GlcT_g = (((elmt_GlcT_g_elmt_GlcT_g_k1 * elmt_Glc_c) - (elmt_GlcT_g_elmt_GlcT_g_k2 * elmt_Glc_g)));
        elmt_PGL_c = ((elmt_PGL_c_elmt_PGL_c_k * elmt_cytosol * (elmt__6PGL_c - (elmt__6PG_c / elmt_PGL_c_elmt_PGL_c_Keq))) + (((elmt_PGL_c_elmt_PGL_c_Vmax * elmt__6PGL_c * (1.0 - (elmt__6PG_c / (elmt_PGL_c_elmt_PGL_c_Keq * elmt__6PGL_c)))) / (elmt_PGL_c_elmt_PGL_c_Km6PGL * (1.0 + (elmt__6PGL_c / elmt_PGL_c_elmt_PGL_c_Km6PGL) + (elmt__6PG_c / elmt_PGL_c_elmt_PGL_c_Km6PG))))));
        elmt_PGI_g = ((elmt_PGI_g_elmt_PGI_g_Vmax * elmt_Glc6P_g * (1.0 - (elmt_Fru6P_g / (elmt_PGI_g_elmt_PGI_g_Keq * elmt_Glc6P_g)))) / (elmt_PGI_g_elmt_PGI_g_KmGlc6P * (1.0 + (elmt_Glc6P_g / elmt_PGI_g_elmt_PGI_g_KmGlc6P) + (elmt_Fru6P_g / elmt_PGI_g_elmt_PGI_g_KmFru6P) + (elmt__6PG_g / elmt_PGI_g_elmt_PGI_g_Ki6PG))));
        elmt_PGK_g = (((elmt_PGK_g_elmt_PGK_g_Vmax * elmt__13BPGA_g * elmt_ADP_g * (1.0 - ((elmt__3PGA_g * elmt_ATP_g) / (elmt_PGK_g_elmt_PGK_g_Keq * elmt__13BPGA_g * elmt_ADP_g)))) / (elmt_PGK_g_elmt_PGK_g_Km13BPGA * elmt_PGK_g_elmt_PGK_g_KmADP * (1.0 + (elmt__13BPGA_g / elmt_PGK_g_elmt_PGK_g_Km13BPGA) + (elmt__3PGA_g / elmt_PGK_g_elmt_PGK_g_Km3PGA)) * (1.0 + (elmt_ADP_g / elmt_PGK_g_elmt_PGK_g_KmADP) + (elmt_ATP_g / elmt_PGK_g_elmt_PGK_g_KmATP)))));
        elmt_G6PP_c = (((elmt_G6PP_c_elmt_G6PP_c_Vmax * elmt_Glc6P_c * (1.0 - (elmt_Glc_c / (elmt_G6PP_c_elmt_G6PP_c_Keq * elmt_Glc6P_c)))) / (elmt_G6PP_c_elmt_G6PP_c_KmGlc6P * (1.0 + (elmt_Glc6P_c / elmt_G6PP_c_elmt_G6PP_c_KmGlc6P) + (elmt_Glc_c / elmt_G6PP_c_elmt_G6PP_c_KmGlc)))));
        elmt_TOX_c = ((elmt_TOX_c_elmt_TOX_c_k * elmt_TSH2_c));
        elmt_PGL_g = ((elmt_glycosome * elmt_PGL_g_elmt_PGL_g_k * (elmt__6PGL_g - (elmt__6PG_g / elmt_PGL_g_elmt_PGL_g_Keq))) + (((elmt_PGL_g_elmt_PGL_g_Vmax * elmt__6PGL_g * (1.0 - (elmt__6PG_g / (elmt_PGL_g_elmt_PGL_g_Keq * elmt__6PGL_g)))) / (elmt_PGL_g_elmt_PGL_g_Km6PGL * (1.0 + (elmt__6PGL_g / elmt_PGL_g_elmt_PGL_g_Km6PGL) + (elmt__6PG_g / elmt_PGL_g_elmt_PGL_g_Km6PG))))));
        elmt_ENO_c = (((elmt_ENO_c_elmt_ENO_c_Vmax * elmt__2PGA_c * (1.0 - (elmt_PEP_c / (elmt_ENO_c_elmt_ENO_c_Keq * elmt__2PGA_c)))) / (elmt_ENO_c_elmt_ENO_c_Km2PGA * (1.0 + (elmt__2PGA_c / elmt_ENO_c_elmt_ENO_c_Km2PGA) + (elmt_PEP_c / elmt_ENO_c_elmt_ENO_c_KmPEP)))));
        elmt_TPI_g = (((elmt_TPI_g_elmt_TPI_g_Vmax * elmt_DHAP_g * (1.0 - (elmt_GA3P_g / (elmt_TPI_g_elmt_TPI_g_Keq * elmt_DHAP_g)))) / (elmt_TPI_g_elmt_TPI_g_KmDHAP * (1.0 + (elmt_DHAP_g / elmt_TPI_g_elmt_TPI_g_KmDHAP) + (elmt_GA3P_g / elmt_TPI_g_elmt_TPI_g_KmGA3P)))));
        elmt_G6PDH_c = (((elmt_G6PDH_c_elmt_G6PDH_c_Vmax * elmt_Glc6P_c * elmt_NADP_c * (1.0 - ((elmt__6PGL_c * elmt_NADPH_c) / (elmt_G6PDH_c_elmt_G6PDH_c_Keq * elmt_Glc6P_c * elmt_NADP_c)))) / (elmt_G6PDH_c_elmt_G6PDH_c_KmGlc6P * elmt_G6PDH_c_elmt_G6PDH_c_KmNADP * (1.0 + (elmt_Glc6P_c / elmt_G6PDH_c_elmt_G6PDH_c_KmGlc6P) + (elmt__6PGL_c / elmt_G6PDH_c_elmt_G6PDH_c_Km6PGL)) * (1.0 + (elmt_NADP_c / elmt_G6PDH_c_elmt_G6PDH_c_KmNADP) + (elmt_NADPH_c / elmt_G6PDH_c_elmt_G6PDH_c_KmNADPH)))));
        elmt_HXK_c = (((elmt_HXK_c_elmt_HXK_c_Vmax * elmt_Glc_c * elmt_ATP_c * (1.0 - ((elmt_Glc6P_c * elmt_ADP_c) / (elmt_HXK_c_elmt_HXK_c_Keq * elmt_Glc_c * elmt_ATP_c)))) / (elmt_HXK_c_elmt_HXK_c_KmGlc * elmt_HXK_c_elmt_HXK_c_KmATP * (1.0 + (elmt_Glc_c / elmt_HXK_c_elmt_HXK_c_KmGlc) + (elmt_Glc6P_c / elmt_HXK_c_elmt_HXK_c_KmGlc6P)) * (1.0 + (elmt_ATP_c / elmt_HXK_c_elmt_HXK_c_KmATP) + (elmt_ADP_c / elmt_HXK_c_elmt_HXK_c_KmADP)))));
        elmt_TR_c = (((elmt_TR_c_elmt_TR_c_Vmax * elmt_TS2_c * elmt_NADPH_c * (1.0 - ((elmt_TSH2_c * elmt_NADP_c) / (elmt_TR_c_elmt_TR_c_Keq * elmt_TS2_c * elmt_NADPH_c)))) / (elmt_TR_c_elmt_TR_c_KmTS2 * elmt_TR_c_elmt_TR_c_KmNADPH * (1.0 + (elmt_TS2_c / elmt_TR_c_elmt_TR_c_KmTS2) + (elmt_TSH2_c / elmt_TR_c_elmt_TR_c_KmTSH2)) * (1.0 + (elmt_NADPH_c / elmt_TR_c_elmt_TR_c_KmNADPH) + (elmt_NADP_c / elmt_TR_c_elmt_TR_c_KmNADP)))));
        elmt_G6PDH_g = (((elmt_G6PDH_g_elmt_G6PDH_g_Vmax * elmt_Glc6P_g * elmt_NADP_g * (1.0 - ((elmt__6PGL_g * elmt_NADPH_g) / (elmt_G6PDH_g_elmt_G6PDH_g_Keq * elmt_Glc6P_g * elmt_NADP_g)))) / (elmt_G6PDH_g_elmt_G6PDH_g_KmGlc6P * elmt_G6PDH_g_elmt_G6PDH_g_KmNADP * (1.0 + (elmt_Glc6P_g / elmt_G6PDH_g_elmt_G6PDH_g_KmGlc6P) + (elmt__6PGL_g / elmt_G6PDH_g_elmt_G6PDH_g_Km6PGL)) * (1.0 + (elmt_NADP_g / elmt_G6PDH_g_elmt_G6PDH_g_KmNADP) + (elmt_NADPH_g / elmt_G6PDH_g_elmt_G6PDH_g_KmNADPH)))));
        elmt_PYK_c = ((elmt_PYK_c_elmt_PYK_c_Vmax * elmt_ADP_c * (1.0 - ((elmt_Pyr_c * elmt_ATP_c) / (elmt_PYK_c_elmt_PYK_c_Keq * elmt_PEP_c * elmt_ADP_c))) * Functions.pow((elmt_PEP_c / (elmt_PYK_c_elmt_PYK_c_KmPEP * (1.0 + (elmt_ADP_c / elmt_PYK_c_elmt_PYK_c_KiADP) + (elmt_ATP_c / elmt_PYK_c_elmt_PYK_c_KiATP)))), elmt_PYK_c_elmt_PYK_c_n)) / (elmt_PYK_c_elmt_PYK_c_KmADP * (1.0 + Functions.pow((elmt_PEP_c / (elmt_PYK_c_elmt_PYK_c_KmPEP * (1.0 + (elmt_ADP_c / elmt_PYK_c_elmt_PYK_c_KiADP) + (elmt_ATP_c / elmt_PYK_c_elmt_PYK_c_KiATP)))), elmt_PYK_c_elmt_PYK_c_n) + (elmt_Pyr_c / elmt_PYK_c_elmt_PYK_c_KmPyr)) * (1.0 + (elmt_ADP_c / elmt_PYK_c_elmt_PYK_c_KmADP) + (elmt_ATP_c / elmt_PYK_c_elmt_PYK_c_KmATP))));
        elmt_G3PDH_g = (((elmt_G3PDH_g_elmt_G3PDH_g_Vmax * elmt_DHAP_g * elmt_NADH_g * (1.0 - ((elmt_Gly3P_g * elmt_NAD_g) / (elmt_G3PDH_g_elmt_G3PDH_g_Keq * elmt_DHAP_g * elmt_NADH_g)))) / (elmt_G3PDH_g_elmt_G3PDH_g_KmDHAP * elmt_G3PDH_g_elmt_G3PDH_g_KmNADH * (1.0 + (elmt_DHAP_g / elmt_G3PDH_g_elmt_G3PDH_g_KmDHAP) + (elmt_Gly3P_g / elmt_G3PDH_g_elmt_G3PDH_g_KmGly3P)) * (1.0 + (elmt_NADH_g / elmt_G3PDH_g_elmt_G3PDH_g_KmNADH) + (elmt_NAD_g / elmt_G3PDH_g_elmt_G3PDH_g_KmNAD)))));
        elmt_ALD_g = ((elmt_ALD_g_elmt_ALD_g_Vmax * elmt_Fru16BP_g * (1.0 - ((elmt_GA3P_g * elmt_DHAP_g) / (elmt_Fru16BP_g * elmt_ALD_g_elmt_ALD_g_Keq)))) / (elmt_ALD_g_elmt_ALD_g_KmFru16BP * (1.0 + (elmt_ATP_g / elmt_ALD_g_elmt_ALD_g_KiATP) + (elmt_ADP_g / elmt_ALD_g_elmt_ALD_g_KiADP) + (elmt_AMP_g / elmt_ALD_g_elmt_ALD_g_KiAMP)) * (1.0 + (elmt_GA3P_g / elmt_ALD_g_elmt_ALD_g_KmGA3P) + (elmt_DHAP_g / elmt_ALD_g_elmt_ALD_g_KmDHAP) + (elmt_Fru16BP_g / (elmt_ALD_g_elmt_ALD_g_KmFru16BP * (1.0 + (elmt_ATP_g / elmt_ALD_g_elmt_ALD_g_KiATP) + (elmt_ADP_g / elmt_ALD_g_elmt_ALD_g_KiADP) + (elmt_AMP_g / elmt_ALD_g_elmt_ALD_g_KiAMP)))) + ((elmt_GA3P_g * elmt_DHAP_g) / (elmt_ALD_g_elmt_ALD_g_KmGA3P * elmt_ALD_g_elmt_ALD_g_KmDHAP)) + ((elmt_Fru16BP_g * elmt_GA3P_g) / (elmt_ALD_g_elmt_ALD_g_KmFru16BP * elmt_ALD_g_elmt_ALD_g_KiGA3P * (1.0 + (elmt_ATP_g / elmt_ALD_g_elmt_ALD_g_KiATP) + (elmt_ADP_g / elmt_ALD_g_elmt_ALD_g_KiADP) + (elmt_AMP_g / elmt_ALD_g_elmt_ALD_g_KiAMP)))))));
        elmt_NADPHu_c = ((elmt_NADPHu_c_elmt_NADPHu_c_k * elmt_NADPH_c));
        elmt_AK_g = (((elmt_AK_g_elmt_AK_g_k1 * Functions.pow(elmt_ADP_g, 2.0)) - (elmt_AMP_g * elmt_ATP_g * elmt_AK_g_elmt_AK_g_k2)));
        elmt_ATPT_g = (((elmt_ATPT_g_elmt_ATPT_g_Vmax * elmt_ADP_g * elmt_ATP_c * (1.0 - ((elmt_ADP_c * elmt_ATP_g) / (elmt_ATPT_g_elmt_ATPT_g_Keq * elmt_ADP_g * elmt_ATP_c)))) / (elmt_ATPT_g_elmt_ATPT_g_KmADP * elmt_ATPT_g_elmt_ATPT_g_KmATP * (1.0 + (elmt_ADP_g / elmt_ATPT_g_elmt_ATPT_g_KmADP) + (elmt_ADP_c / elmt_ATPT_g_elmt_ATPT_g_KmADP)) * (1.0 + (elmt_ATP_c / elmt_ATPT_g_elmt_ATPT_g_KmATP) + (elmt_ATP_g / elmt_ATPT_g_elmt_ATPT_g_KmATP)))));
        elmt_PyrT_c = (((elmt_PyrT_c_elmt_PyrT_c_Vmax * elmt_Pyr_c) / (elmt_PyrT_c_elmt_PyrT_c_KmPyr * (1.0 + (elmt_Pyr_c / elmt_PyrT_c_elmt_PyrT_c_KmPyr)))));
        elmt_PPI_g = (((elmt_PPI_g_elmt_PPI_g_Vmax * elmt_Rul5P_g * (1.0 - (elmt_Rib5P_g / (elmt_PPI_g_elmt_PPI_g_Keq * elmt_Rul5P_g)))) / (elmt_PPI_g_elmt_PPI_g_KmRul5P * (1.0 + (elmt_Rul5P_g / elmt_PPI_g_elmt_PPI_g_KmRul5P) + (elmt_Rib5P_g / elmt_PPI_g_elmt_PPI_g_KmRib5P)))));
        elmt_HXK_g = (((elmt_HXK_g_elmt_HXK_g_Vmax * elmt_Glc_g * elmt_ATP_g * (1.0 - ((elmt_Glc6P_g * elmt_ADP_g) / (elmt_HXK_g_elmt_HXK_g_Keq * elmt_Glc_g * elmt_ATP_g)))) / (elmt_HXK_g_elmt_HXK_g_KmGlc * elmt_HXK_g_elmt_HXK_g_KmATP * (1.0 + (elmt_Glc_g / elmt_HXK_g_elmt_HXK_g_KmGlc) + (elmt_Glc6P_g / elmt_HXK_g_elmt_HXK_g_KmGlc6P)) * (1.0 + (elmt_ATP_g / elmt_HXK_g_elmt_HXK_g_KmATP) + (elmt_ADP_g / elmt_HXK_g_elmt_HXK_g_KmADP)))));
        elmt_NADPHu_g = ((elmt_NADPHu_g_elmt_NADPHu_g_k * elmt_NADPH_g));
        elmt__6PGDH_g = (((elmt__6PGDH_g_elmt__6PGDH_g_Vmax * elmt__6PG_g * elmt_NADP_g * (1.0 - ((elmt_Rul5P_g * elmt_NADPH_g) / (elmt__6PGDH_g_elmt__6PGDH_g_Keq * elmt__6PG_g * elmt_NADP_g)))) / (elmt__6PGDH_g_elmt__6PGDH_g_Km6PG * elmt__6PGDH_g_elmt__6PGDH_g_KmNADP * (1.0 + (elmt__6PG_g / elmt__6PGDH_g_elmt__6PGDH_g_Km6PG) + (elmt_Rul5P_g / elmt__6PGDH_g_elmt__6PGDH_g_KmRul5P)) * (1.0 + (elmt_NADP_g / elmt__6PGDH_g_elmt__6PGDH_g_KmNADP) + (elmt_NADPH_g / elmt__6PGDH_g_elmt__6PGDH_g_KmNADPH)))));
        elmt__6PGDH_c = (((elmt__6PGDH_c_elmt__6PGDH_c_Vmax * elmt__6PG_c * elmt_NADP_c * (1.0 - ((elmt_Rul5P_c * elmt_NADPH_c) / (elmt__6PGDH_c_elmt__6PGDH_c_Keq * elmt__6PG_c * elmt_NADP_c)))) / (elmt__6PGDH_c_elmt__6PGDH_c_Km6PG * elmt__6PGDH_c_elmt__6PGDH_c_KmNADP * (1.0 + (elmt__6PG_c / elmt__6PGDH_c_elmt__6PGDH_c_Km6PG) + (elmt_Rul5P_c / elmt__6PGDH_c_elmt__6PGDH_c_KmRul5P)) * (1.0 + (elmt_NADP_c / elmt__6PGDH_c_elmt__6PGDH_c_KmNADP) + (elmt_NADPH_c / elmt__6PGDH_c_elmt__6PGDH_c_KmNADPH)))));
        elmt_PFK_g = ((elmt_PFK_g_elmt_PFK_g_Vmax * elmt_PFK_g_elmt_PFK_g_Ki1 * elmt_Fru6P_g * elmt_ATP_g * (1.0 - ((elmt_Fru16BP_g * elmt_ADP_g) / (elmt_PFK_g_elmt_PFK_g_Keq * elmt_Fru6P_g * elmt_ATP_g)))) / (elmt_PFK_g_elmt_PFK_g_KmFru6P * elmt_PFK_g_elmt_PFK_g_KmATP * (elmt_Fru16BP_g + elmt_PFK_g_elmt_PFK_g_Ki1) * ((elmt_PFK_g_elmt_PFK_g_KsATP / elmt_PFK_g_elmt_PFK_g_KmATP) + (elmt_Fru6P_g / elmt_PFK_g_elmt_PFK_g_KmFru6P) + (elmt_ATP_g / elmt_PFK_g_elmt_PFK_g_KmATP) + (elmt_ADP_g / elmt_PFK_g_elmt_PFK_g_KmADP) + ((elmt_Fru16BP_g * elmt_ADP_g) / (elmt_PFK_g_elmt_PFK_g_KmADP * elmt_PFK_g_elmt_PFK_g_Ki2)) + ((elmt_Fru6P_g * elmt_ATP_g) / (elmt_PFK_g_elmt_PFK_g_KmFru6P * elmt_PFK_g_elmt_PFK_g_KmATP)))));
        elmt__3PGAT_g = (((elmt__3PGAT_g_elmt__3PGAT_g_k * elmt__3PGA_g) - (elmt__3PGAT_g_elmt__3PGAT_g_k * elmt__3PGA_c)));
        der(elmt_product73) = 0;
        der(elmt_reactant41) = 0;
        der(elmt_product71) = 0;
        der(elmt_product77) = 0;
        der(elmt_product75) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_reactant43) = 0;
        der(elmt_reactant44) = 0;
        der(elmt_product69) = 0;
        der(elmt_product68) = 0;
        der(elmt_reactant50) = 0;
        der(elmt_product83) = 0;
        der(elmt_reactant53) = 0;
        der(elmt_product82) = 0;
        der(elmt_product87) = 0;
        der(elmt_product86) = 0;
        der(elmt_reactant59) = 0;
        der(elmt_reactant55) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_product104) = 0;
        der(elmt_product100) = 0;
        der(elmt_product79) = 0;
        der(elmt_product105) = 0;
        der(elmt_product107) = 0;
        der(elmt_product96) = 0;
        der(elmt_product93) = 0;
        der(elmt_product12) = 0;
        der(elmt_product99) = 0;
        der(elmt_product97) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_product91) = 0;
        der(elmt_product90) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product9) = 0;
        der(elmt_product8) = 0;
        der(elmt_reactant30) = 0;
        der(elmt_product23) = 0;
        der(elmt_product21) = 0;
        der(elmt_product20) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant36) = 0;
        der(elmt_reactant38) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant33) = 0;
        der(elmt_product4) = 0;
        der(elmt_product15) = 0;
        der(elmt_reactant106) = 0;
        der(elmt_product13) = 0;
        der(elmt_reactant103) = 0;
        der(elmt_reactant102) = 0;
        der(elmt_reactant101) = 0;
        der(elmt_product17) = 0;
        der(elmt_reactant84) = 0;
        der(elmt_reactant85) = 0;
        der(elmt_product34) = 0;
        der(elmt_reactant80) = 0;
        der(elmt_reactant81) = 0;
        der(elmt_product31) = 0;
        der(elmt_reactant88) = 0;
        der(elmt_reactant89) = 0;
        der(elmt_product27) = 0;
        der(elmt_product26) = 0;
        der(elmt_product29) = 0;
        der(elmt_reactant94) = 0;
        der(elmt_reactant95) = 0;
        der(elmt_product40) = 0;
        der(elmt_product45) = 0;
        der(elmt_reactant92) = 0;
        der(elmt_product42) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant98) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_product37) = 0;
        der(elmt_product35) = 0;
        der(elmt_product39) = 0;
        der(elmt_product52) = 0;
        der(elmt_product51) = 0;
        der(elmt_reactant63) = 0;
        der(elmt_product54) = 0;
        der(elmt_reactant60) = 0;
        der(elmt_reactant65) = 0;
        der(elmt_reactant66) = 0;
        der(elmt_product49) = 0;
        der(elmt_product47) = 0;
        der(elmt_product46) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_reactant72) = 0;
        der(elmt_product62) = 0;
        der(elmt_reactant74) = 0;
        der(elmt_product61) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_product67) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_reactant70) = 0;
        der(elmt_product64) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_reactant76) = 0;
        der(elmt_reactant78) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product58) = 0;
        der(elmt_product57) = 0;

end Reactions;
