within BIOMD107;
class Parameters

    input Real elmt_dimer_p;
    input Real elmt_p_dimer;
    input Real elmt_cdc25_p;
    input Real elmt_cyclin;
    input Real elmt_wee1_p;
    input Real elmt_p_dimer_p;
    input Real elmt_dimer;
    input Real elmt_UbE_star;

    Real elmt_V25_prime(unit = "") "";
    Real elmt_K_g(unit = "") "";
    Real elmt_K_h(unit = "") "";
    Real elmt_K_e(unit = "") "";
    Real elmt_K_f(unit = "") "";
    Real elmt_total_cdc2(unit = "") "";
    Real elmt_kinh(unit = "") "";
    Real elmt_khPPAse(unit = "") "";
    Real elmt_total_IE(unit = "") "";
    Real elmt_kd_anti_IE(unit = "") "";
    Real elmt_total_wee1(unit = "") "";
    Real elmt_Y15P(unit = "") "";
    Real elmt_V2_double_prime(unit = "") "";
    Real elmt_V25_double_prime(unit = "") "";
    Real elmt_total_cyclin(unit = "") "";
    Real elmt_kbPPase(unit = "") "";
    Real elmt_total_UbE(unit = "") "";
    Real elmt_Vwee_double_prime(unit = "") "";
    Real elmt_V2_prime(unit = "") "";
    Real elmt_k2(unit = "") "";
    Real elmt_k3(unit = "") "";
    Real elmt_ka(unit = "") "";
    Real elmt_k1AA(unit = "") "";
    Real elmt_kcak(unit = "") "";
    Real elmt_kwee(unit = "") "";
    Real elmt_kfPPase(unit = "") "";
    Real elmt_K_c(unit = "") "";
    Real elmt_K_d(unit = "") "";
    Real elmt_k25(unit = "") "";
    Real elmt_K_a(unit = "") "";
    Real elmt_K_b(unit = "") "";
    Real elmt_kg(unit = "") "";
    Real elmt_total_cdc25(unit = "") "";
    Real elmt_ke(unit = "") "";
    Real elmt_Vwee_prime(unit = "") "";
    Real elmt_kc(unit = "") "";


    initial equation
        elmt_V25_prime = 0.1;
        elmt_K_g = 0.01;
        elmt_K_h = 0.01;
        elmt_K_e = 0.3;
        elmt_K_f = 0.3;
        elmt_total_cdc2 = 100.0;
        elmt_kinh = 0.025;
        elmt_khPPAse = 0.087;
        elmt_total_IE = 1.0;
        elmt_kd_anti_IE = 0.095;
        elmt_total_wee1 = 1.0;
        elmt_V2_double_prime = 1.0;
        elmt_V25_double_prime = 2.0;
        elmt_kbPPase = 0.125;
        elmt_total_UbE = 1.0;
        elmt_Vwee_double_prime = 1.0;
        elmt_V2_prime = 0.015;
        elmt_k3 = 0.01;
        elmt_ka = 0.01;
        elmt_k1AA = 1.0;
        elmt_kcak = 0.25;
        elmt_kfPPase = 0.1;
        elmt_K_c = 0.01;
        elmt_K_d = 0.01;
        elmt_K_a = 0.1;
        elmt_K_b = 0.1;
        elmt_kg = 0.0065;
        elmt_total_cdc25 = 1.0;
        elmt_ke = 0.0133;
        elmt_Vwee_prime = 0.1;
        elmt_kc = 0.1;


    equation
        der(elmt_V25_prime) = 0;
        der(elmt_K_g) = 0;
        der(elmt_K_h) = 0;
        der(elmt_K_e) = 0;
        der(elmt_K_f) = 0;
        der(elmt_total_cdc2) = 0;
        der(elmt_kinh) = 0;
        der(elmt_khPPAse) = 0;
        der(elmt_total_IE) = 0;
        der(elmt_kd_anti_IE) = 0;
        der(elmt_total_wee1) = 0;
        elmt_Y15P = (elmt_p_dimer + elmt_p_dimer_p);
        der(elmt_V2_double_prime) = 0;
        der(elmt_V25_double_prime) = 0;
        elmt_total_cyclin = (elmt_cyclin + elmt_dimer + elmt_dimer_p + elmt_p_dimer + elmt_p_dimer_p);
        der(elmt_kbPPase) = 0;
        der(elmt_total_UbE) = 0;
        der(elmt_Vwee_double_prime) = 0;
        der(elmt_V2_prime) = 0;
        elmt_k2 = ((elmt_V2_prime * (elmt_total_UbE - elmt_UbE_star)) + (elmt_V2_double_prime * elmt_UbE_star));
        der(elmt_k3) = 0;
        der(elmt_ka) = 0;
        der(elmt_k1AA) = 0;
        der(elmt_kcak) = 0;
        elmt_kwee = ((elmt_Vwee_prime * elmt_wee1_p) + (elmt_Vwee_double_prime * (elmt_total_wee1 - elmt_wee1_p)));
        der(elmt_kfPPase) = 0;
        der(elmt_K_c) = 0;
        der(elmt_K_d) = 0;
        elmt_k25 = ((elmt_V25_prime * (elmt_total_cdc25 - elmt_cdc25_p)) + (elmt_V25_double_prime * elmt_cdc25_p));
        der(elmt_K_a) = 0;
        der(elmt_K_b) = 0;
        der(elmt_kg) = 0;
        der(elmt_total_cdc25) = 0;
        der(elmt_ke) = 0;
        der(elmt_Vwee_prime) = 0;
        der(elmt_kc) = 0;

end Parameters;
