within BIOMD545;
class Reactions

    input Real elmt_kd1;
    input Real elmt_n3;
    input Real elmt_n1;
    input Real elmt_n2;
    input Real elmt_UVR8M;
    input Real elmt_kdr1;
    input Real elmt_kd4;
    input Real elmt_kd3;
    input Real elmt_kdr2;
    input Real elmt_kd2;
    input Real elmt_kdr3;
    input Real elmt_UVR8D;
    input Real elmt_UCS;
    input Real elmt_HY5;
    input Real elmt_CS;
    input Real elmt_ks3;
    input Real elmt_FHY3;
    input Real elmt_ks2;
    input Real elmt_ksr;
    input Real elmt_ks1;
    input Real elmt_k1;
    input Real elmt_CDW;
    input Real elmt_CD;
    input Real elmt_UV;
    input Real elmt_DWD;
    input Real elmt_ka4;
    input Real elmt_ka3;
    input Real elmt_ka2;
    input Real elmt_kdr3a;
    input Real elmt_ka1;
    input Real elmt_kdr3b;
    input Real elmt_k2;
    input Real elmt_CDCS;
    input Real elmt_UR;
    input Real elmt_RUP;

    Real elmt_r7(unit = "") "";
    Real elmt_product15 "";
    Real elmt_product14 "";
    Real elmt_reactant13 "";
    Real elmt_r8(unit = "") "";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_r5(unit = "") "";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_reactant7 "";
    Real elmt_r6(unit = "") "";
    Real elmt_product12 "";
    Real elmt_reactant10 "";
    Real elmt_reactant11 "";
    Real elmt_r3(unit = "") "";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_r4(unit = "") "";
    Real elmt_reactant4 "";
    Real elmt_product6 "";
    Real elmt_reactant5 "";
    Real elmt_r1(unit = "") "";
    Real elmt_product0 "";
    Real elmt_r2(unit = "") "";
    Real elmt_product1 "";
    Real elmt_r10(unit = "") "";
    Real elmt_reactant20 "";
    Real elmt_reactant19 "";
    Real elmt_product21 "";
    Real elmt_r9(unit = "") "";
    Real elmt_product18 "";


    initial equation
        elmt_product9 = 1.0;
        elmt_reactant2 = 2.0;
        elmt_reactant4 = 2.0;
        elmt_product6 = 1.0;
        elmt_reactant20 = 1.0;
        elmt_product12 = 1.0;
        elmt_reactant5 = 2.0;
        elmt_reactant8 = 1.0;
        elmt_product21 = 1.0;
        elmt_reactant7 = 2.0;
        elmt_product1 = 1.0;
        elmt_product0 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant13 = 2.0;
        elmt_reactant19 = 1.0;
        elmt_product15 = 2.0;
        elmt_product14 = 1.0;
        elmt_product18 = 1.0;
        elmt_product17 = 2.0;


    equation
        elmt_r7 = (elmt_kd3 * Functions.pow(elmt_UR, 2.0));
        elmt_r8 = (elmt_k2 * elmt_UVR8D);
        elmt_r5 = ((elmt_ka2 * Functions.pow(elmt_CS, 2.0) * elmt_CD) - (elmt_kd2 * elmt_CDCS));
        elmt_r6 = (elmt_ka3 * elmt_UVR8M * elmt_RUP);
        elmt_r3 = (elmt_k1 * Functions.pow(elmt_UVR8M, 2.0));
        elmt_r4 = ((elmt_ka1 * Functions.pow(elmt_CS, 2.0) * Functions.pow(elmt_UVR8M, 2.0)) - (elmt_kd1 * elmt_UCS));
        elmt_r1 = ((elmt_ks1 * (1.0 + (elmt_UV * elmt_n3 * (elmt_HY5 + elmt_FHY3)))) - (elmt_kdr1 * (1.0 + (elmt_n1 * elmt_UV)) * elmt_CS));
        elmt_r2 = ((elmt_ks2 * (1.0 + (elmt_UV * elmt_UCS))) - (elmt_kdr2 * elmt_RUP));
        elmt_r10 = ((elmt_ka4 * elmt_CD * elmt_DWD) - (elmt_kd4 * elmt_CDW));
        elmt_r9 = ((elmt_ks3 * (1.0 + (elmt_n2 * elmt_UV))) - (elmt_kdr3 * (((elmt_CDCS / (elmt_kdr3a + elmt_CDCS)) + (elmt_CDW / (elmt_kdr3b + elmt_CDW))) - (elmt_UCS / (elmt_ksr + elmt_UCS))) * elmt_HY5));
        der(elmt_product9) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product6) = 0;
        der(elmt_reactant20) = 0;
        der(elmt_product12) = 0;
        der(elmt_reactant5) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product21) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_product1) = 0;
        der(elmt_product0) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product15) = 0;
        der(elmt_product14) = 0;
        der(elmt_product18) = 0;
        der(elmt_product17) = 0;

end Reactions;
