model BIOMD033 "The statistical mechanism of complex signaling networks: nerve growth factor signaling"

  parameter Real krbEGF = 2.18503e-5;
  parameter Real kruEGF = 0.012;
  parameter Real krbNGF = 1.38209e-7;
  parameter Real kruNGF = 0.007;
  parameter Real kEGF = 694.731;
  parameter Real KmEGF = 6086070.000;
  parameter Real kNGF = 389.428;
  parameter Real KmNGF = 2112.660;
  parameter Real kdSos = 1611.970;
  parameter Real KmdSos = 896896.000;
  parameter Real kSos = 32.344;
  parameter Real KmSos = 35954.300;
  parameter Real kRasGap = 1509.360;
  parameter Real KmRasGap = 1432410.000;
  parameter Real kRasToRaf1 = 0.884;
  parameter Real KmRasToRaf1 = 62464.600;
  parameter Real kpRaf1 = 185.759;
  parameter Real KmpRaf1 = 4768350.000;
  parameter Real kpBRaf = 125.089;
  parameter Real KmpBRaf = 157984.000;
  parameter Real kdMek = 2.832;
  parameter Real KmdMek = 518753.000;
  parameter Real kpMekCytoplasmic = 9.854;
  parameter Real KmpMekCytoplasmic = 1007340.000;
  parameter Real kdErk = 8.891;
  parameter Real KmdErk = 3496490.000;
  parameter Real kpP90Rsk = 0.021;
  parameter Real KmpP90Rsk = 763523.000;
  parameter Real kPI3K = 10.674;
  parameter Real KmPI3K = 184912.000;
  parameter Real kPI3KRas = 0.077;
  parameter Real KmPI3KRas = 272056.000;
  parameter Real kAkt = 0.057;
  parameter Real KmAkt = 653951.000;
  parameter Real kdRaf1ByAkt = 15.121;
  parameter Real KmRaf1ByAkt = 119355.000;
  parameter Real kC3GNGF = 146.912;
  parameter Real KmC3GNGF = 12876.200;
  parameter Real kC3G = 1.401;
  parameter Real KmC3G = 10965.000;
  parameter Real kRapGap = 27.265;
  parameter Real KmRapGap = 295990.000;
  parameter Real kRap1ToBRaf = 2.210;
  parameter Real KmRap1ToBraf = 1025460.000;
  parameter Real kdRaf1 = 0.126;
  parameter Real KmdRaf1 = 1061.710;
  parameter Real kdBRaf = 441.287;
  parameter Real KmdBRaf = 1.08795e7;

  Real EGF;
  Real NGF;
  Real freeEGFReceptor;
  Real boundEGFReceptor;
  Real freeNGFReceptor;
  Real boundNGFReceptor;
  Real SosInactive;
  Real SosActive;
  Real P90RskInactive;
  Real P90RskActive;
  Real RasInactive;
  Real RasActive;
  Real RasGapActive;
  Real Raf1Inactive;
  Real Raf1Active;
  Real BRafInactive;
  Real BRafActive;
  Real MekInactive;
  Real MekActive;
  Real ErkInactive;
  Real ErkActive;
  Real PI3KInactive;
  Real PI3KActive;
  Real AktInactive;
  Real AktActive;
  Real C3GInactive;
  Real C3GActive;
  Real Rap1Inactive;
  Real Rap1Active;
  Real RapGapActive;
  Real PP2AActive;
  Real Raf1PPtase;

initial equation
  BRafInactive = 120000.0;
  MekInactive = 600000.0;
  ErkInactive = 600000.0;
  Raf1Active = 0.0;
  PI3KActive = 0.0;
  SosActive = 0.0;
  Raf1PPtase = 120000.0;
  PI3KInactive = 120000.0;
  Rap1Inactive = 120000.0;
  boundNGFReceptor = 0.0;
  Raf1Inactive = 120000.0;
  ErkActive = 0.0;
  Rap1Active = 0.0;
  RasInactive = 120000.0;
  PP2AActive = 120000.0;
  RapGapActive = 120000.0;
  BRafActive = 0.0;
  boundEGFReceptor = 0.0;
  P90RskInactive = 120000.0;
  C3GActive = 0.0;
  AktActive = 0.0;
  freeEGFReceptor = 80000.0;
  MekActive = 0.0;
  C3GInactive = 120000.0;
  RasActive = 0.0;
  AktInactive = 120000.0;
  EGF = 1.0002E7;
  P90RskActive = 0.0;
  SosInactive = 120000.0;
  NGF = 456000.0;
  freeNGFReceptor = 10000.0;

equation
  der(EGF) = kruEGF*boundEGFReceptor - krbEGF*EGF*freeEGFReceptor;
  der(NGF) = kruNGF*boundNGFReceptor - krbNGF*NGF*freeNGFReceptor;
  der(freeEGFReceptor) = kruEGF*boundEGFReceptor - krbEGF*EGF*freeEGFReceptor;
  der(freeNGFReceptor) = kruNGF*boundNGFReceptor - krbNGF*NGF*freeNGFReceptor;
  der(boundEGFReceptor) = -(kruEGF*boundEGFReceptor - krbEGF*EGF*freeEGFReceptor);
  der(boundNGFReceptor) = -(kruNGF*boundNGFReceptor - krbNGF*NGF*freeNGFReceptor);
  der(SosInactive) = kdSos*P90RskActive*SosActive/(SosActive+KmdSos) - kEGF*boundEGFReceptor*SosInactive/(SosInactive+KmEGF) - kNGF*boundNGFReceptor*SosInactive/(SosInactive+KmNGF);
  der(SosActive) = -(kdSos*P90RskActive*SosActive/(SosActive+KmdSos) - kEGF*boundEGFReceptor*SosInactive/(SosInactive+KmEGF) - kNGF*boundNGFReceptor*SosInactive/(SosInactive+KmNGF));
  der(P90RskInactive) = -(kpP90Rsk*ErkActive*P90RskInactive/(P90RskInactive+KmpP90Rsk));
  der(P90RskActive) = kpP90Rsk*ErkActive*P90RskInactive/(P90RskInactive+KmpP90Rsk);
  der(RasInactive) = kRasGap*RasGapActive*RasActive/(RasActive+KmRasGap) - kSos*SosActive*RasInactive/(RasInactive+KmSos);
  der(RasActive) = -(kRasGap*RasGapActive*RasActive/(RasActive+KmRasGap) - kSos*SosActive*RasInactive/(RasInactive+KmSos));
  der(RasGapActive) = 0.0;
  der(Raf1Inactive) = kdRaf1*Raf1PPtase*Raf1Active/(Raf1Active+KmdRaf1) + kdRaf1*Raf1PPtase*Raf1Active/(Raf1Active+KmdRaf1) - kRasToRaf1*RasActive*Raf1Inactive/(Raf1Inactive+KmRasToRaf1);
  der(Raf1Active) = -(kdRaf1*Raf1PPtase*Raf1Active/(Raf1Active+KmdRaf1) + kdRaf1*Raf1PPtase*Raf1Active/(Raf1Active+KmdRaf1) - kRasToRaf1*RasActive*Raf1Inactive/(Raf1Inactive+KmRasToRaf1));
  der(BRafInactive) = kdBRaf*Raf1PPtase*BRafActive/(BRafActive+KmdBRaf) - kRap1ToBRaf*Rap1Active*BRafInactive/(BRafInactive+KmRap1ToBraf);
  der(BRafActive) = -(kdBRaf*Raf1PPtase*BRafActive/(BRafActive+KmdBRaf) - kRap1ToBRaf*Rap1Active*BRafInactive/(BRafInactive+KmRap1ToBraf));
  der(MekInactive) = kdMek*PP2Active*MekActive/(MekActive/KmdMek) - kpRaf1*Raf1Active*MekInactive/(MekInactive+KmpRaf1) - kpBRaf*BRafInactive*MekInactive/(MekInactive+KmpBRaf);
  der(MekActive) = -(kdMek*PP2Active*MekActive/(MekActive/KmdMek) - kpRaf1*Raf1Active*MekInactive/(MekInactive+KmpRaf1) - kpBRaf*BRafInactive*MekInactive/(MekInactive+KmpBRaf));
  der(ErkInactive) = kdErk*PP2Active*ErkActive/(ErkActive/KmdErk) - kpMekCytoplasmic*MekActive*ErkInactive/(ErkInactive+KmpMekCytoplasmic);
  der(ErkActive) = -(kdErk*PP2Active*ErkActive/(ErkActive/KmdErk) - kpMekCytoplasmic*MekActive*ErkInactive/(ErkInactive+KmpMekCytoplasmic));
  der(PI3KInactive) = -(kPI3K*boundEGFReceptor*PI3KInactive/(PI3KInactive+KmPI3K) + kPI3KRas*RasActive*PI3KInactive/(PI3KInactive+KmPI3KRas));
  der(PI3KActive) = kPI3K*boundEGFReceptor*PI3KInactive/(PI3KInactive+KmPI3K) + kPI3KRas*RasActive*PI3KInactive/(PI3KInactive+KmPI3KRas);
  der(AktInactive) = -(kAkt*PI3KActive*AktInactive/(AktInactive+KmAkt));
  der(AktActive) = kAkt*PI3KActive*AktInactive/(AktInactive+KmAkt);
  der(C3GInactive) = -(kC3GNGF*boundNGFReceptor*C3GInactive/(C3GInactive+KmC3GNGF));
  der(C3GActive) = kC3GNGF*boundNGFReceptor*C3GInactive/(C3GInactive+KmC3GNGF);
  der(Rap1Inactive) = kRapGap*RapGapActive*Rap1Active/(Rap1Active+KmRapGap) - kC3G*C3GActive*Rap1Inactive/(Rap1Inactive+KmC3G);
  der(Rap1Active) = -(kRapGap*RapGapActive*Rap1Active/(Rap1Active+KmRapGap) - kC3G*C3GActive*Rap1Inactive/(Rap1Inactive+KmC3G));
  der(RapGapActive) = 0.0;
  der(PP2AActive) = 0.0;
  der(Raf1PPtase) = 0.0;

end BIOMD033;
