/* Additional record code for MoonLanding generated by the OpenModelica Compiler 1.9.2 (r25115). */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

