within BIOMD578;
class Reactions

    input Real elmt_R5_RKpre;
    input Real elmt_kRK1_0;
    input Real elmt_R3_RKpost;
    input Real elmt_R2_RKpost;
    input Real elmt_kRrecyc;
    input Real elmt_Gt;
    input Real elmt_kA5;
    input Real elmt_R6_RKpost;
    input Real elmt_kA4;
    input Real elmt_RGS;
    input Real elmt_kA3;
    input Real elmt_kA2;
    input Real elmt_R1_RKpost;
    input Real elmt_R4_RKpost;
    input Real elmt_R5_RKpost;
    input Real elmt_Kc1;
    input Real elmt_kPDEshutoff;
    input Real elmt_Kc2;
    input Real elmt_Ga_GTP_PDE_a_Ga_GTP;
    input Real elmt_R0_G_GTP;
    input Real elmt_kRK1_5;
    input Real elmt_kRK1_6;
    input Real elmt_kRGS1;
    input Real elmt_kRK1_3;
    input Real elmt_kRK3_ATP;
    input Real elmt_Gbg;
    input Real elmt_kRK1_4;
    input Real elmt_kRK1_1;
    input Real elmt_R0_Gt;
    input Real elmt_kRGS2;
    input Real elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP;
    input Real elmt_kRK1_2;
    input Real elmt_R5_Arr;
    input Real elmt_Ops_G_GTP;
    input Real elmt_R3_G_GTP;
    input Real elmt_k1;
    input Real elmt_R5;
    input Real elmt_R6;
    input Real elmt_R4_G;
    input Real elmt_R3;
    input Real elmt_kG2ops;
    input Real elmt_R4;
    input Real elmt_PDE;
    input Real elmt_G_GTP;
    input Real elmt_R1;
    input Real elmt_R2;
    input Real elmt_R5_G_GTP;
    input Real elmt_Arr_di;
    input Real elmt_k2;
    input Real elmt_R0_G;
    input Real elmt_Ca2_0;
    input Real elmt_R0;
    input Real elmt_R3_Gt;
    input Real elmt_kOps;
    input Real elmt_Ga_GTP_a_PDE_a_Ga_GTP;
    input Real elmt_R2_G_GTP;
    input Real elmt_R0_RKpre;
    input Real elmt_stimulus;
    input Real elmt_ktherm;
    input Real elmt_R3_Arr;
    input Real elmt_R6_G_GTP;
    input Real elmt_RecR_Ca;
    input Real elmt_R2_Gt;
    input Real elmt_Ca2_buff;
    input Real elmt_Ops_G;
    input Real elmt_R1_G;
    input Real elmt_PDE_a_Ga_GTP;
    input Real elmt_Ga_GDP;
    input Real elmt_R5_G;
    input Real elmt_kGrecyc;
    input Real elmt_kG5_GTP;
    input Real elmt_R1_G_GTP;
    input Real elmt_R1_Arr;
    input Real elmt_Ca2_free;
    input Real elmt_Ga_GTP;
    input Real elmt_R_Gt;
    input Real elmt_alfamax;
    input Real elmt_gammaCa;
    input Real elmt_kGpre2;
    input Real elmt_R5_Gt;
    input Real elmt_kGpre1;
    input Real elmt_Rtot;
    input Real elmt_Arr_tetra;
    input Real elmt_kRK4;
    input Real elmt_kG1ops;
    input Real elmt_kRec1;
    input Real elmt_PDE_Ga_GTP;
    input Real elmt_kRec4;
    input Real elmt_kRec2;
    input Real elmt_kRec3;
    input Real elmt_R6_Arr;
    input Real elmt_kA1_2;
    input Real elmt_kA1_1;
    input Real elmt_Arr;
    input Real elmt_kA1_4;
    input Real elmt_kA1_3;
    input Real elmt_cGMP;
    input Real elmt_R4_Gt;
    input Real elmt_R1_RKpre;
    input Real elmt_R;
    input Real elmt_R2_G;
    input Real elmt_R6_RKpre;
    input Real elmt_R6_G;
    input Real elmt_R4_RKpre;
    input Real elmt_Jdark;
    input Real elmt_ncg;
    input Real elmt_E;
    input Real elmt_F;
    input Real elmt_Ops_Gt;
    input Real elmt_RecT;
    input Real elmt_fCa;
    input Real elmt_eT;
    input Real elmt_RGS_PDE_a_Ga_GTP;
    input Real elmt_kP1_rev;
    input Real elmt_kRK2;
    input Real elmt_R4_Arr;
    input Real elmt_kG3;
    input Real elmt_kG2;
    input Real elmt_Vcyto;
    input Real elmt_betadark;
    input Real elmt_R3_RKpre;
    input Real elmt_kG7;
    input Real elmt_kG6;
    input Real elmt_kG4_GDP;
    input Real elmt_R6_Gt;
    input Real elmt_RecR_Ca_RK;
    input Real elmt_kG1_3;
    input Real elmt_kG1_4;
    input Real elmt_kG1_5;
    input Real elmt_kG1_6;
    input Real elmt_kG1_0;
    input Real elmt_kP4;
    input Real elmt_kG1_1;
    input Real elmt_kP3;
    input Real elmt_kG1_2;
    input Real elmt_kP2;
    input Real elmt_kP1;
    input Real elmt_RK;
    input Real elmt_R2_Arr;
    input Real elmt_m2;
    input Real elmt_R3_G;
    input Real elmt_m1;
    input Real elmt_Ops;
    input Real elmt_kGshutoff;
    input Real elmt_kA1_6;
    input Real elmt_kA1_5;
    input Real elmt_betasub;
    input Real elmt_cGMPdark;
    input Real elmt_R2_RKpre;
    input Real elmt_R4_G_GTP;
    input Real elmt_R1_Gt;

    Real elmt_v_r_tetraarr(unit = "") "v_r_tetraarr";
    Real elmt_reactant236 "";
    Real elmt_product237 "";
    Real elmt_v_r10(unit = "") "v_r10";
    Real elmt_reactant110 "";
    Real elmt_product111 "";
    Real elmt_v_r13_0(unit = "") "v_r13_0";
    Real elmt_reactant121 "";
    Real elmt_reactant120 "";
    Real elmt_product122 "";
    Real elmt_v_r12(unit = "") "v_r12";
    Real elmt_reactant115 "";
    Real elmt_product116 "";
    Real elmt_v_r11(unit = "") "v_r11";
    Real elmt_product113 "";
    Real elmt_product114 "";
    Real elmt_reactant112 "";
    Real elmt_v_r13_3(unit = "") "v_r13_3";
    Real elmt_reactant130 "";
    Real elmt_product131 "";
    Real elmt_reactant129 "";
    Real elmt_v_r18(unit = "") "v_r18";
    Real elmt_reactant194 "";
    Real elmt_reactant193 "";
    Real elmt_product195 "";
    Real elmt_v_r13_4(unit = "") "v_r13_4";
    Real elmt_reactant132 "";
    Real elmt_product134 "";
    Real elmt_reactant133 "";
    Real elmt_v_r17(unit = "") "v_r17";
    Real elmt_reactant190 "";
    Real elmt_product192 "";
    Real elmt_product191 "";
    Real elmt_v_r13_1(unit = "") "v_r13_1";
    Real elmt_product125 "";
    Real elmt_reactant124 "";
    Real elmt_reactant123 "";
    Real elmt_v_r13_2(unit = "") "v_r13_2";
    Real elmt_reactant127 "";
    Real elmt_reactant126 "";
    Real elmt_product128 "";
    Real elmt_v_r1(unit = "") "v_r1";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_v_r13_5(unit = "") "v_r13_5";
    Real elmt_product137 "";
    Real elmt_reactant136 "";
    Real elmt_reactant135 "";
    Real elmt_v_r13_6(unit = "") "v_r13_6";
    Real elmt_reactant139 "";
    Real elmt_reactant138 "";
    Real elmt_product140 "";
    Real elmt_v_r21(unit = "") "v_r21";
    Real elmt_product202 "";
    Real elmt_reactant201 "";
    Real elmt_v_r20(unit = "") "v_r20";
    Real elmt_reactant198 "";
    Real elmt_product200 "";
    Real elmt_reactant199 "";
    Real elmt_v_r6_6(unit = "") "v_r6_6";
    Real elmt_product89 "";
    Real elmt_reactant88 "";
    Real elmt_product90 "";
    Real elmt_v_r25(unit = "") "v_r25";
    Real elmt_product214 "";
    Real elmt_reactant213 "";
    Real elmt_product216 "";
    Real elmt_product215 "";
    Real elmt_v_r6_5(unit = "") "v_r6_5";
    Real elmt_reactant85 "";
    Real elmt_product87 "";
    Real elmt_product86 "";
    Real elmt_v_r24(unit = "") "v_r24";
    Real elmt_product212 "";
    Real elmt_reactant211 "";
    Real elmt_reactant210 "";
    Real elmt_v_r23(unit = "") "v_r23";
    Real elmt_reactant206 "";
    Real elmt_product209 "";
    Real elmt_product208 "";
    Real elmt_product207 "";
    Real elmt_v_r22(unit = "") "v_r22";
    Real elmt_reactant204 "";
    Real elmt_reactant203 "";
    Real elmt_product205 "";
    Real elmt_v_r2_6(unit = "") "v_r2_6";
    Real elmt_product24 "";
    Real elmt_reactant22 "";
    Real elmt_reactant23 "";
    Real elmt_v_r6_2(unit = "") "v_r6_2";
    Real elmt_product78 "";
    Real elmt_product77 "";
    Real elmt_reactant76 "";
    Real elmt_v_r29(unit = "") "v_r29";
    Real elmt_reactant226 "";
    Real elmt_reactant225 "";
    Real elmt_product227 "";
    Real elmt_v_r2_5(unit = "") "v_r2_5";
    Real elmt_reactant20 "";
    Real elmt_reactant19 "";
    Real elmt_product21 "";
    Real elmt_v_r6_1(unit = "") "v_r6_1";
    Real elmt_product74 "";
    Real elmt_reactant73 "";
    Real elmt_product75 "";
    Real elmt_v_r28(unit = "") "v_r28";
    Real elmt_product224 "";
    Real elmt_reactant223 "";
    Real elmt_v_r6_4(unit = "") "v_r6_4";
    Real elmt_product84 "";
    Real elmt_product83 "";
    Real elmt_reactant82 "";
    Real elmt_v_r27(unit = "") "v_r27";
    Real elmt_reactant220 "";
    Real elmt_product222 "";
    Real elmt_product221 "";
    Real elmt_v_r6_3(unit = "") "v_r6_3";
    Real elmt_product81 "";
    Real elmt_product80 "";
    Real elmt_reactant79 "";
    Real elmt_v_r26(unit = "") "v_r26";
    Real elmt_reactant217 "";
    Real elmt_product219 "";
    Real elmt_product218 "";
    Real elmt_v_r2_2(unit = "") "v_r2_2";
    Real elmt_product12 "";
    Real elmt_reactant10 "";
    Real elmt_reactant11 "";
    Real elmt_v_r2_1(unit = "") "v_r2_1";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_reactant7 "";
    Real elmt_v_r2_4(unit = "") "v_r2_4";
    Real elmt_reactant16 "";
    Real elmt_reactant17 "";
    Real elmt_product18 "";
    Real elmt_v_r2_3(unit = "") "v_r2_3";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_reactant13 "";
    Real elmt_v_r19(unit = "") "v_r19";
    Real elmt_reactant196 "";
    Real elmt_product197 "";
    Real elmt_v_r2_0(unit = "") "v_r2_0";
    Real elmt_reactant4 "";
    Real elmt_product6 "";
    Real elmt_reactant5 "";
    Real elmt_v_r16_0(unit = "") "v_r16_0";
    Real elmt_product171 "";
    Real elmt_product170 "";
    Real elmt_reactant169 "";
    Real elmt_v_r16_1(unit = "") "v_r16_1";
    Real elmt_reactant172 "";
    Real elmt_product174 "";
    Real elmt_product173 "";
    Real elmt_v_r16_4(unit = "") "v_r16_4";
    Real elmt_reactant181 "";
    Real elmt_product182 "";
    Real elmt_product183 "";
    Real elmt_v_r16_5(unit = "") "v_r16_5";
    Real elmt_reactant184 "";
    Real elmt_product186 "";
    Real elmt_product185 "";
    Real elmt_v_r16_2(unit = "") "v_r16_2";
    Real elmt_reactant175 "";
    Real elmt_product177 "";
    Real elmt_product176 "";
    Real elmt_v_r16_3(unit = "") "v_r16_3";
    Real elmt_product179 "";
    Real elmt_reactant178 "";
    Real elmt_product180 "";
    Real elmt_v_r16_6(unit = "") "v_r16_6";
    Real elmt_reactant187 "";
    Real elmt_product189 "";
    Real elmt_product188 "";
    Real elmt_v_r5_6(unit = "") "v_r5_6";
    Real elmt_product72 "";
    Real elmt_reactant70 "";
    Real elmt_reactant71 "";
    Real elmt_v_r5_3(unit = "") "v_r5_3";
    Real elmt_reactant61 "";
    Real elmt_product63 "";
    Real elmt_reactant62 "";
    Real elmt_v_r5_2(unit = "") "v_r5_2";
    Real elmt_product60 "";
    Real elmt_reactant58 "";
    Real elmt_reactant59 "";
    Real elmt_v_r5_5(unit = "") "v_r5_5";
    Real elmt_product69 "";
    Real elmt_reactant67 "";
    Real elmt_reactant68 "";
    Real elmt_v_r5_4(unit = "") "v_r5_4";
    Real elmt_reactant64 "";
    Real elmt_product66 "";
    Real elmt_reactant65 "";
    Real elmt_v_r5_1(unit = "") "v_r5_1";
    Real elmt_product57 "";
    Real elmt_reactant55 "";
    Real elmt_reactant56 "";
    Real elmt_v_rstprec(unit = "") "v_rstprec";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_v_GtRpre(unit = "") "v_GtRpre";
    Real elmt_reactant118 "";
    Real elmt_reactant117 "";
    Real elmt_product119 "";
    Real elmt_v_r15_1(unit = "") "v_r15_1";
    Real elmt_product158 "";
    Real elmt_reactant157 "";
    Real elmt_v_r15_2(unit = "") "v_r15_2";
    Real elmt_product160 "";
    Real elmt_reactant159 "";
    Real elmt_v_r15_0(unit = "") "v_r15_0";
    Real elmt_product156 "";
    Real elmt_reactant155 "";
    Real elmt_v_r15_5(unit = "") "v_r15_5";
    Real elmt_reactant165 "";
    Real elmt_product166 "";
    Real elmt_v_r15_6(unit = "") "v_r15_6";
    Real elmt_product168 "";
    Real elmt_reactant167 "";
    Real elmt_v_r15_3(unit = "") "v_r15_3";
    Real elmt_reactant161 "";
    Real elmt_product162 "";
    Real elmt_v_r15_4(unit = "") "v_r15_4";
    Real elmt_reactant163 "";
    Real elmt_product164 "";
    Real elmt_v_r4_4(unit = "") "v_r4_4";
    Real elmt_product48 "";
    Real elmt_product47 "";
    Real elmt_reactant46 "";
    Real elmt_v_r4_3(unit = "") "v_r4_3";
    Real elmt_product45 "";
    Real elmt_product44 "";
    Real elmt_reactant43 "";
    Real elmt_v_r4_6(unit = "") "v_r4_6";
    Real elmt_reactant52 "";
    Real elmt_product54 "";
    Real elmt_product53 "";
    Real elmt_v_r4_5(unit = "") "v_r4_5";
    Real elmt_product51 "";
    Real elmt_product50 "";
    Real elmt_reactant49 "";
    Real elmt_v_r4_2(unit = "") "v_r4_2";
    Real elmt_product41 "";
    Real elmt_reactant40 "";
    Real elmt_product42 "";
    Real elmt_v_r4_1(unit = "") "v_r4_1";
    Real elmt_product38 "";
    Real elmt_reactant37 "";
    Real elmt_product39 "";
    Real elmt_v_r31(unit = "") "v_r31";
    Real elmt_reactant231 "";
    Real elmt_product233 "";
    Real elmt_reactant232 "";
    Real elmt_v_r30(unit = "") "v_r30";
    Real elmt_product230 "";
    Real elmt_reactant229 "";
    Real elmt_reactant228 "";
    Real elmt_v_r36(unit = "") "v_r36";
    Real elmt_product242 "";
    Real elmt_v_r_diarr(unit = "") "v_r_diarr";
    Real elmt_product235 "";
    Real elmt_reactant234 "";
    Real elmt_v_r35(unit = "") "v_r35";
    Real elmt_product241 "";
    Real elmt_v_r34(unit = "") "v_r34";
    Real elmt_reactant240 "";
    Real elmt_v_r33(unit = "") "v_r33";
    Real elmt_reactant238 "";
    Real elmt_product239 "";
    Real elmt_v_r14_2(unit = "") "v_r14_2";
    Real elmt_product146 "";
    Real elmt_reactant145 "";
    Real elmt_v_r14_3(unit = "") "v_r14_3";
    Real elmt_product148 "";
    Real elmt_reactant147 "";
    Real elmt_v_r14_0(unit = "") "v_r14_0";
    Real elmt_reactant141 "";
    Real elmt_product142 "";
    Real elmt_v_r14_1(unit = "") "v_r14_1";
    Real elmt_reactant143 "";
    Real elmt_product144 "";
    Real elmt_v_r37(unit = "") "v_r37";
    Real elmt_reactant243 "";
    Real elmt_v_r14_6(unit = "") "v_r14_6";
    Real elmt_reactant153 "";
    Real elmt_product154 "";
    Real elmt_v_r14_4(unit = "") "v_r14_4";
    Real elmt_reactant149 "";
    Real elmt_product150 "";
    Real elmt_v_r14_5(unit = "") "v_r14_5";
    Real elmt_reactant151 "";
    Real elmt_product152 "";
    Real elmt_v_r7_5(unit = "") "v_r7_5";
    Real elmt_product102 "";
    Real elmt_reactant101 "";
    Real elmt_v_r9(unit = "") "v_r9";
    Real elmt_reactant108 "";
    Real elmt_product109 "";
    Real elmt_v_r7_4(unit = "") "v_r7_4";
    Real elmt_product100 "";
    Real elmt_reactant99 "";
    Real elmt_v_r8(unit = "") "v_r8";
    Real elmt_reactant106 "";
    Real elmt_reactant105 "";
    Real elmt_product107 "";
    Real elmt_v_r7_6(unit = "") "v_r7_6";
    Real elmt_product104 "";
    Real elmt_reactant103 "";
    Real elmt_v_r3_5(unit = "") "v_r3_5";
    Real elmt_product36 "";
    Real elmt_reactant35 "";
    Real elmt_v_r7_1(unit = "") "v_r7_1";
    Real elmt_product94 "";
    Real elmt_reactant93 "";
    Real elmt_v_r3_4(unit = "") "v_r3_4";
    Real elmt_product34 "";
    Real elmt_reactant33 "";
    Real elmt_v_r7_0(unit = "") "v_r7_0";
    Real elmt_reactant91 "";
    Real elmt_product92 "";
    Real elmt_v_r7_3(unit = "") "v_r7_3";
    Real elmt_reactant97 "";
    Real elmt_product98 "";
    Real elmt_v_r7_2(unit = "") "v_r7_2";
    Real elmt_product96 "";
    Real elmt_reactant95 "";
    Real elmt_v_r3_1(unit = "") "v_r3_1";
    Real elmt_reactant27 "";
    Real elmt_product28 "";
    Real elmt_v_r3_0(unit = "") "v_r3_0";
    Real elmt_reactant25 "";
    Real elmt_product26 "";
    Real elmt_v_r3_3(unit = "") "v_r3_3";
    Real elmt_reactant31 "";
    Real elmt_product32 "";
    Real elmt_v_r3_2(unit = "") "v_r3_2";
    Real elmt_product30 "";
    Real elmt_reactant29 "";


    initial equation
        elmt_reactant40 = 1.0;
        elmt_reactant190 = 1.0;
        elmt_reactant49 = 1.0;
        elmt_reactant43 = 1.0;
        elmt_reactant46 = 1.0;
        elmt_reactant198 = 1.0;
        elmt_product212 = 1.0;
        elmt_product214 = 1.0;
        elmt_reactant196 = 1.0;
        elmt_reactant194 = 1.0;
        elmt_reactant193 = 1.0;
        elmt_product219 = 1.0;
        elmt_product216 = 1.0;
        elmt_product215 = 1.0;
        elmt_product218 = 1.0;
        elmt_reactant199 = 1.0;
        elmt_reactant52 = 1.0;
        elmt_reactant58 = 1.0;
        elmt_reactant59 = 1.0;
        elmt_reactant55 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_product102 = 1.0;
        elmt_product222 = 1.0;
        elmt_product104 = 1.0;
        elmt_product224 = 1.0;
        elmt_product221 = 1.0;
        elmt_product100 = 1.0;
        elmt_product109 = 1.0;
        elmt_product227 = 1.0;
        elmt_product107 = 1.0;
        elmt_reactant20 = 1.0;
        elmt_product12 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_reactant175 = 1.0;
        elmt_reactant172 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_reactant178 = 1.0;
        elmt_reactant31 = 1.0;
        elmt_product21 = 1.0;
        elmt_reactant37 = 1.0;
        elmt_reactant33 = 1.0;
        elmt_reactant35 = 1.0;
        elmt_reactant187 = 1.0;
        elmt_product200 = 1.0;
        elmt_product202 = 1.0;
        elmt_reactant184 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_reactant181 = 1.0;
        elmt_product209 = 1.0;
        elmt_product208 = 1.0;
        elmt_product15 = 1.0;
        elmt_product205 = 1.0;
        elmt_product207 = 1.0;
        elmt_product18 = 1.0;
        elmt_reactant153 = 1.0;
        elmt_reactant151 = 1.0;
        elmt_reactant159 = 1.0;
        elmt_reactant157 = 1.0;
        elmt_reactant155 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant17 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_reactant165 = 1.0;
        elmt_reactant163 = 1.0;
        elmt_reactant161 = 1.0;
        elmt_reactant169 = 1.0;
        elmt_reactant167 = 1.0;
        elmt_product192 = 1.0;
        elmt_product195 = 1.0;
        elmt_product191 = 1.0;
        elmt_reactant132 = 1.0;
        elmt_reactant130 = 1.0;
        elmt_product197 = 1.0;
        elmt_reactant139 = 1.0;
        elmt_reactant138 = 1.0;
        elmt_reactant136 = 1.0;
        elmt_reactant135 = 1.0;
        elmt_reactant133 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_reactant5 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant143 = 1.0;
        elmt_reactant141 = 1.0;
        elmt_reactant149 = 1.0;
        elmt_reactant147 = 1.0;
        elmt_reactant145 = 1.0;
        elmt_product74 = 1.0;
        elmt_product72 = 1.0;
        elmt_product78 = 1.0;
        elmt_product77 = 1.0;
        elmt_product75 = 1.0;
        elmt_reactant229 = 1.0;
        elmt_reactant108 = 1.0;
        elmt_product171 = 1.0;
        elmt_product170 = 1.0;
        elmt_product173 = 1.0;
        elmt_reactant110 = 1.0;
        elmt_product179 = 1.0;
        elmt_reactant231 = 1.0;
        elmt_product174 = 1.0;
        elmt_product177 = 1.0;
        elmt_product176 = 1.0;
        elmt_reactant118 = 1.0;
        elmt_reactant117 = 1.0;
        elmt_reactant238 = 1.0;
        elmt_product69 = 1.0;
        elmt_reactant236 = 2.0;
        elmt_reactant115 = 1.0;
        elmt_reactant234 = 2.0;
        elmt_reactant112 = 1.0;
        elmt_reactant232 = 1.0;
        elmt_product84 = 1.0;
        elmt_product83 = 1.0;
        elmt_product89 = 1.0;
        elmt_product87 = 1.0;
        elmt_product86 = 1.0;
        elmt_product182 = 1.0;
        elmt_product183 = 1.0;
        elmt_product81 = 1.0;
        elmt_product80 = 1.0;
        elmt_product180 = 1.0;
        elmt_reactant121 = 1.0;
        elmt_reactant120 = 1.0;
        elmt_product189 = 1.0;
        elmt_reactant240 = 1.0;
        elmt_product186 = 1.0;
        elmt_product185 = 1.0;
        elmt_product188 = 1.0;
        elmt_reactant129 = 1.0;
        elmt_reactant127 = 1.0;
        elmt_reactant126 = 1.0;
        elmt_reactant124 = 1.0;
        elmt_reactant123 = 1.0;
        elmt_reactant243 = 1.0;
        elmt_product96 = 1.0;
        elmt_product94 = 1.0;
        elmt_product98 = 1.0;
        elmt_product150 = 1.0;
        elmt_product92 = 1.0;
        elmt_product90 = 1.0;
        elmt_product156 = 1.0;
        elmt_product158 = 1.0;
        elmt_product152 = 1.0;
        elmt_product154 = 1.0;
        elmt_reactant217 = 1.0;
        elmt_reactant213 = 1.0;
        elmt_reactant211 = 1.0;
        elmt_reactant210 = 1.0;
        elmt_product9 = 1.0;
        elmt_product6 = 1.0;
        elmt_product1 = 1.0;
        elmt_product160 = 1.0;
        elmt_product162 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant220 = 1.0;
        elmt_product168 = 1.0;
        elmt_product164 = 1.0;
        elmt_product166 = 1.0;
        elmt_reactant228 = 1.0;
        elmt_reactant106 = 1.0;
        elmt_reactant226 = 1.0;
        elmt_reactant105 = 1.0;
        elmt_reactant225 = 1.0;
        elmt_reactant103 = 1.0;
        elmt_reactant223 = 1.0;
        elmt_reactant101 = 1.0;
        elmt_product30 = 1.0;
        elmt_reactant85 = 1.0;
        elmt_product34 = 1.0;
        elmt_product32 = 1.0;
        elmt_reactant82 = 1.0;
        elmt_reactant88 = 1.0;
        elmt_product134 = 1.0;
        elmt_product137 = 1.0;
        elmt_product131 = 1.0;
        elmt_product26 = 1.0;
        elmt_product24 = 1.0;
        elmt_product28 = 1.0;
        elmt_product41 = 1.0;
        elmt_reactant95 = 1.0;
        elmt_reactant97 = 1.0;
        elmt_product45 = 1.0;
        elmt_product44 = 1.0;
        elmt_reactant91 = 1.0;
        elmt_product42 = 1.0;
        elmt_reactant93 = 1.0;
        elmt_product140 = 1.0;
        elmt_reactant99 = 1.0;
        elmt_product146 = 1.0;
        elmt_product148 = 1.0;
        elmt_product142 = 1.0;
        elmt_product144 = 1.0;
        elmt_reactant206 = 1.0;
        elmt_product38 = 1.0;
        elmt_reactant204 = 1.0;
        elmt_product36 = 1.0;
        elmt_reactant203 = 1.0;
        elmt_reactant201 = 1.0;
        elmt_product39 = 1.0;
        elmt_reactant61 = 1.0;
        elmt_reactant62 = 1.0;
        elmt_product51 = 1.0;
        elmt_product50 = 1.0;
        elmt_reactant64 = 1.0;
        elmt_product54 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant65 = 1.0;
        elmt_reactant67 = 1.0;
        elmt_reactant68 = 1.0;
        elmt_product113 = 1.0;
        elmt_product233 = 1.0;
        elmt_product114 = 1.0;
        elmt_product235 = 1.0;
        elmt_product230 = 1.0;
        elmt_product111 = 1.0;
        elmt_product48 = 1.0;
        elmt_product47 = 1.0;
        elmt_product237 = 1.0;
        elmt_product116 = 1.0;
        elmt_product119 = 1.0;
        elmt_product239 = 1.0;
        elmt_product63 = 1.0;
        elmt_reactant73 = 1.0;
        elmt_product60 = 1.0;
        elmt_product66 = 1.0;
        elmt_reactant70 = 1.0;
        elmt_reactant71 = 1.0;
        elmt_reactant76 = 1.0;
        elmt_reactant79 = 1.0;
        elmt_product125 = 1.0;
        elmt_product241 = 1.0;
        elmt_product122 = 1.0;
        elmt_product242 = 1.0;
        elmt_product57 = 1.0;
        elmt_product128 = 1.0;


    equation
        elmt_v_r_tetraarr = ((elmt_kA4 * elmt_Arr_di * elmt_Arr_di) - (elmt_kA5 * elmt_Arr_tetra));
        elmt_v_r10 = (elmt_kG5_GTP * elmt_Ops_G);
        elmt_v_r13_0 = ((elmt_kG1_0 * elmt_Gt * elmt_R0) - (elmt_kG2 * elmt_R0_Gt));
        elmt_v_r12 = (elmt_kRrecyc * elmt_Ops);
        elmt_v_r11 = (elmt_kG6 * elmt_Ops_G_GTP);
        elmt_v_r13_3 = ((elmt_kG1_3 * elmt_Gt * elmt_R3) - (elmt_kG2 * elmt_R3_Gt));
        elmt_v_r18 = ((elmt_kP1 * elmt_PDE * elmt_Ga_GTP) - (elmt_kP1_rev * elmt_PDE_Ga_GTP));
        elmt_v_r13_4 = ((elmt_kG1_4 * elmt_Gt * elmt_R4) - (elmt_kG2 * elmt_R4_Gt));
        elmt_v_r17 = (elmt_kG7 * elmt_G_GTP);
        elmt_v_r13_1 = ((elmt_kG1_1 * elmt_Gt * elmt_R1) - (elmt_kG2 * elmt_R1_Gt));
        elmt_v_r13_2 = ((elmt_kG1_2 * elmt_Gt * elmt_R2) - (elmt_kG2 * elmt_R2_Gt));
        elmt_v_r1 = ((elmt_stimulus * elmt_R) / elmt_Rtot);
        elmt_v_r13_5 = ((elmt_kG1_5 * elmt_Gt * elmt_R5) - (elmt_kG2 * elmt_R5_Gt));
        elmt_v_r13_6 = ((elmt_kG1_6 * elmt_Gt * elmt_R6) - (elmt_kG2 * elmt_R6_Gt));
        elmt_v_r21 = (elmt_kP4 * elmt_Ga_GTP_PDE_a_Ga_GTP);
        elmt_v_r20 = (elmt_kP3 * elmt_PDE_a_Ga_GTP * elmt_Ga_GTP);
        elmt_v_r6_6 = (elmt_kA3 * elmt_R6_Arr);
        elmt_v_r25 = (elmt_kRGS2 * elmt_RGS_PDE_a_Ga_GTP);
        elmt_v_r6_5 = (elmt_kA3 * elmt_R5_Arr);
        elmt_v_r24 = (elmt_kRGS1 * elmt_RGS * elmt_PDE_a_Ga_GTP);
        elmt_v_r23 = (elmt_kRGS2 * elmt_RGS_Ga_GTP_a_PDE_a_Ga_GTP);
        elmt_v_r22 = (elmt_kRGS1 * elmt_RGS * elmt_Ga_GTP_a_PDE_a_Ga_GTP);
        elmt_v_r2_6 = ((elmt_kRK1_6 * elmt_RK * elmt_R6) - (elmt_kRK2 * elmt_R6_RKpre));
        elmt_v_r6_2 = (elmt_kA3 * elmt_R2_Arr);
        elmt_v_r29 = (elmt_kGrecyc * elmt_Gbg * elmt_Ga_GDP);
        elmt_v_r2_5 = ((elmt_kRK1_5 * elmt_RK * elmt_R5) - (elmt_kRK2 * elmt_R5_RKpre));
        elmt_v_r6_1 = (elmt_kA3 * elmt_R1_Arr);
        elmt_v_r28 = (elmt_kGshutoff * elmt_Ga_GTP);
        elmt_v_r6_4 = (elmt_kA3 * elmt_R4_Arr);
        elmt_v_r27 = (elmt_kPDEshutoff * elmt_Ga_GTP_a_PDE_a_Ga_GTP);
        elmt_v_r6_3 = (elmt_kA3 * elmt_R3_Arr);
        elmt_v_r26 = (elmt_kPDEshutoff * elmt_PDE_a_Ga_GTP);
        elmt_v_r2_2 = ((elmt_kRK1_2 * elmt_RK * elmt_R2) - (elmt_kRK2 * elmt_R2_RKpre));
        elmt_v_r2_1 = ((elmt_kRK1_1 * elmt_RK * elmt_R1) - (elmt_kRK2 * elmt_R1_RKpre));
        elmt_v_r2_4 = ((elmt_kRK1_4 * elmt_RK * elmt_R4) - (elmt_kRK2 * elmt_R4_RKpre));
        elmt_v_r2_3 = ((elmt_kRK1_3 * elmt_RK * elmt_R3) - (elmt_kRK2 * elmt_R3_RKpre));
        elmt_v_r19 = (elmt_kP2 * elmt_PDE_Ga_GTP);
        elmt_v_r2_0 = ((elmt_kRK1_0 * elmt_RK * elmt_R0) - (elmt_kRK2 * elmt_R0_RKpre));
        elmt_v_r16_0 = (elmt_kG6 * elmt_R0_G_GTP);
        elmt_v_r16_1 = (elmt_kG6 * elmt_R1_G_GTP);
        elmt_v_r16_4 = (elmt_kG6 * elmt_R4_G_GTP);
        elmt_v_r16_5 = (elmt_kG6 * elmt_R5_G_GTP);
        elmt_v_r16_2 = (elmt_kG6 * elmt_R2_G_GTP);
        elmt_v_r16_3 = (elmt_kG6 * elmt_R3_G_GTP);
        elmt_v_r16_6 = (elmt_kG6 * elmt_R6_G_GTP);
        elmt_v_r5_6 = ((elmt_kA1_6 * elmt_Arr * elmt_R6) - (elmt_kA2 * elmt_R6_Arr));
        elmt_v_r5_3 = ((elmt_kA1_3 * elmt_Arr * elmt_R3) - (elmt_kA2 * elmt_R3_Arr));
        elmt_v_r5_2 = ((elmt_kA1_2 * elmt_Arr * elmt_R2) - (elmt_kA2 * elmt_R2_Arr));
        elmt_v_r5_5 = ((elmt_kA1_5 * elmt_Arr * elmt_R5) - (elmt_kA2 * elmt_R5_Arr));
        elmt_v_r5_4 = ((elmt_kA1_4 * elmt_Arr * elmt_R4) - (elmt_kA2 * elmt_R4_Arr));
        elmt_v_r5_1 = ((elmt_kA1_1 * elmt_Arr * elmt_R1) - (elmt_kA2 * elmt_R1_Arr));
        elmt_v_rstprec = ((elmt_stimulus * elmt_R_Gt) / elmt_Rtot);
        elmt_v_GtRpre = ((elmt_kGpre1 * elmt_Gt * elmt_R) - (elmt_kGpre2 * elmt_R_Gt));
        elmt_v_r15_1 = (elmt_kG5_GTP * elmt_R1_G);
        elmt_v_r15_2 = (elmt_kG5_GTP * elmt_R2_G);
        elmt_v_r15_0 = (elmt_kG5_GTP * elmt_R0_G);
        elmt_v_r15_5 = (elmt_kG5_GTP * elmt_R5_G);
        elmt_v_r15_6 = (elmt_kG5_GTP * elmt_R6_G);
        elmt_v_r15_3 = (elmt_kG5_GTP * elmt_R3_G);
        elmt_v_r15_4 = (elmt_kG5_GTP * elmt_R4_G);
        elmt_v_r4_4 = (elmt_kRK4 * elmt_R4_RKpost);
        elmt_v_r4_3 = (elmt_kRK4 * elmt_R3_RKpost);
        elmt_v_r4_6 = (elmt_kRK4 * elmt_R6_RKpost);
        elmt_v_r4_5 = (elmt_kRK4 * elmt_R5_RKpost);
        elmt_v_r4_2 = (elmt_kRK4 * elmt_R2_RKpost);
        elmt_v_r4_1 = (elmt_kRK4 * elmt_R1_RKpost);
        elmt_v_r31 = ((elmt_kRec3 * elmt_RecR_Ca * elmt_RK) - (elmt_kRec4 * elmt_RecR_Ca_RK));
        elmt_v_r30 = ((elmt_kRec1 * elmt_RecT * elmt_Ca2_free) - (elmt_kRec2 * elmt_RecR_Ca));
        elmt_v_r36 = ((elmt_alfamax / (1.0 + Functions.pow((elmt_Ca2_free / elmt_Kc1), elmt_m1))) + (elmt_alfamax / (1.0 + Functions.pow((elmt_Ca2_free / elmt_Kc2), elmt_m2))));
        elmt_v_r_diarr = ((elmt_kA4 * elmt_Arr * elmt_Arr) - (elmt_kA5 * elmt_Arr_di));
        elmt_v_r35 = (((1000000.0 * elmt_fCa * elmt_Jdark) / ((2.0 + elmt_fCa) * elmt_F * elmt_Vcyto)) * Functions.pow((elmt_cGMP / elmt_cGMPdark), elmt_ncg));
        elmt_v_r34 = (elmt_gammaCa * (elmt_Ca2_free - elmt_Ca2_0));
        elmt_v_r33 = ((elmt_k1 * (elmt_eT - elmt_Ca2_buff) * elmt_Ca2_free) - (elmt_k2 * elmt_Ca2_buff));
        elmt_v_r14_2 = ((elmt_kG3 * elmt_R2_Gt) - (elmt_kG4_GDP * elmt_R2_G));
        elmt_v_r14_3 = ((elmt_kG3 * elmt_R3_Gt) - (elmt_kG4_GDP * elmt_R3_G));
        elmt_v_r14_0 = ((elmt_kG3 * elmt_R0_Gt) - (elmt_kG4_GDP * elmt_R0_G));
        elmt_v_r14_1 = ((elmt_kG3 * elmt_R1_Gt) - (elmt_kG4_GDP * elmt_R1_G));
        elmt_v_r37 = ((elmt_betadark + (elmt_betasub * elmt_E)) * elmt_cGMP);
        elmt_v_r14_6 = ((elmt_kG3 * elmt_R6_Gt) - (elmt_kG4_GDP * elmt_R6_G));
        elmt_v_r14_4 = ((elmt_kG3 * elmt_R4_Gt) - (elmt_kG4_GDP * elmt_R4_G));
        elmt_v_r14_5 = ((elmt_kG3 * elmt_R5_Gt) - (elmt_kG4_GDP * elmt_R5_G));
        elmt_v_r7_5 = (elmt_ktherm * elmt_R5);
        elmt_v_r9 = ((elmt_kOps * elmt_Ops_Gt) - (elmt_kG4_GDP * elmt_Ops_G));
        elmt_v_r7_4 = (elmt_ktherm * elmt_R4);
        elmt_v_r8 = ((elmt_kG1ops * elmt_Ops * elmt_Gt) - (elmt_kG2ops * elmt_Ops_Gt));
        elmt_v_r7_6 = (elmt_ktherm * elmt_R6);
        elmt_v_r3_5 = (elmt_kRK3_ATP * elmt_R5_RKpre);
        elmt_v_r7_1 = (elmt_ktherm * elmt_R1);
        elmt_v_r3_4 = (elmt_kRK3_ATP * elmt_R4_RKpre);
        elmt_v_r7_0 = (elmt_ktherm * elmt_R0);
        elmt_v_r7_3 = (elmt_ktherm * elmt_R3);
        elmt_v_r7_2 = (elmt_ktherm * elmt_R2);
        elmt_v_r3_1 = (elmt_kRK3_ATP * elmt_R1_RKpre);
        elmt_v_r3_0 = (elmt_kRK3_ATP * elmt_R0_RKpre);
        elmt_v_r3_3 = (elmt_kRK3_ATP * elmt_R3_RKpre);
        elmt_v_r3_2 = (elmt_kRK3_ATP * elmt_R2_RKpre);
        der(elmt_reactant40) = 0;
        der(elmt_reactant190) = 0;
        der(elmt_reactant49) = 0;
        der(elmt_reactant43) = 0;
        der(elmt_reactant46) = 0;
        der(elmt_reactant198) = 0;
        der(elmt_product212) = 0;
        der(elmt_product214) = 0;
        der(elmt_reactant196) = 0;
        der(elmt_reactant194) = 0;
        der(elmt_reactant193) = 0;
        der(elmt_product219) = 0;
        der(elmt_product216) = 0;
        der(elmt_product215) = 0;
        der(elmt_product218) = 0;
        der(elmt_reactant199) = 0;
        der(elmt_reactant52) = 0;
        der(elmt_reactant58) = 0;
        der(elmt_reactant59) = 0;
        der(elmt_reactant55) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_product102) = 0;
        der(elmt_product222) = 0;
        der(elmt_product104) = 0;
        der(elmt_product224) = 0;
        der(elmt_product221) = 0;
        der(elmt_product100) = 0;
        der(elmt_product109) = 0;
        der(elmt_product227) = 0;
        der(elmt_product107) = 0;
        der(elmt_reactant20) = 0;
        der(elmt_product12) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_reactant175) = 0;
        der(elmt_reactant172) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_reactant178) = 0;
        der(elmt_reactant31) = 0;
        der(elmt_product21) = 0;
        der(elmt_reactant37) = 0;
        der(elmt_reactant33) = 0;
        der(elmt_reactant35) = 0;
        der(elmt_reactant187) = 0;
        der(elmt_product200) = 0;
        der(elmt_product202) = 0;
        der(elmt_reactant184) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_reactant181) = 0;
        der(elmt_product209) = 0;
        der(elmt_product208) = 0;
        der(elmt_product15) = 0;
        der(elmt_product205) = 0;
        der(elmt_product207) = 0;
        der(elmt_product18) = 0;
        der(elmt_reactant153) = 0;
        der(elmt_reactant151) = 0;
        der(elmt_reactant159) = 0;
        der(elmt_reactant157) = 0;
        der(elmt_reactant155) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant17) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_reactant165) = 0;
        der(elmt_reactant163) = 0;
        der(elmt_reactant161) = 0;
        der(elmt_reactant169) = 0;
        der(elmt_reactant167) = 0;
        der(elmt_product192) = 0;
        der(elmt_product195) = 0;
        der(elmt_product191) = 0;
        der(elmt_reactant132) = 0;
        der(elmt_reactant130) = 0;
        der(elmt_product197) = 0;
        der(elmt_reactant139) = 0;
        der(elmt_reactant138) = 0;
        der(elmt_reactant136) = 0;
        der(elmt_reactant135) = 0;
        der(elmt_reactant133) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_reactant5) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant143) = 0;
        der(elmt_reactant141) = 0;
        der(elmt_reactant149) = 0;
        der(elmt_reactant147) = 0;
        der(elmt_reactant145) = 0;
        der(elmt_product74) = 0;
        der(elmt_product72) = 0;
        der(elmt_product78) = 0;
        der(elmt_product77) = 0;
        der(elmt_product75) = 0;
        der(elmt_reactant229) = 0;
        der(elmt_reactant108) = 0;
        der(elmt_product171) = 0;
        der(elmt_product170) = 0;
        der(elmt_product173) = 0;
        der(elmt_reactant110) = 0;
        der(elmt_product179) = 0;
        der(elmt_reactant231) = 0;
        der(elmt_product174) = 0;
        der(elmt_product177) = 0;
        der(elmt_product176) = 0;
        der(elmt_reactant118) = 0;
        der(elmt_reactant117) = 0;
        der(elmt_reactant238) = 0;
        der(elmt_product69) = 0;
        der(elmt_reactant236) = 0;
        der(elmt_reactant115) = 0;
        der(elmt_reactant234) = 0;
        der(elmt_reactant112) = 0;
        der(elmt_reactant232) = 0;
        der(elmt_product84) = 0;
        der(elmt_product83) = 0;
        der(elmt_product89) = 0;
        der(elmt_product87) = 0;
        der(elmt_product86) = 0;
        der(elmt_product182) = 0;
        der(elmt_product183) = 0;
        der(elmt_product81) = 0;
        der(elmt_product80) = 0;
        der(elmt_product180) = 0;
        der(elmt_reactant121) = 0;
        der(elmt_reactant120) = 0;
        der(elmt_product189) = 0;
        der(elmt_reactant240) = 0;
        der(elmt_product186) = 0;
        der(elmt_product185) = 0;
        der(elmt_product188) = 0;
        der(elmt_reactant129) = 0;
        der(elmt_reactant127) = 0;
        der(elmt_reactant126) = 0;
        der(elmt_reactant124) = 0;
        der(elmt_reactant123) = 0;
        der(elmt_reactant243) = 0;
        der(elmt_product96) = 0;
        der(elmt_product94) = 0;
        der(elmt_product98) = 0;
        der(elmt_product150) = 0;
        der(elmt_product92) = 0;
        der(elmt_product90) = 0;
        der(elmt_product156) = 0;
        der(elmt_product158) = 0;
        der(elmt_product152) = 0;
        der(elmt_product154) = 0;
        der(elmt_reactant217) = 0;
        der(elmt_reactant213) = 0;
        der(elmt_reactant211) = 0;
        der(elmt_reactant210) = 0;
        der(elmt_product9) = 0;
        der(elmt_product6) = 0;
        der(elmt_product1) = 0;
        der(elmt_product160) = 0;
        der(elmt_product162) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant220) = 0;
        der(elmt_product168) = 0;
        der(elmt_product164) = 0;
        der(elmt_product166) = 0;
        der(elmt_reactant228) = 0;
        der(elmt_reactant106) = 0;
        der(elmt_reactant226) = 0;
        der(elmt_reactant105) = 0;
        der(elmt_reactant225) = 0;
        der(elmt_reactant103) = 0;
        der(elmt_reactant223) = 0;
        der(elmt_reactant101) = 0;
        der(elmt_product30) = 0;
        der(elmt_reactant85) = 0;
        der(elmt_product34) = 0;
        der(elmt_product32) = 0;
        der(elmt_reactant82) = 0;
        der(elmt_reactant88) = 0;
        der(elmt_product134) = 0;
        der(elmt_product137) = 0;
        der(elmt_product131) = 0;
        der(elmt_product26) = 0;
        der(elmt_product24) = 0;
        der(elmt_product28) = 0;
        der(elmt_product41) = 0;
        der(elmt_reactant95) = 0;
        der(elmt_reactant97) = 0;
        der(elmt_product45) = 0;
        der(elmt_product44) = 0;
        der(elmt_reactant91) = 0;
        der(elmt_product42) = 0;
        der(elmt_reactant93) = 0;
        der(elmt_product140) = 0;
        der(elmt_reactant99) = 0;
        der(elmt_product146) = 0;
        der(elmt_product148) = 0;
        der(elmt_product142) = 0;
        der(elmt_product144) = 0;
        der(elmt_reactant206) = 0;
        der(elmt_product38) = 0;
        der(elmt_reactant204) = 0;
        der(elmt_product36) = 0;
        der(elmt_reactant203) = 0;
        der(elmt_reactant201) = 0;
        der(elmt_product39) = 0;
        der(elmt_reactant61) = 0;
        der(elmt_reactant62) = 0;
        der(elmt_product51) = 0;
        der(elmt_product50) = 0;
        der(elmt_reactant64) = 0;
        der(elmt_product54) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant65) = 0;
        der(elmt_reactant67) = 0;
        der(elmt_reactant68) = 0;
        der(elmt_product113) = 0;
        der(elmt_product233) = 0;
        der(elmt_product114) = 0;
        der(elmt_product235) = 0;
        der(elmt_product230) = 0;
        der(elmt_product111) = 0;
        der(elmt_product48) = 0;
        der(elmt_product47) = 0;
        der(elmt_product237) = 0;
        der(elmt_product116) = 0;
        der(elmt_product119) = 0;
        der(elmt_product239) = 0;
        der(elmt_product63) = 0;
        der(elmt_reactant73) = 0;
        der(elmt_product60) = 0;
        der(elmt_product66) = 0;
        der(elmt_reactant70) = 0;
        der(elmt_reactant71) = 0;
        der(elmt_reactant76) = 0;
        der(elmt_reactant79) = 0;
        der(elmt_product125) = 0;
        der(elmt_product241) = 0;
        der(elmt_product122) = 0;
        der(elmt_product242) = 0;
        der(elmt_product57) = 0;
        der(elmt_product128) = 0;

end Reactions;
