within BIOMD338;
class Reactions

    input Real elmt_PS;
    input Real elmt_d_VK2;
    input Real elmt_d_VIII;
    input Real elmt_Xa;
    input Real elmt_PC;
    input Real elmt_IC50;
    input Real elmt_XI;
    input Real elmt_Heparin_ke;
    input Real elmt_compartment_1;
    input Real elmt_Xa_ATIII_Heparin;
    input Real elmt_Va_Xa;
    input Real elmt_d_Tmod;
    input Real elmt_I_max;
    input Real elmt_ATIII_Heparin;
    input Real elmt_II;
    input Real elmt_VKH2;
    input Real elmt_Tmod0;
    input Real elmt_VK_p;
    input Real elmt_IIa_ATIII_Heparin;
    input Real elmt_IX0;
    input Real elmt_Pk;
    input Real elmt_d_VKO;
    input Real elmt_Pg;
    input Real elmt_VII;
    input Real elmt_APC;
    input Real elmt_d_XIII;
    input Real elmt_Va;
    input Real elmt_VitaminK_k12;
    input Real elmt_IXa_ATIII_Heparin;
    input Real elmt_Pg0;
    input Real elmt_VK;
    input Real elmt_VII0;
    input Real elmt_C_warf;
    input Real elmt_II0;
    input Real elmt_TFPI0;
    input Real elmt_Fg;
    input Real elmt_Tmod;
    input Real elmt_IXa;
    input Real elmt_VIIa;
    input Real elmt_XF;
    input Real elmt_VK0;
    input Real elmt_d_TFPI;
    input Real elmt_c46;
    input Real elmt_c45;
    input Real elmt_c44;
    input Real elmt_X0;
    input Real elmt_d_VII;
    input Real elmt_VIII;
    input Real elmt_d_Pg;
    input Real elmt_d_Pk;
    input Real elmt_IIa_Tmod;
    input Real elmt_VIII0;
    input Real elmt_d_X;
    input Real elmt_d_V;
    input Real elmt_d_II;
    input Real elmt_VKO;
    input Real elmt_XII0;
    input Real elmt_TF;
    input Real elmt_VII_TF;
    input Real elmt_IIa;
    input Real elmt_X;
    input Real elmt_d_IX;
    input Real elmt_V;
    input Real elmt_XIIIa;
    input Real elmt_P;
    input Real elmt_XIIa;
    input Real elmt_K;
    input Real elmt_TFPI;
    input Real elmt_FDP;
    input Real elmt_XI0;
    input Real elmt_F;
    input Real elmt_VIIa_TF_Xa_TFPI;
    input Real elmt_XIII0;
    input Real elmt_D;
    input Real elmt_d_PS;
    input Real elmt_VIIIa;
    input Real elmt_Fg0;
    input Real elmt_XIII;
    input Real elmt_APC_PS;
    input Real elmt_V0;
    input Real elmt_IXa_VIIIa;
    input Real elmt_XII;
    input Real elmt_Pk0;
    input Real elmt_Xa_TFPI;
    input Real elmt_VKH20;
    input Real elmt_d_Fg;
    input Real elmt_VIIa_TF;
    input Real elmt_TAT;
    input Real elmt_IX;
    input Real elmt_XIa;
    input Real elmt_PS0;
    input Real elmt_VitaminK_k21_Vc;
    input Real elmt_d_XI;
    input Real elmt_d_PC;
    input Real elmt_d_VK;
    input Real elmt_PC0;
    input Real elmt_d_VKH2;
    input Real elmt_CA;
    input Real elmt_d_XII;

    Real elmt_dVKH2(unit = "") "dVKH2";
    Real elmt_product157 "";
    Real elmt_reactant156 "";
    Real elmt_r5_(unit = "") "r5 ";
    parameter Real elmt_r5__elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r5__elmt_v(unit "") = 10.0 "";
    Real elmt_product8 "";
    Real elmt_reactant7 "";
    Real elmt_dIIa(unit = "") "dIIa";
    parameter Real elmt_dIIa_elmt_k1(unit "") = 67.4 "";
    Real elmt_reactant117 "";
    Real elmt_product118 "";
    Real elmt_pTFPI(unit = "") "pTFPI";
    Real elmt_product173 "";
    Real elmt_pX_VKH2(unit = "") "pX_VKH2";
    Real elmt_product107 "";
    Real elmt_dCA(unit = "") "dCA";
    parameter Real elmt_dCA_elmt_k1(unit "") = 0.05 "";
    Real elmt_reactant154 "";
    Real elmt_pPS_VKH2(unit = "") "pPS_VKH2";
    Real elmt_product109 "";
    Real elmt_dFDP(unit = "") "dFDP";
    parameter Real elmt_dFDP_elmt_k1(unit "") = 3.5 "";
    Real elmt_reactant141 "";
    Real elmt_eHeparinIXa(unit = "") "eHeparinIXa";
    Real elmt_reactant162 "";
    Real elmt_dTF(unit = "") "dTF";
    parameter Real elmt_dTF_elmt_k1(unit "") = 0.05 "";
    Real elmt_reactant119 "";
    Real elmt_dAPC_PS(unit = "") "dAPC_PS";
    parameter Real elmt_dAPC_PS_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant146 "";
    Real elmt_pXIII(unit = "") "pXIII";
    Real elmt_product170 "";
    Real elmt_r6_(unit = "") "r6 ";
    parameter Real elmt_r6__elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r6__elmt_v(unit "") = 0.1 "";
    Real elmt_product10 "";
    Real elmt_reactant9 "";
    Real elmt_dAPC(unit = "") "dAPC";
    parameter Real elmt_dAPC_elmt_k1(unit "") = 20.4 "";
    Real elmt_reactant139 "";
    Real elmt_dVII(unit = "") "dVII";
    Real elmt_reactant122 "";
    Real elmt_r7_(unit = "") "r7 ";
    parameter Real elmt_r7__elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r7__elmt_v(unit "") = 0.02 "";
    Real elmt_product12 "";
    Real elmt_reactant11 "";
    Real elmt_dVII_TF(unit = "") "dVII_TF";
    parameter Real elmt_dVII_TF_elmt_k1(unit "") = 0.7 "";
    Real elmt_reactant145 "";
    Real elmt_dVIIa(unit = "") "dVIIa";
    parameter Real elmt_dVIIa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant123 "";
    Real elmt_dVIII(unit = "") "dVIII";
    Real elmt_reactant124 "";
    Real elmt_dIXa(unit = "") "dIXa";
    parameter Real elmt_dIXa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant129 "";
    Real elmt_r17(unit = "") "r17";
    parameter Real elmt_r17_elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r17_elmt_v(unit "") = 7.0 "";
    Real elmt_reactant30 "";
    Real elmt_product31 "";
    Real elmt_r16(unit = "") "r16";
    parameter Real elmt_r16_elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r16_elmt_v(unit "") = 7.0 "";
    Real elmt_reactant28 "";
    Real elmt_product29 "";
    Real elmt_pV(unit = "") "pV";
    Real elmt_product168 "";
    Real elmt_r15(unit = "") "r15";
    parameter Real elmt_r15_elmt_k(unit "") = 500.0 "";
    parameter Real elmt_r15_elmt_v(unit "") = 500.0 "";
    Real elmt_product27 "";
    Real elmt_reactant26 "";
    Real elmt_r14(unit = "") "r14";
    parameter Real elmt_r14_elmt_k(unit "") = 0.5 "";
    parameter Real elmt_r14_elmt_v(unit "") = 20000.0 "";
    Real elmt_product25 "";
    Real elmt_reactant24 "";
    Real elmt_r13(unit = "") "r13";
    parameter Real elmt_r13_elmt_k(unit "") = 500.0 "";
    parameter Real elmt_r13_elmt_v(unit "") = 9.0 "";
    Real elmt_product23 "";
    Real elmt_reactant22 "";
    Real elmt_r12(unit = "") "r12";
    parameter Real elmt_r12_elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r12_elmt_v(unit "") = 100.0 "";
    Real elmt_reactant20 "";
    Real elmt_product21 "";
    Real elmt_r11(unit = "") "r11";
    parameter Real elmt_r11_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r11_elmt_v(unit "") = 50.0 "";
    Real elmt_reactant19 "";
    Real elmt_r10(unit = "") "r10";
    parameter Real elmt_r10_elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r10_elmt_v(unit "") = 50000.0 "";
    Real elmt_reactant17 "";
    Real elmt_product18 "";
    Real elmt_r19(unit = "") "r19";
    parameter Real elmt_r19_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r19_elmt_v(unit "") = 1.0 "";
    Real elmt_product35 "";
    Real elmt_reactant34 "";
    Real elmt_r8_(unit = "") "r8 ";
    parameter Real elmt_r8__elmt_k(unit "") = 0.1 "";
    parameter Real elmt_r8__elmt_v(unit "") = 2.0 "";
    Real elmt_product14 "";
    Real elmt_reactant13 "";
    Real elmt_r18(unit = "") "r18";
    parameter Real elmt_r18_elmt_k(unit "") = 100.0 "";
    parameter Real elmt_r18_elmt_v(unit "") = 7.0 "";
    Real elmt_product33 "";
    Real elmt_reactant32 "";
    Real elmt_dVK(unit = "") "dVK";
    Real elmt_reactant176 "";
    Real elmt_dTmod(unit = "") "dTmod";
    Real elmt_reactant149 "";
    Real elmt_dVIIa_TF(unit = "") "dVIIa_TF";
    parameter Real elmt_dVIIa_TF_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant144 "";
    Real elmt_pVK(unit = "") "pVK";
    Real elmt_product175 "";
    Real elmt_r20(unit = "") "r20";
    parameter Real elmt_r20_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r20_elmt_v(unit "") = 7.0 "";
    Real elmt_reactant36 "";
    Real elmt_product37 "";
    Real elmt_dVa(unit = "") "dVa";
    parameter Real elmt_dVa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant121 "";
    Real elmt_pVII_VKH2(unit = "") "pVII_VKH2";
    Real elmt_product105 "";
    Real elmt_pXII(unit = "") "pXII";
    Real elmt_product165 "";
    Real elmt_r9_(unit = "") "r9 ";
    parameter Real elmt_r9__elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r9__elmt_v(unit "") = 1.0E-9 "";
    Real elmt_product16 "";
    Real elmt_reactant15 "";
    Real elmt_r28(unit = "") "r28";
    parameter Real elmt_r28_elmt_c(unit "") = 0.5 "";
    Real elmt_reactant53 "";
    Real elmt_product55 "";
    Real elmt_reactant54 "";
    Real elmt_r27(unit = "") "r27";
    parameter Real elmt_r27_elmt_c(unit "") = 0.5 "";
    Real elmt_reactant50 "";
    Real elmt_product52 "";
    Real elmt_reactant51 "";
    Real elmt_r26(unit = "") "r26";
    parameter Real elmt_r26_elmt_c(unit "") = 0.01 "";
    Real elmt_reactant47 "";
    Real elmt_product49 "";
    Real elmt_reactant48 "";
    Real elmt_r25(unit = "") "r25";
    parameter Real elmt_r25_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r25_elmt_v(unit "") = 2.0 "";
    Real elmt_reactant46 "";
    Real elmt_r24(unit = "") "r24";
    parameter Real elmt_r24_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r24_elmt_v(unit "") = 7.0 "";
    Real elmt_product45 "";
    Real elmt_reactant44 "";
    Real elmt_r23(unit = "") "r23";
    parameter Real elmt_r23_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r23_elmt_v(unit "") = 2.0 "";
    Real elmt_reactant42 "";
    Real elmt_product43 "";
    Real elmt_r22(unit = "") "r22";
    parameter Real elmt_r22_elmt_k(unit "") = 10000.0 "";
    parameter Real elmt_r22_elmt_v(unit "") = 5.0 "";
    Real elmt_product41 "";
    Real elmt_reactant40 "";
    Real elmt_r21(unit = "") "r21";
    parameter Real elmt_r21_elmt_k(unit "") = 5000.0 "";
    parameter Real elmt_r21_elmt_v(unit "") = 7.0 "";
    Real elmt_reactant38 "";
    Real elmt_product39 "";
    Real elmt_r1_(unit = "") "r1 ";
    parameter Real elmt_r1__elmt_k(unit "") = 1.0E-6 "";
    parameter Real elmt_r1__elmt_v(unit "") = 50000.0 "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_dXIIa(unit = "") "dXIIa";
    parameter Real elmt_dXIIa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant131 "";
    Real elmt_dTFPI(unit = "") "dTFPI";
    Real elmt_reactant143 "";
    Real elmt_r29(unit = "") "r29";
    parameter Real elmt_r29_elmt_c(unit "") = 0.5 "";
    Real elmt_product58 "";
    Real elmt_reactant56 "";
    Real elmt_reactant57 "";
    Real elmt_pPC_VKH2(unit = "") "pPC_VKH2";
    Real elmt_product108 "";
    Real elmt_dIIa_Tmod(unit = "") "dIIa_Tmod";
    parameter Real elmt_dIIa_Tmod_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant150 "";
    Real elmt_dFg(unit = "") "dFg";
    Real elmt_reactant110 "";
    Real elmt_product111 "";
    Real elmt_dX(unit = "") "dX";
    Real elmt_reactant126 "";
    Real elmt_dV(unit = "") "dV";
    Real elmt_reactant120 "";
    Real elmt_dXIII(unit = "") "dXIII";
    Real elmt_reactant132 "";
    Real elmt_r31(unit = "") "r31";
    parameter Real elmt_r31_elmt_c(unit "") = 0.5 "";
    Real elmt_reactant62 "";
    Real elmt_reactant63 "";
    Real elmt_product64 "";
    Real elmt_r30(unit = "") "r30";
    parameter Real elmt_r30_elmt_c(unit "") = 0.1 "";
    Real elmt_product61 "";
    Real elmt_reactant60 "";
    Real elmt_reactant59 "";
    Real elmt_r39(unit = "") "r39";
    parameter Real elmt_r39_elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r39_elmt_v(unit "") = 1.0 "";
    Real elmt_product82 "";
    Real elmt_reactant81 "";
    Real elmt_r38(unit = "") "r38";
    parameter Real elmt_r38_elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r38_elmt_v(unit "") = 1.0 "";
    Real elmt_product80 "";
    Real elmt_reactant79 "";
    Real elmt_dPC(unit = "") "dPC";
    Real elmt_reactant138 "";
    Real elmt_r37(unit = "") "r37";
    parameter Real elmt_r37_elmt_c(unit "") = 0.5 "";
    Real elmt_product78 "";
    Real elmt_reactant76 "";
    Real elmt_reactant77 "";
    Real elmt_r36(unit = "") "r36";
    parameter Real elmt_r36_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r36_elmt_v(unit "") = 1000.0 "";
    Real elmt_reactant74 "";
    Real elmt_product75 "";
    Real elmt_dXI(unit = "") "dXI";
    parameter Real elmt_dXI_elmt_k1(unit "") = 0.1 "";
    Real elmt_reactant164 "";
    Real elmt_r35(unit = "") "r35";
    parameter Real elmt_r35_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r35_elmt_v(unit "") = 70.0 "";
    Real elmt_reactant72 "";
    Real elmt_product73 "";
    Real elmt_r34(unit = "") "r34";
    parameter Real elmt_r34_elmt_k(unit "") = 200.0 "";
    parameter Real elmt_r34_elmt_v(unit "") = 900.0 "";
    Real elmt_product71 "";
    Real elmt_reactant70 "";
    Real elmt_r33(unit = "") "r33";
    parameter Real elmt_r33_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r33_elmt_v(unit "") = 70.0 "";
    Real elmt_product69 "";
    Real elmt_reactant68 "";
    Real elmt_dXF(unit = "") "dXF";
    parameter Real elmt_dXF_elmt_k1(unit "") = 0.05 "";
    Real elmt_product115 "";
    Real elmt_reactant114 "";
    Real elmt_r32(unit = "") "r32";
    parameter Real elmt_r32_elmt_c(unit "") = 0.5 "";
    Real elmt_product67 "";
    Real elmt_reactant65 "";
    Real elmt_reactant66 "";
    Real elmt_pFg(unit = "") "pFg";
    Real elmt_product169 "";
    Real elmt_r2_(unit = "") "r2 ";
    parameter Real elmt_r2__elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r2__elmt_v(unit "") = 50.0 "";
    Real elmt_reactant2 "";
    Real elmt_dPS(unit = "") "dPS";
    Real elmt_reactant140 "";
    Real elmt_dVa_Xa(unit = "") "dVa_Xa";
    parameter Real elmt_dVa_Xa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant147 "";
    Real elmt_dIXa_VIIIa(unit = "") "dIXa_VIIIa";
    parameter Real elmt_dIXa_VIIIa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant148 "";
    Real elmt_pXI(unit = "") "pXI";
    Real elmt_product167 "";
    Real elmt_r42(unit = "") "r42";
    parameter Real elmt_r42_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r42_elmt_v(unit "") = 70.0 "";
    Real elmt_product88 "";
    Real elmt_reactant87 "";
    Real elmt_r41(unit = "") "r41";
    parameter Real elmt_r41_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r41_elmt_v(unit "") = 7.0 "";
    Real elmt_reactant85 "";
    Real elmt_product86 "";
    Real elmt_r40(unit = "") "r40";
    parameter Real elmt_r40_elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r40_elmt_v(unit "") = 0.2 "";
    Real elmt_reactant83 "";
    Real elmt_product84 "";
    Real elmt_dXa(unit = "") "dXa";
    parameter Real elmt_dXa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant127 "";
    Real elmt_dXa_TFPI(unit = "") "dXa_TFPI";
    parameter Real elmt_dXa_TFPI_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant151 "";
    Real elmt_r48(unit = "") "r48";
    Real elmt_product103 "";
    Real elmt_reactant102 "";
    Real elmt_r47(unit = "") "r47";
    Real elmt_product101 "";
    Real elmt_reactant100 "";
    Real elmt_r46(unit = "") "r46";
    Real elmt_reactant97 "";
    Real elmt_product99 "";
    Real elmt_reactant98 "";
    Real elmt_dXII(unit = "") "dXII";
    Real elmt_reactant130 "";
    Real elmt_r45(unit = "") "r45";
    Real elmt_reactant94 "";
    Real elmt_product96 "";
    Real elmt_reactant95 "";
    Real elmt_r44(unit = "") "r44";
    Real elmt_product93 "";
    Real elmt_reactant91 "";
    Real elmt_reactant92 "";
    Real elmt_r43(unit = "") "r43";
    parameter Real elmt_r43_elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r43_elmt_v(unit "") = 7.0 "";
    Real elmt_reactant89 "";
    Real elmt_product90 "";
    Real elmt_dPk(unit = "") "dPk";
    Real elmt_reactant134 "";
    Real elmt_r3_(unit = "") "r3 ";
    parameter Real elmt_r3__elmt_k(unit "") = 10.0 "";
    parameter Real elmt_r3__elmt_v(unit "") = 7.0 "";
    Real elmt_reactant3 "";
    Real elmt_product4 "";
    Real elmt_dPg(unit = "") "dPg";
    Real elmt_reactant136 "";
    Real elmt_eHeparinXa(unit = "") "eHeparinXa";
    Real elmt_reactant161 "";
    Real elmt_dVIIIa(unit = "") "dVIIIa";
    parameter Real elmt_dVIIIa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant125 "";
    Real elmt_pPg(unit = "") "pPg";
    Real elmt_product171 "";
    Real elmt_dII(unit = "") "dII";
    Real elmt_reactant116 "";
    Real elmt_pTmod(unit = "") "pTmod";
    Real elmt_product172 "";
    Real elmt_dTAT(unit = "") "dTAT";
    parameter Real elmt_dTAT_elmt_k1(unit "") = 0.2 "";
    Real elmt_reactant153 "";
    Real elmt_dXIa(unit = "") "dXIa";
    parameter Real elmt_dXIa_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant155 "";
    Real elmt_pPk(unit = "") "pPk";
    Real elmt_product174 "";
    Real elmt_dVIIa_TF_Xa_TFPI(unit = "") "dVIIa_TF_Xa_TFPI";
    parameter Real elmt_dVIIa_TF_Xa_TFPI_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant152 "";
    Real elmt_dF(unit = "") "dF";
    parameter Real elmt_dF_elmt_k1(unit "") = 0.05 "";
    Real elmt_product113 "";
    Real elmt_reactant112 "";
    Real elmt_dIX(unit = "") "dIX";
    Real elmt_reactant128 "";
    Real elmt_dD(unit = "") "dD";
    parameter Real elmt_dD_elmt_k1(unit "") = 0.1 "";
    Real elmt_reactant142 "";
    Real elmt_pVIII(unit = "") "pVIII";
    Real elmt_product166 "";
    Real elmt_r4_(unit = "") "r4 ";
    parameter Real elmt_r4__elmt_k(unit "") = 1.0 "";
    parameter Real elmt_r4__elmt_v(unit "") = 7.0 "";
    Real elmt_product6 "";
    Real elmt_reactant5 "";
    Real elmt_dP(unit = "") "dP";
    parameter Real elmt_dP_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant137 "";
    Real elmt_dXIIIa(unit = "") "dXIIIa";
    parameter Real elmt_dXIIIa_elmt_k1(unit "") = 0.69 "";
    Real elmt_reactant133 "";
    Real elmt_eHeparin(unit = "") "eHeparin";
    Real elmt_reactant160 "";
    Real elmt_dK(unit = "") "dK";
    parameter Real elmt_dK_elmt_k1(unit "") = 20.0 "";
    Real elmt_reactant135 "";
    Real elmt_pII_VKH2(unit = "") "pII_VKH2";
    Real elmt_product104 "";
    Real elmt_eHeparinIIa(unit = "") "eHeparinIIa";
    Real elmt_reactant163 "";
    Real elmt_pIX_VKH2(unit = "") "pIX_VKH2";
    Real elmt_product106 "";
    Real elmt_VK_transport(unit = "") "VK_transport";
    Real elmt_product159 "";
    Real elmt_reactant158 "";


    initial equation
        elmt_reactant40 = 1.0;
        elmt_product73 = 1.0;
        elmt_reactant42 = 1.0;
        elmt_product71 = 1.0;
        elmt_product78 = 1.0;
        elmt_product75 = 1.0;
        elmt_reactant47 = 1.0;
        elmt_product171 = 1.0;
        elmt_product170 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_product173 = 1.0;
        elmt_product172 = 1.0;
        elmt_reactant44 = 1.0;
        elmt_reactant46 = 1.0;
        elmt_reactant110 = 1.0;
        elmt_product175 = 1.0;
        elmt_product174 = 1.0;
        elmt_reactant117 = 1.0;
        elmt_product69 = 1.0;
        elmt_reactant116 = 1.0;
        elmt_reactant114 = 1.0;
        elmt_reactant112 = 1.0;
        elmt_reactant50 = 1.0;
        elmt_reactant51 = 1.0;
        elmt_product84 = 1.0;
        elmt_reactant53 = 1.0;
        elmt_product82 = 1.0;
        elmt_product88 = 1.0;
        elmt_reactant119 = 1.0;
        elmt_product86 = 1.0;
        elmt_reactant59 = 1.0;
        elmt_reactant54 = 1.0;
        elmt_product80 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_reactant57 = 1.0;
        elmt_reactant121 = 1.0;
        elmt_reactant120 = 1.0;
        elmt_product101 = 1.0;
        elmt_product104 = 1.0;
        elmt_product103 = 1.0;
        elmt_reactant129 = 1.0;
        elmt_product109 = 1.0;
        elmt_reactant128 = 1.0;
        elmt_reactant127 = 1.0;
        elmt_reactant126 = 1.0;
        elmt_reactant125 = 1.0;
        elmt_product106 = 1.0;
        elmt_reactant124 = 1.0;
        elmt_product105 = 1.0;
        elmt_reactant123 = 1.0;
        elmt_product108 = 1.0;
        elmt_product107 = 1.0;
        elmt_reactant122 = 1.0;
        elmt_product96 = 1.0;
        elmt_reactant20 = 1.0;
        elmt_product93 = 1.0;
        elmt_product12 = 1.0;
        elmt_product99 = 1.0;
        elmt_product10 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_product90 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_product157 = 1.0;
        elmt_reactant176 = 1.0;
        elmt_product159 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product8 = 1.0;
        elmt_reactant30 = 1.0;
        elmt_product6 = 1.0;
        elmt_product23 = 1.0;
        elmt_product21 = 1.0;
        elmt_reactant36 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant38 = 1.0;
        elmt_reactant32 = 1.0;
        elmt_product4 = 1.0;
        elmt_reactant34 = 1.0;
        elmt_product168 = 1.0;
        elmt_product167 = 1.0;
        elmt_product169 = 1.0;
        elmt_product166 = 1.0;
        elmt_product165 = 1.0;
        elmt_product16 = 1.0;
        elmt_product14 = 1.0;
        elmt_reactant102 = 1.0;
        elmt_product18 = 1.0;
        elmt_reactant100 = 1.0;
        elmt_reactant83 = 1.0;
        elmt_reactant85 = 1.0;
        elmt_product33 = 1.0;
        elmt_reactant81 = 1.0;
        elmt_product31 = 1.0;
        elmt_reactant87 = 1.0;
        elmt_reactant89 = 1.0;
        elmt_reactant154 = 1.0;
        elmt_reactant153 = 1.0;
        elmt_reactant152 = 1.0;
        elmt_reactant151 = 1.0;
        elmt_reactant150 = 1.0;
        elmt_product27 = 1.0;
        elmt_reactant9 = 1.0;
        elmt_product25 = 1.0;
        elmt_reactant158 = 1.0;
        elmt_reactant156 = 1.0;
        elmt_product29 = 1.0;
        elmt_reactant155 = 1.0;
        elmt_product41 = 1.0;
        elmt_reactant94 = 1.0;
        elmt_reactant95 = 1.0;
        elmt_reactant97 = 1.0;
        elmt_product45 = 1.0;
        elmt_reactant91 = 1.0;
        elmt_product43 = 1.0;
        elmt_reactant92 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_reactant17 = 1.0;
        elmt_reactant98 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_reactant164 = 1.0;
        elmt_reactant163 = 1.0;
        elmt_reactant162 = 1.0;
        elmt_reactant161 = 1.0;
        elmt_reactant160 = 1.0;
        elmt_product37 = 1.0;
        elmt_product35 = 1.0;
        elmt_product39 = 1.0;
        elmt_product52 = 1.0;
        elmt_reactant62 = 1.0;
        elmt_reactant63 = 1.0;
        elmt_product55 = 1.0;
        elmt_reactant60 = 1.0;
        elmt_reactant65 = 1.0;
        elmt_reactant66 = 1.0;
        elmt_reactant68 = 1.0;
        elmt_reactant132 = 1.0;
        elmt_product113 = 1.0;
        elmt_reactant131 = 1.0;
        elmt_product115 = 1.0;
        elmt_reactant130 = 1.0;
        elmt_product111 = 1.0;
        elmt_product49 = 1.0;
        elmt_reactant139 = 1.0;
        elmt_reactant138 = 1.0;
        elmt_reactant137 = 1.0;
        elmt_reactant136 = 1.0;
        elmt_reactant135 = 1.0;
        elmt_reactant134 = 1.0;
        elmt_product118 = 1.0;
        elmt_reactant133 = 1.0;
        elmt_reactant72 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product61 = 1.0;
        elmt_reactant74 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_product67 = 1.0;
        elmt_reactant5 = 1.0;
        elmt_reactant70 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_product64 = 1.0;
        elmt_reactant76 = 1.0;
        elmt_reactant77 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant79 = 1.0;
        elmt_reactant143 = 1.0;
        elmt_reactant142 = 1.0;
        elmt_reactant141 = 1.0;
        elmt_reactant140 = 1.0;
        elmt_reactant149 = 1.0;
        elmt_product58 = 1.0;
        elmt_reactant148 = 1.0;
        elmt_reactant147 = 1.0;
        elmt_reactant146 = 1.0;
        elmt_reactant145 = 1.0;
        elmt_reactant144 = 1.0;


    equation
        elmt_dVKH2 = (elmt_compartment_1 * elmt_d_VKH2 * elmt_VKH2);
        elmt_r5_ = (elmt_compartment_1 * (((elmt_r5__elmt_v * elmt_XI * elmt_IIa) / (elmt_r5__elmt_k + elmt_IIa))));
        elmt_dIIa = (elmt_compartment_1 * elmt_dIIa_elmt_k1 * elmt_IIa);
        elmt_pTFPI = (elmt_compartment_1 * ((elmt_TFPI0 * elmt_d_TFPI)));
        elmt_pX_VKH2 = (elmt_compartment_1 * (((elmt_d_X * elmt_X0 * elmt_VKH2) / elmt_VKH20)));
        elmt_dCA = (elmt_compartment_1 * elmt_dCA_elmt_k1 * elmt_CA);
        elmt_pPS_VKH2 = (elmt_compartment_1 * (((elmt_d_PS * elmt_PS0 * elmt_VKH2) / elmt_VKH20)));
        elmt_dFDP = (elmt_compartment_1 * elmt_dFDP_elmt_k1 * elmt_FDP);
        elmt_eHeparinIXa = (elmt_compartment_1 * elmt_Heparin_ke * elmt_IXa_ATIII_Heparin);
        elmt_dTF = (elmt_compartment_1 * elmt_dTF_elmt_k1 * elmt_TF);
        elmt_dAPC_PS = (elmt_compartment_1 * elmt_dAPC_PS_elmt_k1 * elmt_APC_PS);
        elmt_pXIII = (elmt_compartment_1 * ((elmt_XIII0 * elmt_d_XIII)));
        elmt_r6_ = (elmt_compartment_1 * (((elmt_r6__elmt_v * elmt_VII * elmt_IIa) / (elmt_r6__elmt_k + elmt_IIa))));
        elmt_dAPC = (elmt_compartment_1 * elmt_dAPC_elmt_k1 * elmt_APC);
        elmt_dVII = (elmt_compartment_1 * elmt_d_VII * elmt_VII);
        elmt_r7_ = (elmt_compartment_1 * (((elmt_r7__elmt_v * elmt_X * elmt_IXa) / (elmt_r7__elmt_k + elmt_IXa))));
        elmt_dVII_TF = (elmt_compartment_1 * elmt_dVII_TF_elmt_k1 * elmt_VII_TF);
        elmt_dVIIa = (elmt_compartment_1 * elmt_dVIIa_elmt_k1 * elmt_VIIa);
        elmt_dVIII = (elmt_compartment_1 * elmt_d_VIII * elmt_VIII);
        elmt_dIXa = (elmt_compartment_1 * elmt_dIXa_elmt_k1 * elmt_IXa);
        elmt_r17 = (elmt_compartment_1 * (((elmt_r17_elmt_v * elmt_F * elmt_P) / (elmt_r17_elmt_k + elmt_P))));
        elmt_r16 = (elmt_compartment_1 * (((elmt_r16_elmt_v * elmt_F * elmt_XIIIa) / (elmt_r16_elmt_k + elmt_XIIIa))));
        elmt_pV = (elmt_compartment_1 * ((elmt_V0 * elmt_d_V)));
        elmt_r15 = (elmt_compartment_1 * (((elmt_r15_elmt_v * elmt_Fg * elmt_P) / (elmt_r15_elmt_k + elmt_P))));
        elmt_r14 = (elmt_compartment_1 * (((elmt_r14_elmt_v * elmt_Fg * elmt_IIa) / (elmt_r14_elmt_k + elmt_IIa))));
        elmt_r13 = (elmt_compartment_1 * (((elmt_r13_elmt_v * elmt_II * elmt_Xa) / (elmt_r13_elmt_k + elmt_Xa))));
        elmt_r12 = (elmt_compartment_1 * (((elmt_r12_elmt_v * elmt_II * elmt_Va_Xa) / (elmt_r12_elmt_k + elmt_Va_Xa))));
        elmt_r11 = (elmt_compartment_1 * (((elmt_r11_elmt_v * elmt_Va * elmt_APC_PS) / (elmt_r11_elmt_k + elmt_APC_PS))));
        elmt_r10 = (elmt_compartment_1 * (((elmt_r10_elmt_v * elmt_V * elmt_IIa) / (elmt_r10_elmt_k + elmt_IIa))));
        elmt_r19 = (elmt_compartment_1 * (((elmt_r19_elmt_v * elmt_XF * elmt_APC_PS) / (elmt_r19_elmt_k + elmt_APC_PS))));
        elmt_r8_ = (elmt_compartment_1 * (((elmt_r8__elmt_v * elmt_X * elmt_IXa_VIIIa) / (elmt_r8__elmt_k + elmt_IXa_VIIIa))));
        elmt_r18 = (elmt_compartment_1 * (((elmt_r18_elmt_v * elmt_XF * elmt_P) / (elmt_r18_elmt_k + elmt_P))));
        elmt_dVK = (elmt_compartment_1 * elmt_d_VK * elmt_VK);
        elmt_dTmod = (elmt_compartment_1 * elmt_d_Tmod * elmt_Tmod);
        elmt_dVIIa_TF = (elmt_compartment_1 * elmt_dVIIa_TF_elmt_k1 * elmt_VIIa_TF);
        elmt_pVK = (elmt_compartment_1 * ((elmt_VK0 * elmt_d_VK)));
        elmt_r20 = (elmt_compartment_1 * (((elmt_r20_elmt_v * elmt_XIII * elmt_IIa) / (elmt_r20_elmt_k + elmt_IIa))));
        elmt_dVa = (elmt_compartment_1 * elmt_dVa_elmt_k1 * elmt_Va);
        elmt_pVII_VKH2 = (elmt_compartment_1 * (((elmt_d_VII * elmt_VII0 * elmt_VKH2) / elmt_VKH20)));
        elmt_pXII = (elmt_compartment_1 * ((elmt_XII0 * elmt_d_XII)));
        elmt_r9_ = (elmt_compartment_1 * (((elmt_r9__elmt_v * elmt_X * elmt_VIIa) / (elmt_r9__elmt_k + elmt_VIIa))));
        elmt_r28 = (elmt_compartment_1 * (((elmt_IIa * elmt_Tmod) / elmt_r28_elmt_c)));
        elmt_r27 = (elmt_compartment_1 * (((elmt_Va * elmt_Xa) / elmt_r27_elmt_c)));
        elmt_r26 = (elmt_compartment_1 * (((elmt_IXa * elmt_VIIIa) / elmt_r26_elmt_c)));
        elmt_r25 = (elmt_compartment_1 * (((elmt_r25_elmt_v * elmt_Va_Xa * elmt_APC_PS) / (elmt_r25_elmt_k + elmt_APC_PS))));
        elmt_r24 = (elmt_compartment_1 * (((elmt_r24_elmt_v * elmt_PC * elmt_IIa_Tmod) / (elmt_r24_elmt_k + elmt_IIa_Tmod))));
        elmt_r23 = (elmt_compartment_1 * (((elmt_r23_elmt_v * elmt_Pg * elmt_APC_PS) / (elmt_r23_elmt_k + elmt_APC_PS))));
        elmt_r22 = (elmt_compartment_1 * (((elmt_r22_elmt_v * elmt_Pg * elmt_F) / (elmt_r22_elmt_k + elmt_F))));
        elmt_r21 = (elmt_compartment_1 * (((elmt_r21_elmt_v * elmt_Pg * elmt_IIa) / (elmt_r21_elmt_k + elmt_IIa))));
        elmt_r1_ = (elmt_compartment_1 * (((elmt_r1__elmt_v * elmt_VIII * elmt_IIa) / (elmt_r1__elmt_k + elmt_IIa))));
        elmt_dXIIa = (elmt_compartment_1 * elmt_dXIIa_elmt_k1 * elmt_XIIa);
        elmt_dTFPI = (elmt_compartment_1 * elmt_d_TFPI * elmt_TFPI);
        elmt_r29 = (elmt_compartment_1 * (((elmt_VIIa * elmt_TF) / elmt_r29_elmt_c)));
        elmt_pPC_VKH2 = (elmt_compartment_1 * (((elmt_d_PC * elmt_PC0 * elmt_VKH2) / elmt_VKH20)));
        elmt_dIIa_Tmod = (elmt_compartment_1 * elmt_dIIa_Tmod_elmt_k1 * elmt_IIa_Tmod);
        elmt_dFg = (elmt_compartment_1 * elmt_d_Fg * elmt_Fg);
        elmt_dX = (elmt_compartment_1 * elmt_d_X * elmt_X);
        elmt_dV = (elmt_compartment_1 * elmt_d_V * elmt_V);
        elmt_dXIII = (elmt_compartment_1 * elmt_d_XIII * elmt_XIII);
        elmt_r31 = (elmt_compartment_1 * (((elmt_VIIa_TF * elmt_Xa_TFPI) / elmt_r31_elmt_c)));
        elmt_r30 = (elmt_compartment_1 * (((elmt_VII * elmt_TF) / elmt_r30_elmt_c)));
        elmt_r39 = (elmt_compartment_1 * (((elmt_r39_elmt_v * elmt_VII * elmt_VIIa_TF) / (elmt_r39_elmt_k + elmt_VIIa_TF))));
        elmt_r38 = (elmt_compartment_1 * (((elmt_r38_elmt_v * elmt_VII * elmt_Xa) / (elmt_r38_elmt_k + elmt_Xa))));
        elmt_dPC = (elmt_compartment_1 * elmt_d_PC * elmt_PC);
        elmt_r37 = (elmt_compartment_1 * (((elmt_APC * elmt_PS) / elmt_r37_elmt_c)));
        elmt_r36 = (elmt_compartment_1 * (((elmt_r36_elmt_v * elmt_VII_TF * elmt_TF) / (elmt_r36_elmt_k + elmt_TF))));
        elmt_dXI = (elmt_compartment_1 * elmt_dXI_elmt_k1 * elmt_XI);
        elmt_r35 = (elmt_compartment_1 * (((elmt_r35_elmt_v * elmt_IX * elmt_VIIa_TF) / (elmt_r35_elmt_k + elmt_VIIa_TF))));
        elmt_r34 = (elmt_compartment_1 * (((elmt_r34_elmt_v * elmt_X * elmt_VIIa_TF) / (elmt_r34_elmt_k + elmt_VIIa_TF))));
        elmt_r33 = (elmt_compartment_1 * (((elmt_r33_elmt_v * elmt_VII_TF * elmt_Xa) / (elmt_r33_elmt_k + elmt_Xa))));
        elmt_dXF = (elmt_compartment_1 * elmt_dXF_elmt_k1 * elmt_XF);
        elmt_r32 = (elmt_compartment_1 * (((elmt_Xa * elmt_TFPI) / elmt_r32_elmt_c)));
        elmt_pFg = (elmt_compartment_1 * ((elmt_Fg0 * elmt_d_Fg)));
        elmt_r2_ = (elmt_compartment_1 * (((elmt_r2__elmt_v * elmt_VIIIa * elmt_APC_PS) / (elmt_r2__elmt_k + elmt_APC_PS))));
        elmt_dPS = (elmt_compartment_1 * elmt_d_PS * elmt_PS);
        elmt_dVa_Xa = (elmt_compartment_1 * elmt_dVa_Xa_elmt_k1 * elmt_Va_Xa);
        elmt_dIXa_VIIIa = (elmt_compartment_1 * elmt_dIXa_VIIIa_elmt_k1 * elmt_IXa_VIIIa);
        elmt_pXI = (elmt_compartment_1 * ((elmt_XI0 * elmt_d_XI)));
        elmt_r42 = (elmt_compartment_1 * (((elmt_r42_elmt_v * elmt_XII * elmt_K) / (elmt_r42_elmt_k + elmt_K))));
        elmt_r41 = (elmt_compartment_1 * (((elmt_r41_elmt_v * elmt_XII * elmt_CA) / (elmt_r41_elmt_k + elmt_CA))));
        elmt_r40 = (elmt_compartment_1 * (((elmt_r40_elmt_v * elmt_VII * elmt_IXa) / (elmt_r40_elmt_k + elmt_IXa))));
        elmt_dXa = (elmt_compartment_1 * elmt_dXa_elmt_k1 * elmt_Xa);
        elmt_dXa_TFPI = (elmt_compartment_1 * elmt_dXa_TFPI_elmt_k1 * elmt_Xa_TFPI);
        elmt_r48 = (elmt_compartment_1 * ((elmt_d_VKO * elmt_VKO * (1.0 - ((elmt_I_max * elmt_C_warf) / (elmt_IC50 + elmt_C_warf))))));
        elmt_r47 = (elmt_compartment_1 * ((elmt_d_VK2 * elmt_VK * (1.0 - ((elmt_I_max * elmt_C_warf) / (elmt_IC50 + elmt_C_warf))))));
        elmt_r46 = (elmt_compartment_1 * (((elmt_IXa * elmt_ATIII_Heparin) / elmt_c46)));
        elmt_dXII = (elmt_compartment_1 * elmt_d_XII * elmt_XII);
        elmt_r45 = (elmt_compartment_1 * (((elmt_Xa * elmt_ATIII_Heparin) / elmt_c45)));
        elmt_r44 = (elmt_compartment_1 * (((elmt_IIa * elmt_ATIII_Heparin) / elmt_c44)));
        elmt_r43 = (elmt_compartment_1 * (((elmt_r43_elmt_v * elmt_Pk * elmt_XIIa) / (elmt_r43_elmt_k + elmt_XIIa))));
        elmt_dPk = (elmt_compartment_1 * elmt_d_Pk * elmt_Pk);
        elmt_r3_ = (elmt_compartment_1 * (((elmt_r3__elmt_v * elmt_IX * elmt_XIa) / (elmt_r3__elmt_k + elmt_XIa))));
        elmt_dPg = (elmt_compartment_1 * elmt_d_Pg * elmt_Pg);
        elmt_eHeparinXa = (elmt_compartment_1 * elmt_Heparin_ke * elmt_Xa_ATIII_Heparin);
        elmt_dVIIIa = (elmt_compartment_1 * elmt_dVIIIa_elmt_k1 * elmt_VIIIa);
        elmt_pPg = (elmt_compartment_1 * ((elmt_Pg0 * elmt_d_Pg)));
        elmt_dII = (elmt_compartment_1 * elmt_d_II * elmt_II);
        elmt_pTmod = (elmt_compartment_1 * ((elmt_Tmod0 * elmt_d_Tmod)));
        elmt_dTAT = (elmt_compartment_1 * elmt_dTAT_elmt_k1 * elmt_TAT);
        elmt_dXIa = (elmt_compartment_1 * elmt_dXIa_elmt_k1 * elmt_XIa);
        elmt_pPk = (elmt_compartment_1 * ((elmt_Pk0 * elmt_d_Pk)));
        elmt_dVIIa_TF_Xa_TFPI = (elmt_compartment_1 * elmt_dVIIa_TF_Xa_TFPI_elmt_k1 * elmt_VIIa_TF_Xa_TFPI);
        elmt_dF = (elmt_compartment_1 * elmt_dF_elmt_k1 * elmt_F);
        elmt_dIX = (elmt_compartment_1 * elmt_d_IX * elmt_IX);
        elmt_dD = (elmt_compartment_1 * elmt_dD_elmt_k1 * elmt_D);
        elmt_pVIII = (elmt_compartment_1 * ((elmt_VIII0 * elmt_d_VIII)));
        elmt_r4_ = (elmt_compartment_1 * (((elmt_r4__elmt_v * elmt_XI * elmt_XIIa) / (elmt_r4__elmt_k + elmt_XIIa))));
        elmt_dP = (elmt_compartment_1 * elmt_dP_elmt_k1 * elmt_P);
        elmt_dXIIIa = (elmt_compartment_1 * elmt_dXIIIa_elmt_k1 * elmt_XIIIa);
        elmt_eHeparin = (elmt_compartment_1 * elmt_Heparin_ke * elmt_ATIII_Heparin);
        elmt_dK = (elmt_compartment_1 * elmt_dK_elmt_k1 * elmt_K);
        elmt_pII_VKH2 = (elmt_compartment_1 * (((elmt_d_II * elmt_II0 * elmt_VKH2) / elmt_VKH20)));
        elmt_eHeparinIIa = (elmt_compartment_1 * elmt_Heparin_ke * elmt_IIa_ATIII_Heparin);
        elmt_pIX_VKH2 = (elmt_compartment_1 * (((elmt_d_IX * elmt_IX0 * elmt_VKH2) / elmt_VKH20)));
        elmt_VK_transport = (elmt_compartment_1 * ((elmt_VitaminK_k12 * elmt_VK) - (elmt_VitaminK_k21_Vc * elmt_VK_p)));
        der(elmt_reactant40) = 0;
        der(elmt_product73) = 0;
        der(elmt_reactant42) = 0;
        der(elmt_product71) = 0;
        der(elmt_product78) = 0;
        der(elmt_product75) = 0;
        der(elmt_reactant47) = 0;
        der(elmt_product171) = 0;
        der(elmt_product170) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_product173) = 0;
        der(elmt_product172) = 0;
        der(elmt_reactant44) = 0;
        der(elmt_reactant46) = 0;
        der(elmt_reactant110) = 0;
        der(elmt_product175) = 0;
        der(elmt_product174) = 0;
        der(elmt_reactant117) = 0;
        der(elmt_product69) = 0;
        der(elmt_reactant116) = 0;
        der(elmt_reactant114) = 0;
        der(elmt_reactant112) = 0;
        der(elmt_reactant50) = 0;
        der(elmt_reactant51) = 0;
        der(elmt_product84) = 0;
        der(elmt_reactant53) = 0;
        der(elmt_product82) = 0;
        der(elmt_product88) = 0;
        der(elmt_reactant119) = 0;
        der(elmt_product86) = 0;
        der(elmt_reactant59) = 0;
        der(elmt_reactant54) = 0;
        der(elmt_product80) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_reactant57) = 0;
        der(elmt_reactant121) = 0;
        der(elmt_reactant120) = 0;
        der(elmt_product101) = 0;
        der(elmt_product104) = 0;
        der(elmt_product103) = 0;
        der(elmt_reactant129) = 0;
        der(elmt_product109) = 0;
        der(elmt_reactant128) = 0;
        der(elmt_reactant127) = 0;
        der(elmt_reactant126) = 0;
        der(elmt_reactant125) = 0;
        der(elmt_product106) = 0;
        der(elmt_reactant124) = 0;
        der(elmt_product105) = 0;
        der(elmt_reactant123) = 0;
        der(elmt_product108) = 0;
        der(elmt_product107) = 0;
        der(elmt_reactant122) = 0;
        der(elmt_product96) = 0;
        der(elmt_reactant20) = 0;
        der(elmt_product93) = 0;
        der(elmt_product12) = 0;
        der(elmt_product99) = 0;
        der(elmt_product10) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_product90) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_product157) = 0;
        der(elmt_reactant176) = 0;
        der(elmt_product159) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product8) = 0;
        der(elmt_reactant30) = 0;
        der(elmt_product6) = 0;
        der(elmt_product23) = 0;
        der(elmt_product21) = 0;
        der(elmt_reactant36) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant38) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_product4) = 0;
        der(elmt_reactant34) = 0;
        der(elmt_product168) = 0;
        der(elmt_product167) = 0;
        der(elmt_product169) = 0;
        der(elmt_product166) = 0;
        der(elmt_product165) = 0;
        der(elmt_product16) = 0;
        der(elmt_product14) = 0;
        der(elmt_reactant102) = 0;
        der(elmt_product18) = 0;
        der(elmt_reactant100) = 0;
        der(elmt_reactant83) = 0;
        der(elmt_reactant85) = 0;
        der(elmt_product33) = 0;
        der(elmt_reactant81) = 0;
        der(elmt_product31) = 0;
        der(elmt_reactant87) = 0;
        der(elmt_reactant89) = 0;
        der(elmt_reactant154) = 0;
        der(elmt_reactant153) = 0;
        der(elmt_reactant152) = 0;
        der(elmt_reactant151) = 0;
        der(elmt_reactant150) = 0;
        der(elmt_product27) = 0;
        der(elmt_reactant9) = 0;
        der(elmt_product25) = 0;
        der(elmt_reactant158) = 0;
        der(elmt_reactant156) = 0;
        der(elmt_product29) = 0;
        der(elmt_reactant155) = 0;
        der(elmt_product41) = 0;
        der(elmt_reactant94) = 0;
        der(elmt_reactant95) = 0;
        der(elmt_reactant97) = 0;
        der(elmt_product45) = 0;
        der(elmt_reactant91) = 0;
        der(elmt_product43) = 0;
        der(elmt_reactant92) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant17) = 0;
        der(elmt_reactant98) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_reactant164) = 0;
        der(elmt_reactant163) = 0;
        der(elmt_reactant162) = 0;
        der(elmt_reactant161) = 0;
        der(elmt_reactant160) = 0;
        der(elmt_product37) = 0;
        der(elmt_product35) = 0;
        der(elmt_product39) = 0;
        der(elmt_product52) = 0;
        der(elmt_reactant62) = 0;
        der(elmt_reactant63) = 0;
        der(elmt_product55) = 0;
        der(elmt_reactant60) = 0;
        der(elmt_reactant65) = 0;
        der(elmt_reactant66) = 0;
        der(elmt_reactant68) = 0;
        der(elmt_reactant132) = 0;
        der(elmt_product113) = 0;
        der(elmt_reactant131) = 0;
        der(elmt_product115) = 0;
        der(elmt_reactant130) = 0;
        der(elmt_product111) = 0;
        der(elmt_product49) = 0;
        der(elmt_reactant139) = 0;
        der(elmt_reactant138) = 0;
        der(elmt_reactant137) = 0;
        der(elmt_reactant136) = 0;
        der(elmt_reactant135) = 0;
        der(elmt_reactant134) = 0;
        der(elmt_product118) = 0;
        der(elmt_reactant133) = 0;
        der(elmt_reactant72) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product61) = 0;
        der(elmt_reactant74) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_product67) = 0;
        der(elmt_reactant5) = 0;
        der(elmt_reactant70) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_product64) = 0;
        der(elmt_reactant76) = 0;
        der(elmt_reactant77) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant79) = 0;
        der(elmt_reactant143) = 0;
        der(elmt_reactant142) = 0;
        der(elmt_reactant141) = 0;
        der(elmt_reactant140) = 0;
        der(elmt_reactant149) = 0;
        der(elmt_product58) = 0;
        der(elmt_reactant148) = 0;
        der(elmt_reactant147) = 0;
        der(elmt_reactant146) = 0;
        der(elmt_reactant145) = 0;
        der(elmt_reactant144) = 0;

end Reactions;
