within BIOMD175;
class Class_elmt_membrane

    input Real elmt_reactant40;
    input Real elmt_reactant41;
    input Real elmt_reactant48;
    input Real elmt_reactant49;
    input Real elmt_Net_E1_ST_Phosphorylation;
    input Real elmt_reactant44;
    input Real elmt_reactant45;
    input Real elmt_ErbB1ErbB2_Heterodimerization;
    input Real elmt_Net_E12PShc_binding;
    input Real elmt_Net_E11PShc_binding;
    input Real elmt_reactant52;
    input Real elmt_reactant53;
    input Real elmt_EGF_Binding_to_ErbB1;
    input Real elmt_reactant56;
    input Real elmt_reactant57;
    input Real elmt_Net_E13Grb2_Binding;
    input Real elmt_Net_E14Grb2_Binding;
    input Real elmt_ERKstar_binding_to_Phosphatase;
    input Real elmt_reactant26;
    input Real elmt_reactant28;
    input Real elmt_reactant21;
    input Real elmt_reactant22;
    input Real elmt_reactant24;
    input Real elmt_Net_SOS_ST_Phosphorylation;
    input Real elmt_Net_E11_Phosphorylation;
    input Real elmt_reactant18;
    input Real elmt_reactant19;
    input Real elmt_reactant30;
    input Real elmt_reactant36;
    input Real elmt_reactant37;
    input Real elmt_reactant32;
    input Real elmt_reactant34;
    input Real elmt_HRG_binding_to_E4PT;
    input Real elmt_ErbB2ErbB3_Heterodimerization;
    input Real elmt_Net_E23_Phosphorylation;
    input Real elmt_reactant9;
    input Real elmt_Net_Gab1RasGAP_binding;
    input Real elmt_Net_Gab1PIP3_binding;
    input Real elmt_reactant15;
    input Real elmt_Net_E14_Phosphorylation;
    input Real elmt_reactant16;
    input Real elmt_reactant10;
    input Real elmt_reactant12;
    input Real elmt_reactant13;
    input Real elmt_Net_E24PRasGAP_binding;
    input Real elmt_Net_E34PTP1B_Binding;
    input Real elmt_Net_Gab1Shc_binding;
    input Real elmt_Net_E23PTP1B_Binding;
    input Real elmt_product192;
    input Real elmt_product194;
    input Real elmt_Net_E14PI3K_Binding;
    input Real elmt_product196;
    input Real elmt_Net_E44PTP1B_Binding;
    input Real elmt_product199;
    input Real elmt_Net_E24PShc_binding;
    input Real elmt_reactant2;
    input Real elmt_reactant4;
    input Real elmt_reactant6;
    input Real elmt_reactant7;
    input Real elmt_reactant0;
    input Real elmt_Gab1_binding_to_SigGO;
    input Real elmt_Net_E13_Phosphorylation;
    input Real elmt_pERK_production;
    input Real elmt_EGF_in_EC_compartment;
    input Real elmt_Net_ShcGrb2_binding;
    input Real elmt_Net_E11PGrb2_binding;
    input Real elmt_ERKstar_dephosphorylation;
    input Real elmt_Net_E12PGrb2_binding;
    input Real elmt_pERK_dephosphorylation;
    input Real elmt_ERKstar_production;
    input Real elmt_product8;
    input Real elmt_HRG_Binding_to_ErbB3;
    input Real elmt_product1;
    input Real elmt_SOS_binding_to_SigGA;
    input Real elmt_Net_E12PTP1B_Binding;
    input Real elmt_product5;
    input Real elmt_PTP1B_binding_to_SigAP;
    input Real elmt_product3;
    input Real elmt_Net_RasGTP_Production;
    input Real elmt_Net_H_E4_ST_Phosphorylation;
    input Real elmt_HRG_Binding_to_ErbB4;
    input Real elmt_Net_MEK_Activation;
    input Real elmt_reactant84;
    input Real elmt_reactant85;
    input Real elmt_reactant80;
    input Real elmt_reactant81;
    input Real elmt_reactant88;
    input Real elmt_reactant89;
    input Real elmt_EGF_binding_to_E1PT;
    input Real elmt_SOS_binding_to_SigAG;
    input Real elmt_reactant96;
    input Real elmt_reactant97;
    input Real elmt_reactant92;
    input Real elmt_reactant93;
    input Real elmt_Net_E23PRasGAP_binding;
    input Real elmt_reactant61;
    input Real elmt_reactant64;
    input Real elmt_reactant60;
    input Real elmt_reactant69;
    input Real elmt_reactant65;
    input Real elmt_reactant68;
    input Real elmt_Net_E13PI3K_Binding;
    input Real elmt_Net_PIP3_Production;
    input Real elmt_reactant72;
    input Real elmt_reactant73;
    input Real elmt_Net_Shc_Phosphorylation;
    input Real elmt_Net_Akt_Activation;
    input Real elmt_E11R_Degradation;
    input Real elmt_reactant76;
    input Real elmt_Net_E11PTP1B_Binding;
    input Real elmt_reactant77;
    input Real elmt_Net_E34_Phosphorylation;
    input Real elmt_Net_RasGAP_Phosphorylation;
    input Real elmt_reactant190;
    input Real elmt_product212;
    input Real elmt_reactant198;
    input Real elmt_reactant197;
    input Real elmt_product211;
    input Real elmt_reactant195;
    input Real elmt_reactant193;
    input Real elmt_reactant191;
    input Real elmt_product219;
    input Real elmt_product216;
    input Real elmt_product215;
    input Real elmt_Net_E24_Phosphorylation;
    input Real elmt_Net_Gab1_ST_Phosphorylation;
    input Real elmt_Net_E13Shc_Binding;
    input Real elmt_product223;
    input Real elmt_product102;
    input Real elmt_E11G_Degradation;
    input Real elmt_product224;
    input Real elmt_product103;
    input Real elmt_product220;
    input Real elmt_product227;
    input Real elmt_product106;
    input Real elmt_product228;
    input Real elmt_product107;
    input Real elmt_product11;
    input Real elmt_Net_E12PRasGAP_binding;
    input Real elmt_ErbB2ErbB4_Heterodimerization;
    input Real elmt_reactant176;
    input Real elmt_reactant297;
    input Real elmt_reactant175;
    input Real elmt_product310;
    input Real elmt_reactant295;
    input Real elmt_product313;
    input Real elmt_reactant173;
    input Real elmt_reactant293;
    input Real elmt_reactant172;
    input Real elmt_reactant291;
    input Real elmt_reactant170;
    input Real elmt_reactant290;
    input Real elmt_product319;
    input Real elmt_product315;
    input Real elmt_reactant179;
    input Real elmt_reactant299;
    input Real elmt_product316;
    input Real elmt_product23;
    input Real elmt_product20;
    input Real elmt_HRG_in_EC_compartment;
    input Real elmt_product322;
    input Real elmt_Net_Grb2SOS_binding;
    input Real elmt_reactant187;
    input Real elmt_product321;
    input Real elmt_product200;
    input Real elmt_product203;
    input Real elmt_reactant184;
    input Real elmt_reactant183;
    input Real elmt_reactant180;
    input Real elmt_product208;
    input Real elmt_product14;
    input Real elmt_product204;
    input Real elmt_product207;
    input Real elmt_reactant188;
    input Real elmt_product17;
    input Real elmt_Net_E_E1_ST_Phosphorylation;
    input Real elmt_ERK_binding_to_MEKstar_2;
    input Real elmt_reactant275;
    input Real elmt_mwbbde76d1_155c_4264_8447_4457527547cb;
    input Real elmt_reactant153;
    input Real elmt_reactant152;
    input Real elmt_reactant273;
    input Real elmt_reactant271;
    input Real elmt_ErbB1ErbB4_Heterodimerization;
    input Real elmt_reactant158;
    input Real elmt_reactant279;
    input Real elmt_reactant156;
    input Real elmt_reactant276;
    input Real elmt_Net_E12_Phosphorylation;
    input Real elmt_reactant164;
    input Real elmt_reactant285;
    input Real elmt_reactant284;
    input Real elmt_reactant162;
    input Real elmt_product301;
    input Real elmt_reactant282;
    input Real elmt_reactant160;
    input Real elmt_reactant281;
    input Real elmt_ERK_binding_to_MEKstar_1;
    input Real elmt_product307;
    input Real elmt_product309;
    input Real elmt_product304;
    input Real elmt_reactant168;
    input Real elmt_product303;
    input Real elmt_reactant288;
    input Real elmt_reactant166;
    input Real elmt_reactant287;
    input Real elmt_reactant253;
    input Real elmt_reactant132;
    input Real elmt_reactant250;
    input Real elmt_reactant258;
    input Real elmt_reactant137;
    input Real elmt_reactant136;
    input Real elmt_reactant257;
    input Real elmt_reactant254;
    input Real elmt_reactant133;
    input Real elmt_Net_Gab1PI3K_binding;
    input Real elmt_ErbB1_Dimerization;
    input Real elmt_reactant263;
    input Real elmt_reactant141;
    input Real elmt_reactant140;
    input Real elmt_reactant261;
    input Real elmt_E11S_Degradation;
    input Real elmt_Net_E13PTP1B_Binding;
    input Real elmt_Net_Grb2Gab1_binding;
    input Real elmt_reactant149;
    input Real elmt_reactant148;
    input Real elmt_reactant269;
    input Real elmt_reactant267;
    input Real elmt_reactant145;
    input Real elmt_reactant144;
    input Real elmt_reactant265;
    input Real elmt_product74;
    input Real elmt_product71;
    input Real elmt_product78;
    input Real elmt_reactant109;
    input Real elmt_reactant108;
    input Real elmt_product75;
    input Real elmt_reactant229;
    input Real elmt_product292;
    input Real elmt_product171;
    input Real elmt_product294;
    input Real elmt_product70;
    input Real elmt_product178;
    input Real elmt_reactant230;
    input Real elmt_Net_E44PRasGAP_binding_1;
    input Real elmt_Net_E44PRasGAP_binding_2;
    input Real elmt_product296;
    input Real elmt_product174;
    input Real elmt_product298;
    input Real elmt_product177;
    input Real elmt_reactant238;
    input Real elmt_reactant117;
    input Real elmt_reactant116;
    input Real elmt_reactant237;
    input Real elmt_reactant113;
    input Real elmt_reactant234;
    input Real elmt_reactant112;
    input Real elmt_Net_E24PTP1B_Binding;
    input Real elmt_reactant233;
    input Real elmt_Net_E34PRasGAP_binding;
    input Real elmt_Net_E23PGrb2_binding;
    input Real elmt_product83;
    input Real elmt_product82;
    input Real elmt_product87;
    input Real elmt_Net_E24PGrb2_binding;
    input Real elmt_product86;
    input Real elmt_product182;
    input Real elmt_product181;
    input Real elmt_reactant242;
    input Real elmt_reactant121;
    input Real elmt_reactant120;
    input Real elmt_product189;
    input Real elmt_reactant241;
    input Real elmt_product186;
    input Real elmt_product185;
    input Real elmt_reactant129;
    input Real elmt_ErbB3ErbB4_Heterodimerization;
    input Real elmt_reactant249;
    input Real elmt_reactant128;
    input Real elmt_reactant126;
    input Real elmt_product79;
    input Real elmt_reactant246;
    input Real elmt_reactant124;
    input Real elmt_reactant245;
    input Real elmt_Net_E44_Phosphorylation;
    input Real elmt_product95;
    input Real elmt_product94;
    input Real elmt_reactant209;
    input Real elmt_product99;
    input Real elmt_product98;
    input Real elmt_product270;
    input Real elmt_Net_E34PGrb2_binding;
    input Real elmt_product272;
    input Real elmt_product151;
    input Real elmt_product150;
    input Real elmt_product91;
    input Real elmt_product90;
    input Real elmt_product157;
    input Real elmt_product278;
    input Real elmt_product277;
    input Real elmt_product159;
    input Real elmt_product274;
    input Real elmt_product155;
    input Real elmt_product154;
    input Real elmt_reactant217;
    input Real elmt_ErbB1ErbB3_Heterodimerization;
    input Real elmt_reactant214;
    input Real elmt_reactant213;
    input Real elmt_ErbB4_Homodimerization;
    input Real elmt_reactant210;
    input Real elmt_reactant218;
    input Real elmt_product280;
    input Real elmt_product283;
    input Real elmt_product161;
    input Real elmt_Net_E13RasGAP_Binding;
    input Real elmt_product289;
    input Real elmt_product167;
    input Real elmt_product169;
    input Real elmt_product163;
    input Real elmt_Net_E14RasGAP_Binding;
    input Real elmt_product165;
    input Real elmt_product286;
    input Real elmt_pERK_binding_to_Phosphatase;
    input Real elmt_Net_E23PPI3K_binding;
    input Real elmt_reactant226;
    input Real elmt_reactant105;
    input Real elmt_reactant225;
    input Real elmt_Net_E14PTP1B_Binding;
    input Real elmt_reactant104;
    input Real elmt_reactant222;
    input Real elmt_reactant101;
    input Real elmt_reactant221;
    input Real elmt_reactant100;
    input Real elmt_product33;
    input Real elmt_reactant308;
    input Real elmt_reactant306;
    input Real elmt_product31;
    input Real elmt_product256;
    input Real elmt_product135;
    input Real elmt_product255;
    input Real elmt_product134;
    input Real elmt_product252;
    input Real elmt_product131;
    input Real elmt_product130;
    input Real elmt_product251;
    input Real elmt_product27;
    input Real elmt_Net_E34PShc_binding;
    input Real elmt_product25;
    input Real elmt_reactant314;
    input Real elmt_reactant312;
    input Real elmt_product139;
    input Real elmt_reactant311;
    input Real elmt_product138;
    input Real elmt_product259;
    input Real elmt_product29;
    input Real elmt_reactant318;
    input Real elmt_product43;
    input Real elmt_product42;
    input Real elmt_reactant317;
    input Real elmt_Net_Raf_Activation;
    input Real elmt_product260;
    input Real elmt_product146;
    input Real elmt_product266;
    input Real elmt_product268;
    input Real elmt_product147;
    input Real elmt_product142;
    input Real elmt_product262;
    input Real elmt_Net_E11PRasGAP_binding;
    input Real elmt_product264;
    input Real elmt_Net_E44PPI3K_binding;
    input Real elmt_product143;
    input Real elmt_product38;
    input Real elmt_reactant206;
    input Real elmt_reactant205;
    input Real elmt_product35;
    input Real elmt_reactant202;
    input Real elmt_reactant201;
    input Real elmt_Net_E14Shc_Binding;
    input Real elmt_reactant320;
    input Real elmt_product39;
    input Real elmt_product51;
    input Real elmt_Net_E4_ST_Phosphorylation;
    input Real elmt_product50;
    input Real elmt_Net_E2_ST_Phosphorylation;
    input Real elmt_product55;
    input Real elmt_product54;
    input Real elmt_Grb2_binding_to_P3_A;
    input Real elmt_product115;
    input Real elmt_product236;
    input Real elmt_product114;
    input Real elmt_Net_E34PPI3K_binding;
    input Real elmt_product235;
    input Real elmt_Net_Gab1_Phosphorylation;
    input Real elmt_product232;
    input Real elmt_product111;
    input Real elmt_product110;
    input Real elmt_product231;
    input Real elmt_product47;
    input Real elmt_Net_E23PShc_binding;
    input Real elmt_product46;
    input Real elmt_Net_E44PShc_binding;
    input Real elmt_product119;
    input Real elmt_product118;
    input Real elmt_product239;
    input Real elmt_product63;
    input Real elmt_product62;
    input Real elmt_product67;
    input Real elmt_E11P_Degradation;
    input Real elmt_product66;
    input Real elmt_product123;
    input Real elmt_product244;
    input Real elmt_product247;
    input Real elmt_product125;
    input Real elmt_E11T_Degradation;
    input Real elmt_product240;
    input Real elmt_product122;
    input Real elmt_product243;
    input Real elmt_Net_E24PPI3K_binding;
    input Real elmt_reactant305;
    input Real elmt_product59;
    input Real elmt_product58;
    input Real elmt_reactant302;
    input Real elmt_product127;
    input Real elmt_reactant300;
    input Real elmt_product248;

    Real elmt_membrane(unit = "m2.0") "membrane";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_MEK_conc(unit = "m-142.0.");
    Real elmt_MEK_amount(unit = "m-140.0.");
    Real elmt_MEK(unit = "m-142.0.") "MEK";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_Aktstar_conc(unit = "m-216.0.");
    Real elmt_Aktstar_amount(unit = "m-214.0.");
    Real elmt_Aktstar(unit = "m-216.0.") "Aktstar";
    Real elmt_E2_PT_conc(unit = "m-208.0.");
    Real elmt_E2_PT_amount(unit = "m-206.0.");
    Real elmt_E2_PT(unit = "m-208.0.") "E2_p-PTP-1B";
    Real elmt_pERK_ERKpase_conc(unit = "m-232.0.");
    Real elmt_pERK_ERKpase_amount(unit = "m-230.0.");
    Real elmt_pERK_ERKpase(unit = "m-232.0.") "p_ERK-ERKpase";
    Real elmt_Empty_conc(unit = "m-122.0.");
    Real elmt_Empty_amount(unit = "m-120.0.");
    Real elmt_Empty(unit = "m-122.0.") "Empty";
    Real elmt_E_E1_PT_conc(unit = "m-212.0.");
    Real elmt_E_E1_PT_amount(unit = "m-210.0.");
    Real elmt_E_E1_PT(unit = "m-212.0.") "E_E1_p-PTP-1B";
    Real elmt_E44G_conc(unit = "m-88.0.");
    Real elmt_E44G_amount(unit = "m-86.0.");
    Real elmt_E44G(unit = "m-88.0.") "E44-Grb2";
    Real elmt_SigA_G_conc(unit = "m-156.0.");
    Real elmt_SigA_G_amount(unit = "m-154.0.");
    Real elmt_SigA_G(unit = "m-156.0.") "Sum PIP3-Gab1-Grb2";
    Real elmt_E44I_conc(unit = "m-92.0.");
    Real elmt_E44I_amount(unit = "m-90.0.");
    Real elmt_E44I(unit = "m-92.0.") "E44-PI-3K";
    Real elmt_ERKpase_conc(unit = "m-234.0.");
    Real elmt_ERKpase_amount(unit = "m-232.0.");
    Real elmt_ERKpase(unit = "m-234.0.") "ERKpase";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E44R_conc(unit = "m-94.0.");
    Real elmt_E44R_amount(unit = "m-92.0.");
    Real elmt_E44R(unit = "m-94.0.") "E44-RasGAP";
    Real elmt_E44S_conc(unit = "m-90.0.");
    Real elmt_E44S_amount(unit = "m-88.0.");
    Real elmt_E44S(unit = "m-90.0.") "E44-Shc";
    Real elmt_E44P_conc(unit = "m-38.0.");
    Real elmt_E44P_amount(unit = "m-36.0.");
    Real elmt_E44P(unit = "m-38.0.") "E44_p";
    Real elmt_SigSP_conc(unit = "m-106.0.");
    Real elmt_SigSP_amount(unit = "m-104.0.");
    Real elmt_SigSP(unit = "m-106.0.") "Sum Shc_p";
    Real elmt_Raf_conc(unit = "m-138.0.");
    Real elmt_Raf_amount(unit = "m-136.0.");
    Real elmt_Raf(unit = "m-138.0.") "Raf";
    Real elmt_E13I_conc(unit = "m-174.0.");
    Real elmt_E13I_amount(unit = "m-172.0.");
    Real elmt_E13I(unit = "m-174.0.") "E13-PI-3K";
    Real elmt_E13G_conc(unit = "m-170.0.");
    Real elmt_E13G_amount(unit = "m-168.0.");
    Real elmt_E13G(unit = "m-170.0.") "E13-Grb2";
    Real elmt_SigAP_conc(unit = "m-108.0.");
    Real elmt_SigAP_amount(unit = "m-106.0.");
    Real elmt_SigAP(unit = "m-108.0.") "Sum Gab1_p";
    Real elmt_E13P_conc(unit = "m-166.0.");
    Real elmt_E13P_amount(unit = "m-164.0.");
    Real elmt_E13P(unit = "m-166.0.") "ErbB1-ErbB3_p";
    Real elmt_E13T_conc(unit = "m-200.0.");
    Real elmt_E13T_amount(unit = "m-198.0.");
    Real elmt_E13T(unit = "m-200.0.") "E13-PTP-1B";
    Real elmt_E13R_conc(unit = "m-176.0.");
    Real elmt_E13R_amount(unit = "m-174.0.");
    Real elmt_E13R(unit = "m-176.0.") "E13-RasGAP";
    Real elmt_E13S_conc(unit = "m-172.0.");
    Real elmt_E13S_amount(unit = "m-170.0.");
    Real elmt_E13S(unit = "m-172.0.") "E13-Shc";
    Real elmt_SigRP_conc(unit = "m-136.0.");
    Real elmt_SigRP_amount(unit = "m-134.0.");
    Real elmt_SigRP(unit = "m-136.0.") "Sum RasGAP_p";
    Real elmt_RsD_conc(unit = "m-132.0.");
    Real elmt_RsD_amount(unit = "m-130.0.");
    Real elmt_RsD(unit = "m-132.0.") "RasGDP";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E14I_conc(unit = "m-182.0.");
    Real elmt_E14I_amount(unit = "m-180.0.");
    Real elmt_E14I(unit = "m-182.0.") "E14-PI-3K";
    Real elmt_P3_conc(unit = "m-128.0.");
    Real elmt_P3_amount(unit = "m-126.0.");
    Real elmt_P3(unit = "m-128.0.") "PIP3";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E14G_conc(unit = "m-178.0.");
    Real elmt_E14G_amount(unit = "m-176.0.");
    Real elmt_E14G(unit = "m-178.0.") "E14-Grb2";
    Real elmt_ERKstar_conc(unit = "m-148.0.");
    Real elmt_ERKstar_amount(unit = "m-146.0.");
    Real elmt_ERKstar(unit = "m-148.0.") "ERK*";
    Real elmt_OP_conc(unit = "m-150.0.");
    Real elmt_OP_amount(unit = "m-148.0.");
    Real elmt_OP(unit = "m-150.0.") "SOS_p";
    Real elmt_P2_conc(unit = "m-126.0.");
    Real elmt_P2_amount(unit = "m-124.0.");
    Real elmt_P2(unit = "m-126.0.") "PIP2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_RsT_conc(unit = "m-134.0.");
    Real elmt_RsT_amount(unit = "m-132.0.");
    Real elmt_RsT(unit = "m-134.0.") "RasGTP";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_H_E4_PT_conc(unit = "m-214.0.");
    Real elmt_H_E4_PT_amount(unit = "m-212.0.");
    Real elmt_H_E4_PT(unit = "m-214.0.") "H_E4_p-PTP-1B";
    Real elmt_SigSP_G_conc(unit = "m-114.0.");
    Real elmt_SigSP_G_amount(unit = "m-112.0.");
    Real elmt_SigSP_G(unit = "m-114.0.") "Sum Shc_p-Grb2";
    Real elmt_MEKstar_conc(unit = "m-144.0.");
    Real elmt_MEKstar_amount(unit = "m-142.0.");
    Real elmt_MEKstar(unit = "m-144.0.") "MEK*";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E14R_conc(unit = "m-184.0.");
    Real elmt_E14R_amount(unit = "m-182.0.");
    Real elmt_E14R(unit = "m-184.0.") "E14-RasGAP";
    Real elmt_E14P_conc(unit = "m-168.0.");
    Real elmt_E14P_amount(unit = "m-166.0.");
    Real elmt_E14P(unit = "m-168.0.") "ErbB1-ErbB3_p";
    Real elmt_E14S_conc(unit = "m-180.0.");
    Real elmt_E14S_amount(unit = "m-178.0.");
    Real elmt_E14S(unit = "m-180.0.") "E14-Shc";
    Real elmt_E14T_conc(unit = "m-202.0.");
    Real elmt_E14T_amount(unit = "m-200.0.");
    Real elmt_E14T(unit = "m-202.0.") "E14-PTP-1B";
    Real elmt_E13_conc(unit = "m-162.0.");
    Real elmt_E13_amount(unit = "m-160.0.");
    Real elmt_E13(unit = "m-162.0.") "ErbB1-ErbB3";
    Real elmt_E14_conc(unit = "m-164.0.");
    Real elmt_E14_amount(unit = "m-162.0.");
    Real elmt_E14(unit = "m-164.0.") "ErbB1-ErbB4";
    Real elmt_E11_conc(unit = "m-16.0.");
    Real elmt_E11_amount(unit = "m-14.0.");
    Real elmt_E11(unit = "m-16.0.") "(EGF-ErbB1)2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E12_conc(unit = "m-18.0.");
    Real elmt_E12_amount(unit = "m-16.0.");
    Real elmt_E12(unit = "m-18.0.") "EGF-ErbB1-ErbB2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_SigA_G_O_conc(unit = "m-158.0.");
    Real elmt_SigA_G_O_amount(unit = "m-156.0.");
    Real elmt_SigA_G_O(unit = "m-158.0.") "Sum PIP3-Gab1-Grb2_SOS";
    Real elmt_E23G_conc(unit = "m-64.0.");
    Real elmt_E23G_amount(unit = "m-62.0.");
    Real elmt_E23G(unit = "m-64.0.") "E23-Grb2";
    Real elmt_E11G_conc(unit = "m-52.0.");
    Real elmt_E11G_amount(unit = "m-50.0.");
    Real elmt_E11G(unit = "m-52.0.") "E11-Grb2";
    Real elmt_E_E1_conc(unit = "m-10.0.");
    Real elmt_E_E1_amount(unit = "m-8.0.");
    Real elmt_E_E1(unit = "m-10.0.") "EGF-ErbB1";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E23I_conc(unit = "m-68.0.");
    Real elmt_E23I_amount(unit = "m-66.0.");
    Real elmt_E23I(unit = "m-68.0.") "E23-PI-3K";
    Real elmt_E2_conc(unit = "m-4.0.");
    Real elmt_E2_amount(unit = "m-2.0.");
    Real elmt_E2(unit = "m-4.0.") "ErbB2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_SigR_conc(unit = "m-102.0.");
    Real elmt_SigR_amount(unit = "m-100.0.");
    Real elmt_SigR(unit = "m-102.0.") "Sum RasGAP";
    Real elmt_E3_conc(unit = "m-6.0.");
    Real elmt_E3_amount(unit = "m-4.0.");
    Real elmt_E3(unit = "m-6.0.") "ErbB3";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E23P_conc(unit = "m-32.0.");
    Real elmt_E23P_amount(unit = "m-30.0.");
    Real elmt_E23P(unit = "m-32.0.") "E23_p";
    Real elmt_SigS_conc(unit = "m-98.0.");
    Real elmt_SigS_amount(unit = "m-96.0.");
    Real elmt_SigS(unit = "m-98.0.") "Sum Shc";
    Real elmt_E1_conc(unit = "m-2.0.");
    Real elmt_E1_amount(unit = "");
    Real elmt_E1(unit = "m-2.0.") "ErbB1";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_ERK_conc(unit = "m-146.0.");
    Real elmt_ERK_amount(unit = "m-144.0.");
    Real elmt_ERK(unit = "m-146.0.") "ERK";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E11R_conc(unit = "m-56.0.");
    Real elmt_E11R_amount(unit = "m-54.0.");
    Real elmt_E11R(unit = "m-56.0.") "E11-RasGAP";
    Real elmt_E23S_conc(unit = "m-66.0.");
    Real elmt_E23S_amount(unit = "m-64.0.");
    Real elmt_E23S(unit = "m-66.0.") "E23-Shc";
    Real elmt_E11S_conc(unit = "m-54.0.");
    Real elmt_E11S_amount(unit = "m-52.0.");
    Real elmt_E11S(unit = "m-54.0.") "E11-Shc";
    Real elmt_E23T_conc(unit = "m-192.0.");
    Real elmt_E23T_amount(unit = "m-190.0.");
    Real elmt_E23T(unit = "m-192.0.") "E23-PTP-1B";
    Real elmt_E11P_conc(unit = "m-28.0.");
    Real elmt_E11P_amount(unit = "m-26.0.");
    Real elmt_E11P(unit = "m-28.0.") "E11_p";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_SigT_conc(unit = "m-204.0.");
    Real elmt_SigT_amount(unit = "m-202.0.");
    Real elmt_SigT(unit = "m-204.0.") "Sig-PTP-1B";
    Real elmt_E23R_conc(unit = "m-70.0.");
    Real elmt_E23R_amount(unit = "m-68.0.");
    Real elmt_E23R(unit = "m-70.0.") "E23-RasGAP";
    Real elmt_E24_conc(unit = "m-24.0.");
    Real elmt_E24_amount(unit = "m-22.0.");
    Real elmt_E24(unit = "m-24.0.") "HRG-Erb4-ErbB2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E23_conc(unit = "m-20.0.");
    Real elmt_E23_amount(unit = "m-18.0.");
    Real elmt_E23(unit = "m-20.0.") "HRG-ErbB3-ErbB2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_SigI_conc(unit = "m-100.0.");
    Real elmt_SigI_amount(unit = "m-98.0.");
    Real elmt_SigI(unit = "m-100.0.") "Sum PI-3K";
    Real elmt_SigO_conc(unit = "m-160.0.");
    Real elmt_SigO_amount(unit = "m-158.0.");
    Real elmt_SigO(unit = "m-160.0.") "Sum SOS";
    Real elmt_norm_Akt_star_conc(unit = "m-238.0.");
    Real elmt_norm_Akt_star_amount(unit = "m-236.0.");
    Real elmt_norm_Akt_star(unit = "m-238.0.") "normalized Akt*";
    Real elmt_Rafstar_conc(unit = "m-140.0.");
    Real elmt_Rafstar_amount(unit = "m-138.0.");
    Real elmt_Rafstar(unit = "m-140.0.") "Raf*";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_SigA_conc(unit = "m-104.0.");
    Real elmt_SigA_amount(unit = "m-102.0.");
    Real elmt_SigA(unit = "m-104.0.") "Sum Gab1";
    Real elmt_S_conc(unit = "m-42.0.");
    Real elmt_S_amount(unit = "m-40.0.");
    Real elmt_S(unit = "m-42.0.") "Shc";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_SigG_conc(unit = "m-96.0.");
    Real elmt_SigG_amount(unit = "m-94.0.");
    Real elmt_SigG(unit = "m-96.0.") "Sum Grb2";
    Real elmt_T_conc(unit = "m-186.0.");
    Real elmt_T_amount(unit = "m-184.0.");
    Real elmt_T(unit = "m-186.0.") "PTP-1B";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_R_conc(unit = "m-46.0.");
    Real elmt_R_amount(unit = "m-44.0.");
    Real elmt_R(unit = "m-46.0.") "RasGAP";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_O_conc(unit = "m-48.0.");
    Real elmt_O_amount(unit = "m-46.0.");
    Real elmt_O(unit = "m-48.0.") "SOS";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E12G_conc(unit = "m-58.0.");
    Real elmt_E12G_amount(unit = "m-56.0.");
    Real elmt_E12G(unit = "m-58.0.") "E12-Grb2";
    Real elmt_ERK_MEKstar_conc(unit = "m-228.0.");
    Real elmt_ERK_MEKstar_amount(unit = "m-226.0.");
    Real elmt_ERK_MEKstar(unit = "m-228.0.") "ERK-MEK*";
    Real elmt_E24I_conc(unit = "m-84.0.");
    Real elmt_E24I_amount(unit = "m-82.0.");
    Real elmt_E24I(unit = "m-84.0.") "E24-PI-3K";
    Real elmt_P3_A_conc(unit = "m-124.0.");
    Real elmt_P3_A_amount(unit = "m-122.0.");
    Real elmt_P3_A(unit = "m-124.0.") "PIP3-Gab1";
    Real elmt_H_E3_conc(unit = "m-12.0.");
    Real elmt_H_E3_amount(unit = "m-10.0.");
    Real elmt_H_E3(unit = "m-12.0.") "HRG-ErbB3";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_SigG_A_conc(unit = "m-112.0.");
    Real elmt_SigG_A_amount(unit = "m-110.0.");
    Real elmt_SigG_A(unit = "m-112.0.") "Sum Grb2-Gab1";
    Real elmt_H_E4_conc(unit = "m-14.0.");
    Real elmt_H_E4_amount(unit = "m-12.0.");
    Real elmt_H_E4(unit = "m-14.0.") "HRG-ErbB4";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E24G_conc(unit = "m-80.0.");
    Real elmt_E24G_amount(unit = "m-78.0.");
    Real elmt_E24G(unit = "m-80.0.") "E24-Grb2";
    Real elmt_I_conc(unit = "m-44.0.");
    Real elmt_I_amount(unit = "m-42.0.");
    Real elmt_I(unit = "m-44.0.") "PI-3K";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E24P_conc(unit = "m-36.0.");
    Real elmt_E24P_amount(unit = "m-34.0.");
    Real elmt_E24P(unit = "m-36.0.") "E24_p";
    Real elmt_G_conc(unit = "m-40.0.");
    Real elmt_G_amount(unit = "m-38.0.");
    Real elmt_G(unit = "m-40.0.") "Grb2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E12P_conc(unit = "m-30.0.");
    Real elmt_E12P_amount(unit = "m-28.0.");
    Real elmt_E12P(unit = "m-30.0.") "E12_p";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_H_conc(unit = "m-222.0.");
    Real elmt_H_amount(unit = "m-220.0.");
    Real elmt_H(unit = "m-222.0.") "HRG";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E_conc(unit = "m-220.0.");
    Real elmt_E_amount(unit = "m-218.0.");
    Real elmt_E(unit = "m-220.0.") "EGF";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E12S_conc(unit = "m-60.0.");
    Real elmt_E12S_amount(unit = "m-58.0.");
    Real elmt_E12S(unit = "m-60.0.") "E12-Shc";
    Real elmt_E24T_conc(unit = "m-196.0.");
    Real elmt_E24T_amount(unit = "m-194.0.");
    Real elmt_E24T(unit = "m-196.0.") "E24-PTP-1B";
    Real elmt_E12T_conc(unit = "m-190.0.");
    Real elmt_E12T_amount(unit = "m-188.0.");
    Real elmt_E12T(unit = "m-190.0.") "E12-PTP-1B";
    Real elmt_E1_PT_conc(unit = "m-206.0.");
    Real elmt_E1_PT_amount(unit = "m-204.0.");
    Real elmt_E1_PT(unit = "m-206.0.") "E1_p-PTP-1B";
    Real elmt_A_conc(unit = "m-50.0.");
    Real elmt_A_amount(unit = "m-48.0.");
    Real elmt_A(unit = "m-50.0.") "Gab1";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E24R_conc(unit = "m-86.0.");
    Real elmt_E24R_amount(unit = "m-84.0.");
    Real elmt_E24R(unit = "m-86.0.") "E24-RasGAP";
    Real elmt_E12R_conc(unit = "m-62.0.");
    Real elmt_E12R_amount(unit = "m-60.0.");
    Real elmt_E12R(unit = "m-62.0.") "E12-RasGAP";
    Real elmt_E24S_conc(unit = "m-82.0.");
    Real elmt_E24S_amount(unit = "m-80.0.");
    Real elmt_E24S(unit = "m-82.0.") "E24-Shc";
    Real elmt_E11T_conc(unit = "m-188.0.");
    Real elmt_E11T_amount(unit = "m-186.0.");
    Real elmt_E11T(unit = "m-188.0.") "E11-PTP-1B";
    Real elmt_E34_conc(unit = "m-22.0.");
    Real elmt_E34_amount(unit = "m-20.0.");
    Real elmt_E34(unit = "m-22.0.") "(HRG-ErbB3/4)2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_A_SigG_O_conc(unit = "m-154.0.");
    Real elmt_A_SigG_O_amount(unit = "m-152.0.");
    Real elmt_A_SigG_O(unit = "m-154.0.") "Gab1_SumGrb2-SOS";
    Real elmt_E4_conc(unit = "m-8.0.");
    Real elmt_E4_amount(unit = "m-6.0.");
    Real elmt_E4(unit = "m-8.0.") "ErbB4";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_fint_conc(unit = "m-224.0.");
    Real elmt_fint_amount(unit = "m-222.0.");
    Real elmt_fint(unit = "m-224.0.") "fint";
    Real elmt_pERK_conc(unit = "m-226.0.");
    Real elmt_pERK_amount(unit = "m-224.0.");
    Real elmt_pERK(unit = "m-226.0.") "p_ERK";
    Real elmt_SigG_O_conc(unit = "m-110.0.");
    Real elmt_SigG_O_amount(unit = "m-108.0.");
    Real elmt_SigG_O(unit = "m-110.0.") "Sum Grb2-SOS";
    Real elmt_SigAP_I_conc(unit = "m-118.0.");
    Real elmt_SigAP_I_amount(unit = "m-116.0.");
    Real elmt_SigAP_I(unit = "m-118.0.") "Sum Gab1_p-PI-3K";
    Real elmt_Akt_conc(unit = "m-130.0.");
    Real elmt_Akt_amount(unit = "m-128.0.");
    Real elmt_Akt(unit = "m-130.0.") "Akt";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_SigAP_T_conc(unit = "m-218.0.");
    Real elmt_SigAP_T_amount(unit = "m-216.0.");
    Real elmt_SigAP_T(unit = "m-218.0.") "SumGab1_p-PTP-1B";
    Real elmt_norm_Erk_star_conc(unit = "m-240.0.");
    Real elmt_norm_Erk_star_amount(unit = "m-238.0.");
    Real elmt_norm_Erk_star(unit = "m-240.0.") "normalized Erk*";
    Real elmt_SigAP_S_conc(unit = "m-116.0.");
    Real elmt_SigAP_S_amount(unit = "m-114.0.");
    Real elmt_SigAP_S(unit = "m-116.0.") "Sum Gab1_p-Shc";
    Real elmt_SigAP_R_conc(unit = "m-120.0.");
    Real elmt_SigAP_R_amount(unit = "m-118.0.");
    Real elmt_SigAP_R(unit = "m-120.0.") "Sum Gab1_p-RasGAP";
    Real elmt_pERK_MEKstar_conc(unit = "m-230.0.");
    Real elmt_pERK_MEKstar_amount(unit = "m-228.0.");
    Real elmt_pERK_MEKstar(unit = "m-230.0.") "p_ERK-MEK*";
    Real elmt_E4_PT_conc(unit = "m-210.0.");
    Real elmt_E4_PT_amount(unit = "m-208.0.");
    Real elmt_E4_PT(unit = "m-210.0.") "E4_p-PTP-1B";
    Real elmt_E44_conc(unit = "m-26.0.");
    Real elmt_E44_amount(unit = "m-24.0.");
    Real elmt_E44(unit = "m-26.0.") "(HRG-Erb4)2";
 annotation(Documentation(info="<annotation>
        <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
        </rdf:RDF>
      </annotation>"));
    Real elmt_E44T_conc(unit = "m-198.0.");
    Real elmt_E44T_amount(unit = "m-196.0.");
    Real elmt_E44T(unit = "m-198.0.") "E44-PTP-1B";
    Real elmt_AP_conc(unit = "m-152.0.");
    Real elmt_AP_amount(unit = "m-150.0.");
    Real elmt_AP(unit = "m-152.0.") "Gab1_p";
    Real elmt_E34G_conc(unit = "m-72.0.");
    Real elmt_E34G_amount(unit = "m-70.0.");
    Real elmt_E34G(unit = "m-72.0.") "E34-Grb2";
    Real elmt_E34I_conc(unit = "m-76.0.");
    Real elmt_E34I_amount(unit = "m-74.0.");
    Real elmt_E34I(unit = "m-76.0.") "E34-PI-3K";
    Real elmt_E34P_conc(unit = "m-34.0.");
    Real elmt_E34P_amount(unit = "m-32.0.");
    Real elmt_E34P(unit = "m-34.0.") "E34_p";
    Real elmt_E34S_conc(unit = "m-74.0.");
    Real elmt_E34S_amount(unit = "m-72.0.");
    Real elmt_E34S(unit = "m-74.0.") "E34-Shc";
    Real elmt_E34T_conc(unit = "m-194.0.");
    Real elmt_E34T_amount(unit = "m-192.0.");
    Real elmt_E34T(unit = "m-194.0.") "E34-PTP-1B";
    Real elmt_E34R_conc(unit = "m-78.0.");
    Real elmt_E34R_amount(unit = "m-76.0.");
    Real elmt_E34R(unit = "m-78.0.") "E34-RasGAP";
    Real elmt_ERKstar_ERKpase_conc(unit = "m-236.0.");
    Real elmt_ERKstar_ERKpase_amount(unit = "m-234.0.");
    Real elmt_ERKstar_ERKpase(unit = "m-236.0.") "ERK*-ERKpase";

    initial equation
        elmt_membrane = 1.0;
        elmt_MEK_conc = (772.0 / elmt_membrane);
        elmt_Aktstar_conc = (0.0 / elmt_membrane);
        elmt_E2_PT_conc = (0.0 / elmt_membrane);
        elmt_pERK_ERKpase_conc = (0.0 / elmt_membrane);
        elmt_Empty_conc = (0.0 / elmt_membrane);
        elmt_E_E1_PT_conc = (0.0 / elmt_membrane);
        elmt_E44G_conc = (0.0 / elmt_membrane);
        elmt_SigA_G_conc = (0.0 / elmt_membrane);
        elmt_E44I_conc = (0.0 / elmt_membrane);
        elmt_ERKpase_conc = (0.0 / elmt_membrane);
        elmt_E44R_conc = (0.0 / elmt_membrane);
        elmt_E44S_conc = (0.0 / elmt_membrane);
        elmt_E44P_conc = (0.0 / elmt_membrane);
        elmt_SigSP_conc = (0.0 / elmt_membrane);
        elmt_Raf_conc = (743.0 / elmt_membrane);
        elmt_E13I_conc = (0.0 / elmt_membrane);
        elmt_E13G_conc = (0.0 / elmt_membrane);
        elmt_SigAP_conc = (0.0 / elmt_membrane);
        elmt_E13P_conc = (0.0 / elmt_membrane);
        elmt_E13T_conc = (0.0 / elmt_membrane);
        elmt_E13R_conc = (0.0 / elmt_membrane);
        elmt_E13S_conc = (0.0 / elmt_membrane);
        elmt_SigRP_conc = (0.0 / elmt_membrane);
        elmt_RsD_conc = (95.7 / elmt_membrane);
        elmt_E14I_conc = (0.0 / elmt_membrane);
        elmt_P3_conc = (0.0 / elmt_membrane);
        elmt_E14G_conc = (0.0 / elmt_membrane);
        elmt_ERKstar_conc = (0.0 / elmt_membrane);
        elmt_OP_conc = (0.0 / elmt_membrane);
        elmt_P2_conc = (197.0 / elmt_membrane);
        elmt_RsT_conc = (0.0 / elmt_membrane);
        elmt_H_E4_PT_conc = (0.0 / elmt_membrane);
        elmt_SigSP_G_conc = (0.0 / elmt_membrane);
        elmt_MEKstar_conc = (0.0 / elmt_membrane);
        elmt_E14R_conc = (0.0 / elmt_membrane);
        elmt_E14P_conc = (0.0 / elmt_membrane);
        elmt_E14S_conc = (0.0 / elmt_membrane);
        elmt_E14T_conc = (0.0 / elmt_membrane);
        elmt_E13_conc = (0.0 / elmt_membrane);
        elmt_E14_conc = (0.0 / elmt_membrane);
        elmt_E11_conc = (0.0 / elmt_membrane);
        elmt_E12_conc = (0.0 / elmt_membrane);
        elmt_SigA_G_O_conc = (0.0 / elmt_membrane);
        elmt_E23G_conc = (0.0 / elmt_membrane);
        elmt_E11G_conc = (0.0 / elmt_membrane);
        elmt_E_E1_conc = (0.0 / elmt_membrane);
        elmt_E23I_conc = (0.0 / elmt_membrane);
        elmt_E2_conc = (158.0 / elmt_membrane);
        elmt_SigR_conc = (0.0 / elmt_membrane);
        elmt_E3_conc = (294.0 / elmt_membrane);
        elmt_E23P_conc = (0.0 / elmt_membrane);
        elmt_SigS_conc = (0.0 / elmt_membrane);
        elmt_E1_conc = (274.0 / elmt_membrane);
        elmt_ERK_conc = (750.0 / elmt_membrane);
        elmt_E11R_conc = (0.0 / elmt_membrane);
        elmt_E23S_conc = (0.0 / elmt_membrane);
        elmt_E11S_conc = (0.0 / elmt_membrane);
        elmt_E23T_conc = (0.0 / elmt_membrane);
        elmt_E11P_conc = (0.0 / elmt_membrane);
        elmt_SigT_conc = (0.0 / elmt_membrane);
        elmt_E23R_conc = (0.0 / elmt_membrane);
        elmt_E24_conc = (0.0 / elmt_membrane);
        elmt_E23_conc = (0.0 / elmt_membrane);
        elmt_SigI_conc = (0.0 / elmt_membrane);
        elmt_SigO_conc = (0.0 / elmt_membrane);
        elmt_Rafstar_conc = (0.0 / elmt_membrane);
        elmt_SigA_conc = (0.0 / elmt_membrane);
        elmt_S_conc = (11.5 / elmt_membrane);
        elmt_SigG_conc = (0.0 / elmt_membrane);
        elmt_T_conc = (500.0 / elmt_membrane);
        elmt_R_conc = (93.6 / elmt_membrane);
        elmt_O_conc = (82.3 / elmt_membrane);
        elmt_E12G_conc = (0.0 / elmt_membrane);
        elmt_ERK_MEKstar_conc = (0.0 / elmt_membrane);
        elmt_E24I_conc = (0.0 / elmt_membrane);
        elmt_P3_A_conc = (0.0 / elmt_membrane);
        elmt_H_E3_conc = (0.0 / elmt_membrane);
        elmt_SigG_A_conc = (0.0 / elmt_membrane);
        elmt_H_E4_conc = (0.0 / elmt_membrane);
        elmt_E24G_conc = (0.0 / elmt_membrane);
        elmt_I_conc = (46.4 / elmt_membrane);
        elmt_E24P_conc = (0.0 / elmt_membrane);
        elmt_G_conc = (82.4 / elmt_membrane);
        elmt_E12P_conc = (0.0 / elmt_membrane);
        elmt_H_conc = (10.0 / elmt_membrane);
        elmt_E_conc = (10.0 / elmt_membrane);
        elmt_E12S_conc = (0.0 / elmt_membrane);
        elmt_E24T_conc = (0.0 / elmt_membrane);
        elmt_E12T_conc = (0.0 / elmt_membrane);
        elmt_E1_PT_conc = (0.0 / elmt_membrane);
        elmt_A_conc = (43.1 / elmt_membrane);
        elmt_E24R_conc = (0.0 / elmt_membrane);
        elmt_E12R_conc = (0.0 / elmt_membrane);
        elmt_E24S_conc = (0.0 / elmt_membrane);
        elmt_E11T_conc = (0.0 / elmt_membrane);
        elmt_E34_conc = (0.0 / elmt_membrane);
        elmt_A_SigG_O_conc = (0.0 / elmt_membrane);
        elmt_E4_conc = (399.0 / elmt_membrane);
        elmt_fint_conc = (0.0 / elmt_membrane);
        elmt_pERK_conc = (0.0 / elmt_membrane);
        elmt_SigG_O_conc = (0.0 / elmt_membrane);
        elmt_SigAP_I_conc = (0.0 / elmt_membrane);
        elmt_Akt_conc = (444.0 / elmt_membrane);
        elmt_SigAP_T_conc = (0.0 / elmt_membrane);
        elmt_SigAP_S_conc = (0.0 / elmt_membrane);
        elmt_SigAP_R_conc = (0.0 / elmt_membrane);
        elmt_pERK_MEKstar_conc = (0.0 / elmt_membrane);
        elmt_E4_PT_conc = (0.0 / elmt_membrane);
        elmt_E44_conc = (0.0 / elmt_membrane);
        elmt_E44T_conc = (0.0 / elmt_membrane);
        elmt_AP_conc = (0.0 / elmt_membrane);
        elmt_E34G_conc = (0.0 / elmt_membrane);
        elmt_E34I_conc = (0.0 / elmt_membrane);
        elmt_E34P_conc = (0.0 / elmt_membrane);
        elmt_E34S_conc = (0.0 / elmt_membrane);
        elmt_E34T_conc = (0.0 / elmt_membrane);
        elmt_E34R_conc = (0.0 / elmt_membrane);
        elmt_ERKstar_ERKpase_conc = (35.0 / elmt_membrane);


    equation
        assert(elmt_membrane >= 0, "Compartment size became negative. Make sure this is a valid bahaviour.");
        der(elmt_membrane) = 0;
        elmt_MEK = elmt_MEK_conc;
        elmt_Aktstar = elmt_Aktstar_conc;
        elmt_E2_PT = elmt_E2_PT_conc;
        elmt_pERK_ERKpase = elmt_pERK_ERKpase_conc;
        elmt_Empty = elmt_Empty_conc;
        elmt_E_E1_PT = elmt_E_E1_PT_conc;
        elmt_E44G = elmt_E44G_conc;
        elmt_SigA_G = elmt_SigA_G_conc;
        elmt_E44I = elmt_E44I_conc;
        elmt_ERKpase = elmt_ERKpase_conc;
        elmt_E44R = elmt_E44R_conc;
        elmt_E44S = elmt_E44S_conc;
        elmt_E44P = elmt_E44P_conc;
        elmt_SigSP = elmt_SigSP_conc;
        elmt_Raf = elmt_Raf_conc;
        elmt_E13I = elmt_E13I_conc;
        elmt_E13G = elmt_E13G_conc;
        elmt_SigAP = elmt_SigAP_conc;
        elmt_E13P = elmt_E13P_conc;
        elmt_E13T = elmt_E13T_conc;
        elmt_E13R = elmt_E13R_conc;
        elmt_E13S = elmt_E13S_conc;
        elmt_SigRP = elmt_SigRP_conc;
        elmt_RsD = elmt_RsD_conc;
        elmt_E14I = elmt_E14I_conc;
        elmt_P3 = elmt_P3_conc;
        elmt_E14G = elmt_E14G_conc;
        elmt_ERKstar = elmt_ERKstar_conc;
        elmt_OP = elmt_OP_conc;
        elmt_P2 = elmt_P2_conc;
        elmt_RsT = elmt_RsT_conc;
        elmt_H_E4_PT = elmt_H_E4_PT_conc;
        elmt_SigSP_G = elmt_SigSP_G_conc;
        elmt_MEKstar = elmt_MEKstar_conc;
        elmt_E14R = elmt_E14R_conc;
        elmt_E14P = elmt_E14P_conc;
        elmt_E14S = elmt_E14S_conc;
        elmt_E14T = elmt_E14T_conc;
        elmt_E13 = elmt_E13_conc;
        elmt_E14 = elmt_E14_conc;
        elmt_E11 = elmt_E11_conc;
        elmt_E12 = elmt_E12_conc;
        elmt_SigA_G_O = elmt_SigA_G_O_conc;
        elmt_E23G = elmt_E23G_conc;
        elmt_E11G = elmt_E11G_conc;
        elmt_E_E1 = elmt_E_E1_conc;
        elmt_E23I = elmt_E23I_conc;
        elmt_E2 = elmt_E2_conc;
        elmt_SigR = elmt_SigR_conc;
        elmt_E3 = elmt_E3_conc;
        elmt_E23P = elmt_E23P_conc;
        elmt_SigS = elmt_SigS_conc;
        elmt_E1 = elmt_E1_conc;
        elmt_ERK = elmt_ERK_conc;
        elmt_E11R = elmt_E11R_conc;
        elmt_E23S = elmt_E23S_conc;
        elmt_E11S = elmt_E11S_conc;
        elmt_E23T = elmt_E23T_conc;
        elmt_E11P = elmt_E11P_conc;
        elmt_SigT = elmt_SigT_conc;
        elmt_E23R = elmt_E23R_conc;
        elmt_E24 = elmt_E24_conc;
        elmt_E23 = elmt_E23_conc;
        elmt_SigI = elmt_SigI_conc;
        elmt_SigO = elmt_SigO_conc;
        elmt_norm_Akt_star = elmt_norm_Akt_star_conc;
        elmt_Rafstar = elmt_Rafstar_conc;
        elmt_SigA = elmt_SigA_conc;
        elmt_S = elmt_S_conc;
        elmt_SigG = elmt_SigG_conc;
        elmt_T = elmt_T_conc;
        elmt_R = elmt_R_conc;
        elmt_O = elmt_O_conc;
        elmt_E12G = elmt_E12G_conc;
        elmt_ERK_MEKstar = elmt_ERK_MEKstar_conc;
        elmt_E24I = elmt_E24I_conc;
        elmt_P3_A = elmt_P3_A_conc;
        elmt_H_E3 = elmt_H_E3_conc;
        elmt_SigG_A = elmt_SigG_A_conc;
        elmt_H_E4 = elmt_H_E4_conc;
        elmt_E24G = elmt_E24G_conc;
        elmt_I = elmt_I_conc;
        elmt_E24P = elmt_E24P_conc;
        elmt_G = elmt_G_conc;
        elmt_E12P = elmt_E12P_conc;
        elmt_H = elmt_H_conc;
        elmt_E = elmt_E_conc;
        elmt_E12S = elmt_E12S_conc;
        elmt_E24T = elmt_E24T_conc;
        elmt_E12T = elmt_E12T_conc;
        elmt_E1_PT = elmt_E1_PT_conc;
        elmt_A = elmt_A_conc;
        elmt_E24R = elmt_E24R_conc;
        elmt_E12R = elmt_E12R_conc;
        elmt_E24S = elmt_E24S_conc;
        elmt_E11T = elmt_E11T_conc;
        elmt_E34 = elmt_E34_conc;
        elmt_A_SigG_O = elmt_A_SigG_O_conc;
        elmt_E4 = elmt_E4_conc;
        elmt_fint = elmt_fint_conc;
        elmt_pERK = elmt_pERK_conc;
        elmt_SigG_O = elmt_SigG_O_conc;
        elmt_SigAP_I = elmt_SigAP_I_conc;
        elmt_Akt = elmt_Akt_conc;
        elmt_SigAP_T = elmt_SigAP_T_conc;
        elmt_norm_Erk_star = elmt_norm_Erk_star_conc;
        elmt_SigAP_S = elmt_SigAP_S_conc;
        elmt_SigAP_R = elmt_SigAP_R_conc;
        elmt_pERK_MEKstar = elmt_pERK_MEKstar_conc;
        elmt_E4_PT = elmt_E4_PT_conc;
        elmt_E44 = elmt_E44_conc;
        elmt_E44T = elmt_E44T_conc;
        elmt_AP = elmt_AP_conc;
        elmt_E34G = elmt_E34G_conc;
        elmt_E34I = elmt_E34I_conc;
        elmt_E34P = elmt_E34P_conc;
        elmt_E34S = elmt_E34S_conc;
        elmt_E34T = elmt_E34T_conc;
        elmt_E34R = elmt_E34R_conc;
        elmt_ERKstar_ERKpase = elmt_ERKstar_ERKpase_conc;
        elmt_norm_Akt_star_amount = (elmt_Aktstar / 18.8) * elmt_membrane;
        elmt_norm_Erk_star_amount = ((elmt_ERKstar + elmt_ERKstar_ERKpase) / 589.5) * elmt_membrane;
        der(elmt_MEK_amount) = (- (elmt_Net_MEK_Activation * elmt_reactant166));
        der(elmt_Aktstar_amount) = (elmt_Net_Akt_Activation * elmt_product157);
        der(elmt_E2_PT_amount) = (elmt_Net_E2_ST_Phosphorylation * elmt_product264);
        der(elmt_pERK_ERKpase_amount) = ((- (elmt_pERK_dephosphorylation * elmt_reactant320)) + (elmt_pERK_binding_to_Phosphatase * elmt_product319));
        der(elmt_Empty_amount) = ((elmt_EGF_in_EC_compartment * elmt_product296) + (elmt_HRG_in_EC_compartment * elmt_product298) + (- (elmt_mwbbde76d1_155c_4264_8447_4457527547cb * elmt_reactant293)) + (elmt_E11P_Degradation * elmt_product280));
        der(elmt_E_E1_PT_amount) = ((elmt_Net_E_E1_ST_Phosphorylation * elmt_product268) + (elmt_EGF_binding_to_E1PT * elmt_product272));
        der(elmt_E44G_amount) = (elmt_Net_E44PRasGAP_binding_1 * elmt_product110);
        der(elmt_SigA_G_amount) = ((- (elmt_SOS_binding_to_SigAG * elmt_reactant175)) + (elmt_Grb2_binding_to_P3_A * elmt_product174));
        der(elmt_E44I_amount) = (elmt_Net_E44PPI3K_binding * elmt_product118);
        der(elmt_ERKpase_amount) = ((elmt_ERKstar_dephosphorylation * elmt_product316) + (elmt_pERK_dephosphorylation * elmt_product322) + (- (elmt_ERKstar_binding_to_Phosphatase * elmt_reactant312)) + (- (elmt_pERK_binding_to_Phosphatase * elmt_reactant318)));
        der(elmt_E44R_amount) = (elmt_Net_E44PRasGAP_binding_2 * elmt_product122);
        der(elmt_E44S_amount) = (elmt_Net_E44PShc_binding * elmt_product114);
        der(elmt_E44P_amount) = ((- (elmt_Net_E44PRasGAP_binding_1 * elmt_reactant108)) + (- (elmt_Net_E44PRasGAP_binding_2 * elmt_reactant120)) + (elmt_Net_E44_Phosphorylation * elmt_product35) + (- (elmt_Net_E44PPI3K_binding * elmt_reactant116)) + (- (elmt_Net_E44PTP1B_Binding * elmt_reactant249)) + (- (elmt_Net_E44PShc_binding * elmt_reactant112)));
        der(elmt_SigSP_amount) = ((- (elmt_Net_ShcGrb2_binding * elmt_reactant136)) + (elmt_Net_Shc_Phosphorylation * elmt_product125));
        der(elmt_Raf_amount) = (- (elmt_Net_Raf_Activation * elmt_reactant164));
        der(elmt_E13I_amount) = (elmt_Net_E13PI3K_Binding * elmt_product207);
        der(elmt_E13G_amount) = (elmt_Net_E13Grb2_Binding * elmt_product199);
        der(elmt_SigAP_amount) = ((- (elmt_PTP1B_binding_to_SigAP * elmt_reactant275)) + (- (elmt_Net_Gab1RasGAP_binding * elmt_reactant148)) + (- (elmt_Net_Gab1Shc_binding * elmt_reactant140)) + (elmt_Net_Gab1_Phosphorylation * elmt_product127) + (- (elmt_Net_Gab1PI3K_binding * elmt_reactant144)));
        der(elmt_E13P_amount) = ((elmt_Net_E13_Phosphorylation * elmt_product194) + (- (elmt_Net_E13Shc_Binding * elmt_reactant201)) + (- (elmt_Net_E13Grb2_Binding * elmt_reactant197)) + (- (elmt_Net_E13RasGAP_Binding * elmt_reactant209)) + (- (elmt_Net_E13PI3K_Binding * elmt_reactant205)) + (- (elmt_Net_E13PTP1B_Binding * elmt_reactant253)));
        der(elmt_E13T_amount) = (elmt_Net_E13PTP1B_Binding * elmt_product255);
        der(elmt_E13R_amount) = (elmt_Net_E13RasGAP_Binding * elmt_product211);
        der(elmt_E13S_amount) = (elmt_Net_E13Shc_Binding * elmt_product203);
        der(elmt_SigRP_amount) = (elmt_Net_RasGAP_Phosphorylation * elmt_product163);
        der(elmt_RsD_amount) = (- (elmt_Net_RasGTP_Production * elmt_reactant160));
        der(elmt_E14I_amount) = (elmt_Net_E14PI3K_Binding * elmt_product223);
        der(elmt_P3_amount) = ((- (elmt_Net_Gab1PIP3_binding * elmt_reactant152)) + (elmt_Net_PIP3_Production * elmt_product159));
        der(elmt_E14G_amount) = (elmt_Net_E14Grb2_Binding * elmt_product215);
        der(elmt_ERKstar_amount) = ((- (elmt_ERKstar_binding_to_Phosphatase * elmt_reactant311)) + (elmt_ERKstar_production * elmt_product309));
        der(elmt_OP_amount) = (elmt_Net_SOS_ST_Phosphorylation * elmt_product169);
        der(elmt_P2_amount) = (- (elmt_Net_PIP3_Production * elmt_reactant158));
        der(elmt_RsT_amount) = (elmt_Net_RasGTP_Production * elmt_product161);
        der(elmt_H_E4_PT_amount) = ((elmt_Net_H_E4_ST_Phosphorylation * elmt_product270) + (elmt_HRG_binding_to_E4PT * elmt_product274));
        der(elmt_SigSP_G_amount) = (elmt_Net_ShcGrb2_binding * elmt_product138);
        der(elmt_MEKstar_amount) = ((elmt_pERK_production * elmt_product304) + (elmt_ERKstar_production * elmt_product310) + (elmt_Net_MEK_Activation * elmt_product167) + (- (elmt_ERK_binding_to_MEKstar_2 * elmt_reactant306)) + (- (elmt_ERK_binding_to_MEKstar_1 * elmt_reactant300)));
        der(elmt_E14R_amount) = (elmt_Net_E14RasGAP_Binding * elmt_product227);
        der(elmt_E14P_amount) = ((- (elmt_Net_E14Grb2_Binding * elmt_reactant213)) + (- (elmt_Net_E14RasGAP_Binding * elmt_reactant225)) + (- (elmt_Net_E14PTP1B_Binding * elmt_reactant257)) + (elmt_Net_E14_Phosphorylation * elmt_product196) + (- (elmt_Net_E14Shc_Binding * elmt_reactant217)) + (- (elmt_Net_E14PI3K_Binding * elmt_reactant221)));
        der(elmt_E14S_amount) = (elmt_Net_E14Shc_Binding * elmt_product219);
        der(elmt_E14T_amount) = (elmt_Net_E14PTP1B_Binding * elmt_product259);
        der(elmt_E13_amount) = ((- (elmt_Net_E13_Phosphorylation * elmt_reactant193)) + (elmt_ErbB1ErbB3_Heterodimerization * elmt_product189));
        der(elmt_E14_amount) = ((elmt_ErbB1ErbB4_Heterodimerization * elmt_product192) + (- (elmt_Net_E14_Phosphorylation * elmt_reactant195)));
        der(elmt_E11_amount) = ((- (elmt_Net_E11_Phosphorylation * elmt_reactant24)) + (elmt_ErbB1_Dimerization * elmt_product8));
        der(elmt_E12_amount) = ((elmt_ErbB1ErbB2_Heterodimerization * elmt_product11) + (- (elmt_Net_E12_Phosphorylation * elmt_reactant26)));
        der(elmt_SigA_G_O_amount) = (elmt_SOS_binding_to_SigAG * elmt_product177);
        der(elmt_E23G_amount) = (elmt_Net_E23PGrb2_binding * elmt_product62);
        der(elmt_E11G_amount) = ((- (elmt_E11G_Degradation * elmt_reactant281)) + (elmt_Net_E11PGrb2_binding * elmt_product38));
        der(elmt_E_E1_amount) = ((- (elmt_ErbB1ErbB2_Heterodimerization * elmt_reactant9)) + (elmt_EGF_Binding_to_ErbB1 * elmt_product1) + (- (elmt_ErbB1ErbB3_Heterodimerization * elmt_reactant188)) + (- (elmt_Net_E_E1_ST_Phosphorylation * elmt_reactant267)) + (- (elmt_ErbB1ErbB4_Heterodimerization * elmt_reactant191)) + (- (elmt_ErbB1_Dimerization * elmt_reactant6)) + (- (elmt_ErbB1_Dimerization * elmt_reactant7)));
        der(elmt_E23I_amount) = (elmt_Net_E23PPI3K_binding * elmt_product70);
        der(elmt_E2_amount) = ((- (elmt_ErbB1ErbB2_Heterodimerization * elmt_reactant10)) + (- (elmt_ErbB2ErbB4_Heterodimerization * elmt_reactant19)) + (- (elmt_ErbB2ErbB3_Heterodimerization * elmt_reactant13)) + (- (elmt_Net_E2_ST_Phosphorylation * elmt_reactant263)));
        der(elmt_SigR_amount) = ((elmt_Net_E44PRasGAP_binding_2 * elmt_product123) + (elmt_Net_E34PRasGAP_binding * elmt_product91) + (elmt_Net_E12PRasGAP_binding * elmt_product59) + (elmt_Net_E13RasGAP_Binding * elmt_product212) + (elmt_Net_E14RasGAP_Binding * elmt_product228) + (elmt_Net_Gab1RasGAP_binding * elmt_product151) + (elmt_Net_E24PRasGAP_binding * elmt_product107) + (elmt_Net_E11PRasGAP_binding * elmt_product47) + (elmt_Net_E23PRasGAP_binding * elmt_product75) + (- (elmt_E11R_Degradation * elmt_reactant288)) + (- (elmt_Net_RasGAP_Phosphorylation * elmt_reactant162)));
        der(elmt_E3_amount) = (- (elmt_HRG_Binding_to_ErbB3 * elmt_reactant2));
        der(elmt_E23P_amount) = ((- (elmt_Net_E23PGrb2_binding * elmt_reactant60)) + (- (elmt_Net_E23PPI3K_binding * elmt_reactant68)) + (elmt_Net_E23_Phosphorylation * elmt_product29) + (- (elmt_Net_E23PRasGAP_binding * elmt_reactant72)) + (- (elmt_Net_E23PTP1B_Binding * elmt_reactant237)) + (- (elmt_Net_E23PShc_binding * elmt_reactant64)));
        der(elmt_SigS_amount) = ((elmt_Net_E12PShc_binding * elmt_product55) + (elmt_Net_E11PShc_binding * elmt_product43) + (elmt_Net_E13Shc_Binding * elmt_product204) + (elmt_Net_E34PShc_binding * elmt_product83) + (elmt_Net_Gab1Shc_binding * elmt_product143) + (elmt_Net_E14Shc_Binding * elmt_product220) + (elmt_Net_E24PShc_binding * elmt_product99) + (elmt_Net_E23PShc_binding * elmt_product67) + (elmt_Net_E44PShc_binding * elmt_product115) + (- (elmt_Net_Shc_Phosphorylation * elmt_reactant124)) + (- (elmt_E11S_Degradation * elmt_reactant285)));
        der(elmt_E1_amount) = ((- (elmt_Net_E1_ST_Phosphorylation * elmt_reactant261)) + (- (elmt_EGF_Binding_to_ErbB1 * elmt_reactant0)));
        der(elmt_ERK_amount) = ((elmt_pERK_dephosphorylation * elmt_product321) + (- (elmt_ERK_binding_to_MEKstar_1 * elmt_reactant299)));
        der(elmt_E11R_amount) = ((elmt_Net_E11PRasGAP_binding * elmt_product46) + (- (elmt_E11R_Degradation * elmt_reactant287)));
        der(elmt_E23S_amount) = (elmt_Net_E23PShc_binding * elmt_product66);
        der(elmt_E11S_amount) = ((elmt_Net_E11PShc_binding * elmt_product42) + (- (elmt_E11S_Degradation * elmt_reactant284)));
        der(elmt_E23T_amount) = (elmt_Net_E23PTP1B_Binding * elmt_product239);
        der(elmt_E11P_amount) = ((- (elmt_Net_E11PShc_binding * elmt_reactant40)) + (- (elmt_Net_E11PGrb2_binding * elmt_reactant36)) + (elmt_Net_E11_Phosphorylation * elmt_product25) + (- (elmt_Net_E11PRasGAP_binding * elmt_reactant44)) + (- (elmt_E11P_Degradation * elmt_reactant279)) + (- (elmt_Net_E11PTP1B_Binding * elmt_reactant229)));
        der(elmt_SigT_amount) = ((elmt_Net_E24PTP1B_Binding * elmt_product248) + (elmt_Net_E12PTP1B_Binding * elmt_product236) + (elmt_PTP1B_binding_to_SigAP * elmt_product278) + (elmt_Net_E14PTP1B_Binding * elmt_product260) + (elmt_Net_E34PTP1B_Binding * elmt_product244) + (elmt_Net_E23PTP1B_Binding * elmt_product240) + (elmt_Net_E44PTP1B_Binding * elmt_product252) + (elmt_Net_E11PTP1B_Binding * elmt_product232) + (- (elmt_E11T_Degradation * elmt_reactant291)) + (elmt_Net_E13PTP1B_Binding * elmt_product256));
        der(elmt_E23R_amount) = (elmt_Net_E23PRasGAP_binding * elmt_product74);
        der(elmt_E24_amount) = ((- (elmt_Net_E24_Phosphorylation * elmt_reactant32)) + (elmt_ErbB2ErbB4_Heterodimerization * elmt_product20));
        der(elmt_E23_amount) = ((elmt_ErbB2ErbB3_Heterodimerization * elmt_product14) + (- (elmt_Net_E23_Phosphorylation * elmt_reactant28)));
        der(elmt_SigI_amount) = ((elmt_Net_E23PPI3K_binding * elmt_product71) + (elmt_Net_E44PPI3K_binding * elmt_product119) + (elmt_Net_E14PI3K_Binding * elmt_product224) + (elmt_Net_E13PI3K_Binding * elmt_product208) + (elmt_Net_E34PPI3K_binding * elmt_product87) + (elmt_Net_Gab1PI3K_binding * elmt_product147) + (elmt_Net_E24PPI3K_binding * elmt_product103));
        der(elmt_SigO_amount) = ((elmt_SOS_binding_to_SigGA * elmt_product186) + (elmt_Net_Grb2SOS_binding * elmt_product131) + (elmt_SOS_binding_to_SigAG * elmt_product178));
        der(elmt_Rafstar_amount) = (elmt_Net_Raf_Activation * elmt_product165);
        der(elmt_SigA_amount) = ((elmt_Net_Gab1PIP3_binding * elmt_product155) + (- (elmt_Net_Gab1_Phosphorylation * elmt_reactant126)) + (elmt_Net_Grb2Gab1_binding * elmt_product135) + (elmt_Gab1_binding_to_SigGO * elmt_product182));
        der(elmt_S_amount) = ((- (elmt_Net_E12PShc_binding * elmt_reactant53)) + (- (elmt_Net_E11PShc_binding * elmt_reactant41)) + (- (elmt_Net_E13Shc_Binding * elmt_reactant202)) + (- (elmt_Net_E34PShc_binding * elmt_reactant81)) + (- (elmt_Net_Gab1Shc_binding * elmt_reactant141)) + (- (elmt_Net_E14Shc_Binding * elmt_reactant218)) + (- (elmt_Net_E24PShc_binding * elmt_reactant97)) + (- (elmt_Net_E23PShc_binding * elmt_reactant65)) + (- (elmt_Net_E44PShc_binding * elmt_reactant113)) + (elmt_E11S_Degradation * elmt_product286));
        der(elmt_SigG_amount) = ((elmt_Net_E44PRasGAP_binding_1 * elmt_product111) + (elmt_Net_E23PGrb2_binding * elmt_product63) + (elmt_Net_E24PGrb2_binding * elmt_product95) + (- (elmt_E11G_Degradation * elmt_reactant282)) + (elmt_Net_E11PGrb2_binding * elmt_product39) + (elmt_Net_ShcGrb2_binding * elmt_product139) + (elmt_Net_E12PGrb2_binding * elmt_product51) + (elmt_Net_E13Grb2_Binding * elmt_product200) + (elmt_Net_E14Grb2_Binding * elmt_product216) + (elmt_Net_E34PGrb2_binding * elmt_product79) + (- (elmt_Net_Grb2SOS_binding * elmt_reactant128)) + (- (elmt_Net_Grb2Gab1_binding * elmt_reactant132)));
        der(elmt_T_amount) = ((- (elmt_Net_E24PTP1B_Binding * elmt_reactant246)) + (- (elmt_Net_E12PTP1B_Binding * elmt_reactant234)) + (- (elmt_PTP1B_binding_to_SigAP * elmt_reactant276)) + (- (elmt_Net_E14PTP1B_Binding * elmt_reactant258)) + (- (elmt_Net_E34PTP1B_Binding * elmt_reactant242)) + (- (elmt_Net_E23PTP1B_Binding * elmt_reactant238)) + (- (elmt_Net_E44PTP1B_Binding * elmt_reactant250)) + (- (elmt_Net_E11PTP1B_Binding * elmt_reactant230)) + (elmt_E11T_Degradation * elmt_product292) + (- (elmt_Net_E13PTP1B_Binding * elmt_reactant254)));
        der(elmt_R_amount) = ((- (elmt_Net_E44PRasGAP_binding_2 * elmt_reactant121)) + (- (elmt_Net_E34PRasGAP_binding * elmt_reactant89)) + (- (elmt_Net_E12PRasGAP_binding * elmt_reactant57)) + (- (elmt_Net_E13RasGAP_Binding * elmt_reactant210)) + (- (elmt_Net_E14RasGAP_Binding * elmt_reactant226)) + (- (elmt_Net_Gab1RasGAP_binding * elmt_reactant149)) + (- (elmt_Net_E24PRasGAP_binding * elmt_reactant105)) + (- (elmt_Net_E11PRasGAP_binding * elmt_reactant45)) + (- (elmt_Net_E23PRasGAP_binding * elmt_reactant73)) + (elmt_E11R_Degradation * elmt_product289));
        der(elmt_O_amount) = ((- (elmt_Net_SOS_ST_Phosphorylation * elmt_reactant168)) + (- (elmt_SOS_binding_to_SigGA * elmt_reactant184)) + (- (elmt_Net_Grb2SOS_binding * elmt_reactant129)) + (- (elmt_SOS_binding_to_SigAG * elmt_reactant176)));
        der(elmt_E12G_amount) = (elmt_Net_E12PGrb2_binding * elmt_product50);
        der(elmt_ERK_MEKstar_amount) = ((- (elmt_pERK_production * elmt_reactant302)) + (elmt_ERK_binding_to_MEKstar_1 * elmt_product301));
        der(elmt_E24I_amount) = (elmt_Net_E24PPI3K_binding * elmt_product102);
        der(elmt_P3_A_amount) = ((elmt_Net_Gab1PIP3_binding * elmt_product154) + (- (elmt_Grb2_binding_to_P3_A * elmt_reactant173)));
        der(elmt_H_E3_amount) = ((- (elmt_ErbB3ErbB4_Heterodimerization * elmt_reactant15)) + (- (elmt_ErbB1ErbB3_Heterodimerization * elmt_reactant187)) + (elmt_HRG_Binding_to_ErbB3 * elmt_product3) + (- (elmt_ErbB2ErbB3_Heterodimerization * elmt_reactant12)));
        der(elmt_SigG_A_amount) = ((- (elmt_SOS_binding_to_SigGA * elmt_reactant183)) + (elmt_Net_Grb2Gab1_binding * elmt_product134));
        der(elmt_H_E4_amount) = ((- (elmt_ErbB3ErbB4_Heterodimerization * elmt_reactant16)) + (- (elmt_ErbB2ErbB4_Heterodimerization * elmt_reactant18)) + (- (elmt_ErbB4_Homodimerization * elmt_reactant21)) + (- (elmt_ErbB4_Homodimerization * elmt_reactant22)) + (elmt_HRG_Binding_to_ErbB4 * elmt_product5) + (- (elmt_Net_H_E4_ST_Phosphorylation * elmt_reactant269)) + (- (elmt_ErbB1ErbB4_Heterodimerization * elmt_reactant190)));
        der(elmt_E24G_amount) = (elmt_Net_E24PGrb2_binding * elmt_product94);
        der(elmt_I_amount) = ((- (elmt_Net_E23PPI3K_binding * elmt_reactant69)) + (- (elmt_Net_E44PPI3K_binding * elmt_reactant117)) + (- (elmt_Net_E14PI3K_Binding * elmt_reactant222)) + (- (elmt_Net_E13PI3K_Binding * elmt_reactant206)) + (- (elmt_Net_E34PPI3K_binding * elmt_reactant85)) + (- (elmt_Net_Gab1PI3K_binding * elmt_reactant145)) + (- (elmt_Net_E24PPI3K_binding * elmt_reactant101)));
        der(elmt_E24P_amount) = ((elmt_Net_E24_Phosphorylation * elmt_product33) + (- (elmt_Net_E24PTP1B_Binding * elmt_reactant245)) + (- (elmt_Net_E24PGrb2_binding * elmt_reactant92)) + (- (elmt_Net_E24PRasGAP_binding * elmt_reactant104)) + (- (elmt_Net_E24PShc_binding * elmt_reactant96)) + (- (elmt_Net_E24PPI3K_binding * elmt_reactant100)));
        der(elmt_G_amount) = ((- (elmt_Net_E44PRasGAP_binding_1 * elmt_reactant109)) + (- (elmt_Net_E23PGrb2_binding * elmt_reactant61)) + (- (elmt_Net_E24PGrb2_binding * elmt_reactant93)) + (elmt_E11G_Degradation * elmt_product283) + (- (elmt_Net_E11PGrb2_binding * elmt_reactant37)) + (- (elmt_Net_ShcGrb2_binding * elmt_reactant137)) + (- (elmt_Net_E12PGrb2_binding * elmt_reactant49)) + (- (elmt_Net_E13Grb2_Binding * elmt_reactant198)) + (- (elmt_Net_E14Grb2_Binding * elmt_reactant214)) + (- (elmt_Net_E34PGrb2_binding * elmt_reactant77)) + (- (elmt_Grb2_binding_to_P3_A * elmt_reactant172)));
        der(elmt_E12P_amount) = ((- (elmt_Net_E12PShc_binding * elmt_reactant52)) + (- (elmt_Net_E12PGrb2_binding * elmt_reactant48)) + (- (elmt_Net_E12PRasGAP_binding * elmt_reactant56)) + (- (elmt_Net_E12PTP1B_Binding * elmt_reactant233)) + (elmt_Net_E12_Phosphorylation * elmt_product27));
        der(elmt_H_amount) = (- (elmt_HRG_in_EC_compartment * elmt_reactant297));
        der(elmt_E_amount) = (- (elmt_EGF_in_EC_compartment * elmt_reactant295));
        der(elmt_E12S_amount) = (elmt_Net_E12PShc_binding * elmt_product54);
        der(elmt_E24T_amount) = (elmt_Net_E24PTP1B_Binding * elmt_product247);
        der(elmt_E12T_amount) = (elmt_Net_E12PTP1B_Binding * elmt_product235);
        der(elmt_E1_PT_amount) = ((elmt_Net_E1_ST_Phosphorylation * elmt_product262) + (- (elmt_EGF_binding_to_E1PT * elmt_reactant271)));
        der(elmt_A_amount) = ((- (elmt_Net_Gab1_ST_Phosphorylation * elmt_reactant170)) + (- (elmt_Net_Gab1PIP3_binding * elmt_reactant153)) + (- (elmt_Net_Grb2Gab1_binding * elmt_reactant133)) + (- (elmt_Gab1_binding_to_SigGO * elmt_reactant180)));
        der(elmt_E24R_amount) = (elmt_Net_E24PRasGAP_binding * elmt_product106);
        der(elmt_E12R_amount) = (elmt_Net_E12PRasGAP_binding * elmt_product58);
        der(elmt_E24S_amount) = (elmt_Net_E24PShc_binding * elmt_product98);
        der(elmt_E11T_amount) = ((elmt_Net_E11PTP1B_Binding * elmt_product231) + (- (elmt_E11T_Degradation * elmt_reactant290)));
        der(elmt_E34_amount) = ((elmt_ErbB3ErbB4_Heterodimerization * elmt_product17) + (- (elmt_Net_E34_Phosphorylation * elmt_reactant30)));
        der(elmt_A_SigG_O_amount) = ((elmt_SOS_binding_to_SigGA * elmt_product185) + (elmt_Gab1_binding_to_SigGO * elmt_product181));
        der(elmt_E4_amount) = ((- (elmt_HRG_Binding_to_ErbB4 * elmt_reactant4)) + (- (elmt_Net_E4_ST_Phosphorylation * elmt_reactant265)));
        der(elmt_fint_amount) = (elmt_mwbbde76d1_155c_4264_8447_4457527547cb * elmt_product294);
        der(elmt_pERK_amount) = ((elmt_pERK_production * elmt_product303) + (elmt_ERKstar_dephosphorylation * elmt_product315) + (- (elmt_pERK_binding_to_Phosphatase * elmt_reactant317)) + (- (elmt_ERK_binding_to_MEKstar_2 * elmt_reactant305)));
        der(elmt_SigG_O_amount) = ((elmt_Net_Grb2SOS_binding * elmt_product130) + (- (elmt_Gab1_binding_to_SigGO * elmt_reactant179)));
        der(elmt_SigAP_I_amount) = (elmt_Net_Gab1PI3K_binding * elmt_product146);
        der(elmt_Akt_amount) = (- (elmt_Net_Akt_Activation * elmt_reactant156));
        der(elmt_SigAP_T_amount) = (elmt_PTP1B_binding_to_SigAP * elmt_product277);
        der(elmt_SigAP_S_amount) = (elmt_Net_Gab1Shc_binding * elmt_product142);
        der(elmt_SigAP_R_amount) = (elmt_Net_Gab1RasGAP_binding * elmt_product150);
        der(elmt_pERK_MEKstar_amount) = ((- (elmt_ERKstar_production * elmt_reactant308)) + (elmt_ERK_binding_to_MEKstar_2 * elmt_product307));
        der(elmt_E4_PT_amount) = ((- (elmt_HRG_binding_to_E4PT * elmt_reactant273)) + (elmt_Net_E4_ST_Phosphorylation * elmt_product266));
        der(elmt_E44_amount) = ((- (elmt_Net_E44_Phosphorylation * elmt_reactant34)) + (elmt_ErbB4_Homodimerization * elmt_product23));
        der(elmt_E44T_amount) = (elmt_Net_E44PTP1B_Binding * elmt_product251);
        der(elmt_AP_amount) = (elmt_Net_Gab1_ST_Phosphorylation * elmt_product171);
        der(elmt_E34G_amount) = (elmt_Net_E34PGrb2_binding * elmt_product78);
        der(elmt_E34I_amount) = (elmt_Net_E34PPI3K_binding * elmt_product86);
        der(elmt_E34P_amount) = ((- (elmt_Net_E34PRasGAP_binding * elmt_reactant88)) + (- (elmt_Net_E34PGrb2_binding * elmt_reactant76)) + (- (elmt_Net_E34PShc_binding * elmt_reactant80)) + (- (elmt_Net_E34PTP1B_Binding * elmt_reactant241)) + (- (elmt_Net_E34PPI3K_binding * elmt_reactant84)) + (elmt_Net_E34_Phosphorylation * elmt_product31));
        der(elmt_E34S_amount) = (elmt_Net_E34PShc_binding * elmt_product82);
        der(elmt_E34T_amount) = (elmt_Net_E34PTP1B_Binding * elmt_product243);
        der(elmt_E34R_amount) = (elmt_Net_E34PRasGAP_binding * elmt_product90);
        der(elmt_ERKstar_ERKpase_amount) = ((- (elmt_ERKstar_dephosphorylation * elmt_reactant314)) + (elmt_ERKstar_binding_to_Phosphatase * elmt_product313));

    algorithm
        elmt_MEK_conc := elmt_MEK_amount / elmt_membrane;
        elmt_Aktstar_conc := elmt_Aktstar_amount / elmt_membrane;
        elmt_E2_PT_conc := elmt_E2_PT_amount / elmt_membrane;
        elmt_pERK_ERKpase_conc := elmt_pERK_ERKpase_amount / elmt_membrane;
        elmt_Empty_conc := elmt_Empty_amount / elmt_membrane;
        elmt_E_E1_PT_conc := elmt_E_E1_PT_amount / elmt_membrane;
        elmt_E44G_conc := elmt_E44G_amount / elmt_membrane;
        elmt_SigA_G_conc := elmt_SigA_G_amount / elmt_membrane;
        elmt_E44I_conc := elmt_E44I_amount / elmt_membrane;
        elmt_ERKpase_conc := elmt_ERKpase_amount / elmt_membrane;
        elmt_E44R_conc := elmt_E44R_amount / elmt_membrane;
        elmt_E44S_conc := elmt_E44S_amount / elmt_membrane;
        elmt_E44P_conc := elmt_E44P_amount / elmt_membrane;
        elmt_SigSP_conc := elmt_SigSP_amount / elmt_membrane;
        elmt_Raf_conc := elmt_Raf_amount / elmt_membrane;
        elmt_E13I_conc := elmt_E13I_amount / elmt_membrane;
        elmt_E13G_conc := elmt_E13G_amount / elmt_membrane;
        elmt_SigAP_conc := elmt_SigAP_amount / elmt_membrane;
        elmt_E13P_conc := elmt_E13P_amount / elmt_membrane;
        elmt_E13T_conc := elmt_E13T_amount / elmt_membrane;
        elmt_E13R_conc := elmt_E13R_amount / elmt_membrane;
        elmt_E13S_conc := elmt_E13S_amount / elmt_membrane;
        elmt_SigRP_conc := elmt_SigRP_amount / elmt_membrane;
        elmt_RsD_conc := elmt_RsD_amount / elmt_membrane;
        elmt_E14I_conc := elmt_E14I_amount / elmt_membrane;
        elmt_P3_conc := elmt_P3_amount / elmt_membrane;
        elmt_E14G_conc := elmt_E14G_amount / elmt_membrane;
        elmt_ERKstar_conc := elmt_ERKstar_amount / elmt_membrane;
        elmt_OP_conc := elmt_OP_amount / elmt_membrane;
        elmt_P2_conc := elmt_P2_amount / elmt_membrane;
        elmt_RsT_conc := elmt_RsT_amount / elmt_membrane;
        elmt_H_E4_PT_conc := elmt_H_E4_PT_amount / elmt_membrane;
        elmt_SigSP_G_conc := elmt_SigSP_G_amount / elmt_membrane;
        elmt_MEKstar_conc := elmt_MEKstar_amount / elmt_membrane;
        elmt_E14R_conc := elmt_E14R_amount / elmt_membrane;
        elmt_E14P_conc := elmt_E14P_amount / elmt_membrane;
        elmt_E14S_conc := elmt_E14S_amount / elmt_membrane;
        elmt_E14T_conc := elmt_E14T_amount / elmt_membrane;
        elmt_E13_conc := elmt_E13_amount / elmt_membrane;
        elmt_E14_conc := elmt_E14_amount / elmt_membrane;
        elmt_E11_conc := elmt_E11_amount / elmt_membrane;
        elmt_E12_conc := elmt_E12_amount / elmt_membrane;
        elmt_SigA_G_O_conc := elmt_SigA_G_O_amount / elmt_membrane;
        elmt_E23G_conc := elmt_E23G_amount / elmt_membrane;
        elmt_E11G_conc := elmt_E11G_amount / elmt_membrane;
        elmt_E_E1_conc := elmt_E_E1_amount / elmt_membrane;
        elmt_E23I_conc := elmt_E23I_amount / elmt_membrane;
        elmt_E2_conc := elmt_E2_amount / elmt_membrane;
        elmt_SigR_conc := elmt_SigR_amount / elmt_membrane;
        elmt_E3_conc := elmt_E3_amount / elmt_membrane;
        elmt_E23P_conc := elmt_E23P_amount / elmt_membrane;
        elmt_SigS_conc := elmt_SigS_amount / elmt_membrane;
        elmt_E1_conc := elmt_E1_amount / elmt_membrane;
        elmt_ERK_conc := elmt_ERK_amount / elmt_membrane;
        elmt_E11R_conc := elmt_E11R_amount / elmt_membrane;
        elmt_E23S_conc := elmt_E23S_amount / elmt_membrane;
        elmt_E11S_conc := elmt_E11S_amount / elmt_membrane;
        elmt_E23T_conc := elmt_E23T_amount / elmt_membrane;
        elmt_E11P_conc := elmt_E11P_amount / elmt_membrane;
        elmt_SigT_conc := elmt_SigT_amount / elmt_membrane;
        elmt_E23R_conc := elmt_E23R_amount / elmt_membrane;
        elmt_E24_conc := elmt_E24_amount / elmt_membrane;
        elmt_E23_conc := elmt_E23_amount / elmt_membrane;
        elmt_SigI_conc := elmt_SigI_amount / elmt_membrane;
        elmt_SigO_conc := elmt_SigO_amount / elmt_membrane;
        elmt_norm_Akt_star_conc := elmt_norm_Akt_star_amount / elmt_membrane;
        elmt_Rafstar_conc := elmt_Rafstar_amount / elmt_membrane;
        elmt_SigA_conc := elmt_SigA_amount / elmt_membrane;
        elmt_S_conc := elmt_S_amount / elmt_membrane;
        elmt_SigG_conc := elmt_SigG_amount / elmt_membrane;
        elmt_T_conc := elmt_T_amount / elmt_membrane;
        elmt_R_conc := elmt_R_amount / elmt_membrane;
        elmt_O_conc := elmt_O_amount / elmt_membrane;
        elmt_E12G_conc := elmt_E12G_amount / elmt_membrane;
        elmt_ERK_MEKstar_conc := elmt_ERK_MEKstar_amount / elmt_membrane;
        elmt_E24I_conc := elmt_E24I_amount / elmt_membrane;
        elmt_P3_A_conc := elmt_P3_A_amount / elmt_membrane;
        elmt_H_E3_conc := elmt_H_E3_amount / elmt_membrane;
        elmt_SigG_A_conc := elmt_SigG_A_amount / elmt_membrane;
        elmt_H_E4_conc := elmt_H_E4_amount / elmt_membrane;
        elmt_E24G_conc := elmt_E24G_amount / elmt_membrane;
        elmt_I_conc := elmt_I_amount / elmt_membrane;
        elmt_E24P_conc := elmt_E24P_amount / elmt_membrane;
        elmt_G_conc := elmt_G_amount / elmt_membrane;
        elmt_E12P_conc := elmt_E12P_amount / elmt_membrane;
        elmt_H_conc := elmt_H_amount / elmt_membrane;
        elmt_E_conc := elmt_E_amount / elmt_membrane;
        elmt_E12S_conc := elmt_E12S_amount / elmt_membrane;
        elmt_E24T_conc := elmt_E24T_amount / elmt_membrane;
        elmt_E12T_conc := elmt_E12T_amount / elmt_membrane;
        elmt_E1_PT_conc := elmt_E1_PT_amount / elmt_membrane;
        elmt_A_conc := elmt_A_amount / elmt_membrane;
        elmt_E24R_conc := elmt_E24R_amount / elmt_membrane;
        elmt_E12R_conc := elmt_E12R_amount / elmt_membrane;
        elmt_E24S_conc := elmt_E24S_amount / elmt_membrane;
        elmt_E11T_conc := elmt_E11T_amount / elmt_membrane;
        elmt_E34_conc := elmt_E34_amount / elmt_membrane;
        elmt_A_SigG_O_conc := elmt_A_SigG_O_amount / elmt_membrane;
        elmt_E4_conc := elmt_E4_amount / elmt_membrane;
        elmt_fint_conc := elmt_fint_amount / elmt_membrane;
        elmt_pERK_conc := elmt_pERK_amount / elmt_membrane;
        elmt_SigG_O_conc := elmt_SigG_O_amount / elmt_membrane;
        elmt_SigAP_I_conc := elmt_SigAP_I_amount / elmt_membrane;
        elmt_Akt_conc := elmt_Akt_amount / elmt_membrane;
        elmt_SigAP_T_conc := elmt_SigAP_T_amount / elmt_membrane;
        elmt_norm_Erk_star_conc := elmt_norm_Erk_star_amount / elmt_membrane;
        elmt_SigAP_S_conc := elmt_SigAP_S_amount / elmt_membrane;
        elmt_SigAP_R_conc := elmt_SigAP_R_amount / elmt_membrane;
        elmt_pERK_MEKstar_conc := elmt_pERK_MEKstar_amount / elmt_membrane;
        elmt_E4_PT_conc := elmt_E4_PT_amount / elmt_membrane;
        elmt_E44_conc := elmt_E44_amount / elmt_membrane;
        elmt_E44T_conc := elmt_E44T_amount / elmt_membrane;
        elmt_AP_conc := elmt_AP_amount / elmt_membrane;
        elmt_E34G_conc := elmt_E34G_amount / elmt_membrane;
        elmt_E34I_conc := elmt_E34I_amount / elmt_membrane;
        elmt_E34P_conc := elmt_E34P_amount / elmt_membrane;
        elmt_E34S_conc := elmt_E34S_amount / elmt_membrane;
        elmt_E34T_conc := elmt_E34T_amount / elmt_membrane;
        elmt_E34R_conc := elmt_E34R_amount / elmt_membrane;
        elmt_ERKstar_ERKpase_conc := elmt_ERKstar_ERKpase_amount / elmt_membrane;
end Class_elmt_membrane;
