within BIOMD250;
class Reactions

    input Real elmt_nucleus;
    input Real elmt_PreFOSmRNA;
    input Real elmt_KexRSKP;
    input Real elmt_MEK;
    input Real elmt_KimDUSP;
    input Real elmt_m49;
    input Real elmt_p23;
    input Real elmt_A3_2;
    input Real elmt_Kin_2;
    input Real elmt_KimERKPP;
    input Real elmt_pc_FOS_c;
    input Real elmt_c_FOS_c;
    input Real elmt_p33;
    input Real elmt_p32;
    input Real elmt_K27;
    input Real elmt_DUSPmRNA;
    input Real elmt_K24;
    input Real elmt_m56;
    input Real elmt_K25;
    input Real elmt_m54;
    input Real elmt_m52;
    input Real elmt_K20;
    input Real elmt_Elk1_n;
    input Real elmt_m51;
    input Real elmt_K21;
    input Real elmt_p39;
    input Real elmt_p38;
    input Real elmt_pDUSP_n_ppERK_n;
    input Real elmt_K28;
    input Real elmt_K29;
    input Real elmt_p34;
    input Real elmt_pDUSP_n_pERK_n;
    input Real elmt_K30;
    input Real elmt_pMEK;
    input Real elmt_A2;
    input Real elmt_EGF;
    input Real elmt_A3;
    input Real elmt_DUSP_n_pERK_n;
    input Real elmt_A1;
    input Real elmt_K37;
    input Real elmt_K35;
    input Real elmt_K36;
    input Real elmt_K31;
    input Real elmt_p49;
    input Real elmt_V10;
    input Real elmt_p48;
    input Real elmt_p47;
    input Real elmt_FOSn;
    input Real elmt_p46;
    input Real elmt_DUSP_n_ppERK_n;
    input Real elmt_p45;
    input Real elmt_Vc;
    input Real elmt_V115;
    input Real elmt_FOSn_2;
    input Real elmt_KimFOSP;
    input Real elmt_V15;
    input Real elmt_RSK_c;
    input Real elmt_V14;
    input Real elmt_V110;
    input Real elmt_DUSP_c;
    input Real elmt_V113;
    input Real elmt_RsD;
    input Real elmt_V114;
    input Real elmt_V111;
    input Real elmt_V112;
    input Real elmt_p55;
    input Real elmt_KimDUSPP;
    input Real elmt_p54;
    input Real elmt_p53;
    input Real elmt_p52;
    input Real elmt_n10;
    input Real elmt_KexDUSPP;
    input Real elmt_p51;
    input Real elmt_K44;
    input Real elmt_p50;
    input Real elmt_DUSP_n;
    input Real elmt_K42;
    input Real elmt_K43;
    input Real elmt_KF31;
    input Real elmt_V24;
    input Real elmt_pRSK_n;
    input Real elmt_nF31;
    input Real elmt_V21;
    input Real elmt_V20;
    input Real elmt_p59;
    input Real elmt_p58;
    input Real elmt_RsT;
    input Real elmt_p56;
    input Real elmt_V29;
    input Real elmt_V28;
    input Real elmt_V27;
    input Real elmt_Fn;
    input Real elmt_V25;
    input Real elmt_pRSK_c;
    input Real elmt_FmRNA;
    input Real elmt_PreDUSPmRNA;
    input Real elmt_KimERKP;
    input Real elmt_K57;
    input Real elmt_p63;
    input Real elmt_p61;
    input Real elmt_p60;
    input Real elmt_Vn;
    input Real elmt_V35;
    input Real elmt_Fct;
    input Real elmt_KexFOSP;
    input Real elmt_V31;
    input Real elmt_A1_2;
    input Real elmt_V30;
    input Real elmt_KexERK;
    input Real elmt_K106;
    input Real elmt_K105;
    input Real elmt_K108;
    input Real elmt_K107;
    input Real elmt_K102;
    input Real elmt_K101;
    input Real elmt_K104;
    input Real elmt_V37;
    input Real elmt_KexF;
    input Real elmt_K103;
    input Real elmt_V36;
    input Real elmt_c_FOSmRNA;
    input Real elmt_n31;
    input Real elmt_pElk1_n;
    input Real elmt_V44;
    input Real elmt_K111;
    input Real elmt_V43;
    input Real elmt_K110;
    input Real elmt_V42;
    input Real elmt_ERK_n;
    input Real elmt_V5;
    input Real elmt_V6;
    input Real elmt_V106;
    input Real elmt_V107;
    input Real elmt_V104;
    input Real elmt_V105;
    input Real elmt_F;
    input Real elmt_KimFOS;
    input Real elmt_ERK_c;
    input Real elmt_K113;
    input Real elmt_K112;
    input Real elmt_K115;
    input Real elmt_KexERKP;
    input Real elmt_V108;
    input Real elmt_K114;
    input Real elmt_V109;
    input Real elmt_V102;
    input Real elmt_pDUSP_n_ERK_n;
    input Real elmt_V103;
    input Real elmt_K109;
    input Real elmt_V101;
    input Real elmt_V3;
    input Real elmt_V4;
    input Real elmt_V1;
    input Real elmt_V2;
    input Real elmt_V57;
    input Real elmt_K1;
    input Real elmt_A2_2;
    input Real elmt_ppERK_c;
    input Real elmt_CREB_n;
    input Real elmt_KimERK;
    input Real elmt_ppERK_n;
    input Real elmt_HRG;
    input Real elmt_K6;
    input Real elmt_KexDUSP;
    input Real elmt_KimRSKP;
    input Real elmt_K4;
    input Real elmt_K5;
    input Real elmt_K2;
    input Real elmt_K3;
    input Real elmt_pDUSP_c;
    input Real elmt_PreFmRNA;
    input Real elmt_p11;
    input Real elmt_n57;
    input Real elmt_pDUSP_n;
    input Real elmt_KimF;
    input Real elmt_pERK_c;
    input Real elmt_pCREB_n;
    input Real elmt_p17;
    input Real elmt_p16;
    input Real elmt_KexERKPP;
    input Real elmt_p13;
    input Real elmt_p12;
    input Real elmt_KexFOS;
    input Real elmt_DUSP_n_ERK_n;
    input Real elmt_pERK_n;
    input Real elmt_cytoplasm;
    input Real elmt_m47;
    input Real elmt_p22;
    input Real elmt_K15;
    input Real elmt_Kin;
    input Real elmt_K14;
    input Real elmt_K10;

    Real elmt_reaction_70(unit = "") "v104";
    Real elmt_product124 "";
    Real elmt_reactant123 "";
    Real elmt_reaction_71(unit = "") "v105";
    Real elmt_product126 "";
    Real elmt_reactant125 "";
    Real elmt_re118(unit = "") "v058";
    Real elmt_reactant109 "";
    Real elmt_product110 "";
    Real elmt_re119(unit = "") "v062";
    Real elmt_product115 "";
    Real elmt_reactant114 "";
    Real elmt_re115(unit = "") "v032";
    Real elmt_product55 "";
    Real elmt_reactant54 "";
    Real elmt_re116(unit = "") "v040";
    Real elmt_product67 "";
    Real elmt_reactant66 "";
    Real elmt_re117(unit = "") "v041";
    Real elmt_product69 "";
    Real elmt_reactant68 "";
    Real elmt_re110(unit = "") "v011";
    Real elmt_reactant19 "";
    Real elmt_product20 "";
    Real elmt_reaction_27(unit = "") "v049";
    Real elmt_reactant84 "";
    Real elmt_reactant85 "";
    Real elmt_product86 "";
    Real elmt_re111(unit = "") "v018";
    Real elmt_product30 "";
    Real elmt_reactant29 "";
    Real elmt_reaction_28(unit = "") "v050";
    Real elmt_product89 "";
    Real elmt_product88 "";
    Real elmt_reactant87 "";
    Real elmt_re112(unit = "") "v019";
    Real elmt_reactant31 "";
    Real elmt_product32 "";
    Real elmt_reaction_25(unit = "") "v047";
    Real elmt_product80 "";
    Real elmt_reactant78 "";
    Real elmt_reactant79 "";
    Real elmt_reaction_69(unit = "") "v103";
    Real elmt_reactant121 "";
    Real elmt_product122 "";
    Real elmt_re113(unit = "") "v026";
    Real elmt_product44 "";
    Real elmt_reactant43 "";
    Real elmt_reaction_26(unit = "") "v048";
    Real elmt_product83 "";
    Real elmt_product82 "";
    Real elmt_reactant81 "";
    Real elmt_reaction_29(unit = "") "v056";
    Real elmt_reactant106 "";
    Real elmt_reactant105 "";
    Real elmt_product107 "";
    Real elmt_reaction_61(unit = "") "v038";
    Real elmt_reactant64 "";
    Real elmt_reaction_62(unit = "") "v039";
    Real elmt_reactant65 "";
    Real elmt_reaction_67(unit = "") "v036";
    Real elmt_product61 "";
    Real elmt_reactant60 "";
    Real elmt_reaction_23(unit = "") "v054";
    Real elmt_product101 "";
    Real elmt_reactant99 "";
    Real elmt_reactant100 "";
    Real elmt_reaction_24(unit = "") "v055";
    Real elmt_product104 "";
    Real elmt_product103 "";
    Real elmt_reactant102 "";
    Real elmt_reaction_68(unit = "") "v102";
    Real elmt_product120 "";
    Real elmt_reactant119 "";
    Real elmt_reaction_21(unit = "") "v052";
    Real elmt_reactant94 "";
    Real elmt_product95 "";
    Real elmt_reactant93 "";
    Real elmt_reaction_22(unit = "") "v053";
    Real elmt_reactant96 "";
    Real elmt_product98 "";
    Real elmt_product97 "";
    Real elmt_reaction_60(unit = "") "v037";
    Real elmt_product63 "";
    Real elmt_reactant62 "";
    Real elmt_reaction_17(unit = "") "v012";
    Real elmt_reactant21 "";
    Real elmt_reaction_14(unit = "") "v022";
    Real elmt_reactant37 "";
    Real elmt_reaction_58(unit = "") "v030";
    Real elmt_product52 "";
    Real elmt_reactant51 "";
    Real elmt_reaction_15(unit = "") "v023";
    Real elmt_reactant38 "";
    Real elmt_reaction_59(unit = "") "v035";
    Real elmt_reactant58 "";
    Real elmt_product59 "";
    Real elmt_reaction_6(unit = "") "v002";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_reaction_52(unit = "") "v042";
    Real elmt_product71 "";
    Real elmt_reactant70 "";
    Real elmt_reaction_53(unit = "") "v043";
    Real elmt_reactant72 "";
    Real elmt_product73 "";
    Real elmt_reaction_50(unit = "") "v033";
    Real elmt_reactant56 "";
    Real elmt_reaction_12(unit = "") "v020";
    Real elmt_product34 "";
    Real elmt_reactant33 "";
    Real elmt_reaction_56(unit = "") "v046";
    Real elmt_reactant77 "";
    Real elmt_reaction_13(unit = "") "v021";
    Real elmt_product36 "";
    Real elmt_reactant35 "";
    Real elmt_reaction_57(unit = "") "v029";
    Real elmt_product50 "";
    Real elmt_reactant49 "";
    Real elmt_reaction_54(unit = "") "v044";
    Real elmt_reactant74 "";
    Real elmt_product75 "";
    Real elmt_reaction_55(unit = "") "v045";
    Real elmt_reactant76 "";
    Real elmt_re95(unit = "") "v060";
    Real elmt_product112 "";
    Real elmt_re96(unit = "") "v061";
    Real elmt_reactant113 "";
    Real elmt_re99(unit = "") "v063";
    Real elmt_reactant116 "";
    Real elmt_reaction_47(unit = "") "v031";
    Real elmt_product53 "";
    Real elmt_reaction_41(unit = "") "v024";
    Real elmt_product40 "";
    Real elmt_reactant39 "";
    Real elmt_reaction_42(unit = "") "v025";
    Real elmt_reactant41 "";
    Real elmt_product42 "";
    Real elmt_reaction_45(unit = "") "v027";
    Real elmt_product46 "";
    Real elmt_reactant45 "";
    Real elmt_reaction_46(unit = "") "v028";
    Real elmt_reactant47 "";
    Real elmt_product48 "";
    Real elmt_reaction_81(unit = "") "v115";
    Real elmt_product146 "";
    Real elmt_reactant145 "";
    Real elmt_reaction_80(unit = "") "v114";
    Real elmt_reactant143 "";
    Real elmt_product144 "";
    Real elmt_re107(unit = "") "v008";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_re85(unit = "") "v003";
    Real elmt_reactant4 "";
    Real elmt_product5 "";
    Real elmt_re108(unit = "") "v009";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_re86(unit = "") "v004";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_re109(unit = "") "v010";
    Real elmt_product18 "";
    Real elmt_re87(unit = "") "v005";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_re88(unit = "") "v006";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_re89(unit = "") "v013";
    Real elmt_product22 "";
    Real elmt_re106(unit = "") "v007";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_reaction_36(unit = "") "v017";
    Real elmt_reactant28 "";
    Real elmt_re90(unit = "") "v034";
    Real elmt_product57 "";
    Real elmt_re92(unit = "") "v057";
    Real elmt_product108 "";
    Real elmt_re94(unit = "") "v059";
    Real elmt_reactant111 "";
    Real elmt_reaction_30(unit = "") "v051";
    Real elmt_reactant90 "";
    Real elmt_reactant91 "";
    Real elmt_product92 "";
    Real elmt_reaction_74(unit = "") "v108";
    Real elmt_reactant131 "";
    Real elmt_product132 "";
    Real elmt_reaction_31(unit = "") "v101";
    Real elmt_reactant117 "";
    Real elmt_product118 "";
    Real elmt_reaction_75(unit = "") "v109";
    Real elmt_product134 "";
    Real elmt_reactant133 "";
    Real elmt_reaction_72(unit = "") "v106";
    Real elmt_reactant127 "";
    Real elmt_product128 "";
    Real elmt_reaction_73(unit = "") "v107";
    Real elmt_product130 "";
    Real elmt_reactant129 "";
    Real elmt_reaction_34(unit = "") "v015";
    Real elmt_reactant25 "";
    Real elmt_product26 "";
    Real elmt_reaction_78(unit = "") "v112";
    Real elmt_reactant139 "";
    Real elmt_product140 "";
    Real elmt_reaction_35(unit = "") "v016";
    Real elmt_reactant27 "";
    Real elmt_reaction_79(unit = "") "v113";
    Real elmt_reactant141 "";
    Real elmt_product142 "";
    Real elmt_reaction_32(unit = "") "v001";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_reaction_76(unit = "") "v110";
    Real elmt_product136 "";
    Real elmt_reactant135 "";
    Real elmt_reaction_33(unit = "") "v014";
    Real elmt_product24 "";
    Real elmt_reactant23 "";
    Real elmt_reaction_77(unit = "") "v111";
    Real elmt_reactant137 "";
    Real elmt_product138 "";


    initial equation
        elmt_product73 = 1.0;
        elmt_reactant41 = 1.0;
        elmt_product71 = 1.0;
        elmt_reactant109 = 1.0;
        elmt_product75 = 1.0;
        elmt_reactant47 = 1.0;
        elmt_reactant49 = 1.0;
        elmt_reactant43 = 1.0;
        elmt_reactant45 = 1.0;
        elmt_reactant117 = 1.0;
        elmt_product69 = 1.0;
        elmt_reactant116 = 1.0;
        elmt_reactant114 = 1.0;
        elmt_reactant113 = 1.0;
        elmt_reactant111 = 1.0;
        elmt_reactant51 = 1.0;
        elmt_product83 = 1.0;
        elmt_product82 = 1.0;
        elmt_product89 = 1.0;
        elmt_product88 = 1.0;
        elmt_product86 = 1.0;
        elmt_reactant119 = 1.0;
        elmt_reactant58 = 1.0;
        elmt_reactant54 = 1.0;
        elmt_product80 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_reactant121 = 1.0;
        elmt_product101 = 1.0;
        elmt_product104 = 1.0;
        elmt_product103 = 1.0;
        elmt_reactant129 = 1.0;
        elmt_reactant127 = 1.0;
        elmt_reactant125 = 1.0;
        elmt_reactant123 = 1.0;
        elmt_product108 = 1.0;
        elmt_product107 = 1.0;
        elmt_product95 = 1.0;
        elmt_product11 = 1.0;
        elmt_product98 = 1.0;
        elmt_product97 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_product92 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product9 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant31 = 1.0;
        elmt_product22 = 1.0;
        elmt_product20 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant37 = 1.0;
        elmt_reactant38 = 1.0;
        elmt_reactant39 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant33 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant35 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_reactant106 = 1.0;
        elmt_product15 = 1.0;
        elmt_reactant105 = 1.0;
        elmt_product13 = 1.0;
        elmt_reactant102 = 1.0;
        elmt_product18 = 1.0;
        elmt_reactant100 = 1.0;
        elmt_product17 = 1.0;
        elmt_product30 = 1.0;
        elmt_reactant84 = 1.0;
        elmt_reactant85 = 1.0;
        elmt_product34 = 1.0;
        elmt_product32 = 1.0;
        elmt_reactant81 = 1.0;
        elmt_reactant87 = 1.0;
        elmt_product134 = 1.0;
        elmt_product136 = 1.0;
        elmt_product130 = 1.0;
        elmt_product132 = 1.0;
        elmt_product26 = 1.0;
        elmt_product24 = 1.0;
        elmt_product138 = 1.0;
        elmt_reactant94 = 1.0;
        elmt_product40 = 1.0;
        elmt_reactant96 = 1.0;
        elmt_reactant90 = 1.0;
        elmt_product44 = 1.0;
        elmt_reactant91 = 1.0;
        elmt_reactant93 = 1.0;
        elmt_product42 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_product140 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant99 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_product146 = 1.0;
        elmt_product142 = 1.0;
        elmt_product144 = 1.0;
        elmt_product36 = 1.0;
        elmt_product52 = 1.0;
        elmt_reactant62 = 1.0;
        elmt_product50 = 1.0;
        elmt_reactant64 = 1.0;
        elmt_product55 = 1.0;
        elmt_reactant60 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant65 = 1.0;
        elmt_reactant66 = 1.0;
        elmt_reactant68 = 1.0;
        elmt_product112 = 1.0;
        elmt_reactant131 = 1.0;
        elmt_product115 = 1.0;
        elmt_product110 = 1.0;
        elmt_product48 = 1.0;
        elmt_reactant139 = 1.0;
        elmt_product46 = 1.0;
        elmt_reactant137 = 1.0;
        elmt_reactant135 = 1.0;
        elmt_product118 = 1.0;
        elmt_reactant133 = 1.0;
        elmt_product63 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_reactant72 = 1.0;
        elmt_product61 = 1.0;
        elmt_reactant74 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product67 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_reactant70 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_reactant76 = 1.0;
        elmt_reactant77 = 1.0;
        elmt_reactant78 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant79 = 1.0;
        elmt_product124 = 1.0;
        elmt_reactant143 = 1.0;
        elmt_product126 = 1.0;
        elmt_reactant141 = 1.0;
        elmt_product120 = 1.0;
        elmt_product122 = 1.0;
        elmt_product59 = 1.0;
        elmt_product57 = 1.0;
        elmt_product128 = 1.0;
        elmt_reactant145 = 1.0;


    equation
        elmt_reaction_70 = (elmt_cytoplasm * (((elmt_V104 * elmt_A2_2) / (elmt_K104 + elmt_A2_2))));
        elmt_reaction_71 = (elmt_cytoplasm * (((elmt_V105 * elmt_EGF * elmt_RsD) / (elmt_K105 + elmt_RsD))));
        elmt_re118 = ((elmt_p58 * elmt_Vn * elmt_PreFmRNA));
        elmt_re119 = (((elmt_KimF * elmt_Vc * elmt_F) - (elmt_KexF * elmt_Vn * elmt_Fn)));
        elmt_re115 = ((elmt_p32 * elmt_Vn * elmt_PreFOSmRNA));
        elmt_re116 = (((elmt_KimFOS * elmt_Vc * elmt_c_FOS_c) - (elmt_KexFOS * elmt_Vn * elmt_FOSn)));
        elmt_re117 = (((elmt_KimFOSP * elmt_Vc * elmt_pc_FOS_c) - (elmt_KexFOSP * elmt_Vn * elmt_FOSn_2)));
        elmt_re110 = ((elmt_p11 * elmt_Vn * elmt_PreDUSPmRNA));
        elmt_reaction_27 = (elmt_nucleus * ((elmt_p54 * elmt_pDUSP_n * elmt_pERK_n) - (elmt_m54 * elmt_pDUSP_n_pERK_n)));
        elmt_re111 = (((elmt_KimDUSP * elmt_Vc * elmt_DUSP_c) - (elmt_KexDUSP * elmt_Vn * elmt_DUSP_n)));
        elmt_reaction_28 = (elmt_nucleus * elmt_p55 * elmt_pDUSP_n_pERK_n);
        elmt_re112 = (((elmt_KimDUSPP * elmt_Vc * elmt_pDUSP_c) - (elmt_KexDUSPP * elmt_Vn * elmt_pDUSP_n)));
        elmt_reaction_25 = (elmt_nucleus * ((elmt_p52 * elmt_pDUSP_n * elmt_ppERK_n) - (elmt_m52 * elmt_pDUSP_n_ppERK_n)));
        elmt_reaction_69 = (elmt_cytoplasm * (((elmt_V103 * elmt_HRG * elmt_A2) / (elmt_K103 + elmt_A2))));
        elmt_re113 = (((elmt_KimRSKP * elmt_Vc * elmt_pRSK_c) - (elmt_KexRSKP * elmt_Vn * elmt_pRSK_n)));
        elmt_reaction_26 = (elmt_nucleus * elmt_p53 * elmt_pDUSP_n_ppERK_n);
        elmt_reaction_29 = (elmt_nucleus * ((elmt_p51 * elmt_DUSP_n * elmt_ERK_n) - (elmt_m51 * elmt_DUSP_n_ERK_n)));
        elmt_reaction_61 = (elmt_cytoplasm * elmt_p38 * elmt_c_FOS_c);
        elmt_reaction_62 = (elmt_cytoplasm * elmt_p39 * elmt_pc_FOS_c);
        elmt_reaction_67 = (elmt_cytoplasm * (((elmt_V36 * elmt_pRSK_c * elmt_c_FOS_c) / (elmt_K36 + elmt_c_FOS_c))));
        elmt_reaction_23 = (elmt_nucleus * ((elmt_p49 * elmt_DUSP_n * elmt_pERK_n) - (elmt_m49 * elmt_DUSP_n_pERK_n)));
        elmt_reaction_24 = (elmt_nucleus * elmt_p50 * elmt_DUSP_n_pERK_n);
        elmt_reaction_68 = (elmt_cytoplasm * (((elmt_V102 * elmt_A1_2) / (elmt_K102 + elmt_A1_2))));
        elmt_reaction_21 = (elmt_nucleus * ((elmt_p47 * elmt_DUSP_n * elmt_ppERK_n) - (elmt_m47 * elmt_DUSP_n_ppERK_n)));
        elmt_reaction_22 = (elmt_nucleus * elmt_p48 * elmt_DUSP_n_ppERK_n);
        elmt_reaction_60 = (elmt_cytoplasm * (((elmt_V37 * elmt_pc_FOS_c) / (elmt_K37 + elmt_pc_FOS_c))));
        elmt_reaction_17 = (elmt_cytoplasm * elmt_p12 * elmt_DUSPmRNA);
        elmt_reaction_14 = (elmt_nucleus * elmt_p22 * elmt_DUSP_n);
        elmt_reaction_58 = (elmt_nucleus * (((elmt_V30 * elmt_pElk1_n) / (elmt_K30 + elmt_pElk1_n))));
        elmt_reaction_15 = (elmt_nucleus * elmt_p23 * elmt_pDUSP_n);
        elmt_reaction_59 = (elmt_cytoplasm * (((elmt_V35 * elmt_ppERK_c * elmt_c_FOS_c) / (elmt_K35 + elmt_c_FOS_c))));
        elmt_reaction_6 = (elmt_cytoplasm * (((elmt_V2 * elmt_Fct * elmt_pMEK * elmt_pERK_c) / ((elmt_K2 * (1.0 + (elmt_ERK_c / elmt_K1))) + elmt_pERK_c))));
        elmt_reaction_52 = (elmt_nucleus * (((elmt_V42 * elmt_ppERK_n * elmt_FOSn) / (elmt_K42 + elmt_FOSn))));
        elmt_reaction_53 = (elmt_nucleus * (((elmt_V43 * elmt_pRSK_n * elmt_FOSn) / (elmt_K43 + elmt_FOSn))));
        elmt_reaction_50 = (elmt_cytoplasm * elmt_p33 * elmt_c_FOSmRNA);
        elmt_reaction_12 = (elmt_nucleus * (((elmt_V20 * elmt_ppERK_n * elmt_DUSP_n) / (elmt_K20 + elmt_DUSP_n))));
        elmt_reaction_56 = (elmt_nucleus * elmt_p46 * elmt_FOSn_2);
        elmt_reaction_13 = (elmt_nucleus * (((elmt_V21 * elmt_pDUSP_n) / (elmt_K21 + elmt_pDUSP_n))));
        elmt_reaction_57 = (elmt_nucleus * (((elmt_V29 * elmt_ppERK_n * elmt_Elk1_n) / (elmt_K29 + elmt_Elk1_n))));
        elmt_reaction_54 = (elmt_nucleus * (((elmt_V44 * elmt_FOSn_2) / (elmt_K44 + elmt_FOSn_2))));
        elmt_reaction_55 = (elmt_nucleus * elmt_p45 * elmt_FOSn);
        elmt_re95 = (elmt_cytoplasm * ((elmt_p60 * elmt_FmRNA)));
        elmt_re96 = (elmt_cytoplasm * elmt_p61 * elmt_F);
        elmt_re99 = (elmt_nucleus * (((elmt_cytoplasm * elmt_p63 * elmt_Fn) / elmt_nucleus)));
        elmt_reaction_47 = (elmt_nucleus * (((elmt_V31 * Functions.pow((elmt_pCREB_n * elmt_pElk1_n), elmt_n31)) / (Functions.pow(elmt_K31, elmt_n31) + Functions.pow((elmt_pCREB_n * elmt_pElk1_n), elmt_n31) + Functions.pow((elmt_Fn / elmt_KF31), elmt_nF31)))));
        elmt_reaction_41 = (elmt_cytoplasm * (((elmt_V24 * elmt_ppERK_c * elmt_RSK_c) / (elmt_K24 + elmt_RSK_c))));
        elmt_reaction_42 = (elmt_cytoplasm * (((elmt_V25 * elmt_pRSK_c) / (elmt_K25 + elmt_pRSK_c))));
        elmt_reaction_45 = (elmt_nucleus * (((elmt_V27 * elmt_pRSK_n * elmt_CREB_n) / (elmt_K27 + elmt_CREB_n))));
        elmt_reaction_46 = (elmt_nucleus * (((elmt_V28 * elmt_pCREB_n) / (elmt_K28 + elmt_pCREB_n))));
        elmt_reaction_81 = (elmt_cytoplasm * (((elmt_V115 * elmt_pMEK) / (elmt_K115 + elmt_pMEK))));
        elmt_reaction_80 = (elmt_cytoplasm * (((elmt_V114 * elmt_Kin_2 * elmt_MEK) / (elmt_K114 + elmt_MEK))));
        elmt_re107 = (((elmt_KimERKP * elmt_Vc * elmt_pERK_c) - (elmt_KexERKP * elmt_Vn * elmt_pERK_n)));
        elmt_re85 = (elmt_cytoplasm * (((elmt_V3 * elmt_pERK_c) / ((elmt_K3 * (1.0 + (elmt_ppERK_c / elmt_K4))) + elmt_pERK_c))));
        elmt_re108 = (((elmt_KimERKPP * elmt_Vc * elmt_ppERK_c) - (elmt_KexERKPP * elmt_Vn * elmt_ppERK_n)));
        elmt_re86 = (elmt_cytoplasm * (((elmt_V4 * elmt_ppERK_c) / ((elmt_K4 * (1.0 + (elmt_pERK_c / elmt_K3))) + elmt_ppERK_c))));
        elmt_re109 = (elmt_nucleus * (((elmt_V10 * Functions.pow(elmt_ppERK_n, elmt_n10)) / (Functions.pow(elmt_K10, elmt_n10) + Functions.pow(elmt_ppERK_n, elmt_n10)))));
        elmt_re87 = (elmt_nucleus * (((elmt_V5 * elmt_pERK_n) / ((elmt_K5 * (1.0 + (elmt_ppERK_n / elmt_K6))) + elmt_pERK_n))));
        elmt_re88 = (elmt_nucleus * (((elmt_V6 * elmt_ppERK_n) / ((elmt_K6 * (1.0 + (elmt_pERK_n / elmt_K5))) + elmt_ppERK_n))));
        elmt_re89 = (elmt_cytoplasm * ((elmt_p13 * elmt_DUSPmRNA)));
        elmt_re106 = (((elmt_KimERK * elmt_Vc * elmt_ERK_c) - (elmt_KexERK * elmt_Vn * elmt_ERK_n)));
        elmt_reaction_36 = (elmt_cytoplasm * elmt_p17 * elmt_pDUSP_c);
        elmt_re90 = (elmt_cytoplasm * ((elmt_p34 * elmt_c_FOSmRNA)));
        elmt_re92 = (elmt_nucleus * (((elmt_V57 * Functions.pow(elmt_FOSn_2, elmt_n57)) / (Functions.pow(elmt_K57, elmt_n57) + Functions.pow(elmt_FOSn_2, elmt_n57)))));
        elmt_re94 = (elmt_cytoplasm * elmt_p59 * elmt_FmRNA);
        elmt_reaction_30 = (elmt_nucleus * ((elmt_p56 * elmt_pDUSP_n * elmt_ERK_n) - (elmt_m56 * elmt_pDUSP_n_ERK_n)));
        elmt_reaction_74 = (elmt_cytoplasm * (((elmt_V108 * elmt_A2_2 * elmt_RsT) / (elmt_K108 + elmt_RsT))));
        elmt_reaction_31 = (elmt_cytoplasm * (((elmt_V101 * elmt_EGF * elmt_A1) / (elmt_K101 + elmt_A1))));
        elmt_reaction_75 = (elmt_cytoplasm * (((elmt_V109 * elmt_HRG * elmt_A3) / (elmt_K109 + elmt_A3))));
        elmt_reaction_72 = (elmt_cytoplasm * (((elmt_V106 * elmt_HRG * elmt_RsD) / (elmt_K106 + elmt_RsD))));
        elmt_reaction_73 = (elmt_cytoplasm * (((elmt_V107 * elmt_A1_2 * elmt_RsT) / (elmt_K107 + elmt_RsT))));
        elmt_reaction_34 = (elmt_cytoplasm * (((elmt_V15 * elmt_pDUSP_c) / (elmt_K15 + elmt_pDUSP_c))));
        elmt_reaction_78 = (elmt_cytoplasm * (((elmt_V112 * elmt_A3_2 * elmt_Kin_2) / (elmt_K112 + elmt_Kin_2))));
        elmt_reaction_35 = (elmt_cytoplasm * elmt_p16 * elmt_DUSP_c);
        elmt_reaction_79 = (elmt_cytoplasm * (((elmt_V113 * elmt_RsT * elmt_MEK) / (elmt_K113 + elmt_MEK))));
        elmt_reaction_32 = (elmt_cytoplasm * (((elmt_V1 * elmt_Fct * elmt_pMEK * elmt_ERK_c) / ((elmt_K1 * (1.0 + (elmt_pERK_c / elmt_K2))) + elmt_ERK_c))));
        elmt_reaction_76 = (elmt_cytoplasm * (((elmt_V110 * elmt_A3_2) / (elmt_K110 + elmt_A3_2))));
        elmt_reaction_33 = (elmt_cytoplasm * (((elmt_V14 * elmt_ppERK_c * elmt_DUSP_c) / (elmt_K14 + elmt_DUSP_c))));
        elmt_reaction_77 = (elmt_cytoplasm * (((elmt_V111 * elmt_HRG * elmt_Kin) / (elmt_K111 + elmt_Kin))));
        der(elmt_product73) = 0;
        der(elmt_reactant41) = 0;
        der(elmt_product71) = 0;
        der(elmt_reactant109) = 0;
        der(elmt_product75) = 0;
        der(elmt_reactant47) = 0;
        der(elmt_reactant49) = 0;
        der(elmt_reactant43) = 0;
        der(elmt_reactant45) = 0;
        der(elmt_reactant117) = 0;
        der(elmt_product69) = 0;
        der(elmt_reactant116) = 0;
        der(elmt_reactant114) = 0;
        der(elmt_reactant113) = 0;
        der(elmt_reactant111) = 0;
        der(elmt_reactant51) = 0;
        der(elmt_product83) = 0;
        der(elmt_product82) = 0;
        der(elmt_product89) = 0;
        der(elmt_product88) = 0;
        der(elmt_product86) = 0;
        der(elmt_reactant119) = 0;
        der(elmt_reactant58) = 0;
        der(elmt_reactant54) = 0;
        der(elmt_product80) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_reactant121) = 0;
        der(elmt_product101) = 0;
        der(elmt_product104) = 0;
        der(elmt_product103) = 0;
        der(elmt_reactant129) = 0;
        der(elmt_reactant127) = 0;
        der(elmt_reactant125) = 0;
        der(elmt_reactant123) = 0;
        der(elmt_product108) = 0;
        der(elmt_product107) = 0;
        der(elmt_product95) = 0;
        der(elmt_product11) = 0;
        der(elmt_product98) = 0;
        der(elmt_product97) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_product92) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product9) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant31) = 0;
        der(elmt_product22) = 0;
        der(elmt_product20) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant37) = 0;
        der(elmt_reactant38) = 0;
        der(elmt_reactant39) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant33) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant35) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_reactant106) = 0;
        der(elmt_product15) = 0;
        der(elmt_reactant105) = 0;
        der(elmt_product13) = 0;
        der(elmt_reactant102) = 0;
        der(elmt_product18) = 0;
        der(elmt_reactant100) = 0;
        der(elmt_product17) = 0;
        der(elmt_product30) = 0;
        der(elmt_reactant84) = 0;
        der(elmt_reactant85) = 0;
        der(elmt_product34) = 0;
        der(elmt_product32) = 0;
        der(elmt_reactant81) = 0;
        der(elmt_reactant87) = 0;
        der(elmt_product134) = 0;
        der(elmt_product136) = 0;
        der(elmt_product130) = 0;
        der(elmt_product132) = 0;
        der(elmt_product26) = 0;
        der(elmt_product24) = 0;
        der(elmt_product138) = 0;
        der(elmt_reactant94) = 0;
        der(elmt_product40) = 0;
        der(elmt_reactant96) = 0;
        der(elmt_reactant90) = 0;
        der(elmt_product44) = 0;
        der(elmt_reactant91) = 0;
        der(elmt_reactant93) = 0;
        der(elmt_product42) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_product140) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant99) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_product146) = 0;
        der(elmt_product142) = 0;
        der(elmt_product144) = 0;
        der(elmt_product36) = 0;
        der(elmt_product52) = 0;
        der(elmt_reactant62) = 0;
        der(elmt_product50) = 0;
        der(elmt_reactant64) = 0;
        der(elmt_product55) = 0;
        der(elmt_reactant60) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant65) = 0;
        der(elmt_reactant66) = 0;
        der(elmt_reactant68) = 0;
        der(elmt_product112) = 0;
        der(elmt_reactant131) = 0;
        der(elmt_product115) = 0;
        der(elmt_product110) = 0;
        der(elmt_product48) = 0;
        der(elmt_reactant139) = 0;
        der(elmt_product46) = 0;
        der(elmt_reactant137) = 0;
        der(elmt_reactant135) = 0;
        der(elmt_product118) = 0;
        der(elmt_reactant133) = 0;
        der(elmt_product63) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_reactant72) = 0;
        der(elmt_product61) = 0;
        der(elmt_reactant74) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product67) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_reactant70) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_reactant76) = 0;
        der(elmt_reactant77) = 0;
        der(elmt_reactant78) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant79) = 0;
        der(elmt_product124) = 0;
        der(elmt_reactant143) = 0;
        der(elmt_product126) = 0;
        der(elmt_reactant141) = 0;
        der(elmt_product120) = 0;
        der(elmt_product122) = 0;
        der(elmt_product59) = 0;
        der(elmt_product57) = 0;
        der(elmt_product128) = 0;
        der(elmt_reactant145) = 0;

end Reactions;
