within BIOMD303;
class Reactions

    input Real elmt_compartment;
    input Real elmt_kf01_1;
    input Real elmt_GlcNac_LF_CRP_MASP;
    input Real elmt_kg03_1;
    input Real elmt_ka04_1;
    input Real elmt_kg03_2;
    input Real elmt_ka04_2;
    input Real elmt_kc02;
    input Real elmt_PC;
    input Real elmt_kc04_2;
    input Real elmt_CRP;
    input Real elmt_HF;
    input Real elmt_GlcNac;
    input Real elmt_kd01_1;
    input Real elmt_kd01_2;
    input Real elmt_PC_CRP_LF;
    input Real elmt_kd05_1;
    input Real elmt_C4BP;
    input Real elmt_kd05_2;
    input Real elmt_kd09_1;
    input Real elmt_kd09_2;
    input Real elmt_ke07_1;
    input Real elmt_ke07_2;
    input Real elmt_kc04_1;
    input Real elmt_ke03_1;
    input Real elmt_ke03_2;
    input Real elmt_dC4b_C2a_C4BP;
    input Real elmt_kf01_2;
    input Real elmt_PC_CRP_LF_MASP;
    input Real elmt_kb02_2;
    input Real elmt_kb02_1;
    input Real elmt_C2a;
    input Real elmt_kg02_2;
    input Real elmt_kg02_1;
    input Real elmt_C4BP_PC_CRP;
    input Real elmt_ka01_2;
    input Real elmt_ka01_1;
    input Real elmt_ke02_1;
    input Real elmt_GlcNac_HF;
    input Real elmt_MASP;
    input Real elmt_dC3b;
    input Real elmt_kd04_1;
    input Real elmt_kd04_2;
    input Real elmt_GlcNac_HF_MASP;
    input Real elmt_kd08_1;
    input Real elmt_kd08_2;
    input Real elmt_C3b;
    input Real elmt_GlcNac_LF_CRP;
    input Real elmt_ke06_2;
    input Real elmt_ke06_1;
    input Real elmt_kc01_1;
    input Real elmt_ke02_2;
    input Real elmt_kc01_2;
    input Real elmt_C4BP_C4b;
    input Real elmt_PC_CRP;
    input Real elmt_kd11_1;
    input Real elmt_kd11_2;
    input Real elmt_kb03_2;
    input Real elmt_kf04_1;
    input Real elmt_kb03_1;
    input Real elmt_kf04_2;
    input Real elmt_C4BP_GlcNac_LF_CRP;
    input Real elmt_C4b;
    input Real elmt_ka02_2;
    input Real elmt_kg01_1;
    input Real elmt_kg01_2;
    input Real elmt_ka02_1;
    input Real elmt_ke01_1;
    input Real elmt_ke01_2;
    input Real elmt_GlcNac_LF_MASP;
    input Real elmt_X;
    input Real elmt_LF;
    input Real elmt_kd03_1;
    input Real elmt_kd03_2;
    input Real elmt_kd07_1;
    input Real elmt_kd07_2;
    input Real elmt_dC4b_C2a;
    input Real elmt_ke05_1;
    input Real elmt_ke05_2;
    input Real elmt_kf07_1;
    input Real elmt_kf07_2;
    input Real elmt_kd10_1;
    input Real elmt_kd10_2;
    input Real elmt_kb04_2;
    input Real elmt_kb04_1;
    input Real elmt_C4b_C2a_C4BP;
    input Real elmt_C4b_C2a;
    input Real elmt_ka03_2;
    input Real elmt_kg04_1;
    input Real elmt_C1;
    input Real elmt_ka03_1;
    input Real elmt_kf03;
    input Real elmt_kg04_2;
    input Real elmt_kf05;
    input Real elmt_GlcNac_LF;
    input Real elmt_PC_CRP_LF_C1;
    input Real elmt_kd02_1;
    input Real elmt_kd02_2;
    input Real elmt_kd06_1;
    input Real elmt_kd06_2;
    input Real elmt_PC_CRP_C1;
    input Real elmt_ke04_2;
    input Real elmt_kc03_1;
    input Real elmt_GlcNac_LF_CRP_C1;
    input Real elmt_kc03_2;
    input Real elmt_ke04_1;
    input Real elmt_C4;
    input Real elmt_C2;
    input Real elmt_C3;
    input Real elmt_kb01_1;
    input Real elmt_kf06_1;
    input Real elmt_PC_CRP_LF_C1_MASP;
    input Real elmt_kf06_2;
    input Real elmt_kf02_1;
    input Real elmt_kf02_2;
    input Real elmt_C4BP_PC_CRP_LF;
    input Real elmt_kb01_2;

    Real elmt_g_02(unit = "") "g_02";
    Real elmt_product125 "";
    Real elmt_reactant124 "";
    Real elmt_reactant123 "";
    Real elmt_g_01(unit = "") "g_01";
    Real elmt_reactant121 "";
    Real elmt_reactant120 "";
    Real elmt_product122 "";
    Real elmt_d_10(unit = "") "d_10";
    Real elmt_product115 "";
    Real elmt_reactant114 "";
    Real elmt_product116 "";
    Real elmt_e_03(unit = "") "e_03";
    Real elmt_product56 "";
    Real elmt_product55 "";
    Real elmt_reactant54 "";
    Real elmt_e_04(unit = "") "e_04";
    Real elmt_product59 "";
    Real elmt_product58 "";
    Real elmt_reactant57 "";
    Real elmt_d_11(unit = "") "d_11";
    Real elmt_reactant117 "";
    Real elmt_product119 "";
    Real elmt_product118 "";
    Real elmt_c_02(unit = "") "c_02";
    Real elmt_reactant15 "";
    Real elmt_reactant16 "";
    Real elmt_product19 "";
    Real elmt_product18 "";
    Real elmt_product17 "";
    Real elmt_e_01(unit = "") "e_01";
    Real elmt_product50 "";
    Real elmt_reactant48 "";
    Real elmt_reactant49 "";
    Real elmt_g_04(unit = "") "g_04";
    Real elmt_product131 "";
    Real elmt_product130 "";
    Real elmt_reactant129 "";
    Real elmt_c_01(unit = "") "c_01";
    Real elmt_product14 "";
    Real elmt_reactant12 "";
    Real elmt_reactant13 "";
    Real elmt_e_02(unit = "") "e_02";
    Real elmt_reactant51 "";
    Real elmt_reactant52 "";
    Real elmt_product53 "";
    Real elmt_g_03(unit = "") "g_03";
    Real elmt_reactant126 "";
    Real elmt_product128 "";
    Real elmt_product127 "";
    Real elmt_a_01(unit = "") "a_01";
    Real elmt_reactant1 "";
    Real elmt_reactant0 "";
    Real elmt_product2 "";
    Real elmt_c_04(unit = "") "c_04";
    Real elmt_product23 "";
    Real elmt_reactant22 "";
    Real elmt_e_07(unit = "") "e_07";
    Real elmt_reactant105 "";
    Real elmt_product106 "";
    Real elmt_product107 "";
    Real elmt_a_02(unit = "") "a_02";
    Real elmt_reactant4 "";
    Real elmt_reactant3 "";
    Real elmt_product5 "";
    Real elmt_c_03(unit = "") "c_03";
    Real elmt_reactant20 "";
    Real elmt_product21 "";
    Real elmt_a_03(unit = "") "a_03";
    Real elmt_product8 "";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_e_05(unit = "") "e_05";
    Real elmt_product101 "";
    Real elmt_reactant99 "";
    Real elmt_reactant100 "";
    Real elmt_a_04(unit = "") "a_04";
    Real elmt_product11 "";
    Real elmt_product10 "";
    Real elmt_reactant9 "";
    Real elmt_e_06(unit = "") "e_06";
    Real elmt_product104 "";
    Real elmt_product103 "";
    Real elmt_reactant102 "";
    Real elmt_t_01(unit = "") "t_01";
    parameter Real elmt_t_01_elmt_k1_4(unit "") = 3.42266E-4 "";
    Real elmt_reactant84 "";
    Real elmt_t_02(unit = "") "t_02";
    parameter Real elmt_t_02_elmt_k1_4(unit "") = 0.492901 "";
    Real elmt_reactant85 "";
    Real elmt_t_03(unit = "") "t_03";
    parameter Real elmt_t_03_elmt_k1_4(unit "") = 0.0470911 "";
    Real elmt_reactant86 "";
    Real elmt_t_04(unit = "") "t_04";
    parameter Real elmt_t_04_elmt_k1_4(unit "") = 0.0 "";
    parameter Real elmt_t_04_elmt_k2(unit "") = 0.0 "";
    Real elmt_reactant96 "";
    Real elmt_reactant97 "";
    Real elmt_product98 "";
    Real elmt_f_01(unit = "") "f_01";
    Real elmt_reactant61 "";
    Real elmt_product62 "";
    Real elmt_reactant60 "";
    Real elmt_d_01(unit = "") "d_01";
    Real elmt_reactant25 "";
    Real elmt_product26 "";
    Real elmt_reactant24 "";
    Real elmt_f_04(unit = "") "f_04";
    Real elmt_product72 "";
    Real elmt_reactant70 "";
    Real elmt_reactant71 "";
    Real elmt_f_05(unit = "") "f_05";
    Real elmt_reactant73 "";
    Real elmt_reactant74 "";
    Real elmt_product77 "";
    Real elmt_product76 "";
    Real elmt_product75 "";
    Real elmt_d_03(unit = "") "d_03";
    Real elmt_reactant30 "";
    Real elmt_product32 "";
    Real elmt_product31 "";
    Real elmt_f_02(unit = "") "f_02";
    Real elmt_reactant63 "";
    Real elmt_reactant64 "";
    Real elmt_product65 "";
    Real elmt_d_02(unit = "") "d_02";
    Real elmt_reactant27 "";
    Real elmt_reactant28 "";
    Real elmt_product29 "";
    Real elmt_b_01(unit = "") "b_01";
    Real elmt_reactant36 "";
    Real elmt_product38 "";
    Real elmt_reactant37 "";
    Real elmt_f_03(unit = "") "f_03";
    Real elmt_product69 "";
    Real elmt_product68 "";
    Real elmt_reactant66 "";
    Real elmt_reactant67 "";
    Real elmt_b_02(unit = "") "b_02";
    Real elmt_product41 "";
    Real elmt_reactant40 "";
    Real elmt_reactant39 "";
    Real elmt_d_05(unit = "") "d_05";
    Real elmt_product89 "";
    Real elmt_reactant87 "";
    Real elmt_reactant88 "";
    Real elmt_d_04(unit = "") "d_04";
    Real elmt_product34 "";
    Real elmt_product35 "";
    Real elmt_reactant33 "";
    Real elmt_b_03(unit = "") "b_03";
    Real elmt_reactant42 "";
    Real elmt_product44 "";
    Real elmt_product43 "";
    Real elmt_b_04(unit = "") "b_04";
    Real elmt_product47 "";
    Real elmt_product46 "";
    Real elmt_reactant45 "";
    Real elmt_f_06(unit = "") "f_06";
    Real elmt_product80 "";
    Real elmt_reactant78 "";
    Real elmt_reactant79 "";
    Real elmt_d_07(unit = "") "d_07";
    Real elmt_product95 "";
    Real elmt_product94 "";
    Real elmt_reactant93 "";
    Real elmt_f_07(unit = "") "f_07";
    Real elmt_product83 "";
    Real elmt_reactant81 "";
    Real elmt_reactant82 "";
    Real elmt_d_06(unit = "") "d_06";
    Real elmt_reactant90 "";
    Real elmt_product92 "";
    Real elmt_product91 "";
    Real elmt_d_09(unit = "") "d_09";
    Real elmt_product113 "";
    Real elmt_reactant112 "";
    Real elmt_reactant111 "";
    Real elmt_d_08(unit = "") "d_08";
    Real elmt_reactant109 "";
    Real elmt_reactant108 "";
    Real elmt_product110 "";


    initial equation
        elmt_reactant40 = 1.0;
        elmt_product72 = 1.0;
        elmt_reactant42 = 1.0;
        elmt_product77 = 1.0;
        elmt_product76 = 1.0;
        elmt_reactant109 = 1.0;
        elmt_product75 = 1.0;
        elmt_reactant108 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_reactant49 = 1.0;
        elmt_reactant45 = 1.0;
        elmt_reactant117 = 1.0;
        elmt_product69 = 1.0;
        elmt_product68 = 1.0;
        elmt_reactant114 = 1.0;
        elmt_reactant112 = 1.0;
        elmt_reactant111 = 1.0;
        elmt_reactant51 = 1.0;
        elmt_reactant52 = 1.0;
        elmt_product83 = 1.0;
        elmt_product89 = 1.0;
        elmt_reactant54 = 1.0;
        elmt_product80 = 1.0;
        elmt_reactant57 = 1.0;
        elmt_reactant121 = 1.0;
        elmt_reactant120 = 1.0;
        elmt_product101 = 1.0;
        elmt_product104 = 1.0;
        elmt_product103 = 1.0;
        elmt_reactant129 = 1.0;
        elmt_reactant126 = 1.0;
        elmt_product106 = 1.0;
        elmt_reactant124 = 1.0;
        elmt_reactant123 = 1.0;
        elmt_product107 = 1.0;
        elmt_product95 = 1.0;
        elmt_product94 = 1.0;
        elmt_reactant20 = 1.0;
        elmt_product11 = 1.0;
        elmt_product10 = 1.0;
        elmt_product98 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_product92 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_product91 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_product8 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant30 = 1.0;
        elmt_product23 = 1.0;
        elmt_product21 = 1.0;
        elmt_reactant36 = 1.0;
        elmt_reactant37 = 1.0;
        elmt_reactant39 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant33 = 1.0;
        elmt_product2 = 1.0;
        elmt_product14 = 1.0;
        elmt_reactant105 = 1.0;
        elmt_product19 = 1.0;
        elmt_reactant102 = 1.0;
        elmt_product18 = 1.0;
        elmt_product17 = 1.0;
        elmt_reactant100 = 1.0;
        elmt_reactant84 = 1.0;
        elmt_reactant85 = 1.0;
        elmt_reactant86 = 1.0;
        elmt_product34 = 1.0;
        elmt_product32 = 1.0;
        elmt_reactant81 = 1.0;
        elmt_product31 = 1.0;
        elmt_reactant82 = 1.0;
        elmt_reactant87 = 1.0;
        elmt_reactant88 = 1.0;
        elmt_product131 = 1.0;
        elmt_product130 = 1.0;
        elmt_reactant9 = 1.0;
        elmt_product26 = 1.0;
        elmt_product29 = 1.0;
        elmt_product41 = 1.0;
        elmt_reactant96 = 1.0;
        elmt_reactant97 = 1.0;
        elmt_reactant90 = 1.0;
        elmt_product44 = 1.0;
        elmt_product43 = 1.0;
        elmt_reactant93 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant99 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_product38 = 1.0;
        elmt_product35 = 1.0;
        elmt_reactant61 = 1.0;
        elmt_product50 = 1.0;
        elmt_reactant63 = 1.0;
        elmt_reactant64 = 1.0;
        elmt_product56 = 1.0;
        elmt_product55 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant60 = 1.0;
        elmt_reactant66 = 1.0;
        elmt_reactant67 = 1.0;
        elmt_product113 = 1.0;
        elmt_product115 = 1.0;
        elmt_product110 = 1.0;
        elmt_product47 = 1.0;
        elmt_product46 = 1.0;
        elmt_product116 = 1.0;
        elmt_product119 = 1.0;
        elmt_product118 = 1.0;
        elmt_reactant1 = 1.0;
        elmt_product62 = 1.0;
        elmt_reactant73 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_reactant74 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_reactant70 = 1.0;
        elmt_product65 = 1.0;
        elmt_reactant71 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant78 = 1.0;
        elmt_reactant79 = 1.0;
        elmt_product125 = 1.0;
        elmt_product122 = 1.0;
        elmt_product59 = 1.0;
        elmt_product58 = 1.0;
        elmt_product128 = 1.0;
        elmt_product127 = 1.0;


    equation
        elmt_g_02 = (elmt_compartment * ((elmt_kg02_1 * elmt_GlcNac_HF * elmt_MASP) - (elmt_kg02_2 * elmt_GlcNac_HF_MASP)));
        elmt_g_01 = (elmt_compartment * ((elmt_kg01_1 * elmt_X * elmt_HF) - (elmt_kg01_2 * elmt_GlcNac_HF)));
        elmt_d_10 = (elmt_compartment * (((elmt_kd10_1 * elmt_PC_CRP_LF_C1_MASP * elmt_C4) / (elmt_kd10_2 + elmt_C4))));
        elmt_e_03 = (elmt_compartment * (((elmt_ke03_1 * elmt_GlcNac_LF_CRP_C1 * elmt_C4) / (elmt_ke03_2 + elmt_C4))));
        elmt_e_04 = (elmt_compartment * (((elmt_ke04_1 * elmt_GlcNac_LF_CRP_C1 * elmt_C2) / (elmt_ke04_2 + elmt_C2))));
        elmt_d_11 = (elmt_compartment * (((elmt_kd11_1 * elmt_PC_CRP_LF_C1_MASP * elmt_C2) / (elmt_kd11_2 + elmt_C2))));
        elmt_c_02 = (elmt_compartment * elmt_kc02 * elmt_C4b_C2a * elmt_C3);
        elmt_e_01 = (elmt_compartment * ((elmt_ke01_1 * elmt_GlcNac_LF * elmt_CRP) - (elmt_ke01_2 * elmt_GlcNac_LF_CRP)));
        elmt_g_04 = (elmt_compartment * (((elmt_kg04_1 * elmt_GlcNac_HF_MASP * elmt_C2) / (elmt_kg04_2 + elmt_C2))));
        elmt_c_01 = (elmt_compartment * ((elmt_kc01_1 * elmt_C4b * elmt_C2a) - (elmt_kc01_2 * elmt_C4b_C2a)));
        elmt_e_02 = (elmt_compartment * ((elmt_ke02_1 * elmt_GlcNac_LF_CRP * elmt_C1) - (elmt_ke02_2 * elmt_GlcNac_LF_CRP_C1)));
        elmt_g_03 = (elmt_compartment * (((elmt_kg03_1 * elmt_GlcNac_HF_MASP * elmt_C4) / (elmt_kg03_2 + elmt_C4))));
        elmt_a_01 = (elmt_compartment * ((elmt_ka01_1 * elmt_PC * elmt_CRP) - (elmt_ka01_2 * elmt_PC_CRP)));
        elmt_c_04 = (elmt_compartment * ((elmt_kc04_1 * elmt_C4b_C2a) - (elmt_kc04_2 * elmt_dC4b_C2a)));
        elmt_e_07 = (elmt_compartment * (((elmt_ke07_1 * elmt_GlcNac_LF_CRP_MASP * elmt_C2) / (elmt_ke07_2 + elmt_C2))));
        elmt_a_02 = (elmt_compartment * ((elmt_ka02_1 * elmt_PC_CRP * elmt_C1) - (elmt_ka02_2 * elmt_PC_CRP_C1)));
        elmt_c_03 = (elmt_compartment * ((elmt_kc03_1 * elmt_C3b) - (elmt_kc03_2 * elmt_dC3b)));
        elmt_a_03 = (elmt_compartment * (((elmt_ka03_1 * elmt_PC_CRP_C1 * elmt_C4) / (elmt_ka03_2 + elmt_C4))));
        elmt_e_05 = (elmt_compartment * ((elmt_ke05_1 * elmt_GlcNac_LF_CRP * elmt_MASP) - (elmt_ke05_2 * elmt_GlcNac_LF_CRP_MASP)));
        elmt_a_04 = (elmt_compartment * (((elmt_ka04_1 * elmt_PC_CRP_C1 * elmt_C2) / (elmt_ka04_2 + elmt_C2))));
        elmt_e_06 = (elmt_compartment * (((elmt_ke06_1 * elmt_GlcNac_LF_CRP_MASP * elmt_C4) / (elmt_ke06_2 + elmt_C4))));
        elmt_t_01 = (elmt_compartment * elmt_t_01_elmt_k1_4 * elmt_C4BP);
        elmt_t_02 = (elmt_compartment * elmt_t_02_elmt_k1_4 * elmt_C3b);
        elmt_t_03 = (elmt_compartment * elmt_t_03_elmt_k1_4 * elmt_C4b_C2a);
        elmt_t_04 = (elmt_compartment * ((elmt_t_04_elmt_k1_4 * elmt_C4BP * elmt_PC_CRP_LF) - (elmt_t_04_elmt_k2 * elmt_C4BP_PC_CRP_LF)));
        elmt_f_01 = (elmt_compartment * ((elmt_kf01_1 * elmt_C4BP * elmt_PC_CRP) - (elmt_kf01_2 * elmt_C4BP_PC_CRP)));
        elmt_d_01 = (elmt_compartment * ((elmt_kd01_1 * elmt_PC_CRP * elmt_LF) - (elmt_kd01_2 * elmt_PC_CRP_LF)));
        elmt_f_04 = (elmt_compartment * ((elmt_kf04_1 * elmt_C4BP * elmt_C4b) - (elmt_kf04_2 * elmt_C4BP_C4b)));
        elmt_f_05 = (elmt_compartment * elmt_kf05 * elmt_C4b_C2a * elmt_C4BP);
        elmt_d_03 = (elmt_compartment * (((elmt_kd03_1 * elmt_PC_CRP_LF_MASP * elmt_C4) / (elmt_kd03_2 + elmt_C4))));
        elmt_f_02 = (elmt_compartment * ((elmt_kf02_1 * elmt_C4BP * elmt_GlcNac_LF_CRP) - (elmt_kf02_2 * elmt_C4BP_GlcNac_LF_CRP)));
        elmt_d_02 = (elmt_compartment * ((elmt_kd02_1 * elmt_PC_CRP_LF * elmt_MASP) - (elmt_kd02_2 * elmt_PC_CRP_LF_MASP)));
        elmt_b_01 = (elmt_compartment * ((elmt_kb01_1 * elmt_GlcNac * elmt_LF) - (elmt_kb01_2 * elmt_GlcNac_LF)));
        elmt_f_03 = (elmt_compartment * elmt_kf03 * elmt_C4b_C2a * elmt_C4BP);
        elmt_b_02 = (elmt_compartment * ((elmt_kb02_1 * elmt_GlcNac_LF * elmt_MASP) - (elmt_kb02_2 * elmt_GlcNac_LF_MASP)));
        elmt_d_05 = (elmt_compartment * ((elmt_kd05_1 * elmt_PC_CRP_LF * elmt_C1) - (elmt_kd05_2 * elmt_PC_CRP_LF_C1)));
        elmt_d_04 = (elmt_compartment * (((elmt_kd04_1 * elmt_PC_CRP_LF_MASP * elmt_C2) / (elmt_kd04_2 + elmt_C2))));
        elmt_b_03 = (elmt_compartment * (((elmt_kb03_1 * elmt_GlcNac_LF_MASP * elmt_C4) / (elmt_kb03_2 + elmt_C4))));
        elmt_b_04 = (elmt_compartment * (((elmt_kb04_1 * elmt_GlcNac_LF_MASP * elmt_C2) / (elmt_kb04_2 + elmt_C2))));
        elmt_f_06 = (elmt_compartment * ((elmt_kf06_1 * elmt_C4b_C2a * elmt_C4BP) - (elmt_kf06_2 * elmt_C4b_C2a_C4BP)));
        elmt_d_07 = (elmt_compartment * (((elmt_kd07_1 * elmt_PC_CRP_LF_C1 * elmt_C2) / (elmt_kd07_2 + elmt_C2))));
        elmt_f_07 = (elmt_compartment * ((elmt_kf07_1 * elmt_dC4b_C2a * elmt_C4BP) - (elmt_kf07_2 * elmt_dC4b_C2a_C4BP)));
        elmt_d_06 = (elmt_compartment * (((elmt_kd06_1 * elmt_PC_CRP_LF_C1 * elmt_C4) / (elmt_kd06_2 + elmt_C4))));
        elmt_d_09 = (elmt_compartment * ((elmt_kd09_1 * elmt_PC_CRP_LF_MASP * elmt_C1) - (elmt_kd09_2 * elmt_PC_CRP_LF_C1_MASP)));
        elmt_d_08 = (elmt_compartment * ((elmt_kd08_1 * elmt_PC_CRP_LF_C1 * elmt_MASP) - (elmt_kd08_2 * elmt_PC_CRP_LF_C1_MASP)));
        der(elmt_reactant40) = 0;
        der(elmt_product72) = 0;
        der(elmt_reactant42) = 0;
        der(elmt_product77) = 0;
        der(elmt_product76) = 0;
        der(elmt_reactant109) = 0;
        der(elmt_product75) = 0;
        der(elmt_reactant108) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_reactant49) = 0;
        der(elmt_reactant45) = 0;
        der(elmt_reactant117) = 0;
        der(elmt_product69) = 0;
        der(elmt_product68) = 0;
        der(elmt_reactant114) = 0;
        der(elmt_reactant112) = 0;
        der(elmt_reactant111) = 0;
        der(elmt_reactant51) = 0;
        der(elmt_reactant52) = 0;
        der(elmt_product83) = 0;
        der(elmt_product89) = 0;
        der(elmt_reactant54) = 0;
        der(elmt_product80) = 0;
        der(elmt_reactant57) = 0;
        der(elmt_reactant121) = 0;
        der(elmt_reactant120) = 0;
        der(elmt_product101) = 0;
        der(elmt_product104) = 0;
        der(elmt_product103) = 0;
        der(elmt_reactant129) = 0;
        der(elmt_reactant126) = 0;
        der(elmt_product106) = 0;
        der(elmt_reactant124) = 0;
        der(elmt_reactant123) = 0;
        der(elmt_product107) = 0;
        der(elmt_product95) = 0;
        der(elmt_product94) = 0;
        der(elmt_reactant20) = 0;
        der(elmt_product11) = 0;
        der(elmt_product10) = 0;
        der(elmt_product98) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_product92) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_product91) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_product8) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant30) = 0;
        der(elmt_product23) = 0;
        der(elmt_product21) = 0;
        der(elmt_reactant36) = 0;
        der(elmt_reactant37) = 0;
        der(elmt_reactant39) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant33) = 0;
        der(elmt_product2) = 0;
        der(elmt_product14) = 0;
        der(elmt_reactant105) = 0;
        der(elmt_product19) = 0;
        der(elmt_reactant102) = 0;
        der(elmt_product18) = 0;
        der(elmt_product17) = 0;
        der(elmt_reactant100) = 0;
        der(elmt_reactant84) = 0;
        der(elmt_reactant85) = 0;
        der(elmt_reactant86) = 0;
        der(elmt_product34) = 0;
        der(elmt_product32) = 0;
        der(elmt_reactant81) = 0;
        der(elmt_product31) = 0;
        der(elmt_reactant82) = 0;
        der(elmt_reactant87) = 0;
        der(elmt_reactant88) = 0;
        der(elmt_product131) = 0;
        der(elmt_product130) = 0;
        der(elmt_reactant9) = 0;
        der(elmt_product26) = 0;
        der(elmt_product29) = 0;
        der(elmt_product41) = 0;
        der(elmt_reactant96) = 0;
        der(elmt_reactant97) = 0;
        der(elmt_reactant90) = 0;
        der(elmt_product44) = 0;
        der(elmt_product43) = 0;
        der(elmt_reactant93) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant99) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_product38) = 0;
        der(elmt_product35) = 0;
        der(elmt_reactant61) = 0;
        der(elmt_product50) = 0;
        der(elmt_reactant63) = 0;
        der(elmt_reactant64) = 0;
        der(elmt_product56) = 0;
        der(elmt_product55) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant60) = 0;
        der(elmt_reactant66) = 0;
        der(elmt_reactant67) = 0;
        der(elmt_product113) = 0;
        der(elmt_product115) = 0;
        der(elmt_product110) = 0;
        der(elmt_product47) = 0;
        der(elmt_product46) = 0;
        der(elmt_product116) = 0;
        der(elmt_product119) = 0;
        der(elmt_product118) = 0;
        der(elmt_reactant1) = 0;
        der(elmt_product62) = 0;
        der(elmt_reactant73) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_reactant74) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_reactant70) = 0;
        der(elmt_product65) = 0;
        der(elmt_reactant71) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant78) = 0;
        der(elmt_reactant79) = 0;
        der(elmt_product125) = 0;
        der(elmt_product122) = 0;
        der(elmt_product59) = 0;
        der(elmt_product58) = 0;
        der(elmt_product128) = 0;
        der(elmt_product127) = 0;

end Reactions;
