within BIOMD505;
class Reactions

    input Real elmt_Vmckat;
    input Real elmt_C8KetoacylCoAMAT;
    input Real elmt_Keqcrot;
    input Real elmt_KmmckatC8KetoacylCoAMAT;
    input Real elmt_Keqvlcad;
    input Real elmt_KmmcadC8AcylCoAMAT;
    input Real elmt_KmmcadFADH;
    input Real elmt_KmscadFADH;
    input Real elmt_C14AcylCarMAT;
    input Real elmt_KmmtpC12AcylCoAMAT;
    input Real elmt_KmscadC6AcylCoAMAT;
    input Real elmt_KmmschadC8KetoacylCoAMAT;
    input Real elmt_KmcrotC6EnoylCoAMAT;
    input Real elmt_KmmckatAcetylCoAMAT;
    input Real elmt_Kmcpt2C8AcylCoAMAT;
    input Real elmt_Vlcad;
    input Real elmt_C8EnoylCoAMAT;
    input Real elmt_C12HydroxyacylCoAMAT;
    input Real elmt_KmlcadC10AcylCoAMAT;
    input Real elmt_KmmckatC16KetoacylCoAMAT;
    input Real elmt_KmscadC4EnoylCoAMAT;
    input Real elmt_FADtMAT;
    input Real elmt_KmmschadC10KetoacylCoAMAT;
    input Real elmt_C14AcylCoAMAT;
    input Real elmt_Keqmckat;
    input Real elmt_Kmcpt2CoAMAT;
    input Real elmt_C12AcylCarMAT;
    input Real elmt_KmmcadC4EnoylCoAMAT;
    input Real elmt_Kmcpt2C4AcylCarMAT;
    input Real elmt_KmmschadC4AcetoacylCoAMAT;
    input Real elmt_KmmschadC16KetoacylCoAMAT;
    input Real elmt_KmscadC4AcylCoAMAT;
    input Real elmt_KmmckatC12KetoacylCoAMAT;
    input Real elmt_KmmtpC10AcylCoAMAT;
    input Real elmt_KmmckatC10AcylCoAMAT;
    input Real elmt_C12EnoylCoAMAT;
    input Real elmt_Kmcpt2C6AcylCoAMAT;
    input Real elmt_C4AcylCoAMAT;
    input Real elmt_C16AcylCoAMAT;
    input Real elmt_KmmckatCoAMAT;
    input Real elmt_KmvlcadC16AcylCoAMAT;
    input Real elmt_KmmtpAcetylCoAMAT;
    input Real elmt_C16HydroxyacylCoAMAT;
    input Real elmt_CarMAT;
    input Real elmt_KmmcadC10EnoylCoAMAT;
    input Real elmt_C10AcylCarCYT;
    input Real elmt_C10EnoylCoAMAT;
    input Real elmt_CoACYT;
    input Real elmt_KmlcadC12AcylCoAMAT;
    input Real elmt_KmmcadC4AcylCoAMAT;
    input Real elmt_Vmcad;
    input Real elmt_KmmschadC14HydroxyacylCoAMAT;
    input Real elmt_CarCYT;
    input Real elmt_C12AcylCoAMAT;
    input Real elmt_C8AcylCarCYT;
    input Real elmt_KmcrotC4HydroxyacylCoAMAT;
    input Real elmt_KmmckatC10KetoacylCoAMAT;
    input Real elmt_Kmcpt2C10AcylCarMAT;
    input Real elmt_C16EnoylCoAMAT;
    input Real elmt_Keqmcad;
    input Real elmt_Kmcpt2C10AcylCoAMAT;
    input Real elmt_KmcrotC10HydroxyacylCoAMAT;
    input Real elmt_Kmcpt2C4AcylCoAMAT;
    input Real elmt_C8HydroxyacylCoAMAT;
    input Real elmt_KmlcadC14AcylCoAMAT;
    input Real elmt_KmcactCarCYT;
    input Real elmt_KmmschadC12HydroxyacylCoAMAT;
    input Real elmt_Vfcact;
    input Real elmt_C6HydroxyacylCoAMAT;
    input Real elmt_KmcrotC6HydroxyacylCoAMAT;
    input Real elmt_C16KetoacylCoAMAT;
    input Real elmt_C12AcylCarCYT;
    input Real elmt_Vscad;
    input Real elmt_C16AcylCoACYT;
    input Real elmt_C12KetoacylCoAMAT;
    input Real elmt_KmmckatC4AcylCoAMAT;
    input Real elmt_Vvlcad;
    input Real elmt_Keqscad;
    input Real elmt_KmmschadC4HydroxyacylCoAMAT;
    input Real elmt_C4AcylCarMAT;
    input Real elmt_KmmcadC10AcylCoAMAT;
    input Real elmt_CoAMAT;
    input Real elmt_KmvlcadC14AcylCoAMAT;
    input Real elmt_KmlcadC8EnoylCoAMAT;
    input Real elmt_NADHMAT;
    input Real elmt_KicrotC4AcetoacylCoA;
    input Real elmt_Vcrot;
    input Real elmt_KmmckatC12AcylCoAMAT;
    input Real elmt_Kmcpt2C6AcylCarMAT;
    input Real elmt_KmmtpCoAMAT;
    input Real elmt_C14KetoacylCoAMAT;
    input Real elmt_KmmckatC4AcetoacylCoAMAT;
    input Real elmt_Kmcpt2CarMAT;
    input Real elmt_C8AcylCoAMAT;
    input Real elmt_Kmcpt2C16AcylCarMAT;
    input Real elmt_KmmckatC14KetoacylCoAMAT;
    input Real elmt_KmcrotC10EnoylCoAMAT;
    input Real elmt_KicactCarCYT;
    input Real elmt_KmvlcadC12AcylCoAMAT;
    input Real elmt_KmlcadFADH;
    input Real elmt_KmmcadC12AcylCoAMAT;
    input Real elmt_C10KetoacylCoAMAT;
    input Real elmt_KmcrotC16HydroxyacylCoAMAT;
    input Real elmt_C14HydroxyacylCoAMAT;
    input Real elmt_KmcactCarMAT;
    input Real elmt_C16AcylCarCYT;
    input Real elmt_KmmtpC6AcylCoAMAT;
    input Real elmt_KmmckatC6AcylCoAMAT;
    input Real elmt_KmlcadC14EnoylCoAMAT;
    input Real elmt_C14EnoylCoAMAT;
    input Real elmt_Kmcpt2C14AcylCarMAT;
    input Real elmt_Keqmschad;
    input Real elmt_Kmcpt2C14AcylCoAMAT;
    input Real elmt_KmvlcadC14EnoylCoAMAT;
    input Real elmt_C6KetoacylCoAMAT;
    input Real elmt_KmmckatC14AcylCoAMAT;
    input Real elmt_C4AcylCarCYT;
    input Real elmt_KmvlcadFAD;
    input Real elmt_KmmckatC6KetoacylCoAMAT;
    input Real elmt_Keqlcad;
    input Real elmt_C4AcetoacylCoAMAT;
    input Real elmt_C6AcylCarCYT;
    input Real elmt_KmcrotC12HydroxyacylCoAMAT;
    input Real elmt_C10AcylCoAMAT;
    input Real elmt_Kmcpt2C16AcylCoAMAT;
    input Real elmt_KmmckatC8AcylCoAMAT;
    input Real elmt_KmmcadC12EnoylCoAMAT;
    input Real elmt_KmlcadFAD;
    input Real elmt_KmscadC6EnoylCoAMAT;
    input Real elmt_Vmschad;
    input Real elmt_NADtMAT;
    input Real elmt_KmmckatC16AcylCoAMAT;
    input Real elmt_KmmtpC8AcylCoAMAT;
    input Real elmt_KmmtpC16AcylCoAMAT;
    input Real elmt_Kmcpt2C12AcylCarMAT;
    input Real elmt_KmmcadC6EnoylCoAMAT;
    input Real elmt_KmmcadFAD;
    input Real elmt_C10HydroxyacylCoAMAT;
    input Real elmt_C8AcylCarMAT;
    input Real elmt_Keqmtp;
    input Real elmt_KmmschadNADMAT;
    input Real elmt_KmscadFAD;
    input Real elmt_AcetylCoAMAT;
    input Real elmt_KmmschadC14KetoacylCoAMAT;
    input Real elmt_KmmcadC8EnoylCoAMAT;
    input Real elmt_KmvlcadFADH;
    input Real elmt_KmvlcadC16EnoylCoAMAT;
    input Real elmt_KmcrotC4EnoylCoAMAT;
    input Real elmt_KmmschadNADHMAT;
    input Real elmt_C10AcylCarMAT;
    input Real elmt_KmmschadC8HydroxyacylCoAMAT;
    input Real elmt_FADHMAT;
    input Real elmt_C6AcylCarMAT;
    input Real elmt_KmmtpC8EnoylCoAMAT;
    input Real elmt_KmmschadC10HydroxyacylCoAMAT;
    input Real elmt_C6EnoylCoAMAT;
    input Real elmt_KmmtpC10EnoylCoAMAT;
    input Real elmt_KmmtpC16EnoylCoAMAT;
    input Real elmt_C6AcylCoAMAT;
    input Real elmt_KmmschadC6HydroxyacylCoAMAT;
    input Real elmt_KmmtpC14AcylCoAMAT;
    input Real elmt_KmcrotC12EnoylCoAMAT;
    input Real elmt_Kmcpt2C8AcylCarMAT;
    input Real elmt_KmlcadC16EnoylCoAMAT;
    input Real elmt_Vcpt2;
    input Real elmt_KmcrotC8EnoylCoAMAT;
    input Real elmt_KmlcadC10EnoylCoAMAT;
    input Real elmt_KmcrotC8HydroxyacylCoAMAT;
    input Real elmt_C4EnoylCoAMAT;
    input Real elmt_Keqcact;
    input Real elmt_KmmtpC12EnoylCoAMAT;
    input Real elmt_KmmschadC6KetoacylCoAMAT;
    input Real elmt_KmvlcadC12EnoylCoAMAT;
    input Real elmt_C4HydroxyacylCoAMAT;
    input Real elmt_KmcrotC14EnoylCoAMAT;
    input Real elmt_KmlcadC8AcylCoAMAT;
    input Real elmt_KmlcadC12EnoylCoAMAT;
    input Real elmt_KmlcadC16AcylCoAMAT;
    input Real elmt_KmcrotC14HydroxyacylCoAMAT;
    input Real elmt_KmmtpC14EnoylCoAMAT;
    input Real elmt_Keqcpt2;
    input Real elmt_KmmschadC16HydroxyacylCoAMAT;
    input Real elmt_C14AcylCarCYT;
    input Real elmt_KmmtpNADHMAT;
    input Real elmt_KmcrotC16EnoylCoAMAT;
    input Real elmt_MalCoACYT;
    input Real elmt_KmmtpNADMAT;
    input Real elmt_Kmcpt2C12AcylCoAMAT;
    input Real elmt_KmmschadC12KetoacylCoAMAT;
    input Real elmt_C16AcylCarMAT;
    input Real elmt_Vrcact;
    input Real elmt_KmmcadC6AcylCoAMAT;
    input Real elmt_Vmtp;

    Real elmt_vlcadC8(unit = "") "";
    parameter Real elmt_vlcadC8_elmt_sflcadC8(unit "") = 0.4 "";
    Real elmt_reactant50 "";
    Real elmt_product52 "";
    Real elmt_product51 "";
    Real elmt_vmtpC10(unit = "") "";
    parameter Real elmt_vmtpC10_elmt_sfmtpC10(unit "") = 0.73 "";
    Real elmt_reactant141 "";
    Real elmt_product142 "";
    Real elmt_product144 "";
    Real elmt_product143 "";
    Real elmt_vcpt2C8(unit = "") "";
    parameter Real elmt_vcpt2C8_elmt_sfcpt2C8(unit "") = 0.35 "";
    Real elmt_product24 "";
    Real elmt_reactant23 "";
    Real elmt_vcpt2C6(unit = "") "";
    parameter Real elmt_vcpt2C6_elmt_sfcpt2C6(unit "") = 0.15 "";
    Real elmt_reactant25 "";
    Real elmt_product26 "";
    Real elmt_vcpt2C4(unit = "") "";
    parameter Real elmt_vcpt2C4_elmt_sfcpt2C4(unit "") = 0.01 "";
    Real elmt_reactant27 "";
    Real elmt_product28 "";
    Real elmt_vacesink(unit = "") "";
    parameter Real elmt_vacesink_elmt_K1acesink(unit "m-3.0.") = 70.0 "";
    parameter Real elmt_vacesink_elmt_Ksacesink(unit "m3.0.s-1.0") = 6000000.0 "";
    Real elmt_reactant149 "";
    Real elmt_vcpt2C16(unit = "") "";
    parameter Real elmt_vcpt2C16_elmt_sfcpt2C16(unit "") = 0.85 "";
    Real elmt_product16 "";
    Real elmt_reactant15 "";
    Real elmt_vmcadC4(unit = "") "";
    parameter Real elmt_vmcadC4_elmt_sfmcadC4(unit "") = 0.12 "";
    Real elmt_product67 "";
    Real elmt_product66 "";
    Real elmt_reactant65 "";
    Real elmt_vcpt2C12(unit = "") "";
    parameter Real elmt_vcpt2C12_elmt_sfcpt2C12(unit "") = 0.95 "";
    Real elmt_reactant19 "";
    Real elmt_product20 "";
    Real elmt_vcpt2C14(unit = "") "";
    parameter Real elmt_vcpt2C14_elmt_sfcpt2C14(unit "") = 1.0 "";
    Real elmt_reactant17 "";
    Real elmt_product18 "";
    Real elmt_vscadC6(unit = "") "";
    parameter Real elmt_vscadC6_elmt_sfscadC6(unit "") = 0.3 "";
    Real elmt_product69 "";
    Real elmt_product70 "";
    Real elmt_reactant68 "";
    Real elmt_vcpt2C10(unit = "") "";
    parameter Real elmt_vcpt2C10_elmt_sfcpt2C10(unit "") = 0.95 "";
    Real elmt_product22 "";
    Real elmt_reactant21 "";
    Real elmt_vscadC4(unit = "") "";
    parameter Real elmt_vscadC4_elmt_sfscadC4(unit "") = 1.0 "";
    Real elmt_product73 "";
    Real elmt_product72 "";
    Real elmt_reactant71 "";
    Real elmt_vcrotC14(unit = "") "";
    parameter Real elmt_vcrotC14_elmt_sfcrotC14(unit "") = 0.2 "";
    Real elmt_product77 "";
    Real elmt_reactant76 "";
    Real elmt_vcrotC16(unit = "") "";
    parameter Real elmt_vcrotC16_elmt_sfcrotC16(unit "") = 0.13 "";
    Real elmt_reactant74 "";
    Real elmt_product75 "";
    Real elmt_vmschadC8(unit = "") "";
    parameter Real elmt_vmschadC8_elmt_sfmschadC8(unit "") = 0.89 "";
    Real elmt_product102 "";
    Real elmt_product101 "";
    Real elmt_reactant100 "";
    Real elmt_vcrotC10(unit = "") "";
    parameter Real elmt_vcrotC10_elmt_sfcrotC10(unit "") = 0.33 "";
    Real elmt_reactant80 "";
    Real elmt_product81 "";
    Real elmt_vmckatC6(unit = "") "";
    parameter Real elmt_vmckatC6_elmt_sfmckatC6(unit "") = 1.0 "";
    Real elmt_product126 "";
    Real elmt_product125 "";
    Real elmt_reactant124 "";
    Real elmt_vcrotC12(unit = "") "";
    parameter Real elmt_vcrotC12_elmt_sfcrotC12(unit "") = 0.25 "";
    Real elmt_product79 "";
    Real elmt_reactant78 "";
    Real elmt_vmckatC4(unit = "") "";
    parameter Real elmt_vmckatC4_elmt_sfmckatC4(unit "") = 0.49 "";
    Real elmt_reactant127 "";
    Real elmt_product128 "";
    Real elmt_vmcadC6(unit = "") "";
    parameter Real elmt_vmcadC6_elmt_sfmcadC6(unit "") = 1.0 "";
    Real elmt_product63 "";
    Real elmt_reactant62 "";
    Real elmt_product64 "";
    Real elmt_vmtpC16(unit = "") "";
    parameter Real elmt_vmtpC16_elmt_sfmtpC16(unit "") = 1.0 "";
    Real elmt_product131 "";
    Real elmt_product130 "";
    Real elmt_product132 "";
    Real elmt_reactant129 "";
    Real elmt_vmcadC8(unit = "") "";
    parameter Real elmt_vmcadC8_elmt_sfmcadC8(unit "") = 0.87 "";
    Real elmt_product61 "";
    Real elmt_product60 "";
    Real elmt_reactant59 "";
    Real elmt_vmckatC8(unit = "") "";
    parameter Real elmt_vmckatC8_elmt_sfmckatC8(unit "") = 0.81 "";
    Real elmt_reactant121 "";
    Real elmt_product123 "";
    Real elmt_product122 "";
    Real elmt_vmtpC14(unit = "") "";
    parameter Real elmt_vmtpC14_elmt_sfmtpC14(unit "") = 0.9 "";
    Real elmt_product135 "";
    Real elmt_product134 "";
    Real elmt_product136 "";
    Real elmt_reactant133 "";
    Real elmt_vmschadC6(unit = "") "";
    parameter Real elmt_vmschadC6_elmt_sfmschadC6(unit "") = 1.0 "";
    Real elmt_product104 "";
    Real elmt_reactant103 "";
    Real elmt_product105 "";
    Real elmt_vmtpC8(unit = "") "";
    parameter Real elmt_vmtpC8_elmt_sfmtpC8(unit "") = 0.34 "";
    Real elmt_product146 "";
    Real elmt_product148 "";
    Real elmt_product147 "";
    Real elmt_reactant145 "";
    Real elmt_vmtpC12(unit = "") "";
    parameter Real elmt_vmtpC12_elmt_sfmtpC12(unit "") = 0.81 "";
    Real elmt_product140 "";
    Real elmt_reactant137 "";
    Real elmt_product139 "";
    Real elmt_product138 "";
    Real elmt_vmschadC4(unit = "") "";
    parameter Real elmt_vmschadC4_elmt_sfmschadC4(unit "") = 0.67 "";
    Real elmt_reactant106 "";
    Real elmt_product108 "";
    Real elmt_product107 "";
    Real elmt_vmckatC16(unit = "") "";
    parameter Real elmt_vmckatC16_elmt_sfmckatC16(unit "") = 0.0 "";
    Real elmt_reactant109 "";
    Real elmt_product111 "";
    Real elmt_product110 "";
    Real elmt_vcpt1C16(unit = "") "";
    parameter Real elmt_vcpt1C16_elmt_Kmcpt1CarCYT(unit "m-3.0.") = 250.0 "";
    parameter Real elmt_vcpt1C16_elmt_Kmcpt1CoACYT(unit "m-3.0.") = 40.7 "";
    parameter Real elmt_vcpt1C16_elmt_ncpt1(unit "") = 2.4799 "";
    parameter Real elmt_vcpt1C16_elmt_Kicpt1MalCoACYT(unit "m-3.0.") = 9.1 "";
    parameter Real elmt_vcpt1C16_elmt_Keqcpt1(unit "") = 0.45 "";
    parameter Real elmt_vcpt1C16_elmt_Kmcpt1C16AcylCarCYT(unit "m-3.0.") = 136.0 "";
    parameter Real elmt_vcpt1C16_elmt_Vcpt1(unit "m-3.0..s-1.0") = 0.012 "";
    parameter Real elmt_vcpt1C16_elmt_sfcpt1C16(unit "") = 1.0 "";
    parameter Real elmt_vcpt1C16_elmt_Kmcpt1C16AcylCoACYT(unit "m-3.0.") = 13.8 "";
    Real elmt_product0 "";
    Real elmt_vmckatC12(unit = "") "";
    parameter Real elmt_vmckatC12_elmt_sfmckatC12(unit "") = 0.38 "";
    Real elmt_reactant115 "";
    Real elmt_product117 "";
    Real elmt_product116 "";
    Real elmt_vmckatC14(unit = "") "";
    parameter Real elmt_vmckatC14_elmt_sfmckatC14(unit "") = 0.2 "";
    Real elmt_product113 "";
    Real elmt_product114 "";
    Real elmt_reactant112 "";
    Real elmt_vmcadC12(unit = "") "";
    parameter Real elmt_vmcadC12_elmt_sfmcadC12(unit "") = 0.38 "";
    Real elmt_reactant53 "";
    Real elmt_product55 "";
    Real elmt_product54 "";
    Real elmt_vmcadC10(unit = "") "";
    parameter Real elmt_vmcadC10_elmt_sfmcadC10(unit "") = 0.8 "";
    Real elmt_product58 "";
    Real elmt_product57 "";
    Real elmt_reactant56 "";
    Real elmt_vcactC8(unit = "") "";
    parameter Real elmt_vcactC8_elmt_KicactC8AcylCarCYT(unit "m-3.0.") = 56.0 "";
    parameter Real elmt_vcactC8_elmt_KmcactC8AcylCarMAT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC8_elmt_KmcactC8AcylCarCYT(unit "m-3.0.") = 15.0 "";
    Real elmt_product10 "";
    Real elmt_reactant9 "";
    Real elmt_vcactC4(unit = "") "";
    parameter Real elmt_vcactC4_elmt_KmcactC4AcylCarCYT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC4_elmt_KicactC4AcylCarCYT(unit "m-3.0.") = 56.0 "";
    parameter Real elmt_vcactC4_elmt_KmcactC4AcylCarMAT(unit "m-3.0.") = 15.0 "";
    Real elmt_product14 "";
    Real elmt_reactant13 "";
    Real elmt_vcrotC4(unit = "") "";
    parameter Real elmt_vcrotC4_elmt_sfcrotC4(unit "") = 1.0 "";
    Real elmt_reactant86 "";
    Real elmt_product87 "";
    Real elmt_vcactC6(unit = "") "";
    parameter Real elmt_vcactC6_elmt_KmcactC6AcylCarCYT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC6_elmt_KmcactC6AcylCarMAT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC6_elmt_KicactC6AcylCarCYT(unit "m-3.0.") = 56.0 "";
    Real elmt_product12 "";
    Real elmt_reactant11 "";
    Real elmt_vcrotC8(unit = "") "";
    parameter Real elmt_vcrotC8_elmt_sfcrotC8(unit "") = 0.58 "";
    Real elmt_product83 "";
    Real elmt_reactant82 "";
    Real elmt_vcrotC6(unit = "") "";
    parameter Real elmt_vcrotC6_elmt_sfcrotC6(unit "") = 0.83 "";
    Real elmt_product85 "";
    Real elmt_reactant84 "";
    Real elmt_vcactC14(unit = "") "";
    parameter Real elmt_vcactC14_elmt_KicactC14AcylCarCYT(unit "m-3.0.") = 56.0 "";
    parameter Real elmt_vcactC14_elmt_KmcactC14AcylCarCYT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC14_elmt_KmcactC14AcylCarMAT(unit "m-3.0.") = 15.0 "";
    Real elmt_reactant3 "";
    Real elmt_product4 "";
    Real elmt_vmschadC14(unit = "") "";
    parameter Real elmt_vmschadC14_elmt_sfmschadC14(unit "") = 0.5 "";
    Real elmt_product93 "";
    Real elmt_reactant91 "";
    Real elmt_product92 "";
    Real elmt_vvlcadC12(unit = "") "";
    parameter Real elmt_vvlcadC12_elmt_sfvlcadC12(unit "") = 0.11 "";
    Real elmt_product37 "";
    Real elmt_product36 "";
    Real elmt_reactant35 "";
    Real elmt_vcactC12(unit = "") "";
    parameter Real elmt_vcactC12_elmt_KmcactC12AcylCarMAT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC12_elmt_KmcactC12AcylCarCYT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC12_elmt_KicactC12AcylCarCYT(unit "m-3.0.") = 56.0 "";
    Real elmt_product6 "";
    Real elmt_reactant5 "";
    Real elmt_vmschadC12(unit = "") "";
    parameter Real elmt_vmschadC12_elmt_sfmschadC12(unit "") = 0.43 "";
    Real elmt_reactant94 "";
    Real elmt_product96 "";
    Real elmt_product95 "";
    Real elmt_vvlcadC14(unit = "") "";
    parameter Real elmt_vvlcadC14_elmt_sfvlcadC14(unit "") = 0.42 "";
    Real elmt_product34 "";
    Real elmt_product33 "";
    Real elmt_reactant32 "";
    Real elmt_vvlcadC16(unit = "") "";
    parameter Real elmt_vvlcadC16_elmt_sfvlcadC16(unit "") = 1.0 "";
    Real elmt_product30 "";
    Real elmt_reactant29 "";
    Real elmt_product31 "";
    Real elmt_vcactC16(unit = "") "";
    parameter Real elmt_vcactC16_elmt_KmcactC16AcylCarCYT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC16_elmt_KmcactC16AcylCarMAT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC16_elmt_KicactC16AcylCarCYT(unit "m-3.0.") = 56.0 "";
    Real elmt_reactant1 "";
    Real elmt_product2 "";
    Real elmt_vmschadC16(unit = "") "";
    parameter Real elmt_vmschadC16_elmt_sfmschadC16(unit "") = 0.6 "";
    Real elmt_product89 "";
    Real elmt_reactant88 "";
    Real elmt_product90 "";
    Real elmt_vnadhsink(unit = "") "";
    parameter Real elmt_vnadhsink_elmt_K1nadhsink(unit "m-3.0.") = 16.0 "";
    parameter Real elmt_vnadhsink_elmt_Ksnadhsink(unit "m3.0.s-1.0") = 6000000.0 "";
    Real elmt_reactant151 "";
    Real elmt_vlcadC10(unit = "") "";
    parameter Real elmt_vlcadC10_elmt_sflcadC10(unit "") = 0.75 "";
    Real elmt_reactant47 "";
    Real elmt_product49 "";
    Real elmt_product48 "";
    Real elmt_vlcadC12(unit = "") "";
    parameter Real elmt_vlcadC12_elmt_sflcadC12(unit "") = 0.9 "";
    Real elmt_product45 "";
    Real elmt_product46 "";
    Real elmt_reactant44 "";
    Real elmt_vlcadC14(unit = "") "";
    parameter Real elmt_vlcadC14_elmt_sflcadC14(unit "") = 1.0 "";
    Real elmt_reactant41 "";
    Real elmt_product43 "";
    Real elmt_product42 "";
    Real elmt_vfadhsink(unit = "") "";
    parameter Real elmt_vfadhsink_elmt_K1fadhsink(unit "m-3.0.") = 0.46 "";
    parameter Real elmt_vfadhsink_elmt_Ksfadhsink(unit "m3.0.s-1.0") = 6000000.0 "";
    Real elmt_reactant150 "";
    Real elmt_vlcadC16(unit = "") "";
    parameter Real elmt_vlcadC16_elmt_sflcadC16(unit "") = 0.9 "";
    Real elmt_product40 "";
    Real elmt_reactant38 "";
    Real elmt_product39 "";
    Real elmt_vmckatC10(unit = "") "";
    parameter Real elmt_vmckatC10_elmt_sfmckatC10(unit "") = 0.65 "";
    Real elmt_product120 "";
    Real elmt_reactant118 "";
    Real elmt_product119 "";
    Real elmt_vcactC10(unit = "") "";
    parameter Real elmt_vcactC10_elmt_KicactC10AcylCarCYT(unit "m-3.0.") = 56.0 "";
    parameter Real elmt_vcactC10_elmt_KmcactC10AcylCarCYT(unit "m-3.0.") = 15.0 "";
    parameter Real elmt_vcactC10_elmt_KmcactC10AcylCarMAT(unit "m-3.0.") = 15.0 "";
    Real elmt_product8 "";
    Real elmt_reactant7 "";
    Real elmt_vmschadC10(unit = "") "";
    parameter Real elmt_vmschadC10_elmt_sfmschadC10(unit "") = 0.64 "";
    Real elmt_reactant97 "";
    Real elmt_product99 "";
    Real elmt_product98 "";


    initial equation
        elmt_product73 = 1.0;
        elmt_product72 = 1.0;
        elmt_reactant41 = 1.0;
        elmt_product77 = 1.0;
        elmt_reactant109 = 1.0;
        elmt_product75 = 1.0;
        elmt_reactant47 = 1.0;
        elmt_product70 = 1.0;
        elmt_reactant44 = 1.0;
        elmt_reactant118 = 1.0;
        elmt_product69 = 1.0;
        elmt_reactant115 = 1.0;
        elmt_reactant112 = 1.0;
        elmt_reactant50 = 1.0;
        elmt_product85 = 1.0;
        elmt_product83 = 1.0;
        elmt_reactant53 = 1.0;
        elmt_product89 = 1.0;
        elmt_product87 = 1.0;
        elmt_reactant59 = 1.0;
        elmt_product81 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_product102 = 1.0;
        elmt_reactant121 = 1.0;
        elmt_product101 = 1.0;
        elmt_product104 = 1.0;
        elmt_reactant129 = 1.0;
        elmt_reactant127 = 1.0;
        elmt_product79 = 1.0;
        elmt_reactant124 = 1.0;
        elmt_product105 = 1.0;
        elmt_product108 = 1.0;
        elmt_product107 = 1.0;
        elmt_product96 = 1.0;
        elmt_product95 = 1.0;
        elmt_product93 = 1.0;
        elmt_product12 = 1.0;
        elmt_product99 = 1.0;
        elmt_product10 = 1.0;
        elmt_product98 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_product92 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_product90 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product8 = 1.0;
        elmt_product6 = 1.0;
        elmt_product22 = 1.0;
        elmt_product20 = 1.0;
        elmt_product0 = 1.0;
        elmt_reactant38 = 1.0;
        elmt_reactant32 = 1.0;
        elmt_product4 = 1.0;
        elmt_reactant35 = 1.0;
        elmt_product2 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_product16 = 1.0;
        elmt_reactant106 = 1.0;
        elmt_product14 = 1.0;
        elmt_reactant103 = 1.0;
        elmt_product18 = 1.0;
        elmt_reactant100 = 1.0;
        elmt_product30 = 1.0;
        elmt_reactant84 = 1.0;
        elmt_reactant86 = 1.0;
        elmt_product34 = 1.0;
        elmt_reactant80 = 1.0;
        elmt_product33 = 1.0;
        elmt_reactant82 = 1.0;
        elmt_product31 = 1.0;
        elmt_reactant88 = 1.0;
        elmt_product135 = 1.0;
        elmt_product134 = 1.0;
        elmt_product136 = 1.0;
        elmt_reactant151 = 1.0;
        elmt_product131 = 1.0;
        elmt_reactant150 = 1.0;
        elmt_product130 = 1.0;
        elmt_product132 = 1.0;
        elmt_product26 = 1.0;
        elmt_reactant9 = 1.0;
        elmt_product24 = 1.0;
        elmt_product139 = 1.0;
        elmt_product138 = 1.0;
        elmt_product28 = 1.0;
        elmt_reactant94 = 1.0;
        elmt_product40 = 1.0;
        elmt_reactant97 = 1.0;
        elmt_product45 = 1.0;
        elmt_reactant91 = 1.0;
        elmt_product43 = 1.0;
        elmt_product42 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_product140 = 1.0;
        elmt_reactant17 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_product146 = 1.0;
        elmt_product148 = 1.0;
        elmt_product147 = 1.0;
        elmt_product142 = 1.0;
        elmt_product144 = 1.0;
        elmt_product143 = 1.0;
        elmt_product37 = 1.0;
        elmt_product36 = 1.0;
        elmt_product39 = 1.0;
        elmt_product52 = 1.0;
        elmt_product51 = 1.0;
        elmt_reactant62 = 1.0;
        elmt_product55 = 1.0;
        elmt_product54 = 1.0;
        elmt_reactant65 = 1.0;
        elmt_reactant68 = 1.0;
        elmt_product113 = 1.0;
        elmt_product114 = 1.0;
        elmt_product111 = 1.0;
        elmt_product110 = 1.0;
        elmt_product49 = 1.0;
        elmt_product48 = 1.0;
        elmt_reactant137 = 1.0;
        elmt_product46 = 1.0;
        elmt_product117 = 1.0;
        elmt_product116 = 1.0;
        elmt_product119 = 1.0;
        elmt_reactant133 = 1.0;
        elmt_product63 = 1.0;
        elmt_reactant1 = 1.0;
        elmt_reactant74 = 1.0;
        elmt_product61 = 1.0;
        elmt_product60 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_product67 = 1.0;
        elmt_product66 = 1.0;
        elmt_reactant5 = 1.0;
        elmt_reactant71 = 1.0;
        elmt_product64 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_reactant76 = 1.0;
        elmt_reactant78 = 1.0;
        elmt_product123 = 1.0;
        elmt_reactant141 = 1.0;
        elmt_product126 = 1.0;
        elmt_product125 = 1.0;
        elmt_product120 = 1.0;
        elmt_product122 = 1.0;
        elmt_reactant149 = 1.0;
        elmt_product58 = 1.0;
        elmt_product57 = 1.0;
        elmt_product128 = 2.0;
        elmt_reactant145 = 1.0;


    equation
        elmt_vlcadC8 = (((elmt_vlcadC8_elmt_sflcadC8 * elmt_Vlcad * (((elmt_C8AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmlcadC8AcylCoAMAT * elmt_KmlcadFAD)) - ((elmt_C8EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmlcadC8AcylCoAMAT * elmt_KmlcadFAD * elmt_Keqlcad)))) / ((1.0 + (elmt_C8AcylCoAMAT / elmt_KmlcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmlcadC8EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmlcadC16AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmlcadC16EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmlcadC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmlcadC14EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmlcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmlcadC12EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmlcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmlcadC10EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmlcadFAD) + (elmt_FADHMAT / elmt_KmlcadFADH)))));
        elmt_vmtpC10 = (((elmt_vmtpC10_elmt_sfmtpC10 * elmt_Vmtp * (((elmt_C10EnoylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT) * elmt_CoAMAT) / (elmt_KmmtpC10EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT)) - ((elmt_C8AcylCoAMAT * elmt_NADHMAT * elmt_AcetylCoAMAT) / (elmt_KmmtpC10EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT * elmt_Keqmtp)))) / ((1.0 + (elmt_C10EnoylCoAMAT / elmt_KmmtpC10EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmtpC8AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmmtpC16EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmtpC16AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmmtpC14EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmtpC14AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmtpC12EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmtpC12AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmtpC8EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmtpC10AcylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmtpC6AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmtpNADMAT) + (elmt_NADHMAT / elmt_KmmtpNADHMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmtpCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmtpAcetylCoAMAT)))));
        elmt_vcpt2C8 = (((elmt_vcpt2C8_elmt_sfcpt2C8 * elmt_Vcpt2 * (((elmt_C8AcylCarMAT * elmt_CoAMAT) / (elmt_Kmcpt2C8AcylCarMAT * elmt_Kmcpt2CoAMAT)) - ((elmt_C8AcylCoAMAT * elmt_CarMAT) / (elmt_Kmcpt2C8AcylCarMAT * elmt_Kmcpt2CoAMAT * elmt_Keqcpt2)))) / ((1.0 + (elmt_C8AcylCarMAT / elmt_Kmcpt2C8AcylCarMAT) + (elmt_C8AcylCoAMAT / elmt_Kmcpt2C8AcylCoAMAT) + (elmt_C16AcylCarMAT / elmt_Kmcpt2C16AcylCarMAT) + (elmt_C16AcylCoAMAT / elmt_Kmcpt2C16AcylCoAMAT) + (elmt_C14AcylCarMAT / elmt_Kmcpt2C14AcylCarMAT) + (elmt_C14AcylCoAMAT / elmt_Kmcpt2C14AcylCoAMAT) + (elmt_C12AcylCarMAT / elmt_Kmcpt2C12AcylCarMAT) + (elmt_C12AcylCoAMAT / elmt_Kmcpt2C12AcylCoAMAT) + (elmt_C10AcylCarMAT / elmt_Kmcpt2C10AcylCarMAT) + (elmt_C10AcylCoAMAT / elmt_Kmcpt2C10AcylCoAMAT) + (elmt_C6AcylCarMAT / elmt_Kmcpt2C6AcylCarMAT) + (elmt_C6AcylCoAMAT / elmt_Kmcpt2C6AcylCoAMAT) + (elmt_C4AcylCarMAT / elmt_Kmcpt2C4AcylCarMAT) + (elmt_C4AcylCoAMAT / elmt_Kmcpt2C4AcylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_Kmcpt2CoAMAT) + (elmt_CarMAT / elmt_Kmcpt2CarMAT)))));
        elmt_vcpt2C6 = (((elmt_vcpt2C6_elmt_sfcpt2C6 * elmt_Vcpt2 * (((elmt_C6AcylCarMAT * elmt_CoAMAT) / (elmt_Kmcpt2C6AcylCarMAT * elmt_Kmcpt2CoAMAT)) - ((elmt_C6AcylCoAMAT * elmt_CarMAT) / (elmt_Kmcpt2C6AcylCarMAT * elmt_Kmcpt2CoAMAT * elmt_Keqcpt2)))) / ((1.0 + (elmt_C6AcylCarMAT / elmt_Kmcpt2C6AcylCarMAT) + (elmt_C6AcylCoAMAT / elmt_Kmcpt2C6AcylCoAMAT) + (elmt_C16AcylCarMAT / elmt_Kmcpt2C16AcylCarMAT) + (elmt_C16AcylCoAMAT / elmt_Kmcpt2C16AcylCoAMAT) + (elmt_C14AcylCarMAT / elmt_Kmcpt2C14AcylCarMAT) + (elmt_C14AcylCoAMAT / elmt_Kmcpt2C14AcylCoAMAT) + (elmt_C12AcylCarMAT / elmt_Kmcpt2C12AcylCarMAT) + (elmt_C12AcylCoAMAT / elmt_Kmcpt2C12AcylCoAMAT) + (elmt_C10AcylCarMAT / elmt_Kmcpt2C10AcylCarMAT) + (elmt_C10AcylCoAMAT / elmt_Kmcpt2C10AcylCoAMAT) + (elmt_C8AcylCarMAT / elmt_Kmcpt2C8AcylCarMAT) + (elmt_C8AcylCoAMAT / elmt_Kmcpt2C8AcylCoAMAT) + (elmt_C4AcylCarMAT / elmt_Kmcpt2C4AcylCarMAT) + (elmt_C4AcylCoAMAT / elmt_Kmcpt2C4AcylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_Kmcpt2CoAMAT) + (elmt_CarMAT / elmt_Kmcpt2CarMAT)))));
        elmt_vcpt2C4 = (((elmt_vcpt2C4_elmt_sfcpt2C4 * elmt_Vcpt2 * (((elmt_C4AcylCarMAT * elmt_CoAMAT) / (elmt_Kmcpt2C4AcylCarMAT * elmt_Kmcpt2CoAMAT)) - ((elmt_C4AcylCoAMAT * elmt_CarMAT) / (elmt_Kmcpt2C4AcylCarMAT * elmt_Kmcpt2CoAMAT * elmt_Keqcpt2)))) / ((1.0 + (elmt_C4AcylCarMAT / elmt_Kmcpt2C4AcylCarMAT) + (elmt_C4AcylCoAMAT / elmt_Kmcpt2C4AcylCoAMAT) + (elmt_C16AcylCarMAT / elmt_Kmcpt2C16AcylCarMAT) + (elmt_C16AcylCoAMAT / elmt_Kmcpt2C16AcylCoAMAT) + (elmt_C14AcylCarMAT / elmt_Kmcpt2C14AcylCarMAT) + (elmt_C14AcylCoAMAT / elmt_Kmcpt2C14AcylCoAMAT) + (elmt_C12AcylCarMAT / elmt_Kmcpt2C12AcylCarMAT) + (elmt_C12AcylCoAMAT / elmt_Kmcpt2C12AcylCoAMAT) + (elmt_C10AcylCarMAT / elmt_Kmcpt2C10AcylCarMAT) + (elmt_C10AcylCoAMAT / elmt_Kmcpt2C10AcylCoAMAT) + (elmt_C8AcylCarMAT / elmt_Kmcpt2C8AcylCarMAT) + (elmt_C8AcylCoAMAT / elmt_Kmcpt2C8AcylCoAMAT) + (elmt_C6AcylCarMAT / elmt_Kmcpt2C6AcylCarMAT) + (elmt_C6AcylCoAMAT / elmt_Kmcpt2C6AcylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_Kmcpt2CoAMAT) + (elmt_CarMAT / elmt_Kmcpt2CarMAT)))));
        elmt_vacesink = ((elmt_vacesink_elmt_Ksacesink * (elmt_AcetylCoAMAT - elmt_vacesink_elmt_K1acesink)));
        elmt_vcpt2C16 = (((elmt_vcpt2C16_elmt_sfcpt2C16 * elmt_Vcpt2 * (((elmt_C16AcylCarMAT * elmt_CoAMAT) / (elmt_Kmcpt2C16AcylCarMAT * elmt_Kmcpt2CoAMAT)) - ((elmt_C16AcylCoAMAT * elmt_CarMAT) / (elmt_Kmcpt2C16AcylCarMAT * elmt_Kmcpt2CoAMAT * elmt_Keqcpt2)))) / ((1.0 + (elmt_C16AcylCarMAT / elmt_Kmcpt2C16AcylCarMAT) + (elmt_C16AcylCoAMAT / elmt_Kmcpt2C16AcylCoAMAT) + (elmt_C14AcylCarMAT / elmt_Kmcpt2C14AcylCarMAT) + (elmt_C14AcylCoAMAT / elmt_Kmcpt2C14AcylCoAMAT) + (elmt_C12AcylCarMAT / elmt_Kmcpt2C12AcylCarMAT) + (elmt_C12AcylCoAMAT / elmt_Kmcpt2C12AcylCoAMAT) + (elmt_C10AcylCarMAT / elmt_Kmcpt2C10AcylCarMAT) + (elmt_C10AcylCoAMAT / elmt_Kmcpt2C10AcylCoAMAT) + (elmt_C8AcylCarMAT / elmt_Kmcpt2C8AcylCarMAT) + (elmt_C8AcylCoAMAT / elmt_Kmcpt2C8AcylCoAMAT) + (elmt_C6AcylCarMAT / elmt_Kmcpt2C6AcylCarMAT) + (elmt_C6AcylCoAMAT / elmt_Kmcpt2C6AcylCoAMAT) + (elmt_C4AcylCarMAT / elmt_Kmcpt2C4AcylCarMAT) + (elmt_C4AcylCoAMAT / elmt_Kmcpt2C4AcylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_Kmcpt2CoAMAT) + (elmt_CarMAT / elmt_Kmcpt2CarMAT)))));
        elmt_vmcadC4 = (((elmt_vmcadC4_elmt_sfmcadC4 * elmt_Vmcad * (((elmt_C4AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmmcadC4AcylCoAMAT * elmt_KmmcadFAD)) - ((elmt_C4EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmmcadC4AcylCoAMAT * elmt_KmmcadFAD * elmt_Keqmcad)))) / ((1.0 + (elmt_C4AcylCoAMAT / elmt_KmmcadC4AcylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmmcadC4EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmcadC12EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmcadC10EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmcadC8EnoylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmcadC6AcylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmmcadC6EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmmcadFAD) + (elmt_FADHMAT / elmt_KmmcadFADH)))));
        elmt_vcpt2C12 = (((elmt_vcpt2C12_elmt_sfcpt2C12 * elmt_Vcpt2 * (((elmt_C12AcylCarMAT * elmt_CoAMAT) / (elmt_Kmcpt2C12AcylCarMAT * elmt_Kmcpt2CoAMAT)) - ((elmt_C12AcylCoAMAT * elmt_CarMAT) / (elmt_Kmcpt2C12AcylCarMAT * elmt_Kmcpt2CoAMAT * elmt_Keqcpt2)))) / ((1.0 + (elmt_C12AcylCarMAT / elmt_Kmcpt2C12AcylCarMAT) + (elmt_C12AcylCoAMAT / elmt_Kmcpt2C12AcylCoAMAT) + (elmt_C16AcylCarMAT / elmt_Kmcpt2C16AcylCarMAT) + (elmt_C16AcylCoAMAT / elmt_Kmcpt2C16AcylCoAMAT) + (elmt_C14AcylCarMAT / elmt_Kmcpt2C14AcylCarMAT) + (elmt_C14AcylCoAMAT / elmt_Kmcpt2C14AcylCoAMAT) + (elmt_C10AcylCarMAT / elmt_Kmcpt2C10AcylCarMAT) + (elmt_C10AcylCoAMAT / elmt_Kmcpt2C10AcylCoAMAT) + (elmt_C8AcylCarMAT / elmt_Kmcpt2C8AcylCarMAT) + (elmt_C8AcylCoAMAT / elmt_Kmcpt2C8AcylCoAMAT) + (elmt_C6AcylCarMAT / elmt_Kmcpt2C6AcylCarMAT) + (elmt_C6AcylCoAMAT / elmt_Kmcpt2C6AcylCoAMAT) + (elmt_C4AcylCarMAT / elmt_Kmcpt2C4AcylCarMAT) + (elmt_C4AcylCoAMAT / elmt_Kmcpt2C4AcylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_Kmcpt2CoAMAT) + (elmt_CarMAT / elmt_Kmcpt2CarMAT)))));
        elmt_vcpt2C14 = (((elmt_vcpt2C14_elmt_sfcpt2C14 * elmt_Vcpt2 * (((elmt_C14AcylCarMAT * elmt_CoAMAT) / (elmt_Kmcpt2C14AcylCarMAT * elmt_Kmcpt2CoAMAT)) - ((elmt_C14AcylCoAMAT * elmt_CarMAT) / (elmt_Kmcpt2C14AcylCarMAT * elmt_Kmcpt2CoAMAT * elmt_Keqcpt2)))) / ((1.0 + (elmt_C14AcylCarMAT / elmt_Kmcpt2C14AcylCarMAT) + (elmt_C14AcylCoAMAT / elmt_Kmcpt2C14AcylCoAMAT) + (elmt_C16AcylCarMAT / elmt_Kmcpt2C16AcylCarMAT) + (elmt_C16AcylCoAMAT / elmt_Kmcpt2C16AcylCoAMAT) + (elmt_C12AcylCarMAT / elmt_Kmcpt2C12AcylCarMAT) + (elmt_C12AcylCoAMAT / elmt_Kmcpt2C12AcylCoAMAT) + (elmt_C10AcylCarMAT / elmt_Kmcpt2C10AcylCarMAT) + (elmt_C10AcylCoAMAT / elmt_Kmcpt2C10AcylCoAMAT) + (elmt_C8AcylCarMAT / elmt_Kmcpt2C8AcylCarMAT) + (elmt_C8AcylCoAMAT / elmt_Kmcpt2C8AcylCoAMAT) + (elmt_C6AcylCarMAT / elmt_Kmcpt2C6AcylCarMAT) + (elmt_C6AcylCoAMAT / elmt_Kmcpt2C6AcylCoAMAT) + (elmt_C4AcylCarMAT / elmt_Kmcpt2C4AcylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_Kmcpt2C4AcylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_Kmcpt2CoAMAT) + (elmt_CarMAT / elmt_Kmcpt2CarMAT)))));
        elmt_vscadC6 = (((elmt_vscadC6_elmt_sfscadC6 * elmt_Vscad * (((elmt_C6AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmscadC6AcylCoAMAT * elmt_KmscadFAD)) - ((elmt_C6EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmscadC6AcylCoAMAT * elmt_KmscadFAD * elmt_Keqscad)))) / ((1.0 + (elmt_C6AcylCoAMAT / elmt_KmscadC6AcylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmscadC6EnoylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmscadC4AcylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmscadC4EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmscadFAD) + (elmt_FADHMAT / elmt_KmscadFADH)))));
        elmt_vcpt2C10 = (((elmt_vcpt2C10_elmt_sfcpt2C10 * elmt_Vcpt2 * (((elmt_C10AcylCarMAT * elmt_CoAMAT) / (elmt_Kmcpt2C10AcylCarMAT * elmt_Kmcpt2CoAMAT)) - ((elmt_C10AcylCoAMAT * elmt_CarMAT) / (elmt_Kmcpt2C10AcylCarMAT * elmt_Kmcpt2CoAMAT * elmt_Keqcpt2)))) / ((1.0 + (elmt_C10AcylCarMAT / elmt_Kmcpt2C10AcylCarMAT) + (elmt_C10AcylCoAMAT / elmt_Kmcpt2C10AcylCoAMAT) + (elmt_C16AcylCarMAT / elmt_Kmcpt2C16AcylCarMAT) + (elmt_C16AcylCoAMAT / elmt_Kmcpt2C16AcylCoAMAT) + (elmt_C14AcylCarMAT / elmt_Kmcpt2C14AcylCarMAT) + (elmt_C14AcylCoAMAT / elmt_Kmcpt2C14AcylCoAMAT) + (elmt_C12AcylCarMAT / elmt_Kmcpt2C12AcylCarMAT) + (elmt_C12AcylCoAMAT / elmt_Kmcpt2C12AcylCoAMAT) + (elmt_C8AcylCarMAT / elmt_Kmcpt2C8AcylCarMAT) + (elmt_C8AcylCoAMAT / elmt_Kmcpt2C8AcylCoAMAT) + (elmt_C6AcylCarMAT / elmt_Kmcpt2C6AcylCarMAT) + (elmt_C6AcylCoAMAT / elmt_Kmcpt2C6AcylCoAMAT) + (elmt_C4AcylCarMAT / elmt_Kmcpt2C4AcylCarMAT) + (elmt_C4AcylCoAMAT / elmt_Kmcpt2C4AcylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_Kmcpt2CoAMAT) + (elmt_CarMAT / elmt_Kmcpt2CarMAT)))));
        elmt_vscadC4 = (((elmt_vscadC4_elmt_sfscadC4 * elmt_Vscad * (((elmt_C4AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmscadC4AcylCoAMAT * elmt_KmscadFAD)) - ((elmt_C4EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmscadC4AcylCoAMAT * elmt_KmscadFAD * elmt_Keqscad)))) / ((1.0 + (elmt_C4AcylCoAMAT / elmt_KmscadC4AcylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmscadC4EnoylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmscadC6AcylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmscadC6EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmscadFAD) + (elmt_FADHMAT / elmt_KmscadFADH)))));
        elmt_vcrotC14 = (((elmt_vcrotC14_elmt_sfcrotC14 * elmt_Vcrot * ((elmt_C14EnoylCoAMAT / elmt_KmcrotC14EnoylCoAMAT) - (elmt_C14HydroxyacylCoAMAT / (elmt_KmcrotC14EnoylCoAMAT * elmt_Keqcrot)))) / (1.0 + (elmt_C14EnoylCoAMAT / elmt_KmcrotC14EnoylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmcrotC14HydroxyacylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmcrotC16EnoylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmcrotC16HydroxyacylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmcrotC12EnoylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmcrotC12HydroxyacylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmcrotC10EnoylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmcrotC10HydroxyacylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmcrotC8EnoylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmcrotC8HydroxyacylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmcrotC6EnoylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmcrotC6HydroxyacylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmcrotC4EnoylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmcrotC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA))));
        elmt_vcrotC16 = (((elmt_vcrotC16_elmt_sfcrotC16 * elmt_Vcrot * ((elmt_C16EnoylCoAMAT / elmt_KmcrotC16EnoylCoAMAT) - (elmt_C16HydroxyacylCoAMAT / (elmt_KmcrotC16EnoylCoAMAT * elmt_Keqcrot)))) / (1.0 + (elmt_C16EnoylCoAMAT / elmt_KmcrotC16EnoylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmcrotC16HydroxyacylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmcrotC14EnoylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmcrotC14HydroxyacylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmcrotC12EnoylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmcrotC12HydroxyacylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmcrotC10EnoylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmcrotC10HydroxyacylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmcrotC8EnoylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmcrotC8HydroxyacylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmcrotC6EnoylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmcrotC6HydroxyacylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmcrotC4EnoylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmcrotC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA))));
        elmt_vmschadC8 = (((elmt_vmschadC8_elmt_sfmschadC8 * elmt_Vmschad * (((elmt_C8HydroxyacylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT)) / (elmt_KmmschadC8HydroxyacylCoAMAT * elmt_KmmschadNADMAT)) - ((elmt_C8KetoacylCoAMAT * elmt_NADHMAT) / (elmt_KmmschadC8HydroxyacylCoAMAT * elmt_KmmschadNADMAT * elmt_Keqmschad)))) / ((1.0 + (elmt_C8HydroxyacylCoAMAT / elmt_KmmschadC8HydroxyacylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmschadC8KetoacylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmmschadC16HydroxyacylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmschadC16KetoacylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmmschadC14HydroxyacylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmschadC14KetoacylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmmschadC12HydroxyacylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmschadC12KetoacylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmmschadC10HydroxyacylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmschadC10KetoacylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmmschadC6HydroxyacylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmschadC6KetoacylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmmschadC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmschadC4AcetoacylCoAMAT)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmschadNADMAT) + (elmt_NADHMAT / elmt_KmmschadNADHMAT)))));
        elmt_vcrotC10 = (((elmt_vcrotC10_elmt_sfcrotC10 * elmt_Vcrot * ((elmt_C10EnoylCoAMAT / elmt_KmcrotC10EnoylCoAMAT) - (elmt_C10HydroxyacylCoAMAT / (elmt_KmcrotC10EnoylCoAMAT * elmt_Keqcrot)))) / (1.0 + (elmt_C10EnoylCoAMAT / elmt_KmcrotC10EnoylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmcrotC10HydroxyacylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmcrotC16EnoylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmcrotC16HydroxyacylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmcrotC14EnoylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmcrotC14HydroxyacylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmcrotC12EnoylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmcrotC12HydroxyacylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmcrotC8EnoylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmcrotC8HydroxyacylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmcrotC6EnoylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmcrotC6HydroxyacylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmcrotC4EnoylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmcrotC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA))));
        elmt_vmckatC6 = (((elmt_vmckatC6_elmt_sfmckatC6 * elmt_Vmckat * (((elmt_C6KetoacylCoAMAT * elmt_CoAMAT) / (elmt_KmmckatC6KetoacylCoAMAT * elmt_KmmckatCoAMAT)) - ((elmt_C4AcylCoAMAT * elmt_AcetylCoAMAT) / (elmt_KmmckatC6KetoacylCoAMAT * elmt_KmmckatCoAMAT * elmt_Keqmckat)))) / ((1.0 + (elmt_C6KetoacylCoAMAT / elmt_KmmckatC6KetoacylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmckatC4AcylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmckatC16KetoacylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmckatC16AcylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmckatC14KetoacylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmckatC14AcylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmckatC12KetoacylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmckatC12AcylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmckatC10KetoacylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmckatC10AcylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmckatC8KetoacylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmckatC8AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmckatC4AcetoacylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmckatC6AcylCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmckatCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)))));
        elmt_vcrotC12 = (((elmt_vcrotC12_elmt_sfcrotC12 * elmt_Vcrot * ((elmt_C12EnoylCoAMAT / elmt_KmcrotC12EnoylCoAMAT) - (elmt_C12HydroxyacylCoAMAT / (elmt_KmcrotC12EnoylCoAMAT * elmt_Keqcrot)))) / (1.0 + (elmt_C12EnoylCoAMAT / elmt_KmcrotC12EnoylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmcrotC12HydroxyacylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmcrotC16EnoylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmcrotC16HydroxyacylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmcrotC14EnoylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmcrotC14HydroxyacylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmcrotC10EnoylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmcrotC10HydroxyacylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmcrotC8EnoylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmcrotC8HydroxyacylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmcrotC6EnoylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmcrotC6HydroxyacylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmcrotC4EnoylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmcrotC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA))));
        elmt_vmckatC4 = (((elmt_vmckatC4_elmt_sfmckatC4 * elmt_Vmckat * (((elmt_C4AcetoacylCoAMAT * elmt_CoAMAT) / (elmt_KmmckatC4AcetoacylCoAMAT * elmt_KmmckatCoAMAT)) - ((elmt_AcetylCoAMAT * elmt_AcetylCoAMAT) / (elmt_KmmckatC4AcetoacylCoAMAT * elmt_KmmckatCoAMAT * elmt_Keqmckat)))) / ((1.0 + (elmt_C4AcetoacylCoAMAT / elmt_KmmckatC4AcetoacylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmckatC4AcylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmckatC16KetoacylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmckatC16AcylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmckatC14KetoacylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmckatC14AcylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmckatC12KetoacylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmckatC12AcylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmckatC10KetoacylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmckatC10AcylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmckatC8KetoacylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmckatC8AcylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmckatC6KetoacylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmckatC6AcylCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmckatCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)))));
        elmt_vmcadC6 = (((elmt_vmcadC6_elmt_sfmcadC6 * elmt_Vmcad * (((elmt_C6AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmmcadC6AcylCoAMAT * elmt_KmmcadFAD)) - ((elmt_C6EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmmcadC6AcylCoAMAT * elmt_KmmcadFAD * elmt_Keqmcad)))) / ((1.0 + (elmt_C6AcylCoAMAT / elmt_KmmcadC6AcylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmmcadC6EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmcadC12EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmcadC10EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmcadC8EnoylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmcadC4AcylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmmcadC4EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmmcadFAD) + (elmt_FADHMAT / elmt_KmmcadFADH)))));
        elmt_vmtpC16 = (((elmt_vmtpC16_elmt_sfmtpC16 * elmt_Vmtp * (((elmt_C16EnoylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT) * elmt_CoAMAT) / (elmt_KmmtpC16EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT)) - ((elmt_C14AcylCoAMAT * elmt_NADHMAT * elmt_AcetylCoAMAT) / (elmt_KmmtpC16EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT * elmt_Keqmtp)))) / ((1.0 + (elmt_C16EnoylCoAMAT / elmt_KmmtpC16EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmtpC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmmtpC14EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmtpC16AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmtpC12EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmtpC12AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmtpC10EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmtpC10AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmtpC8EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmtpC8AcylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmtpC6AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmtpNADMAT) + (elmt_NADHMAT / elmt_KmmtpNADHMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmtpCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmtpAcetylCoAMAT)))));
        elmt_vmcadC8 = (((elmt_vmcadC8_elmt_sfmcadC8 * elmt_Vmcad * (((elmt_C8AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmmcadC8AcylCoAMAT * elmt_KmmcadFAD)) - ((elmt_C8EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmmcadC8AcylCoAMAT * elmt_KmmcadFAD * elmt_Keqmcad)))) / ((1.0 + (elmt_C8AcylCoAMAT / elmt_KmmcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmcadC8EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmcadC12EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmcadC10EnoylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmcadC6AcylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmmcadC6EnoylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmcadC4AcylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmmcadC4EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmmcadFAD) + (elmt_FADHMAT / elmt_KmmcadFADH)))));
        elmt_vmckatC8 = (((elmt_vmckatC8_elmt_sfmckatC8 * elmt_Vmckat * (((elmt_C8KetoacylCoAMAT * elmt_CoAMAT) / (elmt_KmmckatC8KetoacylCoAMAT * elmt_KmmckatCoAMAT)) - ((elmt_C6AcylCoAMAT * elmt_AcetylCoAMAT) / (elmt_KmmckatC8KetoacylCoAMAT * elmt_KmmckatCoAMAT * elmt_Keqmckat)))) / ((1.0 + (elmt_C8KetoacylCoAMAT / elmt_KmmckatC8KetoacylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmckatC6AcylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmckatC16KetoacylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmckatC16AcylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmckatC14KetoacylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmckatC14AcylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmckatC12KetoacylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmckatC12AcylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmckatC10KetoacylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmckatC10AcylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmckatC6KetoacylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmckatC8AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmckatC4AcetoacylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmckatC4AcylCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmckatCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)))));
        elmt_vmtpC14 = (((elmt_vmtpC14_elmt_sfmtpC14 * elmt_Vmtp * (((elmt_C14EnoylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT) * elmt_CoAMAT) / (elmt_KmmtpC14EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT)) - ((elmt_C12AcylCoAMAT * elmt_NADHMAT * elmt_AcetylCoAMAT) / (elmt_KmmtpC14EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT * elmt_Keqmtp)))) / ((1.0 + (elmt_C14EnoylCoAMAT / elmt_KmmtpC14EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmtpC12AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmmtpC16EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmtpC16AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmtpC12EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmtpC14AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmtpC10EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmtpC10AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmtpC8EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmtpC8AcylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmtpC6AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmtpNADMAT) + (elmt_NADHMAT / elmt_KmmtpNADHMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmtpCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmtpAcetylCoAMAT)))));
        elmt_vmschadC6 = (((elmt_vmschadC6_elmt_sfmschadC6 * elmt_Vmschad * (((elmt_C6HydroxyacylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT)) / (elmt_KmmschadC6HydroxyacylCoAMAT * elmt_KmmschadNADMAT)) - ((elmt_C6KetoacylCoAMAT * elmt_NADHMAT) / (elmt_KmmschadC6HydroxyacylCoAMAT * elmt_KmmschadNADMAT * elmt_Keqmschad)))) / ((1.0 + (elmt_C6HydroxyacylCoAMAT / elmt_KmmschadC6HydroxyacylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmschadC6KetoacylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmmschadC16HydroxyacylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmschadC16KetoacylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmmschadC14HydroxyacylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmschadC14KetoacylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmmschadC12HydroxyacylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmschadC12KetoacylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmmschadC10HydroxyacylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmschadC10KetoacylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmmschadC8HydroxyacylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmschadC8KetoacylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmmschadC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmschadC4AcetoacylCoAMAT)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmschadNADMAT) + (elmt_NADHMAT / elmt_KmmschadNADHMAT)))));
        elmt_vmtpC8 = (((elmt_vmtpC8_elmt_sfmtpC8 * elmt_Vmtp * (((elmt_C8EnoylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT) * elmt_CoAMAT) / (elmt_KmmtpC8EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT)) - ((elmt_C6AcylCoAMAT * elmt_NADHMAT * elmt_AcetylCoAMAT) / (elmt_KmmtpC8EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT * elmt_Keqmtp)))) / ((1.0 + (elmt_C8EnoylCoAMAT / elmt_KmmtpC8EnoylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmtpC6AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmmtpC16EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmtpC16AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmmtpC14EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmtpC14AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmtpC12EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmtpC12AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmtpC10EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmtpC10AcylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmtpC8AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmtpNADMAT) + (elmt_NADHMAT / elmt_KmmtpNADHMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmtpCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmtpAcetylCoAMAT)))));
        elmt_vmtpC12 = (((elmt_vmtpC12_elmt_sfmtpC12 * elmt_Vmtp * (((elmt_C12EnoylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT) * elmt_CoAMAT) / (elmt_KmmtpC12EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT)) - ((elmt_C10AcylCoAMAT * elmt_NADHMAT * elmt_AcetylCoAMAT) / (elmt_KmmtpC12EnoylCoAMAT * elmt_KmmtpNADMAT * elmt_KmmtpCoAMAT * elmt_Keqmtp)))) / ((1.0 + (elmt_C12EnoylCoAMAT / elmt_KmmtpC12EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmtpC10AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmmtpC16EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmtpC16AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmmtpC14EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmtpC14AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmtpC10EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmtpC12AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmtpC8EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmtpC8AcylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmtpC6AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmtpNADMAT) + (elmt_NADHMAT / elmt_KmmtpNADHMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmtpCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmtpAcetylCoAMAT)))));
        elmt_vmschadC4 = (((elmt_vmschadC4_elmt_sfmschadC4 * elmt_Vmschad * (((elmt_C4HydroxyacylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT)) / (elmt_KmmschadC4HydroxyacylCoAMAT * elmt_KmmschadNADMAT)) - ((elmt_C4AcetoacylCoAMAT * elmt_NADHMAT) / (elmt_KmmschadC4HydroxyacylCoAMAT * elmt_KmmschadNADMAT * elmt_Keqmschad)))) / ((1.0 + (elmt_C4HydroxyacylCoAMAT / elmt_KmmschadC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmschadC4AcetoacylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmmschadC16HydroxyacylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmschadC16KetoacylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmmschadC14HydroxyacylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmschadC14KetoacylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmmschadC12HydroxyacylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmschadC12KetoacylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmmschadC10HydroxyacylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmschadC10KetoacylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmmschadC8HydroxyacylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmschadC8KetoacylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmmschadC6HydroxyacylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmschadC6KetoacylCoAMAT)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmschadNADMAT) + (elmt_NADHMAT / elmt_KmmschadNADHMAT)))));
        elmt_vmckatC16 = (((elmt_vmckatC16_elmt_sfmckatC16 * elmt_Vmckat * (((elmt_C16KetoacylCoAMAT * elmt_CoAMAT) / (elmt_KmmckatC16KetoacylCoAMAT * elmt_KmmckatCoAMAT)) - ((elmt_C14AcylCoAMAT * elmt_AcetylCoAMAT) / (elmt_KmmckatC16KetoacylCoAMAT * elmt_KmmckatCoAMAT * elmt_Keqmckat)))) / ((1.0 + (elmt_C16KetoacylCoAMAT / elmt_KmmckatC16KetoacylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmckatC14AcylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmckatC14KetoacylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmckatC16AcylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmckatC12KetoacylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmckatC12AcylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmckatC10KetoacylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmckatC10AcylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmckatC8KetoacylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmckatC8AcylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmckatC6KetoacylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmckatC6AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmckatC4AcetoacylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmckatC4AcylCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmckatCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)))));
        elmt_vcpt1C16 = (((elmt_vcpt1C16_elmt_sfcpt1C16 * elmt_vcpt1C16_elmt_Vcpt1 * (((elmt_C16AcylCoACYT * elmt_CarCYT) / (elmt_vcpt1C16_elmt_Kmcpt1C16AcylCoACYT * elmt_vcpt1C16_elmt_Kmcpt1CarCYT)) - ((elmt_C16AcylCarCYT * elmt_CoACYT) / (elmt_vcpt1C16_elmt_Kmcpt1C16AcylCoACYT * elmt_vcpt1C16_elmt_Kmcpt1CarCYT * elmt_vcpt1C16_elmt_Keqcpt1)))) / ((1.0 + (elmt_C16AcylCoACYT / elmt_vcpt1C16_elmt_Kmcpt1C16AcylCoACYT) + (elmt_C16AcylCarCYT / elmt_vcpt1C16_elmt_Kmcpt1C16AcylCarCYT) + Functions.pow((elmt_MalCoACYT / elmt_vcpt1C16_elmt_Kicpt1MalCoACYT), elmt_vcpt1C16_elmt_ncpt1)) * (1.0 + (elmt_CarCYT / elmt_vcpt1C16_elmt_Kmcpt1CarCYT) + (elmt_CoACYT / elmt_vcpt1C16_elmt_Kmcpt1CoACYT)))));
        elmt_vmckatC12 = (((elmt_vmckatC12_elmt_sfmckatC12 * elmt_Vmckat * (((elmt_C12KetoacylCoAMAT * elmt_CoAMAT) / (elmt_KmmckatC12KetoacylCoAMAT * elmt_KmmckatCoAMAT)) - ((elmt_C10AcylCoAMAT * elmt_AcetylCoAMAT) / (elmt_KmmckatC12KetoacylCoAMAT * elmt_KmmckatCoAMAT * elmt_Keqmckat)))) / ((1.0 + (elmt_C12KetoacylCoAMAT / elmt_KmmckatC12KetoacylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmckatC10AcylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmckatC16KetoacylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmckatC16AcylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmckatC14KetoacylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmckatC14AcylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmckatC10KetoacylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmckatC12AcylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmckatC8KetoacylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmckatC8AcylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmckatC6KetoacylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmckatC6AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmckatC4AcetoacylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmckatC4AcylCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmckatCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)))));
        elmt_vmckatC14 = (((elmt_vmckatC14_elmt_sfmckatC14 * elmt_Vmckat * (((elmt_C14KetoacylCoAMAT * elmt_CoAMAT) / (elmt_KmmckatC14KetoacylCoAMAT * elmt_KmmckatCoAMAT)) - ((elmt_C12AcylCoAMAT * elmt_AcetylCoAMAT) / (elmt_KmmckatC14KetoacylCoAMAT * elmt_KmmckatCoAMAT * elmt_Keqmckat)))) / ((1.0 + (elmt_C14KetoacylCoAMAT / elmt_KmmckatC14KetoacylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmckatC12AcylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmckatC16KetoacylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmckatC16AcylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmckatC12KetoacylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmckatC14AcylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmckatC10KetoacylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmckatC10AcylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmckatC8KetoacylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmckatC8AcylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmckatC6KetoacylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmckatC6AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmckatC4AcetoacylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmckatC4AcylCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmckatCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)))));
        elmt_vmcadC12 = (((elmt_vmcadC12_elmt_sfmcadC12 * elmt_Vmcad * (((elmt_C12AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmmcadC12AcylCoAMAT * elmt_KmmcadFAD)) - ((elmt_C12EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmmcadC12AcylCoAMAT * elmt_KmmcadFAD * elmt_Keqmcad)))) / ((1.0 + (elmt_C12AcylCoAMAT / elmt_KmmcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmcadC12EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmcadC10EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmcadC8EnoylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmcadC6AcylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmmcadC6EnoylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmcadC4AcylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmmcadC4EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmmcadFAD) + (elmt_FADHMAT / elmt_KmmcadFADH)))));
        elmt_vmcadC10 = (((elmt_vmcadC10_elmt_sfmcadC10 * elmt_Vmcad * (((elmt_C10AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmmcadC10AcylCoAMAT * elmt_KmmcadFAD)) - ((elmt_C10EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmmcadC10AcylCoAMAT * elmt_KmmcadFAD * elmt_Keqmcad)))) / ((1.0 + (elmt_C10AcylCoAMAT / elmt_KmmcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmmcadC10EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmmcadC12EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmmcadC8EnoylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmcadC6AcylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmmcadC6EnoylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmcadC4AcylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmmcadC4EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmmcadFAD) + (elmt_FADHMAT / elmt_KmmcadFADH)))));
        elmt_vcactC8 = (((elmt_Vfcact * ((elmt_C8AcylCarCYT * elmt_CarMAT) - ((elmt_C8AcylCarMAT * elmt_CarCYT) / elmt_Keqcact))) / ((elmt_C8AcylCarCYT * elmt_CarMAT) + (elmt_KmcactCarMAT * elmt_C8AcylCarCYT) + (elmt_vcactC8_elmt_KmcactC8AcylCarCYT * elmt_CarMAT * (1.0 + (elmt_CarCYT / elmt_KicactCarCYT))) + ((elmt_Vfcact / (elmt_Vrcact * elmt_Keqcact)) * ((elmt_KmcactCarCYT * elmt_C8AcylCarMAT * (1.0 + (elmt_C8AcylCarCYT / elmt_vcactC8_elmt_KicactC8AcylCarCYT))) + (elmt_CarCYT * (elmt_vcactC8_elmt_KmcactC8AcylCarMAT + elmt_C8AcylCarMAT)))))));
        elmt_vcactC4 = (((elmt_Vfcact * ((elmt_C4AcylCarCYT * elmt_CarMAT) - ((elmt_C4AcylCarMAT * elmt_CarCYT) / elmt_Keqcact))) / ((elmt_C4AcylCarCYT * elmt_CarMAT) + (elmt_KmcactCarMAT * elmt_C4AcylCarCYT) + (elmt_vcactC4_elmt_KmcactC4AcylCarCYT * elmt_CarMAT * (1.0 + (elmt_CarCYT / elmt_KicactCarCYT))) + ((elmt_Vfcact / (elmt_Vrcact * elmt_Keqcact)) * ((elmt_KmcactCarCYT * elmt_C4AcylCarMAT * (1.0 + (elmt_C4AcylCarCYT / elmt_vcactC4_elmt_KicactC4AcylCarCYT))) + (elmt_CarCYT * (elmt_vcactC4_elmt_KmcactC4AcylCarMAT + elmt_C4AcylCarMAT)))))));
        elmt_vcrotC4 = (((elmt_vcrotC4_elmt_sfcrotC4 * elmt_Vcrot * ((elmt_C4EnoylCoAMAT / elmt_KmcrotC4EnoylCoAMAT) - (elmt_C4HydroxyacylCoAMAT / (elmt_KmcrotC4EnoylCoAMAT * elmt_Keqcrot)))) / (1.0 + (elmt_C4EnoylCoAMAT / elmt_KmcrotC4EnoylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmcrotC4HydroxyacylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmcrotC16EnoylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmcrotC16HydroxyacylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmcrotC14EnoylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmcrotC14HydroxyacylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmcrotC12EnoylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmcrotC12HydroxyacylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmcrotC10EnoylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmcrotC10HydroxyacylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmcrotC8EnoylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmcrotC8HydroxyacylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmcrotC6EnoylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmcrotC6HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA))));
        elmt_vcactC6 = (((elmt_Vfcact * ((elmt_C6AcylCarCYT * elmt_CarMAT) - ((elmt_C6AcylCarMAT * elmt_CarCYT) / elmt_Keqcact))) / ((elmt_C6AcylCarCYT * elmt_CarMAT) + (elmt_KmcactCarMAT * elmt_C6AcylCarCYT) + (elmt_vcactC6_elmt_KmcactC6AcylCarCYT * elmt_CarMAT * (1.0 + (elmt_CarCYT / elmt_KicactCarCYT))) + ((elmt_Vfcact / (elmt_Vrcact * elmt_Keqcact)) * ((elmt_KmcactCarCYT * elmt_C6AcylCarMAT * (1.0 + (elmt_C6AcylCarCYT / elmt_vcactC6_elmt_KicactC6AcylCarCYT))) + (elmt_CarCYT * (elmt_vcactC6_elmt_KmcactC6AcylCarMAT + elmt_C6AcylCarMAT)))))));
        elmt_vcrotC8 = (((elmt_vcrotC8_elmt_sfcrotC8 * elmt_Vcrot * ((elmt_C8EnoylCoAMAT / elmt_KmcrotC8EnoylCoAMAT) - (elmt_C8HydroxyacylCoAMAT / (elmt_KmcrotC8EnoylCoAMAT * elmt_Keqcrot)))) / (1.0 + (elmt_C8EnoylCoAMAT / elmt_KmcrotC8EnoylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmcrotC8HydroxyacylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmcrotC16EnoylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmcrotC16HydroxyacylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmcrotC14EnoylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmcrotC14HydroxyacylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmcrotC12EnoylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmcrotC12HydroxyacylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmcrotC10EnoylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmcrotC10HydroxyacylCoAMAT) + (elmt_C6EnoylCoAMAT / elmt_KmcrotC6EnoylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmcrotC6HydroxyacylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmcrotC4EnoylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmcrotC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA))));
        elmt_vcrotC6 = (((elmt_vcrotC6_elmt_sfcrotC6 * elmt_Vcrot * ((elmt_C6EnoylCoAMAT / elmt_KmcrotC6EnoylCoAMAT) - (elmt_C6HydroxyacylCoAMAT / (elmt_KmcrotC6EnoylCoAMAT * elmt_Keqcrot)))) / (1.0 + (elmt_C6EnoylCoAMAT / elmt_KmcrotC6EnoylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmcrotC6HydroxyacylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmcrotC16EnoylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmcrotC16HydroxyacylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmcrotC14EnoylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmcrotC14HydroxyacylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmcrotC12EnoylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmcrotC12HydroxyacylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmcrotC10EnoylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmcrotC10HydroxyacylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmcrotC8EnoylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmcrotC8HydroxyacylCoAMAT) + (elmt_C4EnoylCoAMAT / elmt_KmcrotC4EnoylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmcrotC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KicrotC4AcetoacylCoA))));
        elmt_vcactC14 = (((elmt_Vfcact * ((elmt_C14AcylCarCYT * elmt_CarMAT) - ((elmt_C14AcylCarMAT * elmt_CarCYT) / elmt_Keqcact))) / ((elmt_C14AcylCarCYT * elmt_CarMAT) + (elmt_KmcactCarMAT * elmt_C14AcylCarCYT) + (elmt_vcactC14_elmt_KmcactC14AcylCarCYT * elmt_CarMAT * (1.0 + (elmt_CarCYT / elmt_KicactCarCYT))) + ((elmt_Vfcact / (elmt_Vrcact * elmt_Keqcact)) * ((elmt_KmcactCarCYT * elmt_C14AcylCarMAT * (1.0 + (elmt_C14AcylCarCYT / elmt_vcactC14_elmt_KicactC14AcylCarCYT))) + (elmt_CarCYT * (elmt_vcactC14_elmt_KmcactC14AcylCarMAT + elmt_C14AcylCarMAT)))))));
        elmt_vmschadC14 = (((elmt_vmschadC14_elmt_sfmschadC14 * elmt_Vmschad * (((elmt_C14HydroxyacylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT)) / (elmt_KmmschadC14HydroxyacylCoAMAT * elmt_KmmschadNADMAT)) - ((elmt_C14KetoacylCoAMAT * elmt_NADHMAT) / (elmt_KmmschadC14HydroxyacylCoAMAT * elmt_KmmschadNADMAT * elmt_Keqmschad)))) / ((1.0 + (elmt_C14HydroxyacylCoAMAT / elmt_KmmschadC14HydroxyacylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmschadC14KetoacylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmmschadC16HydroxyacylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmschadC16KetoacylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmmschadC12HydroxyacylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmschadC12KetoacylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmmschadC10HydroxyacylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmschadC10KetoacylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmmschadC8HydroxyacylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmschadC8KetoacylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmmschadC6HydroxyacylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmschadC6KetoacylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmmschadC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmschadC4AcetoacylCoAMAT)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmschadNADMAT) + (elmt_NADHMAT / elmt_KmmschadNADHMAT)))));
        elmt_vvlcadC12 = (((elmt_vvlcadC12_elmt_sfvlcadC12 * elmt_Vvlcad * (((elmt_C12AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmvlcadC12AcylCoAMAT * elmt_KmvlcadFAD)) - ((elmt_C12EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmvlcadC12AcylCoAMAT * elmt_KmvlcadFAD * elmt_Keqvlcad)))) / ((1.0 + (elmt_C12AcylCoAMAT / elmt_KmvlcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmvlcadC12EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmvlcadC16AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmvlcadC16EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmvlcadC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmvlcadC14EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmvlcadFAD) + (elmt_FADHMAT / elmt_KmvlcadFADH)))));
        elmt_vcactC12 = (((elmt_Vfcact * ((elmt_C12AcylCarCYT * elmt_CarMAT) - ((elmt_C12AcylCarMAT * elmt_CarCYT) / elmt_Keqcact))) / ((elmt_C12AcylCarCYT * elmt_CarMAT) + (elmt_KmcactCarMAT * elmt_C12AcylCarCYT) + (elmt_vcactC12_elmt_KmcactC12AcylCarCYT * elmt_CarMAT * (1.0 + (elmt_CarCYT / elmt_KicactCarCYT))) + ((elmt_Vfcact / (elmt_Vrcact * elmt_Keqcact)) * ((elmt_KmcactCarCYT * elmt_C12AcylCarMAT * (1.0 + (elmt_C12AcylCarCYT / elmt_vcactC12_elmt_KicactC12AcylCarCYT))) + (elmt_CarCYT * (elmt_vcactC12_elmt_KmcactC12AcylCarMAT + elmt_C12AcylCarMAT)))))));
        elmt_vmschadC12 = (((elmt_vmschadC12_elmt_sfmschadC12 * elmt_Vmschad * (((elmt_C12HydroxyacylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT)) / (elmt_KmmschadC12HydroxyacylCoAMAT * elmt_KmmschadNADMAT)) - ((elmt_C12KetoacylCoAMAT * elmt_NADHMAT) / (elmt_KmmschadC12HydroxyacylCoAMAT * elmt_KmmschadNADMAT * elmt_Keqmschad)))) / ((1.0 + (elmt_C12HydroxyacylCoAMAT / elmt_KmmschadC12HydroxyacylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmschadC12KetoacylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmmschadC16HydroxyacylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmschadC16KetoacylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmmschadC14HydroxyacylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmschadC14KetoacylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmmschadC10HydroxyacylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmschadC10KetoacylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmmschadC8HydroxyacylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmschadC8KetoacylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmmschadC6HydroxyacylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmschadC6KetoacylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmmschadC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmschadC4AcetoacylCoAMAT)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmschadNADMAT) + (elmt_NADHMAT / elmt_KmmschadNADHMAT)))));
        elmt_vvlcadC14 = (((elmt_vvlcadC14_elmt_sfvlcadC14 * elmt_Vvlcad * (((elmt_C14AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmvlcadC14AcylCoAMAT * elmt_KmvlcadFAD)) - ((elmt_C14EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmvlcadC14AcylCoAMAT * elmt_KmvlcadFAD * elmt_Keqvlcad)))) / ((1.0 + (elmt_C14AcylCoAMAT / elmt_KmvlcadC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmvlcadC14EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmvlcadC16AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmvlcadC16EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmvlcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmvlcadC12EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmvlcadFAD) + (elmt_FADHMAT / elmt_KmvlcadFADH)))));
        elmt_vvlcadC16 = (((elmt_vvlcadC16_elmt_sfvlcadC16 * elmt_Vvlcad * (((elmt_C16AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmvlcadC16AcylCoAMAT * elmt_KmvlcadFAD)) - ((elmt_C16EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmvlcadC16AcylCoAMAT * elmt_KmvlcadFAD * elmt_Keqvlcad)))) / ((1.0 + (elmt_C16AcylCoAMAT / elmt_KmvlcadC16AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmvlcadC16EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmvlcadC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmvlcadC14EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmvlcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmvlcadC12EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmvlcadFAD) + (elmt_FADHMAT / elmt_KmvlcadFADH)))));
        elmt_vcactC16 = (((elmt_Vfcact * ((elmt_C16AcylCarCYT * elmt_CarMAT) - ((elmt_C16AcylCarMAT * elmt_CarCYT) / elmt_Keqcact))) / ((elmt_C16AcylCarCYT * elmt_CarMAT) + (elmt_KmcactCarMAT * elmt_C16AcylCarCYT) + (elmt_vcactC16_elmt_KmcactC16AcylCarCYT * elmt_CarMAT * (1.0 + (elmt_CarCYT / elmt_KicactCarCYT))) + ((elmt_Vfcact / (elmt_Vrcact * elmt_Keqcact)) * ((elmt_KmcactCarCYT * elmt_C16AcylCarMAT * (1.0 + (elmt_C16AcylCarCYT / elmt_vcactC16_elmt_KicactC16AcylCarCYT))) + (elmt_CarCYT * (elmt_vcactC16_elmt_KmcactC16AcylCarMAT + elmt_C16AcylCarMAT)))))));
        elmt_vmschadC16 = (((elmt_vmschadC16_elmt_sfmschadC16 * elmt_Vmschad * (((elmt_C16HydroxyacylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT)) / (elmt_KmmschadC16HydroxyacylCoAMAT * elmt_KmmschadNADMAT)) - ((elmt_C16KetoacylCoAMAT * elmt_NADHMAT) / (elmt_KmmschadC16HydroxyacylCoAMAT * elmt_KmmschadNADMAT * elmt_Keqmschad)))) / ((1.0 + (elmt_C16HydroxyacylCoAMAT / elmt_KmmschadC16HydroxyacylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmschadC16KetoacylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmmschadC14HydroxyacylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmschadC14KetoacylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmmschadC12HydroxyacylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmschadC12KetoacylCoAMAT) + (elmt_C10HydroxyacylCoAMAT / elmt_KmmschadC10HydroxyacylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmschadC10KetoacylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmmschadC8HydroxyacylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmschadC8KetoacylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmmschadC6HydroxyacylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmschadC6KetoacylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmmschadC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmschadC4AcetoacylCoAMAT)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmschadNADMAT) + (elmt_NADHMAT / elmt_KmmschadNADHMAT)))));
        elmt_vnadhsink = ((elmt_vnadhsink_elmt_Ksnadhsink * (elmt_NADHMAT - elmt_vnadhsink_elmt_K1nadhsink)));
        elmt_vlcadC10 = (((elmt_vlcadC10_elmt_sflcadC10 * elmt_Vlcad * (((elmt_C10AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmlcadC10AcylCoAMAT * elmt_KmlcadFAD)) - ((elmt_C10EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmlcadC10AcylCoAMAT * elmt_KmlcadFAD * elmt_Keqlcad)))) / ((1.0 + (elmt_C10AcylCoAMAT / elmt_KmlcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmlcadC10EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmlcadC16AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmlcadC16EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmlcadC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmlcadC14EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmlcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmlcadC12EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmlcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmlcadC8EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmlcadFAD) + (elmt_FADHMAT / elmt_KmlcadFADH)))));
        elmt_vlcadC12 = (((elmt_vlcadC12_elmt_sflcadC12 * elmt_Vlcad * (((elmt_C12AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmlcadC12AcylCoAMAT * elmt_KmlcadFAD)) - ((elmt_C14EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmlcadC12AcylCoAMAT * elmt_KmlcadFAD * elmt_Keqlcad)))) / ((1.0 + (elmt_C12AcylCoAMAT / elmt_KmlcadC12AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmlcadC12EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmlcadC16AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmlcadC16EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmlcadC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmlcadC14EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmlcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmlcadC10EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmlcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmlcadC8EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmlcadFAD) + (elmt_FADHMAT / elmt_KmlcadFADH)))));
        elmt_vlcadC14 = (((elmt_vlcadC14_elmt_sflcadC14 * elmt_Vlcad * (((elmt_C14AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmlcadC14AcylCoAMAT * elmt_KmlcadFAD)) - ((elmt_C14EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmlcadC14AcylCoAMAT * elmt_KmlcadFAD * elmt_Keqlcad)))) / ((1.0 + (elmt_C14AcylCoAMAT / elmt_KmlcadC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmlcadC14EnoylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmlcadC16AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmlcadC16EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmlcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmlcadC12EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmlcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmlcadC10EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmlcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmlcadC8EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmlcadFAD) + (elmt_FADHMAT / elmt_KmlcadFADH)))));
        elmt_vfadhsink = ((elmt_vfadhsink_elmt_Ksfadhsink * (elmt_FADHMAT - elmt_vfadhsink_elmt_K1fadhsink)));
        elmt_vlcadC16 = (((elmt_vlcadC16_elmt_sflcadC16 * elmt_Vlcad * (((elmt_C16AcylCoAMAT * (elmt_FADtMAT - elmt_FADHMAT)) / (elmt_KmlcadC16AcylCoAMAT * elmt_KmlcadFAD)) - ((elmt_C16EnoylCoAMAT * elmt_FADHMAT) / (elmt_KmlcadC16AcylCoAMAT * elmt_KmlcadFAD * elmt_Keqlcad)))) / ((1.0 + (elmt_C16AcylCoAMAT / elmt_KmlcadC16AcylCoAMAT) + (elmt_C16EnoylCoAMAT / elmt_KmlcadC16EnoylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmlcadC14AcylCoAMAT) + (elmt_C14EnoylCoAMAT / elmt_KmlcadC14EnoylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmlcadC12AcylCoAMAT) + (elmt_C12EnoylCoAMAT / elmt_KmlcadC12EnoylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmlcadC10AcylCoAMAT) + (elmt_C10EnoylCoAMAT / elmt_KmlcadC10EnoylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmlcadC8AcylCoAMAT) + (elmt_C8EnoylCoAMAT / elmt_KmlcadC8EnoylCoAMAT)) * (1.0 + ((elmt_FADtMAT - elmt_FADHMAT) / elmt_KmlcadFAD) + (elmt_FADHMAT / elmt_KmlcadFADH)))));
        elmt_vmckatC10 = (((elmt_vmckatC10_elmt_sfmckatC10 * elmt_Vmckat * (((elmt_C10KetoacylCoAMAT * elmt_CoAMAT) / (elmt_KmmckatC10KetoacylCoAMAT * elmt_KmmckatCoAMAT)) - ((elmt_C8AcylCoAMAT * elmt_AcetylCoAMAT) / (elmt_KmmckatC10KetoacylCoAMAT * elmt_KmmckatCoAMAT * elmt_Keqmckat)))) / ((1.0 + (elmt_C10KetoacylCoAMAT / elmt_KmmckatC10KetoacylCoAMAT) + (elmt_C8AcylCoAMAT / elmt_KmmckatC8AcylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmckatC16KetoacylCoAMAT) + (elmt_C16AcylCoAMAT / elmt_KmmckatC16AcylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmckatC14KetoacylCoAMAT) + (elmt_C14AcylCoAMAT / elmt_KmmckatC14AcylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmckatC12KetoacylCoAMAT) + (elmt_C12AcylCoAMAT / elmt_KmmckatC12AcylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmckatC8KetoacylCoAMAT) + (elmt_C10AcylCoAMAT / elmt_KmmckatC10AcylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmckatC6KetoacylCoAMAT) + (elmt_C6AcylCoAMAT / elmt_KmmckatC6AcylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmckatC4AcetoacylCoAMAT) + (elmt_C4AcylCoAMAT / elmt_KmmckatC4AcylCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)) * (1.0 + (elmt_CoAMAT / elmt_KmmckatCoAMAT) + (elmt_AcetylCoAMAT / elmt_KmmckatAcetylCoAMAT)))));
        elmt_vcactC10 = (((elmt_Vfcact * ((elmt_C10AcylCarCYT * elmt_CarMAT) - ((elmt_C10AcylCarMAT * elmt_CarCYT) / elmt_Keqcact))) / ((elmt_C10AcylCarCYT * elmt_CarMAT) + (elmt_KmcactCarMAT * elmt_C10AcylCarCYT) + (elmt_vcactC10_elmt_KmcactC10AcylCarCYT * elmt_CarMAT * (1.0 + (elmt_CarCYT / elmt_KicactCarCYT))) + ((elmt_Vfcact / (elmt_Vrcact * elmt_Keqcact)) * ((elmt_KmcactCarCYT * elmt_C10AcylCarMAT * (1.0 + (elmt_C10AcylCarCYT / elmt_vcactC10_elmt_KicactC10AcylCarCYT))) + (elmt_CarCYT * (elmt_vcactC10_elmt_KmcactC10AcylCarMAT + elmt_C10AcylCarMAT)))))));
        elmt_vmschadC10 = (((elmt_vmschadC10_elmt_sfmschadC10 * elmt_Vmschad * (((elmt_C10HydroxyacylCoAMAT * (elmt_NADtMAT - elmt_NADHMAT)) / (elmt_KmmschadC10HydroxyacylCoAMAT * elmt_KmmschadNADMAT)) - ((elmt_C10KetoacylCoAMAT * elmt_NADHMAT) / (elmt_KmmschadC10HydroxyacylCoAMAT * elmt_KmmschadNADMAT * elmt_Keqmschad)))) / ((1.0 + (elmt_C10HydroxyacylCoAMAT / elmt_KmmschadC10HydroxyacylCoAMAT) + (elmt_C10KetoacylCoAMAT / elmt_KmmschadC10KetoacylCoAMAT) + (elmt_C16HydroxyacylCoAMAT / elmt_KmmschadC16HydroxyacylCoAMAT) + (elmt_C16KetoacylCoAMAT / elmt_KmmschadC16KetoacylCoAMAT) + (elmt_C14HydroxyacylCoAMAT / elmt_KmmschadC14HydroxyacylCoAMAT) + (elmt_C14KetoacylCoAMAT / elmt_KmmschadC14KetoacylCoAMAT) + (elmt_C12HydroxyacylCoAMAT / elmt_KmmschadC12HydroxyacylCoAMAT) + (elmt_C12KetoacylCoAMAT / elmt_KmmschadC12KetoacylCoAMAT) + (elmt_C8HydroxyacylCoAMAT / elmt_KmmschadC8HydroxyacylCoAMAT) + (elmt_C8KetoacylCoAMAT / elmt_KmmschadC8KetoacylCoAMAT) + (elmt_C6HydroxyacylCoAMAT / elmt_KmmschadC6HydroxyacylCoAMAT) + (elmt_C6KetoacylCoAMAT / elmt_KmmschadC6KetoacylCoAMAT) + (elmt_C4HydroxyacylCoAMAT / elmt_KmmschadC4HydroxyacylCoAMAT) + (elmt_C4AcetoacylCoAMAT / elmt_KmmschadC4AcetoacylCoAMAT)) * (1.0 + ((elmt_NADtMAT - elmt_NADHMAT) / elmt_KmmschadNADMAT) + (elmt_NADHMAT / elmt_KmmschadNADHMAT)))));
        der(elmt_product73) = 0;
        der(elmt_product72) = 0;
        der(elmt_reactant41) = 0;
        der(elmt_product77) = 0;
        der(elmt_reactant109) = 0;
        der(elmt_product75) = 0;
        der(elmt_reactant47) = 0;
        der(elmt_product70) = 0;
        der(elmt_reactant44) = 0;
        der(elmt_reactant118) = 0;
        der(elmt_product69) = 0;
        der(elmt_reactant115) = 0;
        der(elmt_reactant112) = 0;
        der(elmt_reactant50) = 0;
        der(elmt_product85) = 0;
        der(elmt_product83) = 0;
        der(elmt_reactant53) = 0;
        der(elmt_product89) = 0;
        der(elmt_product87) = 0;
        der(elmt_reactant59) = 0;
        der(elmt_product81) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_product102) = 0;
        der(elmt_reactant121) = 0;
        der(elmt_product101) = 0;
        der(elmt_product104) = 0;
        der(elmt_reactant129) = 0;
        der(elmt_reactant127) = 0;
        der(elmt_product79) = 0;
        der(elmt_reactant124) = 0;
        der(elmt_product105) = 0;
        der(elmt_product108) = 0;
        der(elmt_product107) = 0;
        der(elmt_product96) = 0;
        der(elmt_product95) = 0;
        der(elmt_product93) = 0;
        der(elmt_product12) = 0;
        der(elmt_product99) = 0;
        der(elmt_product10) = 0;
        der(elmt_product98) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_product92) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_product90) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product8) = 0;
        der(elmt_product6) = 0;
        der(elmt_product22) = 0;
        der(elmt_product20) = 0;
        der(elmt_product0) = 0;
        der(elmt_reactant38) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_product4) = 0;
        der(elmt_reactant35) = 0;
        der(elmt_product2) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_product16) = 0;
        der(elmt_reactant106) = 0;
        der(elmt_product14) = 0;
        der(elmt_reactant103) = 0;
        der(elmt_product18) = 0;
        der(elmt_reactant100) = 0;
        der(elmt_product30) = 0;
        der(elmt_reactant84) = 0;
        der(elmt_reactant86) = 0;
        der(elmt_product34) = 0;
        der(elmt_reactant80) = 0;
        der(elmt_product33) = 0;
        der(elmt_reactant82) = 0;
        der(elmt_product31) = 0;
        der(elmt_reactant88) = 0;
        der(elmt_product135) = 0;
        der(elmt_product134) = 0;
        der(elmt_product136) = 0;
        der(elmt_reactant151) = 0;
        der(elmt_product131) = 0;
        der(elmt_reactant150) = 0;
        der(elmt_product130) = 0;
        der(elmt_product132) = 0;
        der(elmt_product26) = 0;
        der(elmt_reactant9) = 0;
        der(elmt_product24) = 0;
        der(elmt_product139) = 0;
        der(elmt_product138) = 0;
        der(elmt_product28) = 0;
        der(elmt_reactant94) = 0;
        der(elmt_product40) = 0;
        der(elmt_reactant97) = 0;
        der(elmt_product45) = 0;
        der(elmt_reactant91) = 0;
        der(elmt_product43) = 0;
        der(elmt_product42) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_product140) = 0;
        der(elmt_reactant17) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_product146) = 0;
        der(elmt_product148) = 0;
        der(elmt_product147) = 0;
        der(elmt_product142) = 0;
        der(elmt_product144) = 0;
        der(elmt_product143) = 0;
        der(elmt_product37) = 0;
        der(elmt_product36) = 0;
        der(elmt_product39) = 0;
        der(elmt_product52) = 0;
        der(elmt_product51) = 0;
        der(elmt_reactant62) = 0;
        der(elmt_product55) = 0;
        der(elmt_product54) = 0;
        der(elmt_reactant65) = 0;
        der(elmt_reactant68) = 0;
        der(elmt_product113) = 0;
        der(elmt_product114) = 0;
        der(elmt_product111) = 0;
        der(elmt_product110) = 0;
        der(elmt_product49) = 0;
        der(elmt_product48) = 0;
        der(elmt_reactant137) = 0;
        der(elmt_product46) = 0;
        der(elmt_product117) = 0;
        der(elmt_product116) = 0;
        der(elmt_product119) = 0;
        der(elmt_reactant133) = 0;
        der(elmt_product63) = 0;
        der(elmt_reactant1) = 0;
        der(elmt_reactant74) = 0;
        der(elmt_product61) = 0;
        der(elmt_product60) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_product67) = 0;
        der(elmt_product66) = 0;
        der(elmt_reactant5) = 0;
        der(elmt_reactant71) = 0;
        der(elmt_product64) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_reactant76) = 0;
        der(elmt_reactant78) = 0;
        der(elmt_product123) = 0;
        der(elmt_reactant141) = 0;
        der(elmt_product126) = 0;
        der(elmt_product125) = 0;
        der(elmt_product120) = 0;
        der(elmt_product122) = 0;
        der(elmt_reactant149) = 0;
        der(elmt_product58) = 0;
        der(elmt_product57) = 0;
        der(elmt_product128) = 0;
        der(elmt_reactant145) = 0;

end Reactions;
