within BIOMD213;
model Folate2004 "Nijhout2004_Folate_Cycle" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_compartment elmt_compartment;

    equation
        Reacs.elmt_TS_Km_5_10_CH2THF = Params.elmt_TS_Km_5_10_CH2THF;
        Reacs.elmt_SHMT_Km_Ser = Params.elmt_SHMT_Km_Ser;
        Reacs.elmt_DHFR_Km_NADPH = Params.elmt_DHFR_Km_NADPH;
        Reacs.elmt_GAR = elmt_compartment.elmt_GAR;
        Reacs.elmt_PGT_Vmax = Params.elmt_PGT_Vmax;
        Reacs.elmt_dUMP = elmt_compartment.elmt_dUMP;
        Reacs.elmt_Ser = elmt_compartment.elmt_Ser;
        Reacs.elmt_Hcy = elmt_compartment.elmt_Hcy;
        Reacs.elmt_DHFR_Km_DHF = Params.elmt_DHFR_Km_DHF;
        Reacs.elmt_MTD_Km_5_10_CH2THF = Params.elmt_MTD_Km_5_10_CH2THF;
        Reacs.elmt_DHF = elmt_compartment.elmt_DHF;
        Reacs.elmt_FTD_Km_10fTHF = Params.elmt_FTD_Km_10fTHF;
        Reacs.elmt_HCOOH = elmt_compartment.elmt_HCOOH;
        Reacs.elmt_TS_Vmax = Params.elmt_TS_Vmax;
        Reacs.elmt_THF = elmt_compartment.elmt_THF;
        Reacs.elmt_AICART_Km_AICAR = Params.elmt_AICART_Km_AICAR;
        Reacs.elmt_NADPH = elmt_compartment.elmt_NADPH;
        Reacs.elmt_NE_k2 = Params.elmt_NE_k2;
        Reacs.elmt_NE_k1 = Params.elmt_NE_k1;
        Reacs.elmt_MTHFR_Km_NADPH = Params.elmt_MTHFR_Km_NADPH;
        Reacs.elmt_MS_Km_Hcy = Params.elmt_MS_Km_Hcy;
        Reacs.elmt_AICART_Km_10fTHF = Params.elmt_AICART_Km_10fTHF;
        Reacs.elmt_MS_Vmax = Params.elmt_MS_Vmax;
        Reacs.elmt_PGT_Km_GAR = Params.elmt_PGT_Km_GAR;
        Reacs.elmt_FTS_Km_HCOOH = Params.elmt_FTS_Km_HCOOH;
        Reacs.elmt_AICAR = elmt_compartment.elmt_AICAR;
        Reacs.elmt__5mTHF = elmt_compartment.elmt__5mTHF;
        Reacs.elmt_FTS_Vmax = Params.elmt_FTS_Vmax;
        Reacs.elmt_MS_Km_5mTHF = Params.elmt_MS_Km_5mTHF;
        Reacs.elmt_FTS_Km_THF = Params.elmt_FTS_Km_THF;
        Reacs.elmt_MS_Kd = Params.elmt_MS_Kd;
        Reacs.elmt_MTCH_VmaxF = Params.elmt_MTCH_VmaxF;
        Reacs.elmt_AICART_Vmax = Params.elmt_AICART_Vmax;
        Reacs.elmt_MTCH_Km_5_10_CHTHF = Params.elmt_MTCH_Km_5_10_CHTHF;
        Reacs.elmt_MTD_Km_5_10_CHTHF = Params.elmt_MTD_Km_5_10_CHTHF;
        Reacs.elmt_Gly = elmt_compartment.elmt_Gly;
        Reacs.elmt_MTD_VmaxR = Params.elmt_MTD_VmaxR;
        Reacs.elmt__5_10_CHTHF = elmt_compartment.elmt__5_10_CHTHF;
        Reacs.elmt_PGT_Km_10fTHF = Params.elmt_PGT_Km_10fTHF;
        Reacs.elmt__5_10_CH2THF = elmt_compartment.elmt__5_10_CH2THF;
        Reacs.elmt_MTCH_Km_10fTHF = Params.elmt_MTCH_Km_10fTHF;
        Reacs.elmt_MTCH_VmaxR = Params.elmt_MTCH_VmaxR;
        Reacs.elmt_SHMT_VmaxF = Params.elmt_SHMT_VmaxF;
        Reacs.elmt_SHMT_Km_THF = Params.elmt_SHMT_Km_THF;
        Reacs.elmt_FTD_Vmax = Params.elmt_FTD_Vmax;
        Reacs.elmt_MTD_VmaxF = Params.elmt_MTD_VmaxF;
        Reacs.elmt__10fTHF = elmt_compartment.elmt__10fTHF;
        Reacs.elmt_MTHFR_Km_5_10_CH2THF = Params.elmt_MTHFR_Km_5_10_CH2THF;
        Reacs.elmt_SHMT_VmaxR = Params.elmt_SHMT_VmaxR;
        Reacs.elmt_TS_Km_dUMP = Params.elmt_TS_Km_dUMP;
        Reacs.elmt_DHFR_Vmax = Params.elmt_DHFR_Vmax;
        Reacs.elmt_MTHFR_Vmax = Params.elmt_MTHFR_Vmax;
        elmt_compartment.elmt_V_TS = Reacs.elmt_V_TS;
        elmt_compartment.elmt_reactant20 = Reacs.elmt_reactant20;
        elmt_compartment.elmt_product11 = Reacs.elmt_product11;
        elmt_compartment.elmt_V_DHFR = Reacs.elmt_V_DHFR;
        elmt_compartment.elmt_V_NE = Reacs.elmt_V_NE;
        elmt_compartment.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_compartment.elmt_V_FTD = Reacs.elmt_V_FTD;
        elmt_compartment.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_compartment.elmt_V_MTCH = Reacs.elmt_V_MTCH;
        elmt_compartment.elmt_V_MS = Reacs.elmt_V_MS;
        elmt_compartment.elmt_reactant2 = Reacs.elmt_reactant2;
        elmt_compartment.elmt_product9 = Reacs.elmt_product9;
        elmt_compartment.elmt_V_SHMT = Reacs.elmt_V_SHMT;
        elmt_compartment.elmt_product7 = Reacs.elmt_product7;
        elmt_compartment.elmt_reactant4 = Reacs.elmt_reactant4;
        elmt_compartment.elmt_V_FTS = Reacs.elmt_V_FTS;
        elmt_compartment.elmt_product23 = Reacs.elmt_product23;
        elmt_compartment.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_compartment.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_compartment.elmt_product21 = Reacs.elmt_product21;
        elmt_compartment.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_compartment.elmt_product1 = Reacs.elmt_product1;
        elmt_compartment.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_compartment.elmt_product5 = Reacs.elmt_product5;
        elmt_compartment.elmt_reactant10 = Reacs.elmt_reactant10;
        elmt_compartment.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_compartment.elmt_product3 = Reacs.elmt_product3;
        elmt_compartment.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_compartment.elmt_V_MTHFR = Reacs.elmt_V_MTHFR;
        elmt_compartment.elmt_V_PGT = Reacs.elmt_V_PGT;
        elmt_compartment.elmt_V_MTD = Reacs.elmt_V_MTD;
        elmt_compartment.elmt_V_AICART = Reacs.elmt_V_AICART;
        elmt_compartment.elmt_product15 = Reacs.elmt_product15;
        elmt_compartment.elmt_product13 = Reacs.elmt_product13;
        elmt_compartment.elmt_product19 = Reacs.elmt_product19;
        elmt_compartment.elmt_product17 = Reacs.elmt_product17;

end Folate2004;
