formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s : %(message)s'
handlers:
  Zeilinger2006_PRR7_PRR9_Y_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/S2MResult/S2MBIOMDx8095/log/Zeilinger2006_PRR7_PRR9_Y.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    formatter: simple
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  Zeilinger2006_PRR7_PRR9_Y:
    handlers:
    - Zeilinger2006_PRR7_PRR9_Y_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
