modelica2gpu:
  generateXML: False # True se serve generare l'XML, oppure False per utilizzare uno già generato
  xml: /home/yorunoomo/Scrivania/Tirocinio/modelica2MPGOSgpuPython/src/XMLs/BouncingBall.xml # null se vogliamo far generare l'XML, altrimenti il path assoluto al file
  workingdir: /home/yorunoomo/Scrivania/Tirocinio/modelica2MPGOSgpuPython/src # il path assoluto alla directory che presenta i file modelica
  modelfilename: null # Il nome del modello (serve in quanto dovrà andare come primo file al compilatore)
  notifier: False # True se si vogliono attivare le notifiche, False altrimenti
  filelogger: True # True se si vuole attivare il logger su file (oltre che console per default)
builder:
  MPGOSsourcedir: /home/yorunoomo/Scrivania/Tirocinio/util/Software/MPGOS/SourceCodes/ # path assoluto alla cartella SourceCode di MPGOS
  usedefaultoptions: True # True se si vogliono utilizzare le impostazioni di default per gpu, NT, NP, NDO, False altrimenti
  gpu:
    major: null # il numero major di versione della CUDA capability (null per default)
    minor: null # il numero minor di versione della CUDA capability (null per default)
  modeldefinition:
    numberOfProblems: null # Numero di problemi da risolvere (null per deafault)
    numberOfThreads: null # Numero di Thred da utilizzare (null per default)
    numberOfDenseOutput: null # Numero di Denseoutput da salvare (null per default)
    threadsPerBlock: null
    preferSharedMemory: null
    maximumTimeStep: null
    minimumTimeStep: null
    timeStepGrowLimit: null
    timeStepShrinkLimit: null
    eventDirection: 
      valueEvent1: 0
      valueEvent2: 0
    denseOutputMinimumTimeStep: null
    denseOutputSaveFrequency: null

# NOTA: se usedefaultoption è False, allora tutti campi di builder devono essere diversi da null.
# NOTA: eventDirection deve essere sempre inserito ed il numero di valori deve coincidere con il numero degli eventi nel modello
