modelica2gpu:
  generateXML: True
  workingdir: /home/yorunoomo/Scrivania/Tirocinio/S2MResult/S2MBIOMDx8095
  modelfilename: /home/yorunoomo/Scrivania/Tirocinio/S2MResult/S2MBIOMDx8095/Goldbeter1995.mo
  notifier: True
  filelogger: True
  usedefaultoptions: True
builder:
  gpu:
    major: 6
    minor: 1
  modeldefinition:
    numberOfProblems: null
    numberOfThreads: null
    numberOfDenseOutput: null