modelica2gpu:
  generateXML: True # True se serve generare l'XML, oppure utilizzare uno già generato
  xml: null # null se vogliamo far generare l'XML, altrimenti il path assoluto al file
  workingdir: /home/yorunoomo/Scrivania/Tirocinio/S2MResult/S2MBIOMDx8095 # il path assoluto alla directory che presenta i file modelica
  modelfilename: Goldbeter1995.mo # Il nome del modello (serve in quanto dovrà andare come primo file al compilatore)
  notifier: True # True se si vogliono attivare le notifiche, False altrimenti
  filelogger: True # True se si vuole attivare il logger su file (oltre che console per default)
builder:
  usedefaultoptions: True # True se si vogliono utilizzare le impostazioni di default per gpu, NT, NP, NDO, False altrimenti
  gpu:
    major: null # il numero major di versione della CUDA capability (null per default)
    minor: null # il numero minor di versione della CUDA capability (null per default)
  modeldefinition:
    numberOfProblems: null # Numero di problemi da risolvere (null per deafault)
    numberOfThreads: null # Numero di Thred da utilizzare (null per default)
    numberOfDenseOutput: null # Numero di Denseoutput da salvare (null per default)

# NOTA: se usedefaultoption è False, allora tutti campi di builder devono essere diversi da null.