within BIOMD257;
class Reactions

    input Real elmt_STUS;
    input Real elmt_SUST;
    input Real elmt_k5r;
    input Real elmt_k7r;
    input Real elmt_k9r;
    input Real elmt_U;
    input Real elmt_S;
    input Real elmt_k1r;
    input Real elmt_T;
    input Real elmt_k10r;
    input Real elmt_k11;
    input Real elmt_k3r;
    input Real elmt_k10;
    input Real elmt_SUSTU;
    input Real elmt_k1;
    input Real elmt_STU;
    input Real elmt_STUST;
    input Real elmt_ST;
    input Real elmt_SU;
    input Real elmt_STUSU;
    input Real elmt_k8;
    input Real elmt_k9;
    input Real elmt_k6;
    input Real elmt_k7;
    input Real elmt_k4;
    input Real elmt_k5;
    input Real elmt_k2;
    input Real elmt_k3;
    input Real elmt_k6r;
    input Real elmt_env;
    input Real elmt_k2r;

    Real elmt_reaction7(unit = "") "";
    Real elmt_reactant16 "";
    Real elmt_product18 "";
    Real elmt_product17 "";
    Real elmt_reaction6(unit = "") "";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_reactant13 "";
    Real elmt_reaction9(unit = "") "";
    Real elmt_reactant20 "";
    Real elmt_product22 "";
    Real elmt_reactant21 "";
    Real elmt_reaction8(unit = "") "";
    Real elmt_reactant19 "";
    Real elmt_reaction3(unit = "") "";
    Real elmt_product8 "";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_reaction2(unit = "") "";
    Real elmt_reactant4 "";
    Real elmt_reactant3 "";
    Real elmt_product5 "";
    Real elmt_reaction5(unit = "") "";
    Real elmt_product12 "";
    Real elmt_reactant10 "";
    Real elmt_reactant11 "";
    Real elmt_reaction4(unit = "") "";
    Real elmt_reactant9 "";
    Real elmt_reaction1(unit = "") "";
    Real elmt_reactant1 "";
    Real elmt_reactant0 "";
    Real elmt_product2 "";
    Real elmt_reaction10(unit = "") "";
    Real elmt_product25 "";
    Real elmt_product24 "";
    Real elmt_reactant23 "";
    Real elmt_reaction11(unit = "") "";
    Real elmt_reactant26 "";


    initial equation
        elmt_reactant20 = 1.0;
        elmt_product12 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_reactant9 = 1.0;
        elmt_product25 = 1.0;
        elmt_product24 = 1.0;
        elmt_product8 = 1.0;
        elmt_reactant1 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product22 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_product2 = 1.0;
        elmt_product15 = 1.0;
        elmt_product18 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_reaction7 = (elmt_env * ((elmt_k7 * elmt_SUSTU) - (elmt_k7r * elmt_STU * elmt_SU)));
        elmt_reaction6 = (elmt_env * ((elmt_k6 * elmt_U * elmt_SUST) - (elmt_k6r * elmt_SUSTU)));
        elmt_reaction9 = (elmt_env * ((elmt_k9 * elmt_U * elmt_STUS) - (elmt_k9r * elmt_STUSU)));
        elmt_reaction8 = (elmt_env * elmt_k8 * elmt_SU);
        elmt_reaction3 = (elmt_env * ((elmt_k3 * elmt_STUST) - (elmt_k3r * elmt_ST * elmt_STU)));
        elmt_reaction2 = (elmt_env * ((elmt_k2 * elmt_T * elmt_STUS) - (elmt_k2r * elmt_STUST)));
        elmt_reaction5 = (elmt_env * ((elmt_k5 * elmt_ST * elmt_SU) - (elmt_k5r * elmt_SUST)));
        elmt_reaction4 = (elmt_env * elmt_k4 * elmt_STU);
        elmt_reaction1 = (elmt_env * ((elmt_k1 * elmt_S * elmt_STU) - (elmt_k1r * elmt_STUS)));
        elmt_reaction10 = (elmt_env * ((elmt_k10 * elmt_STUSU) - (elmt_k10r * elmt_STU * elmt_SU)));
        elmt_reaction11 = (elmt_env * elmt_k11 * elmt_ST);
        der(elmt_reactant20) = 0;
        der(elmt_product12) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_reactant9) = 0;
        der(elmt_product25) = 0;
        der(elmt_product24) = 0;
        der(elmt_product8) = 0;
        der(elmt_reactant1) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product22) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_product2) = 0;
        der(elmt_product15) = 0;
        der(elmt_product18) = 0;
        der(elmt_product17) = 0;

end Reactions;
