within BIOMD298;
class Parameters

    input Real elmt_P1;
    input Real elmt_P2;
    input Real elmt_P0;
    input Real elmt_CN;
    input Real elmt_C;

    Real elmt_KdP(unit = "") "KdP";
    Real elmt_V2T(unit = "") "V2T";
    Real elmt_vsT(unit = "") "vsT";
    Real elmt_V4T(unit = "") "V4T";
    Real elmt_KIT(unit = "") "KIT";
    Real elmt_n(unit = "") "n";
    Real elmt_V2P(unit = "") "V2P";
    Real elmt_vsP(unit = "") "vsP";
    Real elmt_V4P(unit = "") "V4P";
    Real elmt_KIP(unit = "") "KIP";
    Real elmt_vmT(unit = "") "vmT";
    Real elmt_KdT(unit = "") "KdT";
    Real elmt_vmP(unit = "") "vmP";
    Real elmt_K3P(unit = "") "K3P";
    Real elmt_KmP(unit = "") "KmP";
    Real elmt_K1T(unit = "") "K1T";
    Real elmt_K3T(unit = "") "K3T";
    Real elmt_kdC(unit = "") "kdC";
    Real elmt_K1P(unit = "") "K1P";
    Real elmt_k1(unit = "") "k1";
    Real elmt_V3T(unit = "") "V3T";
    Real elmt_Pt(unit = "") "Pt";
    Real elmt_kdN(unit = "") "kdN";
    Real elmt_V1P(unit = "") "V1P";
    Real elmt_V3P(unit = "") "V3P";
    Real elmt_KmT(unit = "") "KmT";
    Real elmt_k4(unit = "") "k4";
    Real elmt_k2(unit = "") "k2";
    Real elmt_k3(unit = "") "k3";
    Real elmt_V1T(unit = "") "V1T";
    Real elmt_ksP(unit = "") "ksP";
    Real elmt_K4P(unit = "") "K4P";
    Real elmt_vdT(unit = "") "vdT";
    Real elmt_vdP(unit = "") "vdP";
    Real elmt_K2T(unit = "") "K2T";
    Real elmt_ksT(unit = "") "ksT";
    Real elmt_kd(unit = "") "kd";
    Real elmt_K4T(unit = "") "K4T";
    Real elmt_K2P(unit = "") "K2P";


    initial equation
        elmt_KdP = 0.2;
        elmt_V2T = 1.0;
        elmt_vsT = 1.0;
        elmt_V4T = 1.0;
        elmt_KIT = 1.0;
        elmt_n = 4.0;
        elmt_V2P = 1.0;
        elmt_vsP = 1.1;
        elmt_V4P = 1.0;
        elmt_KIP = 1.0;
        elmt_vmT = 0.7;
        elmt_KdT = 0.2;
        elmt_vmP = 1.0;
        elmt_K3P = 2.0;
        elmt_KmP = 0.2;
        elmt_K1T = 2.0;
        elmt_K3T = 2.0;
        elmt_kdC = 0.01;
        elmt_K1P = 2.0;
        elmt_k1 = 0.8;
        elmt_V3T = 8.0;
        elmt_kdN = 0.01;
        elmt_V1P = 8.0;
        elmt_V3P = 8.0;
        elmt_KmT = 0.2;
        elmt_k4 = 0.6;
        elmt_k2 = 0.2;
        elmt_k3 = 1.2;
        elmt_V1T = 8.0;
        elmt_ksP = 0.9;
        elmt_K4P = 2.0;
        elmt_vdT = 3.0;
        elmt_vdP = 2.2;
        elmt_K2T = 2.0;
        elmt_ksT = 0.9;
        elmt_kd = 0.01;
        elmt_K4T = 2.0;
        elmt_K2P = 2.0;


    equation
        der(elmt_KdP) = 0;
        der(elmt_V2T) = 0;
        der(elmt_vsT) = 0;
        der(elmt_V4T) = 0;
        der(elmt_KIT) = 0;
        der(elmt_n) = 0;
        der(elmt_V2P) = 0;
        der(elmt_vsP) = 0;
        der(elmt_V4P) = 0;
        der(elmt_KIP) = 0;
        der(elmt_vmT) = 0;
        der(elmt_KdT) = 0;
        der(elmt_vmP) = 0;
        der(elmt_K3P) = 0;
        der(elmt_KmP) = 0;
        der(elmt_K1T) = 0;
        der(elmt_K3T) = 0;
        der(elmt_kdC) = 0;
        der(elmt_K1P) = 0;
        der(elmt_k1) = 0;
        der(elmt_V3T) = 0;
        elmt_Pt = (elmt_P0 + elmt_P1 + elmt_P2 + elmt_C + elmt_CN);
        der(elmt_kdN) = 0;
        der(elmt_V1P) = 0;
        der(elmt_V3P) = 0;
        der(elmt_KmT) = 0;
        der(elmt_k4) = 0;
        der(elmt_k2) = 0;
        der(elmt_k3) = 0;
        der(elmt_V1T) = 0;
        der(elmt_ksP) = 0;
        der(elmt_K4P) = 0;
        der(elmt_vdT) = 0;
        der(elmt_vdP) = 0;
        der(elmt_K2T) = 0;
        der(elmt_ksT) = 0;
        der(elmt_kd) = 0;
        der(elmt_K4T) = 0;
        der(elmt_K2P) = 0;

end Parameters;
