/* Events: Sample, Zero Crossings, Relations, Discrete Changes */
/* Simulation code for System generated by the OpenModelica Compiler 1.9.2 (r25115). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "System_functions.h"
#include "System_model.h"
#include "System_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#if defined(__cplusplus)
extern "C" {
#endif

/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void System_function_initSample(DATA *data)
{
  long i=0;
}

const char *System_zeroCrossingDescription(int i, int **out_EquationIndexes)
{
  static const char *res[] = {"x >= 0.0"};
  static const int occurEqs0[] = {1,3};
  static const int *occurEqs[] = {occurEqs0};
  *out_EquationIndexes = (int*) occurEqs[i];
  return res[i];
}

/* forwarded equations */
extern void System_eqFunction_3(DATA* data);

int System_function_ZeroCrossingsEquations(DATA *data)
{
  TRACE_PUSH
  
  data->simulationInfo.callStatistics.functionZeroCrossingsEquations++;
  
  data->simulationInfo.discreteCall = 0;
  System_eqFunction_3(data);
  
  TRACE_POP
  return 0;
}

int System_function_ZeroCrossings(DATA *data, double *gout)
{
  TRACE_PUSH
  modelica_boolean tmp1006;
  
  data->simulationInfo.callStatistics.functionZeroCrossings++;
  
  tmp1006 = GreaterEqZC($Px, 0.0, data->simulationInfo.storedRelations[0]);
  gout[0] = (tmp1006) ? 1 : -1;
  
  TRACE_POP
  return 0;
}

const char *System_relationDescription(int i)
{
  const char *res[] = {"x >= 0.0"};
  return res[i];
}

int System_function_updateRelations(DATA *data, int evalforZeroCross)
{
  TRACE_PUSH
  modelica_boolean tmp1007;
  
  
  if(evalforZeroCross)
  {
    tmp1007 = GreaterEqZC($Px, 0.0, data->simulationInfo.storedRelations[0]);
    data->simulationInfo.relations[0] = tmp1007;
  }
  else
  {
    data->simulationInfo.relations[0] = ($Px >= 0.0);
  }
  
  TRACE_POP
  return 0;
}

int System_checkForDiscreteChanges(DATA *data)
{
  TRACE_PUSH
  int needToIterate = 0;

  infoStreamPrint(LOG_EVENTS_V, 1, "check for discrete changes at time=%.12g", data->localData[0]->timeValue);
  if (ACTIVE_STREAM(LOG_EVENTS_V)) messageClose(LOG_EVENTS_V);
  
  TRACE_POP
  return needToIterate;
}

#if defined(__cplusplus)
}
#endif

