within BIOMD365;
class Reactions

    input Real elmt_Va536_APC;
    input Real elmt_Va_APC;
    input Real elmt_APC;
    input Real elmt_Va36_APC;
    input Real elmt_Va;
    input Real elmt_Va3_APC;
    input Real elmt_Va3;
    input Real elmt_Va53_APC;
    input Real elmt_VaA53;
    input Real elmt_Va5_APC;
    input Real elmt_VaA536;
    input Real elmt_Va56_APC;
    input Real elmt_compartment_1;
    input Real elmt_VaA36;
    input Real elmt_HC;
    input Real elmt_Va5;
    input Real elmt_LC;
    input Real elmt_k10;
    input Real elmt_VaLCA1_APC;
    input Real elmt_k1;
    input Real elmt_Va53;
    input Real elmt_HC3;
    input Real elmt_LC_APC;
    input Real elmt_Va36;
    input Real elmt_Va56;
    input Real elmt_k8;
    input Real elmt_k9;
    input Real elmt_k6;
    input Real elmt_k7;
    input Real elmt_Va536;
    input Real elmt_k5;
    input Real elmt_k2;
    input Real elmt_VaLCA1;
    input Real elmt_k3;
    input Real elmt_HC5;
    input Real elmt_HC536;
    input Real elmt_VaA3;
    input Real elmt_HC56;
    input Real elmt_HC36;
    input Real elmt_HC53;

    Real elmt_r7(unit = "") "r7";
    Real elmt_reactant18 "";
    Real elmt_reactant19 "";
    Real elmt_product20 "";
    Real elmt_r28(unit = "") "r28";
    Real elmt_reactant72 "";
    Real elmt_product74 "";
    Real elmt_product73 "";
    Real elmt_r8(unit = "") "r8";
    Real elmt_product22 "";
    Real elmt_reactant21 "";
    Real elmt_r27(unit = "") "r27";
    Real elmt_product71 "";
    Real elmt_reactant69 "";
    Real elmt_product70 "";
    Real elmt_r5(unit = "") "r5";
    Real elmt_product14 "";
    Real elmt_reactant12 "";
    Real elmt_reactant13 "";
    Real elmt_r26(unit = "") "r26";
    Real elmt_product67 "";
    Real elmt_product68 "";
    Real elmt_reactant66 "";
    Real elmt_r6(unit = "") "r6";
    Real elmt_reactant15 "";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_r25(unit = "") "r25";
    Real elmt_reactant63 "";
    Real elmt_product65 "";
    Real elmt_product64 "";
    Real elmt_r3(unit = "") "r3";
    Real elmt_product8 "";
    Real elmt_reactant6 "";
    Real elmt_reactant7 "";
    Real elmt_r24(unit = "") "r24";
    Real elmt_reactant61 "";
    Real elmt_product62 "";
    Real elmt_reactant60 "";
    Real elmt_r4(unit = "") "r4";
    Real elmt_product11 "";
    Real elmt_reactant9 "";
    Real elmt_reactant10 "";
    Real elmt_r23(unit = "") "r23";
    Real elmt_product59 "";
    Real elmt_product58 "";
    Real elmt_reactant57 "";
    Real elmt_r1(unit = "") "r1";
    Real elmt_reactant1 "";
    Real elmt_reactant0 "";
    Real elmt_product2 "";
    Real elmt_r22(unit = "") "r22";
    Real elmt_product56 "";
    Real elmt_product55 "";
    Real elmt_reactant54 "";
    Real elmt_r2(unit = "") "r2";
    Real elmt_reactant4 "";
    Real elmt_reactant3 "";
    Real elmt_product5 "";
    Real elmt_r21(unit = "") "r21";
    Real elmt_product52 "";
    Real elmt_reactant51 "";
    Real elmt_product53 "";
    Real elmt_r9(unit = "") "r9";
    Real elmt_product24 "";
    Real elmt_reactant23 "";
    Real elmt_r29(unit = "") "r29";
    Real elmt_reactant75 "";
    Real elmt_product77 "";
    Real elmt_product76 "";
    Real elmt_r31(unit = "") "r31";
    Real elmt_product83 "";
    Real elmt_product82 "";
    Real elmt_reactant81 "";
    Real elmt_r30(unit = "") "r30";
    Real elmt_product79 "";
    Real elmt_product80 "";
    Real elmt_reactant78 "";
    Real elmt_r17(unit = "") "r17";
    Real elmt_product41 "";
    Real elmt_product40 "";
    Real elmt_reactant39 "";
    Real elmt_r16(unit = "") "r16";
    Real elmt_product38 "";
    Real elmt_reactant37 "";
    Real elmt_r15(unit = "") "r15";
    Real elmt_product36 "";
    Real elmt_reactant35 "";
    Real elmt_r14(unit = "") "r14";
    Real elmt_product34 "";
    Real elmt_reactant33 "";
    Real elmt_r13(unit = "") "r13";
    Real elmt_reactant31 "";
    Real elmt_product32 "";
    Real elmt_r12(unit = "") "r12";
    Real elmt_product30 "";
    Real elmt_reactant29 "";
    Real elmt_r11(unit = "") "r11";
    Real elmt_reactant27 "";
    Real elmt_product28 "";
    Real elmt_r33(unit = "") "r33";
    Real elmt_product89 "";
    Real elmt_reactant87 "";
    Real elmt_reactant88 "";
    Real elmt_r10(unit = "") "r10";
    Real elmt_reactant25 "";
    Real elmt_product26 "";
    Real elmt_r32(unit = "") "r32";
    Real elmt_product85 "";
    Real elmt_reactant84 "";
    Real elmt_product86 "";
    Real elmt_r19(unit = "") "r19";
    Real elmt_product47 "";
    Real elmt_product46 "";
    Real elmt_reactant45 "";
    Real elmt_r18(unit = "") "r18";
    Real elmt_reactant42 "";
    Real elmt_product44 "";
    Real elmt_product43 "";
    Real elmt_r20(unit = "") "r20";
    Real elmt_product50 "";
    Real elmt_product49 "";
    Real elmt_reactant48 "";


    initial equation
        elmt_product74 = 1.0;
        elmt_product30 = 1.0;
        elmt_product73 = 1.0;
        elmt_reactant84 = 1.0;
        elmt_product71 = 1.0;
        elmt_reactant42 = 1.0;
        elmt_product34 = 1.0;
        elmt_product77 = 1.0;
        elmt_product76 = 1.0;
        elmt_reactant81 = 1.0;
        elmt_product32 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_product70 = 1.0;
        elmt_reactant87 = 1.0;
        elmt_reactant88 = 1.0;
        elmt_reactant45 = 1.0;
        elmt_reactant9 = 1.0;
        elmt_product26 = 1.0;
        elmt_product68 = 1.0;
        elmt_product24 = 1.0;
        elmt_product28 = 1.0;
        elmt_product41 = 1.0;
        elmt_product85 = 1.0;
        elmt_reactant51 = 1.0;
        elmt_product40 = 1.0;
        elmt_product83 = 1.0;
        elmt_product82 = 1.0;
        elmt_product89 = 1.0;
        elmt_product44 = 1.0;
        elmt_product43 = 1.0;
        elmt_product86 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant54 = 1.0;
        elmt_product80 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_reactant57 = 1.0;
        elmt_product38 = 1.0;
        elmt_product36 = 1.0;
        elmt_product79 = 1.0;
        elmt_reactant61 = 1.0;
        elmt_product52 = 1.0;
        elmt_reactant63 = 1.0;
        elmt_product50 = 1.0;
        elmt_product56 = 1.0;
        elmt_product11 = 1.0;
        elmt_product55 = 1.0;
        elmt_reactant60 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant69 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant66 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product49 = 1.0;
        elmt_product47 = 1.0;
        elmt_product46 = 1.0;
        elmt_reactant72 = 1.0;
        elmt_product8 = 1.0;
        elmt_product62 = 1.0;
        elmt_reactant1 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_reactant75 = 1.0;
        elmt_reactant31 = 1.0;
        elmt_product67 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product22 = 1.0;
        elmt_product65 = 1.0;
        elmt_product20 = 1.0;
        elmt_product64 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_reactant37 = 1.0;
        elmt_reactant39 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant33 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant78 = 1.0;
        elmt_product2 = 1.0;
        elmt_reactant35 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_product59 = 1.0;
        elmt_product14 = 1.0;
        elmt_product58 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_r7 = (elmt_compartment_1 * ((elmt_k1 * elmt_Va536 * elmt_APC) - (elmt_k2 * elmt_Va536_APC)));
        elmt_r28 = (elmt_compartment_1 * ((elmt_k7 * elmt_Va536) - (elmt_k8 * elmt_VaA536 * elmt_VaLCA1)));
        elmt_r8 = (elmt_compartment_1 * elmt_k5 * elmt_Va_APC);
        elmt_r27 = (elmt_compartment_1 * ((elmt_k7 * elmt_Va36) - (elmt_k8 * elmt_VaA36 * elmt_VaLCA1)));
        elmt_r5 = (elmt_compartment_1 * ((elmt_k1 * elmt_Va56 * elmt_APC) - (elmt_k2 * elmt_Va56_APC)));
        elmt_r26 = (elmt_compartment_1 * ((elmt_k7 * elmt_Va53) - (elmt_k8 * elmt_VaA53 * elmt_VaLCA1)));
        elmt_r6 = (elmt_compartment_1 * ((elmt_k1 * elmt_Va36 * elmt_APC) - (elmt_k2 * elmt_Va36_APC)));
        elmt_r25 = (elmt_compartment_1 * ((elmt_k7 * elmt_Va3) - (elmt_k8 * elmt_VaA3 * elmt_VaLCA1)));
        elmt_r3 = (elmt_compartment_1 * ((elmt_k1 * elmt_Va5 * elmt_APC) - (elmt_k2 * elmt_Va5_APC)));
        elmt_r24 = (elmt_compartment_1 * ((elmt_k1 * elmt_LC * elmt_APC) - (elmt_k2 * elmt_LC_APC)));
        elmt_r4 = (elmt_compartment_1 * ((elmt_k1 * elmt_Va53 * elmt_APC) - (elmt_k2 * elmt_Va53_APC)));
        elmt_r23 = (elmt_compartment_1 * ((elmt_k9 * elmt_Va536) - (elmt_k10 * elmt_HC536 * elmt_LC)));
        elmt_r1 = (elmt_compartment_1 * ((elmt_k1 * elmt_Va * elmt_APC) - (elmt_k2 * elmt_Va_APC)));
        elmt_r22 = (elmt_compartment_1 * ((elmt_k9 * elmt_Va36) - (elmt_k10 * elmt_HC36 * elmt_LC)));
        elmt_r2 = (elmt_compartment_1 * ((elmt_k1 * elmt_Va3 * elmt_APC) - (elmt_k2 * elmt_Va3_APC)));
        elmt_r21 = (elmt_compartment_1 * ((elmt_k9 * elmt_Va53) - (elmt_k10 * elmt_HC53 * elmt_LC)));
        elmt_r9 = (elmt_compartment_1 * elmt_k6 * elmt_Va5_APC);
        elmt_r29 = (elmt_compartment_1 * ((elmt_k7 * elmt_Va3_APC) - (elmt_k8 * elmt_VaA3 * elmt_VaLCA1_APC)));
        elmt_r31 = (elmt_compartment_1 * ((elmt_k7 * elmt_Va36_APC) - (elmt_k8 * elmt_VaA36 * elmt_VaLCA1_APC)));
        elmt_r30 = (elmt_compartment_1 * ((elmt_k7 * elmt_Va53_APC) - (elmt_k8 * elmt_VaA53 * elmt_VaLCA1_APC)));
        elmt_r17 = (elmt_compartment_1 * ((elmt_k9 * elmt_Va) - (elmt_k10 * elmt_HC * elmt_LC)));
        elmt_r16 = (elmt_compartment_1 * elmt_k5 * elmt_Va3_APC);
        elmt_r15 = (elmt_compartment_1 * elmt_k5 * elmt_Va36_APC);
        elmt_r14 = (elmt_compartment_1 * elmt_k6 * elmt_Va3_APC);
        elmt_r13 = (elmt_compartment_1 * elmt_k3 * elmt_Va_APC);
        elmt_r12 = (elmt_compartment_1 * elmt_k6 * elmt_Va53_APC);
        elmt_r11 = (elmt_compartment_1 * elmt_k3 * elmt_Va5_APC);
        elmt_r33 = (elmt_compartment_1 * ((elmt_k1 * elmt_VaLCA1 * elmt_APC) - (elmt_k2 * elmt_VaLCA1_APC)));
        elmt_r10 = (elmt_compartment_1 * elmt_k3 * elmt_Va56_APC);
        elmt_r32 = (elmt_compartment_1 * ((elmt_k7 * elmt_Va536_APC) - (elmt_k7 * elmt_VaA536 * elmt_VaLCA1_APC)));
        elmt_r19 = (elmt_compartment_1 * ((elmt_k9 * elmt_Va3) - (elmt_k10 * elmt_HC3 * elmt_LC)));
        elmt_r18 = (elmt_compartment_1 * ((elmt_k9 * elmt_Va5) - (elmt_k10 * elmt_HC5 * elmt_LC)));
        elmt_r20 = (elmt_compartment_1 * ((elmt_k9 * elmt_Va56) - (elmt_k10 * elmt_HC56 * elmt_LC)));
        der(elmt_product74) = 0;
        der(elmt_product30) = 0;
        der(elmt_product73) = 0;
        der(elmt_reactant84) = 0;
        der(elmt_product71) = 0;
        der(elmt_reactant42) = 0;
        der(elmt_product34) = 0;
        der(elmt_product77) = 0;
        der(elmt_product76) = 0;
        der(elmt_reactant81) = 0;
        der(elmt_product32) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_product70) = 0;
        der(elmt_reactant87) = 0;
        der(elmt_reactant88) = 0;
        der(elmt_reactant45) = 0;
        der(elmt_reactant9) = 0;
        der(elmt_product26) = 0;
        der(elmt_product68) = 0;
        der(elmt_product24) = 0;
        der(elmt_product28) = 0;
        der(elmt_product41) = 0;
        der(elmt_product85) = 0;
        der(elmt_reactant51) = 0;
        der(elmt_product40) = 0;
        der(elmt_product83) = 0;
        der(elmt_product82) = 0;
        der(elmt_product89) = 0;
        der(elmt_product44) = 0;
        der(elmt_product43) = 0;
        der(elmt_product86) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant54) = 0;
        der(elmt_product80) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_reactant57) = 0;
        der(elmt_product38) = 0;
        der(elmt_product36) = 0;
        der(elmt_product79) = 0;
        der(elmt_reactant61) = 0;
        der(elmt_product52) = 0;
        der(elmt_reactant63) = 0;
        der(elmt_product50) = 0;
        der(elmt_product56) = 0;
        der(elmt_product11) = 0;
        der(elmt_product55) = 0;
        der(elmt_reactant60) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant69) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant66) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product49) = 0;
        der(elmt_product47) = 0;
        der(elmt_product46) = 0;
        der(elmt_reactant72) = 0;
        der(elmt_product8) = 0;
        der(elmt_product62) = 0;
        der(elmt_reactant1) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_reactant75) = 0;
        der(elmt_reactant31) = 0;
        der(elmt_product67) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product22) = 0;
        der(elmt_product65) = 0;
        der(elmt_product20) = 0;
        der(elmt_product64) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_reactant37) = 0;
        der(elmt_reactant39) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant33) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant78) = 0;
        der(elmt_product2) = 0;
        der(elmt_reactant35) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_product59) = 0;
        der(elmt_product14) = 0;
        der(elmt_product58) = 0;
        der(elmt_product17) = 0;

end Reactions;
