within BIOMD052;
class Reactions

    input Real elmt_Amadori;
    input Real elmt_AMP;
    input Real elmt_Triose;
    input Real elmt_Glu;
    input Real elmt_lys_R;
    input Real elmt_Fru;

    Real elmt__J3(unit = "") "";
    parameter Real elmt__J3_elmt_K3(unit "") = 4.7E-4 "";
    Real elmt_reactant4 "";
    Real elmt_product6 "";
    Real elmt_product5 "";
    Real elmt__J2(unit = "") "";
    parameter Real elmt__J2_elmt_K2(unit "") = 0.00509 "";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt__J1(unit = "") "";
    parameter Real elmt__J1_elmt_K1(unit "") = 0.01 "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt__J11(unit = "") "";
    parameter Real elmt__J11_elmt_K11(unit "") = 0.12514 "";
    Real elmt_product27 "";
    Real elmt_reactant26 "";
    Real elmt__J10(unit = "") "";
    parameter Real elmt__J10_elmt_K10(unit "") = 1.5E-4 "";
    Real elmt_product25 "";
    Real elmt_reactant23 "";
    Real elmt_reactant24 "";
    Real elmt__J9(unit = "") "";
    parameter Real elmt__J9_elmt_K9(unit "") = 0.14359 "";
    Real elmt_product22 "";
    Real elmt_reactant21 "";
    Real elmt__J8(unit = "") "";
    parameter Real elmt__J8_elmt_K8(unit "") = 0.11134 "";
    Real elmt_reactant18 "";
    Real elmt_product20 "";
    Real elmt_product19 "";
    Real elmt__J7(unit = "") "";
    parameter Real elmt__J7_elmt_K7(unit "") = 1.8E-4 "";
    Real elmt_reactant15 "";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt__J6(unit = "") "";
    parameter Real elmt__J6_elmt_K6(unit "") = 0.00439 "";
    Real elmt_product14 "";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt__J5(unit = "") "";
    parameter Real elmt__J5_elmt_K5(unit "") = 0.00712 "";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt__J4(unit = "") "";
    parameter Real elmt__J4_elmt_K4(unit "") = 0.0011 "";
    Real elmt_product9 "";
    Real elmt_product8 "";
    Real elmt_reactant7 "";


    initial equation
        elmt_product11 = 2.0;
        elmt_reactant26 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_product27 = 1.0;
        elmt_product25 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product9 = 1.0;
        elmt_product8 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product6 = 1.0;
        elmt_product22 = 1.0;
        elmt_product20 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_product14 = 1.0;
        elmt_product13 = 1.0;
        elmt_product19 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt__J3 = (elmt__J3_elmt_K3 * elmt_Glu);
        elmt__J2 = (elmt__J2_elmt_K2 * elmt_Fru);
        elmt__J1 = (elmt__J1_elmt_K1 * elmt_Glu);
        elmt__J11 = (elmt__J11_elmt_K11 * elmt_AMP);
        elmt__J10 = (elmt__J10_elmt_K10 * elmt_Fru * elmt_lys_R);
        elmt__J9 = (elmt__J9_elmt_K9 * elmt_Amadori);
        elmt__J8 = (elmt__J8_elmt_K8 * elmt_Amadori);
        elmt__J7 = (elmt__J7_elmt_K7 * elmt_Glu * elmt_lys_R);
        elmt__J6 = (elmt__J6_elmt_K6 * elmt_Triose);
        elmt__J5 = (elmt__J5_elmt_K5 * elmt_Fru);
        elmt__J4 = (elmt__J4_elmt_K4 * elmt_Fru);
        der(elmt_product11) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_product27) = 0;
        der(elmt_product25) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product9) = 0;
        der(elmt_product8) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product6) = 0;
        der(elmt_product22) = 0;
        der(elmt_product20) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_product14) = 0;
        der(elmt_product13) = 0;
        der(elmt_product19) = 0;
        der(elmt_product17) = 0;

end Reactions;
