within BIOMD621;
class Reactions

    input Real elmt_vfg;
    input Real elmt_il1bH;
    input Real elmt_kplacebo;
    input Real elmt_Gh;
    input Real elmt_apoptosis;
    input Real elmt_Proinsulin;
    input Real elmt_Insulin;
    input Real elmt_f;
    input Real elmt_Kxi;
    input Real elmt_xfg;
    input Real elmt_Kxg;
    input Real elmt_Tgl;
    input Real elmt_IL1b;
    input Real elmt_kmfg;
    input Real elmt_kmf;
    input Real elmt_vh;
    input Real elmt_Kxgi;
    input Real elmt_vf;
    input Real elmt_vs;
    input Real elmt_replication;
    input Real elmt_kab;
    input Real elmt_IL1R;
    input Real elmt_k1;
    input Real elmt_tauf;
    input Real elmt_kms;
    input Real elmt_il1b0;
    input Real elmt_CL;
    input Real elmt_placebo_on;
    input Real elmt_k2;
    input Real elmt_B;
    input Real elmt_ks;
    input Real elmt_Glucose;
    input Real elmt_taus;
    input Real elmt_Anakinra;
    input Real elmt_kf;
    input Real elmt_TigB;
    input Real elmt_Vp;
    input Real elmt_Anakinrasc;

    Real elmt_AnakinraSC_elimination(unit = "") "";
    Real elmt_reactant9 "";
    Real elmt_Proinsulin_elimination(unit = "") "";
    Real elmt_reactant19 "";
    Real elmt_Bcell_apoptosis(unit = "") "";
    Real elmt_reactant3 "";
    Real elmt_TigB_down(unit = "") "";
    Real elmt_reactant1 "";
    Real elmt_proinsulin_sec_down(unit = "") "";
    Real elmt_reactant5 "";
    Real elmt_Anakinra_absorption(unit = "") "";
    Real elmt_product10 "";
    Real elmt_Proinsulin_dependent_glucose_uptake(unit = "") "";
    Real elmt_reactant15 "";
    Real elmt_Insulin_dependent_glucose_uptake(unit = "") "";
    Real elmt_reactant14 "";
    Real elmt_Anakinra_elimination(unit = "") "";
    Real elmt_reactant11 "";
    Real elmt_Glucose_dependent_insulin_secretion(unit = "") "";
    Real elmt_product16 "";
    Real elmt_Insulin_elimination(unit = "") "";
    Real elmt_reactant17 "";
    Real elmt_TigB_up(unit = "") "";
    Real elmt_product0 "";
    Real elmt_IL1b_degradation(unit = "") "";
    Real elmt_reactant7 "";
    Real elmt_IL1b_treatment(unit = "") "";
    Real elmt_product6 "";
    Real elmt_proinsulin_sec_up(unit = "") "";
    Real elmt_product4 "";
    Real elmt_Basal_glucose_uptake(unit = "") "";
    Real elmt_reactant13 "";
    Real elmt_IL1b_placebo(unit = "") "";
    Real elmt_product8 "";
    Real elmt_Glucose_production(unit = "") "";
    Real elmt_product12 "";
    Real elmt_Glucose_dependent_proinsulin_secretion(unit = "") "";
    Real elmt_product18 "";
    Real elmt_Bcell_replication(unit = "") "";
    Real elmt_product2 "";


    initial equation
        elmt_reactant1 = 1.0;
        elmt_product8 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_product6 = 1.0;
        elmt_product12 = 1.0;
        elmt_reactant5 = 1.0;
        elmt_product10 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_product0 = 1.0;
        elmt_reactant17 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_product4 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_product2 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product16 = 1.0;
        elmt_reactant9 = 1.0;
        elmt_product18 = 1.0;


    equation
        elmt_AnakinraSC_elimination = (elmt_kab * elmt_Anakinrasc);
        elmt_Proinsulin_elimination = (0.1 * elmt_Kxi * elmt_Proinsulin);
        elmt_Bcell_apoptosis = (elmt_apoptosis * elmt_B);
        elmt_TigB_down = (elmt_taus * elmt_TigB);
        elmt_proinsulin_sec_down = (elmt_tauf * elmt_f);
        elmt_Anakinra_absorption = ((elmt_kab * elmt_Anakinrasc) / elmt_Vp);
        elmt_Proinsulin_dependent_glucose_uptake = (0.1 * elmt_Kxgi * elmt_Proinsulin * elmt_Glucose);
        elmt_Insulin_dependent_glucose_uptake = (elmt_Kxgi * elmt_Insulin * elmt_Glucose);
        elmt_Anakinra_elimination = ((elmt_CL / elmt_Vp) * elmt_Anakinra);
        elmt_Glucose_dependent_insulin_secretion = ((Functions.pow((elmt_Glucose / elmt_Gh), elmt_vh) / (1.0 + Functions.pow((elmt_Glucose / elmt_Gh), elmt_vh))) * elmt_TigB * elmt_B);
        elmt_Insulin_elimination = (elmt_Kxi * elmt_Insulin);
        elmt_TigB_up = (elmt_taus * elmt_ks * (1.0 - ((elmt_vs * elmt_IL1R) / (elmt_kms + elmt_IL1R))));
        elmt_IL1b_degradation = (if (time < 91.0) then ((1.0 - elmt_placebo_on) * elmt_k1 * elmt_IL1b) else ((1.0 - elmt_placebo_on) * elmt_k2 * elmt_IL1b));
        elmt_IL1b_treatment = (if (time < 91.0) then ((1.0 - elmt_placebo_on) * elmt_k1 * elmt_il1bH) else ((1.0 - elmt_placebo_on) * elmt_k2 * (elmt_il1b0 + (elmt_kplacebo * time))));
        elmt_proinsulin_sec_up = (elmt_tauf * elmt_kf * (1.0 + ((elmt_vfg * Functions.pow(elmt_Glucose, elmt_xfg)) / (Functions.pow(elmt_kmfg, elmt_xfg) + Functions.pow(elmt_Glucose, elmt_xfg)))) * (1.0 + ((elmt_vf * elmt_IL1R) / (elmt_kmf + elmt_IL1R))));
        elmt_Basal_glucose_uptake = (elmt_Kxg * elmt_Glucose);
        elmt_IL1b_placebo = (elmt_placebo_on * elmt_kplacebo);
        elmt_Glucose_production = elmt_Tgl;
        elmt_Glucose_dependent_proinsulin_secretion = (((elmt_f * Functions.pow((elmt_Glucose / elmt_Gh), elmt_vh)) / (1.0 + Functions.pow((elmt_Glucose / elmt_Gh), elmt_vh))) * elmt_TigB * elmt_B);
        elmt_Bcell_replication = (elmt_replication * elmt_B);
        der(elmt_reactant1) = 0;
        der(elmt_product8) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_product6) = 0;
        der(elmt_product12) = 0;
        der(elmt_reactant5) = 0;
        der(elmt_product10) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_product0) = 0;
        der(elmt_reactant17) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_product4) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_product2) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product16) = 0;
        der(elmt_reactant9) = 0;
        der(elmt_product18) = 0;

end Reactions;
