within BIOMD021;
model Leloup1999_CircClock_periodic "Leloup1999_CircClock" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_compartment_0000002 elmt_compartment_0000002;
    Class_elmt_Cell elmt_Cell;

    equation
        Params.elmt_P1 = elmt_Cell.elmt_P1;
        Params.elmt_P2 = elmt_Cell.elmt_P2;
        Params.elmt_CC = elmt_Cell.elmt_CC;
        Params.elmt_P0 = elmt_Cell.elmt_P0;
        Params.elmt_T1 = elmt_Cell.elmt_T1;
        Params.elmt_T2 = elmt_Cell.elmt_T2;
        Params.elmt_Cn = elmt_compartment_0000002.elmt_Cn;
        Params.elmt_T0 = elmt_Cell.elmt_T0;
        Reacs.elmt_compartment_0000002 = elmt_compartment_0000002.elmt_compartment_0000002;
        Reacs.elmt_Cell = elmt_Cell.elmt_Cell;
        Reacs.elmt_Mp = elmt_Cell.elmt_Mp;
        Reacs.elmt_P1 = elmt_Cell.elmt_P1;
        Reacs.elmt_P2 = elmt_Cell.elmt_P2;
        Reacs.elmt_CC = elmt_Cell.elmt_CC;
        Reacs.elmt_P0 = elmt_Cell.elmt_P0;
        Reacs.elmt_Cn = elmt_compartment_0000002.elmt_Cn;
        Reacs.elmt_Mt = elmt_Cell.elmt_Mt;
        Reacs.elmt_V_dT = Params.elmt_V_dT;
        Reacs.elmt_T1 = elmt_Cell.elmt_T1;
        Reacs.elmt_T2 = elmt_Cell.elmt_T2;
        Reacs.elmt_V_mT = Params.elmt_V_mT;
        Reacs.elmt_T0 = elmt_Cell.elmt_T0;
        elmt_Cell.elmt_product30 = Reacs.elmt_product30;
        elmt_Cell.elmt_P1_degradation = Reacs.elmt_P1_degradation;
        elmt_Cell.elmt_P2_degradation = Reacs.elmt_P2_degradation;
        elmt_Cell.elmt_T2_degradation = Reacs.elmt_T2_degradation;
        elmt_Cell.elmt_P1_to_P0 = Reacs.elmt_P1_to_P0;
        elmt_Cell.elmt_product32 = Reacs.elmt_product32;
        elmt_Cell.elmt_PT_complex_formation = Reacs.elmt_PT_complex_formation;
        elmt_Cell.elmt_product31 = Reacs.elmt_product31;
        elmt_Cell.elmt_T1_to_T2 = Reacs.elmt_T1_to_T2;
        elmt_Cell.elmt_P1_to_P2 = Reacs.elmt_P1_to_P2;
        elmt_Cell.elmt_P0_degradation = Reacs.elmt_P0_degradation;
        elmt_Cell.elmt_Mt_production = Reacs.elmt_Mt_production;
        elmt_Cell.elmt_T0_degradation = Reacs.elmt_T0_degradation;
        elmt_Cell.elmt_T1_to_T0 = Reacs.elmt_T1_to_T0;
        elmt_Cell.elmt_T1_degradation = Reacs.elmt_T1_degradation;
        elmt_Cell.elmt_product24 = Reacs.elmt_product24;
        elmt_Cell.elmt_product29 = Reacs.elmt_product29;
        elmt_Cell.elmt_P2_to_P1 = Reacs.elmt_P2_to_P1;
        elmt_Cell.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_Cell.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_Cell.elmt_reactant17 = Reacs.elmt_reactant17;
        elmt_Cell.elmt_reactant10 = Reacs.elmt_reactant10;
        elmt_Cell.elmt_T2_to_T1 = Reacs.elmt_T2_to_T1;
        elmt_Cell.elmt_PT_complex_degradation = Reacs.elmt_PT_complex_degradation;
        elmt_Cell.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_Cell.elmt_P0_production = Reacs.elmt_P0_production;
        elmt_Cell.elmt_T0_production = Reacs.elmt_T0_production;
        elmt_Cell.elmt_PT_complex_nucleation = Reacs.elmt_PT_complex_nucleation;
        elmt_Cell.elmt_reactant20 = Reacs.elmt_reactant20;
        elmt_Cell.elmt_product11 = Reacs.elmt_product11;
        elmt_Cell.elmt_Mp_degradation = Reacs.elmt_Mp_degradation;
        elmt_Cell.elmt_reactant25 = Reacs.elmt_reactant25;
        elmt_Cell.elmt_reactant27 = Reacs.elmt_reactant27;
        elmt_Cell.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_Cell.elmt_Mp_production = Reacs.elmt_Mp_production;
        elmt_Cell.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_Cell.elmt_reactant23 = Reacs.elmt_reactant23;
        elmt_Cell.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_Cell.elmt_reactant19 = Reacs.elmt_reactant19;
        elmt_Cell.elmt_product9 = Reacs.elmt_product9;
        elmt_Cell.elmt_reactant2 = Reacs.elmt_reactant2;
        elmt_Cell.elmt_reactant4 = Reacs.elmt_reactant4;
        elmt_Cell.elmt_product7 = Reacs.elmt_product7;
        elmt_Cell.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_Cell.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_Cell.elmt_product1 = Reacs.elmt_product1;
        elmt_Cell.elmt_product5 = Reacs.elmt_product5;
        elmt_Cell.elmt_reactant33 = Reacs.elmt_reactant33;
        elmt_Cell.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_Cell.elmt_product3 = Reacs.elmt_product3;
        elmt_Cell.elmt_reactant34 = Reacs.elmt_reactant34;
        elmt_Cell.elmt_Mt_degradation = Reacs.elmt_Mt_degradation;
        elmt_Cell.elmt_product15 = Reacs.elmt_product15;
        elmt_Cell.elmt_product13 = Reacs.elmt_product13;
        elmt_Cell.elmt_P0_to_P1 = Reacs.elmt_P0_to_P1;
        elmt_Cell.elmt_T0_to_T1 = Reacs.elmt_T0_to_T1;
        elmt_compartment_0000002.elmt_PTnucl_complex_degradation = Reacs.elmt_PTnucl_complex_degradation;
        elmt_compartment_0000002.elmt_product26 = Reacs.elmt_product26;
        elmt_compartment_0000002.elmt_reactant28 = Reacs.elmt_reactant28;
        elmt_compartment_0000002.elmt_PT_complex_nucleation = Reacs.elmt_PT_complex_nucleation;

end Leloup1999_CircClock_periodic;
