within BIOMD344;
class Parameters

    input Real elmt_Hsp70_Proteasome;
    input Real elmt_Hsf1_Hsp90;
    input Real elmt_Hsp70_dam;
    input Real elmt_Hsp90_Hsp90Client;
    input Real elmt_Hsp70_Hsp70Client;
    input Real elmt_Akt_Hsp90;
    input Real elmt_Hsp90_MisP;
    input Real elmt_Akt_CHIP_Hsp90;
    input Real elmt_Hsp70;
    input Real elmt_Hsp90_Proteasome;
    input Real elmt_Hsp70_MisP;
    input Real elmt_MisP;
    input Real elmt_Hsp90_dam;
    input Real elmt_Hsp70_Ppx;
    input Real elmt_Hsp90;

    input Boolean elmt_DeathOfCell;
    input Real assign_elmt_kalive;


    Real elmt_kphosMkp1(unit = "") "";
    Real elmt_kbinHsf1Hsp90(unit = "") "";
    Real elmt_krelAktProt(unit = "") "";
    Real elmt_kbinMkp1Prot(unit = "") "";
    Real elmt_kbinHsp90Prot(unit = "") "";
    Real elmt_krelHspMisp(unit = "") "";
    Real elmt_kdegHsp90(unit = "") "";
    Real elmt_kbinHSEHsf1(unit = "") "";
    Real elmt_kgenROSAggP(unit = "") "";
    Real elmt_krelCHIP(unit = "") "";
    Real elmt_kmisfold(unit = "") "";
    Real elmt_kseqagg(unit = "") "";
    Real elmt_kdedimerHsf1(unit = "") "";
    Real elmt_kbinHsp90client(unit = "") "";
    Real elmt_kdegAkt(unit = "") "";
    Real elmt_ksynNatP(unit = "") "";
    Real elmt_krelHSEPhosTriH(unit = "") "";
    Real elmt_kbinHsp70client(unit = "") "";
    Real elmt_kphosHsf1(unit = "") "";
    Real elmt_kphosJnk(unit = "") "";
    Real elmt_ksynAkt(unit = "") "";
    Real elmt_krelHSEHsf1(unit = "") "";
    Real elmt_kdegMisP(unit = "") "";
    Real elmt_kagg(unit = "") "";
    Real elmt_krelHsp70client(unit = "") "";
    Real elmt_kbasalsynHsp90(unit = "") "";
    Real elmt_tot_Hsp90(unit = "") "";
    Real elmt_kdimerHsf1(unit = "") "";
    Real elmt_kbinMisPProt(unit = "") "";
    Real elmt_kdegMkp1(unit = "") "";
    Real elmt_kp38death(unit = "") "";
    Real elmt_kupregHsp(unit = "") "";
    Real elmt_kremROS(unit = "") "";
    Real elmt_krelHsp90client(unit = "") "";
    Real elmt_kp38act(unit = "") "";
    Real elmt_krelHsp70Ppx(unit = "") "";
    Real elmt_krelAktHsp90(unit = "") "";
    Real elmt_kgenROSp38(unit = "") "";
    Real elmt_krefold(unit = "") "";
    Real elmt_kdephosHsf1(unit = "") "";
    Real elmt_kbinHSEPhosTriH(unit = "") "";
    Real elmt_krelHsf1Hsp90(unit = "") "";
    Real elmt_kgenROS(unit = "") "";
    Real elmt_kbinHsp70Ppx(unit = "") "";
    Real elmt_kdegHsp70(unit = "") "";
    Real elmt_kbinCHIP(unit = "") "";
    Real elmt_kdetrimerHsf1(unit = "") "";
    Real elmt_kdephosJnkMkp1(unit = "") "";
    Real elmt_kdephosp38Mkp1(unit = "") "";
    Real elmt_kdephosMkp1(unit = "") "";
    Real elmt_kdamHsp(unit = "") "";
    Real elmt_kalive(unit = "") "";
    Real elmt_kPIdeath(unit = "") "";
    Real elmt_kbinAggPProt(unit = "") "";
    Real elmt_kbasalsynHsp70(unit = "") "";
    Real elmt_ksynMkp1(unit = "") "";
    Real elmt_tot_Hsp70(unit = "") "";
    Real elmt_kbinHsp70Prot(unit = "") "";
    Real elmt_ktrimerHsf1(unit = "") "";
    Real elmt_kbinAktHsp90(unit = "") "";
    Real elmt_tot_MisP(unit = "") "";
    Real elmt_kphosp38(unit = "") "";
    Real elmt_kJnkdeath(unit = "") "";
    Real elmt_kbinAktProt(unit = "") "";
    Real elmt_kbinHspMisp(unit = "") "";


    initial equation
        elmt_kphosMkp1 = 0.02;
        elmt_kbinHsf1Hsp90 = 0.02;
        elmt_krelAktProt = 1.0E-8;
        elmt_kbinMkp1Prot = 9.6E-9;
        elmt_kbinHsp90Prot = 1.0E-8;
        elmt_krelHspMisp = 8.0E-5;
        elmt_kdegHsp90 = 0.01;
        elmt_kbinHSEHsf1 = 0.05;
        elmt_kgenROSAggP = 1.0E-6;
        elmt_krelCHIP = 1.0E-8;
        elmt_kmisfold = 2.0E-6;
        elmt_kseqagg = 7.0E-7;
        elmt_kdedimerHsf1 = 0.5;
        elmt_kbinHsp90client = 2.0E-4;
        elmt_kdegAkt = 0.01;
        elmt_ksynNatP = 0.042;
        elmt_krelHSEPhosTriH = 0.08;
        elmt_kbinHsp70client = 2.0E-4;
        elmt_kphosHsf1 = 0.03;
        elmt_kphosJnk = 0.02;
        elmt_ksynAkt = 0.0015;
        elmt_krelHSEHsf1 = 0.08;
        elmt_kdegMisP = 0.01;
        elmt_kagg = 1.0E-8;
        elmt_krelHsp70client = 5.0;
        elmt_kbasalsynHsp90 = 0.008;
        elmt_kdimerHsf1 = 8.0E-5;
        elmt_kbinMisPProt = 1.0E-7;
        elmt_kdegMkp1 = 0.01;
        elmt_kp38death = 1.5E-7;
        elmt_kupregHsp = 0.2;
        elmt_kremROS = 0.001;
        elmt_krelHsp90client = 5.0;
        elmt_kp38act = 1.0;
        elmt_krelHsp70Ppx = 5.0;
        elmt_krelAktHsp90 = 7.0;
        elmt_kgenROSp38 = 1.0E-4;
        elmt_krefold = 5.5E-4;
        elmt_kdephosHsf1 = 0.01;
        elmt_kbinHSEPhosTriH = 0.1;
        elmt_krelHsf1Hsp90 = 0.5;
        elmt_kgenROS = 0.01;
        elmt_kbinHsp70Ppx = 0.2;
        elmt_kdegHsp70 = 0.01;
        elmt_kbinCHIP = 2.0E-7;
        elmt_kdetrimerHsf1 = 0.5;
        elmt_kdephosJnkMkp1 = 0.05;
        elmt_kdephosp38Mkp1 = 0.05;
        elmt_kdephosMkp1 = 0.001;
        elmt_kdamHsp = 1.0E-8;
        elmt_kalive = 1.0;
        elmt_kPIdeath = 2.0E-8;
        elmt_kbinAggPProt = 1.0E-5;
        elmt_kbasalsynHsp70 = 0.008;
        elmt_ksynMkp1 = 1.0E-5;
        elmt_kbinHsp70Prot = 1.2E-8;
        elmt_ktrimerHsf1 = 0.01;
        elmt_kbinAktHsp90 = 3.7E-4;
        elmt_kphosp38 = 0.02;
        elmt_kJnkdeath = 1.5E-7;
        elmt_kbinAktProt = 6.0E-8;
        elmt_kbinHspMisp = 8.0E-6;


    equation
        der(elmt_kphosMkp1) = 0;
        der(elmt_kbinHsf1Hsp90) = 0;
        der(elmt_krelAktProt) = 0;
        der(elmt_kbinMkp1Prot) = 0;
        der(elmt_kbinHsp90Prot) = 0;
        der(elmt_krelHspMisp) = 0;
        der(elmt_kdegHsp90) = 0;
        der(elmt_kbinHSEHsf1) = 0;
        der(elmt_kgenROSAggP) = 0;
        der(elmt_krelCHIP) = 0;
        der(elmt_kmisfold) = 0;
        der(elmt_kseqagg) = 0;
        der(elmt_kdedimerHsf1) = 0;
        der(elmt_kbinHsp90client) = 0;
        der(elmt_kdegAkt) = 0;
        der(elmt_ksynNatP) = 0;
        der(elmt_krelHSEPhosTriH) = 0;
        der(elmt_kbinHsp70client) = 0;
        der(elmt_kphosHsf1) = 0;
        der(elmt_kphosJnk) = 0;
        der(elmt_ksynAkt) = 0;
        der(elmt_krelHSEHsf1) = 0;
        der(elmt_kdegMisP) = 0;
        der(elmt_kagg) = 0;
        der(elmt_krelHsp70client) = 0;
        der(elmt_kbasalsynHsp90) = 0;
        elmt_tot_Hsp90 = (elmt_Hsp90 + elmt_Hsp90_dam + elmt_Hsp90_Proteasome + elmt_Hsp90_Hsp90Client + elmt_Akt_Hsp90 + elmt_Akt_CHIP_Hsp90 + elmt_Hsf1_Hsp90 + elmt_Hsp90_MisP);
        der(elmt_kdimerHsf1) = 0;
        der(elmt_kbinMisPProt) = 0;
        der(elmt_kdegMkp1) = 0;
        der(elmt_kp38death) = 0;
        der(elmt_kupregHsp) = 0;
        der(elmt_kremROS) = 0;
        der(elmt_krelHsp90client) = 0;
        der(elmt_kp38act) = 0;
        der(elmt_krelHsp70Ppx) = 0;
        der(elmt_krelAktHsp90) = 0;
        der(elmt_kgenROSp38) = 0;
        der(elmt_krefold) = 0;
        der(elmt_kdephosHsf1) = 0;
        der(elmt_kbinHSEPhosTriH) = 0;
        der(elmt_krelHsf1Hsp90) = 0;
        der(elmt_kgenROS) = 0;
        der(elmt_kbinHsp70Ppx) = 0;
        der(elmt_kdegHsp70) = 0;
        der(elmt_kbinCHIP) = 0;
        der(elmt_kdetrimerHsf1) = 0;
        der(elmt_kdephosJnkMkp1) = 0;
        der(elmt_kdephosp38Mkp1) = 0;
        der(elmt_kdephosMkp1) = 0;
        der(elmt_kdamHsp) = 0;
        der(elmt_kalive) = 0.0;
        der(elmt_kPIdeath) = 0;
        der(elmt_kbinAggPProt) = 0;
        der(elmt_kbasalsynHsp70) = 0;
        der(elmt_ksynMkp1) = 0;
        elmt_tot_Hsp70 = (elmt_Hsp70 + elmt_Hsp70_dam + elmt_Hsp70_Proteasome + elmt_Hsp70_Hsp70Client + elmt_Hsp70_MisP + elmt_Hsp70_Ppx);
        der(elmt_kbinHsp70Prot) = 0;
        der(elmt_ktrimerHsf1) = 0;
        der(elmt_kbinAktHsp90) = 0;
        elmt_tot_MisP = (elmt_MisP + elmt_Hsp70_MisP + elmt_Hsp90_MisP);
        der(elmt_kphosp38) = 0;
        der(elmt_kJnkdeath) = 0;
        der(elmt_kbinAktProt) = 0;
        der(elmt_kbinHspMisp) = 0;

        when elmt_DeathOfCell then
            reinit(elmt_kalive, assign_elmt_kalive);
        end when;
end Parameters;
