formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD036_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tyson1999_CircClock/log/BIOMD036.log
    formatter: simple
    level: DEBUG
  BIOMD038_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/rohwer2000_PhosphotransferaseSystem/log/BIOMD038.log
    formatter: simple
    level: DEBUG
  BIOMD039_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/marhl2000_CaOscillations/log/BIOMD039.log
    formatter: simple
    level: DEBUG
  BIOMD040_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/field1974_Oregonator/log/BIOMD040.log
    formatter: simple
    level: DEBUG
  BIOMD041_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/kongas2007_CreatineKinaseInEnergyMetabolicSignalingInMuscle/log/BIOMD041.log
    formatter: simple
    level: DEBUG
  BIOMD042_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/nielsen1998_Glycolysis/log/BIOMD042.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD036:
    handlers:
    - BIOMD036_handler
    level: DEBUG
    propagate: 'no'
  BIOMD038:
    handlers:
    - BIOMD038_handler
    level: DEBUG
    propagate: 'no'
  BIOMD039:
    handlers:
    - BIOMD039_handler
    level: DEBUG
    propagate: 'no'
  BIOMD040:
    handlers:
    - BIOMD040_handler
    level: DEBUG
    propagate: 'no'
  BIOMD041:
    handlers:
    - BIOMD041_handler
    level: DEBUG
    propagate: 'no'
  BIOMD042:
    handlers:
    - BIOMD042_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
