formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD052_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/brands2002_MonosaccharideCaseInSystems/log/BIOMD052.log
    formatter: simple
    level: DEBUG
  BIOMD053_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/ferreira2003_CMLGeneration2/log/BIOMD053.log
    formatter: simple
    level: DEBUG
  BIOMD054_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/ataullahkhanov1996_Adenylate/log/BIOMD054.log
    formatter: simple
    level: DEBUG
  BIOMD057_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/sneyd2002_IP3Receptor/log/BIOMD057.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD052:
    handlers:
    - BIOMD052_handler
    level: DEBUG
    propagate: 'no'
  BIOMD053:
    handlers:
    - BIOMD053_handler
    level: DEBUG
    propagate: 'no'
  BIOMD054:
    handlers:
    - BIOMD054_handler
    level: DEBUG
    propagate: 'no'
  BIOMD057:
    handlers:
    - BIOMD057_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
