formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BouncingBall_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/Modelica/examples/bouncing-ball/v2//log/BouncingBall.log
    formatter: simple
    level: DEBUG
  Sampling_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/Modelica/examples/sampling//log/Sampling.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
  system_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/Modelica/examples/ifmodel//log/system.log
    formatter: simple
    level: DEBUG
loggers:
  BouncingBall:
    handlers:
    - BouncingBall_handler
    level: DEBUG
    propagate: 'no'
  Sampling:
    handlers:
    - Sampling_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
  system:
    handlers:
    - system_handler
    level: DEBUG
    propagate: 'no'
version: 1
