formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD203_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2006
      - Stem cell switch reversible/log/BIOMD203.log
    formatter: simple
    level: DEBUG
  BIOMD204_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2006
      - Stem cell switch irreversible/log/BIOMD204.log
    formatter: simple
    level: DEBUG
  BIOMD209_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2008
      - Stem cell lineage determination/log/BIOMD209.log
    formatter: simple
    level: DEBUG
  BIOMD210_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2008
      - Stem cell lineage - NANOG GATA-6 switch/log/BIOMD210.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD203:
    handlers:
    - BIOMD203_handler
    level: DEBUG
    propagate: 'no'
  BIOMD204:
    handlers:
    - BIOMD204_handler
    level: DEBUG
    propagate: 'no'
  BIOMD209:
    handlers:
    - BIOMD209_handler
    level: DEBUG
    propagate: 'no'
  BIOMD210:
    handlers:
    - BIOMD210_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
