formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  ChemicalSystem_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/chemicalSystem/log/ChemicalSystem.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  ChemicalSystem:
    handlers:
    - ChemicalSystem_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
