formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD092_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Fuentes2005_ZymogenActivation/log/BIOMD092.log
    formatter: simple
    level: DEBUG
  BIOMD112_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Clarke2006_Smad_signalling/log/BIOMD112.log
    formatter: simple
    level: DEBUG
  BIOMD113_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Dupont1992_Ca_dpt_protein_phospho/log/BIOMD113.log
    formatter: simple
    level: DEBUG
  BIOMD117_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Dupont1991_CaOscillation/log/BIOMD117.log
    formatter: simple
    level: DEBUG
  BIOMD123_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Fisher2006_NFAT_Activation/log/BIOMD123.log
    formatter: simple
    level: DEBUG
  BIOMD203_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2006
      - Stem cell switch reversible/log/BIOMD203.log
    formatter: simple
    level: DEBUG
  BIOMD204_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2006
      - Stem cell switch irreversible/log/BIOMD204.log
    formatter: simple
    level: DEBUG
  BIOMD209_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2008
      - Stem cell lineage determination/log/BIOMD209.log
    formatter: simple
    level: DEBUG
  BIOMD210_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2008
      - Stem cell lineage - NANOG GATA-6 switch/log/BIOMD210.log
    formatter: simple
    level: DEBUG
  BIOMD212_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Curien2009_Aspartate_Metabolism/log/BIOMD212.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD092:
    handlers:
    - BIOMD092_handler
    level: DEBUG
    propagate: 'no'
  BIOMD112:
    handlers:
    - BIOMD112_handler
    level: DEBUG
    propagate: 'no'
  BIOMD113:
    handlers:
    - BIOMD113_handler
    level: DEBUG
    propagate: 'no'
  BIOMD117:
    handlers:
    - BIOMD117_handler
    level: DEBUG
    propagate: 'no'
  BIOMD123:
    handlers:
    - BIOMD123_handler
    level: DEBUG
    propagate: 'no'
  BIOMD203:
    handlers:
    - BIOMD203_handler
    level: DEBUG
    propagate: 'no'
  BIOMD204:
    handlers:
    - BIOMD204_handler
    level: DEBUG
    propagate: 'no'
  BIOMD209:
    handlers:
    - BIOMD209_handler
    level: DEBUG
    propagate: 'no'
  BIOMD210:
    handlers:
    - BIOMD210_handler
    level: DEBUG
    propagate: 'no'
  BIOMD212:
    handlers:
    - BIOMD212_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
