formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD020_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/hodgkin-huxley1952_SquidAxon/log/BIOMD020.log
    formatter: simple
    level: DEBUG
  BIOMD021_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/leloup1999_CircClock/log/BIOMD021.log
    formatter: simple
    level: DEBUG
  BIOMD022_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/ueda2001_CircClock/log/BIOMD022.log
    formatter: simple
    level: DEBUG
  BIOMD023_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/rohwer2001_Sucrose/log/BIOMD023.log
    formatter: simple
    level: DEBUG
  BouncingBall_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/cyber-physical/Bouncingball/v1/log/BouncingBall.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD020:
    handlers:
    - BIOMD020_handler
    level: DEBUG
    propagate: 'no'
  BIOMD021:
    handlers:
    - BIOMD021_handler
    level: DEBUG
    propagate: 'no'
  BIOMD022:
    handlers:
    - BIOMD022_handler
    level: DEBUG
    propagate: 'no'
  BIOMD023:
    handlers:
    - BIOMD023_handler
    level: DEBUG
    propagate: 'no'
  BouncingBall:
    handlers:
    - BouncingBall_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
