formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD008_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/gardner1998_CellCycleGoldbeter/log/BIOMD008.log
    formatter: simple
    level: DEBUG
  BIOMD009_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/huang1996_UltrasensitivityMAPKcascade/log/BIOMD009.log
    formatter: simple
    level: DEBUG
  BIOMD010_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/kholodenko2000_UltrasensAndNegFeedbkMAPKcascade/log/BIOMD010.log
    formatter: simple
    level: DEBUG
  BIOMD012_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/elowitz2000_Repressillator/log/BIOMD012.log
    formatter: simple
    level: DEBUG
  BIOMD015_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/curto1998_purineMetabolism/log/BIOMD015.log
    formatter: simple
    level: DEBUG
  BIOMD016_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/goldbeter1995_CircClock/log/BIOMD016.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD008:
    handlers:
    - BIOMD008_handler
    level: DEBUG
    propagate: 'no'
  BIOMD009:
    handlers:
    - BIOMD009_handler
    level: DEBUG
    propagate: 'no'
  BIOMD010:
    handlers:
    - BIOMD010_handler
    level: DEBUG
    propagate: 'no'
  BIOMD012:
    handlers:
    - BIOMD012_handler
    level: DEBUG
    propagate: 'no'
  BIOMD015:
    handlers:
    - BIOMD015_handler
    level: DEBUG
    propagate: 'no'
  BIOMD016:
    handlers:
    - BIOMD016_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
