formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD084_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Hornberg2005_ERKcascade/log/BIOMD084.log
    formatter: simple
    level: DEBUG
  BIOMD092_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Fuentes2005_ZymogenActivation/log/BIOMD092.log
    formatter: simple
    level: DEBUG
  BIOMD098_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Goldbeter1990_CalciumSpike_CICR/log/BIOMD098.log
    formatter: simple
    level: DEBUG
  BIOMD109_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Haberichter2007_cellcycle/log/BIOMD109.log
    formatter: simple
    level: DEBUG
  BIOMD112_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Clarke2006_Smad_signalling/log/BIOMD112.log
    formatter: simple
    level: DEBUG
  BIOMD113_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Dupont1992_Ca_dpt_protein_phospho/log/BIOMD113.log
    formatter: simple
    level: DEBUG
  BIOMD117_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Dupont1991_CaOscillation/log/BIOMD117.log
    formatter: simple
    level: DEBUG
  BIOMD123_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Fisher2006_NFAT_Activation/log/BIOMD123.log
    formatter: simple
    level: DEBUG
  BIOMD139_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Hoffmann2002_KnockOut_IkBNFkB_Signaling/log/BIOMD139.log
    formatter: simple
    level: DEBUG
  BIOMD140_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Hoffmann2002_WT_IkBNFkB_Signaling/log/BIOMD140.log
    formatter: simple
    level: DEBUG
  BIOMD146_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Hatakeyama2003_MAPK/log/BIOMD146.log
    formatter: simple
    level: DEBUG
  BIOMD186_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Ibrahim2008
      - Mitotic Spindle Assembly Checkpoint - Dissociation variant/log/BIOMD186.log
    formatter: simple
    level: DEBUG
  BIOMD187_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Ibrahim2008
      - Mitotic Spindle Assembly Checkpoint - Convey variant/log/BIOMD187.log
    formatter: simple
    level: DEBUG
  BIOMD192_handler:
    class: logging.FileHandler
    filename: "/home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/G\xF6\
      rlich2003_RanGTP_gradient/log/BIOMD192.log"
    formatter: simple
    level: DEBUG
  BIOMD193_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Ibrahim2008_MCC_assembly_model_KDM/log/BIOMD193.log
    formatter: simple
    level: DEBUG
  BIOMD194_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Ibrahim2008_Cdc20_Sequestring_Template_Model/log/BIOMD194.log
    formatter: simple
    level: DEBUG
  BIOMD201_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Goldbeter2008_Somite_Segmentation_Clock_Notch_Wnt_FGF/log/BIOMD201.log
    formatter: simple
    level: DEBUG
  BIOMD203_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2006
      - Stem cell switch reversible/log/BIOMD203.log
    formatter: simple
    level: DEBUG
  BIOMD204_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2006
      - Stem cell switch irreversible/log/BIOMD204.log
    formatter: simple
    level: DEBUG
  BIOMD209_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2008
      - Stem cell lineage determination/log/BIOMD209.log
    formatter: simple
    level: DEBUG
  BIOMD210_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Chickarmane2008
      - Stem cell lineage - NANOG GATA-6 switch/log/BIOMD210.log
    formatter: simple
    level: DEBUG
  BIOMD212_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/tmp/Curien2009_Aspartate_Metabolism/log/BIOMD212.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD084:
    handlers:
    - BIOMD084_handler
    level: DEBUG
    propagate: 'no'
  BIOMD092:
    handlers:
    - BIOMD092_handler
    level: DEBUG
    propagate: 'no'
  BIOMD098:
    handlers:
    - BIOMD098_handler
    level: DEBUG
    propagate: 'no'
  BIOMD109:
    handlers:
    - BIOMD109_handler
    level: DEBUG
    propagate: 'no'
  BIOMD112:
    handlers:
    - BIOMD112_handler
    level: DEBUG
    propagate: 'no'
  BIOMD113:
    handlers:
    - BIOMD113_handler
    level: DEBUG
    propagate: 'no'
  BIOMD117:
    handlers:
    - BIOMD117_handler
    level: DEBUG
    propagate: 'no'
  BIOMD123:
    handlers:
    - BIOMD123_handler
    level: DEBUG
    propagate: 'no'
  BIOMD139:
    handlers:
    - BIOMD139_handler
    level: DEBUG
    propagate: 'no'
  BIOMD140:
    handlers:
    - BIOMD140_handler
    level: DEBUG
    propagate: 'no'
  BIOMD146:
    handlers:
    - BIOMD146_handler
    level: DEBUG
    propagate: 'no'
  BIOMD186:
    handlers:
    - BIOMD186_handler
    level: DEBUG
    propagate: 'no'
  BIOMD187:
    handlers:
    - BIOMD187_handler
    level: DEBUG
    propagate: 'no'
  BIOMD192:
    handlers:
    - BIOMD192_handler
    level: DEBUG
    propagate: 'no'
  BIOMD193:
    handlers:
    - BIOMD193_handler
    level: DEBUG
    propagate: 'no'
  BIOMD194:
    handlers:
    - BIOMD194_handler
    level: DEBUG
    propagate: 'no'
  BIOMD201:
    handlers:
    - BIOMD201_handler
    level: DEBUG
    propagate: 'no'
  BIOMD203:
    handlers:
    - BIOMD203_handler
    level: DEBUG
    propagate: 'no'
  BIOMD204:
    handlers:
    - BIOMD204_handler
    level: DEBUG
    propagate: 'no'
  BIOMD209:
    handlers:
    - BIOMD209_handler
    level: DEBUG
    propagate: 'no'
  BIOMD210:
    handlers:
    - BIOMD210_handler
    level: DEBUG
    propagate: 'no'
  BIOMD212:
    handlers:
    - BIOMD212_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
