formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD052_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/brands2002_MonosaccharideCaseInSystems/log/BIOMD052.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD052:
    handlers:
    - BIOMD052_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
