formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD052_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/brands2002_MonosaccharideCaseInSystems/log/BIOMD052.log
    formatter: simple
    level: DEBUG
  BIOMD053_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/ferreira2003_CMLGeneration2/log/BIOMD053.log
    formatter: simple
    level: DEBUG
  BIOMD054_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/ataullahkhanov1996_Adenylate/log/BIOMD054.log
    formatter: simple
    level: DEBUG
  BIOMD057_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/sneyd2002_IP3Receptor/log/BIOMD057.log
    formatter: simple
    level: DEBUG
  BIOMD058_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/bindschadler2001_CoupledCaOscillators/log/BIOMD058.log
    formatter: simple
    level: DEBUG
  BIOMD060_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/keizer1996_RyanodineReceptorAdaptation/log/BIOMD060.log
    formatter: simple
    level: DEBUG
  BIOMD062_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/bhartiya2003_TryptophanOperon/log/BIOMD062.log
    formatter: simple
    level: DEBUG
  BIOMD066_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/chassagnole2001_ThreonineSynthesis/log/BIOMD066.log
    formatter: simple
    level: DEBUG
  BIOMD067_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/fung2005_MetabolicOscillator/log/BIOMD067.log
    formatter: simple
    level: DEBUG
  BIOMD068_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/curien2003_MetThrSynthesis/log/BIOMD068.log
    formatter: simple
    level: DEBUG
  BIOMD076_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/cronwright2002_GlycerolSynthesis/log/BIOMD076.log
    formatter: simple
    level: DEBUG
  BIOMD160_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/xie2007_CircClock/log/BIOMD160.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD052:
    handlers:
    - BIOMD052_handler
    level: DEBUG
    propagate: 'no'
  BIOMD053:
    handlers:
    - BIOMD053_handler
    level: DEBUG
    propagate: 'no'
  BIOMD054:
    handlers:
    - BIOMD054_handler
    level: DEBUG
    propagate: 'no'
  BIOMD057:
    handlers:
    - BIOMD057_handler
    level: DEBUG
    propagate: 'no'
  BIOMD058:
    handlers:
    - BIOMD058_handler
    level: DEBUG
    propagate: 'no'
  BIOMD060:
    handlers:
    - BIOMD060_handler
    level: DEBUG
    propagate: 'no'
  BIOMD062:
    handlers:
    - BIOMD062_handler
    level: DEBUG
    propagate: 'no'
  BIOMD066:
    handlers:
    - BIOMD066_handler
    level: DEBUG
    propagate: 'no'
  BIOMD067:
    handlers:
    - BIOMD067_handler
    level: DEBUG
    propagate: 'no'
  BIOMD068:
    handlers:
    - BIOMD068_handler
    level: DEBUG
    propagate: 'no'
  BIOMD076:
    handlers:
    - BIOMD076_handler
    level: DEBUG
    propagate: 'no'
  BIOMD160:
    handlers:
    - BIOMD160_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
