formatters:
  simple:
    format: '%(asctime)s - %(name)s[%(process)d] - %(levelname)s : %(message)s'
handlers:
  BIOMD0000000005_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/BIOMD005/log/BIOMD0000000005.log
    formatter: simple
    level: DEBUG
  BIOMD020_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/hodgkin-huxley1952_SquidAxon/log/BIOMD020.log
    formatter: simple
    level: DEBUG
  BIOMD021_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/leloup1999_CircClock/log/BIOMD021.log
    formatter: simple
    level: DEBUG
  BIOMD022_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/ueda2001_CircClock/log/BIOMD022.log
    formatter: simple
    level: DEBUG
  BIOMD023_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/rohwer2001_Sucrose/log/BIOMD023.log
    formatter: simple
    level: DEBUG
  BIOMD030_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/biological/markevich2004_MAPKAllRandomElmentary/log/BIOMD030.log
    formatter: simple
    level: DEBUG
  BouncingBall_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/Tirocinio/modelica2GPU/test/cyber-physical/Bouncingball/v1/log/BouncingBall.log
    formatter: simple
    level: DEBUG
  Delay_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/delay/log/Delay.log
    formatter: simple
    level: DEBUG
  Rohwer2001_Sucrose_handler:
    class: logging.FileHandler
    filename: /home/yorunoomo/Scrivania/BIOMD023/log/Rohwer2001_Sucrose.log
    formatter: simple
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    stream: ext://sys.stdout
loggers:
  BIOMD0000000005:
    handlers:
    - BIOMD0000000005_handler
    level: DEBUG
    propagate: 'no'
  BIOMD020:
    handlers:
    - BIOMD020_handler
    level: DEBUG
    propagate: 'no'
  BIOMD021:
    handlers:
    - BIOMD021_handler
    level: DEBUG
    propagate: 'no'
  BIOMD022:
    handlers:
    - BIOMD022_handler
    level: DEBUG
    propagate: 'no'
  BIOMD023:
    handlers:
    - BIOMD023_handler
    level: DEBUG
    propagate: 'no'
  BIOMD030:
    handlers:
    - BIOMD030_handler
    level: DEBUG
    propagate: 'no'
  BouncingBall:
    handlers:
    - BouncingBall_handler
    level: DEBUG
    propagate: 'no'
  Delay:
    handlers:
    - Delay_handler
    level: DEBUG
    propagate: 'no'
  Rohwer2001_Sucrose:
    handlers:
    - Rohwer2001_Sucrose_handler
    level: DEBUG
    propagate: 'no'
  root:
    handlers:
    - console
    level: DEBUG
version: 1
