within BIOMD389;
class Reactions

    input Real elmt_phi;
    input Real elmt_ATP;
    input Real elmt_cytosol;
    input Real elmt_CO2;
    input Real elmt_ADP;
    input Real elmt_TP;
    input Real elmt_RuBP;
    input Real elmt_S7P;
    input Real elmt_HeP;
    input Real elmt_GG;
    input Real elmt_E;
    input Real elmt_D;
    input Real elmt_TPc;
    input Real elmt_Ru5P;
    input Real elmt_E4P;
    input Real elmt_Suc;
    input Real elmt_UDP;
    input Real elmt_v_15;
    input Real elmt_Pi;
    input Real elmt_SucV;
    input Real elmt_chloroplast;
    input Real elmt_TPGA;
    input Real elmt_Pic;
    input Real elmt_PGA;
    input Real elmt_r;

    Real elmt_TPT(unit = "") "TP translocator";
    parameter Real elmt_TPT_elmt_k1(unit "") = 0.5 "";
    Real elmt_product41 "";
    Real elmt_reactant40 "";
    Real elmt_product42 "";
    Real elmt_reactant39 "";
    Real elmt_ATP_S(unit = "") "ATP synthase";
    parameter Real elmt_ATP_S_elmt_k1(unit "") = 0.279 "";
    Real elmt_product30 "";
    Real elmt_reactant29 "";
    Real elmt_reactant28 "";
    Real elmt_Starch_S(unit = "") "starch synthetase";
    parameter Real elmt_Starch_S_elmt_k1(unit "") = 0.002 "";
    Real elmt_reactant31 "";
    Real elmt_product34 "";
    Real elmt_product33 "";
    Real elmt_product35 "";
    Real elmt_reactant32 "";
    Real elmt_RuBisCO(unit = "") "RuBisCO";
    parameter Real elmt_RuBisCO_elmt_k1(unit "") = 0.006 "";
    Real elmt_reactant1 "";
    Real elmt_reactant0 "";
    Real elmt_product2 "";
    Real elmt_Starch_P(unit = "") "starch phosphorylase";
    parameter Real elmt_Starch_P_elmt_k1(unit "") = 4.0E-5 "";
    Real elmt_reactant36 "";
    Real elmt_product38 "";
    Real elmt_reactant37 "";
    Real elmt_Diffu(unit = "") "diffusion rate";
    Real elmt_product57 "";
    Real elmt_reactant56 "";
    Real elmt_Transl(unit = "") "translocation rate";
    Real elmt_reactant58 "";
    Real elmt_product59 "";
    Real elmt_TK2_Ru5P_E(unit = "") "trans II + Ru5P epi";
    parameter Real elmt_TK2_Ru5P_E_elmt_k1(unit "") = 6.2 "";
    Real elmt_product23 "";
    Real elmt_reactant21 "";
    Real elmt_reactant22 "";
    Real elmt_UTP_S(unit = "") "UTP synthase";
    parameter Real elmt_UTP_S_elmt_k1(unit "") = 0.00755 "";
    Real elmt_reactant51 "";
    Real elmt_reactant52 "";
    Real elmt_product53 "";
    Real elmt_S7P_TK1_R5P_I(unit = "") "S7P trans I + R5P iso";
    parameter Real elmt_S7P_TK1_R5P_I_elmt_k1(unit "") = 0.31 "";
    Real elmt_reactant18 "";
    Real elmt_product20 "";
    Real elmt_product19 "";
    Real elmt_PGA_red(unit = "") "PGA reduction";
    parameter Real elmt_PGA_red_elmt_k1(unit "") = 0.0207 "";
    Real elmt_reactant4 "";
    Real elmt_product7 "";
    Real elmt_reactant3 "";
    Real elmt_product6 "";
    Real elmt_product5 "";
    Real elmt_FBPc_A_ase(unit = "") "FBPc ald + ase";
    parameter Real elmt_FBPc_A_ase_elmt_k1(unit "") = 1.55 "";
    Real elmt_product45 "";
    Real elmt_product44 "";
    Real elmt_reactant43 "";
    Real elmt_Ru5P_K(unit = "") "Ru5P kinase";
    parameter Real elmt_Ru5P_K_elmt_k1(unit "") = 0.031 "";
    Real elmt_reactant25 "";
    Real elmt_product27 "";
    Real elmt_product26 "";
    Real elmt_reactant24 "";
    Real elmt_Respi(unit = "") "respiration rate";
    Real elmt_product55 "";
    Real elmt_reactant54 "";
    Real elmt_Suc_S(unit = "") "sucrose synthetase";
    Real elmt_product50 "";
    Real elmt_reactant47 "";
    Real elmt_product49 "";
    Real elmt_product48 "";
    Real elmt_reactant46 "";
    Real elmt_FBP_A_ase(unit = "") "FBP ald + ase";
    parameter Real elmt_FBP_A_ase_elmt_k1(unit "") = 4.0 "";
    parameter Real elmt_FBP_A_ase_elmt_k2(unit "") = 0.0 "";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_product10 "";
    Real elmt_F6P_TK1(unit = "") "F6P trans I";
    parameter Real elmt_F6P_TK1_elmt_k1(unit "") = 0.031 "";
    Real elmt_product12 "";
    Real elmt_product13 "";
    Real elmt_reactant11 "";
    Real elmt_SBP_A_ase(unit = "") "SBP ald + ase";
    parameter Real elmt_SBP_A_ase_elmt_k1(unit "") = 3.1 "";
    Real elmt_reactant14 "";
    Real elmt_product16 "";
    Real elmt_reactant15 "";
    Real elmt_product17 "";


    initial equation
        elmt_product30 = 1.0;
        elmt_reactant40 = 1.0;
        elmt_product34 = 1.0;
        elmt_product33 = 1.0;
        elmt_reactant47 = 1.0;
        elmt_reactant43 = 2.0;
        elmt_reactant46 = 2.0;
        elmt_product27 = 1.0;
        elmt_product26 = 1.0;
        elmt_product41 = 1.0;
        elmt_reactant51 = 1.0;
        elmt_reactant52 = 1.0;
        elmt_product45 = 1.0;
        elmt_product44 = 1.0;
        elmt_product42 = 1.0;
        elmt_reactant58 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_reactant54 = 1.0;
        elmt_reactant11 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_product38 = 1.0;
        elmt_product35 = 2.0;
        elmt_product50 = 3.0;
        elmt_product12 = 1.0;
        elmt_product55 = 1.0;
        elmt_product10 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_product49 = 1.0;
        elmt_product48 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant1 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant31 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_product6 = 1.0;
        elmt_product23 = 1.0;
        elmt_reactant8 = 2.0;
        elmt_product20 = 1.0;
        elmt_reactant36 = 1.0;
        elmt_reactant37 = 1.0;
        elmt_reactant39 = 1.0;
        elmt_reactant32 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product2 = 2.0;
        elmt_reactant29 = 1.0;
        elmt_product16 = 1.0;
        elmt_product59 = 1.0;
        elmt_product57 = 1.0;
        elmt_product13 = 1.0;
        elmt_product19 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_TPT = (elmt_TPT_elmt_k1 * elmt_TP * elmt_Pic);
        elmt_ATP_S = (elmt_chloroplast * elmt_ATP_S_elmt_k1 * elmt_ADP * elmt_Pi);
        elmt_Starch_S = (elmt_chloroplast * elmt_Starch_S_elmt_k1 * elmt_ATP * elmt_HeP);
        elmt_RuBisCO = (elmt_chloroplast * elmt_RuBisCO_elmt_k1 * elmt_RuBP * elmt_CO2);
        elmt_Starch_P = (elmt_chloroplast * elmt_Starch_P_elmt_k1 * elmt_GG * elmt_Pi);
        elmt_Diffu = ((elmt_D * elmt_Suc) - (elmt_D * elmt_SucV));
        elmt_Transl = ((elmt_phi * elmt_Suc) - (elmt_phi * elmt_E));
        elmt_TK2_Ru5P_E = (elmt_chloroplast * elmt_TK2_Ru5P_E_elmt_k1 * elmt_TPGA * elmt_TP);
        elmt_UTP_S = (elmt_UTP_S_elmt_k1 * elmt_UDP * elmt_Pic);
        elmt_S7P_TK1_R5P_I = (elmt_chloroplast * elmt_S7P_TK1_R5P_I_elmt_k1 * elmt_S7P);
        elmt_PGA_red = (elmt_chloroplast * elmt_PGA_red_elmt_k1 * elmt_PGA * elmt_ATP);
        elmt_FBPc_A_ase = (elmt_cytosol * elmt_FBPc_A_ase_elmt_k1 * Functions.pow(elmt_TPc, 2.0));
        elmt_Ru5P_K = (elmt_chloroplast * elmt_Ru5P_K_elmt_k1 * elmt_Ru5P * elmt_ATP);
        elmt_Respi = (elmt_r * elmt_Suc);
        elmt_Suc_S = (elmt_v_15);
        elmt_FBP_A_ase = (elmt_chloroplast * ((elmt_FBP_A_ase_elmt_k1 * Functions.pow(elmt_TP, 2.0)) - (elmt_FBP_A_ase_elmt_k2 * elmt_HeP * elmt_Pi)));
        elmt_F6P_TK1 = (elmt_chloroplast * elmt_F6P_TK1_elmt_k1 * elmt_HeP);
        elmt_SBP_A_ase = (elmt_chloroplast * elmt_SBP_A_ase_elmt_k1 * elmt_E4P * elmt_TP);
        der(elmt_product30) = 0;
        der(elmt_reactant40) = 0;
        der(elmt_product34) = 0;
        der(elmt_product33) = 0;
        der(elmt_reactant47) = 0;
        der(elmt_reactant43) = 0;
        der(elmt_reactant46) = 0;
        der(elmt_product27) = 0;
        der(elmt_product26) = 0;
        der(elmt_product41) = 0;
        der(elmt_reactant51) = 0;
        der(elmt_reactant52) = 0;
        der(elmt_product45) = 0;
        der(elmt_product44) = 0;
        der(elmt_product42) = 0;
        der(elmt_reactant58) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant54) = 0;
        der(elmt_reactant11) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_product38) = 0;
        der(elmt_product35) = 0;
        der(elmt_product50) = 0;
        der(elmt_product12) = 0;
        der(elmt_product55) = 0;
        der(elmt_product10) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_product49) = 0;
        der(elmt_product48) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant1) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant31) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_product6) = 0;
        der(elmt_product23) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product20) = 0;
        der(elmt_reactant36) = 0;
        der(elmt_reactant37) = 0;
        der(elmt_reactant39) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product2) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_product16) = 0;
        der(elmt_product59) = 0;
        der(elmt_product57) = 0;
        der(elmt_product13) = 0;
        der(elmt_product19) = 0;
        der(elmt_product17) = 0;

end Reactions;
