within BIOMD144;
class Parameters

    input Real elmt_N;
    input Real elmt_preMPFn;
    input Real elmt_MPFc;
    input Real elmt_StgPc;
    input Real elmt_MPFn;
    input Real elmt_StgPn;
    input Real elmt_preMPFc;

    Real elmt_E_1(unit = "") "E";
    Real elmt_kdn(unit = "") "kdnpp";
    Real elmt_kastgp(unit = "") "kastgp";
    Real elmt_kdm(unit = "") "kdmpp";
    Real elmt_kstgp(unit = "") "kstgp";
    Real elmt_kins_1(unit = "") "kins";
    Real elmt_kdstg(unit = "") "kdstg";
    Real elmt_Jawee(unit = "") "Jawee";
    Real elmt_kdnp(unit = "") "kdnp";
    Real elmt_kstg(unit = "") "kstgpp";
    Real elmt_kinw_1(unit = "") "kinw";
    Real elmt_Jiwee(unit = "") "Jiwee";
    Real elmt_ksstg(unit = "") "ksstg";
    Real elmt_ksc(unit = "") "ksc";
    Real elmt_kiweep(unit = "") "kiweep";
    Real elmt_Jaie(unit = "") "Jaie";
    Real elmt_Jafzy(unit = "") "Jafzy";
    Real elmt_ksxm_1(unit = "") "ksxm";
    Real elmt_Jastg(unit = "") "Jastg";
    Real elmt_ksxp_1(unit = "") "ksxp";
    Real elmt_Jiie(unit = "") "Jiie";
    Real elmt_Jistg(unit = "") "Jistg";
    Real elmt_kez_1(unit = "") "kez";
    Real elmt_Jifzy(unit = "") "Jifzy";
    Real elmt_koutw_1(unit = "") "koutw";
    Real elmt_Jm(unit = "") "Jm";
    Real elmt_kouts_1(unit = "") "kouts";
    Real elmt_StringT(unit = "") "";
    Real elmt_kastg(unit = "") "kastgpp";
    Real elmt_kaie(unit = "") "kaie";
    Real elmt_kafzy(unit = "") "kafzy";
    Real elmt_Wee1T(unit = "") "";
    Real elmt_kawee(unit = "") "kawee";
    Real elmt_kdmp(unit = "") "kdmp";
    Real elmt_kifzy(unit = "") "kifzy";
    Real elmt_kistg(unit = "") "kistg";
    Real elmt_kt(unit = "") "kin";
    Real elmt_kiie(unit = "") "kiie";
    Real elmt_kweep(unit = "") "kweep";
    Real elmt_kiwee(unit = "") "kiweepp";
    Real elmt_StgPT(unit = "") "";
    Real elmt_kwee(unit = "") "kweepp";
    Real elmt_factor_1(unit = "") "factor";
    Real elmt_kout_1(unit = "") "kout";
    Real elmt_kdc(unit = "") "kdcp";
    Real elmt_CycBT(unit = "") "";


    initial equation
        elmt_E_1 = 7.0E-5;
        elmt_kdn = 1.5;
        elmt_kastgp = 0.0;
        elmt_kdm = 0.2;
        elmt_kstgp = 0.2;
        elmt_kins_1 = 0.08;
        elmt_kdstg = 0.0;
        elmt_Jawee = 0.05;
        elmt_kdnp = 0.01;
        elmt_kstg = 2.0;
        elmt_kinw_1 = 0.04;
        elmt_Jiwee = 0.05;
        elmt_ksstg = 0.0;
        elmt_ksc = 0.01;
        elmt_kiweep = 0.01;
        elmt_Jaie = 0.01;
        elmt_Jafzy = 0.01;
        elmt_ksxm_1 = 5.0E-4;
        elmt_Jastg = 0.05;
        elmt_ksxp_1 = 0.001;
        elmt_Jiie = 0.01;
        elmt_Jistg = 0.05;
        elmt_kez_1 = 0.5;
        elmt_Jifzy = 0.01;
        elmt_koutw_1 = 0.01;
        elmt_Jm = 0.05;
        elmt_kouts_1 = 0.02;
        elmt_StringT = 0.8;
        elmt_kastg = 1.0;
        elmt_kaie = 1.0;
        elmt_kafzy = 1.0;
        elmt_Wee1T = 0.8;
        elmt_kawee = 0.3;
        elmt_kdmp = 0.002;
        elmt_kifzy = 0.2;
        elmt_kistg = 0.3;
        elmt_kt = 0.15;
        elmt_kiie = 0.4;
        elmt_kweep = 0.005;
        elmt_kiwee = 1.0;
        elmt_kwee = 1.0;
        elmt_factor_1 = 1.95;
        elmt_kout_1 = 0.0;
        elmt_kdc = 0.01;


    equation
        der(elmt_E_1) = 0;
        der(elmt_kdn) = 0;
        der(elmt_kastgp) = 0;
        der(elmt_kdm) = 0;
        der(elmt_kstgp) = 0;
        der(elmt_kins_1) = 0;
        der(elmt_kdstg) = 0;
        der(elmt_Jawee) = 0;
        der(elmt_kdnp) = 0;
        der(elmt_kstg) = 0;
        der(elmt_kinw_1) = 0;
        der(elmt_Jiwee) = 0;
        der(elmt_ksstg) = 0;
        der(elmt_ksc) = 0;
        der(elmt_kiweep) = 0;
        der(elmt_Jaie) = 0;
        der(elmt_Jafzy) = 0;
        der(elmt_ksxm_1) = 0;
        der(elmt_Jastg) = 0;
        der(elmt_ksxp_1) = 0;
        der(elmt_Jiie) = 0;
        der(elmt_Jistg) = 0;
        der(elmt_kez_1) = 0;
        der(elmt_Jifzy) = 0;
        der(elmt_koutw_1) = 0;
        der(elmt_Jm) = 0;
        der(elmt_kouts_1) = 0;
        der(elmt_StringT) = 0;
        der(elmt_kastg) = 0;
        der(elmt_kaie) = 0;
        der(elmt_kafzy) = 0;
        der(elmt_Wee1T) = 0;
        der(elmt_kawee) = 0;
        der(elmt_kdmp) = 0;
        der(elmt_kifzy) = 0;
        der(elmt_kistg) = 0;
        der(elmt_kt) = 0;
        der(elmt_kiie) = 0;
        der(elmt_kweep) = 0;
        der(elmt_kiwee) = 0;
        elmt_StgPT = (((1.0 - (elmt_N * elmt_E_1)) * elmt_StgPc) + (elmt_N * elmt_E_1 * elmt_StgPn));
        der(elmt_kwee) = 0;
        der(elmt_factor_1) = 0;
        der(elmt_kout_1) = 0;
        der(elmt_kdc) = 0;
        elmt_CycBT = (((1.0 - (elmt_N * elmt_E_1)) * (elmt_MPFc + elmt_preMPFc)) + (elmt_N * elmt_E_1 * (elmt_MPFn + elmt_preMPFn)));

end Parameters;
