within BIOMD619;
class Reactions

    input Real elmt_Kkidney2plasma;
    input Real elmt_Fraction_unbound_plasma;
    input Real elmt_CGut;
    input Real elmt_CLung;
    input Real elmt_Qgfr;
    input Real elmt_Kliver2plasma;
    input Real elmt_VLung;
    input Real elmt_QRest;
    input Real elmt_CKidney;
    input Real elmt_VLiver;
    input Real elmt_CLiver;
    input Real elmt_VRest;
    input Real elmt_VKidney;
    input Real elmt_QCardiac;
    input Real elmt_QGut;
    input Real elmt_VVen;
    input Real elmt_CArt;
    input Real elmt_AGutlumen;
    input Real elmt_VArt;
    input Real elmt_QLiver;
    input Real elmt_Ratioblood2plasma;
    input Real elmt_QKidney;
    input Real elmt_CLmetabolism;
    input Real elmt_kGutabs;
    input Real elmt_CRest;
    input Real elmt_VGut;
    input Real elmt_KRest2plasma;
    input Real elmt_CVen;

    Real elmt_J7(unit = "") "J07";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_J8(unit = "") "J08";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_J5(unit = "") "J05";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_J6(unit = "") "J06";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_J3(unit = "") "J03";
    Real elmt_reactant4 "";
    Real elmt_product5 "";
    Real elmt_J4(unit = "") "J04";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_J1(unit = "") "J01";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_J2(unit = "") "J02";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_J9(unit = "") "J09";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_J12(unit = "") "J12";
    Real elmt_product23 "";
    Real elmt_reactant22 "";
    Real elmt_J13(unit = "") "J13";
    Real elmt_product25 "";
    Real elmt_reactant24 "";
    Real elmt_J10(unit = "") "J10";
    Real elmt_reactant18 "";
    Real elmt_product19 "";
    Real elmt_J11(unit = "") "J11";
    Real elmt_reactant20 "";
    Real elmt_product21 "";


    initial equation
        elmt_reactant20 = 1.0;
        elmt_product11 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_product25 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product23 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product21 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product3 = 1.0;
        elmt_product15 = 1.0;
        elmt_product13 = 1.0;
        elmt_product19 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_J7 = ((elmt_QLiver / elmt_VArt) * elmt_CArt);
        elmt_J8 = ((elmt_CLmetabolism * elmt_CLiver) / (elmt_Kliver2plasma * elmt_Fraction_unbound_plasma));
        elmt_J5 = (elmt_QRest * (elmt_CArt / elmt_VArt));
        elmt_J6 = ((((elmt_QRest / elmt_VRest) * elmt_CRest) * elmt_Ratioblood2plasma) / (elmt_KRest2plasma * elmt_Fraction_unbound_plasma));
        elmt_J3 = ((elmt_QCardiac / elmt_VLung) * elmt_CLung);
        elmt_J4 = ((elmt_QCardiac / elmt_VVen) * elmt_CVen);
        elmt_J1 = ((elmt_QGut / elmt_VArt) * elmt_CArt);
        elmt_J2 = (elmt_kGutabs * elmt_AGutlumen);
        elmt_J9 = ((elmt_QGut / elmt_VGut) * elmt_CGut);
        elmt_J12 = (((elmt_Qgfr / elmt_VKidney) * elmt_CKidney) / elmt_Kkidney2plasma);
        elmt_J13 = ((((elmt_QKidney / elmt_VKidney) * elmt_CKidney) * elmt_Ratioblood2plasma) / (elmt_Kkidney2plasma * elmt_Fraction_unbound_plasma));
        elmt_J10 = (((((elmt_QLiver + elmt_QGut) / elmt_VLiver) * elmt_CLiver) * elmt_Ratioblood2plasma) / (elmt_Kliver2plasma * elmt_Fraction_unbound_plasma));
        elmt_J11 = ((elmt_QKidney / elmt_VArt) * elmt_CArt);
        der(elmt_reactant20) = 0;
        der(elmt_product11) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_product25) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product23) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product21) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product3) = 0;
        der(elmt_product15) = 0;
        der(elmt_product13) = 0;
        der(elmt_product19) = 0;
        der(elmt_product17) = 0;

end Reactions;
