within BIOMD313;
class Reactions

    input Real elmt_p_IL13_Rec;
    input Real elmt_IL13;
    input Real elmt_pJAK2_dephosphorylation;
    input Real elmt_JAK2_p_inhibition;
    input Real elmt_JAK2_phosphorylation;
    input Real elmt_pJAK2;
    input Real elmt_Kon_IL13Rec;
    input Real elmt_SOCS3mRNA_production;
    input Real elmt_SOCS3_accumulation;
    input Real elmt_DecoyR;
    input Real elmt_DecoyR_binding;
    input Real elmt_IL13_Rec;
    input Real elmt_STAT5;
    input Real elmt_cell;
    input Real elmt_pRec_degradation;
    input Real elmt_Rec_intern;
    input Real elmt_p_IL13_Rec_i;
    input Real elmt_JAK2;
    input Real elmt_SHP1;
    input Real elmt_pRec_intern;
    input Real elmt_CD274mRNA_production;
    input Real elmt_SOCS3;
    input Real elmt_Rec_phosphorylation;
    input Real elmt_pSTAT5;
    input Real elmt_STAT5_phosphorylation;
    input Real elmt_SOCS3_translation;
    input Real elmt_SOCS3mRNA;
    input Real elmt_Rec_i;
    input Real elmt_SOCS3_degradation;
    input Real elmt_Rec_recycle;
    input Real elmt_pSTAT5_dephosphorylation;
    input Real elmt_Rec;

    Real elmt_reaction_3(unit = "") "";
    Real elmt_reactant4 "";
    Real elmt_product5 "";
    Real elmt_reaction_4(unit = "") "";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_reaction_1(unit = "") "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_reaction_2(unit = "") "";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_reaction_16(unit = "") "";
    Real elmt_product26 "";
    Real elmt_reaction_9(unit = "") "";
    Real elmt_product16 "";
    Real elmt_reactant15 "";
    Real elmt_reaction_14(unit = "") "";
    Real elmt_product24 "";
    Real elmt_reaction_15(unit = "") "";
    Real elmt_reactant25 "";
    Real elmt_reaction_7(unit = "") "";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_reaction_8(unit = "") "";
    Real elmt_reactant14 "";
    Real elmt_reaction_5(unit = "") "";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_reaction_6(unit = "") "";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_reaction_12(unit = "") "";
    Real elmt_product22 "";
    Real elmt_reactant21 "";
    Real elmt_reaction_13(unit = "") "";
    Real elmt_product23 "";
    Real elmt_reaction_10(unit = "") "";
    Real elmt_reactant17 "";
    Real elmt_product18 "";
    Real elmt_reaction_11(unit = "") "";
    Real elmt_reactant19 "";
    Real elmt_product20 "";


    initial equation
        elmt_product11 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product26 = 1.0;
        elmt_product24 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product23 = 1.0;
        elmt_product22 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product20 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_reactant17 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_product16 = 1.0;
        elmt_product13 = 1.0;
        elmt_product18 = 1.0;


    equation
        elmt_reaction_3 = (elmt_Rec_recycle * elmt_Rec_i * elmt_cell);
        elmt_reaction_4 = (elmt_Rec_phosphorylation * elmt_IL13_Rec * elmt_pJAK2 * elmt_cell);
        elmt_reaction_1 = (elmt_Kon_IL13Rec * elmt_IL13 * elmt_Rec * elmt_cell);
        elmt_reaction_2 = (elmt_Rec_intern * elmt_Rec * elmt_cell);
        elmt_reaction_16 = (elmt_pSTAT5 * elmt_CD274mRNA_production * elmt_cell);
        elmt_reaction_9 = (elmt_pJAK2_dephosphorylation * elmt_pJAK2 * elmt_SHP1 * elmt_cell);
        elmt_reaction_14 = (((elmt_SOCS3mRNA * elmt_SOCS3_translation) / (elmt_SOCS3_accumulation + elmt_SOCS3mRNA)) * elmt_cell);
        elmt_reaction_15 = (elmt_SOCS3_degradation * elmt_SOCS3 * elmt_cell);
        elmt_reaction_7 = (elmt_pRec_intern * elmt_p_IL13_Rec * elmt_cell);
        elmt_reaction_8 = (elmt_pRec_degradation * elmt_p_IL13_Rec_i * elmt_cell);
        elmt_reaction_5 = (((elmt_JAK2_phosphorylation * elmt_IL13_Rec * elmt_JAK2) / (1.0 + (elmt_JAK2_p_inhibition * elmt_SOCS3))) * elmt_cell);
        elmt_reaction_6 = (((elmt_JAK2_phosphorylation * elmt_p_IL13_Rec * elmt_JAK2) / (1.0 + (elmt_JAK2_p_inhibition * elmt_SOCS3))) * elmt_cell);
        elmt_reaction_12 = (elmt_DecoyR_binding * elmt_IL13 * elmt_DecoyR * elmt_cell);
        elmt_reaction_13 = (elmt_pSTAT5 * elmt_SOCS3mRNA_production * elmt_cell);
        elmt_reaction_10 = (elmt_STAT5_phosphorylation * elmt_STAT5 * elmt_pJAK2 * elmt_cell);
        elmt_reaction_11 = (elmt_pSTAT5_dephosphorylation * elmt_pSTAT5 * elmt_SHP1 * elmt_cell);
        der(elmt_product11) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product26) = 0;
        der(elmt_product24) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product23) = 0;
        der(elmt_product22) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product20) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant17) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_product16) = 0;
        der(elmt_product13) = 0;
        der(elmt_product18) = 0;

end Reactions;
