within BIOMD557;
model MODEL1410300001 "Reiterer2013 - pseudophosphatase STYX role in ERK signalling" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_nucleus elmt_nucleus;
    Class_elmt_cytosol elmt_cytosol;

    equation
        Reacs.elmt_nucleus = elmt_nucleus.elmt_nucleus;
        Reacs.elmt_ppERK_DUSPn = elmt_nucleus.elmt_ppERK_DUSPn;
        Reacs.elmt_pERK_ppMEKc = elmt_cytosol.elmt_pERK_ppMEKc;
        Reacs.elmt_DUSPn = elmt_nucleus.elmt_DUSPn;
        Reacs.elmt_k2_pES = Params.elmt_k2_pES;
        Reacs.elmt_kd1_pERKc = Params.elmt_kd1_pERKc;
        Reacs.elmt_DUSPc = elmt_cytosol.elmt_DUSPc;
        Reacs.elmt_pERK_STYXn = elmt_nucleus.elmt_pERK_STYXn;
        Reacs.elmt_ppERK_DUSPc = elmt_cytosol.elmt_ppERK_DUSPc;
        Reacs.elmt_ppERKc = elmt_cytosol.elmt_ppERKc;
        Reacs.elmt_k1_pES = Params.elmt_k1_pES;
        Reacs.elmt_kd2_pERKn = Params.elmt_kd2_pERKn;
        Reacs.elmt_duspn_basal = Params.elmt_duspn_basal;
        Reacs.elmt_pERKc = elmt_cytosol.elmt_pERKc;
        Reacs.elmt_k_ERKout = Params.elmt_k_ERKout;
        Reacs.elmt_k_pERKin = Params.elmt_k_pERKin;
        Reacs.elmt_duspn_ind = Params.elmt_duspn_ind;
        Reacs.elmt_v2 = Params.elmt_v2;
        Reacs.elmt_Tduspn = Params.elmt_Tduspn;
        Reacs.elmt_k2_ERKc = Params.elmt_k2_ERKc;
        Reacs.elmt_pERKn = elmt_nucleus.elmt_pERKn;
        Reacs.elmt_ERKc = elmt_cytosol.elmt_ERKc;
        Reacs.elmt_kd2_pERKc = Params.elmt_kd2_pERKc;
        Reacs.elmt_k1_ERKc = Params.elmt_k1_ERKc;
        Reacs.elmt_kd2_ppERKc = Params.elmt_kd2_ppERKc;
        Reacs.elmt_kd1_pERKn = Params.elmt_kd1_pERKn;
        Reacs.elmt_kd1_ppERKn = Params.elmt_kd1_ppERKn;
        Reacs.elmt_ppMEKc_tot = elmt_cytosol.elmt_ppMEKc_tot;
        Reacs.elmt_k1_ppES = Params.elmt_k1_ppES;
        Reacs.elmt_kd3_ppERKn = Params.elmt_kd3_ppERKn;
        Reacs.elmt_kd3_pERKn = Params.elmt_kd3_pERKn;
        Reacs.elmt_cytosol = elmt_cytosol.elmt_cytosol;
        Reacs.elmt_kd2_ppERKn = Params.elmt_kd2_ppERKn;
        Reacs.elmt_duspn = elmt_nucleus.elmt_duspn;
        Reacs.elmt_pERK_DUSPn = elmt_nucleus.elmt_pERK_DUSPn;
        Reacs.elmt_ERKn = elmt_nucleus.elmt_ERKn;
        Reacs.elmt_k1_ES = Params.elmt_k1_ES;
        Reacs.elmt_ERK_ppMEKc = elmt_cytosol.elmt_ERK_ppMEKc;
        Reacs.elmt_ERK_STYXn = elmt_nucleus.elmt_ERK_STYXn;
        Reacs.elmt_k_ppERKin = Params.elmt_k_ppERKin;
        Reacs.elmt_STYXn = elmt_nucleus.elmt_STYXn;
        Reacs.elmt_ppERK_STYXn = elmt_nucleus.elmt_ppERK_STYXn;
        Reacs.elmt_Kduspn = Params.elmt_Kduspn;
        Reacs.elmt_pERK_DUSPc = elmt_cytosol.elmt_pERK_DUSPc;
        Reacs.elmt_k_ERKin = Params.elmt_k_ERKin;
        Reacs.elmt_k3_ERKc = Params.elmt_k3_ERKc;
        Reacs.elmt_k_pERKout = Params.elmt_k_pERKout;
        Reacs.elmt_k2_ppES = Params.elmt_k2_ppES;
        Reacs.elmt_TDUSPn = Params.elmt_TDUSPn;
        Reacs.elmt_kd1_ppERKc = Params.elmt_kd1_ppERKc;
        Reacs.elmt_k_ppERKout = Params.elmt_k_ppERKout;
        Reacs.elmt_k2_ES = Params.elmt_k2_ES;
        Reacs.elmt_kd3_ppERKc = Params.elmt_kd3_ppERKc;
        Reacs.elmt_ppERKn = elmt_nucleus.elmt_ppERKn;
        Reacs.elmt_kd3_pERKc = Params.elmt_kd3_pERKc;
        elmt_nucleus.elmt_product30 = Reacs.elmt_product30;
        elmt_nucleus.elmt_reactant41 = Reacs.elmt_reactant41;
        elmt_nucleus.elmt_product50 = Reacs.elmt_product50;
        elmt_nucleus.elmt_reactant42 = Reacs.elmt_reactant42;
        elmt_nucleus.elmt_product34 = Reacs.elmt_product34;
        elmt_nucleus.elmt_product11 = Reacs.elmt_product11;
        elmt_nucleus.elmt_product31 = Reacs.elmt_product31;
        elmt_nucleus.elmt_reactant26 = Reacs.elmt_reactant26;
        elmt_nucleus.elmt_reactant48 = Reacs.elmt_reactant48;
        elmt_nucleus.elmt_reactant27 = Reacs.elmt_reactant27;
        elmt_nucleus.elmt_reactant49 = Reacs.elmt_reactant49;
        elmt_nucleus.elmt_reactant43 = Reacs.elmt_reactant43;
        elmt_nucleus.elmt_reactant45 = Reacs.elmt_reactant45;
        elmt_nucleus.elmt_reactant46 = Reacs.elmt_reactant46;
        elmt_nucleus.elmt_reaction_20 = Reacs.elmt_reaction_20;
        elmt_nucleus.elmt_product47 = Reacs.elmt_product47;
        elmt_nucleus.elmt_reaction_21 = Reacs.elmt_reaction_21;
        elmt_nucleus.elmt_product28 = Reacs.elmt_product28;
        elmt_nucleus.elmt_reaction_22 = Reacs.elmt_reaction_22;
        elmt_nucleus.elmt_product9 = Reacs.elmt_product9;
        elmt_nucleus.elmt_product40 = Reacs.elmt_product40;
        elmt_nucleus.elmt_product44 = Reacs.elmt_product44;
        elmt_nucleus.elmt_reactant39 = Reacs.elmt_reactant39;
        elmt_nucleus.elmt_reactant32 = Reacs.elmt_reactant32;
        elmt_nucleus.elmt_reactant33 = Reacs.elmt_reactant33;
        elmt_nucleus.elmt_reactant35 = Reacs.elmt_reactant35;
        elmt_nucleus.elmt_reaction_16 = Reacs.elmt_reaction_16;
        elmt_nucleus.elmt_reaction_17 = Reacs.elmt_reaction_17;
        elmt_nucleus.elmt_reaction_14 = Reacs.elmt_reaction_14;
        elmt_nucleus.elmt_reaction_15 = Reacs.elmt_reaction_15;
        elmt_nucleus.elmt_reactant29 = Reacs.elmt_reactant29;
        elmt_nucleus.elmt_reaction_7 = Reacs.elmt_reaction_7;
        elmt_nucleus.elmt_reaction_5 = Reacs.elmt_reaction_5;
        elmt_nucleus.elmt_reaction_18 = Reacs.elmt_reaction_18;
        elmt_nucleus.elmt_reaction_19 = Reacs.elmt_reaction_19;
        elmt_nucleus.elmt_reaction_6 = Reacs.elmt_reaction_6;
        elmt_nucleus.elmt_product38 = Reacs.elmt_product38;
        elmt_nucleus.elmt_product37 = Reacs.elmt_product37;
        elmt_nucleus.elmt_product36 = Reacs.elmt_product36;
        elmt_nucleus.elmt_product13 = Reacs.elmt_product13;
        elmt_nucleus.elmt_reaction_12 = Reacs.elmt_reaction_12;
        elmt_nucleus.elmt_reaction_13 = Reacs.elmt_reaction_13;
        elmt_cytosol.elmt_reactant20 = Reacs.elmt_reactant20;
        elmt_cytosol.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_cytosol.elmt_reactant23 = Reacs.elmt_reactant23;
        elmt_cytosol.elmt_product25 = Reacs.elmt_product25;
        elmt_cytosol.elmt_product24 = Reacs.elmt_product24;
        elmt_cytosol.elmt_reactant2 = Reacs.elmt_reactant2;
        elmt_cytosol.elmt_k_ppMEKc_tot = Params.elmt_k_ppMEKc_tot;
        elmt_cytosol.elmt_product7 = Reacs.elmt_product7;
        elmt_cytosol.elmt_reactant4 = Reacs.elmt_reactant4;
        elmt_cytosol.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_cytosol.elmt_product22 = Reacs.elmt_product22;
        elmt_cytosol.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_cytosol.elmt_reaction_3 = Reacs.elmt_reaction_3;
        elmt_cytosol.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_cytosol.elmt_product1 = Reacs.elmt_product1;
        elmt_cytosol.elmt_reaction_4 = Reacs.elmt_reaction_4;
        elmt_cytosol.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_cytosol.elmt_reaction_1 = Reacs.elmt_reaction_1;
        elmt_cytosol.elmt_reactant17 = Reacs.elmt_reactant17;
        elmt_cytosol.elmt_reaction_2 = Reacs.elmt_reaction_2;
        elmt_cytosol.elmt_product5 = Reacs.elmt_product5;
        elmt_cytosol.elmt_reactant10 = Reacs.elmt_reactant10;
        elmt_cytosol.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_cytosol.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_cytosol.elmt_product3 = Reacs.elmt_product3;
        elmt_cytosol.elmt_reaction_9 = Reacs.elmt_reaction_9;
        elmt_cytosol.elmt_reaction_7 = Reacs.elmt_reaction_7;
        elmt_cytosol.elmt_reaction_8 = Reacs.elmt_reaction_8;
        elmt_cytosol.elmt_reaction_5 = Reacs.elmt_reaction_5;
        elmt_cytosol.elmt_reaction_6 = Reacs.elmt_reaction_6;
        elmt_cytosol.elmt_product16 = Reacs.elmt_product16;
        elmt_cytosol.elmt_product19 = Reacs.elmt_product19;
        elmt_cytosol.elmt_reaction_10 = Reacs.elmt_reaction_10;
        elmt_cytosol.elmt_product18 = Reacs.elmt_product18;
        elmt_cytosol.elmt_reaction_11 = Reacs.elmt_reaction_11;

end MODEL1410300001;
