within BIOMD557;
class Reactions

    input Real elmt_nucleus;
    input Real elmt_ppERK_DUSPn;
    input Real elmt_pERK_ppMEKc;
    input Real elmt_DUSPn;
    input Real elmt_k2_pES;
    input Real elmt_kd1_pERKc;
    input Real elmt_DUSPc;
    input Real elmt_pERK_STYXn;
    input Real elmt_ppERK_DUSPc;
    input Real elmt_ppERKc;
    input Real elmt_k1_pES;
    input Real elmt_kd2_pERKn;
    input Real elmt_duspn_basal;
    input Real elmt_pERKc;
    input Real elmt_k_ERKout;
    input Real elmt_k_pERKin;
    input Real elmt_duspn_ind;
    input Real elmt_v2;
    input Real elmt_Tduspn;
    input Real elmt_k2_ERKc;
    input Real elmt_pERKn;
    input Real elmt_ERKc;
    input Real elmt_kd2_pERKc;
    input Real elmt_k1_ERKc;
    input Real elmt_kd2_ppERKc;
    input Real elmt_kd1_pERKn;
    input Real elmt_kd1_ppERKn;
    input Real elmt_ppMEKc_tot;
    input Real elmt_k1_ppES;
    input Real elmt_kd3_ppERKn;
    input Real elmt_kd3_pERKn;
    input Real elmt_cytosol;
    input Real elmt_kd2_ppERKn;
    input Real elmt_duspn;
    input Real elmt_pERK_DUSPn;
    input Real elmt_ERKn;
    input Real elmt_k1_ES;
    input Real elmt_ERK_ppMEKc;
    input Real elmt_ERK_STYXn;
    input Real elmt_k_ppERKin;
    input Real elmt_STYXn;
    input Real elmt_ppERK_STYXn;
    input Real elmt_Kduspn;
    input Real elmt_pERK_DUSPc;
    input Real elmt_k_ERKin;
    input Real elmt_k3_ERKc;
    input Real elmt_k_pERKout;
    input Real elmt_k2_ppES;
    input Real elmt_TDUSPn;
    input Real elmt_kd1_ppERKc;
    input Real elmt_k_ppERKout;
    input Real elmt_k2_ES;
    input Real elmt_kd3_ppERKc;
    input Real elmt_ppERKn;
    input Real elmt_kd3_pERKc;

    Real elmt_reaction_3(unit = "") "";
    Real elmt_reactant4 "";
    Real elmt_product5 "";
    Real elmt_reaction_4(unit = "") "";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_reaction_1(unit = "") "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_reaction_2(unit = "") "";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_reaction_16(unit = "") "";
    Real elmt_product38 "";
    Real elmt_reaction_17(unit = "") "";
    Real elmt_reactant39 "";
    Real elmt_reaction_9(unit = "") "";
    Real elmt_reactant17 "";
    Real elmt_product19 "";
    Real elmt_product18 "";
    Real elmt_reaction_14(unit = "") "";
    Real elmt_product34 "";
    Real elmt_reactant32 "";
    Real elmt_reactant33 "";
    Real elmt_reaction_15(unit = "") "";
    Real elmt_product37 "";
    Real elmt_product36 "";
    Real elmt_reactant35 "";
    Real elmt_reaction_7(unit = "") "";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_reaction_8(unit = "") "";
    Real elmt_reactant14 "";
    Real elmt_product16 "";
    Real elmt_reactant15 "";
    Real elmt_reaction_5(unit = "") "";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_reaction_18(unit = "") "";
    Real elmt_product40 "";
    Real elmt_reaction_6(unit = "") "";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_reaction_19(unit = "") "";
    Real elmt_reactant41 "";
    Real elmt_reaction_20(unit = "") "";
    Real elmt_reactant42 "";
    Real elmt_product44 "";
    Real elmt_reactant43 "";
    Real elmt_reaction_12(unit = "") "";
    Real elmt_reactant26 "";
    Real elmt_reactant27 "";
    Real elmt_product28 "";
    Real elmt_reaction_13(unit = "") "";
    Real elmt_product30 "";
    Real elmt_reactant29 "";
    Real elmt_product31 "";
    Real elmt_reaction_10(unit = "") "";
    Real elmt_reactant20 "";
    Real elmt_product22 "";
    Real elmt_reactant21 "";
    Real elmt_reaction_21(unit = "") "";
    Real elmt_product47 "";
    Real elmt_reactant45 "";
    Real elmt_reactant46 "";
    Real elmt_reaction_11(unit = "") "";
    Real elmt_product25 "";
    Real elmt_product24 "";
    Real elmt_reactant23 "";
    Real elmt_reaction_22(unit = "") "";
    Real elmt_product50 "";
    Real elmt_reactant48 "";
    Real elmt_reactant49 "";


    initial equation
        elmt_product30 = 1.0;
        elmt_reactant41 = 1.0;
        elmt_reactant42 = 1.0;
        elmt_product34 = 1.0;
        elmt_product31 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_reactant49 = 1.0;
        elmt_reactant43 = 1.0;
        elmt_reactant45 = 1.0;
        elmt_reactant46 = 1.0;
        elmt_product25 = 1.0;
        elmt_product24 = 1.0;
        elmt_product28 = 1.0;
        elmt_product40 = 1.0;
        elmt_product44 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_reactant17 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_product38 = 1.0;
        elmt_product37 = 1.0;
        elmt_product36 = 1.0;
        elmt_product50 = 1.0;
        elmt_reactant20 = 1.0;
        elmt_product11 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_product47 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product22 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant39 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant32 = 1.0;
        elmt_reactant33 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant35 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_product16 = 1.0;
        elmt_product13 = 1.0;
        elmt_product19 = 1.0;
        elmt_product18 = 1.0;


    equation
        elmt_reaction_3 = ((((elmt_k1_ERKc * elmt_pERKc) * (((elmt_ppMEKc_tot * elmt_cytosol) - (elmt_pERK_ppMEKc * elmt_cytosol)) - elmt_ERK_ppMEKc)) * elmt_cytosol) - ((elmt_k2_ERKc * elmt_pERK_ppMEKc) * elmt_cytosol));
        elmt_reaction_4 = ((elmt_k3_ERKc * elmt_pERK_ppMEKc) * elmt_cytosol);
        elmt_reaction_1 = ((((elmt_k1_ERKc * elmt_ERKc) * (((elmt_ppMEKc_tot * elmt_cytosol) - (elmt_ERK_ppMEKc * elmt_cytosol)) - elmt_pERK_ppMEKc)) * elmt_cytosol) - ((elmt_k2_ERKc * elmt_ERK_ppMEKc) * elmt_cytosol));
        elmt_reaction_2 = ((elmt_k3_ERKc * elmt_ERK_ppMEKc) * elmt_cytosol);
        elmt_reaction_16 = (((elmt_duspn_basal * (1.0 + ((elmt_duspn_ind * Functions.pow(elmt_ppERKn, 2.0)) / ((Functions.pow(elmt_ppERKn, 2.0) * elmt_nucleus) + Functions.pow(elmt_Kduspn, 2.0))))) * 0.693) / elmt_Tduspn);
        elmt_reaction_17 = (((elmt_duspn * 0.693) / elmt_Tduspn) * elmt_nucleus);
        elmt_reaction_9 = ((elmt_kd3_ppERKc * elmt_ppERK_DUSPc) * elmt_cytosol);
        elmt_reaction_14 = ((((((elmt_kd1_pERKn * elmt_pERKn) * elmt_DUSPn) / 0.22) * elmt_nucleus) - (elmt_kd2_pERKn * elmt_pERK_DUSPn)) * elmt_nucleus);
        elmt_reaction_15 = ((elmt_kd3_pERKn * elmt_pERK_DUSPn) * elmt_nucleus);
        elmt_reaction_7 = (((elmt_k_ppERKin * elmt_ppERKc) * elmt_cytosol) - ((elmt_k_ppERKout * elmt_ppERKn) * elmt_nucleus));
        elmt_reaction_8 = ((((((elmt_kd1_ppERKc * elmt_ppERKc) * elmt_DUSPc) / 0.94) * elmt_cytosol) - (elmt_kd2_ppERKc * elmt_ppERK_DUSPc)) * elmt_cytosol);
        elmt_reaction_5 = (((elmt_k_ERKin * elmt_ERKc) * elmt_cytosol) - ((elmt_k_ERKout * elmt_ERKn) * elmt_nucleus));
        elmt_reaction_18 = (((((elmt_v2 * elmt_duspn) / 0.22) * 0.693) / elmt_TDUSPn) * elmt_nucleus);
        elmt_reaction_6 = (((elmt_k_pERKin * elmt_pERKc) * elmt_cytosol) - ((elmt_k_pERKout * elmt_pERKn) * elmt_nucleus));
        elmt_reaction_19 = (((elmt_DUSPn * 0.693) / elmt_TDUSPn) * elmt_nucleus);
        elmt_reaction_20 = ((((((elmt_k1_ES * elmt_ERKn) * elmt_STYXn) / 0.22) * elmt_nucleus) - (elmt_k2_ES * elmt_ERK_STYXn)) * elmt_nucleus);
        elmt_reaction_12 = ((((((elmt_kd1_ppERKn * elmt_ppERKn) * elmt_DUSPn) / 0.22) * elmt_nucleus) - (elmt_kd2_ppERKn * elmt_ppERK_DUSPn)) * elmt_nucleus);
        elmt_reaction_13 = ((elmt_kd3_ppERKn * elmt_ppERK_DUSPn) * elmt_nucleus);
        elmt_reaction_10 = ((((((elmt_kd1_pERKc * elmt_pERKc) * elmt_DUSPc) / 0.94) * elmt_cytosol) - (elmt_kd2_pERKc * elmt_pERK_DUSPc)) * elmt_cytosol);
        elmt_reaction_21 = ((((((elmt_k1_pES * elmt_pERKn) * elmt_STYXn) / 0.22) * elmt_nucleus) - (elmt_k2_pES * elmt_pERK_STYXn)) * elmt_nucleus);
        elmt_reaction_11 = ((elmt_kd3_pERKc * elmt_pERK_DUSPc) * elmt_cytosol);
        elmt_reaction_22 = ((((((elmt_k1_ppES * elmt_ppERKn) * elmt_STYXn) / 0.22) * elmt_nucleus) - (elmt_k2_ppES * elmt_ppERK_STYXn)) * elmt_nucleus);
        der(elmt_product30) = 0;
        der(elmt_reactant41) = 0;
        der(elmt_reactant42) = 0;
        der(elmt_product34) = 0;
        der(elmt_product31) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_reactant49) = 0;
        der(elmt_reactant43) = 0;
        der(elmt_reactant45) = 0;
        der(elmt_reactant46) = 0;
        der(elmt_product25) = 0;
        der(elmt_product24) = 0;
        der(elmt_product28) = 0;
        der(elmt_product40) = 0;
        der(elmt_product44) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant17) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_product38) = 0;
        der(elmt_product37) = 0;
        der(elmt_product36) = 0;
        der(elmt_product50) = 0;
        der(elmt_reactant20) = 0;
        der(elmt_product11) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_product47) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product22) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant39) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_reactant33) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant35) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_product16) = 0;
        der(elmt_product13) = 0;
        der(elmt_product19) = 0;
        der(elmt_product18) = 0;

end Reactions;
