within BIOMD391;
model S2MModel "Arnold2011_Poolman2000_CalvinCycle_Starch" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_cytosol elmt_cytosol;
    Class_elmt_chloroplast elmt_chloroplast;

    equation
        Reacs.elmt_GAP = elmt_chloroplast.elmt_GAP;
        Reacs.elmt_FBP = elmt_chloroplast.elmt_FBP;
        Reacs.elmt_X5P = elmt_chloroplast.elmt_X5P;
        Reacs.elmt_DPGA = elmt_chloroplast.elmt_DPGA;
        Reacs.elmt_NADP = elmt_chloroplast.elmt_NADP;
        Reacs.elmt_F6P = elmt_chloroplast.elmt_F6P;
        Reacs.elmt_NADPH = elmt_chloroplast.elmt_NADPH;
        Reacs.elmt_H = elmt_chloroplast.elmt_H;
        Reacs.elmt_ATP = elmt_chloroplast.elmt_ATP;
        Reacs.elmt_G1P = elmt_chloroplast.elmt_G1P;
        Reacs.elmt_Ru5P = elmt_chloroplast.elmt_Ru5P;
        Reacs.elmt_DHAP = elmt_chloroplast.elmt_DHAP;
        Reacs.elmt_E4P = elmt_chloroplast.elmt_E4P;
        Reacs.elmt_G6P = elmt_chloroplast.elmt_G6P;
        Reacs.elmt_SBP = elmt_chloroplast.elmt_SBP;
        Reacs.elmt_R5P = elmt_chloroplast.elmt_R5P;
        Reacs.elmt_ADP = elmt_chloroplast.elmt_ADP;
        Reacs.elmt_Pext = elmt_cytosol.elmt_Pext;
        Reacs.elmt_RuBP = elmt_chloroplast.elmt_RuBP;
        Reacs.elmt_Pi = elmt_chloroplast.elmt_Pi;
        Reacs.elmt_S7P = elmt_chloroplast.elmt_S7P;
        Reacs.elmt_chloroplast = elmt_chloroplast.elmt_chloroplast;
        Reacs.elmt_PGA = elmt_chloroplast.elmt_PGA;
        elmt_chloroplast.elmt_reactant42 = Reacs.elmt_reactant42;
        elmt_chloroplast.elmt_Starch_S = Reacs.elmt_Starch_S;
        elmt_chloroplast.elmt_product33 = Reacs.elmt_product33;
        elmt_chloroplast.elmt_product32 = Reacs.elmt_product32;
        elmt_chloroplast.elmt_Starch_P = Reacs.elmt_Starch_P;
        elmt_chloroplast.elmt_RuBisCO = Reacs.elmt_RuBisCO;
        elmt_chloroplast.elmt_reactant47 = Reacs.elmt_reactant47;
        elmt_chloroplast.elmt_TP_I = Reacs.elmt_TP_I;
        elmt_chloroplast.elmt_reactant44 = Reacs.elmt_reactant44;
        elmt_chloroplast.elmt_reactant46 = Reacs.elmt_reactant46;
        elmt_chloroplast.elmt_product26 = Reacs.elmt_product26;
        elmt_chloroplast.elmt_product28 = Reacs.elmt_product28;
        elmt_chloroplast.elmt_product40 = Reacs.elmt_product40;
        elmt_chloroplast.elmt_reactant53 = Reacs.elmt_reactant53;
        elmt_chloroplast.elmt_F6P_TK = Reacs.elmt_F6P_TK;
        elmt_chloroplast.elmt_product45 = Reacs.elmt_product45;
        elmt_chloroplast.elmt_product43 = Reacs.elmt_product43;
        elmt_chloroplast.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_chloroplast.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_chloroplast.elmt_SBP_A = Reacs.elmt_SBP_A;
        elmt_chloroplast.elmt_reactant17 = Reacs.elmt_reactant17;
        elmt_chloroplast.elmt_reactant54 = Reacs.elmt_reactant54;
        elmt_chloroplast.elmt_reactant55 = Reacs.elmt_reactant55;
        elmt_chloroplast.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_chloroplast.elmt_Ru5P_K = Reacs.elmt_Ru5P_K;
        elmt_chloroplast.elmt_PGA_K = Reacs.elmt_PGA_K;
        elmt_chloroplast.elmt_product37 = Reacs.elmt_product37;
        elmt_chloroplast.elmt_product35 = Reacs.elmt_product35;
        elmt_chloroplast.elmt_FBPase = Reacs.elmt_FBPase;
        elmt_chloroplast.elmt_Ru5P_E = Reacs.elmt_Ru5P_E;
        elmt_chloroplast.elmt_product52 = Reacs.elmt_product52;
        elmt_chloroplast.elmt_reactant20 = Reacs.elmt_reactant20;
        elmt_chloroplast.elmt_ATP_S = Reacs.elmt_ATP_S;
        elmt_chloroplast.elmt_FBP_A = Reacs.elmt_FBP_A;
        elmt_chloroplast.elmt_reactant25 = Reacs.elmt_reactant25;
        elmt_chloroplast.elmt_PG_I = Reacs.elmt_PG_I;
        elmt_chloroplast.elmt_reactant27 = Reacs.elmt_reactant27;
        elmt_chloroplast.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_chloroplast.elmt_GAP_DH = Reacs.elmt_GAP_DH;
        elmt_chloroplast.elmt_PG_M = Reacs.elmt_PG_M;
        elmt_chloroplast.elmt_reactant24 = Reacs.elmt_reactant24;
        elmt_chloroplast.elmt_TPT_PGA = Reacs.elmt_TPT_PGA;
        elmt_chloroplast.elmt_product49 = Reacs.elmt_product49;
        elmt_chloroplast.elmt_TPT_GAP = Reacs.elmt_TPT_GAP;
        elmt_chloroplast.elmt_product9 = Reacs.elmt_product9;
        elmt_chloroplast.elmt_reactant2 = Reacs.elmt_reactant2;
        elmt_chloroplast.elmt_reactant30 = Reacs.elmt_reactant30;
        elmt_chloroplast.elmt_R5P_I = Reacs.elmt_R5P_I;
        elmt_chloroplast.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_chloroplast.elmt_reactant31 = Reacs.elmt_reactant31;
        elmt_chloroplast.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_chloroplast.elmt_product23 = Reacs.elmt_product23;
        elmt_chloroplast.elmt_product22 = Reacs.elmt_product22;
        elmt_chloroplast.elmt_reactant36 = Reacs.elmt_reactant36;
        elmt_chloroplast.elmt_product1 = Reacs.elmt_product1;
        elmt_chloroplast.elmt_reactant38 = Reacs.elmt_reactant38;
        elmt_chloroplast.elmt_reactant39 = Reacs.elmt_reactant39;
        elmt_chloroplast.elmt_product4 = Reacs.elmt_product4;
        elmt_chloroplast.elmt_reactant34 = Reacs.elmt_reactant34;
        elmt_chloroplast.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_chloroplast.elmt_product16 = Reacs.elmt_product16;
        elmt_chloroplast.elmt_SBPase = Reacs.elmt_SBPase;
        elmt_chloroplast.elmt_S7P_TK = Reacs.elmt_S7P_TK;
        elmt_chloroplast.elmt_product13 = Reacs.elmt_product13;
        elmt_chloroplast.elmt_TPT_DHAP = Reacs.elmt_TPT_DHAP;
        elmt_chloroplast.elmt_product18 = Reacs.elmt_product18;

end S2MModel;
