within BIOMD250;
class Class_elmt_nucleus

    input Real elmt_product73;
    input Real elmt_product71;
    input Real elmt_reactant109;
    input Real elmt_product75;
    input Real elmt_reactant47;
    input Real elmt_reactant49;
    input Real elmt_reactant45;
    input Real elmt_product69;
    input Real elmt_reactant116;
    input Real elmt_reactant51;
    input Real elmt_product83;
    input Real elmt_product82;
    input Real elmt_product89;
    input Real elmt_product88;
    input Real elmt_product86;
    input Real elmt_reactant54;
    input Real elmt_product80;
    input Real elmt_product101;
    input Real elmt_product104;
    input Real elmt_reaction_58;
    input Real elmt_product103;
    input Real elmt_reaction_52;
    input Real elmt_reaction_53;
    input Real elmt_reaction_56;
    input Real elmt_reaction_57;
    input Real elmt_reaction_54;
    input Real elmt_product108;
    input Real elmt_reaction_55;
    input Real elmt_product107;
    input Real elmt_product95;
    input Real elmt_product11;
    input Real elmt_product98;
    input Real elmt_product97;
    input Real elmt_product92;
    input Real elmt_reaction_47;
    input Real elmt_reactant19;
    input Real elmt_reaction_45;
    input Real elmt_reaction_46;
    input Real elmt_product9;
    input Real elmt_re107;
    input Real elmt_re108;
    input Real elmt_reactant37;
    input Real elmt_re109;
    input Real elmt_reactant38;
    input Real elmt_reactant33;
    input Real elmt_re106;
    input Real elmt_reactant35;
    input Real elmt_reaction_30;
    input Real elmt_reactant106;
    input Real elmt_product15;
    input Real elmt_reactant105;
    input Real elmt_product13;
    input Real elmt_reactant102;
    input Real elmt_product18;
    input Real elmt_product17;
    input Real elmt_reactant100;
    input Real elmt_product30;
    input Real elmt_reactant84;
    input Real elmt_reactant85;
    input Real elmt_product34;
    input Real elmt_reactant81;
    input Real elmt_product32;
    input Real elmt_re118;
    input Real elmt_re119;
    input Real elmt_reactant87;
    input Real elmt_re115;
    input Real elmt_re116;
    input Real elmt_re117;
    input Real elmt_reaction_27;
    input Real elmt_re110;
    input Real elmt_reaction_28;
    input Real elmt_re111;
    input Real elmt_reaction_25;
    input Real elmt_re112;
    input Real elmt_re113;
    input Real elmt_reaction_26;
    input Real elmt_reaction_29;
    input Real elmt_reaction_23;
    input Real elmt_reaction_24;
    input Real elmt_reaction_21;
    input Real elmt_reaction_22;
    input Real elmt_reactant94;
    input Real elmt_reactant96;
    input Real elmt_reactant90;
    input Real elmt_product44;
    input Real elmt_reactant91;
    input Real elmt_reactant93;
    input Real elmt_reactant10;
    input Real elmt_reactant99;
    input Real elmt_reaction_14;
    input Real elmt_reaction_15;
    input Real elmt_product36;
    input Real elmt_reaction_12;
    input Real elmt_reaction_13;
    input Real elmt_product52;
    input Real elmt_product50;
    input Real elmt_product53;
    input Real elmt_re99;
    input Real elmt_product115;
    input Real elmt_product48;
    input Real elmt_product46;
    input Real elmt_reactant72;
    input Real elmt_reactant74;
    input Real elmt_product67;
    input Real elmt_reactant70;
    input Real elmt_reactant8;
    input Real elmt_re87;
    input Real elmt_reactant76;
    input Real elmt_re88;
    input Real elmt_reactant77;
    input Real elmt_reactant78;
    input Real elmt_reactant79;
    input Real elmt_re92;

    Real elmt_nucleus(unit = "") "nucleus";
    Real elmt_pCREB_n_conc(unit = "");
    Real elmt_pCREB_n_amount(unit = "");
    Real elmt_pCREB_n(unit = "") "pCREB_n";
    Real elmt_pRSK_n_conc(unit = "");
    Real elmt_pRSK_n_amount(unit = "");
    Real elmt_pRSK_n(unit = "") "pRSK_n";
    Real elmt_PreFOSmRNA_conc(unit = "");
    Real elmt_PreFOSmRNA_amount(unit = "");
    Real elmt_PreFOSmRNA(unit = "") "PreFOSmRNA";
    Real elmt_pDUSP_n_ppERK_n_conc(unit = "");
    Real elmt_pDUSP_n_ppERK_n_amount(unit = "");
    Real elmt_pDUSP_n_ppERK_n(unit = "") "pDUSP_n_ppERK_n";
    Real elmt_CREB_n_conc(unit = "");
    Real elmt_CREB_n_amount(unit = "");
    Real elmt_CREB_n(unit = "") "CREB_n";
    Real elmt_ERK_n_conc(unit = "");
    Real elmt_ERK_n_amount(unit = "");
    Real elmt_ERK_n(unit = "") "ERK_n";
    Real elmt_FOSn_conc(unit = "");
    Real elmt_FOSn_amount(unit = "");
    Real elmt_FOSn(unit = "") "FOSn";
    Real elmt_DUSP_n_ppERK_n_conc(unit = "");
    Real elmt_DUSP_n_ppERK_n_amount(unit = "");
    Real elmt_DUSP_n_ppERK_n(unit = "") "DUSP_n_ppERK_n";
    Real elmt_ppERK_n_conc(unit = "");
    Real elmt_ppERK_n_amount(unit = "");
    Real elmt_ppERK_n(unit = "") "ppERK_n";
    Real elmt_DUSP_n_ERK_n_conc(unit = "");
    Real elmt_DUSP_n_ERK_n_amount(unit = "");
    Real elmt_DUSP_n_ERK_n(unit = "") "DUSP_n_ERK_n";
    Real elmt_pERK_n_conc(unit = "");
    Real elmt_pERK_n_amount(unit = "");
    Real elmt_pERK_n(unit = "") "pERK_n";
    Real elmt_FOSn_2_conc(unit = "");
    Real elmt_FOSn_2_amount(unit = "");
    Real elmt_FOSn_2(unit = "") "FOSn_2";
    Real elmt_Fn_conc(unit = "");
    Real elmt_Fn_amount(unit = "");
    Real elmt_Fn(unit = "") "Fn";
    Real elmt_pDUSP_n_pERK_n_conc(unit = "");
    Real elmt_pDUSP_n_pERK_n_amount(unit = "");
    Real elmt_pDUSP_n_pERK_n(unit = "") "pDUSP_n_pERK_n";
    Real elmt_pDUSP_n_ERK_n_conc(unit = "");
    Real elmt_pDUSP_n_ERK_n_amount(unit = "");
    Real elmt_pDUSP_n_ERK_n(unit = "") "pDUSP_n_ERK_n";
    Real elmt_DUSP_n_pERK_n_conc(unit = "");
    Real elmt_DUSP_n_pERK_n_amount(unit = "");
    Real elmt_DUSP_n_pERK_n(unit = "") "DUSP_n_pERK_n";
    Real elmt_PreFmRNA_conc(unit = "");
    Real elmt_PreFmRNA_amount(unit = "");
    Real elmt_PreFmRNA(unit = "") "PreFmRNA";
    Real elmt_PreDUSPmRNA_conc(unit = "");
    Real elmt_PreDUSPmRNA_amount(unit = "");
    Real elmt_PreDUSPmRNA(unit = "") "PreDUSPmRNA";
    Real elmt_pDUSP_n_conc(unit = "");
    Real elmt_pDUSP_n_amount(unit = "");
    Real elmt_pDUSP_n(unit = "") "pDUSP_n";
    Real elmt_Elk1_n_conc(unit = "");
    Real elmt_Elk1_n_amount(unit = "");
    Real elmt_Elk1_n(unit = "") "Elk1_n";
    Real elmt_DUSP_n_conc(unit = "");
    Real elmt_DUSP_n_amount(unit = "");
    Real elmt_DUSP_n(unit = "") "DUSP_n";
    Real elmt_pElk1_n_conc(unit = "");
    Real elmt_pElk1_n_amount(unit = "");
    Real elmt_pElk1_n(unit = "") "pElk1_n";

    initial equation
        elmt_nucleus = 220.0;
        elmt_pCREB_n_conc = 0.0;
        elmt_pRSK_n_conc = 0.0;
        elmt_PreFOSmRNA_conc = 0.0;
        elmt_pDUSP_n_ppERK_n_conc = 0.0;
        elmt_CREB_n_conc = 1000.0;
        elmt_ERK_n_conc = 1624.9;
        elmt_FOSn_conc = 0.0;
        elmt_DUSP_n_ppERK_n_conc = 0.0;
        elmt_ppERK_n_conc = 0.0;
        elmt_DUSP_n_ERK_n_conc = 0.0;
        elmt_pERK_n_conc = 0.0;
        elmt_FOSn_2_conc = 0.0;
        elmt_Fn_conc = 0.0;
        elmt_pDUSP_n_pERK_n_conc = 0.0;
        elmt_pDUSP_n_ERK_n_conc = 0.0;
        elmt_DUSP_n_pERK_n_conc = 0.0;
        elmt_PreFmRNA_conc = 0.0;
        elmt_PreDUSPmRNA_conc = 0.0;
        elmt_pDUSP_n_conc = 0.0;
        elmt_Elk1_n_conc = 1510.0;
        elmt_DUSP_n_conc = 0.0;
        elmt_pElk1_n_conc = 0.0;


    equation
        assert(elmt_nucleus >= 0, "Compartment size became negative. Make sure this is a valid bahaviour.");
        der(elmt_nucleus) = 0;
        elmt_pCREB_n = elmt_pCREB_n_conc;
        elmt_pRSK_n = elmt_pRSK_n_conc;
        elmt_PreFOSmRNA = elmt_PreFOSmRNA_conc;
        elmt_pDUSP_n_ppERK_n = elmt_pDUSP_n_ppERK_n_conc;
        elmt_CREB_n = elmt_CREB_n_conc;
        elmt_ERK_n = elmt_ERK_n_conc;
        elmt_FOSn = elmt_FOSn_conc;
        elmt_DUSP_n_ppERK_n = elmt_DUSP_n_ppERK_n_conc;
        elmt_ppERK_n = elmt_ppERK_n_conc;
        elmt_DUSP_n_ERK_n = elmt_DUSP_n_ERK_n_conc;
        elmt_pERK_n = elmt_pERK_n_conc;
        elmt_FOSn_2 = elmt_FOSn_2_conc;
        elmt_Fn = elmt_Fn_conc;
        elmt_pDUSP_n_pERK_n = elmt_pDUSP_n_pERK_n_conc;
        elmt_pDUSP_n_ERK_n = elmt_pDUSP_n_ERK_n_conc;
        elmt_DUSP_n_pERK_n = elmt_DUSP_n_pERK_n_conc;
        elmt_PreFmRNA = elmt_PreFmRNA_conc;
        elmt_PreDUSPmRNA = elmt_PreDUSPmRNA_conc;
        elmt_pDUSP_n = elmt_pDUSP_n_conc;
        elmt_Elk1_n = elmt_Elk1_n_conc;
        elmt_DUSP_n = elmt_DUSP_n_conc;
        elmt_pElk1_n = elmt_pElk1_n_conc;
        der(elmt_pCREB_n_amount) = ((elmt_reaction_45 * elmt_product46) + (- (elmt_reaction_46 * elmt_reactant47)));
        der(elmt_pRSK_n_amount) = (elmt_re113 * elmt_product44);
        der(elmt_PreFOSmRNA_amount) = ((- (elmt_re115 * elmt_reactant54)) + (elmt_reaction_47 * elmt_product53));
        der(elmt_pDUSP_n_ppERK_n_amount) = ((elmt_reaction_25 * elmt_product80) + (- (elmt_reaction_26 * elmt_reactant81)));
        der(elmt_CREB_n_amount) = ((- (elmt_reaction_45 * elmt_reactant45)) + (elmt_reaction_46 * elmt_product48));
        der(elmt_ERK_n_amount) = ((elmt_reaction_28 * elmt_product89) + (- (elmt_reaction_29 * elmt_reactant106)) + (elmt_reaction_24 * elmt_product104) + (elmt_re87 * elmt_product9) + (elmt_re106 * elmt_product13) + (- (elmt_reaction_30 * elmt_reactant91)));
        der(elmt_FOSn_amount) = ((elmt_re116 * elmt_product67) + (- (elmt_reaction_52 * elmt_reactant70)) + (- (elmt_reaction_53 * elmt_reactant72)) + (elmt_reaction_54 * elmt_product75) + (- (elmt_reaction_55 * elmt_reactant76)));
        der(elmt_DUSP_n_ppERK_n_amount) = ((elmt_reaction_21 * elmt_product95) + (- (elmt_reaction_22 * elmt_reactant96)));
        der(elmt_ppERK_n_amount) = ((- (elmt_reaction_25 * elmt_reactant79)) + (- (elmt_reaction_21 * elmt_reactant94)) + (elmt_re108 * elmt_product17) + (- (elmt_re88 * elmt_reactant10)));
        der(elmt_DUSP_n_ERK_n_amount) = (elmt_reaction_29 * elmt_product107);
        der(elmt_pERK_n_amount) = ((- (elmt_reaction_27 * elmt_reactant85)) + (elmt_reaction_26 * elmt_product83) + (- (elmt_reaction_23 * elmt_reactant100)) + (elmt_reaction_22 * elmt_product98) + (elmt_re107 * elmt_product15) + (- (elmt_re87 * elmt_reactant8)) + (elmt_re88 * elmt_product11));
        der(elmt_FOSn_2_amount) = ((elmt_re117 * elmt_product69) + (elmt_reaction_52 * elmt_product71) + (elmt_reaction_53 * elmt_product73) + (- (elmt_reaction_56 * elmt_reactant77)) + (- (elmt_reaction_54 * elmt_reactant74)));
        der(elmt_Fn_amount) = ((elmt_re119 * elmt_product115) + (- (elmt_re99 * elmt_reactant116)));
        der(elmt_pDUSP_n_pERK_n_amount) = ((elmt_reaction_27 * elmt_product86) + (- (elmt_reaction_28 * elmt_reactant87)));
        der(elmt_pDUSP_n_ERK_n_amount) = (elmt_reaction_30 * elmt_product92);
        der(elmt_DUSP_n_pERK_n_amount) = ((elmt_reaction_23 * elmt_product101) + (- (elmt_reaction_24 * elmt_reactant102)));
        der(elmt_PreFmRNA_amount) = ((- (elmt_re118 * elmt_reactant109)) + (elmt_re92 * elmt_product108));
        der(elmt_PreDUSPmRNA_amount) = ((- (elmt_re110 * elmt_reactant19)) + (elmt_re109 * elmt_product18));
        der(elmt_pDUSP_n_amount) = ((- (elmt_reaction_27 * elmt_reactant84)) + (elmt_reaction_28 * elmt_product88) + (elmt_re112 * elmt_product32) + (- (elmt_reaction_25 * elmt_reactant78)) + (elmt_reaction_26 * elmt_product82) + (- (elmt_reaction_15 * elmt_reactant38)) + (elmt_reaction_12 * elmt_product34) + (- (elmt_reaction_13 * elmt_reactant35)) + (- (elmt_reaction_30 * elmt_reactant90)));
        der(elmt_Elk1_n_amount) = ((elmt_reaction_58 * elmt_product52) + (- (elmt_reaction_57 * elmt_reactant49)));
        der(elmt_DUSP_n_amount) = ((elmt_re111 * elmt_product30) + (- (elmt_reaction_29 * elmt_reactant105)) + (- (elmt_reaction_23 * elmt_reactant99)) + (elmt_reaction_24 * elmt_product103) + (- (elmt_reaction_21 * elmt_reactant93)) + (elmt_reaction_22 * elmt_product97) + (- (elmt_reaction_14 * elmt_reactant37)) + (- (elmt_reaction_12 * elmt_reactant33)) + (elmt_reaction_13 * elmt_product36));
        der(elmt_pElk1_n_amount) = ((- (elmt_reaction_58 * elmt_reactant51)) + (elmt_reaction_57 * elmt_product50));

    algorithm
        elmt_pCREB_n_conc := elmt_pCREB_n_amount / elmt_nucleus;
        elmt_pRSK_n_conc := elmt_pRSK_n_amount / elmt_nucleus;
        elmt_PreFOSmRNA_conc := elmt_PreFOSmRNA_amount / elmt_nucleus;
        elmt_pDUSP_n_ppERK_n_conc := elmt_pDUSP_n_ppERK_n_amount / elmt_nucleus;
        elmt_CREB_n_conc := elmt_CREB_n_amount / elmt_nucleus;
        elmt_ERK_n_conc := elmt_ERK_n_amount / elmt_nucleus;
        elmt_FOSn_conc := elmt_FOSn_amount / elmt_nucleus;
        elmt_DUSP_n_ppERK_n_conc := elmt_DUSP_n_ppERK_n_amount / elmt_nucleus;
        elmt_ppERK_n_conc := elmt_ppERK_n_amount / elmt_nucleus;
        elmt_DUSP_n_ERK_n_conc := elmt_DUSP_n_ERK_n_amount / elmt_nucleus;
        elmt_pERK_n_conc := elmt_pERK_n_amount / elmt_nucleus;
        elmt_FOSn_2_conc := elmt_FOSn_2_amount / elmt_nucleus;
        elmt_Fn_conc := elmt_Fn_amount / elmt_nucleus;
        elmt_pDUSP_n_pERK_n_conc := elmt_pDUSP_n_pERK_n_amount / elmt_nucleus;
        elmt_pDUSP_n_ERK_n_conc := elmt_pDUSP_n_ERK_n_amount / elmt_nucleus;
        elmt_DUSP_n_pERK_n_conc := elmt_DUSP_n_pERK_n_amount / elmt_nucleus;
        elmt_PreFmRNA_conc := elmt_PreFmRNA_amount / elmt_nucleus;
        elmt_PreDUSPmRNA_conc := elmt_PreDUSPmRNA_amount / elmt_nucleus;
        elmt_pDUSP_n_conc := elmt_pDUSP_n_amount / elmt_nucleus;
        elmt_Elk1_n_conc := elmt_Elk1_n_amount / elmt_nucleus;
        elmt_DUSP_n_conc := elmt_DUSP_n_amount / elmt_nucleus;
        elmt_pElk1_n_conc := elmt_pElk1_n_amount / elmt_nucleus;
end Class_elmt_nucleus;
