within BIOMD111;
class Parameters

    input Real elmt_cdc13T;
    input Real elmt_M;
    input Real elmt_MPF;
    input Real elmt_rum1T;

    input Boolean elmt_event_0000001;    input Boolean elmt_event_0000002;
    input Real assign_elmt_flag_MPF;


    Real elmt_k3_double_prime(unit = "s-1.0") "";
    Real elmt_Va25(unit = "s-1.0") "";
    Real elmt_k5_double_prime(unit = "s-1.0") "";
    Real elmt_Kdiss(unit = "") "";
    Real elmt_k2_triple_prime(unit = "s-1.0") "";
    Real elmt_TF(unit = "") "";
    Real elmt_sigma(unit = "") "";
    Real elmt_k15(unit = "s-1.0") "";
    Real elmt_k14(unit = "s-1.0") "";
    Real elmt_k13(unit = "s-1.0") "";
    Real elmt_k12(unit = "s-1.0") "";
    Real elmt_k11(unit = "s-1.0") "";
    Real elmt_k25_double_prime(unit = "s-1.0") "";
    Real elmt_k3_prime(unit = "s-1.0") "";
    Real elmt_k10(unit = "s-1.0") "";
    Real elmt_k1(unit = "s-1.0") "";
    Real elmt_Ji25(unit = "") "";
    Real elmt_Viwee(unit = "s-1.0") "";
    Real elmt_flag_MPF(unit = "") "";
    Real elmt_J7(unit = "") "";
    Real elmt_k8(unit = "s-1.0") "";
    Real elmt_J8(unit = "") "";
    Real elmt_k9(unit = "s-1.0") "";
    Real elmt_Vawee(unit = "s-1.0") "";
    Real elmt_J5(unit = "") "";
    Real elmt_k6(unit = "s-1.0") "";
    Real elmt_k7(unit = "s-1.0") "";
    Real elmt_J3(unit = "") "";
    Real elmt_k4(unit = "s-1.0") "";
    Real elmt_J4(unit = "") "";
    Real elmt_kwee_prime(unit = "s-1.0") "";
    Real elmt_k12_prime(unit = "s-1.0") "";
    Real elmt_mu(unit = "s-1.0") "";
    Real elmt_J16(unit = "") "";
    Real elmt_k2_prime(unit = "s-1.0") "";
    Real elmt_k25(unit = "s-1.0") "";
    Real elmt_J15(unit = "") "";
    Real elmt_Vi25(unit = "s-1.0") "";
    Real elmt_Ja25(unit = "") "";
    Real elmt_J10(unit = "") "";
    Real elmt_k2_double_prime(unit = "s-1.0") "";
    Real elmt_Jawee(unit = "") "";
    Real elmt_k5_prime(unit = "s-1.0") "";
    Real elmt_Jiwee(unit = "") "";
    Real elmt_k16_prime(unit = "s-1.0") "";
    Real elmt_J9(unit = "") "";
    Real elmt_kwee_double_prime(unit = "s-1.0") "";
    Real elmt_Trimer(unit = "") "";
    Real elmt_k12_double_prime(unit = "s-1.0") "";
    Real elmt_k25_prime(unit = "s-1.0") "";
    Real elmt_k4_prime(unit = "s-1.0") "";
    Real elmt_kwee(unit = "s-1.0") "";
    Real elmt_k16_double_prime(unit = "s-1.0") "";


    initial equation
        elmt_k3_double_prime = 10.0;
        elmt_Va25 = 1.0;
        elmt_k5_double_prime = 0.3;
        elmt_Kdiss = 0.001;
        elmt_k2_triple_prime = 0.1;
        elmt_k15 = 1.5;
        elmt_k14 = 0.1;
        elmt_k13 = 0.1;
        elmt_k12 = 0.01;
        elmt_k11 = 0.1;
        elmt_k25_double_prime = 5.0;
        elmt_k3_prime = 1.0;
        elmt_k10 = 0.04;
        elmt_k1 = 0.03;
        elmt_Ji25 = 0.01;
        elmt_Viwee = 1.0;
        elmt_flag_MPF = 0.0;
        elmt_J7 = 0.001;
        elmt_k8 = 0.25;
        elmt_J8 = 0.001;
        elmt_k9 = 0.1;
        elmt_Vawee = 0.25;
        elmt_J5 = 0.3;
        elmt_k6 = 0.1;
        elmt_k7 = 1.0;
        elmt_J3 = 0.01;
        elmt_k4 = 35.0;
        elmt_J4 = 0.01;
        elmt_kwee_prime = 0.15;
        elmt_k12_prime = 1.0;
        elmt_mu = 0.005;
        elmt_J16 = 0.01;
        elmt_k2_prime = 0.03;
        elmt_J15 = 0.01;
        elmt_Vi25 = 0.25;
        elmt_Ja25 = 0.01;
        elmt_J10 = 0.01;
        elmt_k2_double_prime = 1.0;
        elmt_Jawee = 0.01;
        elmt_k5_prime = 0.005;
        elmt_Jiwee = 0.01;
        elmt_k16_prime = 1.0;
        elmt_J9 = 0.01;
        elmt_kwee_double_prime = 1.3;
        elmt_k12_double_prime = 3.0;
        elmt_k25_prime = 0.05;
        elmt_k4_prime = 2.0;
        elmt_k16_double_prime = 2.0;


    equation
        der(elmt_k3_double_prime) = 0;
        der(elmt_Va25) = 0;
        der(elmt_k5_double_prime) = 0;
        der(elmt_Kdiss) = 0;
        der(elmt_k2_triple_prime) = 0;
        elmt_TF = ((2.0 * elmt_k15 * elmt_M * elmt_J16) / (((elmt_k16_prime + (elmt_k16_double_prime * elmt_MPF)) - (elmt_k15 * elmt_M)) + ((elmt_k16_prime + (elmt_k16_double_prime * elmt_MPF)) * elmt_J15) + (elmt_k15 * elmt_M * elmt_J16) + Functions.root(2.0, (Functions.pow((((elmt_k16_prime + (elmt_k16_double_prime * elmt_MPF)) - (elmt_k15 * elmt_M)) + ((elmt_k16_prime + (elmt_k16_double_prime * elmt_MPF)) * elmt_J15) + (elmt_k15 * elmt_M * elmt_J16)), 2.0) - (4.0 * ((elmt_k16_prime + (elmt_k16_double_prime * elmt_MPF)) - (elmt_k15 * elmt_M)) * elmt_k15 * elmt_M * elmt_J16)))));
        elmt_sigma = (elmt_cdc13T + elmt_rum1T + elmt_Kdiss);
        der(elmt_k15) = 0;
        der(elmt_k14) = 0;
        der(elmt_k13) = 0;
        der(elmt_k12) = 0;
        der(elmt_k11) = 0;
        der(elmt_k25_double_prime) = 0;
        der(elmt_k3_prime) = 0;
        der(elmt_k10) = 0;
        der(elmt_k1) = 0;
        der(elmt_Ji25) = 0;
        der(elmt_Viwee) = 0;
        der(elmt_flag_MPF) = 0.0;
        der(elmt_J7) = 0;
        der(elmt_k8) = 0;
        der(elmt_J8) = 0;
        der(elmt_k9) = 0;
        der(elmt_Vawee) = 0;
        der(elmt_J5) = 0;
        der(elmt_k6) = 0;
        der(elmt_k7) = 0;
        der(elmt_J3) = 0;
        der(elmt_k4) = 0;
        der(elmt_J4) = 0;
        der(elmt_kwee_prime) = 0;
        der(elmt_k12_prime) = 0;
        der(elmt_mu) = 0;
        der(elmt_J16) = 0;
        der(elmt_k2_prime) = 0;
        elmt_k25 = (elmt_k25_prime + ((elmt_k25_double_prime - elmt_k25_prime) * ((2.0 * elmt_Va25 * elmt_MPF * elmt_Ji25) / ((elmt_Vi25 - (elmt_Va25 * elmt_MPF)) + (elmt_Vi25 * elmt_Ja25) + (elmt_Va25 * elmt_MPF * elmt_Ji25) + Functions.root(2.0, (Functions.pow(((elmt_Vi25 - (elmt_Va25 * elmt_MPF)) + (elmt_Vi25 * elmt_Ja25) + (elmt_Va25 * elmt_MPF * elmt_Ji25)), 2.0) - (4.0 * (elmt_Vi25 - (elmt_Va25 * elmt_MPF)) * elmt_Va25 * elmt_MPF * elmt_Ji25)))))));
        der(elmt_J15) = 0;
        der(elmt_Vi25) = 0;
        der(elmt_Ja25) = 0;
        der(elmt_J10) = 0;
        der(elmt_k2_double_prime) = 0;
        der(elmt_Jawee) = 0;
        der(elmt_k5_prime) = 0;
        der(elmt_Jiwee) = 0;
        der(elmt_k16_prime) = 0;
        der(elmt_J9) = 0;
        der(elmt_kwee_double_prime) = 0;
        elmt_Trimer = ((2.0 * elmt_cdc13T * elmt_rum1T) / (elmt_sigma + Functions.pow((Functions.pow(elmt_sigma, 2.0) - (4.0 * elmt_cdc13T * elmt_rum1T)), 0.5)));
        der(elmt_k12_double_prime) = 0;
        der(elmt_k25_prime) = 0;
        der(elmt_k4_prime) = 0;
        elmt_kwee = (elmt_kwee_prime + ((elmt_kwee_double_prime - elmt_kwee_prime) * ((2.0 * elmt_Vawee * elmt_Jiwee) / (((elmt_Viwee * elmt_MPF) - elmt_Vawee) + (elmt_Viwee * elmt_MPF * elmt_Jawee) + (elmt_Vawee * elmt_Jiwee) + Functions.root(2.0, (Functions.pow((((elmt_Viwee * elmt_MPF) - elmt_Vawee) + (elmt_Viwee * elmt_MPF * elmt_Jawee) + (elmt_Vawee * elmt_Jiwee)), 2.0) - (4.0 * ((elmt_Viwee * elmt_MPF) - elmt_Vawee) * elmt_Vawee * elmt_Jiwee)))))));
        der(elmt_k16_double_prime) = 0;

        when elmt_event_0000001 then
            reinit(elmt_flag_MPF, assign_elmt_flag_MPF);
        end when;
        when elmt_event_0000002 then
            reinit(elmt_flag_MPF, assign_elmt_flag_MPF);
        end when;
end Parameters;
