within BIOMD105;
class Class_elmt_cytosol

    input Real elmt_reactant42;
    input Real elmt_reactant47;
    input Real elmt_reactant43;
    input Real elmt_reactant46;
    input Real elmt_reactant50;
    input Real elmt_reactant51;
    input Real elmt_reactant58;
    input Real elmt_reactant59;
    input Real elmt_reactant54;
    input Real elmt_reactant55;
    input Real elmt_MisPE3Release;
    input Real elmt_reactant25;
    input Real elmt_reactant26;
    input Real elmt_reactant21;
    input Real elmt_reactant22;
    input Real elmt_Deubiqutination3;
    input Real elmt_Deubiqutination2;
    input Real elmt_reactant30;
    input Real elmt_Deubiqutination5;
    input Real elmt_Deubiqutination4;
    input Real elmt_reactant31;
    input Real elmt_Deubiqutination7;
    input Real elmt_Deubiqutination6;
    input Real elmt_Deubiqutination8;
    input Real elmt_reactant38;
    input Real elmt_reactant39;
    input Real elmt_Monoubiquitination;
    input Real elmt_reactant34;
    input Real elmt_Deubiqutination1;
    input Real elmt_reactant35;
    input Real elmt_reactant16;
    input Real elmt_reactant17;
    input Real elmt_reactant10;
    input Real elmt_reactant11;
    input Real elmt_reactant13;
    input Real elmt_product192;
    input Real elmt_product195;
    input Real elmt_product198;
    input Real elmt_reactant2;
    input Real elmt_reactant3;
    input Real elmt_reactant7;
    input Real elmt_ProteinSynthesis;
    input Real elmt_Polyubiquitination6;
    input Real elmt_Polyubiquitination7;
    input Real elmt_Polyubiquitination2;
    input Real elmt_Polyubiquitination3;
    input Real elmt_Polyubiquitination4;
    input Real elmt_Polyubiquitination5;
    input Real elmt_Aggregation16;
    input Real elmt_Aggregation17;
    input Real elmt_Aggregation14;
    input Real elmt_Aggregation15;
    input Real elmt_Aggregation12;
    input Real elmt_Aggregation13;
    input Real elmt_Aggregation10;
    input Real elmt_Aggregation11;
    input Real elmt_Polyubiquitination1;
    input Real elmt_Aggregation18;
    input Real elmt_Aggregation19;
    input Real elmt_product9;
    input Real elmt_product8;
    input Real elmt_product6;
    input Real elmt_product1;
    input Real elmt_product5;
    input Real elmt_product4;
    input Real elmt_reactant83;
    input Real elmt_reactant84;
    input Real elmt_Aggregation41;
    input Real elmt_Aggregation42;
    input Real elmt_Aggregation40;
    input Real elmt_reactant88;
    input Real elmt_reactant89;
    input Real elmt_Aggregation49;
    input Real elmt_Aggregation47;
    input Real elmt_Aggregation48;
    input Real elmt_Aggregation45;
    input Real elmt_Aggregation46;
    input Real elmt_Aggregation43;
    input Real elmt_Aggregation44;
    input Real elmt_reactant94;
    input Real elmt_Misfolding;
    input Real elmt_reactant93;
    input Real elmt_Aggregation52;
    input Real elmt_Aggregation53;
    input Real elmt_Aggregation50;
    input Real elmt_Aggregation51;
    input Real elmt_reactant98;
    input Real elmt_reactant99;
    input Real elmt_Aggregation54;
    input Real elmt_reactant63;
    input Real elmt_reactant64;
    input Real elmt_reactant69;
    input Real elmt_Aggregation20;
    input Real elmt_reactant68;
    input Real elmt_Aggregation27;
    input Real elmt_Aggregation28;
    input Real elmt_Aggregation25;
    input Real elmt_Aggregation26;
    input Real elmt_Aggregation23;
    input Real elmt_Aggregation24;
    input Real elmt_Aggregation21;
    input Real elmt_Aggregation22;
    input Real elmt_Aggregation29;
    input Real elmt_E1UbBinding;
    input Real elmt_reactant73;
    input Real elmt_DeubiquitinationBoundMisP5;
    input Real elmt_reactant74;
    input Real elmt_DeubiquitinationBoundMisP4;
    input Real elmt_DeubiquitinationBoundMisP3;
    input Real elmt_DeubiquitinationBoundMisP2;
    input Real elmt_DeubiquitinationBoundMisP1;
    input Real elmt_Aggregation30;
    input Real elmt_Aggregation31;
    input Real elmt_reactant78;
    input Real elmt_reactant79;
    input Real elmt_Aggregation38;
    input Real elmt_Aggregation39;
    input Real elmt_Aggregation36;
    input Real elmt_Aggregation37;
    input Real elmt_Aggregation34;
    input Real elmt_Aggregation35;
    input Real elmt_Aggregation32;
    input Real elmt_Aggregation33;
    input Real elmt_reactant190;
    input Real elmt_reactant197;
    input Real elmt_reactant196;
    input Real elmt_product213;
    input Real elmt_reactant194;
    input Real elmt_reactant193;
    input Real elmt_product210;
    input Real elmt_reactant191;
    input Real elmt_product219;
    input Real elmt_product216;
    input Real elmt_reactant199;
    input Real elmt_product222;
    input Real elmt_product225;
    input Real elmt_product103;
    input Real elmt_product100;
    input Real elmt_product109;
    input Real elmt_product106;
    input Real elmt_product228;
    input Real elmt_product12;
    input Real elmt_Refolding;
    input Real elmt_reactant176;
    input Real elmt_reactant296;
    input Real elmt_reactant174;
    input Real elmt_reactant295;
    input Real elmt_product312;
    input Real elmt_reactant293;
    input Real elmt_reactant172;
    input Real elmt_reactant292;
    input Real elmt_reactant171;
    input Real elmt_reactant290;
    input Real elmt_MisPE3Binding;
    input Real elmt_product318;
    input Real elmt_product315;
    input Real elmt_reactant178;
    input Real elmt_reactant299;
    input Real elmt_reactant298;
    input Real elmt_product23;
    input Real elmt_product201;
    input Real elmt_reactant186;
    input Real elmt_product321;
    input Real elmt_reactant184;
    input Real elmt_product323;
    input Real elmt_reactant182;
    input Real elmt_reactant180;
    input Real elmt_product15;
    input Real elmt_product14;
    input Real elmt_product326;
    input Real elmt_product19;
    input Real elmt_product204;
    input Real elmt_product207;
    input Real elmt_E2UbBinding;
    input Real elmt_reactant188;
    input Real elmt_reactant275;
    input Real elmt_reactant274;
    input Real elmt_reactant272;
    input Real elmt_reactant151;
    input Real elmt_reactant271;
    input Real elmt_reactant278;
    input Real elmt_reactant157;
    input Real elmt_reactant277;
    input Real elmt_reactant286;
    input Real elmt_product300;
    input Real elmt_reactant163;
    input Real elmt_reactant284;
    input Real elmt_reactant283;
    input Real elmt_reactant281;
    input Real elmt_reactant280;
    input Real elmt_product309;
    input Real elmt_reactant169;
    input Real elmt_reactant289;
    input Real elmt_product303;
    input Real elmt_product306;
    input Real elmt_reactant287;
    input Real elmt_reactant253;
    input Real elmt_reactant251;
    input Real elmt_reactant250;
    input Real elmt_reactant139;
    input Real elmt_reactant259;
    input Real elmt_reactant257;
    input Real elmt_reactant256;
    input Real elmt_reactant134;
    input Real elmt_reactant133;
    input Real elmt_reactant254;
    input Real elmt_reactant263;
    input Real elmt_reactant262;
    input Real elmt_reactant260;
    input Real elmt_reactant269;
    input Real elmt_reactant268;
    input Real elmt_reactant266;
    input Real elmt_reactant145;
    input Real elmt_reactant265;
    input Real elmt_product72;
    input Real elmt_product71;
    input Real elmt_product77;
    input Real elmt_product76;
    input Real elmt_product75;
    input Real elmt_reactant229;
    input Real elmt_reactant108;
    input Real elmt_product170;
    input Real elmt_product291;
    input Real elmt_product173;
    input Real elmt_product294;
    input Real elmt_product70;
    input Real elmt_Aggregation1;
    input Real elmt_reactant110;
    input Real elmt_product179;
    input Real elmt_Aggregation2;
    input Real elmt_reactant230;
    input Real elmt_Aggregation3;
    input Real elmt_Aggregation4;
    input Real elmt_Aggregation5;
    input Real elmt_product175;
    input Real elmt_Aggregation6;
    input Real elmt_Aggregation7;
    input Real elmt_product177;
    input Real elmt_Aggregation8;
    input Real elmt_product297;
    input Real elmt_reactant239;
    input Real elmt_Aggregation9;
    input Real elmt_reactant118;
    input Real elmt_reactant238;
    input Real elmt_reactant236;
    input Real elmt_reactant235;
    input Real elmt_reactant114;
    input Real elmt_reactant113;
    input Real elmt_reactant233;
    input Real elmt_reactant232;
    input Real elmt_reactant111;
    input Real elmt_product85;
    input Real elmt_product82;
    input Real elmt_product87;
    input Real elmt_reactant119;
    input Real elmt_product86;
    input Real elmt_product181;
    input Real elmt_product183;
    input Real elmt_product81;
    input Real elmt_product80;
    input Real elmt_reactant242;
    input Real elmt_reactant241;
    input Real elmt_ProteasomeInhibtion;
    input Real elmt_product189;
    input Real elmt_product185;
    input Real elmt_product187;
    input Real elmt_reactant129;
    input Real elmt_reactant128;
    input Real elmt_reactant248;
    input Real elmt_reactant247;
    input Real elmt_reactant245;
    input Real elmt_reactant124;
    input Real elmt_reactant244;
    input Real elmt_reactant123;
    input Real elmt_ProteasomeBinding5;
    input Real elmt_product96;
    input Real elmt_product95;
    input Real elmt_reactant209;
    input Real elmt_reactant208;
    input Real elmt_product97;
    input Real elmt_product270;
    input Real elmt_product150;
    input Real elmt_ProteasomeBinding1;
    input Real elmt_product92;
    input Real elmt_ProteasomeBinding2;
    input Real elmt_product91;
    input Real elmt_product90;
    input Real elmt_ProteasomeBinding3;
    input Real elmt_ProteasomeBinding4;
    input Real elmt_product156;
    input Real elmt_product159;
    input Real elmt_product279;
    input Real elmt_product153;
    input Real elmt_product273;
    input Real elmt_product276;
    input Real elmt_product154;
    input Real elmt_reactant217;
    input Real elmt_reactant215;
    input Real elmt_reactant214;
    input Real elmt_reactant212;
    input Real elmt_reactant211;
    input Real elmt_reactant218;
    input Real elmt_product160;
    input Real elmt_product162;
    input Real elmt_product282;
    input Real elmt_product168;
    input Real elmt_reactant220;
    input Real elmt_product288;
    input Real elmt_product285;
    input Real elmt_product166;
    input Real elmt_product165;
    input Real elmt_reactant107;
    input Real elmt_reactant227;
    input Real elmt_reactant226;
    input Real elmt_reactant105;
    input Real elmt_reactant104;
    input Real elmt_reactant224;
    input Real elmt_reactant223;
    input Real elmt_reactant102;
    input Real elmt_reactant101;
    input Real elmt_reactant221;
    input Real elmt_product33;
    input Real elmt_reactant308;
    input Real elmt_product32;
    input Real elmt_reactant307;
    input Real elmt_product135;
    input Real elmt_product255;
    input Real elmt_product137;
    input Real elmt_product258;
    input Real elmt_product136;
    input Real elmt_product131;
    input Real elmt_product252;
    input Real elmt_product130;
    input Real elmt_product132;
    input Real elmt_product27;
    input Real elmt_reactant316;
    input Real elmt_reactant314;
    input Real elmt_product24;
    input Real elmt_reactant313;
    input Real elmt_reactant311;
    input Real elmt_product138;
    input Real elmt_product29;
    input Real elmt_reactant310;
    input Real elmt_product28;
    input Real elmt_product41;
    input Real elmt_product40;
    input Real elmt_product45;
    input Real elmt_product44;
    input Real elmt_reactant319;
    input Real elmt_reactant317;
    input Real elmt_product261;
    input Real elmt_product267;
    input Real elmt_product148;
    input Real elmt_product147;
    input Real elmt_product142;
    input Real elmt_product141;
    input Real elmt_product144;
    input Real elmt_product264;
    input Real elmt_reactant206;
    input Real elmt_product37;
    input Real elmt_reactant205;
    input Real elmt_product36;
    input Real elmt_reactant325;
    input Real elmt_reactant203;
    input Real elmt_reactant324;
    input Real elmt_reactant202;
    input Real elmt_reactant322;
    input Real elmt_reactant200;
    input Real elmt_reactant320;
    input Real elmt_product52;
    input Real elmt_product56;
    input Real elmt_product53;
    input Real elmt_product234;
    input Real elmt_product112;
    input Real elmt_product115;
    input Real elmt_product231;
    input Real elmt_product49;
    input Real elmt_product48;
    input Real elmt_product117;
    input Real elmt_product116;
    input Real elmt_product237;
    input Real elmt_product62;
    input Real elmt_product61;
    input Real elmt_product60;
    input Real elmt_product67;
    input Real elmt_product66;
    input Real elmt_product65;
    input Real elmt_SequesteringOfAggregates;
    input Real elmt_ProteasomeActivity1;
    input Real elmt_product126;
    input Real elmt_ProteasomeActivity2;
    input Real elmt_product125;
    input Real elmt_product246;
    input Real elmt_ProteasomeActivity3;
    input Real elmt_product120;
    input Real elmt_ProteasomeActivity4;
    input Real elmt_product240;
    input Real elmt_ProteasomeActivity5;
    input Real elmt_product122;
    input Real elmt_product243;
    input Real elmt_product121;
    input Real elmt_reactant305;
    input Real elmt_reactant304;
    input Real elmt_product57;
    input Real elmt_reactant302;
    input Real elmt_reactant301;
    input Real elmt_product249;
    input Real elmt_product127;

    Real elmt_cytosol(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_degUb7_amount(unit = "");
    Real elmt_degUb7_conc(unit = "");
    Real elmt_degUb7(unit = "") "";
    Real elmt_degUb6_amount(unit = "");
    Real elmt_degUb6_conc(unit = "");
    Real elmt_degUb6(unit = "") "";
    Real elmt_ROS_amount(unit = "");
    Real elmt_ROS_conc(unit = "");
    Real elmt_ROS(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_MisP_Ub4_Proteasome_amount(unit = "");
    Real elmt_MisP_Ub4_Proteasome_conc(unit = "");
    Real elmt_MisP_Ub4_Proteasome(unit = "") "";
    Real elmt_degUb8_amount(unit = "");
    Real elmt_degUb8_conc(unit = "");
    Real elmt_degUb8(unit = "") "";
    Real elmt_E1_Ub_amount(unit = "");
    Real elmt_E1_Ub_conc(unit = "");
    Real elmt_E1_Ub(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_E3_MisP_amount(unit = "");
    Real elmt_E3_MisP_conc(unit = "");
    Real elmt_E3_MisP(unit = "") "";
    Real elmt_degUb5_amount(unit = "");
    Real elmt_degUb5_conc(unit = "");
    Real elmt_degUb5(unit = "") "";
    Real elmt_degUb4_amount(unit = "");
    Real elmt_degUb4_conc(unit = "");
    Real elmt_degUb4(unit = "") "";
    Real elmt_E2_amount(unit = "");
    Real elmt_E2_conc(unit = "");
    Real elmt_E2(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_E3_amount(unit = "");
    Real elmt_E3_conc(unit = "");
    Real elmt_E3(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_ATP_amount(unit = "");
    Real elmt_ATP_conc(unit = "");
    Real elmt_ATP(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_E1_amount(unit = "");
    Real elmt_E1_conc(unit = "");
    Real elmt_E1(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_Source_amount(unit = "");
    Real elmt_Source_conc(unit = "");
    Real elmt_Source(unit = "") "";
    Real elmt_MisP_Ub_amount(unit = "");
    Real elmt_MisP_Ub_conc(unit = "");
    Real elmt_MisP_Ub(unit = "") "";
    Real elmt_MisP_Ub8_Proteasome_amount(unit = "");
    Real elmt_MisP_Ub8_Proteasome_conc(unit = "");
    Real elmt_MisP_Ub8_Proteasome(unit = "") "";
    Real elmt_totMisP_amount(unit = "");
    Real elmt_totMisP_conc(unit = "");
    Real elmt_totMisP(unit = "") "";
    Real elmt_AggP_Proteasome_amount(unit = "");
    Real elmt_AggP_Proteasome_conc(unit = "");
    Real elmt_AggP_Proteasome(unit = "") "";
    Real elmt_NatP_amount(unit = "");
    Real elmt_NatP_conc(unit = "");
    Real elmt_NatP(unit = "") "";
    Real elmt_MisP_Ub3_amount(unit = "");
    Real elmt_MisP_Ub3_conc(unit = "");
    Real elmt_MisP_Ub3(unit = "") "";
    Real elmt_MisP_Ub2_amount(unit = "");
    Real elmt_MisP_Ub2_conc(unit = "");
    Real elmt_MisP_Ub2(unit = "") "";
    Real elmt_MisP_Ub5_amount(unit = "");
    Real elmt_MisP_Ub5_conc(unit = "");
    Real elmt_MisP_Ub5(unit = "") "";
    Real elmt_ADP_amount(unit = "");
    Real elmt_ADP_conc(unit = "");
    Real elmt_ADP(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_MisP_Ub4_amount(unit = "");
    Real elmt_MisP_Ub4_conc(unit = "");
    Real elmt_MisP_Ub4(unit = "") "";
    Real elmt_MisP_Ub5_Proteasome_amount(unit = "");
    Real elmt_MisP_Ub5_Proteasome_conc(unit = "");
    Real elmt_MisP_Ub5_Proteasome(unit = "") "";
    Real elmt_refNatP_amount(unit = "");
    Real elmt_refNatP_conc(unit = "");
    Real elmt_refNatP(unit = "") "";
    Real elmt_MisP_Ub7_amount(unit = "");
    Real elmt_MisP_Ub7_conc(unit = "");
    Real elmt_MisP_Ub7(unit = "") "";
    Real elmt_MisP_amount(unit = "");
    Real elmt_MisP_conc(unit = "");
    Real elmt_MisP(unit = "") "";
    Real elmt_MisP_Ub6_amount(unit = "");
    Real elmt_MisP_Ub6_conc(unit = "");
    Real elmt_MisP_Ub6(unit = "") "";
    Real elmt_MisP_Ub8_amount(unit = "");
    Real elmt_MisP_Ub8_conc(unit = "");
    Real elmt_MisP_Ub8(unit = "") "";
    Real elmt_E2_Ub_amount(unit = "");
    Real elmt_E2_Ub_conc(unit = "");
    Real elmt_E2_Ub(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_SeqAggP_amount(unit = "");
    Real elmt_SeqAggP_conc(unit = "");
    Real elmt_SeqAggP(unit = "") "";
    Real elmt_DUB_amount(unit = "");
    Real elmt_DUB_conc(unit = "");
    Real elmt_DUB(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_Ub_amount(unit = "");
    Real elmt_Ub_conc(unit = "");
    Real elmt_Ub(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_MisP_Ub6_Proteasome_amount(unit = "");
    Real elmt_MisP_Ub6_Proteasome_conc(unit = "");
    Real elmt_MisP_Ub6_Proteasome(unit = "") "";
    Real elmt_AggP_amount(unit = "");
    Real elmt_AggP_conc(unit = "");
    Real elmt_AggP(unit = "") "";
    Real elmt_AMP_amount(unit = "");
    Real elmt_AMP_conc(unit = "");
    Real elmt_AMP(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_Proteasome_amount(unit = "");
    Real elmt_Proteasome_conc(unit = "");
    Real elmt_Proteasome(unit = "") "";
 annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	</rdf:RDF>
	</annotation>"));
    Real elmt_MisP_Ub7_Proteasome_amount(unit = "");
    Real elmt_MisP_Ub7_Proteasome_conc(unit = "");
    Real elmt_MisP_Ub7_Proteasome(unit = "") "";

    initial equation
        elmt_cytosol = 1.0;
        elmt_degUb7_amount = 0.0;
        elmt_degUb6_amount = 0.0;
        elmt_ROS_amount = 10.0;
        elmt_MisP_Ub4_Proteasome_amount = 0.0;
        elmt_degUb8_amount = 0.0;
        elmt_E1_Ub_amount = 0.0;
        elmt_E3_MisP_amount = 0.0;
        elmt_degUb5_amount = 0.0;
        elmt_degUb4_amount = 0.0;
        elmt_E2_amount = 100.0;
        elmt_E3_amount = 100.0;
        elmt_ATP_amount = 10000.0;
        elmt_E1_amount = 100.0;
        elmt_Source_amount = 1.0;
        elmt_MisP_Ub_amount = 0.0;
        elmt_MisP_Ub8_Proteasome_amount = 0.0;
        elmt_totMisP_amount = 0.0;
        elmt_AggP_Proteasome_amount = 0.0;
        elmt_NatP_amount = 500.0;
        elmt_MisP_Ub3_amount = 0.0;
        elmt_MisP_Ub2_amount = 0.0;
        elmt_MisP_Ub5_amount = 0.0;
        elmt_ADP_amount = 1000.0;
        elmt_MisP_Ub4_amount = 0.0;
        elmt_MisP_Ub5_Proteasome_amount = 0.0;
        elmt_refNatP_amount = 0.0;
        elmt_MisP_Ub7_amount = 0.0;
        elmt_MisP_amount = 0.0;
        elmt_MisP_Ub6_amount = 0.0;
        elmt_MisP_Ub8_amount = 0.0;
        elmt_E2_Ub_amount = 0.0;
        elmt_SeqAggP_amount = 0.0;
        elmt_DUB_amount = 200.0;
        elmt_Ub_amount = 500.0;
        elmt_MisP_Ub6_Proteasome_amount = 0.0;
        elmt_AggP_amount = 0.0;
        elmt_AMP_amount = 1000.0;
        elmt_Proteasome_amount = 100.0;
        elmt_MisP_Ub7_Proteasome_amount = 0.0;


    equation
        assert(elmt_cytosol >= 0, "Compartment size became negative. Make sure this is a valid bahaviour.");
        der(elmt_cytosol) = 0;
        elmt_degUb7 = elmt_degUb7_amount;
        elmt_degUb6 = elmt_degUb6_amount;
        elmt_ROS = elmt_ROS_amount;
        elmt_MisP_Ub4_Proteasome = elmt_MisP_Ub4_Proteasome_amount;
        elmt_degUb8 = elmt_degUb8_amount;
        elmt_E1_Ub = elmt_E1_Ub_amount;
        elmt_E3_MisP = elmt_E3_MisP_amount;
        elmt_degUb5 = elmt_degUb5_amount;
        elmt_degUb4 = elmt_degUb4_amount;
        elmt_E2 = elmt_E2_amount;
        elmt_E3 = elmt_E3_amount;
        elmt_ATP = elmt_ATP_amount;
        elmt_E1 = elmt_E1_amount;
        elmt_Source = elmt_Source_amount;
        elmt_MisP_Ub = elmt_MisP_Ub_amount;
        elmt_MisP_Ub8_Proteasome = elmt_MisP_Ub8_Proteasome_amount;
        elmt_totMisP = elmt_totMisP_amount;
        elmt_AggP_Proteasome = elmt_AggP_Proteasome_amount;
        elmt_NatP = elmt_NatP_amount;
        elmt_MisP_Ub3 = elmt_MisP_Ub3_amount;
        elmt_MisP_Ub2 = elmt_MisP_Ub2_amount;
        elmt_MisP_Ub5 = elmt_MisP_Ub5_amount;
        elmt_ADP = elmt_ADP_amount;
        elmt_MisP_Ub4 = elmt_MisP_Ub4_amount;
        elmt_MisP_Ub5_Proteasome = elmt_MisP_Ub5_Proteasome_amount;
        elmt_refNatP = elmt_refNatP_amount;
        elmt_MisP_Ub7 = elmt_MisP_Ub7_amount;
        elmt_MisP = elmt_MisP_amount;
        elmt_MisP_Ub6 = elmt_MisP_Ub6_amount;
        elmt_MisP_Ub8 = elmt_MisP_Ub8_amount;
        elmt_E2_Ub = elmt_E2_Ub_amount;
        elmt_SeqAggP = elmt_SeqAggP_amount;
        elmt_DUB = elmt_DUB_amount;
        elmt_Ub = elmt_Ub_amount;
        elmt_MisP_Ub6_Proteasome = elmt_MisP_Ub6_Proteasome_amount;
        elmt_AggP = elmt_AggP_amount;
        elmt_AMP = elmt_AMP_amount;
        elmt_Proteasome = elmt_Proteasome_amount;
        elmt_MisP_Ub7_Proteasome = elmt_MisP_Ub7_Proteasome_amount;
        der(elmt_ATP_amount) = 0;
        der(elmt_Source_amount) = 0;
        der(elmt_ADP_amount) = 0;
        der(elmt_AMP_amount) = 0;
        der(elmt_degUb7_amount) = (elmt_ProteasomeActivity4 * elmt_product162);
        der(elmt_degUb6_amount) = (elmt_ProteasomeActivity3 * elmt_product156);
        der(elmt_ROS_amount) = ((- (elmt_Misfolding * elmt_reactant3)) + (elmt_Misfolding * elmt_product5));
        der(elmt_MisP_Ub4_Proteasome_amount) = ((elmt_ProteasomeBinding1 * elmt_product100) + (elmt_DeubiquitinationBoundMisP2 * elmt_product130) + (- (elmt_DeubiquitinationBoundMisP1 * elmt_reactant133)) + (- (elmt_ProteasomeActivity1 * elmt_reactant139)));
        der(elmt_degUb8_amount) = (elmt_ProteasomeActivity5 * elmt_product168);
        der(elmt_E1_Ub_amount) = ((elmt_E1UbBinding * elmt_product19) + (- (elmt_E2UbBinding * elmt_reactant22)));
        der(elmt_E3_MisP_amount) = ((- (elmt_MisPE3Release * elmt_reactant13)) + (elmt_MisPE3Binding * elmt_product12) + (- (elmt_Monoubiquitination * elmt_reactant26)));
        der(elmt_degUb5_amount) = (elmt_ProteasomeActivity2 * elmt_product150);
        der(elmt_degUb4_amount) = (elmt_ProteasomeActivity1 * elmt_product144);
        der(elmt_E2_amount) = ((elmt_Polyubiquitination6 * elmt_product53) + (elmt_Polyubiquitination7 * elmt_product57) + (elmt_Polyubiquitination2 * elmt_product37) + (elmt_Polyubiquitination3 * elmt_product41) + (elmt_Polyubiquitination4 * elmt_product45) + (elmt_Polyubiquitination5 * elmt_product49) + (elmt_Polyubiquitination1 * elmt_product33) + (elmt_Monoubiquitination * elmt_product28) + (- (elmt_E2UbBinding * elmt_reactant21)));
        der(elmt_E3_amount) = ((elmt_MisPE3Release * elmt_product15) + (- (elmt_MisPE3Binding * elmt_reactant11)) + (elmt_Monoubiquitination * elmt_product29));
        der(elmt_E1_amount) = ((- (elmt_E1UbBinding * elmt_reactant16)) + (elmt_E2UbBinding * elmt_product24));
        der(elmt_MisP_Ub_amount) = ((- (elmt_Aggregation3 * elmt_reactant174)) + (- (elmt_Aggregation11 * elmt_reactant190)) + (- (elmt_Polyubiquitination1 * elmt_reactant30)) + (- (elmt_Aggregation19 * elmt_reactant214)) + (- (elmt_Aggregation27 * elmt_reactant238)) + (- (elmt_Aggregation28 * elmt_reactant241)) + (- (elmt_Aggregation29 * elmt_reactant244)) + (elmt_Deubiqutination7 * elmt_product90) + (- (elmt_Deubiqutination8 * elmt_reactant93)) + (- (elmt_Aggregation30 * elmt_reactant247)) + (- (elmt_Aggregation31 * elmt_reactant250)) + (elmt_Monoubiquitination * elmt_product27) + (- (elmt_Aggregation32 * elmt_reactant253)) + (- (elmt_Aggregation33 * elmt_reactant256)));
        der(elmt_MisP_Ub8_Proteasome_amount) = ((elmt_ProteasomeBinding5 * elmt_product112) + (- (elmt_DeubiquitinationBoundMisP5 * elmt_reactant113)) + (- (elmt_ProteasomeActivity5 * elmt_reactant163)));
        der(elmt_totMisP_amount) = (elmt_Misfolding * elmt_product6);
        der(elmt_AggP_Proteasome_amount) = (elmt_ProteasomeInhibtion * elmt_product326);
        der(elmt_NatP_amount) = ((- (elmt_Misfolding * elmt_reactant2)) + (elmt_Refolding * elmt_product8) + (elmt_ProteinSynthesis * elmt_product1));
        der(elmt_MisP_Ub3_amount) = ((- (elmt_Aggregation41 * elmt_reactant280)) + (- (elmt_Aggregation42 * elmt_reactant283)) + (- (elmt_Aggregation40 * elmt_reactant277)) + (- (elmt_Aggregation5 * elmt_reactant178)) + (- (elmt_Aggregation43 * elmt_reactant286)) + (- (elmt_Aggregation44 * elmt_reactant289)) + (elmt_Polyubiquitination2 * elmt_product36) + (- (elmt_Polyubiquitination3 * elmt_reactant38)) + (- (elmt_Aggregation13 * elmt_reactant196)) + (- (elmt_Aggregation28 * elmt_reactant242)) + (- (elmt_Aggregation21 * elmt_reactant220)) + (elmt_Deubiqutination5 * elmt_product80) + (- (elmt_Deubiqutination6 * elmt_reactant83)) + (elmt_DeubiquitinationBoundMisP1 * elmt_product135) + (- (elmt_Aggregation34 * elmt_reactant260)));
        der(elmt_MisP_Ub2_amount) = ((- (elmt_Aggregation4 * elmt_reactant176)) + (- (elmt_Polyubiquitination2 * elmt_reactant34)) + (- (elmt_Aggregation12 * elmt_reactant193)) + (elmt_Polyubiquitination1 * elmt_product32) + (- (elmt_Aggregation20 * elmt_reactant217)) + (- (elmt_Aggregation27 * elmt_reactant239)) + (- (elmt_Deubiqutination7 * elmt_reactant88)) + (elmt_Deubiqutination6 * elmt_product85) + (- (elmt_Aggregation38 * elmt_reactant271)) + (- (elmt_Aggregation39 * elmt_reactant274)) + (- (elmt_Aggregation36 * elmt_reactant265)) + (- (elmt_Aggregation37 * elmt_reactant268)) + (- (elmt_Aggregation34 * elmt_reactant259)) + (- (elmt_Aggregation35 * elmt_reactant262)));
        der(elmt_MisP_Ub5_amount) = ((- (elmt_Aggregation41 * elmt_reactant281)) + (- (elmt_Aggregation49 * elmt_reactant304)) + (- (elmt_Aggregation45 * elmt_reactant293)) + (- (elmt_Aggregation7 * elmt_reactant182)) + (elmt_Polyubiquitination4 * elmt_product44) + (- (elmt_Polyubiquitination5 * elmt_reactant46)) + (- (elmt_Aggregation50 * elmt_reactant307)) + (- (elmt_Aggregation51 * elmt_reactant310)) + (- (elmt_Aggregation15 * elmt_reactant202)) + (- (elmt_ProteasomeBinding2 * elmt_reactant101)) + (- (elmt_Aggregation23 * elmt_reactant226)) + (elmt_Deubiqutination3 * elmt_product70) + (- (elmt_Deubiqutination4 * elmt_reactant73)) + (- (elmt_Aggregation30 * elmt_reactant248)) + (- (elmt_Aggregation36 * elmt_reactant266)));
        der(elmt_MisP_Ub4_amount) = ((- (elmt_Aggregation40 * elmt_reactant278)) + (- (elmt_Aggregation47 * elmt_reactant298)) + (- (elmt_Aggregation48 * elmt_reactant301)) + (- (elmt_Aggregation45 * elmt_reactant292)) + (- (elmt_Aggregation6 * elmt_reactant180)) + (- (elmt_Aggregation46 * elmt_reactant295)) + (elmt_Polyubiquitination3 * elmt_product40) + (- (elmt_Polyubiquitination4 * elmt_reactant42)) + (- (elmt_Aggregation14 * elmt_reactant199)) + (- (elmt_ProteasomeBinding1 * elmt_reactant98)) + (- (elmt_Aggregation22 * elmt_reactant223)) + (- (elmt_Aggregation29 * elmt_reactant245)) + (- (elmt_Deubiqutination5 * elmt_reactant78)) + (elmt_Deubiqutination4 * elmt_product75) + (- (elmt_Aggregation35 * elmt_reactant263)));
        der(elmt_MisP_Ub5_Proteasome_amount) = ((elmt_ProteasomeBinding2 * elmt_product103) + (elmt_DeubiquitinationBoundMisP3 * elmt_product125) + (- (elmt_DeubiquitinationBoundMisP2 * elmt_reactant128)) + (- (elmt_ProteasomeActivity2 * elmt_reactant145)));
        der(elmt_refNatP_amount) = (elmt_Refolding * elmt_product9);
        der(elmt_MisP_Ub7_amount) = ((- (elmt_Aggregation47 * elmt_reactant299)) + (- (elmt_Aggregation43 * elmt_reactant287)) + (- (elmt_Aggregation9 * elmt_reactant186)) + (elmt_Polyubiquitination6 * elmt_product52) + (- (elmt_Polyubiquitination7 * elmt_reactant54)) + (- (elmt_Aggregation52 * elmt_reactant314)) + (- (elmt_Aggregation50 * elmt_reactant308)) + (- (elmt_Aggregation17 * elmt_reactant208)) + (- (elmt_Aggregation54 * elmt_reactant319)) + (- (elmt_ProteasomeBinding4 * elmt_reactant107)) + (- (elmt_Aggregation25 * elmt_reactant232)) + (- (elmt_Deubiqutination2 * elmt_reactant63)) + (elmt_Deubiqutination1 * elmt_product60) + (- (elmt_Aggregation38 * elmt_reactant272)) + (- (elmt_Aggregation32 * elmt_reactant254)));
        der(elmt_MisP_amount) = ((- (elmt_Aggregation1 * elmt_reactant169)) + (- (elmt_Aggregation2 * elmt_reactant171)) + (elmt_Misfolding * elmt_product4) + (- (elmt_Aggregation16 * elmt_reactant206)) + (- (elmt_Aggregation17 * elmt_reactant209)) + (- (elmt_Aggregation14 * elmt_reactant200)) + (- (elmt_Aggregation15 * elmt_reactant203)) + (- (elmt_Aggregation12 * elmt_reactant194)) + (- (elmt_Aggregation13 * elmt_reactant197)) + (- (elmt_Aggregation11 * elmt_reactant191)) + (- (elmt_Aggregation18 * elmt_reactant212)) + (elmt_MisPE3Release * elmt_product14) + (- (elmt_Refolding * elmt_reactant7)) + (- (elmt_MisPE3Binding * elmt_reactant10)) + (elmt_Deubiqutination8 * elmt_product95));
        der(elmt_MisP_Ub6_amount) = ((- (elmt_Aggregation42 * elmt_reactant284)) + (- (elmt_Aggregation49 * elmt_reactant305)) + (- (elmt_Aggregation46 * elmt_reactant296)) + (- (elmt_Aggregation8 * elmt_reactant184)) + (- (elmt_Polyubiquitination6 * elmt_reactant50)) + (elmt_Polyubiquitination5 * elmt_product48) + (- (elmt_Aggregation52 * elmt_reactant313)) + (- (elmt_Aggregation53 * elmt_reactant316)) + (- (elmt_Aggregation16 * elmt_reactant205)) + (- (elmt_ProteasomeBinding3 * elmt_reactant104)) + (- (elmt_Aggregation24 * elmt_reactant229)) + (- (elmt_Deubiqutination3 * elmt_reactant68)) + (elmt_Deubiqutination2 * elmt_product65) + (- (elmt_Aggregation31 * elmt_reactant251)) + (- (elmt_Aggregation37 * elmt_reactant269)));
        der(elmt_MisP_Ub8_amount) = ((- (elmt_Aggregation48 * elmt_reactant302)) + (- (elmt_Aggregation44 * elmt_reactant290)) + (elmt_Polyubiquitination7 * elmt_product56) + (- (elmt_Aggregation53 * elmt_reactant317)) + (- (elmt_Aggregation51 * elmt_reactant311)) + (- (elmt_Aggregation10 * elmt_reactant188)) + (- (elmt_Aggregation54 * elmt_reactant320)) + (- (elmt_Aggregation18 * elmt_reactant211)) + (- (elmt_ProteasomeBinding5 * elmt_reactant110)) + (- (elmt_Aggregation26 * elmt_reactant235)) + (- (elmt_Deubiqutination1 * elmt_reactant58)) + (- (elmt_Aggregation39 * elmt_reactant275)) + (- (elmt_Aggregation33 * elmt_reactant257)));
        der(elmt_E2_Ub_amount) = ((- (elmt_Polyubiquitination6 * elmt_reactant51)) + (- (elmt_Polyubiquitination7 * elmt_reactant55)) + (- (elmt_Polyubiquitination2 * elmt_reactant35)) + (- (elmt_Polyubiquitination3 * elmt_reactant39)) + (- (elmt_Polyubiquitination4 * elmt_reactant43)) + (- (elmt_Polyubiquitination5 * elmt_reactant47)) + (- (elmt_Polyubiquitination1 * elmt_reactant31)) + (- (elmt_Monoubiquitination * elmt_reactant25)) + (elmt_E2UbBinding * elmt_product23));
        der(elmt_SeqAggP_amount) = (elmt_SequesteringOfAggregates * elmt_product323);
        der(elmt_DUB_amount) = ((elmt_Deubiqutination3 * elmt_product71) + (- (elmt_Deubiqutination3 * elmt_reactant69)) + (- (elmt_Deubiqutination2 * elmt_reactant64)) + (elmt_Deubiqutination2 * elmt_product66) + (elmt_Deubiqutination5 * elmt_product81) + (- (elmt_Deubiqutination5 * elmt_reactant79)) + (- (elmt_DeubiquitinationBoundMisP5 * elmt_reactant114)) + (elmt_DeubiquitinationBoundMisP5 * elmt_product117) + (- (elmt_Deubiqutination4 * elmt_reactant74)) + (elmt_Deubiqutination4 * elmt_product76) + (elmt_DeubiquitinationBoundMisP4 * elmt_product122) + (- (elmt_DeubiquitinationBoundMisP4 * elmt_reactant119)) + (elmt_Deubiqutination7 * elmt_product91) + (- (elmt_Deubiqutination7 * elmt_reactant89)) + (- (elmt_DeubiquitinationBoundMisP3 * elmt_reactant124)) + (elmt_DeubiquitinationBoundMisP3 * elmt_product127) + (- (elmt_Deubiqutination6 * elmt_reactant84)) + (elmt_Deubiqutination6 * elmt_product86) + (elmt_DeubiquitinationBoundMisP2 * elmt_product132) + (- (elmt_DeubiquitinationBoundMisP2 * elmt_reactant129)) + (elmt_DeubiquitinationBoundMisP1 * elmt_product138) + (- (elmt_DeubiquitinationBoundMisP1 * elmt_reactant134)) + (- (elmt_Deubiqutination8 * elmt_reactant94)) + (elmt_Deubiqutination8 * elmt_product96) + (elmt_Deubiqutination1 * elmt_product61) + (- (elmt_Deubiqutination1 * elmt_reactant59)));
        der(elmt_Ub_amount) = ((- (elmt_E1UbBinding * elmt_reactant17)) + (elmt_Deubiqutination3 * elmt_product72) + (elmt_Deubiqutination2 * elmt_product67) + (elmt_Deubiqutination5 * elmt_product82) + (elmt_DeubiquitinationBoundMisP5 * elmt_product116) + (elmt_Deubiqutination4 * elmt_product77) + (elmt_DeubiquitinationBoundMisP4 * elmt_product121) + (elmt_Deubiqutination7 * elmt_product92) + (elmt_DeubiquitinationBoundMisP3 * elmt_product126) + (elmt_Deubiqutination6 * elmt_product87) + (elmt_DeubiquitinationBoundMisP2 * elmt_product131) + (elmt_DeubiquitinationBoundMisP1 * elmt_product137) + (elmt_Deubiqutination8 * elmt_product97) + (elmt_Deubiqutination1 * elmt_product62) + (elmt_ProteasomeActivity1 * elmt_product141) + (elmt_ProteasomeActivity2 * elmt_product147) + (elmt_ProteasomeActivity3 * elmt_product153) + (elmt_ProteasomeActivity4 * elmt_product159) + (elmt_ProteasomeActivity5 * elmt_product165));
        der(elmt_MisP_Ub6_Proteasome_amount) = ((elmt_ProteasomeBinding3 * elmt_product106) + (elmt_DeubiquitinationBoundMisP4 * elmt_product120) + (- (elmt_DeubiquitinationBoundMisP3 * elmt_reactant123)) + (- (elmt_ProteasomeActivity3 * elmt_reactant151)));
        der(elmt_AggP_amount) = ((elmt_Aggregation41 * elmt_product282) + (elmt_Aggregation42 * elmt_product285) + (elmt_Aggregation40 * elmt_product279) + (elmt_Aggregation1 * elmt_product170) + (elmt_Aggregation49 * elmt_product306) + (- (elmt_Aggregation2 * elmt_reactant172)) + (elmt_Aggregation2 * elmt_product173) + (elmt_Aggregation3 * elmt_product175) + (elmt_Aggregation47 * elmt_product300) + (elmt_Aggregation4 * elmt_product177) + (elmt_Aggregation48 * elmt_product303) + (elmt_Aggregation5 * elmt_product179) + (elmt_Aggregation45 * elmt_product294) + (elmt_Aggregation6 * elmt_product181) + (elmt_Aggregation46 * elmt_product297) + (elmt_Aggregation7 * elmt_product183) + (elmt_Aggregation43 * elmt_product288) + (elmt_Aggregation8 * elmt_product185) + (elmt_Aggregation44 * elmt_product291) + (elmt_Aggregation9 * elmt_product187) + (elmt_Aggregation52 * elmt_product315) + (elmt_Aggregation53 * elmt_product318) + (elmt_Aggregation50 * elmt_product309) + (elmt_Aggregation51 * elmt_product312) + (elmt_Aggregation16 * elmt_product207) + (elmt_Aggregation17 * elmt_product210) + (- (elmt_ProteasomeInhibtion * elmt_reactant324)) + (elmt_Aggregation14 * elmt_product201) + (elmt_Aggregation15 * elmt_product204) + (elmt_Aggregation12 * elmt_product195) + (elmt_Aggregation13 * elmt_product198) + (elmt_Aggregation10 * elmt_product189) + (elmt_Aggregation54 * elmt_product321) + (elmt_Aggregation11 * elmt_product192) + (elmt_Aggregation18 * elmt_product213) + (- (elmt_Aggregation19 * elmt_reactant215)) + (elmt_Aggregation19 * elmt_product216) + (- (elmt_Aggregation20 * elmt_reactant218)) + (elmt_Aggregation20 * elmt_product219) + (elmt_Aggregation27 * elmt_product240) + (elmt_Aggregation28 * elmt_product243) + (elmt_Aggregation25 * elmt_product234) + (- (elmt_Aggregation25 * elmt_reactant233)) + (- (elmt_Aggregation26 * elmt_reactant236)) + (elmt_Aggregation26 * elmt_product237) + (- (elmt_Aggregation23 * elmt_reactant227)) + (elmt_Aggregation23 * elmt_product228) + (- (elmt_Aggregation24 * elmt_reactant230)) + (elmt_Aggregation24 * elmt_product231) + (elmt_Aggregation21 * elmt_product222) + (- (elmt_Aggregation21 * elmt_reactant221)) + (elmt_Aggregation22 * elmt_product225) + (- (elmt_Aggregation22 * elmt_reactant224)) + (elmt_Aggregation29 * elmt_product246) + (elmt_Aggregation30 * elmt_product249) + (elmt_Aggregation31 * elmt_product252) + (- (elmt_SequesteringOfAggregates * elmt_reactant322)) + (elmt_Aggregation38 * elmt_product273) + (elmt_Aggregation39 * elmt_product276) + (elmt_Aggregation36 * elmt_product267) + (elmt_Aggregation37 * elmt_product270) + (elmt_Aggregation34 * elmt_product261) + (elmt_Aggregation35 * elmt_product264) + (elmt_Aggregation32 * elmt_product255) + (elmt_Aggregation33 * elmt_product258));
        der(elmt_Proteasome_amount) = ((- (elmt_ProteasomeInhibtion * elmt_reactant325)) + (- (elmt_ProteasomeBinding5 * elmt_reactant111)) + (- (elmt_ProteasomeBinding1 * elmt_reactant99)) + (- (elmt_ProteasomeBinding2 * elmt_reactant102)) + (- (elmt_ProteasomeBinding3 * elmt_reactant105)) + (- (elmt_ProteasomeBinding4 * elmt_reactant108)) + (elmt_DeubiquitinationBoundMisP1 * elmt_product136) + (elmt_ProteasomeActivity1 * elmt_product142) + (elmt_ProteasomeActivity2 * elmt_product148) + (elmt_ProteasomeActivity3 * elmt_product154) + (elmt_ProteasomeActivity4 * elmt_product160) + (elmt_ProteasomeActivity5 * elmt_product166));
        der(elmt_MisP_Ub7_Proteasome_amount) = ((elmt_ProteasomeBinding4 * elmt_product109) + (elmt_DeubiquitinationBoundMisP5 * elmt_product115) + (- (elmt_DeubiquitinationBoundMisP4 * elmt_reactant118)) + (- (elmt_ProteasomeActivity4 * elmt_reactant157)));

    algorithm
        elmt_degUb7_conc := elmt_degUb7_amount / elmt_cytosol;
        elmt_degUb6_conc := elmt_degUb6_amount / elmt_cytosol;
        elmt_ROS_conc := elmt_ROS_amount / elmt_cytosol;
        elmt_MisP_Ub4_Proteasome_conc := elmt_MisP_Ub4_Proteasome_amount / elmt_cytosol;
        elmt_degUb8_conc := elmt_degUb8_amount / elmt_cytosol;
        elmt_E1_Ub_conc := elmt_E1_Ub_amount / elmt_cytosol;
        elmt_E3_MisP_conc := elmt_E3_MisP_amount / elmt_cytosol;
        elmt_degUb5_conc := elmt_degUb5_amount / elmt_cytosol;
        elmt_degUb4_conc := elmt_degUb4_amount / elmt_cytosol;
        elmt_E2_conc := elmt_E2_amount / elmt_cytosol;
        elmt_E3_conc := elmt_E3_amount / elmt_cytosol;
        elmt_ATP_conc := elmt_ATP_amount / elmt_cytosol;
        elmt_E1_conc := elmt_E1_amount / elmt_cytosol;
        elmt_Source_conc := elmt_Source_amount / elmt_cytosol;
        elmt_MisP_Ub_conc := elmt_MisP_Ub_amount / elmt_cytosol;
        elmt_MisP_Ub8_Proteasome_conc := elmt_MisP_Ub8_Proteasome_amount / elmt_cytosol;
        elmt_totMisP_conc := elmt_totMisP_amount / elmt_cytosol;
        elmt_AggP_Proteasome_conc := elmt_AggP_Proteasome_amount / elmt_cytosol;
        elmt_NatP_conc := elmt_NatP_amount / elmt_cytosol;
        elmt_MisP_Ub3_conc := elmt_MisP_Ub3_amount / elmt_cytosol;
        elmt_MisP_Ub2_conc := elmt_MisP_Ub2_amount / elmt_cytosol;
        elmt_MisP_Ub5_conc := elmt_MisP_Ub5_amount / elmt_cytosol;
        elmt_ADP_conc := elmt_ADP_amount / elmt_cytosol;
        elmt_MisP_Ub4_conc := elmt_MisP_Ub4_amount / elmt_cytosol;
        elmt_MisP_Ub5_Proteasome_conc := elmt_MisP_Ub5_Proteasome_amount / elmt_cytosol;
        elmt_refNatP_conc := elmt_refNatP_amount / elmt_cytosol;
        elmt_MisP_Ub7_conc := elmt_MisP_Ub7_amount / elmt_cytosol;
        elmt_MisP_conc := elmt_MisP_amount / elmt_cytosol;
        elmt_MisP_Ub6_conc := elmt_MisP_Ub6_amount / elmt_cytosol;
        elmt_MisP_Ub8_conc := elmt_MisP_Ub8_amount / elmt_cytosol;
        elmt_E2_Ub_conc := elmt_E2_Ub_amount / elmt_cytosol;
        elmt_SeqAggP_conc := elmt_SeqAggP_amount / elmt_cytosol;
        elmt_DUB_conc := elmt_DUB_amount / elmt_cytosol;
        elmt_Ub_conc := elmt_Ub_amount / elmt_cytosol;
        elmt_MisP_Ub6_Proteasome_conc := elmt_MisP_Ub6_Proteasome_amount / elmt_cytosol;
        elmt_AggP_conc := elmt_AggP_amount / elmt_cytosol;
        elmt_AMP_conc := elmt_AMP_amount / elmt_cytosol;
        elmt_Proteasome_conc := elmt_Proteasome_amount / elmt_cytosol;
        elmt_MisP_Ub7_Proteasome_conc := elmt_MisP_Ub7_Proteasome_amount / elmt_cytosol;
end Class_elmt_cytosol;
