within BIOMD293;
class Parameters

    input Real elmt_AggS1;
    input Real elmt_AggS2;
    input Real elmt_E3SUB_SUB_misfolded_Ub6_UCHL1;
    input Real elmt_aggasyndam;
    input Real elmt_E3_MisP_Ub4_DUB;
    input Real elmt_E3SUB_SUB_misfolded_Ub3_UCHL1;
    input Real elmt_E3SUB_SUB_misfolded_Ub2;
    input Real elmt_E3SUB_SUB_misfolded_Ub3;
    input Real elmt_E3SUB_SUB_misfolded_Ub4;
    input Real elmt_E3SUB_SUB_misfolded_Ub5;
    input Real elmt_E3SUB_SUB_misfolded_Ub6;
    input Real elmt_AggS3;
    input Real elmt_E3SUB_SUB_misfolded_Ub7;
    input Real elmt_AggS4;
    input Real elmt_E3SUB_SUB_misfolded_Ub8;
    input Real elmt_AggS5;
    input Real elmt_aggUchl1dam;
    input Real elmt_Parkin_asyn_dam_Ub7_DUB;
    input Real elmt_AggA5;
    input Real elmt_E3_MisP_Ub8_DUB;
    input Real elmt_MisP_Ub6_Proteasome;
    input Real elmt_AggA1;
    input Real elmt_aggUchl1;
    input Real elmt_Parkin_asyn_dam_Ub;
    input Real elmt_AggA2;
    input Real elmt_AggA3;
    input Real elmt_AggA4;
    input Real elmt_aggDUB;
    input Real elmt_SUB_misfolded_Ub5_Proteasome;
    input Real elmt_E3_MisP_Ub6_DUB;
    input Real elmt_E3_MisP_Ub7;
    input Real elmt_E3_MisP_Ub8;
    input Real elmt_E3_MisP_Ub3;
    input Real elmt_E3_MisP_Ub4;
    input Real elmt_E3_MisP_Ub5;
    input Real elmt_E3_MisP_Ub6;
    input Real elmt_Parkin_asyn_dam_Ub_DUB;
    input Real elmt_E3_MisP_Ub2;
    input Real elmt_E1_Ub;
    input Real elmt_Parkin_asyn_dam_Ub5_DUB;
    input Real elmt_MisP_Ub8_Proteasome;
    input Real elmt_E3SUB_SUB_misfolded_Ub8_UCHL1;
    input Real elmt_MisP;
    input Real elmt_Ub_UCHL1;
    input Real elmt_aggSUB;
    input Real elmt_Parkin_asyn_dam_Ub3_DUB;
    input Real elmt_E3SUB_SUB_misfolded_Ub2_UCHL1;
    input Real elmt_E3_MisP_Ub2_DUB;
    input Real elmt_AggP4;
    input Real elmt_AggP5;
    input Real elmt_UCHL1_damaged;
    input Real elmt_AggP1;
    input Real elmt_E3_MisP_Ub;
    input Real elmt_AggP2;
    input Real elmt_AggP3;
    input Real elmt_E3_MisP_Ub5_DUB;
    input Real elmt_MisP_Ub4_Proteasome;
    input Real elmt_E3_MisP;
    input Real elmt_asyn_dam_Ub8_Proteasome;
    input Real elmt_E3SUB_SUB_misfolded_Ub;
    input Real elmt_asyn_dam;
    input Real elmt_asyn_dam_Ub5_Proteasome;
    input Real elmt_SUB_misfolded_Ub7_Proteasome;
    input Real elmt_Parkin_asyn_dam_Ub8_DUB;
    input Real elmt_E3_MisP_Ub_DUB;
    input Real elmt_UCHL1;
    input Real elmt_UCHL1_damaged_Proteasome;
    input Real elmt_Parkin_asyn_dam_Ub2;
    input Real elmt_Parkin_asyn_dam_Ub3;
    input Real elmt_Parkin_asyn_dam_Ub4;
    input Real elmt_Parkin_asyn_dam_Ub5;
    input Real elmt_Parkin_asyn_dam_Ub6;
    input Real elmt_E2_Ub;
    input Real elmt_Parkin_asyn_dam_Ub7;
    input Real elmt_Parkin_asyn_dam_Ub8;
    input Real elmt_E3_MisP_Ub7_DUB;
    input Real elmt_SUB_misfolded_Ub4_Proteasome;
    input Real elmt_Ub;
    input Real elmt_E3SUB_SUB_misfolded_Ub7_UCHL1;
    input Real elmt_Parkin_asyn_dam;
    input Real elmt_Parkin_asyn_dam_Ub6_DUB;
    input Real elmt_asyn;
    input Real elmt_MisP_Ub7_Proteasome;
    input Real elmt_E3SUB_SUB_misfolded_Ub_UCHL1;
    input Real elmt_Lamp2a_UCHL1_damaged;
    input Real elmt_E3SUB_SUB_misfolded_Ub4_UCHL1;
    input Real elmt_asyn_Proteasome;
    input Real elmt_AggU1;
    input Real elmt_SUB_misfolded_Ub6_Proteasome;
    input Real elmt_AggU2;
    input Real elmt_AggU3;
    input Real elmt_AggU4;
    input Real elmt_asyn_dam_Ub4_Proteasome;
    input Real elmt_AggD4;
    input Real elmt_AggD5;
    input Real elmt_UCHL1_Proteasome;
    input Real elmt_aggUb;
    input Real elmt_Parkin_asyn_dam_Ub4_DUB;
    input Real elmt_aggasyn;
    input Real elmt_NatP;
    input Real elmt_MisP_Ub5_Proteasome;
    input Real elmt_AggU5;
    input Real elmt_E3SUB_SUB_misfolded_Ub5_UCHL1;
    input Real elmt_upregUb;
    input Real elmt_Parkin_asyn_dam_Ub2_DUB;
    input Real elmt_SUB_misfolded_Ub8_Proteasome;
    input Real elmt_asyn_dam_Ub6_Proteasome;
    input Real elmt_E3_MisP_Ub3_DUB;
    input Real elmt_asyn_Lamp2a;
    input Real elmt_AggD1;
    input Real elmt_aggE3;
    input Real elmt_aggMisP;
    input Real elmt_AggD2;
    input Real elmt_AggD3;
    input Real elmt_asyn_dam_Ub7_Proteasome;
    input Real elmt_aggParkin;

    Real elmt_kdegasynProt(unit = "") "";
    Real elmt_kbinProt(unit = "") "";
    Real elmt_kproteff(unit = "") "";
    Real elmt_kbinE3SUB(unit = "") "";
    Real elmt_krelUbUCHL1(unit = "") "";
    Real elmt_kbinasynDUB(unit = "") "";
    Real elmt_kbinMisPE3(unit = "") "";
    Real elmt_kbinE2Ub(unit = "") "";
    Real elmt_kbinMisPDUB(unit = "") "";
    Real elmt_kdisaggasyn4(unit = "") "";
    Real elmt_kdisaggasyndam4(unit = "") "";
    Real elmt_kdisaggasyn5(unit = "") "";
    Real elmt_kdisaggasyndam5(unit = "") "";
    Real elmt_kCMAasyn(unit = "") "";
    Real elmt_kbinAggProt(unit = "") "";
    Real elmt_kgenROSAggP(unit = "") "";
    Real elmt_kagg1dam(unit = "") "";
    Real elmt_kdisaggSUB2(unit = "") "";
    Real elmt_kdisaggSUB1(unit = "") "";
    Real elmt_kmisfold(unit = "") "";
    Real elmt_ksynNatP(unit = "") "";
    Real elmt_kdegLysUCHL1dam(unit = "") "";
    Real elmt_kdisaggasyndam1(unit = "") "";
    Real elmt_kdisaggasyndam2(unit = "") "";
    Real elmt_kdisaggasyndam3(unit = "") "";
    Real elmt_kbinLamp2aUCHL1dam(unit = "") "";
    Real elmt_krefoldSUB(unit = "") "";
    Real elmt_ksynasyn(unit = "") "";
    Real elmt_kbinUCHL1Prot(unit = "") "";
    Real elmt_krelMisPE3(unit = "") "";
    Real elmt_kubs(unit = "") "";
    Real elmt_kactDUB(unit = "") "";
    Real elmt_kdamUCHL1(unit = "") "";
    Real elmt_Ub_Conjugates(unit = "") "";
    Real elmt_Tot_Protein(unit = "") "";
    Real elmt_kremROS(unit = "") "";
    Real elmt_kmonoUb(unit = "") "";
    Real elmt_kbinasynLamp2a(unit = "") "";
    Real elmt_kactDUBProt(unit = "") "";
    Real elmt_kbinUbUCHL1(unit = "") "";
    Real elmt_Tot_Ub(unit = "") "";
    Real elmt_kbinSUBUCHL1(unit = "") "";
    Real elmt_kbinasynProt(unit = "") "";
    Real elmt_Tot_asyn_dam(unit = "") "";
    Real elmt_kdisagg5(unit = "") "";
    Real elmt_krefold(unit = "") "";
    Real elmt_kaggSUB2(unit = "") "";
    Real elmt_kaggSUB1(unit = "") "";
    Real elmt_kaggasyn1(unit = "") "";
    Real elmt_kdisagguchl1dam5(unit = "") "";
    Real elmt_Tot_UCHL1(unit = "") "";
    Real elmt_kgenROS(unit = "") "";
    Real elmt_kdisagguchl1dam4(unit = "") "";
    Real elmt_kdisagguchl1dam3(unit = "") "";
    Real elmt_kdisagguchl1dam2(unit = "") "";
    Real elmt_kdisagg4(unit = "") "";
    Real elmt_kdisagguchl1dam1(unit = "") "";
    Real elmt_kbinE1Ub(unit = "") "";
    Real elmt_kdisagg3(unit = "") "";
    Real elmt_kdisagg2(unit = "") "";
    Real elmt_kdisagg1(unit = "") "";
    Real elmt_kaggasyn2(unit = "") "";
    Real elmt_krelLamp2aUCHL1dam(unit = "") "";
    Real elmt_kdegProtUCHL1(unit = "") "";
    Real elmt_kbinasynParkin(unit = "") "";
    Real elmt_kubd(unit = "") "";
    Real elmt_kactProt(unit = "") "";
    Real elmt_Tot_asyn(unit = "") "";
    Real elmt_krelE3SUB(unit = "") "";
    Real elmt_kpolyUb(unit = "") "";
    Real elmt_kdegLysUCHL1(unit = "") "";
    Real elmt_krelasynParkin(unit = "") "";
    Real elmt_kubss(unit = "") "";
    Real elmt_UCHL1_substrate(unit = "") "";
    Real elmt_Tot_MisP(unit = "") "";
    Real elmt_kdisaggSUB4(unit = "") "";
    Real elmt_kdisaggSUB3(unit = "") "";
    Real elmt_kdisaggSUB5(unit = "") "";
    Real elmt_kdamasyn(unit = "") "";
    Real elmt_kdisaggasyn1(unit = "") "";
    Real elmt_kdisaggasyn2(unit = "") "";
    Real elmt_ksynSUB(unit = "") "";
    Real elmt_kdisaggasyn3(unit = "") "";
    Real elmt_kmisfoldSUB(unit = "") "";
    Real elmt_AggP(unit = "") "";
    Real elmt_kagg2(unit = "") "";
    Real elmt_kagg1(unit = "") "";
    Real elmt_ksynUCHL1(unit = "") "";
    Real elmt_kagg2dam(unit = "") "";
    Real elmt_kactUchl1(unit = "") "";
    Real elmt_kigrowth1(unit = "") "";
    Real elmt_kigrowth2(unit = "") "";


    initial equation
        elmt_kdegasynProt = 0.01;
        elmt_kbinProt = 5.0E-6;
        elmt_kproteff = 1.0;
        elmt_kbinE3SUB = 5.0E-4;
        elmt_krelUbUCHL1 = 0.05;
        elmt_kbinasynDUB = 2.0E-7;
        elmt_kbinMisPE3 = 1.0E-4;
        elmt_kbinE2Ub = 0.001;
        elmt_kbinMisPDUB = 2.0E-7;
        elmt_kdisaggasyn4 = 4.0E-9;
        elmt_kdisaggasyndam4 = 4.0E-9;
        elmt_kdisaggasyn5 = 2.0E-9;
        elmt_kdisaggasyndam5 = 2.0E-9;
        elmt_kCMAasyn = 0.001;
        elmt_kbinAggProt = 5.0E-9;
        elmt_kgenROSAggP = 2.0E-5;
        elmt_kagg1dam = 1.0E-5;
        elmt_kdisaggSUB2 = 8.0E-9;
        elmt_kdisaggSUB1 = 1.0E-8;
        elmt_kmisfold = 4.0E-5;
        elmt_ksynNatP = 2.4;
        elmt_kdegLysUCHL1dam = 2.7E-9;
        elmt_kdisaggasyndam1 = 1.0E-8;
        elmt_kdisaggasyndam2 = 8.0E-9;
        elmt_kdisaggasyndam3 = 6.0E-9;
        elmt_kbinLamp2aUCHL1dam = 1.0E-5;
        elmt_krefoldSUB = 5.0E-5;
        elmt_ksynasyn = 0.028;
        elmt_kbinUCHL1Prot = 4.0E-10;
        elmt_krelMisPE3 = 2.0E-4;
        elmt_kubs = 0.009;
        elmt_kactDUB = 1.0E-4;
        elmt_kdamUCHL1 = 1.0E-8;
        elmt_kremROS = 0.001;
        elmt_kmonoUb = 0.001;
        elmt_kbinasynLamp2a = 4.0E-8;
        elmt_kactDUBProt = 1.0E-6;
        elmt_kbinUbUCHL1 = 3.0E-6;
        elmt_kbinSUBUCHL1 = 4.0E-8;
        elmt_kbinasynProt = 1.7E-9;
        elmt_kdisagg5 = 2.0E-9;
        elmt_krefold = 8.0E-5;
        elmt_kaggSUB2 = 1.0E-10;
        elmt_kaggSUB1 = 1.0E-12;
        elmt_kaggasyn1 = 5.0E-12;
        elmt_kdisagguchl1dam5 = 2.0E-9;
        elmt_kgenROS = 0.01;
        elmt_kdisagguchl1dam4 = 4.0E-9;
        elmt_kdisagguchl1dam3 = 6.0E-9;
        elmt_kdisagguchl1dam2 = 8.0E-9;
        elmt_kdisagg4 = 4.0E-9;
        elmt_kdisagguchl1dam1 = 1.0E-8;
        elmt_kbinE1Ub = 2.0E-4;
        elmt_kdisagg3 = 6.0E-9;
        elmt_kdisagg2 = 8.0E-9;
        elmt_kdisagg1 = 1.0E-8;
        elmt_kaggasyn2 = 5.0E-10;
        elmt_krelLamp2aUCHL1dam = 5.0E-5;
        elmt_kdegProtUCHL1 = 0.01;
        elmt_kbinasynParkin = 1.0E-4;
        elmt_kubd = 4.4E-9;
        elmt_kactProt = 0.01;
        elmt_krelE3SUB = 2.0E-4;
        elmt_kpolyUb = 0.01;
        elmt_kdegLysUCHL1 = 2.7E-9;
        elmt_krelasynParkin = 2.0E-4;
        elmt_kubss = 0.1;
        elmt_kdisaggSUB4 = 4.0E-9;
        elmt_kdisaggSUB3 = 6.0E-9;
        elmt_kdisaggSUB5 = 2.0E-9;
        elmt_kdamasyn = 5.0E-8;
        elmt_kdisaggasyn1 = 1.0E-8;
        elmt_kdisaggasyn2 = 8.0E-9;
        elmt_ksynSUB = 0.13;
        elmt_kdisaggasyn3 = 6.0E-9;
        elmt_kmisfoldSUB = 2.0E-5;
        elmt_kagg2 = 1.0E-10;
        elmt_kagg1 = 1.0E-12;
        elmt_ksynUCHL1 = 0.022;
        elmt_kagg2dam = 0.005;
        elmt_kactUchl1 = 1.0E-4;
        elmt_kigrowth1 = 5.0E-9;
        elmt_kigrowth2 = 5.0E-9;


    equation
        der(elmt_kdegasynProt) = 0;
        der(elmt_kbinProt) = 0;
        der(elmt_kproteff) = 0;
        der(elmt_kbinE3SUB) = 0;
        der(elmt_krelUbUCHL1) = 0;
        der(elmt_kbinasynDUB) = 0;
        der(elmt_kbinMisPE3) = 0;
        der(elmt_kbinE2Ub) = 0;
        der(elmt_kbinMisPDUB) = 0;
        der(elmt_kdisaggasyn4) = 0;
        der(elmt_kdisaggasyndam4) = 0;
        der(elmt_kdisaggasyn5) = 0;
        der(elmt_kdisaggasyndam5) = 0;
        der(elmt_kCMAasyn) = 0;
        der(elmt_kbinAggProt) = 0;
        der(elmt_kgenROSAggP) = 0;
        der(elmt_kagg1dam) = 0;
        der(elmt_kdisaggSUB2) = 0;
        der(elmt_kdisaggSUB1) = 0;
        der(elmt_kmisfold) = 0;
        der(elmt_ksynNatP) = 0;
        der(elmt_kdegLysUCHL1dam) = 0;
        der(elmt_kdisaggasyndam1) = 0;
        der(elmt_kdisaggasyndam2) = 0;
        der(elmt_kdisaggasyndam3) = 0;
        der(elmt_kbinLamp2aUCHL1dam) = 0;
        der(elmt_krefoldSUB) = 0;
        der(elmt_ksynasyn) = 0;
        der(elmt_kbinUCHL1Prot) = 0;
        der(elmt_krelMisPE3) = 0;
        der(elmt_kubs) = 0;
        der(elmt_kactDUB) = 0;
        der(elmt_kdamUCHL1) = 0;
        elmt_Ub_Conjugates = (elmt_aggUb + (4.0 * elmt_asyn_dam_Ub4_Proteasome) + (5.0 * elmt_asyn_dam_Ub5_Proteasome) + (6.0 * elmt_asyn_dam_Ub6_Proteasome) + (7.0 * elmt_asyn_dam_Ub7_Proteasome) + (8.0 * elmt_asyn_dam_Ub8_Proteasome) + elmt_E1_Ub + elmt_E2_Ub + elmt_E3_MisP_Ub + elmt_E3_MisP_Ub_DUB + (2.0 * elmt_E3_MisP_Ub2) + (2.0 * elmt_E3_MisP_Ub2_DUB) + (3.0 * elmt_E3_MisP_Ub3) + (3.0 * elmt_E3_MisP_Ub3_DUB) + (4.0 * elmt_E3_MisP_Ub4) + (4.0 * elmt_E3_MisP_Ub4_DUB) + (5.0 * elmt_E3_MisP_Ub5) + (5.0 * elmt_E3_MisP_Ub5_DUB) + (6.0 * elmt_E3_MisP_Ub6) + (6.0 * elmt_E3_MisP_Ub6_DUB) + (7.0 * elmt_E3_MisP_Ub7) + (7.0 * elmt_E3_MisP_Ub7_DUB) + (8.0 * elmt_E3_MisP_Ub8) + (8.0 * elmt_E3_MisP_Ub8_DUB) + elmt_E3SUB_SUB_misfolded_Ub + elmt_E3SUB_SUB_misfolded_Ub_UCHL1 + (2.0 * elmt_E3SUB_SUB_misfolded_Ub2) + (2.0 * elmt_E3SUB_SUB_misfolded_Ub2_UCHL1) + (3.0 * elmt_E3SUB_SUB_misfolded_Ub3) + (3.0 * elmt_E3SUB_SUB_misfolded_Ub3_UCHL1) + (4.0 * elmt_E3SUB_SUB_misfolded_Ub4) + (4.0 * elmt_E3SUB_SUB_misfolded_Ub4_UCHL1) + (5.0 * elmt_E3SUB_SUB_misfolded_Ub5) + (5.0 * elmt_E3SUB_SUB_misfolded_Ub5_UCHL1) + (6.0 * elmt_E3SUB_SUB_misfolded_Ub6) + (6.0 * elmt_E3SUB_SUB_misfolded_Ub6_UCHL1) + (7.0 * elmt_E3SUB_SUB_misfolded_Ub7) + (7.0 * elmt_E3SUB_SUB_misfolded_Ub7_UCHL1) + (8.0 * elmt_E3SUB_SUB_misfolded_Ub8) + (8.0 * elmt_E3SUB_SUB_misfolded_Ub8_UCHL1) + elmt_E3SUB_SUB_misfolded_Ub_UCHL1 + (4.0 * elmt_MisP_Ub4_Proteasome) + (5.0 * elmt_MisP_Ub5_Proteasome) + (6.0 * elmt_MisP_Ub6_Proteasome) + (7.0 * elmt_MisP_Ub7_Proteasome) + (8.0 * elmt_MisP_Ub8_Proteasome) + elmt_Parkin_asyn_dam_Ub + elmt_Parkin_asyn_dam_Ub_DUB + (2.0 * elmt_Parkin_asyn_dam_Ub2) + (2.0 * elmt_Parkin_asyn_dam_Ub2_DUB) + (3.0 * elmt_Parkin_asyn_dam_Ub3) + (3.0 * elmt_Parkin_asyn_dam_Ub3_DUB) + (4.0 * elmt_Parkin_asyn_dam_Ub4) + (4.0 * elmt_Parkin_asyn_dam_Ub4_DUB) + (5.0 * elmt_Parkin_asyn_dam_Ub5) + (5.0 * elmt_Parkin_asyn_dam_Ub5_DUB) + (6.0 * elmt_Parkin_asyn_dam_Ub6) + (6.0 * elmt_Parkin_asyn_dam_Ub6_DUB) + (7.0 * elmt_Parkin_asyn_dam_Ub7) + (7.0 * elmt_Parkin_asyn_dam_Ub7_DUB) + (8.0 * elmt_Parkin_asyn_dam_Ub8) + (8.0 * elmt_Parkin_asyn_dam_Ub8_DUB) + (4.0 * elmt_SUB_misfolded_Ub4_Proteasome) + (5.0 * elmt_SUB_misfolded_Ub5_Proteasome) + (6.0 * elmt_SUB_misfolded_Ub6_Proteasome) + (7.0 * elmt_SUB_misfolded_Ub7_Proteasome) + (8.0 * elmt_SUB_misfolded_Ub8_Proteasome) + elmt_Ub_UCHL1 + elmt_upregUb);
        elmt_Tot_Protein = (elmt_Tot_MisP + elmt_NatP);
        der(elmt_kremROS) = 0;
        der(elmt_kmonoUb) = 0;
        der(elmt_kbinasynLamp2a) = 0;
        der(elmt_kactDUBProt) = 0;
        der(elmt_kbinUbUCHL1) = 0;
        elmt_Tot_Ub = (elmt_Ub_Conjugates + elmt_Ub);
        der(elmt_kbinSUBUCHL1) = 0;
        der(elmt_kbinasynProt) = 0;
        elmt_Tot_asyn_dam = (elmt_asyn_dam + elmt_asyn_dam_Ub4_Proteasome + elmt_asyn_dam_Ub5_Proteasome + elmt_asyn_dam_Ub6_Proteasome + elmt_asyn_dam_Ub7_Proteasome + elmt_asyn_dam_Ub8_Proteasome + elmt_asyn_dam_Ub4_Proteasome + elmt_Parkin_asyn_dam + elmt_Parkin_asyn_dam_Ub + elmt_Parkin_asyn_dam_Ub_DUB + elmt_Parkin_asyn_dam_Ub2 + elmt_Parkin_asyn_dam_Ub2_DUB + elmt_Parkin_asyn_dam_Ub3 + elmt_Parkin_asyn_dam_Ub3_DUB + elmt_Parkin_asyn_dam_Ub4 + elmt_Parkin_asyn_dam_Ub4_DUB + elmt_Parkin_asyn_dam_Ub5 + elmt_Parkin_asyn_dam_Ub5_DUB + elmt_Parkin_asyn_dam_Ub6 + elmt_Parkin_asyn_dam_Ub6_DUB + elmt_Parkin_asyn_dam_Ub7 + elmt_Parkin_asyn_dam_Ub7_DUB + elmt_Parkin_asyn_dam_Ub8 + elmt_Parkin_asyn_dam_Ub8_DUB);
        der(elmt_kdisagg5) = 0;
        der(elmt_krefold) = 0;
        der(elmt_kaggSUB2) = 0;
        der(elmt_kaggSUB1) = 0;
        der(elmt_kaggasyn1) = 0;
        der(elmt_kdisagguchl1dam5) = 0;
        elmt_Tot_UCHL1 = (elmt_UCHL1 + elmt_UCHL1_substrate);
        der(elmt_kgenROS) = 0;
        der(elmt_kdisagguchl1dam4) = 0;
        der(elmt_kdisagguchl1dam3) = 0;
        der(elmt_kdisagguchl1dam2) = 0;
        der(elmt_kdisagg4) = 0;
        der(elmt_kdisagguchl1dam1) = 0;
        der(elmt_kbinE1Ub) = 0;
        der(elmt_kdisagg3) = 0;
        der(elmt_kdisagg2) = 0;
        der(elmt_kdisagg1) = 0;
        der(elmt_kaggasyn2) = 0;
        der(elmt_krelLamp2aUCHL1dam) = 0;
        der(elmt_kdegProtUCHL1) = 0;
        der(elmt_kbinasynParkin) = 0;
        der(elmt_kubd) = 0;
        der(elmt_kactProt) = 0;
        elmt_Tot_asyn = (elmt_asyn + elmt_asyn_Lamp2a + elmt_asyn_Proteasome);
        der(elmt_krelE3SUB) = 0;
        der(elmt_kpolyUb) = 0;
        der(elmt_kdegLysUCHL1) = 0;
        der(elmt_krelasynParkin) = 0;
        der(elmt_kubss) = 0;
        elmt_UCHL1_substrate = (elmt_E3SUB_SUB_misfolded_Ub_UCHL1 + elmt_E3SUB_SUB_misfolded_Ub2_UCHL1 + elmt_E3SUB_SUB_misfolded_Ub3_UCHL1 + elmt_E3SUB_SUB_misfolded_Ub4_UCHL1 + elmt_E3SUB_SUB_misfolded_Ub5_UCHL1 + elmt_E3SUB_SUB_misfolded_Ub6_UCHL1 + elmt_E3SUB_SUB_misfolded_Ub7_UCHL1 + elmt_E3SUB_SUB_misfolded_Ub8_UCHL1 + elmt_Lamp2a_UCHL1_damaged + elmt_Ub_UCHL1 + elmt_UCHL1_damaged + elmt_UCHL1_damaged_Proteasome + elmt_UCHL1_Proteasome);
        elmt_Tot_MisP = (elmt_E3_MisP + elmt_E3_MisP_Ub + elmt_E3_MisP_Ub_DUB + elmt_E3_MisP_Ub2 + elmt_E3_MisP_Ub2_DUB + elmt_E3_MisP_Ub3 + elmt_E3_MisP_Ub3_DUB + elmt_E3_MisP_Ub4 + elmt_E3_MisP_Ub4_DUB + elmt_E3_MisP_Ub5 + elmt_E3_MisP_Ub5_DUB + elmt_E3_MisP_Ub6 + elmt_E3_MisP_Ub6_DUB + elmt_E3_MisP_Ub7 + elmt_E3_MisP_Ub7_DUB + elmt_E3_MisP_Ub8 + elmt_E3_MisP_Ub8_DUB + elmt_MisP + elmt_MisP_Ub4_Proteasome + elmt_MisP_Ub5_Proteasome + elmt_MisP_Ub6_Proteasome + elmt_MisP_Ub7_Proteasome + elmt_MisP_Ub8_Proteasome);
        der(elmt_kdisaggSUB4) = 0;
        der(elmt_kdisaggSUB3) = 0;
        der(elmt_kdisaggSUB5) = 0;
        der(elmt_kdamasyn) = 0;
        der(elmt_kdisaggasyn1) = 0;
        der(elmt_kdisaggasyn2) = 0;
        der(elmt_ksynSUB) = 0;
        der(elmt_kdisaggasyn3) = 0;
        der(elmt_kmisfoldSUB) = 0;
        elmt_AggP = (elmt_AggA1 + elmt_AggA2 + elmt_AggA3 + elmt_AggA4 + elmt_AggA5 + elmt_aggasyn + elmt_aggasyndam + elmt_AggD1 + elmt_AggD2 + elmt_AggD3 + elmt_AggD4 + elmt_AggD5 + elmt_aggDUB + elmt_aggE3 + elmt_aggMisP + elmt_AggP1 + elmt_AggP2 + elmt_AggP3 + elmt_AggP4 + elmt_AggP5 + elmt_aggParkin + elmt_AggS1 + elmt_AggS2 + elmt_AggS3 + elmt_AggS4 + elmt_AggS5 + elmt_aggSUB + elmt_AggU1 + elmt_AggU2 + elmt_AggU3 + elmt_AggU4 + elmt_AggU5 + elmt_aggUb + elmt_aggUchl1 + elmt_aggUchl1dam);
        der(elmt_kagg2) = 0;
        der(elmt_kagg1) = 0;
        der(elmt_ksynUCHL1) = 0;
        der(elmt_kagg2dam) = 0;
        der(elmt_kactUchl1) = 0;
        der(elmt_kigrowth1) = 0;
        der(elmt_kigrowth2) = 0;

end Parameters;
