within BIOMD448;
class Reactions

    input Real elmt_k7b;
    input Real elmt_n9;
    input Real elmt_k3b;
    input Real elmt_k7f;
    input Real elmt_k3a;
    input Real elmt_n6;
    input Real elmt_mTORC2a;
    input Real elmt_X;
    input Real elmt_GLUT4m;
    input Real elmt_k4a;
    input Real elmt_IRi;
    input Real elmt_k4h;
    input Real elmt_k9b1;
    input Real elmt_AS160;
    input Real elmt_k9b2;
    input Real elmt_k4f;
    input Real elmt_IR;
    input Real elmt_k4e;
    input Real elmt_insulin;
    input Real elmt_k4c;
    input Real elmt_k9f1;
    input Real elmt_k9f2;
    input Real elmt_k4b;
    input Real elmt_IRp;
    input Real elmt_S6K;
    input Real elmt_diabetes;
    input Real elmt_Xp;
    input Real elmt_S6Kp;
    input Real elmt_k5b;
    input Real elmt_S6;
    input Real elmt_PKB473p;
    input Real elmt_k5a2;
    input Real elmt_k1f;
    input Real elmt_k1d;
    input Real elmt_k1c;
    input Real elmt_GLUT4;
    input Real elmt_AS160p;
    input Real elmt_k1a;
    input Real elmt_k5d;
    input Real elmt_k5c;
    input Real elmt_k5a1;
    input Real elmt_k2basal;
    input Real elmt_k1g;
    input Real elmt_S6p;
    input Real elmt_PKB308p;
    input Real elmt_mTORC2;
    input Real elmt_k1r;
    input Real elmt_mTORC1;
    input Real elmt_k6b;
    input Real elmt_km9;
    input Real elmt_k6f1;
    input Real elmt_km6;
    input Real elmt_IRins;
    input Real elmt_IRS1307;
    input Real elmt_k2g;
    input Real elmt_k2f;
    input Real elmt_IRS1p;
    input Real elmt_k2d;
    input Real elmt_k2c;
    input Real elmt_k6f2;
    input Real elmt_k2b;
    input Real elmt_IRS1;
    input Real elmt_k2a;
    input Real elmt_IRS1p307;
    input Real elmt_PKB;
    input Real elmt_IRip;
    input Real elmt_PKB308p473p;
    input Real elmt_k1basal;
    input Real elmt_mTORC1a;

    Real elmt_v6b1(unit = "") "v6b1";
    Real elmt_product55 "";
    Real elmt_reactant54 "";
    Real elmt_v9f2(unit = "") "v9f2";
    Real elmt_reactant64 "";
    Real elmt_product65 "";
    Real elmt_v9b1(unit = "") "v9b1";
    Real elmt_product63 "";
    Real elmt_reactant62 "";
    Real elmt_v1basal(unit = "") "v1basal";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_v9b2(unit = "") "v9b2";
    Real elmt_product67 "";
    Real elmt_reactant66 "";
    Real elmt_v1c(unit = "") "v1c";
    Real elmt_reactant4 "";
    Real elmt_product5 "";
    Real elmt_v1a(unit = "") "v1a";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_v3b(unit = "") "v3b";
    Real elmt_reactant30 "";
    Real elmt_product31 "";
    Real elmt_v5d(unit = "") "v5d";
    Real elmt_reactant38 "";
    Real elmt_product39 "";
    Real elmt_v7f(unit = "") "v7f";
    Real elmt_product57 "";
    Real elmt_reactant56 "";
    Real elmt_v3a(unit = "") "v3a";
    Real elmt_reactant28 "";
    Real elmt_product29 "";
    Real elmt_v5c(unit = "") "v5c";
    Real elmt_reactant36 "";
    Real elmt_product37 "";
    Real elmt_v5b(unit = "") "v5b";
    Real elmt_product35 "";
    Real elmt_reactant34 "";
    Real elmt_v5a(unit = "") "v5a";
    Real elmt_product33 "";
    Real elmt_reactant32 "";
    Real elmt_v7b(unit = "") "v7b";
    Real elmt_reactant58 "";
    Real elmt_product59 "";
    Real elmt_v1g(unit = "") "v1g";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_v1e(unit = "") "v1e";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_v1d(unit = "") "v1d";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_v1r(unit = "") "v1r";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_v2d(unit = "") "v2d";
    Real elmt_reactant20 "";
    Real elmt_product21 "";
    Real elmt_v4f(unit = "") "v4f";
    Real elmt_product49 "";
    Real elmt_reactant48 "";
    Real elmt_v2c(unit = "") "v2c";
    Real elmt_reactant18 "";
    Real elmt_product19 "";
    Real elmt_v4e(unit = "") "v4e";
    Real elmt_product47 "";
    Real elmt_reactant46 "";
    Real elmt_v2b(unit = "") "v2b";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_v2a(unit = "") "v2a";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_v4c(unit = "") "v4c";
    Real elmt_product45 "";
    Real elmt_reactant44 "";
    Real elmt_v4b(unit = "") "v4b";
    Real elmt_reactant42 "";
    Real elmt_product43 "";
    Real elmt_v4a(unit = "") "v4a";
    Real elmt_product41 "";
    Real elmt_reactant40 "";
    Real elmt_v6f1(unit = "") "v6f1";
    Real elmt_reactant52 "";
    Real elmt_product53 "";
    Real elmt_v9f1(unit = "") "v9f1";
    Real elmt_product61 "";
    Real elmt_reactant60 "";
    Real elmt_v2g(unit = "") "v2g";
    Real elmt_product27 "";
    Real elmt_reactant26 "";
    Real elmt_v2f(unit = "") "v2f";
    Real elmt_product23 "";
    Real elmt_reactant22 "";
    Real elmt_v4h(unit = "") "v4h";
    Real elmt_reactant50 "";
    Real elmt_product51 "";
    Real elmt_v2basal(unit = "") "v2basal";
    Real elmt_product25 "";
    Real elmt_reactant24 "";


    initial equation
        elmt_reactant40 = 1.0;
        elmt_reactant42 = 1.0;
        elmt_product33 = 1.0;
        elmt_product31 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_reactant44 = 1.0;
        elmt_reactant46 = 1.0;
        elmt_product27 = 1.0;
        elmt_product25 = 1.0;
        elmt_product29 = 1.0;
        elmt_product41 = 1.0;
        elmt_reactant50 = 1.0;
        elmt_reactant52 = 1.0;
        elmt_product45 = 1.0;
        elmt_product43 = 1.0;
        elmt_reactant58 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant54 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_product37 = 1.0;
        elmt_product35 = 1.0;
        elmt_product39 = 1.0;
        elmt_reactant62 = 1.0;
        elmt_product51 = 1.0;
        elmt_reactant64 = 1.0;
        elmt_reactant20 = 1.0;
        elmt_product55 = 1.0;
        elmt_product11 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant60 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_reactant66 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_product49 = 1.0;
        elmt_product47 = 1.0;
        elmt_product63 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_reactant30 = 1.0;
        elmt_product7 = 1.0;
        elmt_product61 = 1.0;
        elmt_product67 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product23 = 1.0;
        elmt_product65 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product21 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant36 = 1.0;
        elmt_reactant38 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant32 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant34 = 1.0;
        elmt_product59 = 1.0;
        elmt_product15 = 1.0;
        elmt_product57 = 1.0;
        elmt_product13 = 1.0;
        elmt_product19 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_v6b1 = (elmt_AS160p * elmt_k6b);
        elmt_v9f2 = (elmt_S6 * elmt_k9f2 * elmt_S6Kp);
        elmt_v9b1 = (elmt_S6Kp * elmt_k9b1);
        elmt_v1basal = (elmt_k1basal * elmt_IR);
        elmt_v9b2 = (elmt_S6p * elmt_k9b2);
        elmt_v1c = (elmt_IRins * elmt_k1c);
        elmt_v1a = (elmt_IR * elmt_k1a * elmt_insulin);
        elmt_v3b = (elmt_Xp * elmt_k3b);
        elmt_v5d = (elmt_k5d * elmt_mTORC2a);
        elmt_v7f = (elmt_GLUT4 * elmt_k7f * elmt_AS160p);
        elmt_v3a = (elmt_X * elmt_k3a * elmt_IRS1p);
        elmt_v5c = (elmt_mTORC2 * elmt_k5c * elmt_IRip);
        elmt_v5b = (elmt_mTORC1a * elmt_k5b);
        elmt_v5a = (elmt_mTORC1 * ((elmt_k5a1 * elmt_PKB308p473p) + (elmt_k5a2 * elmt_PKB308p)));
        elmt_v7b = (elmt_GLUT4m * elmt_k7b);
        elmt_v1g = (elmt_IRp * elmt_k1g);
        elmt_v1e = (elmt_IRip * elmt_k1f * elmt_Xp);
        elmt_v1d = (elmt_IRp * elmt_k1d);
        elmt_v1r = (elmt_IRi * elmt_k1r);
        elmt_v2d = (elmt_IRS1p307 * elmt_k2d);
        elmt_v4f = (elmt_k4f * elmt_PKB308p473p);
        elmt_v2c = (elmt_IRS1p * elmt_k2c * elmt_mTORC1a * elmt_diabetes);
        elmt_v4e = (elmt_k4e * elmt_PKB473p * elmt_IRS1p307);
        elmt_v2b = (elmt_IRS1p * elmt_k2b);
        elmt_v2a = (elmt_IRS1 * elmt_k2a * elmt_IRip);
        elmt_v4c = (elmt_k4c * elmt_PKB308p * elmt_mTORC2a);
        elmt_v4b = (elmt_k4b * elmt_PKB308p);
        elmt_v4a = (elmt_k4a * elmt_PKB * elmt_IRS1p);
        elmt_v6f1 = (elmt_AS160 * ((elmt_k6f1 * elmt_PKB308p473p) + ((elmt_k6f2 * Functions.pow(elmt_PKB473p, elmt_n6)) / (Functions.pow(elmt_km6, elmt_n6) + Functions.pow(elmt_PKB473p, elmt_n6)))));
        elmt_v9f1 = ((elmt_S6K * elmt_k9f1 * Functions.pow(elmt_mTORC1a, elmt_n9)) / (Functions.pow(elmt_km9, elmt_n9) + Functions.pow(elmt_mTORC1a, elmt_n9)));
        elmt_v2g = (elmt_IRS1307 * elmt_k2g);
        elmt_v2f = (elmt_IRS1p307 * elmt_k2f);
        elmt_v4h = (elmt_k4h * elmt_PKB473p);
        elmt_v2basal = (elmt_IRS1 * elmt_k2basal);
        der(elmt_reactant40) = 0;
        der(elmt_reactant42) = 0;
        der(elmt_product33) = 0;
        der(elmt_product31) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_reactant44) = 0;
        der(elmt_reactant46) = 0;
        der(elmt_product27) = 0;
        der(elmt_product25) = 0;
        der(elmt_product29) = 0;
        der(elmt_product41) = 0;
        der(elmt_reactant50) = 0;
        der(elmt_reactant52) = 0;
        der(elmt_product45) = 0;
        der(elmt_product43) = 0;
        der(elmt_reactant58) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant54) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_product37) = 0;
        der(elmt_product35) = 0;
        der(elmt_product39) = 0;
        der(elmt_reactant62) = 0;
        der(elmt_product51) = 0;
        der(elmt_reactant64) = 0;
        der(elmt_reactant20) = 0;
        der(elmt_product55) = 0;
        der(elmt_product11) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant60) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_reactant66) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_product49) = 0;
        der(elmt_product47) = 0;
        der(elmt_product63) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_reactant30) = 0;
        der(elmt_product7) = 0;
        der(elmt_product61) = 0;
        der(elmt_product67) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product23) = 0;
        der(elmt_product65) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product21) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant36) = 0;
        der(elmt_reactant38) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant34) = 0;
        der(elmt_product59) = 0;
        der(elmt_product15) = 0;
        der(elmt_product57) = 0;
        der(elmt_product13) = 0;
        der(elmt_product19) = 0;
        der(elmt_product17) = 0;

end Reactions;
