within BIOMD528;
class Parameters

    input Real elmt_SOCS1m;
    input Real elmt_IFNb_env;
    input Real elmt_IFNa_env;

    Real elmt_n3(unit = "") "";
    Real elmt_tao9(unit = "") "";
    Real elmt_r5(unit = "") "";
    Real elmt_n1(unit = "") "";
    Real elmt_n2(unit = "") "";
    Real elmt_r3(unit = "") "";
    Real elmt_K19(unit = "") "";
    Real elmt_r4(unit = "") "";
    Real elmt_K17(unit = "") "";
    Real elmt_r1(unit = "") "";
    Real elmt_tao1(unit = "") "";
    Real elmt_vmax2(unit = "") "";
    Real elmt_tao4(unit = "") "";
    Real elmt_tao3(unit = "") "";
    Real elmt_tao6(unit = "") "";
    Real elmt_tao8(unit = "") "";
    Real elmt_TJ(unit = "") "";
    Real elmt_k16(unit = "") "";
    Real elmt_r0(unit = "") "";
    Real elmt_k15(unit = "") "";
    Real elmt_k14(unit = "") "";
    Real elmt_k12(unit = "") "";
    Real elmt_k11(unit = "") "";
    Real elmt_K20(unit = "") "";
    Real elmt_delta(unit = "") "";
    Real elmt_IC1(unit = "") "";
    Real elmt_IC2(unit = "") "";
    Real elmt_k8(unit = "") "";
    Real elmt_C(unit = "") "";
    Real elmt_k26(unit = "") "";
    Real elmt_NS(unit = "") "";
    Real elmt_k28(unit = "") "";
    Real elmt_K9(unit = "") "";
    Real elmt_rmax20(unit = "") "";
    Real elmt_bm(unit = "") "";
    Real elmt_K5(unit = "") "";
    Real elmt_K2(unit = "") "";
    Real elmt_K3(unit = "") "";
    Real elmt_NA(unit = "") "";
    Real elmt_TJtot(unit = "") "";
    Real elmt_sv(unit = "") "";
    Real elmt_tao12(unit = "") "";
    Real elmt_tao13(unit = "") "";
    Real elmt_IC2ifa(unit = "") "";
    Real elmt_delta1(unit = "") "";
    Real elmt_delta2(unit = "") "";
    Real elmt_sp(unit = "") "";
    Real elmt_vmax19(unit = "") "";
    Real elmt_vmax17(unit = "") "";


    initial equation
        elmt_n3 = 5.0;
        elmt_tao9 = 2.0;
        elmt_r5 = 1.0;
        elmt_n1 = 1.0;
        elmt_n2 = 5.0;
        elmt_r3 = 1.0E-7;
        elmt_K19 = 0.004;
        elmt_r4 = 1.0E-5;
        elmt_K17 = 0.002;
        elmt_r1 = 1.0E-4;
        elmt_tao1 = 2.5;
        elmt_vmax2 = 72000.0;
        elmt_tao4 = 0.46;
        elmt_tao3 = 0.56;
        elmt_tao6 = 1.0;
        elmt_tao8 = 2.0;
        elmt_k16 = 0.36;
        elmt_r0 = 0.001;
        elmt_k15 = 3.6E-8;
        elmt_k14 = 3.204E-7;
        elmt_k12 = 360.0;
        elmt_k11 = 3.6E-4;
        elmt_K20 = 6.0E-4;
        elmt_delta = 3.0E-4;
        elmt_k8 = 0.0036;
        elmt_C = 500000.0;
        elmt_k26 = 0.360085;
        elmt_k28 = 360.0;
        elmt_K9 = 780.0;
        elmt_rmax20 = 0.001;
        elmt_bm = 6.0;
        elmt_K5 = 0.01;
        elmt_K2 = 0.002;
        elmt_K3 = 0.0043;
        elmt_NA = 6.023E23;
        elmt_TJtot = 1.0E-4;
        elmt_sv = 0.1;
        elmt_tao12 = 1.0;
        elmt_tao13 = 15.0;
        elmt_delta1 = 0.1;
        elmt_delta2 = 0.4;
        elmt_sp = 0.3;
        elmt_vmax19 = 154800.0;
        elmt_vmax17 = 72000.0;


    equation
        der(elmt_n3) = 0;
        der(elmt_tao9) = 0;
        der(elmt_r5) = 0;
        der(elmt_n1) = 0;
        der(elmt_n2) = 0;
        der(elmt_r3) = 0;
        der(elmt_K19) = 0;
        der(elmt_r4) = 0;
        der(elmt_K17) = 0;
        der(elmt_r1) = 0;
        der(elmt_tao1) = 0;
        der(elmt_vmax2) = 0;
        der(elmt_tao4) = 0;
        der(elmt_tao3) = 0;
        der(elmt_tao6) = 0;
        der(elmt_tao8) = 0;
        elmt_TJ = ((((elmt_TJtot * (elmt_IFNb_env + elmt_IFNa_env)) / (elmt_K3 + elmt_IFNb_env + elmt_IFNa_env)) * 1.0) / (1.0 + ((elmt_K9 * elmt_SOCS1m) / elmt_delta)));
        der(elmt_k16) = 0;
        der(elmt_r0) = 0;
        der(elmt_k15) = 0;
        der(elmt_k14) = 0;
        der(elmt_k12) = 0;
        der(elmt_k11) = 0;
        der(elmt_K20) = 0;
        der(elmt_delta) = 0;
        elmt_IC1 = ((1.0 + (elmt_sp * Functions.pow((elmt_NS / elmt_delta1), elmt_n1))) / (1.0 + Functions.pow((elmt_NS / elmt_delta1), elmt_n1)));
        elmt_IC2 = 1.0;
        der(elmt_k8) = 0;
        der(elmt_C) = 0;
        der(elmt_k26) = 0;
        elmt_NS = ((elmt_r5 * Functions.pow(time, elmt_n3)) / (Functions.pow(elmt_bm, elmt_n3) + Functions.pow(time, elmt_n3)));
        der(elmt_k28) = 0;
        der(elmt_K9) = 0;
        der(elmt_rmax20) = 0;
        der(elmt_bm) = 0;
        der(elmt_K5) = 0;
        der(elmt_K2) = 0;
        der(elmt_K3) = 0;
        der(elmt_NA) = 0;
        der(elmt_TJtot) = 0;
        der(elmt_sv) = 0;
        der(elmt_tao12) = 0;
        der(elmt_tao13) = 0;
        elmt_IC2ifa = 1.0;
        der(elmt_delta1) = 0;
        der(elmt_delta2) = 0;
        der(elmt_sp) = 0;
        der(elmt_vmax19) = 0;
        der(elmt_vmax17) = 0;

end Parameters;
