/* Initialization */
/* Simulation code for MoonLanding generated by the OpenModelica Compiler 1.9.2 (r25115). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "MoonLanding_functions.h"
#include "MoonLanding_model.h"
#include "MoonLanding_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "MoonLanding_11mix.h"
#include "MoonLanding_12jac.h"
#if defined(__cplusplus)
extern "C" {
#endif


/*
 equation index: 1
 type: SIMPLE_ASSIGN
 apollo._altitude = apollo.initial_altitude
 */
void MoonLanding_eqFunction_1(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,1};
  $Papollo$Paltitude = $Papollo$Pinitial_altitude;
  TRACE_POP
}
/*
 equation index: 2
 type: SIMPLE_ASSIGN
 $whenCondition1 = false
 */
void MoonLanding_eqFunction_2(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,2};
  $P$whenCondition1 = 0;
  TRACE_POP
}
/*
 equation index: 3
 type: SIMPLE_ASSIGN
 apollo._velocity = apollo.initial_velocity
 */
void MoonLanding_eqFunction_3(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,3};
  $Papollo$Pvelocity = $Papollo$Pinitial_velocity;
  TRACE_POP
}
/*
 equation index: 4
 type: SIMPLE_ASSIGN
 der(apollo._altitude) = apollo.velocity
 */
void MoonLanding_eqFunction_4(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,4};
  $P$DER$Papollo$Paltitude = $Papollo$Pvelocity;
  TRACE_POP
}
/*
 equation index: 5
 type: SIMPLE_ASSIGN
 $PRE._apollo._gravity = $_start(apollo.gravity)
 */
void MoonLanding_eqFunction_5(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,5};
  $P$PRE$Papollo$Pgravity = $P$ATTRIBUTE$Papollo$Pgravity.start;
  TRACE_POP
}
/*
 equation index: 6
 type: SIMPLE_ASSIGN
 $PRE._apollo._thrust = $_start(apollo.thrust)
 */
void MoonLanding_eqFunction_6(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,6};
  $P$PRE$Papollo$Pthrust = $P$ATTRIBUTE$Papollo$Pthrust.start;
  TRACE_POP
}
/*
 equation index: 7
 type: SIMPLE_ASSIGN
 apollo._thrust = $PRE.apollo.thrust
 */
void MoonLanding_eqFunction_7(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,7};
  $Papollo$Pthrust = $P$PRE$Papollo$Pthrust;
  TRACE_POP
}
/*
 equation index: 8
 type: SIMPLE_ASSIGN
 der(apollo._mass) = (-apollo.massLossRate) * abs(apollo.thrust)
 */
void MoonLanding_eqFunction_8(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,8};
  $P$DER$Papollo$Pmass = ((-$Papollo$PmassLossRate) * fabs($Papollo$Pthrust));
  TRACE_POP
}
/*
 equation index: 9
 type: SIMPLE_ASSIGN
 apollo._gravity = $PRE.apollo.gravity
 */
void MoonLanding_eqFunction_9(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,9};
  $Papollo$Pgravity = $P$PRE$Papollo$Pgravity;
  TRACE_POP
}
/*
 equation index: 10
 type: SIMPLE_ASSIGN
 apollo._mass = apollo.initialmass
 */
void MoonLanding_eqFunction_10(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,10};
  $Papollo$Pmass = $Papollo$Pinitialmass;
  TRACE_POP
}
/*
 equation index: 11
 type: SIMPLE_ASSIGN
 apollo._acceleration = DIVISION(apollo.thrust - apollo.mass * apollo.gravity, apollo.mass)
 */
void MoonLanding_eqFunction_11(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,11};
  $Papollo$Pacceleration = DIVISION_SIM(($Papollo$Pthrust - ($Papollo$Pmass * $Papollo$Pgravity)),$Papollo$Pmass,"apollo.mass",equationIndexes);
  TRACE_POP
}
/*
 equation index: 12
 type: SIMPLE_ASSIGN
 der(apollo._velocity) = apollo.acceleration
 */
void MoonLanding_eqFunction_12(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,12};
  $P$DER$Papollo$Pvelocity = $Papollo$Pacceleration;
  TRACE_POP
}


int MoonLanding_functionInitialEquations(DATA *data)
{
  TRACE_PUSH

  data->simulationInfo.discreteCall = 1;
  MoonLanding_eqFunction_1(data);

  MoonLanding_eqFunction_2(data);

  MoonLanding_eqFunction_3(data);

  MoonLanding_eqFunction_4(data);

  MoonLanding_eqFunction_5(data);

  MoonLanding_eqFunction_6(data);

  MoonLanding_eqFunction_7(data);

  MoonLanding_eqFunction_8(data);

  MoonLanding_eqFunction_9(data);

  MoonLanding_eqFunction_10(data);

  MoonLanding_eqFunction_11(data);

  MoonLanding_eqFunction_12(data);
  data->simulationInfo.discreteCall = 0;
  
  TRACE_POP
  return 0;
}
int MoonLanding_functionRemovedInitialEquations(DATA *data)
{
  TRACE_PUSH
  const int *equationIndexes = NULL;
  double res = 0.0;

  
  TRACE_POP
  return 0;
}

/* funtion initialize mixed systems */
void MoonLanding_initialMixedSystem(int nMixedSystems, MIXED_SYSTEM_DATA* mixedSystemData)
{
  /* initial mixed systems */
  /* parameter mixed systems */
  /* model mixed systems */
  /* jacobians mixed systems */
}

#if defined(__cplusplus)
}
#endif

