/* Initialization */
/* Simulation code for System generated by the OpenModelica Compiler 1.9.2 (r25115). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "System_functions.h"
#include "System_model.h"
#include "System_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData

#include "System_11mix.h"
#include "System_12jac.h"
#if defined(__cplusplus)
extern "C" {
#endif


/*
 equation index: 1
 type: SIMPLE_ASSIGN
 x = 1.0
 */
void System_eqFunction_1(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,1};
  $Px = 1.0;
  TRACE_POP
}
/*
 equation index: 2
 type: SIMPLE_ASSIGN
 der(x) = -sqrt(x)
 */
void System_eqFunction_2(DATA *data)
{
  TRACE_PUSH
  const int equationIndexes[2] = {1,2};
  modelica_real tmp0;
  tmp0 = $Px; 
  if(!(tmp0 >= 0.0))
  {
      FILE_INFO info = {"",0,0,0,0,0};
      omc_assert_warning(info, "The following assertion has been violated at time %f", time);
      throwStreamPrintWithEquationIndexes(threadData, equationIndexes, "Model error: Argument of sqrt(x) was %g should be >= 0", tmp0);
  }
  $P$DER$Px = (-sqrt(tmp0));
  TRACE_POP
}


int System_functionInitialEquations(DATA *data)
{
  TRACE_PUSH

  data->simulationInfo.discreteCall = 1;
  System_eqFunction_1(data);

  System_eqFunction_2(data);
  data->simulationInfo.discreteCall = 0;
  
  TRACE_POP
  return 0;
}
int System_functionRemovedInitialEquations(DATA *data)
{
  TRACE_PUSH
  const int *equationIndexes = NULL;
  double res = 0.0;

  
  TRACE_POP
  return 0;
}

/* funtion initialize mixed systems */
void System_initialMixedSystem(int nMixedSystems, MIXED_SYSTEM_DATA* mixedSystemData)
{
  /* initial mixed systems */
  /* parameter mixed systems */
  /* model mixed systems */
  /* jacobians mixed systems */
}

#if defined(__cplusplus)
}
#endif

