within BIOMD042;
model Glycolysis_Nielsen "Nielsen1998_Glycolysis" annotation(Documentation(info="<annotation>
  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
  </rdf:RDF>
</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_compartment elmt_compartment;

    equation
        Reacs.elmt_k9f = Params.elmt_k9f;
        Reacs.elmt_k5b = Params.elmt_k5b;
        Reacs.elmt_compartment = elmt_compartment.elmt_compartment;
        Reacs.elmt_GAP = elmt_compartment.elmt_GAP;
        Reacs.elmt_k9b = Params.elmt_k9b;
        Reacs.elmt_K2ATP = Params.elmt_K2ATP;
        Reacs.elmt_NAD = elmt_compartment.elmt_NAD;
        Reacs.elmt_k3f = Params.elmt_k3f;
        Reacs.elmt_ATP = elmt_compartment.elmt_ATP;
        Reacs.elmt_GLC = elmt_compartment.elmt_GLC;
        Reacs.elmt_PEP = elmt_compartment.elmt_PEP;
        Reacs.elmt_DPG = elmt_compartment.elmt_DPG;
        Reacs.elmt_k5f = Params.elmt_k5f;
        Reacs.elmt_k3b = Params.elmt_k3b;
        Reacs.elmt_K2 = Params.elmt_K2;
        Reacs.elmt_K7PYR = Params.elmt_K7PYR;
        Reacs.elmt_K6ADP = Params.elmt_K6ADP;
        Reacs.elmt_K1ATP = Params.elmt_K1ATP;
        Reacs.elmt_ADP = elmt_compartment.elmt_ADP;
        Reacs.elmt_flow = Params.elmt_flow;
        Reacs.elmt_k10 = Params.elmt_k10;
        Reacs.elmt_NADH = elmt_compartment.elmt_NADH;
        Reacs.elmt_P = elmt_compartment.elmt_P;
        Reacs.elmt_k8b = Params.elmt_k8b;
        Reacs.elmt_V7 = Params.elmt_V7;
        Reacs.elmt_FBP = elmt_compartment.elmt_FBP;
        Reacs.elmt_K1GLC = Params.elmt_K1GLC;
        Reacs.elmt_V6 = Params.elmt_V6;
        Reacs.elmt_ACA = elmt_compartment.elmt_ACA;
        Reacs.elmt_F6P = elmt_compartment.elmt_F6P;
        Reacs.elmt_EtOH = elmt_compartment.elmt_EtOH;
        Reacs.elmt_k2 = Params.elmt_k2;
        Reacs.elmt_k8f = Params.elmt_k8f;
        Reacs.elmt_AMP = elmt_compartment.elmt_AMP;
        Reacs.elmt_K4NAD = Params.elmt_K4NAD;
        Reacs.elmt_V4 = Params.elmt_V4;
        Reacs.elmt_V1 = Params.elmt_V1;
        Reacs.elmt_V2 = Params.elmt_V2;
        Reacs.elmt_K4GAP = Params.elmt_K4GAP;
        Reacs.elmt_K6PEP = Params.elmt_K6PEP;
        Reacs.elmt_PYR = elmt_compartment.elmt_PYR;
        elmt_compartment.elmt_reactant40 = Reacs.elmt_reactant40;
        elmt_compartment.elmt_FBPflow = Reacs.elmt_FBPflow;
        elmt_compartment.elmt_NADflow = Reacs.elmt_NADflow;
        elmt_compartment.elmt_product32 = Reacs.elmt_product32;
        elmt_compartment.elmt_F6Pflow = Reacs.elmt_F6Pflow;
        elmt_compartment.elmt_product31 = Reacs.elmt_product31;
        elmt_compartment.elmt_PYRflow = Reacs.elmt_PYRflow;
        elmt_compartment.elmt_reactant43 = Reacs.elmt_reactant43;
        elmt_compartment.elmt_reactant44 = Reacs.elmt_reactant44;
        elmt_compartment.elmt_EtOHflow = Reacs.elmt_EtOHflow;
        elmt_compartment.elmt_reactant46 = Reacs.elmt_reactant46;
        elmt_compartment.elmt_DPGflow = Reacs.elmt_DPGflow;
        elmt_compartment.elmt_product27 = Reacs.elmt_product27;
        elmt_compartment.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_compartment.elmt_product24 = Reacs.elmt_product24;
        elmt_compartment.elmt_product28 = Reacs.elmt_product28;
        elmt_compartment.elmt_product41 = Reacs.elmt_product41;
        elmt_compartment.elmt_product45 = Reacs.elmt_product45;
        elmt_compartment.elmt_product42 = Reacs.elmt_product42;
        elmt_compartment.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_compartment.elmt_reaction_3 = Reacs.elmt_reaction_3;
        elmt_compartment.elmt_GLCflow = Reacs.elmt_GLCflow;
        elmt_compartment.elmt_reaction_4 = Reacs.elmt_reaction_4;
        elmt_compartment.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_compartment.elmt_ACAflow = Reacs.elmt_ACAflow;
        elmt_compartment.elmt_reaction_1 = Reacs.elmt_reaction_1;
        elmt_compartment.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_compartment.elmt_reaction_2 = Reacs.elmt_reaction_2;
        elmt_compartment.elmt_reactant10 = Reacs.elmt_reactant10;
        elmt_compartment.elmt_reactant11 = Reacs.elmt_reactant11;
        elmt_compartment.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_compartment.elmt_reactant13 = Reacs.elmt_reactant13;
        elmt_compartment.elmt_Pflow = Reacs.elmt_Pflow;
        elmt_compartment.elmt_reaction_9 = Reacs.elmt_reaction_9;
        elmt_compartment.elmt_reaction_7 = Reacs.elmt_reaction_7;
        elmt_compartment.elmt_reaction_8 = Reacs.elmt_reaction_8;
        elmt_compartment.elmt_ATPflow = Reacs.elmt_ATPflow;
        elmt_compartment.elmt_reaction_5 = Reacs.elmt_reaction_5;
        elmt_compartment.elmt_reaction_6 = Reacs.elmt_reaction_6;
        elmt_compartment.elmt_product38 = Reacs.elmt_product38;
        elmt_compartment.elmt_product36 = Reacs.elmt_product36;
        elmt_compartment.elmt_product35 = Reacs.elmt_product35;
        elmt_compartment.elmt_reaction_10 = Reacs.elmt_reaction_10;
        elmt_compartment.elmt_reactant20 = Reacs.elmt_reactant20;
        elmt_compartment.elmt_NADHflow = Reacs.elmt_NADHflow;
        elmt_compartment.elmt_reactant25 = Reacs.elmt_reactant25;
        elmt_compartment.elmt_reactant26 = Reacs.elmt_reactant26;
        elmt_compartment.elmt_PEPflow = Reacs.elmt_PEPflow;
        elmt_compartment.elmt_reactant23 = Reacs.elmt_reactant23;
        elmt_compartment.elmt_reactant19 = Reacs.elmt_reactant19;
        elmt_compartment.elmt_product47 = Reacs.elmt_product47;
        elmt_compartment.elmt_reactant30 = Reacs.elmt_reactant30;
        elmt_compartment.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_compartment.elmt_reactant5 = Reacs.elmt_reactant5;
        elmt_compartment.elmt_product22 = Reacs.elmt_product22;
        elmt_compartment.elmt_product21 = Reacs.elmt_product21;
        elmt_compartment.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_compartment.elmt_reactant7 = Reacs.elmt_reactant7;
        elmt_compartment.elmt_product1 = Reacs.elmt_product1;
        elmt_compartment.elmt_product0 = Reacs.elmt_product0;
        elmt_compartment.elmt_reactant37 = Reacs.elmt_reactant37;
        elmt_compartment.elmt_reactant39 = Reacs.elmt_reactant39;
        elmt_compartment.elmt_product4 = Reacs.elmt_product4;
        elmt_compartment.elmt_reactant33 = Reacs.elmt_reactant33;
        elmt_compartment.elmt_product3 = Reacs.elmt_product3;
        elmt_compartment.elmt_reactant34 = Reacs.elmt_reactant34;
        elmt_compartment.elmt_product2 = Reacs.elmt_product2;
        elmt_compartment.elmt_reactant29 = Reacs.elmt_reactant29;
        elmt_compartment.elmt_ADPflow = Reacs.elmt_ADPflow;
        elmt_compartment.elmt_GAPflow = Reacs.elmt_GAPflow;
        elmt_compartment.elmt_AMPflow = Reacs.elmt_AMPflow;
        elmt_compartment.elmt_product18 = Reacs.elmt_product18;
        elmt_compartment.elmt_product17 = Reacs.elmt_product17;

end Glycolysis_Nielsen;
