within BIOMD427;
model MODEL1209230000 "Bianconi2012 - EGFR and IGF1R pathway in lung cancer" annotation(Documentation(info="<annotation>
	<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
	
	
	</rdf:RDF>
	</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_cell_nsclc elmt_cell_nsclc;

    equation
        Reacs.elmt_Raf = elmt_cell_nsclc.elmt_Raf;
        Reacs.elmt_Mek = elmt_cell_nsclc.elmt_Mek;
        Reacs.elmt_P90Rsk_Active = elmt_cell_nsclc.elmt_P90Rsk_Active;
        Reacs.elmt_k_P90Rsk_ERKActive = Params.elmt_k_P90Rsk_ERKActive;
        Reacs.elmt_Raf_active = elmt_cell_nsclc.elmt_Raf_active;
        Reacs.elmt_ERK = elmt_cell_nsclc.elmt_ERK;
        Reacs.elmt_PI3KCA = elmt_cell_nsclc.elmt_PI3KCA;
        Reacs.elmt_Ras = elmt_cell_nsclc.elmt_Ras;
        Reacs.elmt_EGFR_active = elmt_cell_nsclc.elmt_EGFR_active;
        Reacs.elmt_D_SOS = elmt_cell_nsclc.elmt_D_SOS;
        Reacs.elmt_gamma_EGFR = Params.elmt_gamma_EGFR;
        Reacs.elmt_RafPP = elmt_cell_nsclc.elmt_RafPP;
        Reacs.elmt_gamma_IGFR = Params.elmt_gamma_IGFR;
        Reacs.elmt_A_SOS = elmt_cell_nsclc.elmt_A_SOS;
        Reacs.elmt_kd_PI3K_a = Params.elmt_kd_PI3K_a;
        Reacs.elmt_IGFR_active = elmt_cell_nsclc.elmt_IGFR_active;
        Reacs.elmt_RasGapActive = elmt_cell_nsclc.elmt_RasGapActive;
        Reacs.elmt_P90RskInactive = elmt_cell_nsclc.elmt_P90RskInactive;
        Reacs.elmt_ERK_active = elmt_cell_nsclc.elmt_ERK_active;
        Reacs.elmt_AKT_active = elmt_cell_nsclc.elmt_AKT_active;
        Reacs.elmt_Ras_active = elmt_cell_nsclc.elmt_Ras_active;
        Reacs.elmt_PI3KCA_active = elmt_cell_nsclc.elmt_PI3KCA_active;
        Reacs.elmt_PP2A = elmt_cell_nsclc.elmt_PP2A;
        Reacs.elmt_KM_P90Rsk_ERKActive = Params.elmt_KM_P90Rsk_ERKActive;
        Reacs.elmt_Mek_active = elmt_cell_nsclc.elmt_Mek_active;
        Reacs.elmt_AKT = elmt_cell_nsclc.elmt_AKT;
        elmt_cell_nsclc.elmt_product73 = Reacs.elmt_product73;
        elmt_cell_nsclc.elmt_reactant40 = Reacs.elmt_reactant40;
        elmt_cell_nsclc.elmt_product72 = Reacs.elmt_product72;
        elmt_cell_nsclc.elmt_product75 = Reacs.elmt_product75;
        elmt_cell_nsclc.elmt_reactant47 = Reacs.elmt_reactant47;
        elmt_cell_nsclc.elmt_reactant48 = Reacs.elmt_reactant48;
        elmt_cell_nsclc.elmt_reactant43 = Reacs.elmt_reactant43;
        elmt_cell_nsclc.elmt_reactant44 = Reacs.elmt_reactant44;
        elmt_cell_nsclc.elmt_product69 = Reacs.elmt_product69;
        elmt_cell_nsclc.elmt_product68 = Reacs.elmt_product68;
        elmt_cell_nsclc.elmt_ERK_activationBy_Mek = Reacs.elmt_ERK_activationBy_Mek;
        elmt_cell_nsclc.elmt_reactant51 = Reacs.elmt_reactant51;
        elmt_cell_nsclc.elmt_reactant52 = Reacs.elmt_reactant52;
        elmt_cell_nsclc.elmt_reactant59 = Reacs.elmt_reactant59;
        elmt_cell_nsclc.elmt_reactant55 = Reacs.elmt_reactant55;
        elmt_cell_nsclc.elmt_reactant56 = Reacs.elmt_reactant56;
        elmt_cell_nsclc.elmt_PI3KCA_activationBy_IGF1R = Reacs.elmt_PI3KCA_activationBy_IGF1R;
        elmt_cell_nsclc.elmt_Akt_activationBy_PI3KCA = Reacs.elmt_Akt_activationBy_PI3KCA;
        elmt_cell_nsclc.elmt_Raf_deactivation = Reacs.elmt_Raf_deactivation;
        elmt_cell_nsclc.elmt_product12 = Reacs.elmt_product12;
        elmt_cell_nsclc.elmt_product11 = Reacs.elmt_product11;
        elmt_cell_nsclc.elmt_reactant25 = Reacs.elmt_reactant25;
        elmt_cell_nsclc.elmt_reactant26 = Reacs.elmt_reactant26;
        elmt_cell_nsclc.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_cell_nsclc.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_cell_nsclc.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_cell_nsclc.elmt_EGFR_degradation = Reacs.elmt_EGFR_degradation;
        elmt_cell_nsclc.elmt_SOS_activationBy_IGF = Reacs.elmt_SOS_activationBy_IGF;
        elmt_cell_nsclc.elmt_product7 = Reacs.elmt_product7;
        elmt_cell_nsclc.elmt_reactant30 = Reacs.elmt_reactant30;
        elmt_cell_nsclc.elmt_SOS_conformational_activation = Reacs.elmt_SOS_conformational_activation;
        elmt_cell_nsclc.elmt_product6 = Reacs.elmt_product6;
        elmt_cell_nsclc.elmt_product23 = Reacs.elmt_product23;
        elmt_cell_nsclc.elmt_product20 = Reacs.elmt_product20;
        elmt_cell_nsclc.elmt_reactant36 = Reacs.elmt_reactant36;
        elmt_cell_nsclc.elmt_reactant39 = Reacs.elmt_reactant39;
        elmt_cell_nsclc.elmt_reactant33 = Reacs.elmt_reactant33;
        elmt_cell_nsclc.elmt_product3 = Reacs.elmt_product3;
        elmt_cell_nsclc.elmt_product2 = Reacs.elmt_product2;
        elmt_cell_nsclc.elmt_reactant35 = Reacs.elmt_reactant35;
        elmt_cell_nsclc.elmt_reactant29 = Reacs.elmt_reactant29;
        elmt_cell_nsclc.elmt_product16 = Reacs.elmt_product16;
        elmt_cell_nsclc.elmt_product15 = Reacs.elmt_product15;
        elmt_cell_nsclc.elmt_product19 = Reacs.elmt_product19;
        elmt_cell_nsclc.elmt_product34 = Reacs.elmt_product34;
        elmt_cell_nsclc.elmt_product32 = Reacs.elmt_product32;
        elmt_cell_nsclc.elmt_product31 = Reacs.elmt_product31;
        elmt_cell_nsclc.elmt_PI3KCA_activationBy_kRas = Reacs.elmt_PI3KCA_activationBy_kRas;
        elmt_cell_nsclc.elmt_SOS_deactivationBy_P90 = Reacs.elmt_SOS_deactivationBy_P90;
        elmt_cell_nsclc.elmt_product27 = Reacs.elmt_product27;
        elmt_cell_nsclc.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_cell_nsclc.elmt_product24 = Reacs.elmt_product24;
        elmt_cell_nsclc.elmt_product28 = Reacs.elmt_product28;
        elmt_cell_nsclc.elmt_product41 = Reacs.elmt_product41;
        elmt_cell_nsclc.elmt_product45 = Reacs.elmt_product45;
        elmt_cell_nsclc.elmt_product42 = Reacs.elmt_product42;
        elmt_cell_nsclc.elmt_reactant14 = Reacs.elmt_reactant14;
        elmt_cell_nsclc.elmt_reactant17 = Reacs.elmt_reactant17;
        elmt_cell_nsclc.elmt_IGFR_active_degradation = Reacs.elmt_IGFR_active_degradation;
        elmt_cell_nsclc.elmt_reactant10 = Reacs.elmt_reactant10;
        elmt_cell_nsclc.elmt_P90_activationBy_ERK = Reacs.elmt_P90_activationBy_ERK;
        elmt_cell_nsclc.elmt_Mek_deactivation = Reacs.elmt_Mek_deactivation;
        elmt_cell_nsclc.elmt_reactant13 = Reacs.elmt_reactant13;
        elmt_cell_nsclc.elmt_kRas_Activation = Reacs.elmt_kRas_Activation;
        elmt_cell_nsclc.elmt_ERK_deactivationBy_PP2A = Reacs.elmt_ERK_deactivationBy_PP2A;
        elmt_cell_nsclc.elmt_product38 = Reacs.elmt_product38;
        elmt_cell_nsclc.elmt_product37 = Reacs.elmt_product37;
        elmt_cell_nsclc.elmt_Mek_activationBy_Raf = Reacs.elmt_Mek_activationBy_Raf;
        elmt_cell_nsclc.elmt_reactant63 = Reacs.elmt_reactant63;
        elmt_cell_nsclc.elmt_product50 = Reacs.elmt_product50;
        elmt_cell_nsclc.elmt_reactant64 = Reacs.elmt_reactant64;
        elmt_cell_nsclc.elmt_product54 = Reacs.elmt_product54;
        elmt_cell_nsclc.elmt_product53 = Reacs.elmt_product53;
        elmt_cell_nsclc.elmt_reactant60 = Reacs.elmt_reactant60;
        elmt_cell_nsclc.elmt_reactant66 = Reacs.elmt_reactant66;
        elmt_cell_nsclc.elmt_reactant67 = Reacs.elmt_reactant67;
        elmt_cell_nsclc.elmt_Raf_deactivationBy_Akt = Reacs.elmt_Raf_deactivationBy_Akt;
        elmt_cell_nsclc.elmt_product49 = Reacs.elmt_product49;
        elmt_cell_nsclc.elmt_product46 = Reacs.elmt_product46;
        elmt_cell_nsclc.elmt_reactant1 = Reacs.elmt_reactant1;
        elmt_cell_nsclc.elmt_product62 = Reacs.elmt_product62;
        elmt_cell_nsclc.elmt_reactant4 = Reacs.elmt_reactant4;
        elmt_cell_nsclc.elmt_product61 = Reacs.elmt_product61;
        elmt_cell_nsclc.elmt_reactant74 = Reacs.elmt_reactant74;
        elmt_cell_nsclc.elmt_reactant5 = Reacs.elmt_reactant5;
        elmt_cell_nsclc.elmt_reactant70 = Reacs.elmt_reactant70;
        elmt_cell_nsclc.elmt_product65 = Reacs.elmt_product65;
        elmt_cell_nsclc.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_cell_nsclc.elmt_reactant71 = Reacs.elmt_reactant71;
        elmt_cell_nsclc.elmt_Akt_deactivation = Reacs.elmt_Akt_deactivation;
        elmt_cell_nsclc.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_cell_nsclc.elmt_PI3KCA_activationBy_EGF = Reacs.elmt_PI3KCA_activationBy_EGF;
        elmt_cell_nsclc.elmt_Raf_activationBy_kRas = Reacs.elmt_Raf_activationBy_kRas;
        elmt_cell_nsclc.elmt_Ras_deactivation = Reacs.elmt_Ras_deactivation;
        elmt_cell_nsclc.elmt_product58 = Reacs.elmt_product58;
        elmt_cell_nsclc.elmt_product57 = Reacs.elmt_product57;
        elmt_cell_nsclc.elmt_P90_deactivation = Reacs.elmt_P90_deactivation;
        elmt_cell_nsclc.elmt_PI3KCA_deactivation = Reacs.elmt_PI3KCA_deactivation;

end MODEL1209230000;
