within BIOMD427;
class Reactions

    input Real elmt_Raf;
    input Real elmt_Mek;
    input Real elmt_P90Rsk_Active;
    input Real elmt_k_P90Rsk_ERKActive;
    input Real elmt_Raf_active;
    input Real elmt_ERK;
    input Real elmt_PI3KCA;
    input Real elmt_Ras;
    input Real elmt_EGFR_active;
    input Real elmt_D_SOS;
    input Real elmt_gamma_EGFR;
    input Real elmt_RafPP;
    input Real elmt_gamma_IGFR;
    input Real elmt_A_SOS;
    input Real elmt_kd_PI3K_a;
    input Real elmt_IGFR_active;
    input Real elmt_RasGapActive;
    input Real elmt_P90RskInactive;
    input Real elmt_ERK_active;
    input Real elmt_AKT_active;
    input Real elmt_Ras_active;
    input Real elmt_PI3KCA_active;
    input Real elmt_PP2A;
    input Real elmt_KM_P90Rsk_ERKActive;
    input Real elmt_Mek_active;
    input Real elmt_AKT;

    Real elmt_Raf_deactivation(unit = "") "Raf deactivation by RafPP";
    parameter Real elmt_Raf_deactivation_elmt_KM_RasActive_RafPP(unit "") = 1061.71 "";
    parameter Real elmt_Raf_deactivation_elmt_k_RasActive_RafPP(unit "") = 0.126329 "";
    parameter Real elmt_Raf_deactivation_elmt_n_RasActive_RafPP(unit "") = 1.0 "";
    Real elmt_product69 "";
    Real elmt_product68 "";
    Real elmt_reactant66 "";
    Real elmt_reactant67 "";
    Real elmt_SOS_conformational_activation(unit = "") "SOS conformational activation";
    parameter Real elmt_SOS_conformational_activation_elmt_n_SOS(unit "") = 1.0 "";
    parameter Real elmt_SOS_conformational_activation_elmt_KM_SOS_E(unit "") = 6086070.0 "";
    parameter Real elmt_SOS_conformational_activation_elmt_k_SOS_E(unit "") = 694.731 "";
    Real elmt_reactant1 "";
    Real elmt_reactant0 "";
    Real elmt_product3 "";
    Real elmt_product2 "";
    Real elmt_Akt_deactivation(unit = "") "Akt deactivation";
    parameter Real elmt_Akt_deactivation_elmt_kd_AKT(unit "") = 0.005 "";
    Real elmt_product34 "";
    Real elmt_reactant33 "";
    Real elmt_IGFR_active_degradation(unit = "") "IGFR active degradation";
    Real elmt_reactant63 "";
    Real elmt_P90_activationBy_ERK(unit = "") "P90 activation by ERK";
    Real elmt_product73 "";
    Real elmt_product72 "";
    Real elmt_reactant70 "";
    Real elmt_reactant71 "";
    Real elmt_PI3KCA_activationBy_EGF(unit = "") "PI3KCA activation by EGF";
    parameter Real elmt_PI3KCA_activationBy_EGF_elmt_k_PI3K_EGF1R(unit "") = 10.6737 "";
    parameter Real elmt_PI3KCA_activationBy_EGF_elmt_n_PI3K_E(unit "") = 1.0 "";
    parameter Real elmt_PI3KCA_activationBy_EGF_elmt_KM_PI3K_EGF1R(unit "") = 184912.0 "";
    Real elmt_reactant25 "";
    Real elmt_product27 "";
    Real elmt_reactant26 "";
    Real elmt_product28 "";
    Real elmt_PI3KCA_activationBy_kRas(unit = "") "PI3KCA activation by kRas";
    parameter Real elmt_PI3KCA_activationBy_kRas_elmt_k_PI3K_Ras(unit "") = 0.0771067 "";
    parameter Real elmt_PI3KCA_activationBy_kRas_elmt_n_PI3K_Ras(unit "") = 1.0 "";
    parameter Real elmt_PI3KCA_activationBy_kRas_elmt_KM_PI3K_Ras(unit "") = 272056.0 "";
    Real elmt_product41 "";
    Real elmt_reactant40 "";
    Real elmt_product42 "";
    Real elmt_reactant39 "";
    Real elmt_Raf_deactivationBy_Akt(unit = "") "Raf deactivation by Akt";
    parameter Real elmt_Raf_deactivationBy_Akt_elmt_n_Raf_AKT(unit "") = 1.0 "";
    parameter Real elmt_Raf_deactivationBy_Akt_elmt_KM_Raf_AKT(unit "") = 119355.0 "";
    parameter Real elmt_Raf_deactivationBy_Akt_elmt_k_Raf_AKT(unit "") = 15.1212 "";
    Real elmt_reactant51 "";
    Real elmt_reactant52 "";
    Real elmt_product54 "";
    Real elmt_product53 "";
    Real elmt_Mek_deactivation(unit = "") "Mek deactivation by PP2A";
    parameter Real elmt_Mek_deactivation_elmt_n_MekActivePP2A(unit "") = 1.0 "";
    parameter Real elmt_Mek_deactivation_elmt_k_MekActivePP2A(unit "") = 2.83243 "";
    parameter Real elmt_Mek_deactivation_elmt_KM_MekActivePP2A(unit "") = 518753.0 "";
    Real elmt_product62 "";
    Real elmt_product61 "";
    Real elmt_reactant60 "";
    Real elmt_reactant59 "";
    Real elmt_SOS_deactivationBy_P90(unit = "") "SOS deactivation by P90";
    parameter Real elmt_SOS_deactivationBy_P90_elmt_k_D_SOS_P90Rsk(unit "") = 161197.0 "";
    parameter Real elmt_SOS_deactivationBy_P90_elmt_n_D_SOS(unit "") = 1.0 "";
    parameter Real elmt_SOS_deactivationBy_P90_elmt_KM_D_SOS_P90Rsk(unit "") = 896896.0 "";
    Real elmt_reactant14 "";
    Real elmt_product16 "";
    Real elmt_product15 "";
    Real elmt_reactant13 "";
    Real elmt_PI3KCA_activationBy_IGF1R(unit = "") "PI3KCA activation by IGF1R";
    parameter Real elmt_PI3KCA_activationBy_IGF1R_elmt_k_PI3K_IGF1R(unit "") = 10.6737 "";
    parameter Real elmt_PI3KCA_activationBy_IGF1R_elmt_KM_PI3K_IGF1R(unit "") = 184912.0 "";
    parameter Real elmt_PI3KCA_activationBy_IGF1R_elmt_n_PI3K_I(unit "") = 1.0 "";
    Real elmt_product23 "";
    Real elmt_product24 "";
    Real elmt_reactant21 "";
    Real elmt_reactant22 "";
    Real elmt_kRas_Activation(unit = "") "kRas Activation";
    parameter Real elmt_kRas_Activation_elmt_n_Ras_SOS(unit "") = 1.0 "";
    parameter Real elmt_kRas_Activation_elmt_KM_Ras_SOS(unit "") = 35954.3 "";
    parameter Real elmt_kRas_Activation_elmt_k_Ras_SOS(unit "") = 32.344 "";
    Real elmt_reactant4 "";
    Real elmt_product7 "";
    Real elmt_product6 "";
    Real elmt_reactant5 "";
    Real elmt_Akt_activationBy_PI3KCA(unit = "") "Akt activation by PI3KCA";
    parameter Real elmt_Akt_activationBy_PI3KCA_elmt_KM_AKT_PI3K(unit "") = 653951.0 "";
    parameter Real elmt_Akt_activationBy_PI3KCA_elmt_n_AKT_PI3K(unit "") = 1.0 "";
    parameter Real elmt_Akt_activationBy_PI3KCA_elmt_k_AKT_PI3K(unit "") = 0.0566279 "";
    Real elmt_reactant30 "";
    Real elmt_reactant29 "";
    Real elmt_product32 "";
    Real elmt_product31 "";
    Real elmt_ERK_deactivationBy_PP2A(unit = "") "ERK deactivation by PP2A";
    parameter Real elmt_ERK_deactivationBy_PP2A_elmt_n_ERKactive_PP2A(unit "") = 1.0 "";
    parameter Real elmt_ERK_deactivationBy_PP2A_elmt_k_ERKactive_PP2A(unit "") = 8.8912 "";
    parameter Real elmt_ERK_deactivationBy_PP2A_elmt_KM_ERKactive_PP2A(unit "") = 3496490.0 "";
    Real elmt_reactant36 "";
    Real elmt_product38 "";
    Real elmt_product37 "";
    Real elmt_reactant35 "";
    Real elmt_Raf_activationBy_kRas(unit = "") "Raf activation by kRas";
    parameter Real elmt_Raf_activationBy_kRas_elmt_k_Raf_RasActive(unit "") = 0.884096 "";
    parameter Real elmt_Raf_activationBy_kRas_elmt_KM_Raf_RasActive(unit "") = 62464.6 "";
    parameter Real elmt_Raf_activationBy_kRas_elmt_n_Raf_RasActive(unit "") = 1.0 "";
    Real elmt_product45 "";
    Real elmt_product46 "";
    Real elmt_reactant43 "";
    Real elmt_reactant44 "";
    Real elmt_EGFR_degradation(unit = "") "EGFR degradation";
    Real elmt_reactant8 "";
    Real elmt_Ras_deactivation(unit = "") "Ras deactivation by RasGab";
    parameter Real elmt_Ras_deactivation_elmt_k_RasActiveRasGap(unit "") = 1509.36 "";
    parameter Real elmt_Ras_deactivation_elmt_n_RasActiveRasGap(unit "") = 1.0 "";
    parameter Real elmt_Ras_deactivation_elmt_KM_RasActiveRasGap(unit "") = 1432410.0 "";
    Real elmt_product58 "";
    Real elmt_product57 "";
    Real elmt_reactant55 "";
    Real elmt_reactant56 "";
    Real elmt_SOS_activationBy_IGF(unit = "") "SOS activation by IGF";
    parameter Real elmt_SOS_activationBy_IGF_elmt_k_A_SOS_I(unit "") = 500.0 "";
    parameter Real elmt_SOS_activationBy_IGF_elmt_n_A_SOS_I(unit "") = 1.0 "";
    parameter Real elmt_SOS_activationBy_IGF_elmt_KM_A_SOS_I(unit "") = 100000.0 "";
    Real elmt_reactant18 "";
    Real elmt_product20 "";
    Real elmt_reactant17 "";
    Real elmt_product19 "";
    Real elmt_P90_deactivation(unit = "") "P90 deactivation";
    parameter Real elmt_P90_deactivation_elmt_kd_P90Rsk(unit "") = 0.005 "";
    Real elmt_reactant74 "";
    Real elmt_product75 "";
    Real elmt_ERK_activationBy_Mek(unit = "") "ERK activation by Mek";
    parameter Real elmt_ERK_activationBy_Mek_elmt_KM_ERK_MekActive(unit "") = 1007340.0 "";
    parameter Real elmt_ERK_activationBy_Mek_elmt_k_ERK_MekActive(unit "") = 9.85367 "";
    Real elmt_product12 "";
    Real elmt_product11 "";
    Real elmt_reactant9 "";
    Real elmt_reactant10 "";
    Real elmt_Mek_activationBy_Raf(unit = "") "Mek activation by Raf";
    parameter Real elmt_Mek_activationBy_Raf_elmt_KM_MekPP2A(unit "") = 4768350.0 "";
    parameter Real elmt_Mek_activationBy_Raf_elmt_k_Mek_PP2A(unit "") = 185.759 "";
    parameter Real elmt_Mek_activationBy_Raf_elmt_n_Mek_PP2A(unit "") = 1.0 "";
    Real elmt_product50 "";
    Real elmt_reactant47 "";
    Real elmt_product49 "";
    Real elmt_reactant48 "";
    Real elmt_PI3KCA_deactivation(unit = "") "PI3KCA deactivation";
    Real elmt_reactant64 "";
    Real elmt_product65 "";


    initial equation
        elmt_product73 = 1.0;
        elmt_reactant40 = 1.0;
        elmt_product72 = 1.0;
        elmt_product34 = 1.0;
        elmt_product32 = 1.0;
        elmt_product31 = 1.0;
        elmt_product75 = 1.0;
        elmt_reactant47 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_reactant43 = 1.0;
        elmt_reactant44 = 1.0;
        elmt_product27 = 1.0;
        elmt_reactant9 = 1.0;
        elmt_product69 = 1.0;
        elmt_product68 = 1.0;
        elmt_product24 = 1.0;
        elmt_product28 = 1.0;
        elmt_product41 = 1.0;
        elmt_reactant51 = 1.0;
        elmt_reactant52 = 1.0;
        elmt_product45 = 1.0;
        elmt_product42 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant59 = 1.0;
        elmt_reactant17 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant55 = 1.0;
        elmt_reactant56 = 1.0;
        elmt_reactant13 = 1.0;
        elmt_product38 = 1.0;
        elmt_product37 = 1.0;
        elmt_reactant63 = 1.0;
        elmt_product50 = 1.0;
        elmt_reactant64 = 1.0;
        elmt_product12 = 1.0;
        elmt_product11 = 1.0;
        elmt_product54 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant60 = 1.0;
        elmt_reactant25 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant66 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_reactant67 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_product49 = 1.0;
        elmt_product46 = 1.0;
        elmt_reactant1 = 1.0;
        elmt_product62 = 1.0;
        elmt_product61 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant30 = 1.0;
        elmt_reactant74 = 1.0;
        elmt_product6 = 1.0;
        elmt_product23 = 1.0;
        elmt_reactant5 = 1.0;
        elmt_reactant70 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product65 = 1.0;
        elmt_reactant71 = 1.0;
        elmt_product20 = 1.0;
        elmt_reactant36 = 1.0;
        elmt_reactant39 = 1.0;
        elmt_reactant33 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product3 = 1.0;
        elmt_product2 = 1.0;
        elmt_reactant35 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_product16 = 1.0;
        elmt_product15 = 1.0;
        elmt_product58 = 1.0;
        elmt_product57 = 1.0;
        elmt_product19 = 1.0;


    equation
        elmt_Raf_deactivation = ((elmt_RafPP * elmt_Raf_deactivation_elmt_k_RasActive_RafPP * Functions.pow(elmt_Raf_active, elmt_Raf_deactivation_elmt_n_RasActive_RafPP)) / (Functions.pow(elmt_Raf_deactivation_elmt_KM_RasActive_RafPP, elmt_Raf_deactivation_elmt_n_RasActive_RafPP) + Functions.pow(elmt_Raf_active, elmt_Raf_deactivation_elmt_n_RasActive_RafPP)));
        elmt_SOS_conformational_activation = ((elmt_SOS_conformational_activation_elmt_k_SOS_E * elmt_EGFR_active * Functions.pow(elmt_D_SOS, elmt_SOS_conformational_activation_elmt_n_SOS)) / (Functions.pow(elmt_SOS_conformational_activation_elmt_KM_SOS_E, elmt_SOS_conformational_activation_elmt_n_SOS) + Functions.pow(elmt_D_SOS, elmt_SOS_conformational_activation_elmt_n_SOS)));
        elmt_Akt_deactivation = (elmt_Akt_deactivation_elmt_kd_AKT * elmt_AKT_active);
        elmt_IGFR_active_degradation = (elmt_gamma_IGFR * elmt_IGFR_active);
        elmt_P90_activationBy_ERK = ((elmt_ERK_active * elmt_k_P90Rsk_ERKActive * elmt_P90RskInactive) / (elmt_KM_P90Rsk_ERKActive + elmt_P90RskInactive));
        elmt_PI3KCA_activationBy_EGF = ((elmt_EGFR_active * elmt_PI3KCA_activationBy_EGF_elmt_k_PI3K_EGF1R * elmt_EGFR_active * Functions.pow(elmt_PI3KCA, elmt_PI3KCA_activationBy_EGF_elmt_n_PI3K_E)) / (Functions.pow(elmt_PI3KCA_activationBy_EGF_elmt_KM_PI3K_EGF1R, elmt_PI3KCA_activationBy_EGF_elmt_n_PI3K_E) + Functions.pow(elmt_PI3KCA, elmt_PI3KCA_activationBy_EGF_elmt_n_PI3K_E)));
        elmt_PI3KCA_activationBy_kRas = ((elmt_Ras_active * elmt_PI3KCA_activationBy_kRas_elmt_k_PI3K_Ras * Functions.pow(elmt_PI3KCA, elmt_PI3KCA_activationBy_kRas_elmt_n_PI3K_Ras)) / (Functions.pow(elmt_PI3KCA_activationBy_kRas_elmt_KM_PI3K_Ras, elmt_PI3KCA_activationBy_kRas_elmt_n_PI3K_Ras) + Functions.pow(elmt_PI3KCA, elmt_PI3KCA_activationBy_kRas_elmt_n_PI3K_Ras)));
        elmt_Raf_deactivationBy_Akt = ((elmt_AKT_active * elmt_Raf_deactivationBy_Akt_elmt_k_Raf_AKT * Functions.pow(elmt_Raf_active, elmt_Raf_deactivationBy_Akt_elmt_n_Raf_AKT)) / (Functions.pow(elmt_Raf_deactivationBy_Akt_elmt_KM_Raf_AKT, elmt_Raf_deactivationBy_Akt_elmt_n_Raf_AKT) + Functions.pow(elmt_Raf_active, elmt_Raf_deactivationBy_Akt_elmt_n_Raf_AKT)));
        elmt_Mek_deactivation = ((elmt_PP2A * elmt_Mek_deactivation_elmt_k_MekActivePP2A * Functions.pow(elmt_Mek_active, elmt_Mek_deactivation_elmt_n_MekActivePP2A)) / (Functions.pow(elmt_Mek_deactivation_elmt_KM_MekActivePP2A, elmt_Mek_deactivation_elmt_n_MekActivePP2A) + Functions.pow(elmt_Mek_active, elmt_Mek_deactivation_elmt_n_MekActivePP2A)));
        elmt_SOS_deactivationBy_P90 = ((elmt_P90Rsk_Active * elmt_SOS_deactivationBy_P90_elmt_k_D_SOS_P90Rsk * Functions.pow(elmt_A_SOS, elmt_SOS_deactivationBy_P90_elmt_n_D_SOS)) / (Functions.pow(elmt_SOS_deactivationBy_P90_elmt_KM_D_SOS_P90Rsk, elmt_SOS_deactivationBy_P90_elmt_n_D_SOS) + Functions.pow(elmt_A_SOS, elmt_SOS_deactivationBy_P90_elmt_n_D_SOS)));
        elmt_PI3KCA_activationBy_IGF1R = ((elmt_IGFR_active * elmt_PI3KCA_activationBy_IGF1R_elmt_k_PI3K_IGF1R * Functions.pow(elmt_PI3KCA, elmt_PI3KCA_activationBy_IGF1R_elmt_n_PI3K_I)) / (Functions.pow(elmt_PI3KCA_activationBy_IGF1R_elmt_KM_PI3K_IGF1R, elmt_PI3KCA_activationBy_IGF1R_elmt_n_PI3K_I) + Functions.pow(elmt_PI3KCA, elmt_PI3KCA_activationBy_IGF1R_elmt_n_PI3K_I)));
        elmt_kRas_Activation = ((elmt_A_SOS * elmt_kRas_Activation_elmt_k_Ras_SOS * Functions.pow(elmt_Ras, elmt_kRas_Activation_elmt_n_Ras_SOS)) / (Functions.pow(elmt_kRas_Activation_elmt_KM_Ras_SOS, elmt_kRas_Activation_elmt_n_Ras_SOS) + Functions.pow(elmt_Ras, elmt_kRas_Activation_elmt_n_Ras_SOS)));
        elmt_Akt_activationBy_PI3KCA = ((elmt_PI3KCA_active * elmt_Akt_activationBy_PI3KCA_elmt_k_AKT_PI3K * Functions.pow(elmt_AKT, elmt_Akt_activationBy_PI3KCA_elmt_n_AKT_PI3K)) / (Functions.pow(elmt_Akt_activationBy_PI3KCA_elmt_KM_AKT_PI3K, elmt_Akt_activationBy_PI3KCA_elmt_n_AKT_PI3K) + Functions.pow(elmt_AKT, elmt_Akt_activationBy_PI3KCA_elmt_n_AKT_PI3K)));
        elmt_ERK_deactivationBy_PP2A = ((elmt_PP2A * elmt_ERK_deactivationBy_PP2A_elmt_k_ERKactive_PP2A * Functions.pow(elmt_ERK_active, elmt_ERK_deactivationBy_PP2A_elmt_n_ERKactive_PP2A)) / (Functions.pow(elmt_ERK_deactivationBy_PP2A_elmt_KM_ERKactive_PP2A, elmt_ERK_deactivationBy_PP2A_elmt_n_ERKactive_PP2A) + Functions.pow(elmt_ERK_active, elmt_ERK_deactivationBy_PP2A_elmt_n_ERKactive_PP2A)));
        elmt_Raf_activationBy_kRas = ((elmt_Ras_active * elmt_Raf_activationBy_kRas_elmt_k_Raf_RasActive * Functions.pow(elmt_Raf, elmt_Raf_activationBy_kRas_elmt_n_Raf_RasActive)) / (elmt_Raf_activationBy_kRas_elmt_KM_Raf_RasActive + Functions.pow(elmt_Raf, elmt_Raf_activationBy_kRas_elmt_n_Raf_RasActive)));
        elmt_EGFR_degradation = (elmt_gamma_EGFR * elmt_EGFR_active);
        elmt_Ras_deactivation = ((elmt_RasGapActive * elmt_Ras_deactivation_elmt_k_RasActiveRasGap * Functions.pow(elmt_Ras_active, elmt_Ras_deactivation_elmt_n_RasActiveRasGap)) / (Functions.pow(elmt_Ras_deactivation_elmt_KM_RasActiveRasGap, elmt_Ras_deactivation_elmt_n_RasActiveRasGap) + Functions.pow(elmt_Ras_active, elmt_Ras_deactivation_elmt_n_RasActiveRasGap)));
        elmt_SOS_activationBy_IGF = ((elmt_IGFR_active * elmt_SOS_activationBy_IGF_elmt_k_A_SOS_I * Functions.pow(elmt_D_SOS, elmt_SOS_activationBy_IGF_elmt_n_A_SOS_I)) / (Functions.pow(elmt_SOS_activationBy_IGF_elmt_KM_A_SOS_I, elmt_SOS_activationBy_IGF_elmt_n_A_SOS_I) + Functions.pow(elmt_D_SOS, elmt_SOS_activationBy_IGF_elmt_n_A_SOS_I)));
        elmt_P90_deactivation = (elmt_P90_deactivation_elmt_kd_P90Rsk * elmt_P90Rsk_Active);
        elmt_ERK_activationBy_Mek = ((elmt_Mek_active * elmt_ERK_activationBy_Mek_elmt_k_ERK_MekActive * elmt_ERK) / (elmt_ERK_activationBy_Mek_elmt_KM_ERK_MekActive + elmt_ERK));
        elmt_Mek_activationBy_Raf = ((elmt_Raf_active * elmt_Mek_activationBy_Raf_elmt_k_Mek_PP2A * Functions.pow(elmt_Mek, elmt_Mek_activationBy_Raf_elmt_n_Mek_PP2A)) / (Functions.pow(elmt_Mek_activationBy_Raf_elmt_KM_MekPP2A, elmt_Mek_activationBy_Raf_elmt_n_Mek_PP2A) + Functions.pow(elmt_Mek, elmt_Mek_activationBy_Raf_elmt_n_Mek_PP2A)));
        elmt_PI3KCA_deactivation = (elmt_kd_PI3K_a * elmt_PI3KCA_active);
        der(elmt_product73) = 0;
        der(elmt_reactant40) = 0;
        der(elmt_product72) = 0;
        der(elmt_product34) = 0;
        der(elmt_product32) = 0;
        der(elmt_product31) = 0;
        der(elmt_product75) = 0;
        der(elmt_reactant47) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_reactant43) = 0;
        der(elmt_reactant44) = 0;
        der(elmt_product27) = 0;
        der(elmt_reactant9) = 0;
        der(elmt_product69) = 0;
        der(elmt_product68) = 0;
        der(elmt_product24) = 0;
        der(elmt_product28) = 0;
        der(elmt_product41) = 0;
        der(elmt_reactant51) = 0;
        der(elmt_reactant52) = 0;
        der(elmt_product45) = 0;
        der(elmt_product42) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant59) = 0;
        der(elmt_reactant17) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant55) = 0;
        der(elmt_reactant56) = 0;
        der(elmt_reactant13) = 0;
        der(elmt_product38) = 0;
        der(elmt_product37) = 0;
        der(elmt_reactant63) = 0;
        der(elmt_product50) = 0;
        der(elmt_reactant64) = 0;
        der(elmt_product12) = 0;
        der(elmt_product11) = 0;
        der(elmt_product54) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant60) = 0;
        der(elmt_reactant25) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant66) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_reactant67) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_product49) = 0;
        der(elmt_product46) = 0;
        der(elmt_reactant1) = 0;
        der(elmt_product62) = 0;
        der(elmt_product61) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant30) = 0;
        der(elmt_reactant74) = 0;
        der(elmt_product6) = 0;
        der(elmt_product23) = 0;
        der(elmt_reactant5) = 0;
        der(elmt_reactant70) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product65) = 0;
        der(elmt_reactant71) = 0;
        der(elmt_product20) = 0;
        der(elmt_reactant36) = 0;
        der(elmt_reactant39) = 0;
        der(elmt_reactant33) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product3) = 0;
        der(elmt_product2) = 0;
        der(elmt_reactant35) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_product16) = 0;
        der(elmt_product15) = 0;
        der(elmt_product58) = 0;
        der(elmt_product57) = 0;
        der(elmt_product19) = 0;

end Reactions;
