within BIOMD050;
class Reactions

    input Real elmt_DFG;
    input Real elmt_Gly;
    input Real elmt__3DG;
    input Real elmt__1DG;
    input Real elmt_E2;
    input Real elmt_Glu;
    input Real elmt_Cn;
    input Real elmt_E1;
    input Real elmt_Man;

    Real elmt_v13(unit = "") "";
    parameter Real elmt_v13_elmt_k13(unit "") = 0.0022 "";
    Real elmt_product30 "";
    Real elmt_reactant29 "";
    Real elmt_v12(unit = "") "";
    parameter Real elmt_v12_elmt_k12(unit "") = 8.0E-4 "";
    Real elmt_reactant27 "";
    Real elmt_product28 "";
    Real elmt_v9(unit = "") "";
    parameter Real elmt_v9_elmt_k9(unit "") = 1.9085 "";
    Real elmt_reactant19 "";
    Real elmt_product20 "";
    Real elmt_v11(unit = "") "";
    parameter Real elmt_v11_elmt_k11(unit "") = 0.1131 "";
    Real elmt_product26 "";
    Real elmt_product25 "";
    Real elmt_reactant24 "";
    Real elmt_v10(unit = "") "";
    parameter Real elmt_v10_elmt_k10(unit "") = 0.0707 "";
    Real elmt_product23 "";
    Real elmt_product22 "";
    Real elmt_reactant21 "";
    Real elmt_v7(unit = "") "";
    parameter Real elmt_v7_elmt_k7(unit "") = 0.2125 "";
    Real elmt_reactant14 "";
    Real elmt_product16 "";
    Real elmt_product15 "";
    Real elmt_v8(unit = "") "";
    parameter Real elmt_v8_elmt_k8(unit "") = 0.0 "";
    Real elmt_reactant17 "";
    Real elmt_product18 "";
    Real elmt_v5(unit = "") "";
    parameter Real elmt_v5_elmt_k5(unit "") = 0.0907 "";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_v6(unit = "") "";
    parameter Real elmt_v6_elmt_k6(unit "") = 0.0274 "";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_v16(unit = "") "";
    parameter Real elmt_v16_elmt_k16(unit "") = 0.0134 "";
    Real elmt_product40 "";
    Real elmt_reactant38 "";
    Real elmt_product39 "";
    Real elmt_v15(unit = "") "";
    parameter Real elmt_v15_elmt_k15(unit "") = 0.0159 "";
    Real elmt_product37 "";
    Real elmt_product36 "";
    Real elmt_product35 "";
    Real elmt_reactant34 "";
    Real elmt_v14(unit = "") "";
    parameter Real elmt_v14_elmt_k14(unit "") = 0.0034 "";
    Real elmt_reactant31 "";
    Real elmt_product33 "";
    Real elmt_reactant32 "";
    Real elmt_v3(unit = "") "";
    parameter Real elmt_v3_elmt_k3(unit "") = 0.0155 "";
    Real elmt_reactant4 "";
    Real elmt_product6 "";
    Real elmt_product5 "";
    Real elmt_v4(unit = "") "";
    parameter Real elmt_v4_elmt_k4(unit "") = 0.0794 "";
    Real elmt_product9 "";
    Real elmt_product8 "";
    Real elmt_reactant7 "";
    Real elmt_v1(unit = "") "";
    parameter Real elmt_v1_elmt_k1(unit "") = 0.0057 "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_v2(unit = "") "";
    parameter Real elmt_v2_elmt_k2(unit "") = 0.0156 "";
    Real elmt_reactant2 "";
    Real elmt_product3 "";


    initial equation
        elmt_product30 = 1.0;
        elmt_product11 = 1.0;
        elmt_product33 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product26 = 1.0;
        elmt_product25 = 1.0;
        elmt_product28 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product40 = 1.0;
        elmt_product8 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_reactant31 = 1.0;
        elmt_product6 = 1.0;
        elmt_product23 = 1.0;
        elmt_product22 = 1.0;
        elmt_product20 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant38 = 1.0;
        elmt_reactant17 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant32 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_reactant34 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_product16 = 1.0;
        elmt_product15 = 1.0;
        elmt_product37 = 1.0;
        elmt_product36 = 1.0;
        elmt_product13 = 1.0;
        elmt_product35 = 1.0;
        elmt_product18 = 1.0;
        elmt_product39 = 1.0;


    equation
        elmt_v13 = (elmt_v13_elmt_k13 * elmt_Glu);
        elmt_v12 = (elmt_v12_elmt_k12 * elmt_Man);
        elmt_v9 = (elmt_v9_elmt_k9 * elmt__1DG);
        elmt_v11 = (elmt_v11_elmt_k11 * elmt_E1);
        elmt_v10 = (elmt_v10_elmt_k10 * elmt_E1);
        elmt_v7 = (elmt_v7_elmt_k7 * elmt_E2);
        elmt_v8 = (elmt_v8_elmt_k8 * elmt__1DG);
        elmt_v5 = (elmt_v5_elmt_k5 * elmt__3DG);
        elmt_v6 = (elmt_v6_elmt_k6 * elmt__3DG);
        elmt_v16 = (elmt_v16_elmt_k16 * elmt_E2);
        elmt_v15 = (elmt_v15_elmt_k15 * elmt_Cn);
        elmt_v14 = (elmt_v14_elmt_k14 * elmt_Cn * elmt_Gly);
        elmt_v3 = (elmt_v3_elmt_k3 * elmt_DFG);
        elmt_v4 = (elmt_v4_elmt_k4 * elmt_E1);
        elmt_v1 = (elmt_v1_elmt_k1 * elmt_DFG);
        elmt_v2 = (elmt_v2_elmt_k2 * elmt_DFG);
        der(elmt_product30) = 0;
        der(elmt_product11) = 0;
        der(elmt_product33) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product26) = 0;
        der(elmt_product25) = 0;
        der(elmt_product28) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product40) = 0;
        der(elmt_product8) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_reactant31) = 0;
        der(elmt_product6) = 0;
        der(elmt_product23) = 0;
        der(elmt_product22) = 0;
        der(elmt_product20) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant38) = 0;
        der(elmt_reactant17) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_reactant34) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_product16) = 0;
        der(elmt_product15) = 0;
        der(elmt_product37) = 0;
        der(elmt_product36) = 0;
        der(elmt_product13) = 0;
        der(elmt_product35) = 0;
        der(elmt_product18) = 0;
        der(elmt_product39) = 0;

end Reactions;
