within BIOMD172;
model Pritchard2002_glycolysis "Pritchard2002_glycolysis" annotation(Documentation(info="<annotation>
  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
  </rdf:RDF>
</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_cell elmt_cell;
    Class_elmt_ext elmt_ext;

    equation
        Reacs.elmt_GAP = elmt_cell.elmt_GAP;
        Reacs.elmt_NAD = elmt_cell.elmt_NAD;
        Reacs.elmt_GLCi = elmt_cell.elmt_GLCi;
        Reacs.elmt_F6P = elmt_cell.elmt_F6P;
        Reacs.elmt_ATP = elmt_cell.elmt_ATP;
        Reacs.elmt_EtOH = elmt_cell.elmt_EtOH;
        Reacs.elmt_Glycerol = elmt_cell.elmt_Glycerol;
        Reacs.elmt_PEP = elmt_cell.elmt_PEP;
        Reacs.elmt_BPG = elmt_cell.elmt_BPG;
        Reacs.elmt_AcAld = elmt_cell.elmt_AcAld;
        Reacs.elmt_F16bP = elmt_cell.elmt_F16bP;
        Reacs.elmt_cell = elmt_cell.elmt_cell;
        Reacs.elmt_P2G = elmt_cell.elmt_P2G;
        Reacs.elmt_AMP = elmt_cell.elmt_AMP;
        Reacs.elmt_P3G = elmt_cell.elmt_P3G;
        Reacs.elmt_G6P = elmt_cell.elmt_G6P;
        Reacs.elmt_DHAP = elmt_cell.elmt_DHAP;
        Reacs.elmt_GLCo = elmt_ext.elmt_GLCo;
        Reacs.elmt_ADP = elmt_cell.elmt_ADP;
        Reacs.elmt_F26bP = elmt_cell.elmt_F26bP;
        Reacs.elmt_PYR = elmt_cell.elmt_PYR;
        Reacs.elmt_NADH = elmt_cell.elmt_NADH;
        elmt_cell.elmt_reactant40 = Reacs.elmt_reactant40;
        elmt_cell.elmt_HK = Reacs.elmt_HK;
        elmt_cell.elmt_PGM = Reacs.elmt_PGM;
        elmt_cell.elmt_reactant42 = Reacs.elmt_reactant42;
        elmt_cell.elmt_product34 = Reacs.elmt_product34;
        elmt_cell.elmt_PGK = Reacs.elmt_PGK;
        elmt_cell.elmt_product32 = Reacs.elmt_product32;
        elmt_cell.elmt_PGI = Reacs.elmt_PGI;
        elmt_cell.elmt_product31 = Reacs.elmt_product31;
        elmt_cell.elmt_reactant49 = Reacs.elmt_reactant49;
        elmt_cell.elmt_reactant45 = Reacs.elmt_reactant45;
        elmt_cell.elmt_reactant46 = Reacs.elmt_reactant46;
        elmt_cell.elmt_ENO = Reacs.elmt_ENO;
        elmt_cell.elmt_HXT = Reacs.elmt_HXT;
        elmt_cell.elmt_PDC = Reacs.elmt_PDC;
        elmt_cell.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_cell.elmt_Glycogen_Branch = Reacs.elmt_Glycogen_Branch;
        elmt_cell.elmt_product26 = Reacs.elmt_product26;
        elmt_cell.elmt_TPI = Reacs.elmt_TPI;
        elmt_cell.elmt_product24 = Reacs.elmt_product24;
        elmt_cell.elmt_product28 = Reacs.elmt_product28;
        elmt_cell.elmt_reactant50 = Reacs.elmt_reactant50;
        elmt_cell.elmt_product41 = Reacs.elmt_product41;
        elmt_cell.elmt_reactant53 = Reacs.elmt_reactant53;
        elmt_cell.elmt_ATPase = Reacs.elmt_ATPase;
        elmt_cell.elmt_product44 = Reacs.elmt_product44;
        elmt_cell.elmt_product43 = Reacs.elmt_product43;
        elmt_cell.elmt_reactant58 = Reacs.elmt_reactant58;
        elmt_cell.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_cell.elmt_Trehalose_Branch = Reacs.elmt_Trehalose_Branch;
        elmt_cell.elmt_reactant17 = Reacs.elmt_reactant17;
        elmt_cell.elmt_reactant54 = Reacs.elmt_reactant54;
        elmt_cell.elmt_AK = Reacs.elmt_AK;
        elmt_cell.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_cell.elmt_reactant57 = Reacs.elmt_reactant57;
        elmt_cell.elmt_PYK = Reacs.elmt_PYK;
        elmt_cell.elmt_product38 = Reacs.elmt_product38;
        elmt_cell.elmt_G3PDH = Reacs.elmt_G3PDH;
        elmt_cell.elmt_product39 = Reacs.elmt_product39;
        elmt_cell.elmt_product51 = Reacs.elmt_product51;
        elmt_cell.elmt_Succinate_Branch = Reacs.elmt_Succinate_Branch;
        elmt_cell.elmt_product11 = Reacs.elmt_product11;
        elmt_cell.elmt_product55 = Reacs.elmt_product55;
        elmt_cell.elmt_product10 = Reacs.elmt_product10;
        elmt_cell.elmt_reactant25 = Reacs.elmt_reactant25;
        elmt_cell.elmt_reactant27 = Reacs.elmt_reactant27;
        elmt_cell.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_cell.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_cell.elmt_ALD = Reacs.elmt_ALD;
        elmt_cell.elmt_ADH = Reacs.elmt_ADH;
        elmt_cell.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_cell.elmt_product47 = Reacs.elmt_product47;
        elmt_cell.elmt_reactant2 = Reacs.elmt_reactant2;
        elmt_cell.elmt_PFK = Reacs.elmt_PFK;
        elmt_cell.elmt_product7 = Reacs.elmt_product7;
        elmt_cell.elmt_reactant30 = Reacs.elmt_reactant30;
        elmt_cell.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_cell.elmt_product23 = Reacs.elmt_product23;
        elmt_cell.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_cell.elmt_GAPDH = Reacs.elmt_GAPDH;
        elmt_cell.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_cell.elmt_product20 = Reacs.elmt_product20;
        elmt_cell.elmt_reactant36 = Reacs.elmt_reactant36;
        elmt_cell.elmt_product1 = Reacs.elmt_product1;
        elmt_cell.elmt_product5 = Reacs.elmt_product5;
        elmt_cell.elmt_product4 = Reacs.elmt_product4;
        elmt_cell.elmt_reactant33 = Reacs.elmt_reactant33;
        elmt_cell.elmt_reactant29 = Reacs.elmt_reactant29;
        elmt_cell.elmt_product16 = Reacs.elmt_product16;
        elmt_cell.elmt_product59 = Reacs.elmt_product59;
        elmt_cell.elmt_product14 = Reacs.elmt_product14;
        elmt_cell.elmt_product13 = Reacs.elmt_product13;
        elmt_cell.elmt_product19 = Reacs.elmt_product19;

end Pritchard2002_glycolysis;
