within BIOMD028;
model model_0000001 "Markevich2004_MAPK_phosphoRandomElementary" annotation(Documentation(info="<annotation>
      <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
      </rdf:RDF>
    </annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_cell elmt_cell;

    equation
        Reacs.elmt_MpY = elmt_cell.elmt_MpY;
        Reacs.elmt_MKP3 = elmt_cell.elmt_MKP3;
        Reacs.elmt_MEK = elmt_cell.elmt_MEK;
        Reacs.elmt_MpT = elmt_cell.elmt_MpT;
        Reacs.elmt_M_MEK_T = elmt_cell.elmt_M_MEK_T;
        Reacs.elmt_M_MEK_Y = elmt_cell.elmt_M_MEK_Y;
        Reacs.elmt_h5 = Params.elmt_h5;
        Reacs.elmt_h6 = Params.elmt_h6;
        Reacs.elmt_h3 = Params.elmt_h3;
        Reacs.elmt_h4 = Params.elmt_h4;
        Reacs.elmt_h1 = Params.elmt_h1;
        Reacs.elmt_h2 = Params.elmt_h2;
        Reacs.elmt_cell = elmt_cell.elmt_cell;
        Reacs.elmt_MpY_MKP3 = elmt_cell.elmt_MpY_MKP3;
        Reacs.elmt_Mpp = elmt_cell.elmt_Mpp;
        Reacs.elmt_M_MKP3_Y = elmt_cell.elmt_M_MKP3_Y;
        Reacs.elmt_M_MKP3_T = elmt_cell.elmt_M_MKP3_T;
        Reacs.elmt_MpY_MEK = elmt_cell.elmt_MpY_MEK;
        Reacs.elmt_k1 = Params.elmt_k1;
        Reacs.elmt_M = elmt_cell.elmt_M;
        Reacs.elmt_Mpp_MKP3 = elmt_cell.elmt_Mpp_MKP3;
        Reacs.elmt_MpT_MEK = elmt_cell.elmt_MpT_MEK;
        Reacs.elmt_k8 = Params.elmt_k8;
        Reacs.elmt_h_7 = Params.elmt_h_7;
        Reacs.elmt_h_6 = Params.elmt_h_6;
        Reacs.elmt_k_3 = Params.elmt_k_3;
        Reacs.elmt_k6 = Params.elmt_k6;
        Reacs.elmt_k7 = Params.elmt_k7;
        Reacs.elmt_h_4 = Params.elmt_h_4;
        Reacs.elmt_k_1 = Params.elmt_k_1;
        Reacs.elmt_h_3 = Params.elmt_h_3;
        Reacs.elmt_k4 = Params.elmt_k4;
        Reacs.elmt_k5 = Params.elmt_k5;
        Reacs.elmt_h_1 = Params.elmt_h_1;
        Reacs.elmt_k2 = Params.elmt_k2;
        Reacs.elmt_k3 = Params.elmt_k3;
        Reacs.elmt_h9 = Params.elmt_h9;
        Reacs.elmt_MpT_MKP3_Y = elmt_cell.elmt_MpT_MKP3_Y;
        Reacs.elmt_k_7 = Params.elmt_k_7;
        Reacs.elmt_h_9 = Params.elmt_h_9;
        Reacs.elmt_h7 = Params.elmt_h7;
        Reacs.elmt_k_5 = Params.elmt_k_5;
        Reacs.elmt_h8 = Params.elmt_h8;
        Reacs.elmt_MpT_MKP3_T = elmt_cell.elmt_MpT_MKP3_T;
        elmt_cell.elmt_product30 = Reacs.elmt_product30;
        elmt_cell.elmt_reactant42 = Reacs.elmt_reactant42;
        elmt_cell.elmt_product33 = Reacs.elmt_product33;
        elmt_cell.elmt_product31 = Reacs.elmt_product31;
        elmt_cell.elmt_reactant43 = Reacs.elmt_reactant43;
        elmt_cell.elmt_reactant45 = Reacs.elmt_reactant45;
        elmt_cell.elmt_reactant9 = Reacs.elmt_reactant9;
        elmt_cell.elmt_product26 = Reacs.elmt_product26;
        elmt_cell.elmt_product28 = Reacs.elmt_product28;
        elmt_cell.elmt_reaction_0000019 = Reacs.elmt_reaction_0000019;
        elmt_cell.elmt_product41 = Reacs.elmt_product41;
        elmt_cell.elmt_product40 = Reacs.elmt_product40;
        elmt_cell.elmt_reaction_0000017 = Reacs.elmt_reaction_0000017;
        elmt_cell.elmt_product44 = Reacs.elmt_product44;
        elmt_cell.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_cell.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_cell.elmt_reactant13 = Reacs.elmt_reactant13;
        elmt_cell.elmt_reaction_0000011 = Reacs.elmt_reaction_0000011;
        elmt_cell.elmt_product38 = Reacs.elmt_product38;
        elmt_cell.elmt_reaction_0000010 = Reacs.elmt_reaction_0000010;
        elmt_cell.elmt_product36 = Reacs.elmt_product36;
        elmt_cell.elmt_reaction_0000015 = Reacs.elmt_reaction_0000015;
        elmt_cell.elmt_reaction_0000014 = Reacs.elmt_reaction_0000014;
        elmt_cell.elmt_reaction_0000013 = Reacs.elmt_reaction_0000013;
        elmt_cell.elmt_reaction_0000012 = Reacs.elmt_reaction_0000012;
        elmt_cell.elmt_reaction_0000008 = Reacs.elmt_reaction_0000008;
        elmt_cell.elmt_reaction_0000007 = Reacs.elmt_reaction_0000007;
        elmt_cell.elmt_reaction_0000006 = Reacs.elmt_reaction_0000006;
        elmt_cell.elmt_reaction_0000005 = Reacs.elmt_reaction_0000005;
        elmt_cell.elmt_product11 = Reacs.elmt_product11;
        elmt_cell.elmt_product10 = Reacs.elmt_product10;
        elmt_cell.elmt_reaction_0000009 = Reacs.elmt_reaction_0000009;
        elmt_cell.elmt_reactant25 = Reacs.elmt_reactant25;
        elmt_cell.elmt_reactant27 = Reacs.elmt_reactant27;
        elmt_cell.elmt_reactant21 = Reacs.elmt_reactant21;
        elmt_cell.elmt_reactant24 = Reacs.elmt_reactant24;
        elmt_cell.elmt_reactant18 = Reacs.elmt_reactant18;
        elmt_cell.elmt_reactant19 = Reacs.elmt_reactant19;
        elmt_cell.elmt_product47 = Reacs.elmt_product47;
        elmt_cell.elmt_product46 = Reacs.elmt_product46;
        elmt_cell.elmt_reaction_0000004 = Reacs.elmt_reaction_0000004;
        elmt_cell.elmt_reaction_0000003 = Reacs.elmt_reaction_0000003;
        elmt_cell.elmt_reaction_0000002 = Reacs.elmt_reaction_0000002;
        elmt_cell.elmt_reaction_0000001 = Reacs.elmt_reaction_0000001;
        elmt_cell.elmt_product8 = Reacs.elmt_product8;
        elmt_cell.elmt_reactant1 = Reacs.elmt_reactant1;
        elmt_cell.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_cell.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_cell.elmt_product23 = Reacs.elmt_product23;
        elmt_cell.elmt_product22 = Reacs.elmt_product22;
        elmt_cell.elmt_reactant7 = Reacs.elmt_reactant7;
        elmt_cell.elmt_product20 = Reacs.elmt_product20;
        elmt_cell.elmt_reactant37 = Reacs.elmt_reactant37;
        elmt_cell.elmt_reactant39 = Reacs.elmt_reactant39;
        elmt_cell.elmt_product5 = Reacs.elmt_product5;
        elmt_cell.elmt_reactant32 = Reacs.elmt_reactant32;
        elmt_cell.elmt_product4 = Reacs.elmt_product4;
        elmt_cell.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_cell.elmt_reactant34 = Reacs.elmt_reactant34;
        elmt_cell.elmt_reactant35 = Reacs.elmt_reactant35;
        elmt_cell.elmt_product2 = Reacs.elmt_product2;
        elmt_cell.elmt_reactant29 = Reacs.elmt_reactant29;
        elmt_cell.elmt_product16 = Reacs.elmt_product16;
        elmt_cell.elmt_product14 = Reacs.elmt_product14;
        elmt_cell.elmt_product17 = Reacs.elmt_product17;

end model_0000001;
