within BIOMD513;
class Reactions

    input Real elmt_PEP_c;
    input Real elmt__3PGA_c;
    input Real elmt_Fru16BP_g;
    input Real elmt_AMP_g;
    input Real elmt__3PGA_g;
    input Real elmt_AMP_c;
    input Real elmt_Gly_e;
    input Real elmt_ATP_c;
    input Real elmt_Gly3P_c;
    input Real elmt_Glc6P_g;
    input Real elmt_ATP_g;
    input Real elmt_Gly3P_g;
    input Real elmt_DHAP_c;
    input Real elmt_ADP_c;
    input Real elmt_Pyr_c;
    input Real elmt_DHAP_g;
    input Real elmt_ADP_g;
    input Real elmt_NADH_g;
    input Real elmt__13BPGA_g;
    input Real elmt_Glc_e;
    input Real elmt_Glc_c;
    input Real elmt_Fru6P_g;
    input Real elmt_GA3P_g;
    input Real elmt_Glc_g;
    input Real elmt__2PGA_c;
    input Real elmt_NAD_g;

    Real elmt_ENO_c(unit = "") "ENO_c";
    parameter Real elmt_ENO_c_elmt_ENO_c_Km2PGA(unit "") = 0.054 "";
    parameter Real elmt_ENO_c_elmt_ENO_c_KmPEP(unit "") = 0.24 "";
    parameter Real elmt_ENO_c_elmt_ENO_c_Keq(unit "") = 4.17 "";
    parameter Real elmt_ENO_c_elmt_ENO_c_Vmax(unit "") = 598.0 "";
    Real elmt_product22 "";
    Real elmt_reactant21 "";
    Real elmt_PGAM_c(unit = "") "PGAM_c";
    parameter Real elmt_PGAM_c_elmt_PGAM_c_Km2PGA(unit "") = 0.16 "";
    parameter Real elmt_PGAM_c_elmt_PGAM_c_Km3PGA(unit "") = 0.15 "";
    parameter Real elmt_PGAM_c_elmt_PGAM_c_Vmax(unit "") = 225.0 "";
    parameter Real elmt_PGAM_c_elmt_PGAM_c_Keq(unit "") = 0.17 "";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_GAPDH_g(unit = "") "GAPDH_g";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_Vmax(unit "") = 720.9 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_KmNAD(unit "") = 0.45 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_KmNADH(unit "") = 0.02 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_Keq(unit "") = 0.066 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_Km13BPGA(unit "") = 0.1 "";
    parameter Real elmt_GAPDH_g_elmt_GAPDH_g_KmGA3P(unit "") = 0.15 "";
    Real elmt_reactant50 "";
    Real elmt_reactant51 "";
    Real elmt_reactant52 "";
    Real elmt_product54 "";
    Real elmt_product53 "";
    Real elmt_TPI_g(unit = "") "TPI_g";
    parameter Real elmt_TPI_g_elmt_TPI_g_KmGA3P(unit "") = 0.25 "";
    parameter Real elmt_TPI_g_elmt_TPI_g_Keq(unit "") = 0.046 "";
    parameter Real elmt_TPI_g_elmt_TPI_g_KmDHAP(unit "") = 1.2 "";
    parameter Real elmt_TPI_g_elmt_TPI_g_Vmax(unit "") = 999.3 "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_GK_g(unit = "") "GK_g";
    parameter Real elmt_GK_g_elmt_GK_g_KmGly(unit "") = 0.44 "";
    parameter Real elmt_GK_g_elmt_GK_g_Vmax(unit "") = 200.0 "";
    parameter Real elmt_GK_g_elmt_GK_g_KmGly3P(unit "") = 3.83 "";
    parameter Real elmt_GK_g_elmt_GK_g_KmADP(unit "") = 0.56 "";
    parameter Real elmt_GK_g_elmt_GK_g_KmATP(unit "") = 0.24 "";
    parameter Real elmt_GK_g_elmt_GK_g_Keq(unit "") = 8.37E-4 "";
    Real elmt_reactant41 "";
    Real elmt_reactant42 "";
    Real elmt_product44 "";
    Real elmt_product43 "";
    Real elmt_GDA_g(unit = "") "GDA_g";
    parameter Real elmt_GDA_g_elmt_GDA_g_k(unit "") = 600.0 "";
    Real elmt_product61 "";
    Real elmt_product60 "";
    Real elmt_reactant58 "";
    Real elmt_reactant59 "";
    Real elmt_GPO_c(unit = "") "GPO_c";
    parameter Real elmt_GPO_c_elmt_GPO_c_KmGly3P(unit "") = 1.7 "";
    parameter Real elmt_GPO_c_elmt_GPO_c_Vmax(unit "") = 368.0 "";
    Real elmt_product38 "";
    Real elmt_reactant37 "";
    Real elmt_PYK_c(unit = "") "PYK_c";
    parameter Real elmt_PYK_c_elmt_PYK_c_KmPyr(unit "") = 50.0 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KmPEP(unit "") = 0.34 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_Vmax(unit "") = 1020.0 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_Keq(unit "") = 10800.0 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_n(unit "") = 2.5 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KmADP(unit "") = 0.114 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KmATP(unit "") = 15.0 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KiATP(unit "") = 0.57 "";
    parameter Real elmt_PYK_c_elmt_PYK_c_KiADP(unit "") = 0.64 "";
    Real elmt_reactant2 "";
    Real elmt_reactant3 "";
    Real elmt_product5 "";
    Real elmt_product4 "";
    Real elmt_G3PDH_g(unit = "") "G3PDH_g";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_Vmax(unit "") = 465.0 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_KmGly3P(unit "") = 2.0 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_Keq(unit "") = 17085.0 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_KmDHAP(unit "") = 0.1 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_KmNADH(unit "") = 0.01 "";
    parameter Real elmt_G3PDH_g_elmt_G3PDH_g_KmNAD(unit "") = 0.4 "";
    Real elmt_product36 "";
    Real elmt_product35 "";
    Real elmt_reactant33 "";
    Real elmt_reactant34 "";
    Real elmt_AK_c(unit = "") "AK_c";
    parameter Real elmt_AK_c_elmt_AK_c_k1(unit "") = 480.0 "";
    parameter Real elmt_AK_c_elmt_AK_c_k2(unit "") = 1000.0 "";
    Real elmt_product47 "";
    Real elmt_product46 "";
    Real elmt_reactant45 "";
    Real elmt_ALD_g(unit = "") "ALD_g";
    parameter Real elmt_ALD_g_elmt_ALD_g_KmDHAP(unit "") = 0.015 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KiATP(unit "") = 0.68 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KiADP(unit "") = 1.51 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KmFru16BP(unit "") = 0.009 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KiAMP(unit "") = 3.65 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KiGA3P(unit "") = 0.098 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_Keq(unit "") = 0.084 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_Vmax(unit "") = 560.0 "";
    parameter Real elmt_ALD_g_elmt_ALD_g_KmGA3P(unit "") = 0.067 "";
    Real elmt_reactant18 "";
    Real elmt_product20 "";
    Real elmt_product19 "";
    Real elmt_ATPu_c(unit = "") "ATPu_c";
    parameter Real elmt_ATPu_c_elmt_ATPu_c_k(unit "") = 50.0 "";
    Real elmt_product40 "";
    Real elmt_reactant39 "";
    Real elmt_GlcT_c(unit = "") "GlcT_c";
    parameter Real elmt_GlcT_c_elmt_GlcT_c_KmGlc(unit "") = 1.0 "";
    parameter Real elmt_GlcT_c_elmt_GlcT_c_alpha(unit "") = 0.75 "";
    parameter Real elmt_GlcT_c_elmt_GlcT_c_Vmax(unit "") = 111.7 "";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_AK_g(unit = "") "AK_g";
    parameter Real elmt_AK_g_elmt_AK_g_k1(unit "") = 480.0 "";
    parameter Real elmt_AK_g_elmt_AK_g_k2(unit "") = 1000.0 "";
    Real elmt_product56 "";
    Real elmt_product57 "";
    Real elmt_reactant55 "";
    Real elmt_PyrT_c(unit = "") "PyrT_c";
    parameter Real elmt_PyrT_c_elmt_PyrT_c_Vmax(unit "") = 230.0 "";
    parameter Real elmt_PyrT_c_elmt_PyrT_c_KmPyr(unit "") = 1.96 "";
    Real elmt_reactant14 "";
    Real elmt_product15 "";
    Real elmt_GlcT_g(unit = "") "GlcT_g";
    parameter Real elmt_GlcT_g_elmt_GlcT_g_k2(unit "") = 250000.0 "";
    parameter Real elmt_GlcT_g_elmt_GlcT_g_k1(unit "") = 250000.0 "";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_HXK_g(unit = "") "HXK_g";
    parameter Real elmt_HXK_g_elmt_HXK_g_Keq(unit "") = 759.0 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_KmATP(unit "") = 0.116 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_KmADP(unit "") = 0.126 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_KmGlc(unit "") = 0.1 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_KmGlc6P(unit "") = 12.0 "";
    parameter Real elmt_HXK_g_elmt_HXK_g_Vmax(unit "") = 1774.68 "";
    Real elmt_product26 "";
    Real elmt_product25 "";
    Real elmt_reactant23 "";
    Real elmt_reactant24 "";
    Real elmt_PGI_g(unit = "") "PGI_g";
    parameter Real elmt_PGI_g_elmt_PGI_g_KmGlc6P(unit "") = 0.4 "";
    parameter Real elmt_PGI_g_elmt_PGI_g_KmFru6P(unit "") = 0.12 "";
    parameter Real elmt_PGI_g_elmt_PGI_g_Vmax(unit "") = 1305.0 "";
    parameter Real elmt_PGI_g_elmt_PGI_g_Ki6PG(unit "") = 0.14 "";
    parameter Real elmt_PGI_g_elmt__6PG_g(unit "") = 0.0841958 "";
    parameter Real elmt_PGI_g_elmt_PGI_g_Keq(unit "") = 0.457 "";
    Real elmt_product49 "";
    Real elmt_reactant48 "";
    Real elmt_PGK_g(unit = "") "PGK_g";
    parameter Real elmt_PGK_g_elmt_PGK_g_Vmax(unit "") = 2862.0 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_Km13BPGA(unit "") = 0.003 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_Keq(unit "") = 3377.0 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_KmADP(unit "") = 0.1 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_KmATP(unit "") = 0.29 "";
    parameter Real elmt_PGK_g_elmt_PGK_g_Km3PGA(unit "") = 1.62 "";
    Real elmt_reactant30 "";
    Real elmt_reactant29 "";
    Real elmt_product32 "";
    Real elmt_product31 "";
    Real elmt_PFK_g(unit = "") "PFK_g";
    parameter Real elmt_PFK_g_elmt_PFK_g_Vmax(unit "") = 1708.0 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_KmFru6P(unit "") = 0.999 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_KsATP(unit "") = 0.0393 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_Ki2(unit "") = 10.7 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_Ki1(unit "") = 15.8 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_KmATP(unit "") = 0.0648 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_KmADP(unit "") = 1.0 "";
    parameter Real elmt_PFK_g_elmt_PFK_g_Keq(unit "") = 1035.0 "";
    Real elmt_product9 "";
    Real elmt_product8 "";
    Real elmt_reactant6 "";
    Real elmt_reactant7 "";
    Real elmt__3PGAT_g(unit = "") "_3PGAT_g";
    parameter Real elmt__3PGAT_g_elmt__3PGAT_g_k(unit "") = 250.0 "";
    Real elmt_reactant27 "";
    Real elmt_product28 "";


    initial equation
        elmt_reactant41 = 1.0;
        elmt_reactant42 = 1.0;
        elmt_product32 = 1.0;
        elmt_product31 = 1.0;
        elmt_reactant48 = 1.0;
        elmt_reactant45 = 2.0;
        elmt_product26 = 1.0;
        elmt_product25 = 1.0;
        elmt_product28 = 1.0;
        elmt_reactant50 = 1.0;
        elmt_reactant51 = 1.0;
        elmt_product40 = 1.0;
        elmt_reactant52 = 1.0;
        elmt_product44 = 1.0;
        elmt_product43 = 1.0;
        elmt_reactant58 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant59 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant55 = 2.0;
        elmt_reactant12 = 1.0;
        elmt_product38 = 1.0;
        elmt_product36 = 1.0;
        elmt_product35 = 1.0;
        elmt_product56 = 1.0;
        elmt_product11 = 1.0;
        elmt_product54 = 1.0;
        elmt_product53 = 1.0;
        elmt_reactant27 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant23 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_product49 = 1.0;
        elmt_product47 = 1.0;
        elmt_product46 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product9 = 1.0;
        elmt_product8 = 1.0;
        elmt_product61 = 1.0;
        elmt_reactant30 = 1.0;
        elmt_product60 = 1.0;
        elmt_reactant3 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_product22 = 1.0;
        elmt_product20 = 1.0;
        elmt_reactant7 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant37 = 1.0;
        elmt_reactant39 = 1.0;
        elmt_product5 = 1.0;
        elmt_product4 = 1.0;
        elmt_reactant33 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant34 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_product15 = 1.0;
        elmt_product13 = 1.0;
        elmt_product57 = 1.0;
        elmt_product19 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_ENO_c = (((elmt_ENO_c_elmt_ENO_c_Vmax * elmt__2PGA_c * (1.0 - (elmt_PEP_c / (elmt_ENO_c_elmt_ENO_c_Keq * elmt__2PGA_c)))) / (elmt_ENO_c_elmt_ENO_c_Km2PGA * (1.0 + (elmt__2PGA_c / elmt_ENO_c_elmt_ENO_c_Km2PGA) + (elmt_PEP_c / elmt_ENO_c_elmt_ENO_c_KmPEP)))));
        elmt_PGAM_c = (((elmt_PGAM_c_elmt_PGAM_c_Vmax * elmt__3PGA_c * (1.0 - (elmt__2PGA_c / (elmt_PGAM_c_elmt_PGAM_c_Keq * elmt__3PGA_c)))) / (elmt_PGAM_c_elmt_PGAM_c_Km3PGA * (1.0 + (elmt__3PGA_c / elmt_PGAM_c_elmt_PGAM_c_Km3PGA) + (elmt__2PGA_c / elmt_PGAM_c_elmt_PGAM_c_Km2PGA)))));
        elmt_GAPDH_g = (((elmt_GAPDH_g_elmt_GAPDH_g_Vmax * elmt_GA3P_g * elmt_NAD_g * (1.0 - ((elmt__13BPGA_g * elmt_NADH_g) / (elmt_GAPDH_g_elmt_GAPDH_g_Keq * elmt_GA3P_g * elmt_NAD_g)))) / (elmt_GAPDH_g_elmt_GAPDH_g_KmGA3P * elmt_GAPDH_g_elmt_GAPDH_g_KmNAD * (1.0 + (elmt_GA3P_g / elmt_GAPDH_g_elmt_GAPDH_g_KmGA3P) + (elmt__13BPGA_g / elmt_GAPDH_g_elmt_GAPDH_g_Km13BPGA)) * (1.0 + (elmt_NAD_g / elmt_GAPDH_g_elmt_GAPDH_g_KmNAD) + (elmt_NADH_g / elmt_GAPDH_g_elmt_GAPDH_g_KmNADH)))));
        elmt_TPI_g = (((elmt_TPI_g_elmt_TPI_g_Vmax * elmt_DHAP_g * (1.0 - (elmt_GA3P_g / (elmt_TPI_g_elmt_TPI_g_Keq * elmt_DHAP_g)))) / (elmt_TPI_g_elmt_TPI_g_KmDHAP * (1.0 + (elmt_DHAP_g / elmt_TPI_g_elmt_TPI_g_KmDHAP) + (elmt_GA3P_g / elmt_TPI_g_elmt_TPI_g_KmGA3P)))));
        elmt_GK_g = (((elmt_GK_g_elmt_GK_g_Vmax * elmt_Gly3P_g * elmt_ADP_g * (1.0 - ((elmt_Gly_e * elmt_ATP_g) / (elmt_GK_g_elmt_GK_g_Keq * elmt_Gly3P_g * elmt_ADP_g)))) / (elmt_GK_g_elmt_GK_g_KmGly3P * elmt_GK_g_elmt_GK_g_KmADP * (1.0 + (elmt_Gly3P_g / elmt_GK_g_elmt_GK_g_KmGly3P) + (elmt_Gly_e / elmt_GK_g_elmt_GK_g_KmGly)) * (1.0 + (elmt_ADP_g / elmt_GK_g_elmt_GK_g_KmADP) + (elmt_ATP_g / elmt_GK_g_elmt_GK_g_KmATP)))));
        elmt_GDA_g = ((elmt_Gly3P_g * elmt_GDA_g_elmt_GDA_g_k * elmt_DHAP_c) - (elmt_Gly3P_c * elmt_GDA_g_elmt_GDA_g_k * elmt_DHAP_g));
        elmt_GPO_c = (((elmt_GPO_c_elmt_GPO_c_Vmax * elmt_Gly3P_c) / (elmt_GPO_c_elmt_GPO_c_KmGly3P * (1.0 + (elmt_Gly3P_c / elmt_GPO_c_elmt_GPO_c_KmGly3P)))));
        elmt_PYK_c = ((elmt_PYK_c_elmt_PYK_c_Vmax * elmt_ADP_c * (1.0 - ((elmt_Pyr_c * elmt_ATP_c) / (elmt_PYK_c_elmt_PYK_c_Keq * elmt_PEP_c * elmt_ADP_c))) * Functions.pow((elmt_PEP_c / (elmt_PYK_c_elmt_PYK_c_KmPEP * (1.0 + (elmt_ADP_c / elmt_PYK_c_elmt_PYK_c_KiADP) + (elmt_ATP_c / elmt_PYK_c_elmt_PYK_c_KiATP)))), elmt_PYK_c_elmt_PYK_c_n)) / (elmt_PYK_c_elmt_PYK_c_KmADP * (1.0 + Functions.pow((elmt_PEP_c / (elmt_PYK_c_elmt_PYK_c_KmPEP * (1.0 + (elmt_ADP_c / elmt_PYK_c_elmt_PYK_c_KiADP) + (elmt_ATP_c / elmt_PYK_c_elmt_PYK_c_KiATP)))), elmt_PYK_c_elmt_PYK_c_n) + (elmt_Pyr_c / elmt_PYK_c_elmt_PYK_c_KmPyr)) * (1.0 + (elmt_ADP_c / elmt_PYK_c_elmt_PYK_c_KmADP) + (elmt_ATP_c / elmt_PYK_c_elmt_PYK_c_KmATP))));
        elmt_G3PDH_g = (((elmt_G3PDH_g_elmt_G3PDH_g_Vmax * elmt_DHAP_g * elmt_NADH_g * (1.0 - ((elmt_Gly3P_g * elmt_NAD_g) / (elmt_G3PDH_g_elmt_G3PDH_g_Keq * elmt_DHAP_g * elmt_NADH_g)))) / (elmt_G3PDH_g_elmt_G3PDH_g_KmDHAP * elmt_G3PDH_g_elmt_G3PDH_g_KmNADH * (1.0 + (elmt_DHAP_g / elmt_G3PDH_g_elmt_G3PDH_g_KmDHAP) + (elmt_Gly3P_g / elmt_G3PDH_g_elmt_G3PDH_g_KmGly3P)) * (1.0 + (elmt_NADH_g / elmt_G3PDH_g_elmt_G3PDH_g_KmNADH) + (elmt_NAD_g / elmt_G3PDH_g_elmt_G3PDH_g_KmNAD)))));
        elmt_AK_c = (((elmt_AK_c_elmt_AK_c_k1 * Functions.pow(elmt_ADP_c, 2.0)) - (elmt_AMP_c * elmt_ATP_c * elmt_AK_c_elmt_AK_c_k2)));
        elmt_ALD_g = ((elmt_ALD_g_elmt_ALD_g_Vmax * elmt_Fru16BP_g * (1.0 - ((elmt_GA3P_g * elmt_DHAP_g) / (elmt_Fru16BP_g * elmt_ALD_g_elmt_ALD_g_Keq)))) / (elmt_ALD_g_elmt_ALD_g_KmFru16BP * (1.0 + (elmt_ATP_g / elmt_ALD_g_elmt_ALD_g_KiATP) + (elmt_ADP_g / elmt_ALD_g_elmt_ALD_g_KiADP) + (elmt_AMP_g / elmt_ALD_g_elmt_ALD_g_KiAMP)) * (1.0 + (elmt_GA3P_g / elmt_ALD_g_elmt_ALD_g_KmGA3P) + (elmt_DHAP_g / elmt_ALD_g_elmt_ALD_g_KmDHAP) + (elmt_Fru16BP_g / (elmt_ALD_g_elmt_ALD_g_KmFru16BP * (1.0 + (elmt_ATP_g / elmt_ALD_g_elmt_ALD_g_KiATP) + (elmt_ADP_g / elmt_ALD_g_elmt_ALD_g_KiADP) + (elmt_AMP_g / elmt_ALD_g_elmt_ALD_g_KiAMP)))) + ((elmt_GA3P_g * elmt_DHAP_g) / (elmt_ALD_g_elmt_ALD_g_KmGA3P * elmt_ALD_g_elmt_ALD_g_KmDHAP)) + ((elmt_Fru16BP_g * elmt_GA3P_g) / (elmt_ALD_g_elmt_ALD_g_KmFru16BP * elmt_ALD_g_elmt_ALD_g_KiGA3P * (1.0 + (elmt_ATP_g / elmt_ALD_g_elmt_ALD_g_KiATP) + (elmt_ADP_g / elmt_ALD_g_elmt_ALD_g_KiADP) + (elmt_AMP_g / elmt_ALD_g_elmt_ALD_g_KiAMP)))))));
        elmt_ATPu_c = ((elmt_ATPu_c_elmt_ATPu_c_k * elmt_ATP_c) / elmt_ADP_c);
        elmt_GlcT_c = ((elmt_GlcT_c_elmt_GlcT_c_Vmax * (elmt_Glc_e - elmt_Glc_c)) / (elmt_GlcT_c_elmt_GlcT_c_KmGlc + elmt_Glc_e + elmt_Glc_c + ((elmt_GlcT_c_elmt_GlcT_c_alpha * elmt_Glc_e * elmt_Glc_c) / elmt_GlcT_c_elmt_GlcT_c_KmGlc)));
        elmt_AK_g = (((elmt_AK_g_elmt_AK_g_k1 * Functions.pow(elmt_ADP_g, 2.0)) - (elmt_AMP_g * elmt_ATP_g * elmt_AK_g_elmt_AK_g_k2)));
        elmt_PyrT_c = (((elmt_PyrT_c_elmt_PyrT_c_Vmax * elmt_Pyr_c) / (elmt_PyrT_c_elmt_PyrT_c_KmPyr * (1.0 + (elmt_Pyr_c / elmt_PyrT_c_elmt_PyrT_c_KmPyr)))));
        elmt_GlcT_g = (((elmt_GlcT_g_elmt_GlcT_g_k1 * elmt_Glc_c) - (elmt_GlcT_g_elmt_GlcT_g_k2 * elmt_Glc_g)));
        elmt_HXK_g = (((elmt_HXK_g_elmt_HXK_g_Vmax * elmt_Glc_g * elmt_ATP_g * (1.0 - ((elmt_Glc6P_g * elmt_ADP_g) / (elmt_HXK_g_elmt_HXK_g_Keq * elmt_Glc_g * elmt_ATP_g)))) / (elmt_HXK_g_elmt_HXK_g_KmGlc * elmt_HXK_g_elmt_HXK_g_KmATP * (1.0 + (elmt_Glc_g / elmt_HXK_g_elmt_HXK_g_KmGlc) + (elmt_Glc6P_g / elmt_HXK_g_elmt_HXK_g_KmGlc6P)) * (1.0 + (elmt_ATP_g / elmt_HXK_g_elmt_HXK_g_KmATP) + (elmt_ADP_g / elmt_HXK_g_elmt_HXK_g_KmADP)))));
        elmt_PGI_g = ((elmt_PGI_g_elmt_PGI_g_Vmax * elmt_Glc6P_g * (1.0 - (elmt_Fru6P_g / (elmt_PGI_g_elmt_PGI_g_Keq * elmt_Glc6P_g)))) / (elmt_PGI_g_elmt_PGI_g_KmGlc6P * (1.0 + (elmt_Glc6P_g / elmt_PGI_g_elmt_PGI_g_KmGlc6P) + (elmt_Fru6P_g / elmt_PGI_g_elmt_PGI_g_KmFru6P) + (elmt_PGI_g_elmt__6PG_g / elmt_PGI_g_elmt_PGI_g_Ki6PG))));
        elmt_PGK_g = (((elmt_PGK_g_elmt_PGK_g_Vmax * elmt__13BPGA_g * elmt_ADP_g * (1.0 - ((elmt__3PGA_g * elmt_ATP_g) / (elmt_PGK_g_elmt_PGK_g_Keq * elmt__13BPGA_g * elmt_ADP_g)))) / (elmt_PGK_g_elmt_PGK_g_Km13BPGA * elmt_PGK_g_elmt_PGK_g_KmADP * (1.0 + (elmt__13BPGA_g / elmt_PGK_g_elmt_PGK_g_Km13BPGA) + (elmt__3PGA_g / elmt_PGK_g_elmt_PGK_g_Km3PGA)) * (1.0 + (elmt_ADP_g / elmt_PGK_g_elmt_PGK_g_KmADP) + (elmt_ATP_g / elmt_PGK_g_elmt_PGK_g_KmATP)))));
        elmt_PFK_g = ((elmt_PFK_g_elmt_PFK_g_Vmax * elmt_PFK_g_elmt_PFK_g_Ki1 * elmt_Fru6P_g * elmt_ATP_g * (1.0 - ((elmt_Fru16BP_g * elmt_ADP_g) / (elmt_PFK_g_elmt_PFK_g_Keq * elmt_Fru6P_g * elmt_ATP_g)))) / (elmt_PFK_g_elmt_PFK_g_KmFru6P * elmt_PFK_g_elmt_PFK_g_KmATP * (elmt_Fru16BP_g + elmt_PFK_g_elmt_PFK_g_Ki1) * ((elmt_PFK_g_elmt_PFK_g_KsATP / elmt_PFK_g_elmt_PFK_g_KmATP) + (elmt_Fru6P_g / elmt_PFK_g_elmt_PFK_g_KmFru6P) + (elmt_ATP_g / elmt_PFK_g_elmt_PFK_g_KmATP) + (elmt_ADP_g / elmt_PFK_g_elmt_PFK_g_KmADP) + ((elmt_Fru16BP_g * elmt_ADP_g) / (elmt_PFK_g_elmt_PFK_g_KmADP * elmt_PFK_g_elmt_PFK_g_Ki2)) + ((elmt_Fru6P_g * elmt_ATP_g) / (elmt_PFK_g_elmt_PFK_g_KmFru6P * elmt_PFK_g_elmt_PFK_g_KmATP)))));
        elmt__3PGAT_g = (((elmt__3PGAT_g_elmt__3PGAT_g_k * elmt__3PGA_g) - (elmt__3PGAT_g_elmt__3PGAT_g_k * elmt__3PGA_c)));
        der(elmt_reactant41) = 0;
        der(elmt_reactant42) = 0;
        der(elmt_product32) = 0;
        der(elmt_product31) = 0;
        der(elmt_reactant48) = 0;
        der(elmt_reactant45) = 0;
        der(elmt_product26) = 0;
        der(elmt_product25) = 0;
        der(elmt_product28) = 0;
        der(elmt_reactant50) = 0;
        der(elmt_reactant51) = 0;
        der(elmt_product40) = 0;
        der(elmt_reactant52) = 0;
        der(elmt_product44) = 0;
        der(elmt_product43) = 0;
        der(elmt_reactant58) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant59) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant55) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_product38) = 0;
        der(elmt_product36) = 0;
        der(elmt_product35) = 0;
        der(elmt_product56) = 0;
        der(elmt_product11) = 0;
        der(elmt_product54) = 0;
        der(elmt_product53) = 0;
        der(elmt_reactant27) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant23) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_product49) = 0;
        der(elmt_product47) = 0;
        der(elmt_product46) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product9) = 0;
        der(elmt_product8) = 0;
        der(elmt_product61) = 0;
        der(elmt_reactant30) = 0;
        der(elmt_product60) = 0;
        der(elmt_reactant3) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_product22) = 0;
        der(elmt_product20) = 0;
        der(elmt_reactant7) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant37) = 0;
        der(elmt_reactant39) = 0;
        der(elmt_product5) = 0;
        der(elmt_product4) = 0;
        der(elmt_reactant33) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant34) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_product15) = 0;
        der(elmt_product13) = 0;
        der(elmt_product57) = 0;
        der(elmt_product19) = 0;
        der(elmt_product17) = 0;

end Reactions;
