/* Simulation code for MoonLanding generated by the OpenModelica Compiler OpenModelica 1.13.0~dev-747-g0c1336f. */
#if !defined(MoonLanding__MODEL_H)
#define MoonLanding__MODEL_H
#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <string.h>

#include "MoonLanding_functions.h"

#define ECU_ad_index 0
#define ECU_autopilot7_index 1

extern void MoonLanding_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
extern void MoonLanding_initialNonLinearSystem(int nNonLinearSystems, NONLINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void MoonLanding_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int MoonLanding_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int MoonLanding_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int MoonLanding_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int MoonLanding_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int MoonLanding_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int MoonLanding_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int MoonLanding_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int MoonLanding_checkForAsserts(DATA *data, threadData_t *threadData);
extern int MoonLanding_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int MoonLanding_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int MoonLanding_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* MoonLanding_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* MoonLanding_relationDescription(int i);
extern void MoonLanding_function_initSample(DATA *data, threadData_t *threadData);
extern int MoonLanding_initialAnalyticJacobianG(void* data, threadData_t *threadData);
extern int MoonLanding_initialAnalyticJacobianA(void* data, threadData_t *threadData);
extern int MoonLanding_initialAnalyticJacobianB(void* data, threadData_t *threadData);
extern int MoonLanding_initialAnalyticJacobianC(void* data, threadData_t *threadData);
extern int MoonLanding_initialAnalyticJacobianD(void* data, threadData_t *threadData);
extern int MoonLanding_functionJacG_column(void* data, threadData_t *threadData);
extern int MoonLanding_functionJacA_column(void* data, threadData_t *threadData);
extern int MoonLanding_functionJacB_column(void* data, threadData_t *threadData);
extern int MoonLanding_functionJacC_column(void* data, threadData_t *threadData);
extern int MoonLanding_functionJacD_column(void* data, threadData_t *threadData);
extern const char* MoonLanding_linear_model_frame(void);
extern const char* MoonLanding_linear_model_datarecovery_frame(void);
extern int MoonLanding_mayer(DATA* data, modelica_real** res, short *);
extern int MoonLanding_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int MoonLanding_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int MoonLanding_setInputData(DATA *data, const modelica_boolean file);
extern int MoonLanding_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void MoonLanding_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void MoonLanding_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int MoonLanding_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void MoonLanding_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void MoonLanding_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int MoonLanding_inputNames(DATA* data, char ** names);
extern int MoonLanding_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int MoonLanding_functionLocalKnownVars(DATA*, threadData_t*);
extern int MoonLanding_symbolicInlineSystem(DATA*, threadData_t*);

#include "MoonLanding_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#endif

