/* Additional record code for MoonLanding generated by the OpenModelica Compiler OpenModelica 1.13.0~dev-747-g0c1336f. */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

