

#include <iostream>
#include <vector>
#include <iomanip>
#include <string>
#include <fstream>

#define PI 3.14159265358979323846

#include "Zeilinger2006_PRR7_PRR9_Y_SystemDefinition.cuh"
#include "SingleSystem_PerThread_Interface.cuh"

using namespace std;

#define SOLVER RKCK45
#define PRECISION double
const int NT   = 1000;
const int SD   = 170;
const int NCP  = 0;
const int NSP  = 0;
const int NISP = 0;
const int NE   = 1;
const int NA   = 86;
const int NIA  = 2;
const int NDO  = 1000;


void FillSolverObject(
    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION>& Solver, 
     vector<PRECISION>& Variable_X, 
    int FirstProblemNumber, int NumberOfThreads
) {
    int k_begin = FirstProblemNumber;
    int k_end   = FirstProblemNumber + NumberOfThreads;
	
    int ProblemNumber = 0;
    while (k_begin < k_end) {
        Solver.SetHost(ProblemNumber, TimeDomain, 0, 0.0);
        Solver.SetHost(ProblemNumber, TimeDomain, 1, 10.0);  

        int i = 0;
        for (PRECISION x : Variable_X) {
            Solver.SetHost(ProblemNumber, ActualState, i++, x);
        }

        Solver.SetHost(ProblemNumber, ActualTime, 0.0);
        Solver.SetHost(ProblemNumber, ControlParameters, 0, 0.0);
        Solver.SetHost(ProblemNumber, DenseIndex, 0 );

        Solver.SetHost(ProblemNumber, Accessories, 0, 6.7846);
        Solver.SetHost(ProblemNumber, Accessories, 1, 20.0554);
        Solver.SetHost(ProblemNumber, Accessories, 2, 6.0091);
        Solver.SetHost(ProblemNumber, Accessories, 3, 0.1724);
        Solver.SetHost(ProblemNumber, Accessories, 4, 13.0372);
        Solver.SetHost(ProblemNumber, Accessories, 5, 7.075);
        Solver.SetHost(ProblemNumber, Accessories, 6, 0.8539);
        Solver.SetHost(ProblemNumber, Accessories, 7, 6.8104);
        Solver.SetHost(ProblemNumber, Accessories, 8, 4.28);
        Solver.SetHost(ProblemNumber, Accessories, 9, 2.091);
        Solver.SetHost(ProblemNumber, Accessories, 10, 1.1006);
        Solver.SetHost(ProblemNumber, Accessories, 11, 3.7528);
        Solver.SetHost(ProblemNumber, Accessories, 12, 0.0);
        Solver.SetHost(ProblemNumber, Accessories, 13, 0.3717);
        Solver.SetHost(ProblemNumber, Accessories, 14, 8.0398);
        Solver.SetHost(ProblemNumber, Accessories, 15, 8.487);
        Solver.SetHost(ProblemNumber, Accessories, 16, 31.8995);
        Solver.SetHost(ProblemNumber, Accessories, 17, 0.1937);
        Solver.SetHost(ProblemNumber, Accessories, 18, 1.07);
        Solver.SetHost(ProblemNumber, IntegerAccessories, 0, 0);
        Solver.SetHost(ProblemNumber, IntegerAccessories, 1, 0);
		
		ProblemNumber++;
        k_begin++;
    }



}


void SaveData(
    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION>& Solver, 
    ofstream& DataFile, int NumberOfThreads
) {
    int Width = 18;
    DataFile.precision(10);
    DataFile.flags(ios::scientific);
	
    for (int tid=0; tid<NumberOfThreads; tid++)
    {
        DataFile.width(Width); DataFile << "X_Params.elmt_a" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_b" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_c" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_d" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_e" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_f" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g1" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g10" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g2" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g3" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g4" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g5" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g6" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g7" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g8" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_g9" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_h" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_i" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_j" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k1" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k10" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k11" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k12" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k13" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k14" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k15" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k16" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k17" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k18" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k19" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k2" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k3" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k4" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k5" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k6" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k7" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k8" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_k9" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_ld" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_lmax" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m1" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m10" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m11" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m12" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m13" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m14" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m15" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m16" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m17" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m18" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m19" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m2" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m20" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m21" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m3" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m4" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m5" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m6" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m7" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m8" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_m9" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_n1" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_n2" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_n3" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_n4" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_n5" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_n6" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_n7" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_p1" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_p2" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_p3" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_p4" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_p5" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_p6" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_p7" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_q1" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_q2" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_q3" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r1" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r10" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r11" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r12" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r2" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r3" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r4" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r5" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r6" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r7" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r8" << ',';
        DataFile.width(Width); DataFile << "X_Params.elmt_r9" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product0" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product1" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product10" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product12" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product14" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product16" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product19" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product21" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product23" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product25" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product28" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product3" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product30" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product32" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product34" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product37" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product40" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product42" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product44" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product46" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product49" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product5" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product51" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product53" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product55" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_product7" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant11" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant13" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant15" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant17" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant18" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant2" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant20" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant22" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant24" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant26" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant27" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant29" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant31" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant33" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant35" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant36" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant38" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant39" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant4" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant41" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant43" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant45" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant47" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant48" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant50" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant52" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant54" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant56" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant57" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant6" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant8" << ',';
        DataFile.width(Width); DataFile << "X_Reacs.elmt_reactant9" << ',';
        DataFile.width(Width); DataFile << "X_elmt_cytoplasm.elmt_cLc_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_cytoplasm.elmt_cP7c_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_cytoplasm.elmt_cP9c_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_cytoplasm.elmt_cTc_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_cytoplasm.elmt_cXc_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_cytoplasm.elmt_cYc_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_cytoplasm.elmt_cytoplasm" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cLm_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cLn_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cP7m_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cP7n_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cP9m_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cP9n_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cPn_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cTm_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cTn_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cXm_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cXn_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cYm_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_cYn_amount" << ',';
        DataFile.width(Width); DataFile << "X_elmt_nucleus.elmt_nucleus" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse1" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse10" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse11" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse12" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse13" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse14" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse15" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse16" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse17" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse18" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse19" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse2" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse20" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse3" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse4" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse5" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse6" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse7" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse8" << ',';
        DataFile.width(Width); DataFile << "ACC_$cse9" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R11" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R14" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R18" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R21" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R25" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R28" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R34" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R37" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R4" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R41" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R44" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_R7" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_cLc_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_cP7c_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_cP9c_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_cTc_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_cXc_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_cytoplasm.elmt_cYc_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_event_0000001.value_elmt_ld" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R1" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R10" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R12" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R13" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R15" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R16" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R17" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R19" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R2" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R20" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R22" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R23" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R24" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R26" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R27" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R29" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R3" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R30" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R31a" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R31b" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R32" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R33" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R35" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R36" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R38" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R39" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R40" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R42" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R43" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R45" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R5" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R6" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R8" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_R9" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cLm_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cLn_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cP7m_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cP7n_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cP9m_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cP9n_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cPn_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cTm_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cTn_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cXm_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cXn_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cYm_conc" << ',';
        DataFile.width(Width); DataFile << "ACC_elmt_nucleus.elmt_cYn_conc" << ',';
        DataFile.width(Width); DataFile << "ACCi_$whenCondition1" << ',';
        DataFile.width(Width); DataFile << "ACCi_Params.elmt_event_0000001" << ',';
        DataFile.width(Width); DataFile << endl;
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 1) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 2) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 3) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 4) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 5) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 6) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 7) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 8) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 9) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 10) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 11) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 12) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 13) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 14) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 15) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 16) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 17) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 18) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 19) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 20) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 21) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 22) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 23) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 24) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 25) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 26) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 27) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 28) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 29) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 30) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 31) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 32) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 33) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 34) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 35) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 36) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 37) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 38) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 39) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 40) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 41) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 42) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 43) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 44) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 45) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 46) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 47) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 48) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 49) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 50) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 51) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 52) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 53) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 54) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 55) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 56) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 57) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 58) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 59) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 60) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 61) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 62) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 63) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 64) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 65) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 66) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 67) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 68) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 69) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 70) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 71) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 72) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 73) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 74) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 75) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 76) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 77) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 78) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 79) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 80) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 81) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 82) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 83) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 84) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 85) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 86) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 87) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 88) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 89) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 90) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 91) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 92) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 93) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 94) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 95) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 96) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 97) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 98) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 99) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 100) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 101) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 102) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 103) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 104) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 105) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 106) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 107) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 108) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 109) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 110) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 111) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 112) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 113) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 114) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 115) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 116) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 117) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 118) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 119) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 120) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 121) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 122) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 123) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 124) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 125) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 126) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 127) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 128) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 129) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 130) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 131) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 132) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 133) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 134) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 135) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 136) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 137) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 138) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 139) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 140) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 141) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 142) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 143) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 144) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 145) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 146) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 147) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 148) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 149) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 150) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 151) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 152) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 153) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 154) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 155) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 156) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 157) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 158) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 159) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 160) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 161) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 162) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 163) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 164) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 165) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 166) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 167) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 168) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, ActualState, 169) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 1) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 2) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 3) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 4) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 5) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 6) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 7) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 8) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 9) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 10) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 11) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 12) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 13) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 14) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 15) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 16) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 17) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 18) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 19) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 20) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 21) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 22) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 23) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 24) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 25) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 26) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 27) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 28) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 29) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 30) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 31) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 32) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 33) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 34) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 35) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 36) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 37) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 38) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 39) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 40) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 41) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 42) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 43) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 44) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 45) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 46) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 47) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 48) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 49) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 50) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 51) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 52) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 53) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 54) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 55) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 56) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 57) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 58) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 59) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 60) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 61) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 62) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 63) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 64) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 65) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 66) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 67) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 68) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 69) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 70) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 71) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 72) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 73) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 74) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 75) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 76) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 77) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 78) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 79) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 80) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 81) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 82) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 83) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 84) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, Accessories, 85) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, IntegerAccessories, 0) << ',';
        DataFile.width(Width); DataFile << Solver.GetHost<PRECISION>(tid, IntegerAccessories, 1) << ',';

        DataFile << '\n';
    }
}


int main() {
    int numberOfProblems = 2000; // Numero di problemi da risolvere, uno per thread
    int blockSize        = 1024; // Numero di Thread per blocchi
    
    // Listing dei Device CUDA
    ListCUDADevices();

    int MajorVersion = 7; // Major version della CUDA compute capability
    int MinorVersion = 5; // Minor version della CUDA compute capability

    // Seleziona il Device da utilizzare dando in input la CUDA compute capability e ne stampa le caratteristiche
    int SelectedDevice = SelectDeviceByClosestRevision(MajorVersion, MinorVersion);
    PrintPropertiesOfSpecificDevice(SelectedDevice);

    PRECISION InitialCondtition_Params_elmt_a=1.8775;
    PRECISION InitialCondtition_Params_elmt_b=1.5408;
    PRECISION InitialCondtition_Params_elmt_c=1.4723;
    PRECISION InitialCondtition_Params_elmt_d=4.0627;
    PRECISION InitialCondtition_Params_elmt_e=3.5723;
    PRECISION InitialCondtition_Params_elmt_f=2.0127;
    PRECISION InitialCondtition_Params_elmt_g1=11.7992;
    PRECISION InitialCondtition_Params_elmt_g10=17.7951;
    PRECISION InitialCondtition_Params_elmt_g2=8.733000000000001;
    PRECISION InitialCondtition_Params_elmt_g3=17.9887;
    PRECISION InitialCondtition_Params_elmt_g4=5.6552;
    PRECISION InitialCondtition_Params_elmt_g5=1.5091;
    PRECISION InitialCondtition_Params_elmt_g6=20.7577;
    PRECISION InitialCondtition_Params_elmt_g7=4.6434;
    PRECISION InitialCondtition_Params_elmt_g8=4.7985;
    PRECISION InitialCondtition_Params_elmt_g9=4.8052;
    PRECISION InitialCondtition_Params_elmt_h=3.3286;
    PRECISION InitialCondtition_Params_elmt_i=3.5898;
    PRECISION InitialCondtition_Params_elmt_j=1.269;
    PRECISION InitialCondtition_Params_elmt_k=1.5212;
    PRECISION InitialCondtition_Params_elmt_k1=4.1029;
    PRECISION InitialCondtition_Params_elmt_k10=16.4042;
    PRECISION InitialCondtition_Params_elmt_k11=55.7326;
    PRECISION InitialCondtition_Params_elmt_k12=9.0406;
    PRECISION InitialCondtition_Params_elmt_k13=1.2;
    PRECISION InitialCondtition_Params_elmt_k14=14.0306;
    PRECISION InitialCondtition_Params_elmt_k15=19.799;
    PRECISION InitialCondtition_Params_elmt_k16=8.797700000000001;
    PRECISION InitialCondtition_Params_elmt_k17=16.0706;
    PRECISION InitialCondtition_Params_elmt_k18=48.4999;
    PRECISION InitialCondtition_Params_elmt_k19=57.4671;
    PRECISION InitialCondtition_Params_elmt_k2=29.5681;
    PRECISION InitialCondtition_Params_elmt_k3=18.6335;
    PRECISION InitialCondtition_Params_elmt_k4=4.7728;
    PRECISION InitialCondtition_Params_elmt_k5=3.0204;
    PRECISION InitialCondtition_Params_elmt_k6=55.3798;
    PRECISION InitialCondtition_Params_elmt_k7=29.3208;
    PRECISION InitialCondtition_Params_elmt_k8=9.5343;
    PRECISION InitialCondtition_Params_elmt_k9=45.1336;
    PRECISION InitialCondtition_Params_elmt_ld=0.0;
    PRECISION InitialCondtition_Params_elmt_lmax=1.0;
    PRECISION InitialCondtition_Params_elmt_m1=3.7622;
    PRECISION InitialCondtition_Params_elmt_m10=35.1982;
    PRECISION InitialCondtition_Params_elmt_m11=7.0274;
    PRECISION InitialCondtition_Params_elmt_m12=3.4563;
    PRECISION InitialCondtition_Params_elmt_m13=9.153499999999999;
    PRECISION InitialCondtition_Params_elmt_m14=7.5549;
    PRECISION InitialCondtition_Params_elmt_m15=1.2;
    PRECISION InitialCondtition_Params_elmt_m16=10.1357;
    PRECISION InitialCondtition_Params_elmt_m17=7.2481;
    PRECISION InitialCondtition_Params_elmt_m18=7.8275;
    PRECISION InitialCondtition_Params_elmt_m19=10.1288;
    PRECISION InitialCondtition_Params_elmt_m2=22.5198;
    PRECISION InitialCondtition_Params_elmt_m20=0.5315;
    PRECISION InitialCondtition_Params_elmt_m21=8.594200000000001;
    PRECISION InitialCondtition_Params_elmt_m3=4.5545;
    PRECISION InitialCondtition_Params_elmt_m4=7.1601;
    PRECISION InitialCondtition_Params_elmt_m5=1.5511;
    PRECISION InitialCondtition_Params_elmt_m6=1.4189;
    PRECISION InitialCondtition_Params_elmt_m7=1.6789;
    PRECISION InitialCondtition_Params_elmt_m8=11.3548;
    PRECISION InitialCondtition_Params_elmt_m9=5.7847;
    PRECISION InitialCondtition_Params_elmt_n1=1.0988;
    PRECISION InitialCondtition_Params_elmt_n2=13.5067;
    PRECISION InitialCondtition_Params_elmt_n3=1.7236;
    PRECISION InitialCondtition_Params_elmt_n4=1.8828;
    PRECISION InitialCondtition_Params_elmt_n5=1.506;
    PRECISION InitialCondtition_Params_elmt_n6=4.6039;
    PRECISION InitialCondtition_Params_elmt_n7=4.4383;
    PRECISION InitialCondtition_Params_elmt_p1=7.5408;
    PRECISION InitialCondtition_Params_elmt_p2=1.4452;
    PRECISION InitialCondtition_Params_elmt_p3=3.1473;
    PRECISION InitialCondtition_Params_elmt_p4=2.8599;
    PRECISION InitialCondtition_Params_elmt_p5=0.5;
    PRECISION InitialCondtition_Params_elmt_p6=2.0248;
    PRECISION InitialCondtition_Params_elmt_p7=1.0929;
    PRECISION InitialCondtition_Params_elmt_q1=13.1446;
    PRECISION InitialCondtition_Params_elmt_q2=12.7437;
    PRECISION InitialCondtition_Params_elmt_q3=1.0;
    PRECISION InitialCondtition_Params_elmt_r1=9.937799999999999;
    PRECISION InitialCondtition_Params_elmt_r10=30.7684;
    PRECISION InitialCondtition_Params_elmt_r11=9.7804;
    PRECISION InitialCondtition_Params_elmt_r12=15.4577;
    PRECISION InitialCondtition_Params_elmt_r2=9.6442;
    PRECISION InitialCondtition_Params_elmt_r3=14.7607;
    PRECISION InitialCondtition_Params_elmt_r4=0.2559;
    PRECISION InitialCondtition_Params_elmt_r5=31.0081;
    PRECISION InitialCondtition_Params_elmt_r6=12.5039;
    PRECISION InitialCondtition_Params_elmt_r7=5.735;
    PRECISION InitialCondtition_Params_elmt_r8=37.3301;
    PRECISION InitialCondtition_Params_elmt_r9=3.2996;
    PRECISION InitialCondtition_Reacs_elmt_product0=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product1=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product10=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product12=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product14=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product16=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product19=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product21=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product23=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product25=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product28=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product3=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product30=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product32=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product34=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product37=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product40=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product42=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product44=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product46=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product49=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product5=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product51=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product53=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product55=1.0;
    PRECISION InitialCondtition_Reacs_elmt_product7=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant11=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant13=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant15=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant17=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant18=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant2=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant20=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant22=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant24=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant26=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant27=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant29=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant31=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant33=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant35=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant36=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant38=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant39=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant4=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant41=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant43=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant45=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant47=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant48=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant50=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant52=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant54=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant56=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant57=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant6=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant8=1.0;
    PRECISION InitialCondtition_Reacs_elmt_reactant9=1.0;
    PRECISION InitialCondtition_elmt_cytoplasm_elmt_cytoplasm=1.0;
    PRECISION InitialCondtition_elmt_nucleus_elmt_nucleus=1.0;
    vector<PRECISION> Parameter_X = {InitialCondition_Params_elmt_a,InitialCondition_Params_elmt_b,InitialCondition_Params_elmt_c,InitialCondition_Params_elmt_d,InitialCondition_Params_elmt_e,InitialCondition_Params_elmt_f,InitialCondition_Params_elmt_g1,InitialCondition_Params_elmt_g10,InitialCondition_Params_elmt_g2,InitialCondition_Params_elmt_g3,InitialCondition_Params_elmt_g4,InitialCondition_Params_elmt_g5,InitialCondition_Params_elmt_g6,InitialCondition_Params_elmt_g7,InitialCondition_Params_elmt_g8,InitialCondition_Params_elmt_g9,InitialCondition_Params_elmt_h,InitialCondition_Params_elmt_i,InitialCondition_Params_elmt_j,InitialCondition_Params_elmt_k,InitialCondition_Params_elmt_k1,InitialCondition_Params_elmt_k10,InitialCondition_Params_elmt_k11,InitialCondition_Params_elmt_k12,InitialCondition_Params_elmt_k13,InitialCondition_Params_elmt_k14,InitialCondition_Params_elmt_k15,InitialCondition_Params_elmt_k16,InitialCondition_Params_elmt_k17,InitialCondition_Params_elmt_k18,InitialCondition_Params_elmt_k19,InitialCondition_Params_elmt_k2,InitialCondition_Params_elmt_k3,InitialCondition_Params_elmt_k4,InitialCondition_Params_elmt_k5,InitialCondition_Params_elmt_k6,InitialCondition_Params_elmt_k7,InitialCondition_Params_elmt_k8,InitialCondition_Params_elmt_k9,InitialCondition_Params_elmt_ld,InitialCondition_Params_elmt_lmax,InitialCondition_Params_elmt_m1,InitialCondition_Params_elmt_m10,InitialCondition_Params_elmt_m11,InitialCondition_Params_elmt_m12,InitialCondition_Params_elmt_m13,InitialCondition_Params_elmt_m14,InitialCondition_Params_elmt_m15,InitialCondition_Params_elmt_m16,InitialCondition_Params_elmt_m17,InitialCondition_Params_elmt_m18,InitialCondition_Params_elmt_m19,InitialCondition_Params_elmt_m2,InitialCondition_Params_elmt_m20,InitialCondition_Params_elmt_m21,InitialCondition_Params_elmt_m3,InitialCondition_Params_elmt_m4,InitialCondition_Params_elmt_m5,InitialCondition_Params_elmt_m6,InitialCondition_Params_elmt_m7,InitialCondition_Params_elmt_m8,InitialCondition_Params_elmt_m9,InitialCondition_Params_elmt_n1,InitialCondition_Params_elmt_n2,InitialCondition_Params_elmt_n3,InitialCondition_Params_elmt_n4,InitialCondition_Params_elmt_n5,InitialCondition_Params_elmt_n6,InitialCondition_Params_elmt_n7,InitialCondition_Params_elmt_p1,InitialCondition_Params_elmt_p2,InitialCondition_Params_elmt_p3,InitialCondition_Params_elmt_p4,InitialCondition_Params_elmt_p5,InitialCondition_Params_elmt_p6,InitialCondition_Params_elmt_p7,InitialCondition_Params_elmt_q1,InitialCondition_Params_elmt_q2,InitialCondition_Params_elmt_q3,InitialCondition_Params_elmt_r1,InitialCondition_Params_elmt_r10,InitialCondition_Params_elmt_r11,InitialCondition_Params_elmt_r12,InitialCondition_Params_elmt_r2,InitialCondition_Params_elmt_r3,InitialCondition_Params_elmt_r4,InitialCondition_Params_elmt_r5,InitialCondition_Params_elmt_r6,InitialCondition_Params_elmt_r7,InitialCondition_Params_elmt_r8,InitialCondition_Params_elmt_r9,InitialCondition_Reacs_elmt_product0,InitialCondition_Reacs_elmt_product1,InitialCondition_Reacs_elmt_product10,InitialCondition_Reacs_elmt_product12,InitialCondition_Reacs_elmt_product14,InitialCondition_Reacs_elmt_product16,InitialCondition_Reacs_elmt_product19,InitialCondition_Reacs_elmt_product21,InitialCondition_Reacs_elmt_product23,InitialCondition_Reacs_elmt_product25,InitialCondition_Reacs_elmt_product28,InitialCondition_Reacs_elmt_product3,InitialCondition_Reacs_elmt_product30,InitialCondition_Reacs_elmt_product32,InitialCondition_Reacs_elmt_product34,InitialCondition_Reacs_elmt_product37,InitialCondition_Reacs_elmt_product40,InitialCondition_Reacs_elmt_product42,InitialCondition_Reacs_elmt_product44,InitialCondition_Reacs_elmt_product46,InitialCondition_Reacs_elmt_product49,InitialCondition_Reacs_elmt_product5,InitialCondition_Reacs_elmt_product51,InitialCondition_Reacs_elmt_product53,InitialCondition_Reacs_elmt_product55,InitialCondition_Reacs_elmt_product7,InitialCondition_Reacs_elmt_reactant11,InitialCondition_Reacs_elmt_reactant13,InitialCondition_Reacs_elmt_reactant15,InitialCondition_Reacs_elmt_reactant17,InitialCondition_Reacs_elmt_reactant18,InitialCondition_Reacs_elmt_reactant2,InitialCondition_Reacs_elmt_reactant20,InitialCondition_Reacs_elmt_reactant22,InitialCondition_Reacs_elmt_reactant24,InitialCondition_Reacs_elmt_reactant26,InitialCondition_Reacs_elmt_reactant27,InitialCondition_Reacs_elmt_reactant29,InitialCondition_Reacs_elmt_reactant31,InitialCondition_Reacs_elmt_reactant33,InitialCondition_Reacs_elmt_reactant35,InitialCondition_Reacs_elmt_reactant36,InitialCondition_Reacs_elmt_reactant38,InitialCondition_Reacs_elmt_reactant39,InitialCondition_Reacs_elmt_reactant4,InitialCondition_Reacs_elmt_reactant41,InitialCondition_Reacs_elmt_reactant43,InitialCondition_Reacs_elmt_reactant45,InitialCondition_Reacs_elmt_reactant47,InitialCondition_Reacs_elmt_reactant48,InitialCondition_Reacs_elmt_reactant50,InitialCondition_Reacs_elmt_reactant52,InitialCondition_Reacs_elmt_reactant54,InitialCondition_Reacs_elmt_reactant56,InitialCondition_Reacs_elmt_reactant57,InitialCondition_Reacs_elmt_reactant6,InitialCondition_Reacs_elmt_reactant8,InitialCondition_Reacs_elmt_reactant9,InitialCondition_elmt_cytoplasm_elmt_cytoplasm,InitialCondition_elmt_nucleus_elmt_nucleus};


    ProblemSolver<NT,SD,NCP,NSP,NISP,NE,NA,NIA,NDO,SOLVER,PRECISION> Solver(SelectedDevice);
    Solver.SolverOption(ThreadsPerBlock, blockSize);
    Solver.SolverOption(PreferSharedMemory, 1);
    Solver.SolverOption(InitialTimeStep, 0.01);
    Solver.SolverOption(ActiveNumberOfThreads, NT);
    Solver.SolverOption(MaximumTimeStep, 1000000.0);
    Solver.SolverOption(MinimumTimeStep, 1e-14);
    Solver.SolverOption(TimeStepGrowLimit, 10.0);
    Solver.SolverOption(TimeStepShrinkLimit, 0.2);
    Solver.SolverOption(EventDirection, 0, 0);

    Solver.SolverOption(DenseOutputMinimumTimeStep, 0.0);
    Solver.SolverOption(DenseOutputSaveFrequency, 1);
    Solver.SolverOption(AbsoluteTolerance, 0, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 1, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 2, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 3, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 4, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 5, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 6, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 7, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 8, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 9, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 10, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 11, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 12, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 13, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 14, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 15, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 16, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 17, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 18, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 19, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 20, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 21, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 22, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 23, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 24, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 25, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 26, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 27, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 28, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 29, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 30, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 31, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 32, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 33, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 34, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 35, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 36, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 37, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 38, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 39, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 40, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 41, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 42, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 43, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 44, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 45, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 46, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 47, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 48, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 49, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 50, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 51, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 52, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 53, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 54, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 55, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 56, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 57, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 58, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 59, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 60, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 61, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 62, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 63, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 64, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 65, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 66, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 67, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 68, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 69, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 70, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 71, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 72, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 73, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 74, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 75, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 76, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 77, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 78, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 79, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 80, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 81, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 82, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 83, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 84, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 85, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 86, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 87, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 88, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 89, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 90, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 91, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 92, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 93, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 94, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 95, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 96, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 97, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 98, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 99, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 100, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 101, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 102, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 103, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 104, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 105, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 106, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 107, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 108, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 109, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 110, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 111, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 112, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 113, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 114, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 115, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 116, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 117, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 118, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 119, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 120, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 121, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 122, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 123, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 124, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 125, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 126, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 127, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 128, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 129, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 130, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 131, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 132, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 133, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 134, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 135, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 136, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 137, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 138, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 139, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 140, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 141, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 142, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 143, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 144, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 145, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 146, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 147, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 148, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 149, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 150, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 151, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 152, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 153, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 154, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 155, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 156, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 157, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 158, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 159, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 160, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 161, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 162, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 163, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 164, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 165, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 166, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 167, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 168, 1e-06);
    Solver.SolverOption(AbsoluteTolerance, 169, 1e-06);

    Solver.SolverOption(RelativeTolerance, 0, 1e-06);
    Solver.SolverOption(RelativeTolerance, 1, 1e-06);
    Solver.SolverOption(RelativeTolerance, 2, 1e-06);
    Solver.SolverOption(RelativeTolerance, 3, 1e-06);
    Solver.SolverOption(RelativeTolerance, 4, 1e-06);
    Solver.SolverOption(RelativeTolerance, 5, 1e-06);
    Solver.SolverOption(RelativeTolerance, 6, 1e-06);
    Solver.SolverOption(RelativeTolerance, 7, 1e-06);
    Solver.SolverOption(RelativeTolerance, 8, 1e-06);
    Solver.SolverOption(RelativeTolerance, 9, 1e-06);
    Solver.SolverOption(RelativeTolerance, 10, 1e-06);
    Solver.SolverOption(RelativeTolerance, 11, 1e-06);
    Solver.SolverOption(RelativeTolerance, 12, 1e-06);
    Solver.SolverOption(RelativeTolerance, 13, 1e-06);
    Solver.SolverOption(RelativeTolerance, 14, 1e-06);
    Solver.SolverOption(RelativeTolerance, 15, 1e-06);
    Solver.SolverOption(RelativeTolerance, 16, 1e-06);
    Solver.SolverOption(RelativeTolerance, 17, 1e-06);
    Solver.SolverOption(RelativeTolerance, 18, 1e-06);
    Solver.SolverOption(RelativeTolerance, 19, 1e-06);
    Solver.SolverOption(RelativeTolerance, 20, 1e-06);
    Solver.SolverOption(RelativeTolerance, 21, 1e-06);
    Solver.SolverOption(RelativeTolerance, 22, 1e-06);
    Solver.SolverOption(RelativeTolerance, 23, 1e-06);
    Solver.SolverOption(RelativeTolerance, 24, 1e-06);
    Solver.SolverOption(RelativeTolerance, 25, 1e-06);
    Solver.SolverOption(RelativeTolerance, 26, 1e-06);
    Solver.SolverOption(RelativeTolerance, 27, 1e-06);
    Solver.SolverOption(RelativeTolerance, 28, 1e-06);
    Solver.SolverOption(RelativeTolerance, 29, 1e-06);
    Solver.SolverOption(RelativeTolerance, 30, 1e-06);
    Solver.SolverOption(RelativeTolerance, 31, 1e-06);
    Solver.SolverOption(RelativeTolerance, 32, 1e-06);
    Solver.SolverOption(RelativeTolerance, 33, 1e-06);
    Solver.SolverOption(RelativeTolerance, 34, 1e-06);
    Solver.SolverOption(RelativeTolerance, 35, 1e-06);
    Solver.SolverOption(RelativeTolerance, 36, 1e-06);
    Solver.SolverOption(RelativeTolerance, 37, 1e-06);
    Solver.SolverOption(RelativeTolerance, 38, 1e-06);
    Solver.SolverOption(RelativeTolerance, 39, 1e-06);
    Solver.SolverOption(RelativeTolerance, 40, 1e-06);
    Solver.SolverOption(RelativeTolerance, 41, 1e-06);
    Solver.SolverOption(RelativeTolerance, 42, 1e-06);
    Solver.SolverOption(RelativeTolerance, 43, 1e-06);
    Solver.SolverOption(RelativeTolerance, 44, 1e-06);
    Solver.SolverOption(RelativeTolerance, 45, 1e-06);
    Solver.SolverOption(RelativeTolerance, 46, 1e-06);
    Solver.SolverOption(RelativeTolerance, 47, 1e-06);
    Solver.SolverOption(RelativeTolerance, 48, 1e-06);
    Solver.SolverOption(RelativeTolerance, 49, 1e-06);
    Solver.SolverOption(RelativeTolerance, 50, 1e-06);
    Solver.SolverOption(RelativeTolerance, 51, 1e-06);
    Solver.SolverOption(RelativeTolerance, 52, 1e-06);
    Solver.SolverOption(RelativeTolerance, 53, 1e-06);
    Solver.SolverOption(RelativeTolerance, 54, 1e-06);
    Solver.SolverOption(RelativeTolerance, 55, 1e-06);
    Solver.SolverOption(RelativeTolerance, 56, 1e-06);
    Solver.SolverOption(RelativeTolerance, 57, 1e-06);
    Solver.SolverOption(RelativeTolerance, 58, 1e-06);
    Solver.SolverOption(RelativeTolerance, 59, 1e-06);
    Solver.SolverOption(RelativeTolerance, 60, 1e-06);
    Solver.SolverOption(RelativeTolerance, 61, 1e-06);
    Solver.SolverOption(RelativeTolerance, 62, 1e-06);
    Solver.SolverOption(RelativeTolerance, 63, 1e-06);
    Solver.SolverOption(RelativeTolerance, 64, 1e-06);
    Solver.SolverOption(RelativeTolerance, 65, 1e-06);
    Solver.SolverOption(RelativeTolerance, 66, 1e-06);
    Solver.SolverOption(RelativeTolerance, 67, 1e-06);
    Solver.SolverOption(RelativeTolerance, 68, 1e-06);
    Solver.SolverOption(RelativeTolerance, 69, 1e-06);
    Solver.SolverOption(RelativeTolerance, 70, 1e-06);
    Solver.SolverOption(RelativeTolerance, 71, 1e-06);
    Solver.SolverOption(RelativeTolerance, 72, 1e-06);
    Solver.SolverOption(RelativeTolerance, 73, 1e-06);
    Solver.SolverOption(RelativeTolerance, 74, 1e-06);
    Solver.SolverOption(RelativeTolerance, 75, 1e-06);
    Solver.SolverOption(RelativeTolerance, 76, 1e-06);
    Solver.SolverOption(RelativeTolerance, 77, 1e-06);
    Solver.SolverOption(RelativeTolerance, 78, 1e-06);
    Solver.SolverOption(RelativeTolerance, 79, 1e-06);
    Solver.SolverOption(RelativeTolerance, 80, 1e-06);
    Solver.SolverOption(RelativeTolerance, 81, 1e-06);
    Solver.SolverOption(RelativeTolerance, 82, 1e-06);
    Solver.SolverOption(RelativeTolerance, 83, 1e-06);
    Solver.SolverOption(RelativeTolerance, 84, 1e-06);
    Solver.SolverOption(RelativeTolerance, 85, 1e-06);
    Solver.SolverOption(RelativeTolerance, 86, 1e-06);
    Solver.SolverOption(RelativeTolerance, 87, 1e-06);
    Solver.SolverOption(RelativeTolerance, 88, 1e-06);
    Solver.SolverOption(RelativeTolerance, 89, 1e-06);
    Solver.SolverOption(RelativeTolerance, 90, 1e-06);
    Solver.SolverOption(RelativeTolerance, 91, 1e-06);
    Solver.SolverOption(RelativeTolerance, 92, 1e-06);
    Solver.SolverOption(RelativeTolerance, 93, 1e-06);
    Solver.SolverOption(RelativeTolerance, 94, 1e-06);
    Solver.SolverOption(RelativeTolerance, 95, 1e-06);
    Solver.SolverOption(RelativeTolerance, 96, 1e-06);
    Solver.SolverOption(RelativeTolerance, 97, 1e-06);
    Solver.SolverOption(RelativeTolerance, 98, 1e-06);
    Solver.SolverOption(RelativeTolerance, 99, 1e-06);
    Solver.SolverOption(RelativeTolerance, 100, 1e-06);
    Solver.SolverOption(RelativeTolerance, 101, 1e-06);
    Solver.SolverOption(RelativeTolerance, 102, 1e-06);
    Solver.SolverOption(RelativeTolerance, 103, 1e-06);
    Solver.SolverOption(RelativeTolerance, 104, 1e-06);
    Solver.SolverOption(RelativeTolerance, 105, 1e-06);
    Solver.SolverOption(RelativeTolerance, 106, 1e-06);
    Solver.SolverOption(RelativeTolerance, 107, 1e-06);
    Solver.SolverOption(RelativeTolerance, 108, 1e-06);
    Solver.SolverOption(RelativeTolerance, 109, 1e-06);
    Solver.SolverOption(RelativeTolerance, 110, 1e-06);
    Solver.SolverOption(RelativeTolerance, 111, 1e-06);
    Solver.SolverOption(RelativeTolerance, 112, 1e-06);
    Solver.SolverOption(RelativeTolerance, 113, 1e-06);
    Solver.SolverOption(RelativeTolerance, 114, 1e-06);
    Solver.SolverOption(RelativeTolerance, 115, 1e-06);
    Solver.SolverOption(RelativeTolerance, 116, 1e-06);
    Solver.SolverOption(RelativeTolerance, 117, 1e-06);
    Solver.SolverOption(RelativeTolerance, 118, 1e-06);
    Solver.SolverOption(RelativeTolerance, 119, 1e-06);
    Solver.SolverOption(RelativeTolerance, 120, 1e-06);
    Solver.SolverOption(RelativeTolerance, 121, 1e-06);
    Solver.SolverOption(RelativeTolerance, 122, 1e-06);
    Solver.SolverOption(RelativeTolerance, 123, 1e-06);
    Solver.SolverOption(RelativeTolerance, 124, 1e-06);
    Solver.SolverOption(RelativeTolerance, 125, 1e-06);
    Solver.SolverOption(RelativeTolerance, 126, 1e-06);
    Solver.SolverOption(RelativeTolerance, 127, 1e-06);
    Solver.SolverOption(RelativeTolerance, 128, 1e-06);
    Solver.SolverOption(RelativeTolerance, 129, 1e-06);
    Solver.SolverOption(RelativeTolerance, 130, 1e-06);
    Solver.SolverOption(RelativeTolerance, 131, 1e-06);
    Solver.SolverOption(RelativeTolerance, 132, 1e-06);
    Solver.SolverOption(RelativeTolerance, 133, 1e-06);
    Solver.SolverOption(RelativeTolerance, 134, 1e-06);
    Solver.SolverOption(RelativeTolerance, 135, 1e-06);
    Solver.SolverOption(RelativeTolerance, 136, 1e-06);
    Solver.SolverOption(RelativeTolerance, 137, 1e-06);
    Solver.SolverOption(RelativeTolerance, 138, 1e-06);
    Solver.SolverOption(RelativeTolerance, 139, 1e-06);
    Solver.SolverOption(RelativeTolerance, 140, 1e-06);
    Solver.SolverOption(RelativeTolerance, 141, 1e-06);
    Solver.SolverOption(RelativeTolerance, 142, 1e-06);
    Solver.SolverOption(RelativeTolerance, 143, 1e-06);
    Solver.SolverOption(RelativeTolerance, 144, 1e-06);
    Solver.SolverOption(RelativeTolerance, 145, 1e-06);
    Solver.SolverOption(RelativeTolerance, 146, 1e-06);
    Solver.SolverOption(RelativeTolerance, 147, 1e-06);
    Solver.SolverOption(RelativeTolerance, 148, 1e-06);
    Solver.SolverOption(RelativeTolerance, 149, 1e-06);
    Solver.SolverOption(RelativeTolerance, 150, 1e-06);
    Solver.SolverOption(RelativeTolerance, 151, 1e-06);
    Solver.SolverOption(RelativeTolerance, 152, 1e-06);
    Solver.SolverOption(RelativeTolerance, 153, 1e-06);
    Solver.SolverOption(RelativeTolerance, 154, 1e-06);
    Solver.SolverOption(RelativeTolerance, 155, 1e-06);
    Solver.SolverOption(RelativeTolerance, 156, 1e-06);
    Solver.SolverOption(RelativeTolerance, 157, 1e-06);
    Solver.SolverOption(RelativeTolerance, 158, 1e-06);
    Solver.SolverOption(RelativeTolerance, 159, 1e-06);
    Solver.SolverOption(RelativeTolerance, 160, 1e-06);
    Solver.SolverOption(RelativeTolerance, 161, 1e-06);
    Solver.SolverOption(RelativeTolerance, 162, 1e-06);
    Solver.SolverOption(RelativeTolerance, 163, 1e-06);
    Solver.SolverOption(RelativeTolerance, 164, 1e-06);
    Solver.SolverOption(RelativeTolerance, 165, 1e-06);
    Solver.SolverOption(RelativeTolerance, 166, 1e-06);
    Solver.SolverOption(RelativeTolerance, 167, 1e-06);
    Solver.SolverOption(RelativeTolerance, 168, 1e-06);
    Solver.SolverOption(RelativeTolerance, 169, 1e-06);
   
    
    int NumberOfSimulationLaunches = NumberOfProblems / NT + (NumberOfProblems % NT == 0 ? 0:1);
    ofstream DataFile;
    DataFile.open ( "Zeilinger2006_PRR7_PRR9_Y.csv" );
    clock_t SimulationStart = clock();
    clock_t TransientStart;
    clock_t TransientEnd;    
    for (int i=0; i < NumberOfSimulationLaunches; i++) {
        fillSolverObject(Solver, Parameter_X, i*NT, NT);
        Solver.SynchroniseFromHostToDevice(All);
        Solver.InsertSynchronisationPoint();
        Solver.SynchroniseSolver();

        TransientStart = clock();
        for (int j=0; j < 1; j++) {
            Solver.Solve();
            Solver.InsertSynchronisationPoint();
            Solver.SynchroniseSolver();
        }
        TransientEnd = clock();
        cout << "Launches: " << i << "  Simulation time: ";
        cout << 1000.0*(TransientEnd-TransientStart) / CLOCKS_PER_SEC << "ms" << endl << endl;
        for (int j=0; j<1; j++)
        {
            Solver.Solve();
            Solver.SynchroniseFromDeviceToHost(All);
            Solver.InsertSynchronisationPoint();
            Solver.SynchroniseSolver();
            SaveData(Solver, DataFile, NT);
        }
    }

    clock_t SimulationEnd = clock();
    cout << "Total simulation time: " << 1000.0*(SimulationEnd-SimulationStart) / CLOCKS_PER_SEC << "ms";
    cout << endl;
	
    DataFile.close();
    
    Solver.Print(DenseOutput, 0);
    Solver.Print(ActualState);
    Solver.Print(ActualTime);
	
    cout << "Test finished!" << endl;

    return 0;
}

