within BIOMD436;
class Reactions

    input Real elmt_DNA;
    input Real elmt_LPSactivity;
    input Real elmt_PGE2;
    input Real elmt_dPGD2;
    input Real elmt_k16;
    input Real elmt_k15;
    input Real elmt_k14;
    input Real elmt_FA;
    input Real elmt_k13;
    input Real elmt_k12;
    input Real elmt_dPGJ2;
    input Real elmt_PGF2a;
    input Real elmt_k11;
    input Real elmt_k10;
    input Real elmt_k1;
    input Real elmt_GPChoratio;
    input Real elmt_GPCho;
    input Real elmt_k19;
    input Real elmt_k18;
    input Real elmt_k17;
    input Real elmt_AA;
    input Real elmt_k8;
    input Real elmt_PGJ2;
    input Real elmt_k9;
    input Real elmt_PGH2;
    input Real elmt_k6;
    input Real elmt_k7;
    input Real elmt_HETE;
    input Real elmt_k4;
    input Real elmt_k5;
    input Real elmt_k2;
    input Real elmt_PGD2;
    input Real elmt_k3;
    input Real elmt_DGactivity;
    input Real elmt_DGperDNA;
    input Real elmt_onepmol;
    input Real elmt_k22;
    input Real elmt_k21;
    input Real elmt_k20;

    Real elmt_r7(unit = "") "";
    Real elmt_reactant4 "";
    Real elmt_product5 "";
    Real elmt_r17(unit = "") "";
    Real elmt_product23 "";
    Real elmt_reactant22 "";
    Real elmt_r8(unit = "") "";
    Real elmt_product13 "";
    Real elmt_reactant12 "";
    Real elmt_r16(unit = "") "";
    Real elmt_reactant21 "";
    Real elmt_r5(unit = "") "";
    Real elmt_product7 "";
    Real elmt_reactant6 "";
    Real elmt_r15(unit = "") "";
    Real elmt_reactant19 "";
    Real elmt_product20 "";
    Real elmt_r14(unit = "") "";
    Real elmt_reactant18 "";
    Real elmt_r6(unit = "") "";
    Real elmt_product35 "";
    Real elmt_reactant34 "";
    Real elmt_r3(unit = "") "";
    Real elmt_reactant2 "";
    Real elmt_product3 "";
    Real elmt_r13(unit = "") "";
    Real elmt_reactant16 "";
    Real elmt_product17 "";
    Real elmt_r4(unit = "") "";
    Real elmt_reactant14 "";
    Real elmt_r12(unit = "") "";
    Real elmt_reactant36 "";
    Real elmt_product37 "";
    Real elmt_r11(unit = "") "";
    Real elmt_product9 "";
    Real elmt_reactant8 "";
    Real elmt_r22(unit = "") "";
    Real elmt_reactant31 "";
    Real elmt_r1(unit = "") "";
    Real elmt_product33 "";
    Real elmt_reactant32 "";
    Real elmt_r2(unit = "") "";
    Real elmt_product1 "";
    Real elmt_reactant0 "";
    Real elmt_r10(unit = "") "";
    Real elmt_product11 "";
    Real elmt_reactant10 "";
    Real elmt_r21(unit = "") "";
    Real elmt_product30 "";
    Real elmt_reactant29 "";
    Real elmt_r9(unit = "") "";
    Real elmt_reactant15 "";
    Real elmt_r19(unit = "") "";
    Real elmt_product27 "";
    Real elmt_reactant26 "";
    Real elmt_r18(unit = "") "";
    Real elmt_product25 "";
    Real elmt_reactant24 "";
    Real elmt_r20(unit = "") "";
    Real elmt_reactant28 "";


    initial equation
        elmt_product30 = 1.0;
        elmt_product33 = 1.0;
        elmt_product11 = 1.0;
        elmt_reactant26 = 1.0;
        elmt_reactant28 = 1.0;
        elmt_reactant21 = 1.0;
        elmt_reactant22 = 1.0;
        elmt_reactant24 = 1.0;
        elmt_reactant18 = 1.0;
        elmt_reactant19 = 1.0;
        elmt_product27 = 1.0;
        elmt_product25 = 1.0;
        elmt_reactant2 = 1.0;
        elmt_product9 = 1.0;
        elmt_reactant4 = 1.0;
        elmt_product7 = 1.0;
        elmt_reactant31 = 1.0;
        elmt_product23 = 1.0;
        elmt_reactant6 = 1.0;
        elmt_reactant8 = 1.0;
        elmt_product20 = 1.0;
        elmt_reactant14 = 1.0;
        elmt_reactant36 = 1.0;
        elmt_product1 = 1.0;
        elmt_reactant15 = 1.0;
        elmt_reactant16 = 1.0;
        elmt_product5 = 1.0;
        elmt_reactant32 = 1.0;
        elmt_reactant10 = 1.0;
        elmt_reactant12 = 1.0;
        elmt_reactant34 = 1.0;
        elmt_product3 = 1.0;
        elmt_reactant0 = 1.0;
        elmt_reactant29 = 1.0;
        elmt_product37 = 1.0;
        elmt_product13 = 1.0;
        elmt_product35 = 1.0;
        elmt_product17 = 1.0;


    equation
        elmt_r7 = (elmt_k7 * elmt_GPChoratio * elmt_GPCho);
        elmt_r17 = (elmt_k17 * elmt_PGH2);
        elmt_r8 = (elmt_k8 * elmt_AA);
        elmt_r16 = (elmt_k16 * elmt_PGF2a);
        elmt_r5 = ((elmt_k5 * elmt_DGactivity * elmt_GPChoratio * elmt_GPCho) / elmt_DNA);
        elmt_r15 = (elmt_k15 * elmt_PGH2);
        elmt_r14 = (elmt_k14 * elmt_PGE2);
        elmt_r6 = (elmt_k6 * elmt_GPCho * elmt_GPChoratio * elmt_LPSactivity);
        elmt_r3 = (elmt_k3 * elmt_DGactivity * elmt_DGperDNA * elmt_DNA);
        elmt_r13 = (elmt_k13 * elmt_PGH2);
        elmt_r4 = (elmt_k4 * elmt_AA);
        elmt_r12 = (elmt_k12 * elmt_AA * elmt_LPSactivity);
        elmt_r11 = (elmt_k11 * elmt_AA);
        elmt_r22 = (elmt_k22 * elmt_dPGJ2);
        elmt_r1 = (elmt_k1 * elmt_onepmol * elmt_LPSactivity);
        elmt_r2 = (elmt_k2 * elmt_FA);
        elmt_r10 = ((elmt_k10 * elmt_DGactivity * elmt_AA) / elmt_DNA);
        elmt_r21 = (elmt_k21 * elmt_PGJ2);
        elmt_r9 = (elmt_k9 * elmt_HETE);
        elmt_r19 = (elmt_k19 * elmt_PGD2);
        elmt_r18 = (elmt_k18 * elmt_PGD2);
        elmt_r20 = (elmt_k20 * elmt_dPGD2);
        der(elmt_product30) = 0;
        der(elmt_product33) = 0;
        der(elmt_product11) = 0;
        der(elmt_reactant26) = 0;
        der(elmt_reactant28) = 0;
        der(elmt_reactant21) = 0;
        der(elmt_reactant22) = 0;
        der(elmt_reactant24) = 0;
        der(elmt_reactant18) = 0;
        der(elmt_reactant19) = 0;
        der(elmt_product27) = 0;
        der(elmt_product25) = 0;
        der(elmt_reactant2) = 0;
        der(elmt_product9) = 0;
        der(elmt_reactant4) = 0;
        der(elmt_product7) = 0;
        der(elmt_reactant31) = 0;
        der(elmt_product23) = 0;
        der(elmt_reactant6) = 0;
        der(elmt_reactant8) = 0;
        der(elmt_product20) = 0;
        der(elmt_reactant14) = 0;
        der(elmt_reactant36) = 0;
        der(elmt_product1) = 0;
        der(elmt_reactant15) = 0;
        der(elmt_reactant16) = 0;
        der(elmt_product5) = 0;
        der(elmt_reactant32) = 0;
        der(elmt_reactant10) = 0;
        der(elmt_reactant12) = 0;
        der(elmt_reactant34) = 0;
        der(elmt_product3) = 0;
        der(elmt_reactant0) = 0;
        der(elmt_reactant29) = 0;
        der(elmt_product37) = 0;
        der(elmt_product13) = 0;
        der(elmt_product35) = 0;
        der(elmt_product17) = 0;

end Reactions;
