within BIOMD247;
model ralser "Ralser2007_Carbohydrate_Rerouting_ROS" annotation(Documentation(info="<annotation>
  <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\" xmlns:bqmodel=\"http://biomodels.net/model-qualifiers/\" xmlns:vCard=\"http://www.w3.org/2001/vcard-rdf/3.0#\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:bqbiol=\"http://biomodels.net/biology-qualifiers/\">
	
  </rdf:RDF>
</annotation>"));

    Parameters Params;
    Reactions Reacs;
    Class_elmt_cytoplasm elmt_cytoplasm;
    Class_elmt_extracellular elmt_extracellular;

    equation
        Params.elmt_NADP = elmt_cytoplasm.elmt_NADP;
        Params.elmt_NADPH = elmt_cytoplasm.elmt_NADPH;
        Reacs.elmt_F16P = elmt_cytoplasm.elmt_F16P;
        Reacs.elmt_NAD = elmt_cytoplasm.elmt_NAD;
        Reacs.elmt_NADP = elmt_cytoplasm.elmt_NADP;
        Reacs.elmt_Ribose5P = elmt_cytoplasm.elmt_Ribose5P;
        Reacs.elmt_Erythrose4P = elmt_cytoplasm.elmt_Erythrose4P;
        Reacs.elmt_ETOH = elmt_extracellular.elmt_ETOH;
        Reacs.elmt_k_rel_GAPDH = Params.elmt_k_rel_GAPDH;
        Reacs.elmt_PEP = elmt_cytoplasm.elmt_PEP;
        Reacs.elmt_Xyl5P = elmt_cytoplasm.elmt_Xyl5P;
        Reacs.elmt_Seduhept7P = elmt_cytoplasm.elmt_Seduhept7P;
        Reacs.elmt_BPG = elmt_cytoplasm.elmt_BPG;
        Reacs.elmt_P3G = elmt_cytoplasm.elmt_P3G;
        Reacs.elmt_k_rel_TPI = Params.elmt_k_rel_TPI;
        Reacs.elmt_DHAP = elmt_cytoplasm.elmt_DHAP;
        Reacs.elmt_GLCo = elmt_extracellular.elmt_GLCo;
        Reacs.elmt_NADH = elmt_cytoplasm.elmt_NADH;
        Reacs.elmt_P = elmt_cytoplasm.elmt_P;
        Reacs.elmt_Ribulose5P = elmt_cytoplasm.elmt_Ribulose5P;
        Reacs.elmt_D6PGluconoLactone = elmt_cytoplasm.elmt_D6PGluconoLactone;
        Reacs.elmt_GLY = elmt_extracellular.elmt_GLY;
        Reacs.elmt_GLCi = elmt_cytoplasm.elmt_GLCi;
        Reacs.elmt_F6P = elmt_cytoplasm.elmt_F6P;
        Reacs.elmt_NADPH = elmt_cytoplasm.elmt_NADPH;
        Reacs.elmt_P2G = elmt_cytoplasm.elmt_P2G;
        Reacs.elmt_ACE = elmt_cytoplasm.elmt_ACE;
        Reacs.elmt_cytoplasm = elmt_cytoplasm.elmt_cytoplasm;
        Reacs.elmt_G6P = elmt_cytoplasm.elmt_G6P;
        Reacs.elmt_SUMAXP = Params.elmt_SUMAXP;
        Reacs.elmt_GA3P = elmt_cytoplasm.elmt_GA3P;
        Reacs.elmt_PYR = elmt_cytoplasm.elmt_PYR;
        Reacs.elmt_F26BP = elmt_cytoplasm.elmt_F26BP;
        Reacs.elmt_D6PGluconate = elmt_cytoplasm.elmt_D6PGluconate;
        elmt_cytoplasm.elmt_product30 = Reacs.elmt_product30;
        elmt_cytoplasm.elmt_reactant40 = Reacs.elmt_reactant40;
        elmt_cytoplasm.elmt_product73 = Reacs.elmt_product73;
        elmt_cytoplasm.elmt_product71 = Reacs.elmt_product71;
        elmt_cytoplasm.elmt_vGLT = Reacs.elmt_vGLT;
        elmt_cytoplasm.elmt_reactant42 = Reacs.elmt_reactant42;
        elmt_cytoplasm.elmt_product34 = Reacs.elmt_product34;
        elmt_cytoplasm.elmt_v6PGL = Reacs.elmt_v6PGL;
        elmt_cytoplasm.elmt_vGLK = Reacs.elmt_vGLK;
        elmt_cytoplasm.elmt_vADH = Reacs.elmt_vADH;
        elmt_cytoplasm.elmt_reactant48 = Reacs.elmt_reactant48;
        elmt_cytoplasm.elmt_vG3PDH = Reacs.elmt_vG3PDH;
        elmt_cytoplasm.elmt_reactant44 = Reacs.elmt_reactant44;
        elmt_cytoplasm.elmt_reactant45 = Reacs.elmt_reactant45;
        elmt_cytoplasm.elmt_vTransk1 = Reacs.elmt_vTransk1;
        elmt_cytoplasm.elmt_vTransk2 = Reacs.elmt_vTransk2;
        elmt_cytoplasm.elmt_vSUC = Reacs.elmt_vSUC;
        elmt_cytoplasm.elmt_product27 = Reacs.elmt_product27;
        elmt_cytoplasm.elmt_vPFK = Reacs.elmt_vPFK;
        elmt_cytoplasm.elmt_product25 = Reacs.elmt_product25;
        elmt_cytoplasm.elmt_product69 = Reacs.elmt_product69;
        elmt_cytoplasm.elmt_product68 = Reacs.elmt_product68;
        elmt_cytoplasm.elmt_vTransald = Reacs.elmt_vTransald;
        elmt_cytoplasm.elmt_product28 = Reacs.elmt_product28;
        elmt_cytoplasm.elmt_reactant50 = Reacs.elmt_reactant50;
        elmt_cytoplasm.elmt_reactant51 = Reacs.elmt_reactant51;
        elmt_cytoplasm.elmt_product43 = Reacs.elmt_product43;
        elmt_cytoplasm.elmt_reactant15 = Reacs.elmt_reactant15;
        elmt_cytoplasm.elmt_reactant16 = Reacs.elmt_reactant16;
        elmt_cytoplasm.elmt_reactant54 = Reacs.elmt_reactant54;
        elmt_cytoplasm.elmt_vR5PI = Reacs.elmt_vR5PI;
        elmt_cytoplasm.elmt_reactant11 = Reacs.elmt_reactant11;
        elmt_cytoplasm.elmt_reactant56 = Reacs.elmt_reactant56;
        elmt_cytoplasm.elmt_reactant12 = Reacs.elmt_reactant12;
        elmt_cytoplasm.elmt_reactant57 = Reacs.elmt_reactant57;
        elmt_cytoplasm.elmt_vATP = Reacs.elmt_vATP;
        elmt_cytoplasm.elmt_vALD = Reacs.elmt_vALD;
        elmt_cytoplasm.elmt_product39 = Reacs.elmt_product39;
        elmt_cytoplasm.elmt_product52 = Reacs.elmt_product52;
        elmt_cytoplasm.elmt_reactant62 = Reacs.elmt_reactant62;
        elmt_cytoplasm.elmt_vTPI = Reacs.elmt_vTPI;
        elmt_cytoplasm.elmt_reactant63 = Reacs.elmt_reactant63;
        elmt_cytoplasm.elmt_vPDC = Reacs.elmt_vPDC;
        elmt_cytoplasm.elmt_product55 = Reacs.elmt_product55;
        elmt_cytoplasm.elmt_product10 = Reacs.elmt_product10;
        elmt_cytoplasm.elmt_reactant60 = Reacs.elmt_reactant60;
        elmt_cytoplasm.elmt_product53 = Reacs.elmt_product53;
        elmt_cytoplasm.elmt_vENO = Reacs.elmt_vENO;
        elmt_cytoplasm.elmt_reactant26 = Reacs.elmt_reactant26;
        elmt_cytoplasm.elmt_vPPI = Reacs.elmt_vPPI;
        elmt_cytoplasm.elmt_reactant66 = Reacs.elmt_reactant66;
        elmt_cytoplasm.elmt_reactant22 = Reacs.elmt_reactant22;
        elmt_cytoplasm.elmt_reactant67 = Reacs.elmt_reactant67;
        elmt_cytoplasm.elmt_reactant24 = Reacs.elmt_reactant24;
        elmt_cytoplasm.elmt_vNADPH = Reacs.elmt_vNADPH;
        elmt_cytoplasm.elmt_vPYK = Reacs.elmt_vPYK;
        elmt_cytoplasm.elmt_reactant19 = Reacs.elmt_reactant19;
        elmt_cytoplasm.elmt_product49 = Reacs.elmt_product49;
        elmt_cytoplasm.elmt_product47 = Reacs.elmt_product47;
        elmt_cytoplasm.elmt_product46 = Reacs.elmt_product46;
        elmt_cytoplasm.elmt_product9 = Reacs.elmt_product9;
        elmt_cytoplasm.elmt_vGAPDH = Reacs.elmt_vGAPDH;
        elmt_cytoplasm.elmt_reactant1 = Reacs.elmt_reactant1;
        elmt_cytoplasm.elmt_product7 = Reacs.elmt_product7;
        elmt_cytoplasm.elmt_product61 = Reacs.elmt_product61;
        elmt_cytoplasm.elmt_reactant3 = Reacs.elmt_reactant3;
        elmt_cytoplasm.elmt_reactant6 = Reacs.elmt_reactant6;
        elmt_cytoplasm.elmt_vPGI = Reacs.elmt_vPGI;
        elmt_cytoplasm.elmt_product23 = Reacs.elmt_product23;
        elmt_cytoplasm.elmt_reactant5 = Reacs.elmt_reactant5;
        elmt_cytoplasm.elmt_reactant8 = Reacs.elmt_reactant8;
        elmt_cytoplasm.elmt_vGluDH = Reacs.elmt_vGluDH;
        elmt_cytoplasm.elmt_product65 = Reacs.elmt_product65;
        elmt_cytoplasm.elmt_vPGK = Reacs.elmt_vPGK;
        elmt_cytoplasm.elmt_product21 = Reacs.elmt_product21;
        elmt_cytoplasm.elmt_reactant70 = Reacs.elmt_reactant70;
        elmt_cytoplasm.elmt_product20 = Reacs.elmt_product20;
        elmt_cytoplasm.elmt_product64 = Reacs.elmt_product64;
        elmt_cytoplasm.elmt_reactant36 = Reacs.elmt_reactant36;
        elmt_cytoplasm.elmt_reactant37 = Reacs.elmt_reactant37;
        elmt_cytoplasm.elmt_reactant32 = Reacs.elmt_reactant32;
        elmt_cytoplasm.elmt_reactant33 = Reacs.elmt_reactant33;
        elmt_cytoplasm.elmt_product4 = Reacs.elmt_product4;
        elmt_cytoplasm.elmt_reactant0 = Reacs.elmt_reactant0;
        elmt_cytoplasm.elmt_vG6PDH = Reacs.elmt_vG6PDH;
        elmt_cytoplasm.elmt_product2 = Reacs.elmt_product2;
        elmt_cytoplasm.elmt_reactant29 = Reacs.elmt_reactant29;
        elmt_cytoplasm.elmt_vPGM = Reacs.elmt_vPGM;
        elmt_cytoplasm.elmt_product59 = Reacs.elmt_product59;
        elmt_cytoplasm.elmt_product14 = Reacs.elmt_product14;
        elmt_cytoplasm.elmt_product58 = Reacs.elmt_product58;
        elmt_cytoplasm.elmt_product18 = Reacs.elmt_product18;
        elmt_cytoplasm.elmt_product17 = Reacs.elmt_product17;

end ralser;
