within BIOMD342;
class Parameters

    input Real elmt_LRC_endo;
    input Real elmt_LRC_surf;
    input Real elmt_PSmad2_Smad4_n;
    input Real elmt_PSmad2c;
    input Real elmt_PSmad2_Smad4_c;
    input Real elmt_Smad2n;
    input Real elmt_T2R_endo;
    input Real elmt_PSmad2_PSmad2_c;
    input Real elmt_T1R_surf;
    input Real elmt_PSmad2n;
    input Real elmt_T1R_endo;
    input Real elmt_TGF_beta_ex;
    input Real elmt_T2R_surf;
    input Real elmt_Vmed;
    input Real elmt_PSmad2_PSmad2_n;
    input Real elmt_Smad2c;

    Real elmt_totalNumT1R(unit = "") "";
    Real elmt_kon_Smads(unit = "mol-1.0.s-1.0") "";
    Real elmt_kdeg_T1R(unit = "s-1.0") "";
    Real elmt_kimp_Smad4(unit = "s-1.0") "";
    Real elmt_ka_LRC(unit = "mol-2.0.s-1.0") "";
    Real elmt_kimp_Smads(unit = "s-1.0") "";
    Real elmt_kimp_Smad2(unit = "s-1.0") "";
    Real elmt_kon_ns(unit = "s-1.0") "";
    Real elmt_KD_ns(unit = "") "";
    Real elmt_kdiss_LRC(unit = "s-1.0") "";
    Real elmt_koff_ns(unit = "s-1.0") "";
    Real elmt_TGF_beta_dose_mol_per_cell(unit = "") "";
    Real elmt_k_T2R(unit = ".s-1.0") "";
    Real elmt_koff_Smads(unit = "s-1.0") "";
    Real elmt_kdepho_Smad2(unit = "s-1.0") "";
    Real elmt_totalNuclearPSmad2(unit = "") "";
    Real elmt_single_pulse_duration(unit = "") "";
    Real elmt_medium_TGF_beta_amount(unit = "") "";
    Real elmt_totalNumT2R(unit = "") "";
    Real elmt_kdeg_LRC(unit = "s-1.0") "";
    Real elmt_k_T1R(unit = ".s-1.0") "";
    Real elmt_klid(unit = "s-1.0") "";
    Real elmt_totalNumLRC(unit = "") "";
    Real elmt_kpho_Smad2(unit = "mol-1.0.s-1.0") "";
    Real elmt_stimulation_type(unit = "") "";
    Real elmt_kr(unit = "s-1.0") "";
    Real elmt_kdeg_T2R(unit = "s-1.0") "";
    Real elmt_totalSmad2c(unit = "") "";
    Real elmt_kdeg_TGF_beta(unit = "s-1.0") "";
    Real elmt_totalNumPSmad2(unit = "") "";
    Real elmt_kexp_Smad4(unit = "s-1.0") "";
    Real elmt_totalSmad2n(unit = "") "";
    Real elmt_ki(unit = "s-1.0") "";
    Real elmt_kexp_Smad2(unit = "s-1.0") "";


    initial equation
        elmt_kon_Smads = 0.198472;
        elmt_kdeg_T1R = 0.00256;
        elmt_kimp_Smad4 = 0.156;
        elmt_ka_LRC = 117.897;
        elmt_kimp_Smads = 0.889;
        elmt_kimp_Smad2 = 0.156;
        elmt_kon_ns = 0.0505413;
        elmt_KD_ns = 40.2257;
        elmt_kdiss_LRC = 0.0438111;
        elmt_TGF_beta_dose_mol_per_cell = (elmt_TGF_beta_ex * 1.0E-9 * elmt_Vmed * 6.0E23);
        elmt_k_T2R = 0.0190076;
        elmt_koff_Smads = 1.0;
        elmt_kdepho_Smad2 = 0.394;
        elmt_single_pulse_duration = 0.5;
        elmt_kdeg_LRC = 0.00256;
        elmt_k_T1R = 0.0167;
        elmt_klid = 0.0233678;
        elmt_kpho_Smad2 = 0.0488268;
        elmt_stimulation_type = 1.0;
        elmt_kr = 0.0333;
        elmt_kdeg_T2R = 0.0132;
        elmt_kdeg_TGF_beta = 0.347;
        elmt_kexp_Smad4 = 0.359;
        elmt_ki = 0.333;
        elmt_kexp_Smad2 = 0.763;


    equation
        elmt_totalNumT1R = ((elmt_T1R_surf + elmt_T1R_endo + elmt_LRC_surf + elmt_LRC_endo) * 2.3 * 602.0);
        der(elmt_kon_Smads) = 0;
        der(elmt_kdeg_T1R) = 0;
        der(elmt_kimp_Smad4) = 0;
        der(elmt_ka_LRC) = 0;
        der(elmt_kimp_Smads) = 0;
        der(elmt_kimp_Smad2) = 0;
        der(elmt_kon_ns) = 0;
        der(elmt_KD_ns) = 0;
        der(elmt_kdiss_LRC) = 0;
        elmt_koff_ns = (elmt_kon_ns * elmt_KD_ns);
        der(elmt_TGF_beta_dose_mol_per_cell) = 0;
        der(elmt_k_T2R) = 0;
        der(elmt_koff_Smads) = 0;
        der(elmt_kdepho_Smad2) = 0;
        elmt_totalNuclearPSmad2 = (elmt_PSmad2n + (2.0 * elmt_PSmad2_PSmad2_n) + elmt_PSmad2_Smad4_n);
        der(elmt_single_pulse_duration) = 0;
        elmt_medium_TGF_beta_amount = (elmt_TGF_beta_ex * 1.0E-9 * elmt_Vmed * 6.0E23);
        elmt_totalNumT2R = ((elmt_T2R_surf + elmt_T2R_endo + elmt_LRC_surf + elmt_LRC_endo) * 2.3 * 602.0);
        der(elmt_kdeg_LRC) = 0;
        der(elmt_k_T1R) = 0;
        der(elmt_klid) = 0;
        elmt_totalNumLRC = ((elmt_LRC_surf + elmt_LRC_endo) * 2.3 * 602.0);
        der(elmt_kpho_Smad2) = 0;
        der(elmt_stimulation_type) = 0;
        der(elmt_kr) = 0;
        der(elmt_kdeg_T2R) = 0;
        elmt_totalSmad2c = (elmt_Smad2c + elmt_PSmad2c + (2.0 * elmt_PSmad2_PSmad2_c) + elmt_PSmad2_Smad4_c);
        der(elmt_kdeg_TGF_beta) = 0;
        elmt_totalNumPSmad2 = (((elmt_PSmad2c + (elmt_PSmad2_PSmad2_c * 2.0) + elmt_PSmad2_Smad4_c) * 2.3 * 602.0) + ((elmt_PSmad2n + (elmt_PSmad2_PSmad2_n * 2.0) + elmt_PSmad2_Smad4_n) * 602.0));
        der(elmt_kexp_Smad4) = 0;
        elmt_totalSmad2n = (elmt_Smad2n + elmt_PSmad2n + (2.0 * elmt_PSmad2_PSmad2_n) + elmt_PSmad2_Smad4_n);
        der(elmt_ki) = 0;
        der(elmt_kexp_Smad2) = 0;

end Parameters;
