within BIOMD297;
class Parameters

    input Real elmt_PSwe1M;
    input Real elmt_Mcm;
    input Real elmt_SBF;
    input Real elmt_Cdh1;
    input Real elmt_PSwe1;
    input Real elmt_Swe1;
    input Real elmt_IE;
    input Real elmt_Swe1M;
    input Real elmt_Mih1a;

    input Boolean elmt_event_0000005;    input Boolean elmt_event_0000002;    input Boolean elmt_event_0000003;
    input Real assign_elmt_flag;
    input Real assign_elmt_BUD;


    Real elmt_IEtot(unit = "") "";
    Real elmt_ksclb(unit = "") "";
    Real elmt_kdcln(unit = "") "";
    Real elmt_Swe1T(unit = "") "";
    Real elmt_Mih_ast(unit = "") "";
    Real elmt_IEin(unit = "") "";
    Real elmt_kscln(unit = "") "";
    Real elmt_Mcmtot(unit = "") "";
    Real elmt_kdswe_prime(unit = "") "";
    Real elmt_kisbf_doubleprime(unit = "") "";
    Real elmt_jimih(unit = "") "";
    Real elmt_SBFin(unit = "") "";
    Real elmt_kasbf_doubleprime(unit = "") "";
    Real elmt_kdclb_tripleprime(unit = "") "";
    Real elmt_kasbf_prime(unit = "") "";
    Real elmt_jscdc20(unit = "") "";
    Real elmt_kdcdc20(unit = "") "";
    Real elmt_Kacdh_prime(unit = "") "";
    Real elmt_kdsic_prime(unit = "") "";
    Real elmt_flag(unit = "") "";
    Real elmt_Vamih(unit = "") "";
    Real elmt_kswe(unit = "") "";
    Real elmt_kass(unit = "") "";
    Real elmt_Mih1tot(unit = "") "";
    Real elmt_kicdh(unit = "") "";
    Real elmt_jamcm(unit = "") "";
    Real elmt_kdiss(unit = "") "";
    Real elmt_BUD(unit = "") "";
    Real elmt_Viwee(unit = "") "";
    Real elmt_jimcm(unit = "") "";
    Real elmt_kamcm(unit = "") "";
    Real elmt_Vawee(unit = "") "";
    Real elmt_mu(unit = "") "";
    Real elmt_kswe_prime(unit = "") "";
    Real elmt_jacdh(unit = "") "";
    Real elmt_kimcm(unit = "") "";
    Real elmt_kssic(unit = "") "";
    Real elmt_khsl1(unit = "") "";
    Real elmt_Kacdh_doubleprime(unit = "") "";
    Real elmt_kdclb_doubleprime(unit = "") "";
    Real elmt_kscdc20_doubleprime(unit = "") "";
    Real elmt_jicdh(unit = "") "";
    Real elmt_kswe_tripleprime(unit = "") "";
    Real elmt_jacdc20(unit = "") "";
    Real elmt_Vimih(unit = "") "";
    Real elmt_kdbud(unit = "") "";
    Real elmt_jaie(unit = "") "";
    Real elmt_Mih1(unit = "") "";
    Real elmt_SBFtot(unit = "") "";
    Real elmt_jasbf(unit = "") "";
    Real elmt_Jawee(unit = "") "";
    Real elmt_jiie(unit = "") "";
    Real elmt_jisbf(unit = "") "";
    Real elmt_Jiwee(unit = "") "";
    Real elmt_Jamih(unit = "") "";
    Real elmt_kacdc20(unit = "") "";
    Real elmt_kdsic_doubleprime(unit = "") "";
    Real elmt_Cdh1in(unit = "") "";
    Real elmt_kswe_doubleprime(unit = "") "";
    Real elmt_kdsic(unit = "") "";
    Real elmt_ksbud(unit = "") "";
    Real elmt_kdclb_prime(unit = "") "";
    Real elmt_jicdc20(unit = "") "";
    Real elmt_kisbf_prime(unit = "") "";
    Real elmt_kscdc20_prime(unit = "") "";
    Real elmt_Jm(unit = "") "";
    Real elmt_kicdc20(unit = "") "";
    Real elmt_kicdh_prime(unit = "") "";
    Real elmt_kaie(unit = "") "";
    Real elmt_kssweC(unit = "") "";
    Real elmt_ksswe(unit = "") "";
    Real elmt_kdswe_doubleprime(unit = "") "";
    Real elmt_kmih_prime(unit = "") "";
    Real elmt_kiie(unit = "") "";
    Real elmt_eps(unit = "") "";
    Real elmt_kmih_doubleprime(unit = "") "";
    Real elmt_kmih(unit = "") "";
    Real elmt_Mcmin(unit = "") "";
    Real elmt_Mih(unit = "") "";
    Real elmt_Cdh1tot(unit = "") "";
    Real elmt_khsl1r(unit = "") "";


    initial equation
        elmt_IEtot = 1.0;
        elmt_ksclb = 0.015;
        elmt_kdcln = 0.1;
        elmt_Mih_ast = 0.0;
        elmt_kscln = 0.1;
        elmt_Mcmtot = 1.0;
        elmt_kdswe_prime = 0.007;
        elmt_kisbf_doubleprime = 2.0;
        elmt_jimih = 0.1;
        elmt_kasbf_doubleprime = 0.0;
        elmt_kdclb_tripleprime = 0.1;
        elmt_kasbf_prime = 1.0;
        elmt_jscdc20 = 0.3;
        elmt_kdcdc20 = 0.1;
        elmt_Kacdh_prime = 1.0;
        elmt_kdsic_prime = 1.0;
        elmt_flag = 0.0;
        elmt_Vamih = 1.0;
        elmt_kass = 300.0;
        elmt_Mih1tot = 1.0;
        elmt_kicdh = 35.0;
        elmt_jamcm = 0.1;
        elmt_kdiss = 0.1;
        elmt_BUD = 0.0;
        elmt_Viwee = 1.0;
        elmt_jimcm = 0.1;
        elmt_kamcm = 1.0;
        elmt_Vawee = 0.3;
        elmt_mu = 0.005;
        elmt_kswe_prime = 2.0;
        elmt_jacdh = 0.01;
        elmt_kimcm = 0.15;
        elmt_kssic = 0.1;
        elmt_khsl1 = 1.0;
        elmt_Kacdh_doubleprime = 10.0;
        elmt_kdclb_doubleprime = 1.0;
        elmt_kscdc20_doubleprime = 0.3;
        elmt_jicdh = 0.01;
        elmt_kswe_tripleprime = 0.2;
        elmt_jacdc20 = 0.001;
        elmt_Vimih = 0.3;
        elmt_kdbud = 0.1;
        elmt_jaie = 0.01;
        elmt_SBFtot = 1.0;
        elmt_jasbf = 0.01;
        elmt_Jawee = 0.05;
        elmt_jiie = 0.01;
        elmt_jisbf = 0.01;
        elmt_Jiwee = 0.05;
        elmt_Jamih = 0.1;
        elmt_kacdc20 = 1.0;
        elmt_kdsic_doubleprime = 3.0;
        elmt_kswe_doubleprime = 0.01;
        elmt_kdsic = 0.01;
        elmt_ksbud = 0.1;
        elmt_kdclb_prime = 0.015;
        elmt_jicdc20 = 0.001;
        elmt_kisbf_prime = 1.0;
        elmt_kscdc20_prime = 0.005;
        elmt_Jm = 10.0;
        elmt_kicdc20 = 0.25;
        elmt_kicdh_prime = 2.0;
        elmt_kaie = 0.1;
        elmt_kssweC = 0.0;
        elmt_ksswe = 0.0025;
        elmt_kdswe_doubleprime = 0.05;
        elmt_kmih_prime = 5.0;
        elmt_kiie = 0.04;
        elmt_eps = 0.5;
        elmt_kmih_doubleprime = 0.5;
        elmt_Mih = 0.0;
        elmt_Cdh1tot = 1.0;
        elmt_khsl1r = 0.01;


    equation
        der(elmt_IEtot) = 0;
        der(elmt_ksclb) = 0;
        der(elmt_kdcln) = 0;
        elmt_Swe1T = (elmt_Swe1 + elmt_Swe1M + elmt_PSwe1 + elmt_PSwe1M);
        der(elmt_Mih_ast) = 0;
        elmt_IEin = (elmt_IEtot - elmt_IE);
        der(elmt_kscln) = 0;
        der(elmt_Mcmtot) = 0;
        der(elmt_kdswe_prime) = 0;
        der(elmt_kisbf_doubleprime) = 0;
        der(elmt_jimih) = 0;
        elmt_SBFin = (elmt_SBFtot - elmt_SBF);
        der(elmt_kasbf_doubleprime) = 0;
        der(elmt_kdclb_tripleprime) = 0;
        der(elmt_kasbf_prime) = 0;
        der(elmt_jscdc20) = 0;
        der(elmt_kdcdc20) = 0;
        der(elmt_Kacdh_prime) = 0;
        der(elmt_kdsic_prime) = 0;
        der(elmt_flag) = 0.0;
        der(elmt_Vamih) = 0;
        elmt_kswe = ((elmt_kswe_prime * elmt_Swe1) + (elmt_kswe_doubleprime * elmt_Swe1M) + (elmt_kswe_tripleprime * elmt_PSwe1));
        der(elmt_kass) = 0;
        der(elmt_Mih1tot) = 0;
        der(elmt_kicdh) = 0;
        der(elmt_jamcm) = 0;
        der(elmt_kdiss) = 0;
        der(elmt_BUD) = 0.0;
        der(elmt_Viwee) = 0;
        der(elmt_jimcm) = 0;
        der(elmt_kamcm) = 0;
        der(elmt_Vawee) = 0;
        der(elmt_mu) = 0;
        der(elmt_kswe_prime) = 0;
        der(elmt_jacdh) = 0;
        der(elmt_kimcm) = 0;
        der(elmt_kssic) = 0;
        der(elmt_khsl1) = 0;
        der(elmt_Kacdh_doubleprime) = 0;
        der(elmt_kdclb_doubleprime) = 0;
        der(elmt_kscdc20_doubleprime) = 0;
        der(elmt_jicdh) = 0;
        der(elmt_kswe_tripleprime) = 0;
        der(elmt_jacdc20) = 0;
        der(elmt_Vimih) = 0;
        der(elmt_kdbud) = 0;
        der(elmt_jaie) = 0;
        elmt_Mih1 = (elmt_Mih1tot - elmt_Mih1a);
        der(elmt_SBFtot) = 0;
        der(elmt_jasbf) = 0;
        der(elmt_Jawee) = 0;
        der(elmt_jiie) = 0;
        der(elmt_jisbf) = 0;
        der(elmt_Jiwee) = 0;
        der(elmt_Jamih) = 0;
        der(elmt_kacdc20) = 0;
        der(elmt_kdsic_doubleprime) = 0;
        elmt_Cdh1in = (elmt_Cdh1tot - elmt_Cdh1);
        der(elmt_kswe_doubleprime) = 0;
        der(elmt_kdsic) = 0;
        der(elmt_ksbud) = 0;
        der(elmt_kdclb_prime) = 0;
        der(elmt_jicdc20) = 0;
        der(elmt_kisbf_prime) = 0;
        der(elmt_kscdc20_prime) = 0;
        der(elmt_Jm) = 0;
        der(elmt_kicdc20) = 0;
        der(elmt_kicdh_prime) = 0;
        der(elmt_kaie) = 0;
        der(elmt_kssweC) = 0;
        der(elmt_ksswe) = 0;
        der(elmt_kdswe_doubleprime) = 0;
        der(elmt_kmih_prime) = 0;
        der(elmt_kiie) = 0;
        der(elmt_eps) = 0;
        der(elmt_kmih_doubleprime) = 0;
        elmt_kmih = ((elmt_kmih_prime * elmt_Mih_ast) + (elmt_kmih_doubleprime * elmt_Mih));
        elmt_Mcmin = (elmt_Mcmtot - elmt_Mcm);
        der(elmt_Mih) = 0;
        der(elmt_Cdh1tot) = 0;
        der(elmt_khsl1r) = 0;

        when elmt_event_0000005 then
            reinit(elmt_BUD, assign_elmt_BUD);
        end when;
        when elmt_event_0000002 then
            reinit(elmt_flag, assign_elmt_flag);
        end when;
        when elmt_event_0000003 then
            reinit(elmt_BUD, assign_elmt_BUD);
        end when;
end Parameters;
